### ISSUE TITLE
[Server thread/ERROR] [Sponge]: Could not pass DestructEntityEvent$Death$Impl to Plugin{id=walletdrop 

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/Sponge#1002]
[http://pastebin.com/WHD1M7yD](http://pastebin.com/WHD1M7yD)

> > trentech commented 12 hours ago
> > This is an implementation issue in Sponge, when checking if a Zombie is a baby.

latest api5

**Comment by gabizou** [comment]
You're requesting `AgeableData` when there is none available. Refer to #8.
