### ISSUE TITLE
EntitySnapshot toContainer NullPointerException

### ISSUE THREAD

**Issue by trentech** [SpongePowered/Sponge#1003]
SpongeForge 1.10.2-2107-6.0.0-BETA-1844

http://pastebin.com/t8W8kMC7

This only happens when using the EntitySnapshot Builder

**Comment by windy1** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/7dd9c916f42c5da5e484d9e62956c68434effa1c#diff-d22b05657e065a1afc570ae52da1b621R119
