### ISSUE TITLE
Setting RepresentedPlayerData on a Skull ItemStack does not set the skin.

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Sponge#1013]
The following code is the test case. It sets the Owner tag on the Skull, but it doesn't set the skin. The default skin is still used.

```
SkullData data = Sponge.getGame().getDataManager().getManipulatorBuilder(SkullData.class).get().create();
data.set(Keys.SKULL_TYPE, SkullTypes.PLAYER);
ItemStack stack = Sponge.getGame().getRegistry().createBuilder(ItemStack.Builder.class).itemType(ItemTypes.SKULL).itemData(data).build();
RepresentedPlayerData skinData = Sponge.getGame().getDataManager().getManipulatorBuilder(RepresentedPlayerData.class).get().create();
skinData.set(Keys.REPRESENTED_PLAYER, GameProfile.of(UUID.fromString("4c38ed11-596a-4fd4-ab1d-26f386c1cbac"), "MHF_Blaze"));
stack.offer(skinData);
```

**Comment by ZephireNZ** [comment]
This is likely because the skin shown is via the skin property blob, not the UUID. Further more the blob has to be signed by Mojang's servers (if I remember correctly), so you can't just create the ProfileProperty yourself.

**Comment by me4502** [comment]
The profile I'm providing has the skin I want, how should I be applying it?

**Comment by kashike** [comment]
@me4502 has provided a `toContainer` of the stack:
`[16:58:41] [Server thread/INFO] [STDOUT]: [com.sk89q.craftbook.sponge.mechanics.HeadDrops:onItemDrops:109]: MemoryDataContainer{safety=ALL_DATA_CLONED, map={ContentVersion=1, ItemType=minecraft:skull, Count=1, UnsafeDamage=3, UnsafeData=MemoryDataView{path=UnsafeData, safety=ALL_DATA_CLONED, map={SkullOwner=MemoryDataView{path=UnsafeData.SkullOwner, safety=ALL_DATA_CLONED, map={Id=18a2bb50-334a-4084-9184-2c380251a24b, Name=MHF_PigZombie}}, display=MemoryDataView{path=UnsafeData.display, safety=ALL_DATA_CLONED, map={Name=Pigzombie Head}}}}, Data=[MemoryDataContainer{safety=ALL_DATA_CLONED, map={DataClass=org.spongepowered.common.data.manipulator.mutable.SpongeDisplayNameData, ManipulatorData=MemoryDataView{path=ManipulatorData, safety=ALL_DATA_CLONED, map={ContentVersion=1, DisplayName={"extra":[{"text":"Pigzombie Head"}],"text":""}}}}}]}}`

**Comment by kashike** [comment]
As far as I can tell, from code and the `toContainer` above, the `SkullOwner` tag is being set correctly, so it's some other issue such as the stack losing the `SkullOwner` tag during send, or the client having some sort of issue.

**Comment by me4502** [comment]
It appears this only happens when behind BungeeCord, or when in Offline mode.

**Comment by vectrixdevelops** [comment]
I've noticed adding the NBT data to the item in game via command only loads the skin if the player was online when the skull was created. Not running bungeecord. On SpongeVanilla.

Edit: Not sure if this is connecting or a whole other issue.
