### ISSUE TITLE
No InteractItemEvent.Primary.MainHand for left clicking a block with an empty hand

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/Sponge#1016]
Currently we only throw an `InteractBlockEvent.Primary.MainHand` for this action with no preceding `InteractItemEvent.Primary.MainHand`. When I right click there is an `InteractItemEvent.Secondary.MainHand` thrown as I would expect.

~~There are also currently no events thrown at all when I right click while looking at the sky and not holding an item but I can't remember if this is a case where we receive no packets from the client.~~

**Comment by Zidane** [comment]
Unfortunately client doesn't send anything if you right click air with no item in hand.

**Comment by Deamon5550** [comment]
@Zidane yeah I figured, what a pity.
