### ISSUE TITLE
Trying to create a player's inventory throws a NPE

### ISSUE THREAD

**Issue by Maxqia** [SpongePowered/Sponge#1017]
When I use [this](http://pastebin.com/7abXvaUZ) code to try and create and display a player's inventory, it throws a NPE. Log : http://pastebin.com/EWa9vhui

**Comment by Faithcaio** [comment]
I might be able to fix the problem when building the inventory.
But displaying will not be possible as mentioned in the comment on the Archetype.

Try using `InventoryArchetypes.CHEST` instead.
