### ISSUE TITLE
Implement World Creation

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/Sponge#102]
The API is fairly complete for worlds, so the implementation needs to start on this.

Worlds is a fairly complex thing to implement given that it has a lot of extensibility and we aim for full compatibility with forge mods. Since world creation and manipulation in forge is based around the concept of dimensions instead of worlds, we need to figure out what system we want to use for Sponge's implementation.

Currently I see two main options:

1. The original minecraft system where worlds are levels and what SpongeAPI calls Worlds are referred to as dimensions, with only one level.dat file and session.lock for an entire set of dimensions

2. We use a Bukkit style system where each World is split into a seperate level folder with it's own level.dat and session.lock files. Each world folder only stores a single dimension and the folder as a whole makes up the entirety of a World.

One posibility is an extension of 2 where those seperate world folders are expanded into another concept, allowing multiple World's (Dimensions) per Universe (Level), a sort of combination of 1 and 2.

**Comment by simon816** [comment]
FWIW [This Document](https://docs.google.com/document/d/1LXBVACwT30n9VJxVXoYW_2Oor7iSJEK248BiXhWLpzk), created back when Sponge first started, suggests worlds should be stored in a folder structure like
```
./maps/
    /world/
    /DIM-1/
    /DIM-2/
    /other-world/
```
Etc.
So worlds are stored per dimention

**Comment by ryantheleach** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/1621

**Comment by Zidane** [comment]
@bloodmc is almost finished with this.

**Comment by bloodmc** [comment]
Fixed in https://github.com/SpongePowered/Sponge/commit/55175a11f7327a42c20f6f1f9e20307c4ca3058e
