### ISSUE TITLE
Extending `AbstractEvent`

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#1024]
I created an event in my plugin: [`CurrentEditorScrolledEvent`](https://github.com/randombyte-developer/free-blocks/blob/8e4af57a1c5bd4e095008737bc7ae5d2ede01952/src/main/kotlin/de/randombyte/freeblocks/CurrentEditorScrolledEvent.kt)

I updated SpongeVanilla to test the plugin again and I see that the custom event that is fired needs to extend `AbstractEvent` because of [this](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/SpongeEventManager.java#L304).
Is this intended? As you can see, I just extend from that event and everything seems to be ok.

**Comment by kashike** [comment]
According to @Aaron1011 it is intended, and won't be fixed.

**Comment by Aaron1011** [comment]
I'll make it more clear in the javadocs and in SpongeDocs that custom events need to extend `AbstractEvent`.
