### ISSUE TITLE
ItemStack display names don't preserve colors properly

### ISSUE THREAD

**Issue by Limeth** [SpongePowered/Sponge#1028]
```java
Text text = Text.builder().color(TextColors.RESET).append(Text.of("test")).build();
itemStack.offer(Keys.DISPLAY_NAME, text);
System.out.println(itemStack.get(Keys.DISPLAY_NAME).get().getColor());  // prints `NONE`, should print `reset`
```

**Comment by kashike** [comment]
Are you sure it isn't applied to a child of the `Text`?

**Comment by ST-DDT** [comment]
The color `RESET` is not preserved, since `RESET` cleans the previous color information.
Every other color is kept as it. If this behavious is wrong then its only the Text ApI that is lacking here. Although IMO it works as expected.

**Comment by kashike** [comment]
The `RESET` colour should be retained.
