### ISSUE TITLE
Cancelling a Piston Move Event doesn't work

### ISSUE THREAD

**Issue by Maxqia** [SpongePowered/Sponge#1029]
When canceling a piston move event, It breaks the piston and/or leaves duplicate blocks everywhere.
Code Sample : http://pastebin.com/MZbmvvNj
Stack Trace on the Item Spawned : http://pastebin.com/q9rub4tu

**Comment by Maxqia** [comment]
I think it's a problem with SpongeBlockSnapshot not removing the tile entity when restoring by doing TileEntityPiston.clearPistonTileEntity()

**Comment by bloodmc** [comment]
I'm currently looking into this.
