### ISSUE TITLE
[1.10.2-1.11] Doesn't drop loot from the mobs

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/Sponge#1035]
Doesn't drop loot from the mobs. Experience falls.
```
forge-1.11-13.19.0.2157-universal.jar
spongeforge-1.11-2157-6.0.0-BETA-1906.jar
```
Other mods is not installed. If remove the sponge, then drops! 
Probably has value: http://pastebin.com/35EgpNR5

**Comment by Maxqia** [comment]
Confirmed!

**Comment by bloodmc** [comment]
Latest 1.10.2 (5.1.0) build works fine. This issue is only present in 1.11

**Comment by ziceptor** [comment]
Doesn't drop loot from the mobs.
`spongeforge-1.10.2-2123-5.1.0-BETA-1911.jar`

**Comment by bloodmc** [comment]
@ziceptor Loot definitely drops from mobs in 1.10.2. Remove all your plugins/mods and retest.

**Comment by ziceptor** [comment]
@bloodmc @Maxqia Sorry for bad English.
Deleting plugins doesn't help. I found that with new world loot drops. I installed only the plugins for the sponge. Some plugin broke the world. Perhaps the issue is worth exploring!
Logs https://cloud.mail.ru/public/5pXz/k1S1D3aaQ
Configs https://cloud.mail.ru/public/LQAj/pDPTAEmri

Thank you for your patience!

**Comment by Maxqia** [comment]
Do you have the gamerule doEntityDrops/doMobLoot disabled? Sponge stores gamerules differently so it might not transfer them to vanilla minecraft.

**Comment by ziceptor** [comment]
@Maxqia You are right! doMobLoot disabled! Thank you!
