### ISSUE TITLE
DropItemEvent.Pre not firing in all vanilla cases.

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#1037]
While doing some testing I've discovered that [`DropItemEvent.Pre`](https://jd.spongepowered.org/5.0.0/org/spongepowered/api/event/item/inventory/DropItemEvent.Pre.html) is not correctly firing for certain actions. So far it does not fire for:

- [x] The Items dropped when an Entity is killed

- [ ] The Items dropped when a Dispenser is triggered

- [x] Items dropped by the Player from their inventories

I've also discovered that [`DropItemEvent`](https://jd.spongepowered.org/5.0.0/org/spongepowered/api/event/item/inventory/DropItemEvent.html) isn't firing for dispensers either.

This was all tested on SpongeVanilla 1.10.2-5.1.0-BETA-359

**Comment by ImMorpheus** [comment]
Able to reproduce with 1.12 (bleeding branch):

`The Items dropped when a Dispenser is triggered`

Fixed:
```
The Items dropped when an Entity is killed
Items dropped by the Player from their inventories
```

**Comment by ryantheleach** [comment]
Thanks for the updated info @ImMorpheus
