### ISSUE TITLE
DamageEntityEvent caused by EnderPearl hitting entity does not contain EnderPearl in the cause. 

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Sponge#1041]
When an EnderPearl hits an entity, it causes damage, which fires the DamageEntityEvent. However, the EnderPearl is not in the cause.

Test code, this outputs null.

```
    @Listener
    public void onDamage(DamageEntityEvent event) {
        System.out.println(event.getCause().first(EnderPearl.class).orElse(null));
    }
```

Tested in both 1.10.2 and 1.11

**Comment by ImMorpheus** [comment]
Tested in 1.12 (bleeding branch).

```
[STDOUT]: EntityEnderPearl['entity.ThrownEnderpearl.name'/370, l='world', x=220.73, y=72.07, z=298.81]
[STDOUT]: EntityEnderPearl['entity.ThrownEnderpearl.name'/370, l='world', x=220.73, y=72.07, z=298.81]
```

Note: the event is called twice. It could be related to #1447, but this specific issue is fixed in the latest version.
