### ISSUE TITLE
LocaleCache error

### ISSUE THREAD

**Issue by Wundero** [SpongePowered/Sponge#1042]
In the latest build of SpongeVanilla, I tried joining using the locale "lol_us", and I get this error:
http://pastebin.com/vTmcY18c
After looking through the code, it seems to be that the default Java locale implementation does not include such languages as lolcats and pirate speak. Perhaps some kind of catcher for minecraft locales could be implemented?
(Note: this error occurred on join)

**Comment by JBYoshi** [comment]
I think it's just for lol speak. Java expects all locales to be in the format `xx_XX`. `lol` has too many characters for Java to allow.

**Comment by Wundero** [comment]
That makes sense. It likely should have it's own special case then, unless a better way can be found to fix that.

**Comment by simon816** [comment]
I found out that you can put anything in the `lang` option in the client's `options.txt` and it will blindly send it to the server. For example `lang:something_unknown` and it will throw the same exception on the server.

Perhaps there should be a sanity check and use a default if it fails

**Comment by Wundero** [comment]
True, however I think that, given the language lol_US is a legitimate translation on the client side, there should be note of it somehow. Another thing to consider is that this error was not present in Sponge API 5 (I was using SpongeVanilla in both cases for the test, with only one plugin installed on my test environment), however it is now present in API 6.
