### ISSUE TITLE
Inventory#parent returns null if no parent

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#1049]
Despite its JavaDoc specifying that `Inventory#parent` should return itself if it has no parent, it instead returns `null`.

**Comment by Faithcaio** [comment]
@caseif is this still happening?

**Comment by caseif** [comment]
It looks to have been fixed by 8d8eb4b2c6200d6bfe4ba53675a498063020eed8 - I'll test it later today when I get a chance just to be certain.

**Comment by caseif** [comment]
The bug is resolved in `bleeding`.
