### ISSUE TITLE
Inventory.offer(ItemStack) not adding item to inventory

### ISSUE THREAD

**Issue by Maxqia** [SpongePowered/Sponge#1050]
When I offer an item to a chest/player inventory on 1.11, it doesn't add the ItemStack to the inventory.

**Comment by Faithcaio** [comment]
I probably fixed it in this branch, but did not have time to test it yet.
https://github.com/SpongePowered/SpongeCommon/tree/fix/itemstack-null

**Comment by Maxqia** [comment]
Do you have a PR for that? (If not, can I make one including my fixes)

**Comment by Faithcaio** [comment]
There is no PR yet.
Go for it.

**Comment by mcmonkey4eva** [comment]
Can confirm this - also it actually successfully gives if you have the item already.
Meaning, if you have one blaze rod gotten naturally, then offer a new blaze rod, you'll accurately have two blaze rods.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/982dffaa80d39fb23ed8f958990a7d25113a081a
