### ISSUE TITLE
Shields doesn't protect you

### ISSUE THREAD

**Issue by Rolphoe** [SpongePowered/Sponge#1061]
Hello, I've been told to open this issue here. I was playing on  my server and was using a shield to protect from skeletons or creepers. The hurt sound doesn't play, but I still receive the damage. Can you fix this?

**Comment by Aaron1011** [comment]
@Rolphoe: I'll be pushing a fix to this today along with some other improvements related to shield damage in the API.

**Comment by Rolphoe** [comment]
Ok thx

**Comment by liach** [comment]
Is this fixed?
