### ISSUE TITLE
Plugin/Config folder enviroments

### ISSUE THREAD

**Issue by thomas15v** [SpongePowered/Sponge#1062]
This is more an enhancement idea that I think will be really useful if you run a bungee network where the server nodes have a lot of common configuration/plugins.

Basically instead defining the plugin and config folder statistically. I would like to have an array of possibly plugins and config locations. Like this

```python
[{
        #plugins that all game servers have in common
	"pluginDir": ".../.../common/plugins",
	"configDir": ".../.../common/pluginConfig"
}, {
        #plugins that all infinite lite servers have in common
	"pluginDir": ".../.../infinitylite1.10/plugins",
	"configDir": ".../.../infinitylite1.10/pluginConfig"
}, {
        #plugins that this server specifically needs. 
	"pluginDir": "plugins",
	"configDir": "pluginConfig"
}]
```

**Comment by Maxqia** [comment]
Doesn't the Sponge Config already have a config for plugin/config dir?

-- snip --
```
    general {
        # The directory for Sponge plugin configurations, relative to the
        # execution root or specified as an absolute path.
        # Note that the default: "${CANONICAL_GAME_DIR}/config"
        # is going to use the "plugins" directory in the root game directory.
        # If you wish for plugin configs to reside within a child of the configuration
        # directory, change the value to, for example, "${CANONICAL_CONFIG_DIR}/sponge/plugins".
        # Note: It is not recommended to set this to "${CANONICAL_CONFIG_DIR}/sponge", as there is
        # a possibility that plugin configurations can conflict the Sponge core configurations.
        config-dir="${CANONICAL_GAME_DIR}/config"
        # Disable warning messages to server admins
        disable-warnings=false
        # Additional directory to search for plugins, relative to the
        # execution root or specified as an absolute path.
        # Note that the default: "${CANONICAL_MODS_DIR}/plugins"
        # is going to search for a plugins folder in the mods directory.
        # If you wish for the plugins folder to reside in the root game
        # directory, change the value to "${CANONICAL_GAME_DIR}/plugins".
        plugins-dir="${CANONICAL_MODS_DIR}/plugins"
    }
```
-- snip --
Also couldn't you just symlink the configs?

**Comment by Deamon5550** [comment]
Symlinking does seem to be the most logical option. I don't see any use for this not covered by a few symlinks.

**Comment by kashike** [comment]
Not to mention it would extremely hard, if not impossible, to support more than one default plugin configuration directory.

**Comment by thomas15v** [comment]
@Deamon5550 You can't symlink if the servers have some slight modifications between them. And symlinking plugins separately is a pain. I tried it before, and its even harder than copying plugins separately to each server.
@kashike Couldn't you just pass a the config directory to each plugin?

**Comment by kashike** [comment]
No, that's not how it works.

**Comment by Maxqia** [comment]
Why symlink them seperately?

cp -rs file1 file2
-r recursive
-s symlink

**Comment by ryantheleach** [comment]
@kashike I think it's possible, given the structure they specified. Would we be willing to pull it if someone made a PR, or accept this issue if someone else was willing to code it after the team accepting a strawman proposal?

@Yeregorix I noticed you thumbs'd up this, what are your thoughts? Would you and @thomas15v be willing to sort out the details / PR if the team accepts?

This issue has been frozen for too long, I want it to start moving, whether it's towards a PR later this year when the current temporary feature freeze is over, or a hard no from the team.

**Comment by dualspiral** [comment]
I see no reason for us to do this when it would likely be less work for an owner to symlink configs than to configure any implementation, which would be then be another source of issues we would get from owners who change things without knowing what it does, taking valuable time up. We would also have to maintain such a system for a handful of servers. 

I think this should be be no. We don’t need to reinvent the wheel on this one.

**Comment by thomas15v** [comment]
@dualspiral the only way to do this is symlink plugin configurations/jars separately, what is more work to maintain that what I am proposing.

With symlinking you do this:
1. drop jar in the common plugin folder
2. rename the plugin without the version in the name (annoying because you can't see the version than)
3. google how to do `find -exec` again.
4. The command to symlink the plugin jar on each server
5. Restart servers
6. forgot to symlink the configuration folder
7. delete all the wrongly generated folders on 13+ servers
8. Symlink the configuration folder
9. Restart servers

With what I am proposing you do this:
1. drop jar in the common plugin folder
2. Restart servers

**Comment by dualspiral** [comment]
There are plenty of other, better solutions. Having plugins accessed by more than one instance might seem safe, but if you update the directory and forget to restart a server you might find a server explode over the console and stop functioning correctly as it can’t suddenly classload the class it hadn’t used yet. There might be file locking issues. All things that would be the server owners fault, but I guarantee that someone would blame Sponge or a plugin dev.

Use rsync. Have plugins in a repo you update from. Add once, one other manual step to complete. This is a server management issue and doing it this way decouples the need to shut down all servers to deploy a new version of a plugin. You could update the server script to pull the latest versions of the common plugins directory and make this more automated without some horrible config in Sponge that will get largely ignored by 99.5% of the user base and ignored by the Sponge volunteers.

This is a relatively invasive change that would benefit a few and I’m sure will cause more problems than it’s worth for the many who get confused by such a config and raise issues when they break it.

**Comment by thomas15v** [comment]
I agree that the change is a bit breaking. The config file needs to get migrated and it might annoy more people. I am not doing servers anymore, but if I were I would just make docker images and do something like this:

```Dockerfile
FROM java:alpine

COPY common_plugins /plugins
# othercode...
```

```Dockerfile
FROM docker.minecraftserver.com/common:latest

COPY individual_plugins /tmp/plugins
RUN mv /tmp/plugins/*.jar /plugins
```

But the thing is not every minecraft server owner out there is a Linux guru with a beard. Rsync, Docker and symlinks are pretty powerfully tools. But they add a lot of complexity that is a bit hard for the majority of the people that play/host minecraft. If I were still 17 years old and trying to setup/manage minecraft networks, I would be really glad to find this feature in the documentation of sponge.

**Comment by ryantheleach** [comment]
If you arn't even needing your own issue anymore, as well as the comments that dual made about file locking make this open and shut in my mind. I blanked and forgot that a lot of plugin configs are read/write not just read.
