### ISSUE TITLE
Slot#peek() returns an ItemStack of type (minecraft:air)

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#1065]
`Slot#peek()` returns an `ItemStack` of type `(minecraft:air)` when the slot is empty but in the API we don't have `ItemTypes.AIR`, we only have `ItemTypes.NONE` and it's =/= at runtime. Either the method musts return `ItemTypes.NONE` instead of `(minecraft:air)`, either we must add `ItemTypes.AIR` in the API (instead of `ItemTypes.NONE`?)

**Comment by Faithcaio** [comment]
I'll change the method to return an empty Optional for now when there is an Air Item.
We can change the API later if we want to return the actual empty Air Itemstack
