### ISSUE TITLE
MixinWorldInfo#ensureLevelnameMatchesDirectory sets levelName to null before save, causing crash.

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Sponge#1078]
http://pastebin.com/jamC1dr5

Through testing I've found that ensureLevelNameMatchesDirectory is setting `this.levelName` to null, right before a save.

**Comment by Deamon5550** [comment]
That error doesn't actually mean empty strings but rather that the string passed in was null.

**Comment by me4502** [comment]
Ah, just assumed it was that one as when I checked the level.dat it was the only empty string. Any idea on the cause? Trying to look into fixing it.
