### ISSUE TITLE
Inventory#contains() and similar not implemented

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/Sponge#1083]
Trying to check if an Inventory contains a certain item type or item stack returns a static "false". This is a really, really useful feature that needs to be implemented.

**Comment by codeHusky** [comment]
@Faithcaio thank you omg

**Comment by Faithcaio** [comment]
I hope you dont need "exact" contains which checks for the stack size too. That might only come after an API change.

**Comment by codeHusky** [comment]
That would be nice, but this will work for now. I'm not sure why I even needed contain ATM but I'll figure it out.

**Comment by Faithcaio** [comment]
Well with a contains WITH amount you could check if a player has at least x of an item.
You can still do that now by comparing: `inventory.query(stack).totalItems()`

This one only checks if you have any amount of given ItemStack
