### ISSUE TITLE
Calling `ChangeBlockEvent`s affects the world

### ISSUE THREAD

**Issue by Limeth** [SpongePowered/Sponge#1088]
If I implement the `ChangeBlockEvent.Place` and send it to the event manager using `EventManager#post(Event)`, the block is placed after the event is processed, if the method didn't return `true` (didn't get cancelled).
I want to change the place sound to something else, but I can't remove the sound caused by the automatic placement of the block.

I may have figured out one workaround:
Instead of using the `BlockSnapshot`, which I'd like to place, in the event, I could use the `BlockSnapshot` of the `BlockSoundGroup` I would want to use. Then, I could change the type manually if the event wasn't cancelled.
The disadvantage is, that other plugins listening to that event will receive an incorrect block type, not reflecting the actual final result.

**Comment by JBYoshi** [comment]
I can't reproduce this. Could you post your code and the versions of Sponge and (if applicable) Forge?

**Comment by Limeth** [comment]
I found out it was entirely my fault, I must've got lost in my code when I sent this issue. Please, forgive me for wasting your time. :blush: 
[Derp](https://github.com/Limeth/CustomItemLibrary/commit/48c6092a34424c15672b5be292346e022d10d83d).
