### ISSUE TITLE
`Location#setBlockType` does not trigger a block update

### ISSUE THREAD

**Issue by Limeth** [SpongePowered/Sponge#1091]
When I use the following line of code on a block surrounded by water, the water doesn't update.
`location.setBlockType(BlockTypes.AIR, BlockChangeFlag.ALL, cause);`

Version:
`forge-1.11-13.19.1.2195-universal.jar`
`spongeforge-1.11-2195-6.0.0-BETA-2004.jar`

**Comment by me4502** [comment]
Potentially related to https://github.com/SpongePowered/SpongeCommon/issues/1054

**Comment by gabizou** [comment]
Yes, related entirely to #1054.
