### ISSUE TITLE
ChangeBlockEvent.Break cancelling issues

### ISSUE THREAD

**Issue by vectrixdevelops** [SpongePowered/Sponge#1098]
If you break a block, which a sign is hanging off. Cancelling the sign break event does not stop the sign item from dropping. Instead the sign is dropped along with the event for the block broken behind it. I do not think this is intended.

**Comment by liach** [comment]
You probably should subscribe to `org.spongepowered.api.event.block.ChangeBlockEvent`.

**Comment by vectrixdevelops** [comment]
Whoops that is what I meant yeah.

**Comment by liach** [comment]
You should try to listen to the outer class event but not the subclass one.

**Comment by vectrixdevelops** [comment]
I have. It still does the same thing.

**Comment by ImMorpheus** [comment]
Not able to reproduce with 1.12 (bleeding branch). The sign remains in mid-air.

For reference, listening to ChangeBlockEvent.Break is enough:

```
    @Listener
    public void onBlockBreak(ChangeBlockEvent.Break e, @Root Player player) {
        for (Transaction<BlockSnapshot> a : e.getTransactions()) {
            if (a.getOriginal().getState().getType().equals(BlockTypes.WALL_SIGN)) {
                e.setCancelled(true);
            }
        }
    }
```
