### ISSUE TITLE
Wrong block type in ChangeBlockEvent.Break

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/Sponge#1099]
Tested this in SpongeVanilla 1.11-6.0.0-BETA-190.

When a player breaks a block (or some other cause) the transaction contains a block state that has the block type `BlockTypes.AIR`. This happens regardless of which type the actual broken block has.

**Comment by vectrixdevelops** [comment]
Even for the original transaction?

**Comment by me4502** [comment]
Could you please provide some test code for this? Also, ensure that you're using getOriginal, rather than getFinal or getCustom

**Comment by TheRaspPie** [comment]
Ok, this is really embarrassing.
I was using getFinal instead of getOriginal. I really don't know how I missed that.
Thanks for your quick help anyway.
