### ISSUE TITLE
Starting a server without a DataManipulator present corrupts all TileEntities that had the data attached.

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Sponge#1100]
I accidentally started up my CraftBook test server earlier today without the plugin injected into the classpath - this of course caused all of the data to disappear. However, when I started it up again with the plugin, all of the signs that had the data attached are corrupted.

This is what they look like ingame, http://imgur.com/tE6HySD
There are no errors beyond the initial ones from the data manipulator being missing on the first startup without the plugin.

I believe that instead of the entire tileentity becoming corrupt, it should just not deserialize the data and keep it as is.

**Comment by gabizou** [comment]
Superseded by https://github.com/SpongePowered/SpongeCommon/issues/1102
