### ISSUE TITLE
Custom Inventory issue

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#1105]
I created a custom `Inventory` with archetype `MENU_GRID`, I filled the inventory with random items, every time I click on an item, all items disappear except the clicked one.
I remember having seen a similar issue in past but I can't find it anymore.
The server is a recent clone of SpongeForge/bleeding and there is no error in the log. Also, I'm cancelling any `ClickInventoryEvent.Primary` of the specified inventory.

**Comment by Faithcaio** [comment]
Could you provide your code (Inventory creation + Listener) please?

**Comment by Yeregorix** [comment]
http://pastebin.com/G867HwNq
http://pastebin.com/RVNgjNZS
http://pastebin.com/2qjHwW3H
http://pastebin.com/w3a9entG
These sources are part of a pretty big plugin, if you need some details just ask

**Comment by Faithcaio** [comment]
ok... so the ClickInventoryEvent has around 300-400 Transactions in it.
It seems the inventory changes made in the repeating task are attributed to the player. (accumulated via `MixinContainer#detectAndSendChanges`)
When canceling the event all of those transactions get reset.
@bloodmc @gabizou

**Comment by Yeregorix** [comment]
This large number of transactions is only related to the item being clicked, or to the fact that the inventory is filled with many items randomly?

**Comment by Faithcaio** [comment]
Its the random items. But imo they should not be part of the Event.
On ClickInventoryPrimary there should be a single SlotTransaction.

**Comment by Yeregorix** [comment]
Would calling `detectAndSendChanges()` (without capturing transactions) before the `CPacketClickWindow` and `detectAndSendChanges()` (capturing transactions) after the `CPacketClickWindow` fix the issue? It would separate plugins's transactions and players's transactions

**Comment by joeyasselin** [comment]
@Yeregorix One thing you can do until the issue is fixed is filter out the transactions from the event yourself. If you remove them from the event.getTransactions() list I found that I was able to prevent items from reappearing/disappearing when I cancelled the event.

**Comment by Yeregorix** [comment]
The idea is good but I don't see how to differentiate plugins's transactions and player's transactions.

**Comment by kashike** [comment]
@Yeregorix The pastebin links you provided are no longer valid. Is it possible to get new links?

**Comment by gabizou** [comment]
I think @bloodmc already had fixed this a little while ago, not sure as to when but I do remember that the commit did involve calling the necessary methods to end capturing.

**Comment by Yeregorix** [comment]
I can try to generate new pastebins if it's really needed but it seems that the issue was fixed in my case. Should I close this issue ?
