### ISSUE TITLE
Custom event fails to cast to AbstractEvent

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Sponge#1107]
SpongeVersion: SpongeVanilla: 1.11.2-6.0.0-BETA-192

We are trying to post a custom event, but for some reason we get this problem where the event(which implements Event and Cancellable) fails to cast to AbstractEvent. 

The custom event: https://github.com/IchorPowered/Latch/blob/master/src/main/java/com/meronat/latch/events/LockCreateEvent.java

The class we post the event from:
https://github.com/IchorPowered/Latch/blob/master/src/main/java/com/meronat/latch/interactions/CreateLockInteraction.java#L102

The stack trace:
![image](https://cloud.githubusercontent.com/assets/18372958/21555958/7a9cc454-cde2-11e6-8e8e-b4752e943a6d.png)

**Comment by Deamon5550** [comment]
Duplicate #1024 Custom events need to extend `AbstractEvent`.
