### ISSUE TITLE
Data inconsistency: player data and world save

### ISSUE THREAD

**Issue by Slind14** [SpongePowered/Sponge#1108]
When using
```
        auto-player-save-interval=0
        auto-save-interval=0
```
and doing the save manually via. /save-all command the world and player data gets out of sync on shutdown (crash, out of mem..).

We are running the saves our self as we want the distance between saves to be in real time (to match the players experience of time) and so we can delay saves while backups are in progress to avoid corruption and inconsistency of backups.

**Comment by ryantheleach** [comment]
Do you know what version of Sponge you were testing on / is it reproducible still on the latest stable and bleeding? 

Was the config set in the global config?

I've added this to my Todo list to do some preliminary testing this weekend, but I'm not sure that I'm going to be able to come up with a valid testing strategy without more information about how I can tell if they are out of sync.

**Comment by Slind14** [comment]
1. configure as described above
2. load world, run manual save once
3. do some stuff with the world and your inventory 
4. run manual save
5. kill the server

-> the inventory will have a different state than the world.

**Comment by ryantheleach** [comment]
Thanks for the prompt reply. Any idea if this is still reproducible or the versions last tested with?

**Comment by Slind14** [comment]
Unfortunately, I don't (been a year), but it is straight forward to reproduce.
It was a 1.10 version from around the time of the issue (probably latest) with forge and is probably still an issue.

**Comment by ImMorpheus** [comment]
>     configure as described above
>     load world, run manual save once
>     do some stuff with the world and your inventory
>     run manual save
>     kill the server

Not able to reproduce with 1.12 (bleeding branch)

**Comment by ryantheleach** [comment]
@ImMorpheus Thanks.
