### ISSUE TITLE
Player#getOpenInventory().get().first() causes NullPointerException

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#1111]
The gist of it is that calling `player.getOpenInventory().get(),first()` can cause a `NullPointerException` to be thrown within Sponge. This is due to `InventoryAdapter#getRootLens()` returning `null` somehow. Stack trace is below.

https://gist.github.com/caseif/957eb9c66d9fc7732ad86781f96c0815

Replicated on SpongeForge #2010 with Forge #2171.

**Edit:** This seems to occur consistently when the open inventory is a workbench.

**Comment by Faithcaio** [comment]
This happens because there is no fallback lens for containers when the lens is not provided.
This will be fixed with https://github.com/SpongePowered/SpongeCommon/pull/1010

also duplicate to https://github.com/SpongePowered/SpongeCommon/issues/1082
