### ISSUE TITLE
Exception Exiting Phase 

### ISSUE THREAD

**Issue by AshmitOld** [SpongePowered/Sponge#1112]
This happens randomly in console
http://pastebin.com/DbJLBfDh
its upside down
not sure sure if this is the right section but thought i should just inform
sorry if this is nothing important

**Comment by Aaron1011** [comment]
Can you pastebin your full `fml-server-latest.log`?

**Comment by AshmitOld** [comment]
tried but 
![image](https://cloud.githubusercontent.com/assets/24188806/21582906/f327c2e4-d08e-11e6-9f2a-016e222cf87a.png)

**Comment by JBYoshi** [comment]
You can try https://gist.github.com. I believe the limits are much higher there.

**Comment by AshmitOld** [comment]
https://gist.github.com/Ashmit7509/041e60fa37de3a05c640862702f3a2ee
there you go that has the same error happening again with a diff ign too

**Comment by phit** [comment]
The logs are down, please reopen in SpongeVanilla/SpongeForge if this is still happening in the latest versions.
