### ISSUE TITLE
[1.10.2 SF] Too many files open with Chunk Unload

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/Sponge#1118]
Using `lsof` in my linux terminal to find open files and print them into a folder, I found that there were approx. 130-140 region files there with 30 players online - and of course, `view-chunk-distance` is very low. This normally also parallels an error seen after the server has been running for 6+ hours, where console is suddenly flooded by "Too Many Open Files" java errors.

Here is a timings, where the regions are calculated to 143 (unsure of the number, since this is often at times not a precise tool) and players, 50.

https://timings.aikar.co/v2/?id=9238d7576de342729a70d85ed4cc3005&section=chunks

In this case, you can see 25 players, but 1322 chunks loaded: https://timings.aikar.co/v2/?id=abb541dde17d4826a0f0d808c2471dcf . The server had to be killed as it froze.

Using SpongeForge 2008 and Forge 2185.

**Comment by bloodmc** [comment]
Set "deny-chunk-requests" to true in global.conf then retest. This is normally true by default to prevent many chunk load requests, from various sources, loading unneeded chunks.

**Comment by Rasgnarok** [comment]
Has not happened since - 41 players and 1760 chunks. I believe that is acceptable, non?

**Comment by Rasgnarok** [comment]
Have now 15 players, and 1400 chunks as per timings. https://timings.aikar.co/?id=c08638d849a843fdb6e9f40f4bbe0da6

**Comment by phit** [comment]
closing this, as this is more of a question and there was no updates since january
