### ISSUE TITLE
Server#getBoundAddress throws IllegalArgumentException

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#1120]
If `DedicatedServer#getHostname` returns `null`, `Server#getBoundAddress` will throw an `IllegalArgumentException`. [This line](https://github.com/SpongePowered/SpongeCommon/blob/e7841a5/src/main/java/org/spongepowered/common/mixin/core/server/MixinDedicatedServer.java#L633) is the culprit.

**Comment by stephan-gh** [comment]
When would `getHostname()` return null? This sounds like you are calling it before `server.properties` is actually loaded.

**Comment by caseif** [comment]
I have no idea why it would be `null`, but this is happening long after server initialization.
