### ISSUE TITLE
API 6 Allow Setting the Quantity of an Itemstack to -1

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#1121]
It seems in API 6 the ability to set the quantity of an ItemStack to -1 was removed, however this functionality is necessary for [Inventory#Query](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/item/inventory/Inventory.html#query-org.spongepowered.api.item.inventory.ItemStack...-)  as setting the quantity to -1 is how you query ignoring the size of the actual itemstack. Either this behavior needs to be added back in, or `Query` needs to be refactored to allow this behavior in some other way.  

**Test Code:**
```Java
public int getItemCount(Inventory inventory, ItemStack itemStack) {

    ItemStack copy = itemStack.copy();
    copy.setQuantity(-1); //Copy has a quantity of 0!

    return inventory.query(copy).totalItems();
}
```

Tested on *spongevanilla-1.11.2-6.0.0-BETA-192*

**Comment by Deamon5550** [comment]
Covered by Spongepowered/SpongeAPI#1437
