### ISSUE TITLE
Mixin error

### ISSUE THREAD

**Issue by vectrixdevelops** [SpongePowered/Sponge#1123]
For the newest versions of experimental 1.11.2 SpongeVanilla (which I have tested, may also occur on SpongeForge) there is a mixin error at launch.
 
https://gist.github.com/connorhartley/e3c8c0eb8f5ed0b5ef3c9068b142e224

Running a completely new server with no plugins.

**Comment by Maxqia** [comment]
Yup. Testing against 629b59f3c1bf57a2c6df57a179b2473965713f72 works though (haven't run a bisection yet, but I'd guess that  657d1ace3afb9b187464a218845f9f791b15950b broke it)

**Comment by Mumfrey** [comment]
Why did you assign me? I already fixed this,

**Comment by stephan-gh** [comment]
@Mumfrey I've assigned you because you fixed it, not because you still have to fix it. ;)
