### ISSUE TITLE
Setting an inventory slot causes a cascade of setting

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/Sponge#1124]
When you set a certain slot's value, you set all of the slots below or to the right of it to that same item, no matter what.

**Comment by windy1** [comment]
I've also experienced this.

**Comment by codeHusky** [comment]
This makes it fairly hard to make Chest GUIs that work on higher latency clients, so a fix ASAP would be perfect.

**Comment by Faithcaio** [comment]
Still happening?
Please provide example code.

**Comment by codeHusky** [comment]
I’m pretty sure this was resolved a while ago
