### ISSUE TITLE
World Save Method not implemented

### ISSUE THREAD

**Issue by JessiahC** [SpongePowered/Sponge#1126]
Class org.spongepowered.api.world.World;

World.save() Method is not implemented, results in:
`
java.lang.AbstractMethodError: Method net/minecraft/world/WorldServer.save()Z is abstract at net.minecraft.world.WorldServer.save(SourceFile) ~[ls.class:?]`

Moving from API to SpongeCommon as per https://github.com/SpongePowered/SpongeAPI/issues/1458

**Comment by stephan-gh** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/b676c6feba5ce865c65fe693457920b85e0d18dd
