### ISSUE TITLE
ChangeDataHolderEvent implementation progress

### ISSUE THREAD

**Issue by vectrixdevelops** [SpongePowered/Sponge#1128]
Is the ChangeDataHolderEvent being worked on somewhere? 🍰

**Comment by me4502** [comment]
Potential answer, https://github.com/SpongePowered/SpongeCommon/issues/742#issuecomment-262993173

**Comment by gabizou** [comment]
No, don't open issues just asking about the progress of them. As they're added to the API, they will be implemented.
