### ISSUE TITLE
Pixelmon breaks and can not be thrown out 

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#1131]
After seeing this in console:
https://hastebin.com/yihoveyibu.css < -- Not sure if this is related!

....Pixelmon are unable to be thrown out and seem to not even register to try to be thrown out due to no "X has been sent out" message in chat. Seems to happen frequently on Sponge version 2029.

http://pixelmonmod.com/tracker.php?p=2&t=11375

**Comment by Rasgnarok** [comment]
Referencing off of this, does it happen in the same manner as these two times?
https://github.com/SpongePowered/SpongeForge/issues/949
https://github.com/SpongePowered/SpongeForge/issues/901
