### ISSUE TITLE
SlotTransactions from other viewers of containers are included in your slot transactions

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Sponge#1133]
So there is a duplication bug with our locking plugin Latch. We have a donation chest which only people who are added to can remove from but everyone can add to. How it works is basically the people who are not the owner or added as an accessor cannot remove items, move them, or similar. The problem arises when someone without access is viewing someone with access removing items. Once the person without access tries to move an item out or similar we cancel the event, and for some reason the items removed are replaced into the container creating a duplicate.

It seems like for some reason the person simply viewing the transactions also has the original player's slot transactions within theirs. There may be a reason for this but to me that does not seem intentional.

Find our code for this ClickInventoryEvent listener [here](https://github.com/IchorPowered/Latch/blob/0cc4285faf40c447fa30e2063d03566ea01ca798/src/main/java/com/meronat/latch/listeners/InteractBlockListener.java#L54).

Sponge versions where this has occurred.

**First:** 
spongeforge-1.10.2-2171-5.1.0-BETA-2010

**Second:**
SpongeAPI: 6.0.0-SNAPSHOT-9005019
SpongeVanilla: 1.11.2-6.0.0-BETA-192

**Comment by Faithcaio** [comment]
might be related to: https://github.com/SpongePowered/SpongeCommon/issues/1105
