### ISSUE TITLE
Sometimes removing items from chest calls/posts ClickInventoryEvent but has 0 transactions

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Sponge#1134]
We cancel removal of items from containers for people without access, but for some reason if they keep shift clicking fast enough sometimes ClickInventoryEvent is called/posted but has zero transactions so we cannot cancel the movement of that item and they can take from someone else's container.

You can see how we tested this with the log statements in our [ClickInventoryEvent listener](https://gist.github.com/Nighteyes604/afff61c8836912d92f0b88319eeb3461#file-interactblocklistener-java-L61). When it was working properly nothing was logged but when the problem arose "no transaction" was logged so we couldn't cancel the event.

**Comment by ryantheleach** [comment]
@Meronat Do you know if this is still relevant? A smaller test plugin would go a long way in helping someone tackle this.

**Comment by parlough** [comment]
@ryantheleach I investigated this with Aaron at one point, and he may have made a fix, I don't remember. I will look for a relevant commit and test it as soon as I'm on a computer. 

Thanks for bringing this to my attention, I forgot about it.

**Comment by parlough** [comment]
Going to close this for now due to no one else reporting the issue. If it occurs again I will re-investigate the issue.
