### ISSUE TITLE
Error when clicking respawn in the Nether

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Sponge#1139]
Players are unable to respawn in the nether.

http://pastebin.com/SvWb1EL7

**Comment by simon816** [comment]
Huh. History repeats itself
https://github.com/SpongePowered/SpongeVanilla/commit/9e4f711d0f230614cf1477b717ec72825f04830e#diff-37b668064b9c94b0afaa1f7e5ab1c7afL66

https://github.com/SpongePowered/SpongeVanilla/commit/09edb026ecfb7f3475691d446c0359e6ae77eb54#diff-37b668064b9c94b0afaa1f7e5ab1c7afR71

https://github.com/SpongePowered/SpongeVanilla/commit/19e3158daa8e73d7677fed1d11a8479bb17794a6#diff-f744cf6631575018455bf2e995bd511eL40
