### ISSUE TITLE
ClassEventHandlerFactory method.getDeclaringClass() instead of getClass().getClassLoader()

### ISSUE THREAD

**Issue by vorburger** [SpongePowered/Sponge#1143]
Would there be any way that 1 & 1/2 years later I would be able to do anything to convince you to accept the 2 line change I had originally proposed on https://github.com/SpongePowered/SpongeCommon/pull/82/files after all, to use `method.getDeclaringClass()` instead of `getClass().getClassLoader()` in [ClassEventHandlerFactory](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/ClassEventListenerFactory.java)? _(And that change alone, and nothing else related proposed at the time in https://github.com/SpongePowered/SpongeVanilla/pull/178; forget about all that.)_

Such a change would not have any impact, because for normal plugins `method.getDeclaringClass()` IS of course `getClass().getClassLoader()`. But as "[some plugins (such as scripting plugins) may wish to dynamically register an event listener](https://docs.spongepowered.org/master/en-GB/plugin/event/listeners.html#dynamically-registering-event-listeners)" (to quote from the documentation), this change would enable _some plugins (such as scripting plugins)_ to register event listeners annotated by @Listener - because there are use cases when `method.getDeclaringClass()` is not the same as `getClass().getClassLoader()`.

I would need this for work I'm doing related to https://github.com/vorburger/ch.vorburger.minecraft.osgi/. I can continue maintaining a fork of SpongeCommon, but it just seems such a PITA for this 2 line change - thus humbly thanking you for re-considering this (old...) request.

Happy to contribute a new Pull Request with https://github.com/SpongePowered/SpongeCommon/pull/82/files adjusted to current code base, if OK.

**Comment by Deamon5550** [comment]
That change wasn't actually valid as the classloader would be immediately garbage collected and the generated class with it. There is however a PR open right now (#1090) which does the same thing in a better way.
