### ISSUE TITLE
Player#getLocale() seems to always return Locales.EN_US

### ISSUE THREAD

**Issue by DawnTheFawn1** [SpongePowered/Sponge#1145]
I'm working on a system for my plugins going forward where I want to translate a message differently depending on their locale. As of spongeforge 5.1.0-BETA-2042 for 1.10.2, getting a player's Locale doesn't seem to work properly. Here's a short demo [video](https://youtu.be/RuzrAconSZE) and using [this](http://pastebin.com/8Gd7Gv5f) code for the output shown in the video.

**Comment by kashike** [comment]
`Player#getLocale` will *always* return `en_US` when a client joins - the `Player`'s locale gets updated after joining, when packet `0x04`/`CPacketClientSettings` is sent to the server.

**Comment by DawnTheFawn1** [comment]
Yea, I apologize for this, I for some reason thought that packet was sent before the player finishes joining the server. I was sending a message on join previously to test which was also why my previous tests weren't working. I guess in the future I should really test more thoroughly next time, I'm sorry for the trouble.
