### ISSUE TITLE
NullPointerException while getting invalid gamemode

### ISSUE THREAD

**Issue by JonathanBrouwer** [SpongePowered/Sponge#1146]
I get a NullPointerException when I request an invalid gamemode, while it should just return Optional.empty().

Example error:
http://pastebin.com/wYQuH9AC

This is caused by this line:
https://github.com/SpongePowered/SpongeCommon/blob/9e6acff2f9c25f346151420d368a26a0e3578a5b/src/main/java/org/spongepowered/common/registry/type/entity/GameModeRegistryModule.java#L50

Optional.of() should be replaced with Optional.ofNullable()
I did not check if this bug is in any other registry module.

**Comment by ST-DDT** [comment]
See also: https://github.com/SpongePowered/SpongeCommon/issues/739

> I did not check if this bug is in any other registry module.

Last time I checked it wasn't.

**Comment by Bammerbom** [comment]
I wouldn't consider this an OCD issue, considering it actually breaks stuff, but I might be wrong.
