### ISSUE TITLE
Command problem

### ISSUE THREAD

**Issue by TheGeekdu74** [SpongePowered/Sponge#115]
Hello, I have a little problem, when I want to install Sponge with eclipse, I need to do "Run gradle setupDecompWorkspace --refresh-dependencies" but where I can do that ?

**Comment by AIOOB** [comment]
In the command line, follow the instructions in the README.

**Comment by TheGeekdu74** [comment]
In a CMD ? or in Eclipse ?

**Comment by AIOOB** [comment]
cmd...

**Comment by TheGeekdu74** [comment]
Ok, but the CMd said to me gradle does not exists

**Comment by kenzierocks** [comment]
Use `./gradlew.bat` as mentioned in the readme.

**Comment by TheGeekdu74** [comment]
Ok thanks

**Comment by TheGeekdu74** [comment]
But, for the main class, I write "GradleStart" and GradleStartServer", or I search them ? Because when I search them, I don't found them

**Comment by AIOOB** [comment]
If the search is not finding them that probably indicates you have set it up wrong. The working directory is an optoin in the run configuration setup wizard.

**Comment by TheGeekdu74** [comment]
My gradle is set it up wrong ?

**Comment by AIOOB** [comment]
The project may be set up wrong or incorrectly imported into eclipse.

**Comment by bloodmc** [comment]
@TheGeekdu74 use our forums for issues such as these.
