### ISSUE TITLE
InteractBlockEvent.Secondary bug with alex

### ISSUE THREAD

**Issue by TheSebakl** [SpongePowered/Sponge#1150]
I report a bug about the event InteractBlockEvent.Secondary, who is not active when you are alex.

**Comment by liach** [comment]
?

**Comment by TheSebakl** [comment]
When i try the event InteractBlockEvent.Secondary with an account with Alex skin, the event is not read.

**Comment by JBYoshi** [comment]
Does this happen on the latest version? If so, post the version of Minecraft and Sponge that you're using.
