### ISSUE TITLE
Commands with same name override their permissions

### ISSUE THREAD

**Issue by dogboy21** [SpongePowered/Sponge#1154]
_To illustrate this issue I'm using Pixelmon, but every other plugin should work too_
Pixelmon adds an administrative `/unlock` command with the permission `pixelmon.command.unlock`. If there's another plugin which also adds a command named `/unlock` the permission node required for the Pixelmon command gets overwritten.
I created [a plugin](https://github.com/dogboy21/PermissionTest) to demonstrate this issue.

**Version**
SpongeForge (I think permissions is part of SpongeCommon so I created the ticket here)
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-d41d606
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2068
    Minecraft Forge: 12.18.3.2202

**Steps to reproduce**

- Setup a Sponge server with PermissionsEx (or every other permission plugin which has a debug mode to output the checked permissions) and Pixelmon.
Execute the command `/pixelmon:unlock`
![Pixelmon only](https://ss.myftb.de/jFtq7szu.png)
I have no permission for the command and PEX correctly reports the checked permission.

- Add the test plugin linked above to the server.
Execute `/pixelmon:unlock` again
![Pixelmon+Test plugin](https://ss.myftb.de/2_GHVdsM.png)
I have no permission for the command again, but PEX reports that Sponge checked for the permission of the test plugin, not Pixelmon's permission

This can be kinda dangerous if one plugin adds an administrative command which player aren't supposed to use and another plugin adds the same command but accessible to players.

**Comment by ryantheleach** [comment]
related: https://github.com/SpongePowered/SpongeCommon/pull/1008

**Comment by dogboy21** [comment]
Oh, okay. I haven't found an issue for this ^^
