### ISSUE TITLE
Armor Stand Invisibility

### ISSUE THREAD

**Issue by TheSebakl** [SpongePowered/Sponge#1156]
Hello, for a lot of design i need to use Armor Stand, but i can't use a command block.
it's sad to have an armorstand visible... do you know when the invisibility data will be implemented? 
thx

**Comment by me4502** [comment]
I believe this is already implemented. What code are you using?

**Comment by TheSebakl** [comment]
oh, yes, i've not tested since i putted the code. i asked because i will need it in few days. Thx ;-)
