### ISSUE TITLE
Getting a key by id doesn't work

### ISSUE THREAD

**Issue by JonathanBrouwer** [SpongePowered/Sponge#1160]
All of these return Optional.empty()
Sponge.getRegistry().getType(Key.class, "health")
Sponge.getRegistry().getType(Key.class, "HEALTH")
Sponge.getRegistry().getType(Key.class, "sponge:health")
Sponge.getRegistry().getType(Key.class, "sponge:HEALTH")

Related IRC discussion:
http://pastebin.com/hEF0sFRh

**Comment by rexbut** [comment]
I had the same problem, but it will be solved with the PR : https://github.com/SpongePowered/SpongeCommon/pull/1257

**Comment by gabizou** [comment]
Should be fixed with the latest builds of both SpongeForge#2262 and SpongeVanilla#235.
