### ISSUE TITLE
ParticleTypes.MOB_SPELL is the incorrect effect

### ISSUE THREAD

**Issue by Time6628** [SpongePowered/Sponge#1162]
mobSpell via /particle command: http://i.imgur.com/ZGLWwHp.png
MOB_SPELL from Sponge: http://i.imgur.com/YugcLFK.png
it's the little circles, they just fly everywhere even with no velocity set

Sample Code:
```java
//pl = plugin class, only used to get a random in this case
player.spawnParticles(ParticleEffect.builder().quantity(1).type(ParticleTypes.MOB_SPELL).option(ParticleOptions.COLOR, Color.ofRgb(pl.getRandom().nextInt(255), pl.getRandom().nextInt(255), pl.getRandom().nextInt(255))).build(), player.getLocation().getPosition());
```

**Comment by rexbut** [comment]
[ParticleRegistryModule Line 135](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/registry/type/effect/ParticleRegistryModule.java#L135) : It's not EnumParticleTypes.END_ROD but EnumParticleTypes.SPELL_MOB
