### ISSUE TITLE
server.saveWorldProperties doesn't appear to save values to world.conf

### ISSUE THREAD

**Issue by drakmirv** [SpongePowered/Sponge#1163]
Edits to the WorldProperties object are saved into level.dat on server.saveWorldProperties(...) calls.

However, the values contained in config/sponge/worlds/minecraft/overworld/<worldname>/world.conf file are not updated.

This results in those values being overridden on the next server startup / world load.

A workaround that seems to work is to call this immediately after calling saveWorldProperties(...):

Sponge.getCommandManager().process(server.getConsole(), "sponge save -w " + worldProperty.getWorldName())

This has a few disadvantages:

1) Relies on a command that may change in future versions of sponge
2) Relies on a world name versus UUID
3) Just doesn't feel "clean" 

I was unable to find an API that allowed me to do what the sponge command is doing.  It is part of the common package but its behavior relies on things in the Mixin classes which aren't exposed to the API.  Therefore, I couldn't find a safe way to do the same behavior without using the command.

**Comment by drakmirv** [comment]
Note that world.save() doesn't appear to save these values either.

**Comment by drakmirv** [comment]
This may also be affecting the ability to "enable" a world that is "disabled".  I think this happens since you can't programmatically save the "enabled" flag into world.conf.  The "sponge save" command (hack) above doesn't work for an unloaded world and you can't load a world marked as disabled.

**Comment by bloodmc** [comment]
This was fixed in a recent commit

https://github.com/SpongePowered/SpongeCommon/blob/stable-5/src/main/java/org/spongepowered/common/world/WorldManager.java#L442
