### ISSUE TITLE
unable to save world difficulty

### ISSUE THREAD

**Issue by lantren** [SpongePowered/Sponge#1165]
any time a single worlds difficulty is changed it gets changed back to what it was before after a server restart. 

so for example. world "A" and world "B" both have a difficult of easy. If you change world "B" to have a difficulty of normal. It only stays that way until the server is restarted.

**Comment by drakmirv** [comment]
Reference #1163 - I think this may be the same issue.  (There is an ugly workaround in 1163 that may work for you)

**Comment by lantren** [comment]
@drakmirv , thank you for the suggestion. Unfortunately, that is beyond the scope of a basic server administration task, since in can't be accomplished by a server admin.

**Comment by lantren** [comment]
apparently it's not the same as #1163 since that issue has been closed as resolved and this issue still persists.

**Comment by ryantheleach** [comment]
Related: https://github.com/SpongePowered/SpongeForge/issues/568

**Comment by Zidane** [comment]
This has been a long time coming but:

https://github.com/SpongePowered/SpongeCommon/tree/feature/multi-world-difficulty

Still a WIP but mostly there. Apologies for the very long wait!

**Comment by bloodmc** [comment]
@Zidane please push your branch when tested.

**Comment by Zidane** [comment]
Already in latest builds.
