### ISSUE TITLE
Cancelling an InventoryClickEvent and closing the inventory on the same tick results in erratic behavior

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#1166]
In the case that an `InventoryClickEvent` is cancelled and the inventory in question is closed on the same tick, erratic behavior will occur and [an exception may be thrown](https://git.io/vDf1R) by the packet phase handler and the event will not be properly cancelled. This is caused by [this line](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/tracking/phase/packet/PacketPhaseUtil.java#L71) referencing the player's currently open inventory in order to complete the rollback of the event. However, when the inventory is closed before the event is fully processed, it attempts to reference a slot which does not exist in the expected state (and may not exist at all for that matter), causing an exception to be thrown or strange behavior such as the item being applied to the player's armor inventory.

Provided my understanding of the inventory implementation is accurate, the obvious fix should be to reference the parent of the slot in question rather than the player's currently open inventory. If this is not viable, then this represents a more serious flaw and would likely require significantly more work in order to maintain expected behavior.

This behavior is reproducible on SpongeForge build 2086.

A [reduced version of the MWE](https://git.io/vDf1L) from #1045 is sufficient to demonstrate this bug.

**Comment by JBYoshi** [comment]
I think the link you posted would be the problematic code for #1045, #1105, and #1175. Fixing this should fix all of those.

**Comment by JBYoshi** [comment]
I think the code link you posted is also the problematic code for #1045, #1175, and #1229. Fixing this should fix all of those.
