### ISSUE TITLE
crash when installed on client

### ISSUE THREAD

**Issue by refparo** [SpongePowered/Sponge#1176]
It crashed when I'm opening a world.
[fml client log](https://gist.github.com/Problem233/cc12248ea3a5e2924f45645ce218e416)

**Comment by simon816** [comment]
Looks like it is conflicting with liteloader, @Mumfrey could that be the case?

**Comment by phit** [comment]
if this is still an issue report it to liteloader http://develop.liteloader.com/liteloader/LiteLoader/issues
