### ISSUE TITLE
Cancelling DropItemEvent.Pre destroys the ItemStack in some cases

### ISSUE THREAD

**Issue by eternel22** [SpongePowered/Sponge#1178]
When a player drops an item by pressing _**"ctrl+q"**_ and the event called is cancelled, the whole stack **disappears**.

![bug](https://cloud.githubusercontent.com/assets/23460744/22520894/590dad78-e8b6-11e6-84b1-3ad113f3f2a1.gif)

**Comment by bloodmc** [comment]
I can't reproduce this issue so closing as it was probably fixed awhile back.
