### ISSUE TITLE
Cancelling InteractBlockEvent.Secondary doesn't update the item count on the client side

### ISSUE THREAD

**Issue by eternel22** [SpongePowered/Sponge#1179]
When a player **place a block** and the event called is cancelled, the **item count** doesn't update on the client side.
![bug2](https://cloud.githubusercontent.com/assets/23460744/22521661/00e5db2c-e8b9-11e6-8df1-4e2b5a93da86.gif)

**Comment by Zidane** [comment]
Fixed in latest implementation builds.
