### ISSUE TITLE
Anvil get Custom

### ISSUE THREAD

**Issue by TheSebakl** [SpongePowered/Sponge#1180]
Hello, i've created a custom inventory of an anvil, i want to get the value of the result of new item (the name)
i've tried by myself with .getCursorTransaction() and there is nothing here, i've tried to get all transactions with getTransactions() and i get something at index 0 with propriety default but i get item without any change. I saw there is a custom value but with Optional.empty

How can i get the final name of an item who has changed name with anvil in a custom anvil inventory.

thx

**Comment by Zidane** [comment]
@Faithcaio 

Status?

**Comment by Faithcaio** [comment]
This PR makes the vanilla containers work as the client expects it. (currently there is no item on server side in the output slot)
https://github.com/SpongePowered/SpongeCommon/pull/1221

**Comment by phit** [comment]
@Faithcaio can this be closed as the PR got merged?
