### ISSUE TITLE
End gateway portals fail to save exit portal

### ISSUE THREAD

**Issue by kherock** [SpongePowered/Sponge#1189]
I've found that in the latest 1.11.2 builds, end gateway portals fail to create an exit portal and a safe teleport location. For example, the server will log

```
Couldn't save exit portal at BlockPos{x=-389, y=85, z=1220}
```

for seed -4451667846734335168.

**Comment by Aaron1011** [comment]
@rockmacaca: Set `deny-chunk-requests` to `false` in your `global.conf` for now. I'm working on a more comprehensive fix for this issue, but that will solve the problem without affecting anything for now.
