### ISSUE TITLE
Cancelling the ClickInventoryEvent when removing from a furnace does not stop experience creation

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Sponge#1193]
I cancel the `ClickInventoryEvent` if a player is removing from a certain container, and when this happens to be from the resulting box of a furnace, the removal is cancelled but the experience is still created. This leads to issues where players can infinitely create experience. I can stop the spawning of the experience by listening to that as a work around, but I feel this should be handled in Sponge to prevent general unauthorized experience creation.

**Comment by parlough** [comment]
I'm not exactly sure but it seems the experience is spawned before the `ClickInventoryEvent` is even fired.

**Comment by JBYoshi** [comment]
Confirmed. The XP orb is not being captured.

Test code:
```java
package jbyoshi.sponge.test;

import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.item.inventory.ClickInventoryEvent;
import org.spongepowered.api.item.ItemTypes;
import org.spongepowered.api.item.inventory.transaction.SlotTransaction;
import org.spongepowered.api.plugin.Plugin;

@Plugin(id = "testspongecommon1193")
public class TestSpongeCommon1193 {

    @Listener
    public void onClickInventory(ClickInventoryEvent event) {
        if (event.getTargetInventory().getClass().getName().endsWith(".ContainerFurnace")) {
            for (SlotTransaction transaction : event.getTransactions()) {
                if (transaction.getOriginal().getType() == ItemTypes.GLASS) {
                    event.setCancelled(true);
                    break;
                }
            }
        }
    }
}
```

To test, smelt some sand and try to remove the glass. Be aware that smelting glass does not always give XP; try removing it repeatedly.
