### ISSUE TITLE
Sleep player data is not set false when the bed is removed

### ISSUE THREAD

**Issue by vectrixdevelops** [SpongePowered/Sponge#1197]
As the title says, plus this causes the server to crash when it first happens.

**Comment by gabizou** [comment]
Could you provide us with a stack trace (I understand how to reproduce the issue, but a stack trace would still be nice to avoid the server crash in the future).

**Comment by vectrixdevelops** [comment]
I found one. :P

First time the bed is destroyed: https://gist.github.com/connorhartley/36c68ee364a8230db0707573f0244f66
Join error: https://gist.github.com/connorhartley/75194fc4d0e2d416b67c2f6d61abc38b

**Comment by Aaron1011** [comment]
@connorhartley: What version of SpongeForge/SpongeVanilla are you running?

**Comment by vectrixdevelops** [comment]
@Aaron1011 SpongeVanilla-1.11.2-6.0.0-BETA-217

**Comment by vectrixdevelops** [comment]
Fixed by https://github.com/SpongePowered/SpongeVanilla/commit/93cf8fbf2c3daf8d88772e76122116b05d7e319c
