### ISSUE TITLE
Keys.BOOK_PAGES and PagedData giving unexpected results.

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Sponge#1198]
I've only tested this on API 5.1. I will test this on API 6 tomorrow, but I want to get this down now.

When using `Keys.BOOK_PAGES` (which is of type `List<Text>`) on books, both writable and written, it seems to give odd results - tabulated below. I am working with the text "test text", and the returned value will be the result of `toPlain`.

-> | book.get(Keys.BOOK_PAGES).get() - printed on screen | book.offer(Keys.BOOK_PAGES, Lists.newArrayList(Text.of("test text"))) - checked book afterwards
-|----------|------------
Writable Book | "test text" | {"text":"test text"}
Written Book | {"text":"test text"} | "test text"

In the case of the writable book, I would expect that _offering_ text would not set the string representation of the text. In the case of the written book, I would expect that _getting_ text would get me the text, not the json representation.

I haven't develed _too_ far into how this works so don't know where the issue/s lives/lie, but it's inconvenient when you're transferring text from a written book to a writable book, even if you convert the text from the json that written book gives out!

[Code to test with can be found here](https://gist.github.com/dualspiral/170cf685672fbdcc5e4419e67015b80d). Hold a book, use `/getfrombook` and `/offertobook`.

**Comment by Aaron1011** [comment]
I think this is a duplicate of https://github.com/SpongePowered/SpongeCommon/issues/509.

**Comment by dualspiral** [comment]
Ah, my mistake - it looks like it is. Let me comment over there.
