### ISSUE TITLE
allow humans to be spawned

### ISSUE THREAD

**Issue by writeescape** [SpongePowered/Sponge#1199]
at the moment you have to write in a plugin the ability to spawn a human. 
please allow /summon sponge:human to be a thing as right now it errors.

**Comment by Zidane** [comment]
Can I ask why you want this?

**Comment by windy1** [comment]
@Zidane Slightly off-topic but I thought I'd mention that EntityHuman is rather broken at this point. It is currently impossible to write a decent NPC plugin in it's current state. I began fixing a few issues with [this branch](https://github.com/SpongePowered/SpongeCommon/tree/fix/humans) but I don't think I'll have an opportunity to finish it anytime soon. 

I'm sure many plugin devs would appreciate it if someone has the time to throw that branch some love.

**Comment by writeescape** [comment]
mainly so that the entity list is complete so that it could be worked upon rather then error into a stacktrace

**Comment by mcmonkey4eva** [comment]
@windy1 +1 to getting that worked on more. I don't want us to have to make our own damn cross-compatible human code when Sponge could helpfully do it for us.

**Comment by Zidane** [comment]
@windy1 @mcmonkey4eva Humans have always been my baby (Though @simon816 technically gave birth). My professional work is winding down so this seems like a good way to kick back up Sponge dev work.

@windy1 PM or create me an issue with the current problems with Humans and I'll take that branch and modify it to address the issues.

**Comment by Zidane** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/fd4aca2ca58a04b86f545869558d6249c095a470

https://github.com/SpongePowered/SpongeCommon/commit/8b37cb29c7ed95a9e75d0d355ae1e017edc6c9b2

Humans now persist between restarts.

Summon command is working fine:

```
/summon Sponge.Human
```

What other issues are there?

**Comment by writeescape** [comment]
Setting a player skin to them?

**Comment by Zidane** [comment]
@writeescape make a new issue for that then.
