### ISSUE TITLE
World Modifiers get reset after world reset

### ISSUE THREAD

**Issue by dogboy21** [SpongePowered/Sponge#1200]
After resetting a world (deleting the whole dimension folder) the world generation modifiers in the Sponge world config are gone. Every other world config keeps it's previous value.

**Test environment**

SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-6459642
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2142
    Minecraft Forge: 12.18.3.2221

**Steps to reproduce**

- Add a world modifier into a world config of the nether, for example `sponge:skylands`.

- Stop the server, delete the whole nether folder (world/DIM-1)

- Start the server, look into the config
Before: ![Before]( https://ss.myftb.de/L4WR2WGz.png)
After:    ![After](https://ss.myftb.de/aqLk6yp-.png)

**Comment by Deamon5550** [comment]
duplicate #1188

Its not the modifiers its that when the world is created the config is recreated rather than just loaded.

**Comment by dogboy21** [comment]
I saw that issue, but IMO it's not related to deleting the world. Also it doesn't apply to the whole config, I also changed the chunk-gc settings to test this, and the settings were still changed after the world reset, just the modifiers were gone.
Btw @bloodmc said that this behaviour doesn't make any sense so I created the issue

**Comment by Deamon5550** [comment]
alright not quite caused by what I was thinking, but its still identical to the other issue.
