### ISSUE TITLE
Cannot cancel world saving

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/Sponge#1202]
I tried cancelling SaveWorldEvent, but it saves anyways.
After researching, I noticed that the events are posted, but it is not checked whether it was cancelled:

https://github.com/SpongePowered/SpongeCommon/blob/10c4e2f31c5bacd0b6e4b9018e528ca0cb9dd3fe/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L890.
Also line 899.

I also looked in SpongeForge and SpongeVanilla, this is the only occurrence.
This should be irrelevant, but I reproduced it on _spongevanilla-1.11.2-6.0.0-BETA-208_.

This should be an easy fix.
Thanks!

**Comment by kashike** [comment]
Feel like submitting a pull request?

**Comment by JonathanBrouwer** [comment]
This should be closed considering the PR has been merged.
