### ISSUE TITLE
Change InvulnerabilityData to boolean

### ISSUE THREAD

**Issue by Ptilopsis** [SpongePowered/Sponge#1204]
As someone who tries to move from Spigot to Sponge, I noticed some strange inconsistencies within org.spongepowered.api.data.manipulator.mutable.entity.

The interface InvulnerabilityData offers me the possiblity to make an entity invulnerable.
But it requires me to specify an amount of ticks, which seems rather unnecessary and makes the plugin logic somewhat harder, as even Integer.MAX_VALUE isn't permanent (but a long time).
Spigot instead seems to chose to work with NBT internally.

Comparison:
Spigot:
player.setInvulnerable(true);

Sponge:
player.offer(Keys.INVULNERABILITY_TICKS, Integer.MAX_VALUE);

I only noticed this, because the InvisibilityData-Interface uses booleans internally on each of its methods.

**Comment by randombyte-developer** [comment]
I also asked for this earlier https://github.com/SpongePowered/SpongeAPI/issues/1317

**Comment by gabizou** [comment]
Duplicate of SpongePowered/SpongeAPI#1317.
