### ISSUE TITLE
Infinite item despawn-delay is not working

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#1212]
I tried to make an item never despawn using `item.offer(Keys.INFINITE_DESPAWN_DELAY, true);`
But the items are still despawning after 5 minutes.
*The "INFINITE_PICKUP_DELAY" however is working fine!*

I tested it using this code: https://gist.github.com/TBlueF/b82539453671bb90e24350024acb69d3
on both:
Sponge Vanilla *(1.11.2-6.0.0-BETA-217)*
and Sponge Forge *(1.11.2-2227-6.0.0-BETA-2148 using Forge 1.11.2-13.20.0.2227)*

This is the spawned item:
![forge](https://cloud.githubusercontent.com/assets/10765470/23107188/f0faee16-f6f8-11e6-9094-32bdc518a208.PNG)
*(Also very important: "Water flows" ;D)*

**Comment by Zidane** [comment]
@gabizou Status on this?

**Comment by ryantheleach** [comment]
Possibly related: 
1. https://github.com/SpongePowered/SpongeForge/issues/1324
 2. https://github.com/SpongePowered/SpongeForge/issues/1201

**Comment by Twisted-Code** [comment]
@gabizou any progress? Pretty sure this is related to the issue I'm having with AE crystal seeds despawning. I know they have the no-despawn flag set but, as I noted in reply to one of the issues referenced above, they keep despawning on my server (and not in singleplayer)

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1324#issuecomment-325364383 reports that it is not reproducible in single player.

**Comment by randombyte-developer** [comment]
That is just a simple copy paste error: https://github.com/SpongePowered/SpongeCommon/blob/3bf7c161715a86bd504e370a263a8a55ba07f7f8/src/main/java/org/spongepowered/common/data/processor/value/entity/InfiniteDespawnDelayValueProcessor.java#L53 should be the equivalent `setDespawnDelay()` and https://github.com/SpongePowered/SpongeCommon/blob/3bf7c161715a86bd504e370a263a8a55ba07f7f8/src/main/java/org/spongepowered/common/data/processor/value/entity/InfiniteDespawnDelayValueProcessor.java#L59
