### ISSUE TITLE
Event listener Order not checked to allow cancellation

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/Sponge#1213]
In the [API javadocs on Order](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/Order.java) we mention that in certain order phases events are read-only and cannot be cancelled. Currently neither of these are enforced.

**Comment by ImMorpheus** [comment]
PR merged.

read-only event orders are dead.
