### ISSUE TITLE
Console spam: Tried to assign a mutable BlockPos to tick data...

### ISSUE THREAD

**Issue by Wadimich** [SpongePowered/Sponge#1216]
Hello, here is log: http://pastebin.com/ZJ4Txyzp
This is happen on sponge 2178 and forge 2221 and only when item from mod is generation redstone signal and it's accepting something like lamp. Vanilla ways to output redstone signal works fine.

**Comment by Aaron1011** [comment]
Does this occur with only Forge and the mod installed (e.g. without Sponge)?

**Comment by Wadimich** [comment]
Yes, it occurs when Sponge isn't loaded, new trace: http://pastebin.com/krTZtYQ9

**Comment by Deamon5550** [comment]
Report it to that mod then.
