### ISSUE TITLE
GridInventory.getSlot(x, y) returns a Slot with an incorrect position

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#1218]
I have a git clone of the `SpongeForge` project, some parts of my plugin which worked in past now have strange behaviors, to identify the problem I did some tests, here is the result : 

Test code : http://pastebin.com/GZUWTb0D
Test log : http://pastebin.com/eK4ZMzWg
Test screenshots : http://imgur.com/a/fLSDu

**Comment by Faithcaio** [comment]
Where are you getting your grid from?
Is it really a GridInventory?

Generally the Inventories you get from an Event are NOT GridInventories.
You can query for GridInventories in them and then get the slot by SlotPos:
```
Container container = event.getTargetInventory();
// Query for GridInventories in the Container
Inventory queryResult = container.query(GridInventory.class);
// The queryResult contains now all GridInventories in the Container;
for (Inventory grid : queryResult)
{
    // e.g. if Container is for a vanilla chest you will get 2 grids one for the Chest and one for the Main Player Inventory
    Inventory slot = grid.query(SlotPos.of(2,2));
    // Do stuff with your slot.
}
```
Btw. usually you can access the "upper" viewed inventory by calling
`container.iterator().next()`

**Comment by Yeregorix** [comment]
The GridInventory does not come from any event, it's a custom one, created using `Inventory.builder()`, look at the constructor of this class http://pastebin.com/BsDiV64p. Method `onInteract()` is called from an external event listener.

**Comment by Faithcaio** [comment]
Works fine in latest bleeding...
http://i.imgur.com/NQqk6Mm.png

**Comment by Yeregorix** [comment]
Very strange.. I will make a new clean git clone and try again.

**Comment by Yeregorix** [comment]
It works fine for me now. I come back if I see the problem again.
