### ISSUE TITLE
Crash java.util.NoSuchElementException

### ISSUE THREAD

**Issue by Wadimich** [SpongePowered/Sponge#1219]
Hello! Here is crashlog: http://pastebin.com/MGKyeBbq

This is on Sponge 2185 and Forge 2221.

**Comment by Aaron1011** [comment]
Can you upload your `fml-server-latest.log`?

**Comment by Wadimich** [comment]
Yes, here it is
[fml-server-3.zip](https://github.com/SpongePowered/SpongeCommon/files/801770/fml-server-3.zip)

**Comment by Aaron1011** [comment]
Can you re-test on the latest SpongeForge? I've [fixed a bug](https://github.com/SpongePowered/SpongeCommon/commit/ba3642a3d8d086c270d60ad7892c8407587e8ce8) which cause causing chunk loading (and therefore CauseTracker phase completion) to happen off of the main thread.

**Comment by Wadimich** [comment]
Sure, updating. It will take some time, cause i don't really know, how to 100% reproduce this bug, i'll write later, if got same.

**Comment by Aaron1011** [comment]
That's to be expected, as this crash was caused by a race condition. Btw, make sure to download SpongeForge from [here](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2), as the other downloads page is having issues.

**Comment by Tencao** [comment]
I would like to confirm for me this issue has not come back as of yet. It was very reproduce-able for me simply by turning on the world generation via plugin, however on the latest sponge this crash no longer happens.

**Comment by Wadimich** [comment]
I still haven't crashes, looks like the issue is fixed.
