### ISSUE TITLE
TNT Error

### ISSUE THREAD

**Issue by JonathanBrouwer** [SpongePowered/Sponge#1220]
**System information:**
Windows 10 64 bits
SpongeForge 1.11.2-2227-6.0.0-BETA-2190

**Steps to reproduce:**
1. Place 2 blocks of tnt right next to eachother
2. Ingnite one of the blocks of TNT
3. Once the TNT blows up, this error is thrown.
Sometimes it seems to result in a full server crash, but that only happened once to me and I can't reproduce it anymore. The error is consistent tho.

http://pastebin.com/jcJvXkC3

**Comment by Aaron1011** [comment]
@gabizou Can you take a look at this?
