### ISSUE TITLE
CustomContainer.getPlugin() is not implemented

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#1222]
When called in a listener (and presumably from other places, as well), an instance of `CustomContainer` (as returned from `ClickInventoryEvent.getTargetInventory()`) throws an `AbstractMethodError` when its `getPlugin()` method is called.

[Here is the stacktrace](http://pastebin.com/bsgYvmqp)
[Here is my listener code that triggers the error](http://pastebin.com/xRURH76m)

**Comment by ghost** [comment]
I have found a possible solution where in the `MixinCustomInventory` class, a few tweaks need to be made. The diff is [here](http://pastebin.com/DGFr7yFw). I did not make this fix into a pull request as it would be too short.

**Comment by JBYoshi** [comment]
I've got some code for this. I'm just trying to fix up some messed merges, then I'll put up a PR.
