### ISSUE TITLE
SF3 animal spawn with spongeforge 2168 or greater 

### ISSUE THREAD

**Issue by darkcamo12** [SpongePowered/Sponge#1223]
we are running skyfactory 3 3.0.6 for Minecraft 1.10.2
and we had noticed a lack of passive mobs spawning so we started doing some testing loading a server up with just skyfactory3's default mods and only spongeforge 2188 installed

our set up was a large grass platform in a brand new empty void world we waited anywhere up to if not more then 20 mins for passive mobs such as cows, chickens and pigs to spawn with no luck so we rolled sponge forge back about 100~ versions they started spawning instantly so we went to spongeforge version 2166 and all was good then updated to spongeforge 2168 and nothing 

the reason for going to version 2166 was because it was the version before the change for entity limits and world spawner

this could be affecting ambient and aquatic not just animal

**Comment by Aaron1011** [comment]
@bloodmc Can you take a look at this?

**Comment by bloodmc** [comment]
Just raise the spawn limits in config.

**Comment by darkcamo12** [comment]
I tried that and well setting the spawn limit to 1500 on a new server with no players except myself and patch of grass about 100x100 didn't do anything

**Comment by DamageDoctor** [comment]
Passive mobs didn't naturally spawn at all until we rolled back to the earlier build. This was both on test and production servers built completely separately.

**Comment by darkcamo12** [comment]
Also just as a side note hostile mobs seem to be working fine
