### ISSUE TITLE
"deny-chunk-requests" option prevents world pregeneration

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Sponge#1224]
In the latest versions of Sponge for 1.10 and 1.11, the `deny-chunk-requests` feature prevents world pregeneration from taking place correctly. Whilst no error is returned, the effect is that the pre-generator suggests that tens of thousands of chunks are being generated every tick, and whilst it would be _nice_ if that was true, all this is happening is that "empty chunks" are being returned.

To reproduce, kick off a pre-generation on a latest version of Sponge and watch the console log show that tens of thousands of chunks are generated. On a fairly decent spec machines, I would expect this to be around 20-30 per tick using the default settings.

**Comment by Aaron1011** [comment]
This should be fixed in [the latest SpongeForge](https://github.com/SpongePowered/SpongeCommon/commit/0cd9650e1fe168ba60110c5ee3c8e00afdc0d9b1).

**Comment by dualspiral** [comment]
Yep, can confirm, thanks.
