### ISSUE TITLE
ClickInventoryEvent - returns wrong inventory archetype

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Sponge#1225]
```Java
Inventory i = Inventory.builder().of(InventoryArchetypes.DOUBLE_CHEST).build(plugin);
//fill with items
getPlayer().openInventory(i, cause);
```

```Java
public void onOptionSelect(ClickInventoryEvent event, @First(typeFilter = Player.class) Player player) {
	event.getTargetInventory().getArchetype()...
```

Click on an item which is present in the inventory, we just created. Method getArchetype returns archetype UNKNOWN instead of DOUBLE_CHEST. 

Tested with 1.11.2-6.0.0-BETA-224 Sponge vanilla

**Comment by Faithcaio** [comment]
Thats because it is not a DoubleChest. Its a Container viewing a DoubleChest and PlayerInventory.

**Comment by NeumimTo** [comment]
@Faithcaio What would be a correct approach then?  
A spongebuild from the start of February returned in the same case either archetype PLAYER or DOUBLE_CHEST (depending on which inventory player clicked)

**Comment by Faithcaio** [comment]
If you want to check for upper/lower inventory the easiest way for now is to get the SlotIndex 
and check if its greater than the first sub-inventory in the container.
