### ISSUE TITLE
Constant not used in mob/animal spawning limits

### ISSUE THREAD

**Issue by elementalistic** [SpongePowered/Sponge#1230]
Looking at the Mixin MixinWorldEntitySpawner.java file, I noticed the code uses the formula for maxCount as 

`int maxCount = limit * chunkSpawnCandidates / MOB_COUNT_DIV;`

but a bit further down it recalculates it for the moblimit as

`int mobLimit = (limit * chunkSpawnCandidates / 256) - entityCount + 1;` 

Shouldn't the 256 be the constant as well, or even just referencing the maxCount variable?

**Comment by Zidane** [comment]
@bloodmc Can you comment on this?
