### ISSUE TITLE
Significant delay between block break and item frame break

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/Sponge#1231]
To better explain. Putting an item frame with a clock (haven't tested anything else) in it on any block and breaking that block it is attached to you'll see the item frame sit there for a good 2-4 seconds before it breaks.

**Minecraft:** 1.11.2
**SpongeAPI:** 6.0.0-SNAPSHOT-8aabd12
**SpongeForge:** 1.11.2-2227-6.0.0-BETA-2218
**Minecraft Forge:** 13.20.0.2228

**Comment by ryantheleach** [comment]
Vanilla SSP Creative 1.11.2 for reference.

https://www.youtube.com/watch?v=55SvjB3Bj3c&feature=youtu.be

@Grinch Close this? or was it significantly longer? 
I suspect this will be intended behavior expected after sponges entity ticking optimizations.

**Comment by Grinch** [comment]
No, it was about the same time. Didn't expect it to be that way in Vanilla as well. I will close this. :)
