### ISSUE TITLE
Equipment not implemented

### ISSUE THREAD

**Issue by mcmonkey4eva** [SpongePowered/Sponge#1232]
Method EntityPlayerMP.equip(EquipmentType, ItemStack) is abstract

Methods for entities in general that have equipment are all seeming to be abstract as well .-.

**Comment by parlough** [comment]
@Faithcaio / @kashike I believe this was fixed in https://github.com/SpongePowered/SpongeCommon/pull/1401

**Comment by kashike** [comment]
#1401
