### ISSUE TITLE
 DropItemEvent.Destruct doesn't track cause properly when caused by a block breaking

### ISSUE THREAD

**Issue by Waterpicker** [SpongePowered/Sponge#1238]
When I try to listen for the DropItemEvent.Destruct event and read out the causes. I get this as a result.

> Cause[{Name=Source, Object={BlockSpawnCause{SpawnType=SpongeSpawnType{id=DroppedItem, name=DroppedItem}, BlockSnapshot=SpongeBlockSnapshot{worldUniqueId=b9aeca80-d827-471a-b318-4b50c26dcd18, position=(54, 71, 309), blockState=minecraft:air, extendedState=minecraft:air}}}}, {Name=Notifier, Object={EntityPlayerMP['Waterpicker'/242, l='world', x=52.41, y=71.00, z=306.75]}}]

The BlockSpawnCause is always air regardless of what block type I break.

I used the code below to listen.

`
    @Listener
    public void onItemDrop(DropItemEvent.Destruct event) {
        event.getCause().all().forEach((c) -> logger.info(c.toString()));
    }
`

**Comment by DarkArc** [comment]
I can confirm this is an issue:
```
SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a26c654
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2322
    Minecraft Forge: 12.18.3.2254
```

**Comment by Waterpicker** [comment]
Has this issue been looked at recently?

**Comment by RedNesto** [comment]
The Cause is the right one for me: 
```
[14:52:41 INFO] [tests]: Cause: SpongeBlockSnapshot{worldUniqueId=382051b1-3121-49c9-8c69-3c75ba696875, position=(164, 71, 43), blockState=minecraft:diamond_ore, extendedState=minecraft:diamond_ore}
[14:52:41 INFO] [tests]: Cause: EntityPlayerMP['RedNesto'/124, l='world', x=164,57, y=71,00, z=40,61]
```

with: 
```java
    @Listener
    public void onBlockItemDrop(DropItemEvent.Destruct event, @First Player player, @First BlockSnapshot blockSnapshot) {
        event.getCause().all().forEach(cause -> logger.info("Cause: " + cause.toString()));
    }
```
When breaking a diamond ore.
