### ISSUE TITLE
Sponge Plugins list String too big

### ISSUE THREAD

**Issue by phit** [SpongePowered/Sponge#1239]
running `/sponge plugins` on big packs can kick you from the server

`[16:01:13] [Netty Server IO #1/ERROR]: io.netty.handler.codec.EncoderException: String too big (was 36841 bytes encoded, max 32767)`

old issue https://github.com/SpongePowered/SpongeForge/issues/918

**Comment by ST-DDT** [comment]
Addressed by PR: https://github.com/SpongePowered/SpongeCommon/pull/1250
