### ISSUE TITLE
Zombies do not break wooden doors

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/Sponge#1240]
Zombies do not seem to break wooden doors as they typically would.

**Minecraft:** 1.11.2
**SpongeAPI:** 6.0.0-SNAPSHOT-8aabd12
**SpongeForge:** 1.11.2-2227-6.0.0-BETA-2221
**Minecraft Forge:** 13.20.0.2228

**Comment by Deamon5550** [comment]
They only break doors if the local difficulty is above a certain threshold (which depends on several factors). I forced it to true and they break doors just fine.

**Comment by Grinch** [comment]
My server has the difficulty set to hard though I still cannot get them to break doors. What other factors does it depend on?

**Comment by Deamon5550** [comment]
From the code its between a 0-10% that a zombie will be set as able to break doors (calculated only once upon spawning not when loading from nbt).

Difficulty calculation (it uses the clamped additional difficulty): https://gist.github.com/Deamon5550/dd84ed526b1c87ab5d1b0ca65660a515

**Comment by Grinch** [comment]
Interesting. I'll go ahead and close this issue. Thanks!
