### ISSUE TITLE
Squids do not spawn naturally

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/Sponge#1241]
I've searched high and low for a squid and cannot find any. I'm convinced they are not spawning right now.

**Minecraft:** 1.11.2
**SpongeAPI:** 6.0.0-SNAPSHOT-8aabd12
**SpongeForge:** 1.11.2-2227-6.0.0-BETA-2221
**Minecraft Forge:** 13.20.0.2228

**Comment by dogboy21** [comment]
We're also encountering this bug. Squids and even bats do not spawn naturally

**Minecraft**: 1.10.2
**SpongeAPI**: 5.2.0-SNAPSHOT-982a6b0
**SpongeForge**: 1.10.2-2221-5.2.0-BETA-2223
**Minecraft Forge**: 12.18.3.2254

**Comment by ShieLian** [comment]
One more here. When I disable the sponge-forge, they appear.
Minecraft: 1.10.2
SpongeForge: spongeforge-1.10.2-2221-5.1.0-BETA-2210.jar and spongeforge-1.10.2-2221-5.1.0-BETA-2262.jar
Minecraft Forge: 12.18.3.2239

**Comment by ladehaug** [comment]
I installed a clean server setup with the most recent build 2231 (forge 2254) with only SpongeForge installed (essentially a vanilla setup) and can confirm that there are no squids spawning in the world. It also explains why I haven't seen a bat on my server for quite some time.. Tried adjusting a number of settings in the config file with no luck.

--
Geir

**Comment by JonoColwell** [comment]
This issue is still unfixed
Minecraft 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
Spongeforge: 1.10.2-2254-5.2.0-BETA-2231
Minecraft Forge: 12.18.3.2254

**Comment by JaSpr** [comment]
We are also experiencing an issue with no squids spawning whatsoever in our world.
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2254-5.2.0-BETA-2231
    Minecraft Forge: 12.18.3.2254

**Comment by xF4m3** [comment]
This issue seems to be back again, we do not get squid spawns at all with sponge installed. 
We also found this issue aswell #1432 , but we also turned up the spawn caps that are mentioned there, and this did not help either. I would like to reopen this issue.

    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2274
    Minecraft Forge: 12.18.3.2281

**Comment by bloodmc** [comment]
I cannot reproduce this issue. With only SpongeForge and raising the aquatic spawns in config to a high number shows many squids. Make sure to update to latest SF and raise aquatic spawn cap if you want more squids.
