### ISSUE TITLE
Help command doesn't follow Vanilla usage

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/Sponge#1242]
In Minecraft we have the help command which follows this syntax for page traversal `/help [page]`. So `/help 2` works fine and as expected.

If you try to do this in Sponge you are met with a "Unknown command. Try /help for a list of commands". Instead you must do `/page 2` to traverse the pages. This completely breaks what people would expect from this command.

**Comment by kashike** [comment]
This is the same with other sponge commands afaics.

**Comment by kashike** [comment]
I'm not exactly sure why we even replace the vanilla help command with our... worse version.

**Comment by Deamon5550** [comment]
Its particularly bad if you call it from the console as there is no prompt or any indication of now to get to the next page.

**Comment by dvoraktypist** [comment]
This is beyond bad. It breaks one of the core assumptions of how the game works, ... accessing the help system.

Why isn't in documented where it belongs, in the /help command itself?

I almost uninstalled, except one of the mods I'm using requires sponge.
