### ISSUE TITLE
Cannot teleport players

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Sponge#1245]
I cannot teleport to other players or teleport one person to another, I get this error instead. I have not verified this on SpongeForge yet, only SpongeVanilla.

![image](https://cloud.githubusercontent.com/assets/18372958/23813904/a51d84e2-05a6-11e7-8a57-393f4a255eca.png)

SpongeVanilla -
Minecraft: 1.11.2
SpongeAPI: 6.0.0-SNAPSHOT-e108372
SpongeVanilla: 1.11.2-6.0.0-BETA-231

**Comment by Deamon5550** [comment]
This was fixed in d29616bc75a625f415a67bb98b4c1df9de70ef85
