### ISSUE TITLE
Exception attempting to capture or spawn an Entity when canceling BlockChanges

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/Sponge#1248]
Setup: TNT narby Fire http://i.imgur.com/d9JD2sU.png

Cancel BlockChanges using:
```
@Listener
public void onChangeBlock(ChangeBlockEvent event)
{
    if (!(event.getCause().root() instanceof Player))
    {
        event.setCancelled(true);
    }
}
```
Error:
https://gist.github.com/Faithcaio/9c29d59c4c59847785901d508d516d20

tested using latest SpongeForge

**Comment by bloodmc** [comment]
This is fixed in latest builds.
