### ISSUE TITLE
Shulker boxes throwing errors

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/Sponge#1253]
Interacting with Shulker boxes throw a massive error on console. Here's the relevant slice of the latest.log: http://pastebin.com/jaKc4ZV8
This has been happening on the Sponge Community Server, currently with SpongeVanilla 1.11.2 build 231 (although it's been happening since at least build 228).

**Comment by liach** [comment]
Fixed in #1214, needs check.

**Comment by liach** [comment]
@gabizou Can you manage this?

**Comment by Faithcaio** [comment]
similar to https://github.com/SpongePowered/SpongeForge/issues/1362
I'm fixing it in:
SpongePowered/SpongeCommon@7719eee

**Comment by liach** [comment]
My pull gets killed again :thinking:

**Comment by Faithcaio** [comment]
sry, but i'm including some of it

**Comment by Faithcaio** [comment]
fixed in https://github.com/SpongePowered/SpongeCommon/commit/ba2a27ffa83ee972a024407921fbd36c01e768c0
