### ISSUE TITLE
Server crashes when trading with leatherworker

### ISSUE THREAD

**Issue by floomat** [SpongePowered/Sponge#1254]
Everytime if someone tries to trade with a leatherworker in a village the server crashes and i need to restart it.[This](https://forums-cdn.spongepowered.org/uploads/default/optimized/3X/2/8/2813c43b0101feb201e94be02df2908f1fd21aca_1_690x415.gif) shows it really good.

I have two error/crash logs:
1: http://pastebin.com/GXSFwvmh
2: http://pastebin.com/FfXnMLFq

According to the logs the Leatherworker Career seems to be missing somehow, this leads to a server crash when trading i think. I tried to spawn Leatherworkers with spawner-eggs and tried /summon on a new world without plugins but i was not able to spawn a leatherworker at all, it always leads to a butcher instead.

best regards

EDIT: new links, sorry!

**Comment by hfreeb** [comment]
The crash logs can't be viewed.

> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

**Comment by floomat** [comment]
It should work now, sorry. :)
1: http://pastebin.com/GXSFwvmh
2: http://pastebin.com/FfXnMLFq

**Comment by gabizou** [comment]
This should be fixed once the branch fixing all the catalog type registries is merged in (after more fixes and assurances that an alias system is in place due to some id changes to match the internal id's).

**Comment by phit** [comment]
was fixed months ago with https://github.com/SpongePowered/SpongeCommon/pull/1257, closed
