### ISSUE TITLE
Some InventoryArchetypes aren't fully functional

### ISSUE THREAD

**Issue by poqdavid** [SpongePowered/Sponge#1261]
Well i been attempting to open Anvil, EnchantingTable, Workbench but EnderChest is the only one working that rest just returns no items even when i try to use click event my self

**Comment by Faithcaio** [comment]
Do you mean the output-slot of those inventories?
Custom Inventories currently have no additional logic behind them, so the output-slot will never actually change on its own. (They basicly are chests that look like an Anvil etc.)
The Client however does not know this and displays an item in there regardless.

I am working on allowing to replicate vanilla behaviour of those containers in: 
https://github.com/SpongePowered/SpongeCommon/pull/1221

**Comment by poqdavid** [comment]
Yah well i worked on it and now my plugin works here https://github.com/poqdavid/VirtualTool/commit/304b49ccffd89fa84fe3ff6e3905464dda4975d2 maybe that helps

**Comment by phit** [comment]
Resolved with #1221
