### ISSUE TITLE
Exception while updating neighbours org.spongepowered.common.util.CachedLong2ObjectMap.get

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/Sponge#1266]
Forge: 2254
SF: 2241
MC: 1.10.2

Thats a causetracker issue  with liquids somehow.
This server is heavily modded (FTB Beyond 1.2.1), but this still shouldn't crashed by sponge.
`java.lang.NullPointerException
    at org.spongepowered.common.util.CachedLong2ObjectMap.get(CachedLong2ObjectMap.java:39) ~[CachedLong2ObjectMap.class:1.10.2-2254-5.2.0-BETA-2241]`
Error:
https://pastebin.com/CWV0cmei
Crashlog:
https://pastebin.com/jsTMj7qC

**Comment by Deamon5550** [comment]
Hello #1234
