### ISSUE TITLE
Scoreboard DisplaySlots.BELOW_NAME Bug

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/Sponge#1267]
**Sponge API:** 6.0.0-20170323.180311-60
**Sponge Forge Build:** spongeforge-1.11.2-2227-6.0.0-BETA-2244
**Forge Build:** forge-1.11.2-13.20.0.2227-universal
**Java Version:** 1.8.0_121-b13

About a month ago, I had posted an issue on the Plugin Development forums with Scoreboards. I presume it's a bug, since Aaron1011 didn't get back to me on my last post, so I thought I post it here so you guys can have a look at it.

**Original Post:**
Hello everyone, so I'm working on a PVP plugin, but I ran into a scoreboard problem. So in the first image was screenshotted by a contestant, C88. The problem with this image is that SalvadorZXA (me) received a team scoreboard, but was not suppose to.

![9e23d1f5664cb5814416f5c2d5224188bbea61e2](https://cloud.githubusercontent.com/assets/24198315/24324357/27d96e8e-1153-11e7-9961-5d8d7290e05d.png)

The second image was screenshotted by another contestant, X, in another team. In this image though, the non contestant, SalvadorZXA is seen with a different scoreboard than image 1. Still though, SalvadorZXA was not suppose to receive the scoreboard under it's username.

![196d1a938272a361e24fbe919f78a683f0616136](https://cloud.githubusercontent.com/assets/24198315/24324361/3029fb3a-1153-11e7-98c3-fa8fc9f5ad0a.png)

Through SalvadorZXA's perspective though, neither of the contestants can be seen with their team names under their usernames.

![dce05c9cda24b6e575bf19f179be65820d249faa](https://cloud.githubusercontent.com/assets/24198315/24324364/358fa53e-1153-11e7-875a-f15e2493e4f1.png)

Does anyone have any clue to how this is happening and know of a way to fix this? Thanks.

**Code that sets up the scoreboards:**

Note: This method is called twice. Once to set up one team, and one to set up the other.

```
public static void setUpTDMT(List<Player> teamContestants, Text teamName) {
	
    for (Player player : teamContestants) {

        Scoreboard scoreboard = Scoreboard.builder().build();
        
        Objective teamTagNameObjective = Objective.builder().name(teamName.toPlain()).displayName(Text.of(teamName)).criterion(Criteria.DUMMY).build();
        
        scoreboard.addObjective(teamTagNameObjective);
        
        scoreboard.updateDisplaySlot(teamTagNameObjective, DisplaySlots.BELOW_NAME);
        
        player.setScoreboard(scoreboard);
    }
}
```

**Comment by SjsolisZXA** [comment]
Bumping up report.

**Comment by JBYoshi** [comment]
@SjsolisZXA By "team scoreboard", do you mean the extra like of text for the score? If so, that's intended behavior in vanilla; each player can see one and only one objective under other player's names, and that objective is shown for all players they see, and Sponge can't work around that.

**Comment by SjsolisZXA** [comment]
That would make sense except that I have code that can retrieve another player's "team scoreboard" and read it correctly. The only issue is that it's displayed incorrectly from a contestant's point of view.

**Comment by JBYoshi** [comment]
What I'm trying to say is, `BELOW_NAME` for X's scoreboard is not what other players see below X's name. It's what X sees under other players' names. This is intended behavior.

**Comment by ryantheleach** [comment]
To add to this, not only is it intended behaviour, but unfixable given the current Minecraft codebase.

**Comment by ryantheleach** [comment]
To my knowledge this is intended behavior and unfix-able without client changes. If someone can provide evidence to the contrary feel free to reopen.
