### ISSUE TITLE
InteractEntityEvent.Secondary cancelled : Client isn't updated

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/Sponge#1268]
Hi,
When i cancelled event "InteractEntityEvent.Secondary", the client doesn't receive the update.
Example : [Video](https://youtu.be/6BHe10VJeaQ)

Tested on SpongeVanilla-1.11.2-6.0.0-BETA-234

**Comment by parlough** [comment]
Is this still occurring on the latest bleeding builds?

**Comment by lesbleu** [comment]
I checked on SpongeVanilla 7.0.0 Beta 318 and this bug is present

**Comment by stephan-gh** [comment]
I fixed the two examples in your video (milk and lead) but I'm not sure if I have covered all other cases, special handling was required to make lead work correctly. Let me know if it's broken for anything else.

**Comment by lesbleu** [comment]
Thanks. It's broken when : 
- I add saddle to pig, 
- I color sheep and wolf
- I equip chest with mule and donkey

**Comment by stephan-gh** [comment]
@lesbleu Thanks :) I'll take a look at these as soon as possible.

**Comment by stephan-gh** [comment]
@lesbleu Should be fixed. I've also added name tags which seemed to be also broken.
