### ISSUE TITLE
Exception when a painting is destroyed by TNT

### ISSUE THREAD

**Issue by rexbut** [SpongePowered/Sponge#1270]
The exception is thrown only if the player is not in creative mode.

Log : http://pastebin.com/RrVe0T9V

Tested on SpongeVanilla-1.11.2-6.0.0-234 and bleeding

**Comment by gabizou** [comment]
This is already fixed, we just need to get SpongeVanilla an update.

**Comment by rexbut** [comment]
There is always the error in SpongeVanilla-1.11.2-6.0.0-BETA-239.

Log : https://pastebin.com/GdbvFQep

**Comment by lesbleu** [comment]
There are the same error with bed explosion in nether world
[Logs](https://pastebin.com/njtWna7r)

**Comment by ImMorpheus** [comment]
Not able to reproduce with 1.12 (bleeding branch).
