### ISSUE TITLE
Mixin apply failed mixins.common.core.optional.json:util.math.MixinMutableBlockPos

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/Sponge#1272]
Forge: 2254
SF: 2254

I think I first saw this error with SF 2254, but not 100% sure.
startup forge log:
https://pastebin.com/iHrRhEHq
error:
https://pastebin.com/Q2N3Z6wq

**Comment by Zidane** [comment]
```
<Zidane> !gf field_177997_b 1.10.2
-MCPBot_Reborn- === MC 1.10.2: net/minecraft/util/math/BlockPos$MutableBlockPos.x (cm$a.b) UNLOCKED ===
-MCPBot_Reborn- Name       : b => field_177997_b => x
-MCPBot_Reborn- Descriptor : I
-MCPBot_Reborn- AT         : public net.minecraft.util.math.BlockPos$MutableBlockPos field_177997_b # x
-MCPBot_Reborn- Comment    : Mutable X Coordinate
-MCPBot_Reborn- Last Change: 2014-09-25 20:23:36.116450-04:00 (diesieben07)
```

You've got a mod doing some shady ASM. Remove mods one by one until you find the culprit.

**Comment by asiekierka** [comment]
This is probably a better/more efficient option than removing mods one by one: https://asie.pl/Projects/Minecraft/Mods/EnvironmentChecker
