### ISSUE TITLE
Phase incompatibility on clicking item

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#1278]
I've been observing this warning a lot recently. Not entirely sure what it entails, as I have only a rough understanding of the cause system. Furthermore, I apologize if this is not an issue with Sponge directly - I'm unsure of the conditions required to trigger the warning, and frankly, I'm not really sure how to track it down.

Relevant log: https://gist.github.com/caseif/640c73863eec8a426626ce1c75873dd9

**Comment by gabizou** [comment]
There's more to this than the log you linked. I need what is likely to be an exception thrown before the log, and then the rest of the "block" surrounded in `*`s (That's the entire point of the *s.)

**Comment by caseif** [comment]
There was no exception before that log; however, I've found one that *does* include one.
https://gist.github.com/caseif/084948305deb2cb1a9765a0ccdd8f050

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/df84abf5cf54dd8ad7fba2af4c407648bc828f4c
