### ISSUE TITLE
Sweeping-edge enchantment is not working

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#1279]
The **Sweeping-Edge enchantment** is not modifying the damage made by the sweep-attack. You only deal 1 damage, with or without achievement.
This happens on all: Sponge-Vanilla and Sponge-Forge and Forge without Sponge. Only on pure vanilla minecraft i managed to deal more damage.
So i guess its a Forge AND Sponge Issue? ^^

***Tested with:**
Sponge Vanilla 1.11.2-6.0.0-BETA-239
Sponge Forge 1.11.2-2227-6.0.0-BETA-2260
Forge 2227*

**Comment by gabizou** [comment]
I can fix this on sponge's side, however, we'll have to PR a fix to Forge's side.

**Comment by BrainStone** [comment]
Please do so!

**Comment by parlough** [comment]
Is this still the case on the latest bleeding?

**Comment by phit** [comment]
seems to work fine, tested by throwing 5 zombies in a 1x1 space, to kill them all took about 10 hits with a normal diamond sword and about 4-5 with a diamond sword enchanted with sweeping edge III

Tested with forge-1.12.2-14.23.0.2517 & spongeforge-1.12.2-2503-7.0.0-BETA-2716 bit older but shouldn't really matter in this case

**Comment by phit** [comment]
seems to work fine, tested by throwing 5 zombies in a 1x1 space, to kill them all took about 10 hits with a normal diamond sword and about 4-5 with a diamond sword enchanted with sweeping edge III

Tested with forge-1.12.2-14.23.0.2517 & spongeforge-1.12.2-2503-7.0.0-BETA-2716 bit older but shouldn't really matter in this case
