### ISSUE TITLE
hasPlayedBefore "always" returning true, due to timestamps differing slightly.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1282]
From:

https://forums.spongepowered.org/t/hasplayedbefore-always-return-true/18311

```
 
 @Listener
 public void onLogin(ClientConnectionEvent.Join event) {
 	System.out.println(event.getTargetEntity().hasPlayedBefore());
 	System.out.println(event.getTargetEntity().firstPlayed());
 	System.out.println(event.getTargetEntity().lastPlayed());
 }
```

> Version: SpongeVanilla version 1.11.2-6.0.0-BETA-243
> 
> [16:18:56] [Server thread/INFO] [STDOUT]: [***.onLogin(***.java:32)]: true
> [16:18:56] [Server thread/INFO] [STDOUT]: [***.onLogin(***.java:33)]: SpongeValue{key=Key{Value:Value<Instant>, Query: FirstTimeJoined}, defaultValue=1970-01-01T00:00:00Z, actualValue=2017-04-04T08:18:**55.928**Z}
> [16:18:56] [Server thread/INFO] [STDOUT]: [***.onLogin(***.java:34)]: SpongeValue{key=Key{Value:Value<Instant>, Query: LastTimePlayed}, defaultValue=1970-01-01T00:00:00Z, actualValue=2017-04-04T08:18:**56.104**Z}
> 

I've filed it against Sponge Common until I've done further testing to see if it is unique to vanilla or also occurs on Sponge Forge.

**Comment by ryantheleach** [comment]
Ok, So I think the problem is semantic.

FirstJoined & FirstPlayed are being mixed interchangably, as is LastJoined/LastPlayed.

FirstJoin should be when a player *connects*(successfully) for the first time.
FirstPlayed should be when a player is spawned for the first time.
LastJoined should be when a player last connected (sucessfully)
LastPlayed should be the current instant, if the player is currently online.

There is room for LastConnectionAttempt possibly, but I feel it lies outside this issue.

The 2 firsts should be pretty easily narrowed down to FirstJoin only, for simplicity, the times between them should in most cases be negligible.

However LastJoined vs LastPlayed is very different, in that Last Played could be the current instant, where as LastJoined is very clearly defined as the last time the player logged in.

Reading the current implementation seems to act like LastPlayed as opposed to LastJoined, however the hasPlayedBefore check treats it like LastJoined.

I'm going to make a test plugin to test this.

**Comment by Sir-Will** [comment]
Any news on this issue?

**Comment by ImMorpheus** [comment]
Still happening in 1.12 (bleeding branch).

This was tricky. (PR scheduled for tomorrow (maybe))

You also need to change https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L850

to

```
return new SpongeValue<>(Keys.LAST_DATE_PLAYED, Instant.EPOCH, SpongePlayerDataHandler.getLastPlayed(this.getUniqueID()).get());
```

**Comment by ryantheleach** [comment]
I think it should be an optionaldata, rather then using the Epoch. But that would require an API change.

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1938 Proposes a quick-fix of:

> Quick and dirty fix would be:
> player.firstPlayed().get().truncatedTo(ChronoUnit.MINUTES)
> player.lastPlayed().get().truncatedTo(ChronoUnit.MINUTES)

I support this in the case of fixing it **_now_** without requiring a break.

As a recap of where this is at, most relevant discussion can be found here: https://github.com/SpongePowered/SpongeCommon/pull/1710
