### ISSUE TITLE
Can't retrieve a ParticleType with just the name, need "minecraft:"

### ISSUE THREAD

**Issue by Xenmai** [SpongePowered/Sponge#1286]
I've noticed you can't retrieve a ParticleType with Sponge.getRegistry().getType(ParticleType.class, "heart"), you need to use "minecraft:heart". I was not expecting this because, when retrieving blocks, you can use just "stone" without the need of "minecraft:". Seems like a small issue. Thanks beforehand for your time.

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/pull/1554

**Comment by ImMorpheus** [comment]
PR merged. 

`Sponge.getRegistry().getType(ParticleType.class, "heart")` is still returning Optional#empty()

**Comment by ImMorpheus** [comment]
PR merged
