### ISSUE TITLE
Check behaviour between SV, SF, and V in regards to vanilla spawn protection.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1288]
Kane_Hart reports in IRC that spawn protect covers other worlds other then the overworld.

@ryantheleach 

- [ ] Check behaviour between different platforms and work out if this is a bug or not.
- [ ] Look into making this per world, or offer a fix.

**Comment by JBYoshi** [comment]
See also https://github.com/SpongePowered/SpongeCommon/issues/1453 and https://github.com/SpongePowered/SpongeVanilla/issues/313.

**Comment by stephan-gh** [comment]
Closing, let's move this to a single issue: https://github.com/SpongePowered/SpongeCommon/issues/1453
