### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/Sponge#1292]
Kashike told me to report it here so I'm reporting it here 😄 

Stacktrace: https://hastebin.com/sovivusuzo.css

    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2254-5.2.0-BETA-2272
    Minecraft Forge: 12.18.3.2239

**Comment by dogboy21** [comment]
The log says `SpongeForge : 1.10.2-2254-5.2.0-BETA-2264`.
The issue was fixed in SF 2267+
#1281
