### ISSUE TITLE
GrantAchievementEvent is Implemented on 1.11.2 but not 1.10.2

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/Sponge#1293]
`GrantAchievementEvent` exists in API 5 but is only fired on 1.11.2 SpongeForge servers. Is it possible to have the implementation back ported to 1.10.2?

**Comment by gabizou** [comment]
Due to the breaking changes required for Statistics, it was not implemented for API 5. Refer to https://github.com/SpongePowered/SpongeAPI/pull/1434
