### ISSUE TITLE
#getUnloadedWorlds() returning ALL worlds.

### ISSUE THREAD

**Issue by MarkTwoFive** [SpongePowered/Sponge#1297]
As I found out this evening (and as [discussed on the dev IRC](https://hastebin.com/utaholenut.coffeescript)) ``Sponge.getServer().getUnloadedWorlds()`` returns the ``WorldProperties`` for all worlds regardless of whether they're actually unloaded or not.
As IRC user "blood|wrk" pointed out there seems to be a state check missing [within the function](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/world/WorldManager.java#L528) .

I've created a [code snippet](https://gist.github.com/MarkL4YG/aebf0e604a997d82e5e0c337af4b5483) too.

---
Also included in the snippet is that I think some stuff around these methods is rather confusing.
1. ``World``s have an ``isLoaded`` function which suggests that a ``World`` could be unloaded __regardless of whether it's been stored or just retrieved__ which is misleading since one can't __retrieve__ unloaded ``World`` references. Just keep them from when they were loaded which I would consider bad coding style.
2. ``#getWorlds`` only returns loaded worlds while suggesting that it returns __all__ worlds.
3. ``#getWorld`` returns ``Optional.empty()`` for unloaded worlds. (JD only implicitly states that !loaded equals not existing)
4. If this issue is fixed there's no (single) method of getting __all__ worlds regardless of loading status.

I would recommend providing three methods for this: ``getLoadedWorlds()``, ``getUnloadedWorlds()`` and ``getWorlds`` and I would also suggest either renaming ``isLoaded`` to ``isStillLoaded`` (or something like this) or allowing ``#getWorld`` to return unloaded ``World``s aswell.

The whole latter part is of course just a recommendation or a wish to consider this opinion but I guess that there're developers out there who might think the same.

**Comment by MarkTwoFive** [comment]
~Just a reminder for others: This is not fixed in API 5 (MC 1.10.2)~

Update: Fixed

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/79410aa688649c96d60507df7e190f5985906379
https://github.com/SpongePowered/SpongeCommon/commit/5b0e8eacadf1c3bccd5d2a7871c8a33cc17c7b88
