### ISSUE TITLE
Wrong generator ID return

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/Sponge#1300]
In the 5.2 stable branch running the following code:
```
Sponge.getRegistry().getAllOf(GeneratorType.class).forEach(d -> System.out.println("Gen: " + d.getId()));
```
Will print a line "Gen: largeBiomes", this is incorrect, "large_biomes" is the correct value, attempting to call:
```
registry.getType(GeneratorType.class, "largeBiomes").get();
```

Will result in an exception, as the generator cannot be resolved.

**Comment by kashike** [comment]
Querying for `largeBiomes` should work too, seeing as that is the real name:
`public static final WorldType LARGE_BIOMES = new WorldType(2, "largeBiomes");`

**Comment by Zidane** [comment]
@Deamon5550 Thoughts?

**Comment by Deamon5550** [comment]
Seems to be no longer an issue as of https://github.com/SpongePowered/SpongeCommon/commit/9d594880e16905f61784f37d0bc890da05981caf
