### ISSUE TITLE
DataView deserialization fails at enchantments

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#1307]
I have this code: https://gist.github.com/randombyte-developer/f9d0ecc09cccd56ed081acac23423477

It takes the item the player is holding and serializes it:
1. `toContainer()`
2. `DataTranslators.CONFIGURATION_NODE.translate()`
3. `ConfigurationLoader#save()`

The debug output for a Smite V book is: 
```
{
  "ContentVersion": 1,
  "ItemType": "minecraft:enchanted_book",
  "Count": 1,
  "UnsafeDamage": 0,
  "UnsafeData": {
    "StoredEnchantments": [
      {
        "lvl": "5",
        "id": "17"
      }
    ]
  }
}
```

The deserialization:
1. `ConfigurationLoader#load()`
2. `DataTranslators.CONFIGURATION_NODE.translate()`
3. `Sponge.getDataManager().deserialize()`

The item given to the player should be the same he is holding. But the deserialization of the enchantment data doesn't work properly: The player gets a book with Protection 0 regardless of the original enchantment.

[Forum topic](https://forums.spongepowered.org/t/enchantments-couldnt-retreat-due-itemstack-serialization/18425/17?u=randombyte)(screenshots and more explanation).

**Comment by randombyte-developer** [comment]
This problem can be solved by using `HoconConfigurationLoader` instead of `GsonConfigurationLoader`: [Forum post](https://forums.spongepowered.org/t/enchantments-couldnt-retreat-due-itemstack-serialization/18425/20?u=randombyte).
Since the recommended config format is Hocon, is this still regarded as an issue?

**Comment by stephan-gh** [comment]
Once merged, you should use the [JSON data format](https://github.com/SpongePowered/SpongeAPI/pull/1363) to serialize/deserialize to JSON.

**Comment by stephan-gh** [comment]
@randombyte-developer Would you mind giving the JSON data format a try now that it is merged?

**Comment by randombyte-developer** [comment]
I'll test it soon.

**Comment by randombyte-developer** [comment]
@Minecrell Am I supposed to do `DataFormats.JSON.write(container)` and write that string as the value of the config node? Doing it this way works but doesn't look the same as before.

Example:
Before:
```json
test-node = {
    "ItemType":"minecraft:cookie"
    ...
}
```

Now:
```json
test-node = "{
    \"ItemType\":\"minecraft:cookie\"
    ...
}"
```

I am just asking to confirm I am doing it the correct way.

**Comment by TheoKah** [comment]
I'm having the same problem.
When I use `ItemStack.equalTo()` between the source object and the one created after a serialize/deserialize they do not match.

This is a problem when using `Inventory.query()` to poll items using an ItemStack created from DB.
(Using `Inventory.query()` with ItemType doesn't do the trick because "too permissive")

**Comment by stephan-gh** [comment]
@randombyte-developer You should only use the JSON data format if you want to serialize data entirely to JSON. The configurate translator exists when you want to write data into the configuration.

**Comment by stephan-gh** [comment]
I've tested it with this code and it works correctly (I get the same enchanted book again):

```java
@Plugin(id = "testdeserialization")
public class TestDeserialization {

    @Listener
    public void onPlayer(SendCommandEvent event, @Root Player player) throws IOException {
        doStuff(player);
    }

    public static void doStuff(Player player) throws IOException {
        // serialize
        DataView container1 = player.getItemInHand(HandTypes.MAIN_HAND).get().toContainer();
        String data = DataFormats.JSON.write(container1);
        System.out.println(data);

        // deserialize
        DataView container2 = DataFormats.JSON.read(data);
        ItemStack itemStack = Sponge.getDataManager().deserialize(ItemStack.class, container2).get();

        player.getInventory().offer(itemStack);
    }
}
```

Tested on latest SV 1.12 (bleeding branch).

**Comment by stephan-gh** [comment]
Tested the same with `DataFormats.HOCON` (uses the configurate translator internally) and it works too.

**Comment by randombyte-developer** [comment]
@Minecrell ok, the JSON data format and hocon did work for me but I wanted to ask if I'm doing it correctly. Thanks.
Doing it with gson was wrong.
