### ISSUE TITLE
Block's won't update after explosion

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1314]
1. Place gravel
2. Place TNT
3. Explode tnt
4. Gravel won't fall.
Tested on:
spongevanilla-1.11.2-6.0.0-BETA-250

**Comment by gabizou** [comment]
Could you show a picture of where the gravel/sand is placed in relation to TNT? Otherwise, the gravel/sand are supposed to simply be removed, not "fall".

**Comment by XakepSDK** [comment]
I can't add screenshot now. But you can try it yourself. Place TNT and
place around TNT gravel. Make 3x3x12 gravel structure with TNT in bottom
middle. Activate TNT and wait.
Sorry for my english.

**Comment by XakepSDK** [comment]
https://puu.sh/vrjNS/bc4efd5fff.png
https://puu.sh/vrjOE/d5c99d6dbe.png
This seems not explosions issue, this happens after world generation. Water won't flow, sand won't fall, until i touch it.

**Comment by gabizou** [comment]
> This seems not explosions issue, this happens after world generation. Water won't flow, sand won't fall, until i touch it.

You were reporting gravel not falling, is that still an issue with explosions? Please avoid getting off track.

**Comment by XakepSDK** [comment]
See screenshot. There is issue with block updating. At first, i saw this issue only after TNT explosion, but after 5 mins playing, i found same issues with world generated blocks. Sand won't fall, until i place/break block on this sand, water won't flow.

**Comment by Deamon5550** [comment]
That is how it works in vanilla, all physics updates are disabled during world generation.

**Comment by XakepSDK** [comment]
Oh, this is all my bad english. Sorry, guys. I make video with
demonstration, 14:00 gmt+6

**Comment by XakepSDK** [comment]
No video, sorry.
Gravel:
1. https://puu.sh/vskBd/39bc5ccec0.png
2. https://puu.sh/vskC0/cbf3696aef.png
3. https://puu.sh/vskCp/7b3ad3902a.png
4. https://puu.sh/vskD7/7dffb4be10.png

Sand:
1. https://puu.sh/vskE6/2cb15c926b.png
2. https://puu.sh/vskEx/4ae32f3a00.png
3. https://puu.sh/vskEU/27e865719f.png
4. https://puu.sh/vskFn/a5019c2800.png
5. https://puu.sh/vskFP/7935cc4ba8.png
6. https://puu.sh/vskFP/7935cc4ba8.png
7. https://puu.sh/vskGC/a957de14c0.png

Gravel falled after 1 block break, sand falled after i break first layer and 1 block from second layer.

**Comment by gabizou** [comment]
Funny that this only happens in SpongeVanilla. The systems involved are from SpongeCommon I believe, so will have a fix very soon.

**Comment by ImMorpheus** [comment]
As noted by the SpongeVanilla issue, this is still happening with 1.12, we can remove the 1.11 label.
