### ISSUE TITLE
potion effect negative amplifier not allowed

### ISSUE THREAD

**Issue by jaymsDooku** [SpongePowered/Sponge#1319]
There are some potion effects that accept a negative amplifier such as the Jump Boost Potion Effect, but I'm unable to build a Potion Effect with a negative amplifier because the builder does not accept negative amplifier values.

**Comment by ST-DDT** [comment]
The API javadocs have to be adjusted as well. https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/effect/potion/PotionEffect.java#L138

**Comment by stephan-gh** [comment]
Please re-open this as SpongeAPI issue: https://github.com/SpongePowered/SpongeAPI/issues
