### ISSUE TITLE
EnderChest crash

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1320]
Crash log:
https://pastebin.com/mZ1dZxcZ
How to reproduce?
1. Place ender chest
2. Get empty map item
3. Open ender chest
4. Drag map from player inventory
5. ????
6. PROFIT!

Plugins:
WorldEdit
FastAsyncWorldEdit
LuckPerms
GriefPrevention
Nucleus
NucleusMixins

**Comment by Faithcaio** [comment]
fixed in https://github.com/SpongePowered/SpongeCommon/commit/ba06972bdd9d87052f08de922132d151f9ec666b
