### ISSUE TITLE
Problem with DataFormats.NBT for saving and reading stack data

### ISSUE THREAD

**Issue by poqdavid** [SpongePowered/Sponge#1323]
Here is my source for saving and reading data https://github.com/poqdavid/VirtualTool/blob/master/src/main/java/io/github/poqdavid/virtualtool/Utils/Tools.java and it messes up all books like this in the image http://imgur.com/a/slBAs also a sample NBT data that my plugin saves from a itemstack https://www.dropbox.com/s/qazpjuy2g7s7n0d/data.dat?dl=0

- SpongeForge version: 5.2.0-BETA-2229

**Comment by poqdavid** [comment]
I just checked with latest stable version and I have the same problem

**Comment by dualspiral** [comment]
I think this is the same issue as https://github.com/SpongePowered/SpongeCommon/issues/509 in that the data manipulator for "writable" books saves the data into the wrong format - I imagine you get conversion issues in the same way as the table in https://github.com/SpongePowered/SpongeCommon/issues/1198#issue-207095837?

**Comment by poqdavid** [comment]
Well i made it in my source to check and deal with errors so it wont load items if there is a error with them and the odd thing is this wont throw any errors and yes looks like there are problems with that part and if those get fixed as soon as possible it will be really good

**Comment by ImMorpheus** [comment]
dual is correct.
content of dat file:

```
"": {
    ContentVersion: 1
    ItemType: "minecraft:written_book"
    UnsafeDamage: 0
    Data: [
        {
            DataClass: org.spongepowered.common.data.manipulator.mutable.item.SpongeAuthorData
            ManipulatorData: {
                ContentVersion: 1
                BookAuthor: "{\"text\":\"poqdavid\"}"
            }
        },
        {
            DataClass: org.spongepowered.common.data.manipulator.mutable.item.SpongePagedData
            ManipulatorData: {
                ContentVersion: 1
                BookPages: ["{\"text\":\"{\\\"text\\\":\\\"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz\\\"}\"}",]
            }
        },
        {
            DataClass: org.spongepowered.common.data.manipulator.mutable.item.SpongeGenerationData
            ManipulatorData: {
                Generation: 0
                ContentVersion: 1
            }
        },
    ]
    Count: 1
    UnsafeData: {
        pages: ["{\"text\":\"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz\"}",]
        author: poqdavid
        title: Test
    }
}
```

Fixed since the PR was merged a long time ago
