### ISSUE TITLE
[1.10.2] EnderDragon crashes server when nearly dead ontop of the portal

### ISSUE THREAD

**Issue by xF4m3** [SpongePowered/Sponge#1327]
Sometimes when we spawn an EnderDragon and try to kill him, when there is around 1/5-1/7 of the health left, it crashes the Server while the Dragon is sitting on top of the portal. If that Happens the only way to kill him is using commands. 

SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a26c654
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2291
    Minecraft Forge: 12.18.3.2281

I added the crash report as a file.

[crash-2017-05-01_15.04.20-server.txt](https://github.com/SpongePowered/SpongeCommon/files/967888/crash-2017-05-01_15.04.20-server.txt)

**Comment by phit** [comment]
Closing this, if it's still an issue please report it again on the [SpongeForge ](https://github.com/SpongePowered/SpongeForge) tracker.
