### ISSUE TITLE
Player.sendMessage(TranslatableText)

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1328]
Player.sendMessage(TranslatableText) send translation key. Is it ok?
I can get manually right translation, using TranslatebleText.getTranslation().get(Locale).

**Comment by stephan-gh** [comment]
Please use IRC for questions like this.

You can use `TranslatableText` using any translations available on the client (e.g. the ones added by Mojang for Vanilla Minecraft and the ones added by client mods) but sending custom translations is not possible using `TranslatableText`.

**Comment by ST-DDT** [comment]
The translatable key only works if the client has a translation for that key in his reourcepacks. If you execute the later code on the server the server will use his internal translations to translate it server side. If the side does not have a translation it will return/show only the translation key
