### ISSUE TITLE
Pistons sometimes dissapearing

### ISSUE THREAD

**Issue by vectrixdevelops** [SpongePowered/Sponge#1329]
**I am currently running...**

- SpongeVanilla version: 1.11.2-6.0.0-BETA-255
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2292
- Java version: 8

Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

**What is the expected result?**
Pistons / Sticky Pistons should not disappear at all after being used.

**What is the current result?**
Sometimes when a piston or sticky piston is used they disappear, (like magic!?). They also leave the space where the piston was occupied, not allowing you to place anything there. This may also include blocks they are interacting with.

No error is thrown.

**Comment by johnfriedrich** [comment]
Latest is not a version.
We experience that too. It's a thing since that build that changed causetracker to be global or something like that. It was already fixed before that commit.
We are on
Forge: 2281
SF: 2292
