### ISSUE TITLE
Configuration default values

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1330]
If i do like this:
```
ConfigurationNode root = ...;
String str = root.getNode("testNode").getString("Test defaults");
loader.save(root);
```
No default value saved in configuration file.

Currently i have this monstrous "fix":

```
ConfigurationNode tableNameNode = databaseNode.getNode("tableName");
tableName = tableNameNode.getString();
if(StringUtils.isEmpty(tableName)) {
    tableName = "purchases";
    tableNameNode.setValue(tableName);
}
```

Is it right?

**Comment by Deamon5550** [comment]
`getString(default)` returns the node as a string or the given default value of not found. It does not set that default value back to the configuration node. If you want to set default values into a configuration to save it you have to actually set them.

Any further issues with configurate should be opened with them https://github.com/zml2008/configurate
