### ISSUE TITLE
[1.10.2] Invasion server crash

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#1331]
Invasion modpack server crashes when a player gets near a mobspawner containing a wasp from BiomesOPlenty. (Found mob type when checking affected region data in NBT editor)

Crash Report: 
[cZJT8s8b.txt](https://github.com/SpongePowered/SpongeCommon/files/972314/cZJT8s8b.txt)

Minecraft: 1.10.2
SpongeForge: 1.10.2-2281-5.2.0-BETA-2300
Minecraft Forge: 12.18.3.2281
Operating System: Linux

**Comment by phit** [comment]
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/1422
