### ISSUE TITLE
Cannot load custom world

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/Sponge#1333]
When trying to load a world programmatically, the following warning occurs:
`[02:32:14 ERROR] [Sponge]: Unable to load world [.\world\lobby-world\play-world]. We cannot find its folder under [.\world\lobby-world].`

The folder structure is as follows:
- world
- - lobby-world
- - play-world

All three worlds are generated top-level worlds which were copied and renamed (which should be possible!).
I tried removing the `config` directory, but this doesn't change anything.

Tested with SpongeVanilla _1.11.2-6.1.0-BETA-2_.

**Comment by stephan-gh** [comment]
Can you post the code you're using to load the world?

**Comment by stephan-gh** [comment]
Closing this, hard to tell what's causing this without the code used to load the world.
