### ISSUE TITLE
New dimension with gregtech

### ISSUE THREAD

**Issue by sintaxcz** [SpongePowered/Sponge#1336]
Hello i have problem when i entering portal to another dimension for a first time (generating new world)
i got server error for
[gregtech]: at org.spongepowered.common.event.tracking.CauseTracker.notifyBlockOfStateChange(CauseTracker.java:402)
and server stucks and i get nonstop of theese gregtech errors but normal overworld vas generated ok with no errors

with new version of sponge 1.10.2-2281-5.2.0-BETA-2303

**Comment by Deamon5550** [comment]
We need the full log from your server

**Comment by stephan-gh** [comment]
Please re-open the issue with a full log on https://github.com/SpongePowered/SpongeForge/issues
