### ISSUE TITLE
Retrieving SlotIndex not working as expected

### ISSUE THREAD

**Issue by DawnTheFawn1** [SpongePowered/Sponge#1344]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2312
- Java version: 1.8.0_91
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: LuckPerms, Pixelmon, Pixelmon-Daycare(hybrid plugin I was testing this on)

**What is the expected result?**
When I run the code provided, it will show the index of the clicked slot
**What is the current result?**
It only shows the index of a slot which contains an item.

test code: https://gist.github.com/RysingDragon/87ea22c92f9c31bfbcb34801e64ce7a5
example of it in action: https://gyazo.com/9ed19352b476bd111c3a5d2f12c2c3cf
stacktrace: https://gist.github.com/RysingDragon/f169ae2ecc1f4c5aa976887d283515e6
full fml-server-latest.log : https://gist.github.com/RysingDragon/8b1b017662875c5e805f8750c3533088
@Faithcaio blood told me to ping you on this

**Comment by NeumimTo** [comment]
@JBYoshi Its not working, using your code you wrote in my pr

Im facing problem which might related to this issue. 

listening to the event ClickInventoryEvent

```Java
  int index = event.getTargetInventory().getProperty(i, SlotIndex.class, "slotindex").get().getValue();
```

returns correct value as excepted, however listening to the event ChangeInventoryEvent.Pickup 

```Java
event.getTargetInventory().getProperty(i, SlotIndex.class, "slotindex")
```

Returns an empty optional. 

@RysingDragon Even its not recommanded and someone will yell at me again, but if you need it typecast to SlotAdapter (you will need spongecommon as a dependency) and call getOrdinal

**Comment by Faithcaio** [comment]
@NeumimTo The issue with the Pickup Event is that the transaction did not happen yet. (the other events are fired after the transaction and are rolled back when canceled)
You cannot know the Slot for sure at this time.
Also don't use SlotAdapter^^

**Comment by Faithcaio** [comment]
fixed in 63910c74

**Comment by NeumimTo** [comment]
@Faithcaio good to know. How does one get the slot into which will be the picked up item assigned? Is there any event which is called after the transaction is processed?

**Comment by Faithcaio** [comment]
You cannot know for sure before it actually happens.
Don't think there is currently.
