### ISSUE TITLE
NullPointerException in ConfigurateTranslator

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#1346]
**I am currently running...**

- SpongeForge version: 
- SpongeVanilla version: `1.11.2-6.1.0-BETA-3`
- Java version: `openjdk version "1.8.0_111"`
- Operating System:

 - [X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
  - Only the test plugin pasted below

**What is the expected result?**
Ähm, no exception.
**What is the current result?**
A NPE.

Stacktrace: https://pastebin.com/6tWm7sBe

---

I am trying to use a `BlockState` as a key for a map that is going to be serialized to a config file(here `Map<BlockState, Integer>`).

Here is the test plugin: https://gist.github.com/randombyte-developer/60c06fefbad4a8e2497313d145e770ce

The plugin saves and loads the `Config` object.
The problematic line seems to be [this one](https://github.com/SpongePowered/SpongeCommon/blob/7000d73eabead5e4636fe90a12a6c5230f1d5ec3/src/main/java/org/spongepowered/common/data/persistence/ConfigurateTranslator.java#L83). The key of the node is tried to be accessed but it is null. I think this is because this deserializer was written for translating the value but not a key.
The serialization works fine. The generated config is:
```
map {
    "minecraft:diamond_block"=12
}
```

**Comment by simon816** [comment]
I believe this is the same as https://github.com/SpongePowered/SpongeCommon/issues/1142

**Comment by randombyte-developer** [comment]
@simon816 You are right, I just worked around it now by not using `BlockState` as a key.
