### ISSUE TITLE
Inventory slot set

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1347]
This:
`Inventory.query(SlotIndex.of(0)).set(ItemStack);`
sets slot 9(first - 0)
This:
`Inventory.query(SlotPos.of(0,0)).set(ItemStack);`
sets slot 0

Inventory creating:
```
inventory = Inventory.builder()
                .of(InventoryArchetypes.CHEST)
                .property(InventoryDimension.PROPERTY_NAME, InventoryDimension.of(9, 6))
                .build(container);
```

**Comment by Favorlock** [comment]
Can confirm that this does happen.

**Comment by XakepSDK** [comment]
Fixed?

**Comment by Faithcaio** [comment]
Well actually its not entirely wrong. You can see this when you set more items that what fits in one slot.
In a Gridinventory there are multiple Slots that have an Index of 0:
![img](http://i.imgur.com/XwJc6GB.png)
Each Row and Column have a Slot 0.
