### ISSUE TITLE
BlockState gets serialized as CatalogType to config with ObjectMapping

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#1348]
**I am currently running...**

- SpongeForge version: 
- SpongeVanilla version: `1.11.2-6.1.0-BETA-3`
- Java version: `openjdk version "1.8.0_111"`
- Operating System:

 - [X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
   - Only the test plugin

**What is the expected result?**
`BlockState` getting serialized as a BlockState in the config, so like

```
{
    BlockState="minecraft:wool[color=red]"
    ContentVersion=2
}
```

**What is the current result?**
`BlockState` getting serialized as a `CatalogType`, so like `minecraft:wool[color=red]`.

Crash when trying to deserialize `BlockState`: https://pastebin.com/x7shJaxq

---

It is like #1171 but the fix in 53f44ab(@gabizou) doesn't actually fix it.

The problem lies in configurate which chooses an (in)appropriate serializer. I think the fix by gabizou only works when directly setting the value of a config node with `setValue(...)` but not as I do it with ObjectMapping.
The problematic line is [this one](https://github.com/zml2008/configurate/blob/3dcbf1266a60f0592a3db8070bc744cc03a20caa/configurate-core/src/main/java/ninja/leaping/configurate/objectmapping/ObjectMapper.java#L108). The [get() method is here](https://github.com/zml2008/configurate/blob/3dcbf1266a60f0592a3db8070bc744cc03a20caa/configurate-core/src/main/java/ninja/leaping/configurate/objectmapping/serialize/TypeSerializerCollection.java#L39). The get method returns the `CatalogTypeTypeSerializer` instead of the needed `DataSerializableTypeSerializer`.

**Comment by dualspiral** [comment]
Based on 53f44ab, I would think that the intention is that the `CatalogTypeTypeSerializer` should override the `DataSerializableTypeSerializer`, not the other way around as you suggest. That would make sense, as the catalog ID would be all that is needed to recreate the data structure in that scenario. It seems to me that _serialising_ is working fine, but the problem is that Configurate selects a different deserialiser.

I should be able to coerce Configurate into doing this right.

**Comment by dualspiral** [comment]
[I used this test code](https://gist.github.com/dualspiral/093d818440f9bb267e8c09333ec137fd) to test that my fix works successfully, results are below it. It confirms that `DataSerializables` that are not `CatalogTypes` can still be processed as before. `CatalogType`s will now _always_ go through the `CatalogTypeTypeSerializer`.
