### ISSUE TITLE
Utilizing Legacy Data Registration Provided by Sponge Throws IllegalArgumentException

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#1352]
**I am currently running...**

- SpongeForge version: 1.11.2-2282-6.0.0-BETA-2297
- SpongeVanilla version: --
- Java version: 1.8.0_45
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

**What is the expected result?**
Sponge should give a warning that ID's need to be transferred over to the new system, but the plugin should still function.
**What is the current result?**
Currently an IllegalArgumentException is thrown with the message "Data ID must be formatted correctly!"

[Server Log](https://gist.github.com/Zerthick/a95d83ed54e0b77f695918904451deb7#file-fml-server-latest-log-L3557)

**Comment by gabizou** [comment]
This was fixed a while ago. Go ahead and bump to the latest stable versions (SpongeForge wasn't building stable-6, but it finally built one now).
