### ISSUE TITLE
AbstractMethodError when calling player.offer(Keys.GAME_MODE, gameMode, cause)

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/Sponge#1355]
When running the call `player.offer(Keys.GAME_MODE, gameMode, cause)` *(`player` being an `org.spongepowered.api.entity.living.player.Player`, `gameMode` an `org.spongepowered.api.entity.living.player.gamemode.GameMode`, and `cause` an `org.spongepowered.api.event.cause.Cause` object)* I get an `java.lang.AbstractMethodError`, indicating the method is not implemented.

**I am currently running...**
- SpongeVanilla version: 1.11.2-7.0.0-BETA-268
- Java version: 1.8.0_131
- Operating System: Windows 10

**What is the expected result?**
That this method is doing the same as `player.offer(Keys.GAME_MODE, gameMode)` but also adding an cause.

**What is the current result?**
It crashes with an `java.lang.AbstractMethodError`.

**Log**
[latest.log](https://github.com/SpongePowered/SpongeCommon/files/1005507/latest.txt)

**Comment by BrainStone** [comment]
Releated:
https://pastebin.com/n2gtB7bM

I added `-Dmixin.checks.interfaces=true` when starting the server and also called `/sponge audit` as asked by @Deamon5550

**Comment by parlough** [comment]
This is no longer an issue on bleeding due to the removal of this method in https://github.com/SpongePowered/SpongeAPI/pull/1370

Will keep it open as the issue most likely remains on 1.11 and possibly 1.10

**Comment by parlough** [comment]
No longer an issue in stable-7 or bleeding due to removal of the method.
