### ISSUE TITLE
Fix minecraft /locate command for blacklisted structures?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1359]
In deamons comment on 
https://github.com/SpongePowered/SpongeCommon/pull/887#issuecomment-267802463

He states that

"
A better fix that we can do that I was talking about earlier in irc is to prune the nbt data for a structure when that structure is 'complete'. Just disabling saving breaks both the structure generation and the locate command, but 99% of the space in the nbt is the children list which can be discarded after the structure is fully formed.
"

This is the mixin responsible for the current bleeding version

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/optimization/world/gen/structure/MixinMapGenStructure_Structure_Saving.java

Was this comment ever addressed? or was it decided to not act upon it?

**Comment by Deamon5550** [comment]
I just haven't gotten around to fixing it yet, but its still on the table.

**Comment by ImMorpheus** [comment]
We don't have structure config settings for saving so this does not apply anymore.
