### ISSUE TITLE
Utilizing Legacy Data Registration Provided by Sponge Throws NullPointerException

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#1364]
**I am currently running...**

- SpongeForge version: spongeforge-1.11.2-2282-6.1.0-BETA-2343
- SpongeVanilla version: 
- Java version: 1.8.0_45
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

**What is the expected result?**
Sponge should give a warning that ID's need to be transferred over to the new system, but the plugin should still function.
**What is the current result?**
Currently a NullPointerException is thrown with the message "Data name is null!"

[Log](https://gist.github.com/Zerthick/c159ad2e82b055e5bc8ef1df4ec6fcac#file-fml-server-latest-log-L3569)

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/c928639ae8fcb4a51c1a4fb128c443870e78baaa
