### ISSUE TITLE
EntityUniverse#spawnEntities returns whether event was cancelled, not whether entities were spawned

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#1365]
As seen [here](https://github.com/SpongePowered/SpongeCommon/blob/3634fcb/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L1093), the method is returning an improper value per [its JavaDoc](https://jd.spongepowered.org/6.0.0/org/spongepowered/api/world/extent/EntityUniverse.html#spawnEntities-java.lang.Iterable-org.spongepowered.api.event.cause.Cause-). Unsure of whether this is an OCD fix since it constitutes a fairly significant bug.

**Comment by Deamon5550** [comment]
The return is actually useless regardless of what it is changed to return. It should instead return a list of entities that were actually spawned.

**Comment by caseif** [comment]
I agree it could be improved; however, this is still a bug in API 5 and 6 implementations.

**Comment by ryantheleach** [comment]
I meant to close this when it was moved to SpongeAPI
