### ISSUE TITLE
Error : DetonateExplosiveEvent

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/Sponge#1366]
- SpongeVanilla version: 1.11.2 Beta 269
- Java version: 8 Update 131
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

When I cancelled the explosion of TNT, the server crash with this [error](https://pastebin.com/jMBEbE6T)

**Comment by theboomer** [comment]
>>> PluginContainer must be at the ROOT of a cause!

You're probably resetting block volumes, or spawning entities, or something similar that requires a cause provided as part of your process (or some other plugin on it is) and the cause provided is not using the plugincontainer as the cause, but rather the plugin itself (or 'this') etc.  Unfortunately, you can't tell from the stacktrace where its from, but thats what its from - providing a cause incorrectly.  So start there, if you have any code that issues a cause.

**Comment by JBYoshi** [comment]
No, I took a quick look into it. Sponge provides the faulty cause - it replaces the TNT block when the detonation event is cancelled.
