### ISSUE TITLE
Can't teleport players in custom world

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1369]
`minecraft:tp from to` says "Unable to teleport bec. players are not in the same dim."
`tp from to` errors "cannot cast SpongeUser to Player"
I can use `tp my-nick` to tp.

**Comment by dualspiral** [comment]
That latter bit about `tp from to` is a Nucleus command and thus a Nucleus issue, nothing to do with Sponge. I am aware of it.

**Comment by XakepSDK** [comment]
Aw, sorry. Wait a sec.
