### ISSUE TITLE
MessageChannel event not fired when MessageChannel.TO_ALL.send(...) is used

### ISSUE THREAD

**Issue by LJack2k** [SpongePowered/Sponge#1374]
The event `MessageChannel`, `MessageChannelEvent `or `MessageChannelEvent.chat` doesnt get fired when the method `MessageChannel.TO_ALL.send(...)` is being used to send the message in the first place.

**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2353
- Java version: 8
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows
- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Discord Bridge, EconomyLite, LuckPerms, Sponge Nation Chat Tag, Nations, Nucleus, OxideServerChat

**What is the expected result?**
The event being fired

**What is the current result?**
Nothing happens

**Comment by LJack2k** [comment]
Is there any progress update on this? I would really like to finish my mod.

**Comment by Zidane** [comment]
@kashike 

Status?

**Comment by LJack2k** [comment]
any idea when this get through?

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/1566
