### ISSUE TITLE
Data registration issue(sponge issue)

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1378]
`org.spongepowered.api.data.DataRegistrationNotFoundException: Could not locate a DataRegistration for class class org.spongepowered.common.data.manipulator.mutable.block.SpongeLogAxisData`

Test code:
```
    @Listener
    public void onRC(InteractBlockEvent.Secondary.MainHand event, @Root Player player) {
        String state = event.getTargetBlock().getState().toString();
        Optional<BlockState> type = Sponge.getGame().getRegistry().getType(BlockState.class, state);
        ItemStack build = ItemStack.builder().fromBlockState(type.get()).build();
        player.getInventory().offer(build);

        player.sendMessage(Text.of(state));
    }
```

How to reproduce:
1. Right click any log.
Fails at `fromBlockState`.

Tested version:
spongeforge-1.11.2-2282-7.0.0-BETA-2348

**Comment by gabizou** [comment]
@XakepSDK Do you have a stack trace handy?

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/65b18b4dce1021d97ac4d13d1104beb9c7305c07
