### ISSUE TITLE
Currently no way to create an itemstack with a number variant

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/Sponge#1379]
As far as I know, there is currently no possible way to generate an item stack with a *number* variant. For instance, you can create birch planks by telling the item which variant it is, but if someone was using a mod that relied on number variants or just wanted to use a more general variant numbering scheme, it's virtually impossible to do so. At least, without some serious hacky code that I haven't found.

![image](https://cloud.githubusercontent.com/assets/6946558/26566437/cb16abe6-44b8-11e7-88a4-a6b3d40e02c2.png)
In this image, the 3 is the number variant, jungle being the named variant. It would be nice if we could use the number rather than the name, and would make stuff much more compatible.

**Comment by JBYoshi** [comment]
# DISCLAIMER to anyone reading this: Most of the time, you should just use Sponge's Data API. If the functionality you need isn't there yet, submit a PR for a new `DataManipulator`.

But if you *really* can't use the Data API (example: you use mods, or need backwards compatibility with other server software), read this...

### Option 1: With ForgeGradle
Cast the Sponge `ItemStack` to a Minecraft `ItemStack` and put your data in there.

### Option 2: Without ForgeGradle (untested)
```java
DataContainer container = ItemStack.of(ItemTypes.PLANKS, 1);
container.set(DataQuery.of("UnsafeDamage"), 3);
// If you want:
DataView nbt = container.createView(DataQuery.of("UnsafeData"));
// Stick the NBT data in there before the build() call.
ItemStack stack = ItemStack.builder().build(container);
```

**Comment by gabizou** [comment]
The block states themselves are the best way to create these "numbered items". There is JBYoshi's way of doing it as well with the API only. 

Otherwise, damage values are still not supported and will likely never be supported as the game has been moving away from it slowly and surely.
