### ISSUE TITLE
Using setLocation() and transferToWorld() in MoveEntityEvent.Teleport.Portal causing issues

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/Sponge#1385]
All the info can be found in this issue: https://github.com/SpongePowered/SpongeAPI/issues/1568

spongeforge-1.10.2-2281-5.2.0-BETA-2353

**Comment by Zidane** [comment]
@bloodmc You wrote the portal code, review the API issue and let me know your thoughts. Be sure to read it all.

**Comment by ryantheleach** [comment]
This issue is solely about:

>Found another weird issue with this.
>Doing player.getLocation() before event.setCancelled(true); will give you the coordinates of the destination (nether) but the world of the start position (overworld, where I entered the portal).

>How can I get the start/enter location when I don't cancel the event?

Correct?

**Comment by Sir-Will** [comment]
As far as I remember yes.

**Comment by ImMorpheus** [comment]
Not able to reproduce on 1.12 (bleeding branch):

```
    @Listener
    public void onTp(MoveEntityEvent.Teleport.Portal event, @Root Player player) {
        Location<World> l = player.getLocation();
        System.out.println(l);
    }
```
Create a portal in the overworld: (coordinate of the start position and world of the start position)
```
[STDOUT]: Location{(65.56237176334476, 66.0, -51.94971009418808) in WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld}}
```

Once in the nether, use the portal to go back to the overworld: (coordinate of the start position and world of the start position)
```
[STDOUT]: Location{(21.806176517551723, 78.7531999805212, -1.9138701075136444) in WorldServer{LevelName=DIM-1, DimensionId=-1, DimensionType=minecraft:nether}}
```

Note: cancelling the event doesn't change the outcome.

**Comment by ryantheleach** [comment]
@ImMorpheus Thanks.
