### ISSUE TITLE
LaunchProjectileEvent Does Not Fire

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/Sponge#1397]
Sponge Build: spongeforge-1.11.2-2227-6.0.0-BETA-2159
Sponge API Build: 6.0.0-20170217.091623-41
Forge Build: forge-1.11.2-13.20.0.2227-universal
Java Version: 1.8.0_121-b13

Hello, I have the following listeners that do not function at all. Unless I'm doing something wrong, I would like to know if this can be looked at. Thanks!

@Listener
public void onPlayerConsumption(UseItemStackEvent.Start event) {
	event.setCancelled(true);
}

@Listener
public void onPotionThrow(LaunchProjectileEvent event) {
    event.setCancelled(true);
}

**Comment by johnfg2610** [comment]
are you registering the event listener? or is this in the main class? also try updating your version for sponge/forge see if it works in the newer versions

**Comment by SjsolisZXA** [comment]
The listeners are registered and I've updated to spongeforge-1.10.2-2281-5.2.0-BETA-2401, but the issues are still present to this day. My issue was originally posted [here](https://github.com/SpongePowered/SpongeAPI/issues/1495) months ago, but was told to re-post it here.

**Comment by darichey** [comment]
I can also confirm that neither `TargetProjectileEvent` nor any of its children are fired using
spongevanilla-1.12-7.0.0-BETA-290
spongeapi-7.0.0-20170703.084035-18

**Comment by ryantheleach** [comment]
I can confirm that LaunchProjectile event did not fire for players, skeletons, or dispensers shooting arrows on [SpongeForge Bleeding 7789e67bbd1ef2ed2411d08d23c1ea006ef7aa56](https://github.com/SpongePowered/SpongeForge/commit/7789e67bbd1ef2ed2411d08d23c1ea006ef7aa56)

by using https://gist.github.com/ryantheleach/2152cebe0e3c90874c39e69566df4b66

**Comment by SjsolisZXA** [comment]
Bumping up report.

**Comment by phit** [comment]
still an issue with https://github.com/SpongePowered/SpongeCommon/commit/caccfa4f325396c866bb803d51ee0c3763e8d073 tested both `LaunchProjectileEvent` & `UseItemStackEvent.Start`

**Comment by ImMorpheus** [comment]
Partially able to reproduce on 1.12
UseItemStackEvent.Start is working fine.

LaunchProjectileEvent is broken.

**Comment by Zidane** [comment]
@ImMorpheus 

Want to work on LaunchProjectileEvent?

**Comment by RedNesto** [comment]
@Zidane Oh, I started working on LaunchProjectileEvent, but I will need some time to do it properly (modded support mostly)

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/pull/1769

**Comment by ImMorpheus** [comment]
PR merged
