### ISSUE TITLE
Cancelling the DropItemEvent.Destruct event no longer preserves inventory items x2

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/Sponge#1398]
This is once again the case: https://github.com/SpongePowered/SpongeCommon/issues/654

Affected version:
```
    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-a15cc3e
    SpongeForge: 1.11.2-2315-6.1.0-BETA-2398
    Minecraft Forge: 13.20.0.2315
```

Also noticed this in Stable-5.

**Comment by DarkArc** [comment]
This looks like it may have been changed intentionally:
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/tracking/phase/entity/DeathPhase.java#L150-L167

Though that makes this logic effectively useless:
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinInventoryPlayer.java#L170-L187

**Comment by bloodmc** [comment]
This will NOT be changed in SpongeForge as it caused all sorts of issues with mods that use soulbound items such as Tinkers Construct. The event works exactly like Forge's PlayerDropsEvent 

https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/event/entity/player/PlayerDropsEvent.java#L34

"Canceling the event will prevent ALL drops from entering the world"

If you need to move items to the newly spawned player then you need to use the RespawnPlayerEvent.

https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/entity/living/humanoid/player/RespawnPlayerEvent.java

**Comment by ryantheleach** [comment]
So to elaborate,

1. "Canceling the event will prevent ALL drops from entering the world" and also does not place the items back on the (currently dead) player?

2. The dead players inventory will be cleared on respawn, except for items that are soulbound, if keep inventory is on.

3. to keep items on respawn, you can carry them from the dead player, to the new player?

**Comment by bloodmc** [comment]
1. It should keep the items on the dead player.
2. The dead player should still have the items on "corpse". If this is not happening then it is a bug that I have to fix as you should be able to copy/transfer items from the dead player to newly respawned player.
3. Yes

@DarkArc Please confirm if this is working as stated above. If not then I'll reopen ticket as it is a bug.

**Comment by DarkArc** [comment]
Yeah the inventory is copyable at the time of death. I already implemented a "workaround" solution before your reply. It uses my player state service. 

Implementation code here if someone comes across this issue looking for guidance:
https://github.com/Skelril/Skree/blob/master/src/main/java/com/skelril/skree/content/zone/ZoneInventoryProtector.java
https://github.com/Skelril/Skree/blob/master/src/main/java/com/skelril/skree/service/internal/playerstate/PlayerStateServiceImpl.java

Not terribly well documented, but hopefully helpful.

**Comment by ryantheleach** [comment]
Why does it store, then immediately release the inventory @DarkArc

**Comment by DarkArc** [comment]
@ryantheleach implementation detail. Release basically tells the service if the player logs out and back in, or respawns, it's free to restore the "general" inventory store. The thought being, if there is a minigame or something where they should have an isolated inventory, and their original inventory should not be restored on death, that is possible.

**Comment by ryantheleach** [comment]
@DarkArc Faith has found a solution that seems to work with tinkers construct, that allows us to copy on respawn by default.
