### ISSUE TITLE
UnloadChunkEvent is not fired when a world unloads

### ISSUE THREAD

**Issue by xcube16** [SpongePowered/Sponge#1399]
When a world unloads UnloadChunkEvent's are NOT fired for currently loaded chunks.

**I am currently running...**

- SpongeForge version: stable-6 3bb6c1b2ab4c98b00764cdaee219ed9fd6fed6b3
- SpongeVanilla version: untested
- Java version: 1.8.0
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, xcube, skyblockwars (xcore and skyblockwars are plugins I am developing)

**What is the expected result?**
UnloadChunkEvent should be fired for when ever a chunk unloads, including when the world unloads.
Note: I think UnloadChunkEvent is fired before the chunk saves, this should also happen before the chunk saves when the world is unloading.

**What is the current result?**
UnloadChunkEvent is fired for normal chunk unloads during the game, but not when the world unloads.
UnloadWorldEvent can be used as a work-a-round, keeping in mind that it is fired after the world is saved.

**Comment by ryantheleach** [comment]
Do you have a test plugin handy in order to demonstrate this issue? Not a requirement, but it saves dev time.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/c352510dff8293fa1b3cab730605baf302af0bfb
