### ISSUE TITLE
WorldUUID Changing on restart.

### ISSUE THREAD

**Issue by G1R-Productions** [SpongePowered/Sponge#1403]
- SpongeForge version:  spongeforge-1.11.2-2315-6.1.0-BETA-2395
- Operating System: Windows 10

**What is the expected result?**
World UUIDs should not change on server restart.
**What is the current result?**
The UUID for world is changing on restart:
Before Restart:
https://pastebin.com/e5TPWwqE
After Restart:
https://pastebin.com/3JaC8Qw0

The level_sponge.dat seems to think that the UUID is:
00000000-0000-0000-0000-000000000000
http://i.imgur.com/1OVEFFU.png

**Comment by codeHusky** [comment]
Oh wow, this has become an issue on SpongeForge as well now? odd.

**Comment by kashike** [comment]
#1181
https://github.com/SpongePowered/SpongeVanilla/issues/326

**Comment by ryantheleach** [comment]
Does anyone know if we have had any recent reports of this on 1.12? Some reproduction steps would be sweet.

**Comment by Zidane** [comment]
Closing as I've tested this to death months ago per codehusky's issue on SV and I cannot get this to reproduce. I've tried every way I can think of and told of and the UUID is and has always persisted fine and loaded fine. Find me a reproduction and make mew a new issue.
