### ISSUE TITLE
forums.spongepowered.org Poll Data Load Issue

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/Sponge#1405]
Hello, I conducted a poll [here](https://forums.spongepowered.org/t/quick-poll-server-with-mods-vs-server-without-mods/18663), and now I need to retrieve the name of users who voted to participate in the alpha testing of a plugin I've developed. When I tried to click on: "Show Results" > "↓ ", a infinite loading symbol keeps rolling and doesn't show me any results. Below are my specs. 

OS: Windows 10
Browsers: Google Chrome, Mozilla FireFox

**Comment by XakepSDK** [comment]
https://github.com/SpongePowered/SpongeHome

**Comment by stephan-gh** [comment]
Please report issues like these directly on the forums: https://forums.spongepowered.org/c/meta
`Show Results` works fine for me.

**Comment by XakepSDK** [comment]
1 may...
https://forums.spongepowered.org/t/polls-bug/18672
Not fixed.
