### ISSUE TITLE
Issue when using Nashorn API

### ISSUE THREAD

**Issue by HaedHutner** [SpongePowered/Sponge#1413]
There is an issue when trying to use the Nashorn API. When trying to access the classes of the API, a NoClassDefFoundError is thrown. I have done the following tests:

1. Trying to utilize classes from the API ( ScriptObjectMirror ):

https://pastebin.com/Ef1N67i6

2. Putting nashorn.jar into the mods folder so that Forge may load it. Also outputting the class loader for the class of the variable and the jdk.nashorn.scripting.api.ScriptObjectMirror. Then attempted to cast result3 to a ScriptObjectMirror with following results:

https://pastebin.com/dcuu5WfK

Here is the code contained with test.js:

https://pastebin.com/7xUbFHmQ

**I am currently running...**

- SpongeForge version: spongeforge-1.11.2-2282-7.0.0-BETA-2376
- Java version: JRE 1.8.0_101
- Operating System:

 - [x] Windows
- [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS

**Comment by HaedHutner** [comment]
> [DC] <N​e​u​m​i​m​T​o​> Fromage this is unrelated to your problems, but you should not initialize ScriptEngineManager with null argument. In this case nashorn will miss classloader context. And second point you might want to take look at NashornScriptEngineFactory (you will need nashorn.jar on your classpath) where you can initialize nashorn with jjs arguments, esp. "--optimistic-types=true" might be han 

Using a new instance of NashornScriptEngineFactory made everything work. Still had to have nashorn.jar in my mods folder, though.

```java
    @Listener
    public void onInit (GameStartingServerEvent event) {

        NashornScriptEngineFactory factory = new NashornScriptEngineFactory();
        ScriptEngine engine = factory.getScriptEngine();

        try {
            engine.eval(new FileReader("config/testplugin/test/test.js"));

            Invocable invocable = (Invocable) engine;

            System.out.println(NashornScriptEngine.NASHORN_GLOBAL);

            Object result3 = invocable.invokeFunction("func3");

            ScriptObjectMirror test = (ScriptObjectMirror) result3;
            test.forEach( (k,v) -> {
                System.out.println(k + " : " + v);
            });

        } catch (ScriptException | NoSuchMethodException | FileNotFoundException e) {
            e.printStackTrace();
        }
    }
```

**Comment by Zidane** [comment]
@Minecrell Status?

**Comment by stephan-gh** [comment]
@lucko Generally yes, good catch, but it still prevented interacting with Nashorn classes directly (although the question is if you should really do that...). Not sure why you deleted your comment, it was fine :P

**Comment by lucko** [comment]
I deleted my reply it because it looks like OP already tried it that. The first example given above was exactly what I was suggesting. (I didn't fully read the issue before replying 🙂)

As you said, it prevents interacting directly with Nashorn, which I assume is necessary.

Also, I'm not entirely sure if constructing with a null classloader will allow you to use Sponge/your own plugin's classes within the JS code. For me that's not an issue, as I only use Nashorn for evaluating simple expressions, but if you wanted to use Java objects etc within the JS code, I'm not sure if it would work.

**Comment by stephan-gh** [comment]
> Also, I'm not entirely sure if constructing with a null classloader will allow you to use Sponge/your own plugin's classes within the JS code.

That's exactly what I thought, but it worked fine with a null class loader when I tested it. It seems like the classloader that is given to the `ScriptEngineManager` is only used to locate the `ScriptEngine`, but not for the actual scripts.
