### ISSUE TITLE
Fence gates do not support Keys.DIRECTION

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#1414]
`supports()` returns false, and `offer()` has no effect.

**Comment by JBYoshi** [comment]
I'm not sure whether `Keys.DIRECTION` is the best option. When the gate is closed, `Keys.AXIS` would be more appropriate. However, when the gate is open, since it can open in either direction, `Keys.DIRECTION` would be more appropriate then.

**Comment by pie-flavor** [comment]
@JBYoshi Well, no, not at all. The gate block faces one of the four directions. Vanilla models render it symmetrically, but a resource pack doesn't have to. It's represented in the BlockState.

**Comment by JBYoshi** [comment]
I'll take this, then.
