### ISSUE TITLE
Not possible to cancell armor equipment via rightclicking

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Sponge#1417]
**I am currently running...**

- SpongeVanilla version:  1.12-7.0.0-BETA-289
- Java version: 8
- Operating System:

 - [x ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x ] Windows

When a player has no armor and rightlicks with an armor in the main hand the armor is then put into armor section of player's inventory. 

Depending on the  player actions ingame  before the item is moved from hotbar to armor inventory one of the following events is fired

- InteractEntityEvent.Secondary
- InteractBlockEvent.Secondary  - this one is surprisingly fired even if a player righclicks into the air.

I think it would be very helpful if cancelling such events would restrict players from equiping armor via rightclicks, however this is not the case right now. Even if the event is cancelled the amor still gets equiped.

**Comment by Faithcaio** [comment]
ChangeEntityEquipmentEvent is not fired yet.
see https://github.com/SpongePowered/SpongeCommon/issues/1402

**Comment by JBYoshi** [comment]
I'll look at this once https://github.com/SpongePowered/Mixin/issues/193 is fixed (which is currently preventing SpongeVanilla from running in my development environment).

**Comment by JBYoshi** [comment]
Try listening to `InteractItemEvent` instead. That should work.

**Comment by NeumimTo** [comment]
InteractItemEvent works
