### ISSUE TITLE
SaturationProperty does not match actual saturation replenished

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Sponge#1418]
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/data/property/store/item/SaturationPropertyStore.java

So the SaturationProperty is all about amount of saturation replenished, but Minecraft seems to use a different value internally when it registers the food items, then when it adds the stats to the player it uses this calculation:

```java
this.foodSaturationLevel = Math.min(this.foodSaturationLevel + (float)foodLevelIn * foodSaturationModifier * 2.0F, (float)this.foodLevel);
```

For what reason this internal value is used, I have no idea, but I feel it would be best to modify the SaturationPropertyStore to add this calculation within there to display what that actual amount of saturation gained will be instead of some internal number that is changed later anyway. These new numbers would then match the wiki values. 

Maybe I am missing a reason this internal number is used, so if so please point that out to me.

Once there's some agreement I can make this PR.

**Comment by Zidane** [comment]
I don't think there is a reason why the internal number is used. @gabizou thoughts?
