### ISSUE TITLE
Some optimisations

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1420]
Why we need this check?
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/biome/MixinBiome.java#L114
This method can't return null.
```
    public String getGeneratorOptions()
    {
        return this.generatorOptions == null ? "" : this.generatorOptions;
    }
```

**Comment by Zidane** [comment]
@Deamon5550 

Here you go.

**Comment by Deamon5550** [comment]
Yeah this changed back in 1.9, it used to return null.
