### ISSUE TITLE
MOB_SPELL particle wierdness

### ISSUE THREAD

**Issue by trentech** [SpongePowered/Sponge#1421]
So spawning MOB_SPELL Particle seems messed up. They just spawn colorless balls of plain white. adding a color value seems to change the direction they move. No errors are thrown. Example screenshots below.

http://imgur.com/a/h3R1C

Tested this on lastest SpongeForge and SpongeVanilla, both 6.x and 7.x builds, with same results.
This was tested in tests build of ProjectPortals so it could be a result of the method I'm spawning particles but I don't believe it is.

Java: 8 U131
OS: Windows 10

Let me know if more information is needed.

**Comment by JBYoshi** [comment]
I'm working on a fix right now. Just give me a few minutes and it should be up.

Let's just say it was a wacky bug.
