### ISSUE TITLE
Cannot set item in hand when spawning entity

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#1428]
See: https://forums.spongepowered.org/t/spawning-skeleton-with-item-in-hand/19794/4

It looks like unimeplemented yet.

spongevanilla-1.11.2-6.1.0-BETA-11
spongeforge 1.11.2-2315-6.1.0-BETA-2438

**Comment by ghost** [comment]
Please backport to 1.11.2 too - api 6.1.0. Thanks.

**Comment by JBYoshi** [comment]
@hunter688 Done.
