### ISSUE TITLE
Inventory#query(Object[]) returns an empty inventory every time

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#1431]
Code: 
```java
player.getInventory().query(ItemTypes.STICK, ItemStack.of(ItemTypes.BLAZE_ROD, 5))
```
Inventory contains a stick and a stack of five blaze rods.
The returned `Inventory` is empty.

SpongeVanilla 1.11.2-6.1.0-BETA-11

**Comment by JBYoshi** [comment]
A quick note: I decided to have the method ignore the stack size. Let me know if it should be changed.

**Comment by pie-flavor** [comment]
I think there should be two methods, one for each behavior, just like the current ItemStack query methods.

**Comment by JBYoshi** [comment]
@pie-flavor I have updated the behavior for API versions 6 and 7. I haven't changed API 5 because it uses a stack size of -1 to specify that the stack size should be ignored.

**Comment by Mumfrey** [comment]
No, `queryAny` is bad and I can't believe you added this without discussing it.

**Comment by Mumfrey** [comment]
I mean. This is where inconsistency starts, there are so many ways this could have been done nicely and adding an extra, totally redundant method is a bloody stupid way of going about it and makes the whole thing inconsistent.

`query` - queries the things
`queryAny` - queries *any of the things*?   ... waht?

This is half-baked, inconsistent, and needs to be removed ASAP. Fortunately, the half-bakedness continues to the implementation where you **didn't test your build before you pushed the code**, meaning it's broken.

You need to revert these changes.

**Comment by Mumfrey** [comment]
To be clear, the changes to the strategy are fine and I approve. But I'm absolutely bloody furious that you would change the `Inventory` interface in such a careless manner without so much as a discussion.

**Comment by JBYoshi** [comment]
@Mumfrey Reverted.

**Comment by Mumfrey** [comment]
Thankyou. I see that there's another `queryAny` which was added by @Faithcaio previously which I'm not desperately happy about either but it's been there too long to change. We should probably remove it in API 7.

Propose some better combinatorial approaches and we can discuss them.

**Comment by Faithcaio** [comment]
The queryAny I added was to query ItemStacks of **any** size as it was no longer possible to created -1 sized stacks.

**Comment by Faithcaio** [comment]
just leaving this here:
query(Predicate<ItemStack>...)

**Comment by pie-flavor** [comment]
@Mumfrey That was... an explosion, to say the least. How would _you_ recommend we go about adding support for both querying including stack size, and querying ignoring it?
