### ISSUE TITLE
Connected directions not supported/working on double chests

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Sponge#1436]
**I am currently running...**
- SpongeVanilla version: 1.12-7.0.0-BETA-300
- Java version: 8u131
- Operating System: Windows

- Plugins/Mods: 
Latch
IPLog

**What is the expected result?**
Chests should support connected direction data.

**What is the current result?**

They do not support connected directions.

This code:

```java
@Listener(order = Order.EARLY)
public void onInteraction(InteractBlockEvent event, @First Player player) {
    player.sendMessage(Text.of("Id: " + event.getTargetBlock().getState().getType().getId()));
    player.sendMessage(Text.of("Supports connected directions: " + event.getTargetBlock().supports(Keys.CONNECTED_DIRECTIONS)));
    player.sendMessage(Text.of("All connected directions: "));
    event.getTargetBlock().get(Keys.CONNECTED_DIRECTIONS).orElse(new HashSet<>()).forEach(m -> player.sendMessage(Text.of(m.toString())));
}
```

causes the following to be printed out when right clicking a chest or door(these are not supposed to support it):

![image](https://user-images.githubusercontent.com/18372958/28201778-29c538d6-6838-11e7-95ef-60dfc9adfb7a.png)
![image](https://user-images.githubusercontent.com/18372958/28201825-657b6918-6838-11e7-8799-49ac8993fe7f.png)

**Edit:** This is not expected to work on doors, but I cannot get it to work on chests from their block snapshot or tile entity.

**Comment by JBYoshi** [comment]
For chests, only the tile entities support `ConnectedDirectionData`. Doors use `PortionData` instead.

**Comment by parlough** [comment]
@JBYoshi For the chest though, its `BlockSnapshot` says here that it does not support connected directions nor does it have any connected directions and a block snapshot is supposed to contain "any extra data that may be associated with it, including {@link TileEntity} related data."

I haven't tested this in a while and I may have made some mistake but I don't think so. I'll test it again and also try getting its tile entity from its location and using that.

**Comment by parlough** [comment]
Yeah @JBYoshi as I expected(since the block snapshot would contain it too), the tile entity grabbed from the location still says it does not support `Keys.CONNECTED_DIRECTIONS`.

**Comment by parlough** [comment]
I use this in Latch to automatically lock the second part of a chest, and it used to work but it no longer does. 

I have tried to find the issue within Latch as well as Sponge itself but the dataprocessor seems right. I must be missing something.

**Comment by JBYoshi** [comment]
Apparently someone forgot to register the tile entity data processor.

**Comment by JBYoshi** [comment]
Wait a minute... It is in the list to register... just not being tied with the other processor.

**Comment by JBYoshi** [comment]
Never mind. I was looking at the data processor, not the value processor. The value processor doesn't have any code for tile entities. Looking into it now.

**Comment by parlough** [comment]
@JBYoshi Thanks for taking a look, I couldn't find the issue.
