### ISSUE TITLE
ChangeBlockEvent.Break cancelled Enderman duplicate block

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/Sponge#1443]
- SpongeVanilla version: SpongeVanilla version: 1.12-7.0.0-BETA-300
- Java version: 8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

When I cancelled the event "ChangeBlockEvent.Break", Enderman get a block in the enderman's hand.

**Comment by ryantheleach** [comment]
Assuming a minor language issue.
"Enderman get block in your hand." \> An enderman gets a block in the enderman's hand?

Sounds like entities states arn't being captured before block breaks.

**Comment by lesbleu** [comment]
I fixed this language issue. Sorry for my bad English.

**Comment by bloodmc** [comment]
@lesbleu Does the same result occur on 1.10.2 as well?

**Comment by lesbleu** [comment]
This bug is also present in spongevanilla-1.10.2-6.0.0-BETA-161

**Comment by bloodmc** [comment]
@lesbleu That is an ancient build. Test on the latest here

https://www.spongepowered.org/downloads/spongevanilla/stable/1.10.2

https://repo.spongepowered.org/maven/org/spongepowered/spongevanilla/1.10.2-5.2.0-BETA-391/spongevanilla-1.10.2-5.2.0-BETA-391.jar

**Comment by lesbleu** [comment]
I can't start this version [Error](https://pastebin.com/LT6j5176).

**Comment by bloodmc** [comment]
Try latest SpongeForge for now

https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.10.2-2281-5.2.0-BETA-2464/spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar

You will need to install Forge on your server in order to run this. Grab latest forge installer here

https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html

**Comment by lesbleu** [comment]
I have tested in spongeforge-1.10.2-2281-5.2.0-BETA-2464 and the bug is present.

**Comment by napentathol** [comment]
I am also experiencing this issue: https://forums.spongepowered.org/t/how-to-disable-endermen-from-picking-up-blocks/20232/2

I am using:
Sponge: 1.12-7.0.0-BETA-303
Java: 1.8.0_131
OS: Ubuntu-flavor linux

**Comment by Zidane** [comment]
@phit 

Can you verify against latest 1.12 on this?

**Comment by ImMorpheus** [comment]
I'm able to reproduce this on bleeding (https://github.com/SpongePowered/SpongeCommon/commit/a0675944bd8e75cf59e48e87a42380a0d07507d5).
```
@Listener
public void onBlockBreak(ChangeBlockEvent event, @Root Enderman enderman) {
    System.out.println("Stopping enderman at " + enderman.getLocation().getPosition());
    event.setCancelled(true);
}
```

**Comment by gabizou** [comment]
@ImMorpheus Ignore bleeding... We're focusing on stable-7.
