### ISSUE TITLE
No event launched when lava spread fire

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/Sponge#1446]
- SpongeVanilla version: SpongeVanilla version: 1.12-7.0.0-BETA-300
- Java version: 8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

A player places lava around flammable blocks. When fire is spreading by lava, no event is launched.

**Comment by lesbleu** [comment]
At [MixinBlock](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/block/MixinBlock.java#L155), Event is not launched with there conditions. It's normal ? If yes, why ?

**Comment by ImMorpheus** [comment]
PR merged. This can be closed.
