### ISSUE TITLE
Excessive Amount Of Java Errors On Startup

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/Sponge#1456]
As the title suggests, I'm having an excessive amount of Java errors appear on my console on startup, preventing several of my server's plugins from functioning. This only happens with server hosts (MCProhosting and BeastNode as least), perhaps because they're using linux? I tried running my server on both hosts and got similar, if not the same, errors. On my PC, the server runs smooth and perfectly fine.

**My PC's Specs**

**SpongeForge:** spongeforge-1.10.2-2281-5.2.0-BETA-2464
**Java:** 1.8.0_131
**OS:** Windows 10

Server log files can be found [here](https://drive.google.com/drive/folders/0B2FEPcC_CJ4GQUZDSjJXaHJVbVU?usp=sharing).

**Comment by kashike** [comment]
This is an issue with the `dreadzone` plugin. Please contact the author of that plugin for help.
