### ISSUE TITLE
[1.12 SV] Using SmeltingRecipe, system ignores my isValid() checks; false sometimes means true..

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1457]
Refer to thread on forum: https://forums.spongepowered.org/t/recipe-based-question/20016/20

Goal:  A test to register a custom smelting recipe that uses more restrictive info about the ingredient to produce the item result.  Creating a stack with display name/lore data on a granite item and registering it via the SmeltingRecipeBuilder failed to restrict the ingredient to a true match (for display name and lore parts) and gives the result for both modified and unmodified granite block items.

Implimenting the SmeltingRecipe directly instead has the same result, and debugging shows that the isValid() method is returning false when expected but still the recipe is being smelted.

If there is a fault in the base SmeltingRecipe, the builder based on that would be impacted by the same thing I guess: SHOULD in theory, displayname/lore be able to be specified on an ingredient and result in a specificity for this, or should lore/displayname be discarded by the builder approach, and require this custom implimentation of SmeltingRecipe as per the thread?

**I am currently running...**

- SpongeForge version: 
- SpongeVanilla version: spongevanilla-1.12-7.0.0-BETA-300
- Java version: 8_111
- Operating System: 

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
Just the testing plugin for this
**What is the expected result?**
A granite block named "Copper Ore" to produce cocoa-beans named "Copper nuggets" when smelted
An unnamed, normal granite block to produce nothing when smelted
An unnamed, andesite block to produce nothing when smelted

**What is the current result?**
A granite block named "Copper Ore" produces cocoa-beans named "Copper nuggets" when smelted
An unnamed, normal granite block produces cocoa-beans named "Copper nuggets" when smelted
An unnamed andesite block produces nothing when smelted.

My isValid() method generates true for copper-ore, false for granite only, and false for andesite, yet the recipe spits out the result for true=copper ore, and false=granite, and spits nothing out for false=andesite.

**Comment by Faithcaio** [comment]
please retest with latest

**Comment by theboomer** [comment]
NO CHANGE IN RESULTS AT ALL

`[13:32:53 INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.6.15 Source=file:/N:/000SpongeTestservers/1.12SV/spongevanilla-1.12-7.0.0-BETA-301.jar Env=UNKNOWN`

Tested with the custom implimentation first (with regular isValid tests lined up), and there is no change.  Raw Granite still converts to recipe.

Tested with builder approach on itemstacks, in case fix was limited to builder-based approach, but no difference there either.

Full plugin code: https://pastebin.com/bwz8U7TM

**Comment by Faithcaio** [comment]
but now!

**Comment by theboomer** [comment]
Yes, the custom implimentation method does work now in SV-beta-302 !!!

I also tried to set up a recipe with the recipe builder, but it had the same old behavior - raw granite also triggered the smelting. 

So the question now is, is the builder method supposed to have this  behavior, ignoring the name/lore data on the itemstack ingredient - or is there somewhere else that needs the same change made as you made here?

**Comment by Faithcaio** [comment]
Use the predicate ingredient method.
The ItemType/ItemStack/Snapshot one uses vanilla matching behaviour as noted in the javadocs. 
(which is ItemType + DamageValue)
