### ISSUE TITLE
[1.12SV] Crafting recipes (shaped, shapeless) do not work in SpongeVanilla

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1458]
Unable to get shaped/shapeless recipes registered /or/ working - they may be registering, just not working... dunno.
The following code is tacked to the end of the GamePostInitializeEvent event handler (where SmeltingRecipes are successfully registered and functional) as whimsical recipes for demonstration testing only:
````
        Sponge.getRegistry().getCraftingRecipeRegistry()
             .register(CraftingRecipe.shapelessBuilder().addIngredient(Ingredient.of(ItemTypes.BAKED_POTATO))
                        .result(ItemStack.of(ItemTypes.ANVIL, 1))
                        .build("anviltato", this));

        CraftingRecipe shaped = CraftingRecipe.shapedBuilder()
                .aisle("srs", "rsr", "srs")
                .where('s', Ingredient.of(ItemTypes.SAND))
                .where('r', Ingredient.of(ItemTypes.REDSTONE))
                .result(ItemStack.of(ItemTypes.RED_SANDSTONE, 5)).build("redsandtone", this);
        Sponge.getRegistry().getCraftingRecipeRegistry().register(shaped);
````

**I am currently running...**

- SpongeForge version: 
- SpongeVanilla version: 1.12 Beta 302
- Java version: 8.111
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: 
Just the testing plugin

**What is the expected result?**
A baked potato in crafting slots to result in an anvil
A checkerboard of sand and redstone to result in 5 redsandstone blocks
OR some errors during registration or while crafting the recipes
**What is the current result?**
A baked potato sits on crafting slots, nothing in result slot
The checkerboard of sand/redstone sits in crafting space, nothing in result slot
There are no errors thrown while registering recipes or when crafting the recipes in the console (there may be mixin noise for them in the log though):

https://pastebin.com/ecDXpbuu

**Comment by Faithcaio** [comment]
works fine in SF so something is broken with vanilla somehow

**Comment by Faithcaio** [comment]
Oh I see it.
You have to register recipes in PreInit.

@gabizou do we want to allow later registration in SV?

**Comment by theboomer** [comment]
Theoretically that might have been it, but is not, so something is broken in SV indeed.
I just moved that same code to the GamePreInitialization event, and the results are the same: nothing.

**Comment by Faithcaio** [comment]
Should work with latest now.

**Comment by theboomer** [comment]
Works!

Thank you very much for your repeated and rapid handling of these crafting based issues :)

FOR REFERENCE PURPOSES: Version 1.12-api 7-Beta-303 solves it

**Comment by theboomer** [comment]
While that works to actually make recipes register and work, it suffers the same limitation as posted in https://github.com/SpongePowered/SpongeCommon/issues/1455

It seems that data-manipulators are not applying (display names, stone type etc).  Test recipe is shapeless conversion of baked_potato to smoothgranite block with name, result is a nameless regular stone block.
