### ISSUE TITLE
Help system and command errors needs to be aware of subcommands

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/Sponge#1463]
Currently, the help system isn't aware of subcommands beyond "list all subcommands of main command separated by |". Help won't tell you about parameters of subcommands, or about subsubcommands.

For example, for this command tree: 
```
mycmd
 ├add
 ├change
 │ ├name
 │ └coords
 └remove
```
"/help mycmd change" should display grandchild commands "name" and "coords", and "/help mycmd change name" should display description and parameters of said subcommand.

Analogous for "Usage:" part of error messages:
For example, "/sponge config" displays this:
![img](http://orig06.deviantart.net/7808/f/2017/205/d/7/2017_07_25_15_40_42_by_vcsajen-dbhkzhs.png)
it would be more helpful if it displayed "/sponge config [-g] [-d dim] [-w world] key value" instead.

P.S. I'm sorry if it's duplicate, or invalid issue. Feel free to remove if that's the case.

**Comment by ryantheleach** [comment]
This will have to wait for the command refactor, but it's something I've been looking forward to / wanting for a long time.

**Comment by Zidane** [comment]
Closing as its already panned for fixing in the Commands PR.
