### ISSUE TITLE
"An essential class was loaded before Sponge could patch it"

### ISSUE THREAD

**Issue by EmanYm** [SpongePowered/Sponge#1466]
I'm not sure which Sponge github to put this on...
Everything relivant is on [this hastebin](https://hastebin.com/ifaweqitum.md).

The console log and the fml-latest have different time stamps because they are from different attempts to run the server.

**Comment by kashike** [comment]
This is an issue with the BaseMetals mod: https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues/159.

**Comment by EmanYm** [comment]
Thank you for the swift response.

**Comment by ryantheleach** [comment]
@EmanYm You may find luck using SpongeBootstrap.

**Comment by EmanYm** [comment]
It didn't fix the issue I'm having.  It does disclaim that it's not a guaranteed fix.  *shrug*  I have another course I can take.  Thank you for the help, Ryan

**Comment by ryantheleach** [comment]
@kashike How did you determine out of all the mods that it was with BaseMetals?

**Comment by kashike** [comment]
By reading the log?
