### ISSUE TITLE
Unexpected World Change

### ISSUE THREAD

**Issue by caunt** [SpongePowered/Sponge#1468]
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2464
- Java version: 1.8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, Not Enough Items, SpongeAPI, SpongeForge, ccl-entityhook, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Applied Energistics 2, AutoBroadcaster, CodeChicken Lib, Brandon's Core, CatClearLag, CodeChicken Core, CraftTweaker JEI Support, Just Enough Items, MineTweaker 3, Draconic Evolution, Extra Utilities 2, FlatBedrock Xplosion's Edition, Forestry, FTBLib, FTBUtilities, Gravitation Suite, Holograms, HuskyUI, HuskyCrates, Iron Chest, JourneyMap, Kaboom 2.1 Donation, KaboomRestrict, Mantle, MMCReboot, MTLib, Mod Tweaker, Nucleus, PermissionsEx, Tinkers' Construct, TickProfiler, TickThreading, WorldEdit

Problem in Applied Energistics 2 

https://gist.github.com/caunt/8820f53ea533836d8fe11463e34f0747

**Comment by runescapejon** [comment]
hey i had ready report this on SpongeForge Github https://github.com/SpongePowered/SpongeForge/issues/1690
there in case one of the dev want to know more information

**Comment by bloodmc** [comment]
dupe SpongePowered/SpongeForge#1690
