### ISSUE TITLE
Canceled ClickInventoryEvent causes dupe with InventoryTweaks

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/Sponge#1470]
Hey,
if I cancel the `ClickInventoryEvent` event and then have InventoryTweaks installed on the client (it's not on the server) I can dupe items by ctrl + left clicking any item in a container (inventory, chest..).
The item stays at the position but gets also moved to the slot where it would go without the canceled event.

I did relog to make sure it's no ghost item.

The code I used for testing:
```java
	@Listener
	public void testEvent(ClickInventoryEvent event) {
		event.setCancelled(true);
	}
```
spongeforge-1.10.2-2281-5.2.0-BETA-2464

**Comment by runescapejon** [comment]
you don't put inventorytweaks in your server it cause's inventory GUI issue's because inventorytweaks bypass all event's 
it works on clientside you don't need it in serverside

**Comment by Sir-Will** [comment]
@runescapejon it's NOT on the server. I mentioned this explicitly above.

**Comment by dualspiral** [comment]
I imagine it's the same as https://github.com/SpongePowered/SpongeForge/issues/1546 - I forgot to check whether https://github.com/SpongePowered/SpongeCommon/commit/1a5ab72d29cf2c397043bb8178a964fbfb004046 needed backporting to stable-5, I expect that it does.

If I feel better later tonight, I'll test this and backport it, unless someone gets there first.

**Comment by dualspiral** [comment]
Hold on, I misread the issue this morning - I didn't properly read the bit about containers. Still, made me check to see whether I needed to backport my fix, I don't.

I tried to reproduce this using InvTweaks, but I couldn't reproduce this. I did the following:

* Put a double chest down on a clean server (running Nucleus + Mixins, LuckPerms, Total Economy, SF and Forge as above)
* Added some diamonds to it
* Stopped the server, [added a test plugin](https://gist.github.com/dualspiral/96fd19df68194fa1f62d6237e37d051c)
* Started the server, logged on
* Opened the chest
* Ctrl+left clicked the diamonds

Note: this was all done in survival mode

They disappeared from my screen (which would be incorrect), but then reopened the chest and they were in their original position - no dupe seemed to have occurred. I checked events were firing, see the plugin gist for the log. I also tried going the other way, local inventory to chest, same thing happened. Shift click didn't make the item "disappear" - everything cancelled fine.

So, I'm sorry to say I can't reproduce this...

**Comment by Sir-Will** [comment]
Just tested it again and found out that it only happens with one item and not stacked items. 
@dualspiral did you test it with a stack or one single item?

How I reproduced it:
- Placed a chest
- Put one diamond into it
- Restarted the server with the test plugin enabled
- Opened the chest and ctrl + left clicked the diamond
- Closed the chest and opened my inventory (If I would open the chest instead of my inventory it will remove the item)

My inventory does now contain one diamond while the chest does it have too.

![](http://i.imgur.com/ancHRTs.gif)

**Comment by runescapejon** [comment]
@Sir-Will  can you try this in survival mode ? because creative mode cancel event sucks

**Comment by Sir-Will** [comment]
Yea, just realized it. Testing it again.

**Comment by Sir-Will** [comment]
Ok, can't reproduce it in survival. 
I wasn't aware that this makes a huge difference and didn't thing about switching to survival, next time I will know better. Sorry about that.
