### ISSUE TITLE
SpongeAvoidEntityAIBuilder should use Entity as classToAvoid

### ISSUE THREAD

**Issue by marysaka** [SpongePowered/Sponge#1472]
SpongeAvoidEntityAIBuilder [actually use EntityCreature as second argument](https://github.com/SpongePowered/SpongeCommon/blob/74080b0c75e59075f164f5151b08be395e2d17fc/src/main/java/org/spongepowered/common/entity/ai/SpongeAvoidEntityAIBuilder.java#L92).

Because of that you cannot actually avoid no-creature based entity like the player.

Version: SpongeVanilla 1.12-7.0.0-BETA-306

**Comment by JBYoshi** [comment]
Then it should be `EntityLivingBase`. The player isn't an `EntityLiving`.

**Comment by ryantheleach** [comment]
Is it able to avoid non-living entities as well?

**Comment by marysaka** [comment]
@ryantheleach After a quick look, ```EntityAIAvoidEntity``` seems to accept ```Entity``` so yeah in theory, we can use it to be able to avoid non-living entities.

**Comment by Zidane** [comment]
I'll be dammed.

Looks like when I originally wrote this AI interface, I brought in the filter (which is fine) but completely forgot about the target class.

So really two things can be done here (give me some thoughts). One is a break, one isn't:

* (non-break) Change the second argument to Entity.class, filter out the ones you want with the predicate. Drawback is you better make sure that your predicate impl is FAST (as there could be many entities and its hot code)
* (break) Introduce the avoiding class and setting it in the interface. I could do this regardless but would keep it to bleeding API.

Thoughts?

**Comment by ryantheleach** [comment]
I don't understand the second option.

**Comment by JBYoshi** [comment]
The second option wouldn't have to be a break. It could just default to `Entity.class` if left unspecified.

**Comment by Zidane** [comment]
I've elected to just allow all entities to be passed to the selector due to the generics usage, changing the target class after the task has been built gets ugly fast and allowing the target class in the builder still means the predicate in the task would be just an Entity predicate (which means you would still need to cast).
