### ISSUE TITLE
Chunk.setBlockState() doesn't fire ChangeBlockEvent

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Sponge#1473]
When I call `World.setBlockState()`, it fires several `ChangeBlockEvent`s (the actual types vary based on the original and resulting block). However, I noticed that calling `Chunk.setBlockState()` doesn't fire any events. Is this intended?

**Comment by Zidane** [comment]
@bloodmc 

Thoughts?

**Comment by bloodmc** [comment]
@JBYoshi @Zidane Intended for mods such as WorldEdit to not bring the server to its knees. Those that bypass world usually do so for a reason.

**Comment by ryantheleach** [comment]
That's super surprising. 

Is there not something that can be done to change the signature, or at least document this behavior if we are going to let an escape hatch exist?
