### ISSUE TITLE
ExplosionEvent.Detonate is called twice

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/Sponge#1478]
```java
@Plugin(id = "test")
public final class Main {

    @Listener
    public void onInteract( InteractBlockEvent event ) {
        World w = event.getTargetBlock().getLocation().get().getExtent();
        Cause pluginCause = Cause.source( Sponge.getPluginManager().fromInstance( this ).get() ).build();
        w.spawnEntity( w.createEntity( EntityTypes.PRIMED_TNT, event.getTargetBlock().getPosition() ), pluginCause );
    }

    @Listener
    public void onExplode( ExplosionEvent.Detonate event ) {
        new Throwable().printStackTrace();
    }

}
```

https://pastebin.com/ktAuY751

ExplosionEvent.Detonate is called twice (as you can see in the stacktrace). Can only reproduce this by creating a new tnt entity programmatically. Burning tnt like in Vanilla Minecraft doesn't work.

Verified with _spongevanilla-1.11.2-6.1.0-BETA-16_

**Comment by JBYoshi** [comment]
Found the issue - apparently the click packet is being sent twice, and Sponge isn't doing anything about it. That means two TNT entities are being spawned.

**Comment by JBYoshi** [comment]
I think I saw a fix related to this earlier. Does this still happen on the latest version?

**Comment by TheRaspPie** [comment]
This is no longer an issue.
