### ISSUE TITLE
How to implement horse inventory?

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Sponge#1480]
I was looking at implementing the horse inventories earlier. It seemed pretty easy, except for one thing: the size of a horse's inventory can change.

* Every horse has at least one slot: slot 0, for the saddle.
* Regular horses have a second slot (slot 1) that holds a piece of armor. Donkeys, mules, and llamas use it for a chest that toggles access to the rest of the inventory, although . Llamas hold a piece of carpet for decoration in this slot. Zombie and skeleton horses have it, but don't use it.
* Donkeys, mules, and llamas have a larger inventory available for freely storing items. However, this section may or may not exist, based on whether there is a chest in the chest slot. There's an additional problem here in that the inventory object is replaced whenever the chest status changes.

**Comment by Faithcaio** [comment]
Pretty sure the inventory does not change its size. Instead when a Chest is added the inventory is recreated.

**Comment by JBYoshi** [comment]
Yeah, that's what I meant.

**Comment by Zidane** [comment]
Closing as this is in Faith's branch.
