### ISSUE TITLE
Querying for OrderedInventory throwing ClassCastException

### ISSUE THREAD

**Issue by DawnTheFawn1** [SpongePowered/Sponge#1482]
**I am currently running...**

- SpongeForge version: 
- SpongeVanilla version: 1.12.1-7.0.0-BETA-311
- Java version: 1.8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Minecraft, SpongeVanilla, Crates, SpongeAPI, ViaVersion, Cosmetics, Mod Coder Pack, Eleria Core, Spart

Most of the plugins are private for a new server in the works
**What is the expected result?**
When I run the code ```OrderedInventory orderedInventory = inventory.query(OrderedInventory.class);``` for it to give me an OrderedInventory to work with.
**What is the current result?**
I get a ClassCastException detailed here https://gist.github.com/RysingDragon/bd8c1fe03a234bb5edf5fceaa6f5f16d

I also tried testing it with a Player's inventory to make sure it just wasn't something with custom inventories, same result. Here's the code from the test:
```java
Player player = ...
OrderedInventory inventory = player.getInventory().query(OrderedInventory.class);
inventory.getSlot(SlotIndex.of(1)).get().set(ItemStack.of(ItemTypes.APPLE, 1));
player.openInventory(inventory,
                Cause.of(NamedCause.of("Plugin", Sponge.getPluginManager().fromInstance(Plugin.getInstance()))));
```
It fails right at querying for the OrderedInventory.
@Faithcaio

**Comment by Faithcaio** [comment]
A Player Inventory contains multiple smaller OrderedInventories so your query returns an adapter wrapping those. 
`query` does NOT always return the type you give it.
If the queryresult is not an empty inventory you can iterate through it to get all the OrderedInventories contained in the result.

**Comment by DawnTheFawn1** [comment]
Ok I understand that for the Player Inventories, but what about for custom inventories which is what I originally found the issue on? The code in the gist hasn't changed and it worked fine in 1.11.2 but now gives that error since updating to 1.12.1

**Comment by Cybermaxke** [comment]
`Inventory inventory = player.getInventory().query(OrderedInventory.class)` gives a inventory that may contain multiple `OrderedInventory`s. (can also return EmptyInventory, in case no `OrderedInventory` is found)
To get the first one, just call `OrderedInventory orderedInventory = inventory.first()`.
So you end up with: `OrderedInventory inventory = player.getInventory().query(OrderedInventory.class).first()`
To target all of them, you will have to use the query `Inventory`.
That's how I thought that it worked and implemented it like that in Lantern, reading the original inventory PR.

**Comment by DawnTheFawn1** [comment]
Yea and like I said in my previous comment, I understand that's not how you use it for player inventories. Though one thing you said intrigued me. It appears that with my custom inventory system, calling inventory.query(OrderedInventory.class).first() opposed to just directly using query works fine, I'll do a bit more testing to be sure but so far that seems to have resolved the issue. I'm still curious, what changed between sponge 6.x and 7.x that makes it behave in this different manner?

**Comment by DawnTheFawn1** [comment]
Nope that doesn't actually solve it, it just ended up giving me the first InventoryRow, which makes sense when I think about it. I've changed to just using GridInventory and it appears to actually be working this time, probably should have used that from the beginning. I'll be testing more to make absolute sure, and if all's good I'll close the issue.

**Comment by DawnTheFawn1** [comment]
Issue resolved, sorry about this. My understanding of the inventory api isn't so great at times.

**Comment by Faithcaio** [comment]
>  it just ended up giving me the first InventoryRow

cause rows are ordered
