### ISSUE TITLE
Starting a 1.12.1 server with 1.10.2 worlds

### ISSUE THREAD

**Issue by EmanYm** [SpongePowered/Sponge#1487]
**I am currently running...**
- SpongeVanilla version:
    - 1.12.1-7.0.0-Beta 315
- Java version:
    - 8
- Operating System:
    - - [x] Linux (Ubuntu, Debian, Fedora, etc)

- Plugins/Mods: 
    - [Here is a screen capture](https://i.gyazo.com/86e406114bc9625fb07b8fefcdd735d1.png) of everything in my server's mods folder

**What is the current result?**
>[1:44 PM] Breantique: I'm getting a runtime exception each time the server starts "preparing start region"
[https://pastebin.com/87LRbU3p](https://pastebin.com/87LRbU3p)
It's very likely because they are 1.10.2 generated worlds and I updated to SpongeVanilla 1.12.1.  It might fix itself after a player joins and the worlds are re-saved
[1:46 PM] BOTSpongie: <Zidane> @Breantique Open an issue on SpongeCommon for that and tag gabizou. Upload your map as well please.
[1:47 PM] Breantique: Alright Zidane.
[1:47 PM] BOTSpongie: <Zidane> Thanks

**Comment by EmanYm** [comment]
I forgot to tag @gabizou in the opening post...

**Comment by gabizou** [comment]
Looks like SignPortalData is not being registered. Whether the plugin is missing, or whether the "old alias" is not being registered for upgradability is unknown at this moment, but the data will still remain until it is either forcefully removed, or until the plugin upgrades the data successfully. Good thing to note though is that for some reason, I didn't get this in a pretty printer so it can be properly formatted.

Otherwise, nothing is really wrong in sponge it seems.

**Comment by gabizou** [comment]
Verified [ProjectPortals does not register a legacy id for the legacy data](https://github.com/trentech/ProjectPortals/blob/b6cb1dc8a16a25833db8259f701b4eaae039fba0/src/main/java/com/gmail/trentech/pjp/Main.java#L119). Tagging @trentech.

To resolve the issue: Using [`registerLegacyManipulatorIds`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/DataManager.java#L140), you can automatically register for legacy data from older worlds to be upgraded to the new registration. Of course, this is only after you have registered your data in the first place. Looking at the log, the legacy id appears to be: `com.gmail.trentech.pjp.data.mutable.SignPortalData`

Closing this issue as it is not a Sponge issue but a safeguard ;)
