### ISSUE TITLE
ClickInventoryEvent returns instance of the container when clicking a slot in the player inventory while a container is open.

### ISSUE THREAD

**Issue by PurpleIsEverything** [SpongePowered/Sponge#1489]
**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2569
- Java version: Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_131
- Operating System: Centos 7 - Docker Alpine
- Plugins: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, LuckPerms, Nucleus, Prism

**What is the expected result?**

ClickInventoryEvent should return the PlayerInventory instead of the Container with slot.parent() or event.getTargetInventory when clicking on a slot in the players inventory when a container such as a chest is open.

**What is the current result?**

Currently it returns the instance of the container in my case a chest instead of the player inventory. So you are unable to figure out what inventory the slot is from.

I've provided some test code to replicate this issue:
https://gist.github.com/ShadowKitten/5e861ea8b9620bb1a610b2ff6dca7305

**Comment by Faithcaio** [comment]
Since API 7 you can `slot.transform()` to convert the slot in the container to the slot in the inventory. 
`slot.transform().parent()` is then the viewed inventory.

I'd say it is correct that the events `slot.parent()` returns the container. 
Slots are childs in the container. The viewed inventory is only referenced in slots.

**Comment by ImMorpheus** [comment]
Status ? Is this a wontfix ?

**Comment by Faithcaio** [comment]
yeah. use `slot.transform().parent()` to get the "real" inventory
