### ISSUE TITLE
Exception during phase body

### ISSUE THREAD

**Issue by EmanYm** [SpongePowered/Sponge#1493]
I get [this](https://hastebin.com/yozevaxita.md) after using `/kill breantique`

**I am currently running...**
- SpongeVanilla version:
    - 1.12.1-7.0.0-beta 315
- Java version:
    - 8
- Operating System:
    - [x] Linux (Ubuntu, Debian, Fedora, etc)

**Comment by gabizou** [comment]
@Faithcaio looks like some inventory parents are null for some reason or another.

**Comment by phit** [comment]
Closing this as it appears to be a SpongeVanilla issue and the log is down, reopen this on SpongeVanilla if its still an issue.
