### ISSUE TITLE
Crash On Login

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/Sponge#1499]
As the title suggests, the server crashes on client log in.

**SpongeForge:** spongeforge-1.10.2-2281-5.2.0-BETA-2546.jar (This also happens with the latest build, spongeforge-1.10.2-2281-5.2.0-BETA-2571)
**Java Version:** 1.8.0_141
**OS:** Linux

Console Log: [rawlog.txt](https://github.com/SpongePowered/SpongeCommon/files/1235233/rawlog.txt)
Crash Report: [crash-2017-08-18_13.52.34-server.txt](https://github.com/SpongePowered/SpongeCommon/files/1235249/crash-2017-08-18_13.52.34-server.txt)

**Comment by Aaron1011** [comment]
@SjsolisZXA: Are you able to reproduce this consistently with a fresh world?

**Comment by SjsolisZXA** [comment]
No, it seems like it's a problem with the world I had on my server, my apologies. Do you have any idea what the log is saying about the world?

Update: It was a level.dat issue.
