### ISSUE TITLE
Inventory Root and getting "real" Slot

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/Sponge#1503]
More stuff for the Inventory API + Impl:

add a Inventory#root which recursivly gets .parent() until reaching the root inventory.
(This is usually the actual IInventory or Container)

Add a way to query for the "real" Slot. (slot.query(???).root()) is then usually the real IInventory holding the slot.

@Mumfrey

**Comment by Cybermaxke** [comment]
This got covered in https://github.com/SpongePowered/SpongeAPI/pull/1642

@Faithcaio Would it also be possible to add a `transform` method in the `Container`? That makes it possible to get the inventory structure from the container. For the example from a chest container you would get a (query?) inventory:
```
[
  "chest-inventory": [
    ...slots...
  ],
  "player-bottom-inventory": {
    "main-grid": [ ... ],
    "hotbar": [ ... ],
  }
]
```

**Comment by Faithcaio** [comment]
Is not not already like that?
Just iterate through the inventory. 
Hotbar might be a separate 3rd inventory currently.

**Comment by Cybermaxke** [comment]
Oh I thought it were just the container slots inside a container and not any inventory structure. I guess I will have to rewrite some things in lantern...

**Comment by Faithcaio** [comment]
It is both.
There is a difference between
`inventory.slots().iterator()` and `inventory.iterator()`

**Comment by Cybermaxke** [comment]
Ah ok, the inventories inside the container will also have the container as parent? Inventories are in lantern pre-constructed and not for every container, so I can't change the parent without wrapping around it.

**Comment by Faithcaio** [comment]
Direct Sub-Inventories in the container are all wrappers.
Thats why I added Slot#transform to convert the Slot in the container to a Slot in the actual Inventory (Chest or Player)
Also Slots in Containers are the real ones from vanilla.
Slots in Inventories do not exist so we have a wrapper for them.

Confusion!
