### ISSUE TITLE
Phase incompatibility detected error but code runs correctly

### ISSUE THREAD

**Issue by Evolht** [SpongePowered/Sponge#1507]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2597
- Java version: 1.8
- Operating System: windows 10

 - [x] Windows

Plugins/Mods: 

- Pixelmon Dark 1.7
- EconomyLite-6.0.0-2.12-23
- Nucleus-1.1.0-S7.0-MC1.12.1-plugin
- PixelmonEconomyBridge-1.10.2-1.3.0
- spongeforge-1.10.2-2281-5.2.0-BETA-2597

I also use a separate mod called NBTHandler, which I've compiled, and **is being used to provide access NBTTag/NMS methods**. I run the server outside of a dev environment as an attempt to a 'live' environment before pushing the plugin to the real server.

**What is the expected result?**
**What is the current result?**
The expected result and the current result are the same. The methods seem to run correctly, the code doesn't break and everything works as expected.

The only issue is that the game server/client seems to freeze while it's printing this huge error to the console/log file.

https://gist.github.com/SparkVGX/60769cb395dd06829871b8fd19c5931b

**Comment by phit** [comment]
log is gone and 1.10 with no reproduction
