### ISSUE TITLE
Cancelling ChangeInventoryEvent.Held not working

### ISSUE THREAD

**Issue by DawnTheFawn1** [SpongePowered/Sponge#1508]
**I am currently running...**

- SpongeForge version: 
- SpongeVanilla version: Spongevanilla-1.12.1-7.0.0-BETA-314
- Java version: 1.8.0_44
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: Minecraft, Mod Coder Pack, SpongeAPI, SpongeVanilla, AnotherRPGPlugin, Eleria Core (last 2 are private for a server I'm working on, let me know if there's any code snips I need to provide)

**What is the expected result?**
When I cancel ChangeInventoryEvent.Held, for the held item to revert to the original Slot.
**What is the current result?**
https://i.gyazo.com/7efa8cef57fbf6b15d3d4779953043b2.mp4

log: https://gist.github.com/RysingDragon/deda0aa099788cb2a47cb48c08616ac5

**Comment by ryantheleach** [comment]
The log states this was from : spongevanilla-1.12.1-7.0.0-BETA-314

@Faithcaio It's my assumption that this is buggy behavior, and that we don't expect the event to be thrown when setting it back to the original slot?

@RysingDragon A test plugin would save the devs a little time.

**Comment by DawnTheFawn1** [comment]
@ryantheleach Ah my bad, somehow I missed filling out that field creating the issue. I also just tested it again on the latest spongevanilla (spongevanilla-1.12.2-7.0.0-BETA-356) and it's still a problem. Here's a gist with test plugin code as requested. https://gist.github.com/RysingDragon/2262edb459ee7ba808b089b8c981e2bd
Using either of the two lines of the event ends in the same result as shown above.
