### ISSUE TITLE
Issue with chunks unloading after players logout or leaves the region 

### ISSUE THREAD

**Issue by Sharkske** [SpongePowered/Sponge#1512]
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-259 
- Java version: Java 8
- Operating System: Ubuntu
- Plugins/Mods: Skyfactory 3 ftb modpack

Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Not Enough Items, OpenComputers (Core), SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, Fence Overhaul, AdminShop, Block Restrictor, CatClearLag, DisableSkeletonHorse, NuVotifier, Enjin Minecraft Plugin, FoxCore, FoxGuard, GriefPrevention, LuckPerms, LuckRankup, MMCReboot, MultiChat - Sponge Bridge, Nucleus, Nucleus API, Project Core, SeriousVote, Stack Ban, TickProfiler, Total Economy, WorldEdit, Actually Additions, CodeChicken Lib, CodeChicken Core, EnderStorage, Just Enough Items, OpenComputers, ActuallyComputers, Baubles, Extra Utilities 2, AngelRing 2 Bauble, AppleCore, apple_shields, AppleSkin, AutoPackager, Psi, AutoRegLib, Baconators, CraftTweaker JEI Support, MineTweaker 3, B.A.S.E, BD Lib, Bed Bugs, Better Builder's Wands, BiomeTweaker, BlockDispenser, Guide-API, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Mantle, Tinkers' Construct, Ceramics, Chameleon, Chance Cubes, MCMultiPart, ‽, |, /, Chest Transporter, ChickenChunks, Chickens, Chisel, Chisels & Bits, ShadowMC, Clipboard, Clumps, Cyclops Core, Colossal Chests, CommonCapabilities, Cooking for Blockheads, Waila, Dark Utilities, PTRModelLib, Decocraft, Dimensional Cake, Draconic Evolution, Dragon Mounts, Storage Drawers, Drawers & Bits, Elevator Mod, EnderCore, Ender IO, Engineers Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Ex Nihilo Adscensio, Ex Compressum, Extra Bit Manipulation, Zero CORE, Extreme Reactors, Fairy Lights, Farming for Blockheads, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Shadowfacts' Forgelin, FTBLib, FTBUtilities, Funnels, Garden of Glass, Advanced Generators, Gravestone, Grue, Get Ya' Tanks Here, Hammer Core, Hatchery, Headcrumbs, Hopper Ducts, HydroGel, Immersive Engineering, LunatriusCore, InGame Info XML, MTLib, InitialInventory, Integrated Dynamics, Integrated Tunnels, Simple Inventory sorting, Iron Backpacks, Iron Chest, YUNoMakeGoodMap, ItsBecauseUHasNoGoodSpawn, It's Raining Food, JourneyMap, KleeSlabs, LLibrary, Literal Ascension, Long Fall Boots, Loot Bags, Mercurius, MineMenu, MiniCoal, Natura, Missing Pieces, Random Things, Roots, MoarSigns, mob_grinding_utils, Mod Tweaker, More Chickens, More Shearables, More Shears, Morpheus, ModPack Utilities, ModPack Basic Tools, Mystical Agriculture, Nice, Not Enough Wands, OreExcavation, Packing Tape, Pam's HarvestCraft, ShetiPhian-Core, Platforms, RebornCore, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, Refined Storage, RebornStorage, Redstone Paste, Reliquia, RFTools, RFTools Control, RFTools Dimensions, Wooden Shears, Scanner, Shear Madness, Simple Achievements, Simple Barrels, Simple Corn, Simple Generators, SimpleLabels, Simply Jetpacks 2, Snad, Solar Flux Reborn, Steve's Carts 2, Super Circuit Maker, The Beneath, Tinkers Tool Leveling, Tiny Progressions, TorchMaster, Translocator, Twerk-Sim 2K16, Twitchcrumbs, voidcup, Waddles, WanionLib, I Can See Everything, What Are We Looking At, Wither Crumbs, Experience Rings, UniDict

The Issue im having is when a player comes on to our server and plays and loads there base at that time everything is fine but the problem is when they leave, so far from what i gathered by using the tools i have at hand is that chunks with machines in them fail to unload "some of them" as with chunks with nothing in them always unload without a problem.

Now this could be a issue with a mod, or even a error in my sponge config file here = https://pastebin.com/et5CKP1F 

I tracked this down by using a mod called ChickenChunks and the /chunkloaders command when im in the area this is what is shows 

http://i.imgur.com/njfRMl2.png

now when i leave the area it shows the main chunks with all the players machines within them still loaded

http://i.imgur.com/83YUr9A.png

this happens with every players that comes and goes so after a hour or 2 of up time the lag get out of control and TE get to super high nums as u can see here http://i.imgur.com/hyWNDZe.jpg

any Idea what i can do or how i can go about dealing with this issue it also happens on our beyond and dw20 servers both use the same spongeforge

**Comment by bloodmc** [comment]
You are setting very bad chunk settings in your config. Reset your sponge global config and test again with DEFAULTS.

**Comment by Sharkske** [comment]
i know they are, its not for normal use i just set some of the settings low to speed up things to be able to gather the info i need to post here, the setting i normally use are default just maybe some changes with mob spawn rates. The point im trying to show u is chunks arent being marked as inactive for unload, it may not be the fault of sponge it could even be the fault of a mod, but im here i n search of help.

**Comment by Sharkske** [comment]
new config https://pastebin.com/NN0YqiyM 

same issue just, bases arent fully unloading after leaving them

**Comment by bloodmc** [comment]
Test without sponge.

**Comment by Sharkske** [comment]
i ran a test server without sponge still the same issue

**Comment by JBYoshi** [comment]
Not a Sponge bug then.

**Comment by Sharkske** [comment]
thanks for the help...
