### ISSUE TITLE
The many paths to NPE on Adapter line 382

### ISSUE THREAD

**Issue by napentathol** [SpongePowered/Sponge#1513]
I noticed this in commit d31c658, though, presumably it affects every commit after 4f6471a.

This is breaking custom recipes in spongevanilla-1.12.1-7.0.0-BETA-320.jar

---

If you look at line 382 of org.spongepowered.common.item.inventory.adapter.impl.Adapter there is a precondition that "parent" not be null. This is apparently because there is a need in getPlugin() to ensure that "parent" is defined, and if "parent" is defined as "this", then there must be a "root container".

The problem occurs on line 48 of InventoryUtil where toSpongeInventory initializes a CraftingGridInventoryAdapter.

On line 46 of CraftingGridInventoryAdapter in the first initializer, it initializes parent to null. This violates the precondition in Adapter and throws an NPE.

But that is not all, this can also hypothetically occur on:
line 54 of GridInventoryAdapter
line 46 of Inventory2DAdapter
line 48 of OrderedInventoryAdapter
line 47 of EquipmentInventoryAdapter

Though, to my knowledge, none of these methods are actually used, and can probably be removed.

**Comment by napentathol** [comment]
https://github.com/napentathol/SpongeCommon/compare/bleeding...napentathol:1513

I can open a PR if you want

**Comment by Faithcaio** [comment]
The NPE should be solved in latest.

The actual issue is not.
But it requires a rewrite of our lens-system and where we mixin into inventories.

Thanks for your investigation anyways.
