### ISSUE TITLE
"java.sql.BatchUpdateException: (conn:12908) Unknown command" from mariadb-java-client

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/Sponge#1514]
##Recently the library `mariadb-java-client` has been updated from `2.0.2` to `2.1.0`, which is a bugged version, causing `java.sql.BatchUpdateException: (conn:12908) Unknown command` exceptions when excuting batches of prepared statements.  
I'm asking to revert c4d8144c39c842214739f1131ca45b2cc2c53e30 from @Minecrell or downgrade it to 2.0.2 or 2.0.3 (LuckPerms for BungeeCord uses that version) as these versions work.  
Also see: https://jira.mariadb.org/browse/CONJ-520

**I am currently running...**
- SpongeForge version: 1.12.1-2444-7.0.0-BETA-2562+
- Java version: 1.8.131
- Operating System: Debian 9.1
- Plugins (with that issue): LuckPerms, Prism

**What is the expected result?**
That prepared batch statements can be executed.

**What is the current result?**
Prepared batch statements thrown an exception.

Just the exceptions: 
- https://hastebin.com/sitadonilu.log
- https://hastebin.com/siwicameti.log
Please note that these exceptions are not to be found in the logs!

**Comment by ryantheleach** [comment]
Glad you found the issue, seemed like it was driving you insane :-(

**Comment by BrainStone** [comment]
Trying to fix it for 16 hours straight. Yes. It drove me insane.

**Comment by stephan-gh** [comment]
@BrainStone I apologize for all the trouble this has caused you. I did some basic testing with the new  version, but I can't cover all cases (and I expect upstream to do these tests to be honest). Hopefully they fix it upstream soon.

**Comment by BrainStone** [comment]
Thanks Mincrell! I don't blame you for this issue. As it turns out it is an issue partially caused by me too, as this problem only occurs with MariaDB 10.3 (which is an alpha version). But thanks for changing it back. And update for SF and SV would be highly apprechiated!

**Comment by stephan-gh** [comment]
> And update for SF and SV would be highly apprechiated!

Already done. :)
