### ISSUE TITLE
SpongeEntityType.translation is unused and would be incorrect if it were used

### ISSUE THREAD

**Issue by Pokechu22** [SpongePowered/Sponge#1516]
This code:

https://github.com/SpongePowered/SpongeCommon/blob/7f977c8628ce5f47813a06084a31a6f8c6f78c0d/src/main/java/org/spongepowered/common/entity/SpongeEntityType.java#L91-L99

is incorrect.  It would produce translation codes like `entity.magma_cube.name`, when the actual translation code is `entity.LavaSlime.name` (using old IDs) - [see burger](http://pokechu22.github.io/Burger/1.12.1.html#language:entity).  However, fortunately the `SpongeEntityType.translation` field is actually unused - instead, a parameter is passed and given to the superclass, which actually handles the translation (and that is correct, so there are no problems ingame).  `EntityList.getTranslationName(EntityList.getKey(clazz))` would need to be used instead, and in fact it (or the equivalent) is used to actually make the `translation` parameter:

https://github.com/SpongePowered/SpongeCommon/blob/7f977c8628ce5f47813a06084a31a6f8c6f78c0d/src/main/java/org/spongepowered/common/registry/type/entity/EntityTypeRegistryModule.java#L202-L203

This incorrect code (and the unused `SpongeEntityType.translation` field) should be removed.

**Comment by Pokechu22** [comment]
I wasn't sure whether I should make a PR, an issue, or just bring this up in IRC - if this isn't the best place, let me know.

**Comment by ST-DDT** [comment]
Are there `Translation`s for all `EntityType`s in there? IIRC in my research for #1306 that method also "failed" for some internal ones like complex part(?). That method also fails for the `Minecart` as it returns `entity.MinecartRideable.name` instead of `entity.Minecart.name` (AFAICT).

In addition to fixing it in Common we might also have to change the API to make the return value optional.

**Comment by Pokechu22** [comment]
Not all exist, true.  [This is a vanilla problem](https://bugs.mojang.com/browse/MC-68446 "[MC-68446] Some entities have the wrong name").
