### ISSUE TITLE
1.12.1 SV (L or R)Shift-clicking creative inventory destroy-item results in _Exception during phase body_  phase packet-errorspam

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1517]
Errorspam thrown while shift left/right clicking on the "Destroy Item" 'slot' on the 'Survival Inventory' tab of the Creative-mode inventory display, regardless of having items in inventory or completely empty, 

Reproducibility level: 100.0% 

org.spongepowered.common.event.tracking.phase.packet.CreativeInventoryPacketState errors

Happens for both leftclick and rightclick usages

**I am currently running...**

- SpongeForge version: 
- SpongeVanilla version: spongevanilla-1.12.1-7.0.0-BETA-321.jar
- Java version: 8_111
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
No mods required, naked server.

**What is the expected result?**
Clear all items from inventory slots

**What is the current result?**
Clears all items from inventory slots, and spams logs with many hundreds of lines of phase body error messages.

For Shift-Leftclick error, the log is here: https://pastebin.com/3GyRV7e2
For Shift-Rightclick error, the log is here: https://pastebin.com/Q54jvpye

Have been instructed to post phase-error stuff in SpongeCommon

**Comment by Faithcaio** [comment]
try again with latest

**Comment by theboomer** [comment]
Yes, this is now fixed.
Thank you for insanely prompt response to address :)
