### ISSUE TITLE
1.12.1 Bug or Intentional?  Player in cause for mob spawning cube EntitySpawnEvents not consistent with scenario

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1518]
I don't know if this is the way the system should work, or if it is a bug, but it doesn't seem to have a reason for me as to why it would work this way, making no consistant sense as to what player is listed in the cause and how so.

In this example, I go to the nether and find and stand beside a blaze spawner cube.  The cause for the EntitySpawnEvent is the following:

`Cause[{Name=Source, Object={LocatableBlockSpawnCause{SpawnType=SpongeSpawnType{id=sponge:mob_spawner, name=MobSpawner}, LocatableBlock=SpongeLocatableBlock{blockState=minecraft:mob_spawner, position=(636, 64, -130), worldId=a0ac2298-11d8-437a-bf27-ba787f04fa65, worldReference=java.lang.ref.WeakReference@3df9a108}}}}, {Name=Notifier, Object={EntityPlayerMP['BooMod'/221, l='DIM-1', x=640.07, y=64.00, z=-130.11]}}]`

Which shows me as the notifier object, as a Player object.
If I then teleport a different player to me, and we both stand beside each other, there is **no change** **in the cause.**
If I then leave the nether, and leave the other player standing by the mobspawner, the cause becomes:

`Cause[{Name=Source, Object={LocatableBlockSpawnCause{SpawnType=SpongeSpawnType{id=sponge:mob_spawner, name=MobSpawner}, LocatableBlock=SpongeLocatableBlock{blockState=minecraft:mob_spawner, position=(636, 64, -130), worldId=a0ac2298-11d8-437a-bf27-ba787f04fa65, worldReference=java.lang.ref.WeakReference@3df9a108}}}}, {Name=Notifier, Object={SpongeUser{isOnline=true, profile=com.mojang.authlib.GameProfile@1d921322[id=f2657b0b-fcb6-4d74-af49-3eb629035666,name=BooMod,properties={},legacy=false]}}}]`

which is still me in the cause, as a User object.

**What is the expected result?**
I would expect that the cause object either lists both players who are within the mobspawner activation range, or at the very least, whichever player it finds FIRST who is within the activation range, and in the case where I left the world and the other player was nearby, I would expect to have their player object in the cause, not mine.

What is the reasoning behind my player object being in the cause for blaze spawning events when I am in a different world and someone else is activating it?
I know that if it was a block I placed, then I would be forever listed in the cause as the owner of the spawner, but this case is using a naturally generated and discovered spawner.

---
**I am currently running...**

- SpongeForge version: 
- SpongeVanilla version:  spongevanilla-1.12.1-7.0.0-BETA-321.jar
- Java version: 8.111
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: 
Just the test plugin responding to event

**Comment by gabizou** [comment]
The way that the notification system works is if you *indirectly* interacted with the block by modifying a block close enough to that target block (in this case the mob spawner), this is more common when you interact with redstone to where the end result of all blocks that switched or were *notified* were notified by the player that initially interacted with the redstone machine at that time.

What you're noticing is that the other player has not interacted with the mob spawner block and therefor should not be listed as the notifier, because there's no logic in place to find out if they were the notifier or not. 

I notice this is 1.12, but does this even change if you switch to 1.10.2 or 1.11.2? The reason why I ask this is that I don't believe I've ever written any logic to mark things like mob spawners to be tracked based on player activation ranges.

**Comment by theboomer** [comment]
I suppose I could create some older test servers to see the result, but I only noted this when I examined the testing in these circumstances, which I hadn't done before now.

By modifying a block close to the mob spawner, I assume you mean "explored the space causing the chunk to load /be generated"  (what happens if the region is pregenerated??) -- because in this pristine test, I didn't touch any blocks anywhere within a 300 block radius of the blazespawner.

Still, okay, if the player in the cause really means nothing related to mob spawning event, we can run with that.  Why is the object a player (Boomod)  while I am near the spawner and in that world, but when I switched to a different world, the cause was me as a user-object?  Its not like I was offline, I was online, should it not still be a player object?  Why the inconsistency ... even if it is still a rather meaningless object to have that can't be useful for identifying who is near the spawner, should it not be the same in both cases?

**Comment by theboomer** [comment]
I think we can mark this as not a bug if that is how notifiers work, though still odd the difference in online player being a player in same world, user in other world...

If anything, there may be room for adding a player who was responsible for the 'activation' of the spawning, if possible somehow, to the contexts now.
