### ISSUE TITLE
1.12.1 CauseTracker Errors

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/Sponge#1521]
- SpongeVanilla version:bleeding latest
- Java version: 8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows
- Plugins/Mods: No mods

When I use piston with button, I obtain this [error](https://pastebin.com/bc9cVkBs)

Example : ![Image](https://image.noelshack.com/fichiers/2017/36/7/1505042581-2017-09-10-13-22-04.png)

**Comment by lesbleu** [comment]
CauseTracker is broken. [video](https://www.youtube.com/watch?v=HPT7HRUtEdI&feature=youtu.be) (Bug : PISTON_EXTEND, OWNER, ENTITY_HIT, BLOCK_HIT)

**Comment by Zidane** [comment]
@Deamon5550 @gabizou got a number of issues in that video above. Need for this to be looked into.

**Comment by lesbleu** [comment]
@bloodmc You have only fixed the bug "PISTON_EXTEND".

There are still bugs "OWNER", "ENTITY_HIT" and "BLOCK_HIT" and there is always an error when using a PISTON with BUTTON,

**Comment by bloodmc** [comment]
Yes I know, others will be fixed soon.
