### ISSUE TITLE
Furnance changes rotation if facing into a block

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#1522]
If you place a furnace down, and place some other solid block in front of if *(i tried it with gravel & another furnance)*, it will rotate as soon as it is fired up. After it rotated, it is empty and the items you just placed in the furnace are gone. This happens in both, SpongeForge and SpongeVanilla. This does not happen with only Forge installed or in Vanilla Minecraft.

**Tested Versions:**
SpongeForge: *1.12.1-2444-7.0.0-BETA-2609*
with Minecraft Forge: *14.22.0.2474*
**and**
SpongeVanilla: *1.12.1-7.0.0-BETA-326*

**Comment by phit** [comment]
still happens with https://github.com/SpongePowered/SpongeCommon/commit/caccfa4f325396c866bb803d51ee0c3763e8d073 (used SpongeForge), looks like the block rotates after being placed

https://phit.link/s/2017-11-07_18-33-59.mp4

alright this is too funny if you place another block on the opposite site it will switch direction twice
https://gist.github.com/phit/8de68e0efc7a2e1f08f54146d7cb2c3a

also checked doesn't happen in vanilla

tried a few other blocks
rotates: dropper, dispenser, furnace
doesn't rotate: anvil, pumpkin, piston

**Comment by ImMorpheus** [comment]
~~> also checked doesn't happen in vanilla~~

~~I'm able to reproduce this in vanilla (1.12, bleeding branch)~~

My bad.

**Comment by phit** [comment]
With Vanilla I meant actual Vanilla, not SpongeVanilla.

**Comment by Aaron1011** [comment]
@phit: I can't reproduce this on the latest SpongeForge. Can you see if it's still an issue for you?

**Comment by phit** [comment]
yup, seems fixed
