### ISSUE TITLE
1.12.1 Block-Hit context key/data never clears after first occurance, poisons all events after

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1527]
I have not tested all events, just enough to see pattern: The block-hit data is being set when a block is hit (attacked, like a tree/stone, yet not one-punch broken like grass/flowers) **and remembered infinitely**, and then poisons '**every**' event thereafter, being present in all events with that block hit info.

SpawnEntityEvent, DamageEntityEvent, ChangeBlockEvent.Place, ClientConnectionEvent.Join, MessageChannelEvent.Chat etc..., set to log the event.getContext().keySet() and event.getContext().get(EventContextKeys.BLOCK_HIT) results...

1) Boot server 2) Join server : Observe logging that keys are empty, BH data empty for .Join event
3) Observe spawning events logging with spawn-type key only, BH data empty
4) Type something in chat   Observe empty keyset, empty BH data
5) Observe Place event logging as vines grow and such changes happen, empty context keyset, empty BH data
6) Drown yourself to take a few damage hits  Observe damage with empty keyset, empty BH
7) Whack sandblock, breaking not required
8) Observe any Place events still occuring around are spamming with BlockHit key in context, and the BH data is the sand block at the location just whacked
9) Move around, let chunk genererating do more Place and Spawning events,   Observe Spawn event now includes BlockHit key, with BH data of sand block for each event spamming log
10) Type something in chat  ) Observe chat context keyset contains BlockHit, and BH data of the sand block
11) Disconnect from server  12) Relogin to server
13) Observe the Join event contains BlockHit in keyset, and BH data for the sandblock

14) Hit a tree, observe all events in log are logging that tree-type log block
15) drown self to take damage ) Observe each damage event logs BlockHit in keyset, BH data of the log block...
16) explore for 5 minutes not touching anything, see all the events keep spamming that blockhit info.
...

**The BlockHit data gets inserted into Context for everything once it happens and never disappears.**

**I am currently running...**

- SpongeForge version: spongeforge-1.12.1-2479-7.0.0-BETA-2624, Forge 2479
- SpongeVanilla version: spongevanilla-1.12.1-7.0.0-BETA-327
- Java version: 1.8.111
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: 
Just test logging plugin

**What is the expected result?**
A blockhit key and data only to be present for things like interact and break, maybe place, etc, but definitely not for chat, or the server spawning 

**What is the current result?**
Oprah-esque "You get a BlockHit, and you get a BlockHit, and all you events in the audience, look under your chair - YOU ALLL get a BlockHit!" behavior.

**Comment by Deamon5550** [comment]
Fixed in 2848bbfb5151db0f880cab335c376c901dd9a090
