### ISSUE TITLE
No lightning sound effect.

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#1529]
**Tested on the following...**

- SpongeForge-1.10.2-2477-5.2.0-BETA-2632 with Forge-1.10.2-12.18.3.2477
- SpongeVanilla-1.10.2-5.2.0-BETA-395
- SpongeForge-1.12.1-2480-7.0.0-BETA-2634 with Forge-1.12.1-14.22.1.2480
- SpongeVanilla-1.12.1-7.0.0-BETA-328
- Java version: 1.8.0_144
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: None
**What is the expected result?**
BOOM!
**What is the current result?**
Lightning has no sound effect.

- Yes, I did make sure my client sounds were on during these tests.
- Lighting sound is present when running Forge without SpongeForge.
- TheHiggsBozo on IRC also tested and confirmed this.

**Comment by theboomer** [comment]
Tested by summoning lightning_bolt

**Comment by kashike** [comment]
See https://github.com/SpongePowered/SpongeForge/issues/1776 for more details.
