### ISSUE TITLE
1.12.1 Context: FishingEvent.Stop Use_Item context missing when retracting rod while block-selection present

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1532]
If the player **secondary-clicks** the rod against a block to pull in the line(ie, the block-selection hitbox is present, player clicking against the block) then the **Use_Item** key-data _is missing_ from the context.

The **Use_Item** key-data _is_ _present_ (the rod used) in the context if secondary clicking the rod 'in the air' or when there is no block within reach for the line of sight while pulling in the line.

See video in action: 
https://youtu.be/Rajv4IwSn6k

**I am currently running...**

- SpongeForge version: spongeforge-1.12.1-2480-7.0.0-BETA-2634
- SpongeVanilla version: spongevanilla-1.12.1-7.0.0-BETA-328
- Java version: 1.8.111
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: None other than test plugin outputting fishing event context keyset

**What is the expected result?**
Use_Item context should be present for retracting the rod at all times

**What is the current result?**
Use_Item context absent when rod 'interacts' with block in reach

Plugin code:
```
  @Listener
    public void retractFishingRod(FishingEvent.Stop event, @Root Player player) { //
        Sponge.getServer().getBroadcastChannel()
                .send(Text.of(TextColors.AQUA, "Fishing Stop Context: " + event.getContext().keySet()));
    }
```

**Comment by Zidane** [comment]
Closing as I have a PR for this here: https://github.com/SpongePowered/SpongeCommon/pull/1548
