### ISSUE TITLE
Skin unique id for Human entity doesn't work properly

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1535]
Simple code:
```Java
Human e = (Human) player.getWorld().createEntity(EntityTypes.HUMAN, player.getLocation().getPosition());
e.offer(Keys.SKIN_UNIQUE_ID, player.getUniqueId());
```
This works wrong. Skin will not be set, you need to rejoin the server.
https://cdn.discordapp.com/attachments/142425521391665153/360127022728478730/2017-09-21_00.16.00.png
https://cdn.discordapp.com/attachments/142425521391665153/360127467555389440/2017-09-21_00.17.49.png

**Comment by XakepSDK** [comment]
This work fine only if i set this data before spawning human.

**Comment by Cybermaxke** [comment]
IMO the server should handle this properly so you don't need to rejoin the server.

**Comment by Zidane** [comment]
I have been able to set this after they've spawned and their skin changes.

``` java
    @Listener
    public void onInteractEntityMainSecondary(InteractEntityEvent.Secondary.MainHand event) {
        if (event.getTargetEntity() instanceof Human) {
            event.getTargetEntity().offer(Keys.SKIN_UNIQUE_ID, new Random().nextBoolean() ? UUID.fromString("85271de5-8380-4db5-9f05-ada3b4aa785c")
                    : UUID.fromString("004204f2-3c19-4446-9794-d09d1f015d59"));
        }
    }
```

**Comment by XakepSDK** [comment]
@Zidane 
I think, this can be reproduced if you spawn human during player join event.
I'll try this little bit later.
