### ISSUE TITLE
Inventory#getProperty doesn't work as expected

### ISSUE THREAD

**Issue by benfah** [SpongePowered/Sponge#1538]
When you build an Inventory, e.g.
`Inventory inv = Inventory.builder().of(InventoryArchetypes.CHEST).property("test", new Identifiable()).build(this);`
and then try to get the Identifiable object by:
`inv.getInventoryProperty(Identifiable.class)`
or:
`inv.getProperty(Identifiable.class, "test")`
both return Optional.empty.

Normally the Identifiable object should be returned.

Sponge 1.12.2

**Comment by VapidLinus** [comment]
I am noticing this issue as well. Seems to affect other types of `AbstractInventoryProperty` as well. Here's some code to quickly replicate this, just type _!test_ in chat:

```java
@Listener
public void onTest(MessageChannelEvent.Chat event) {
	if (!event.getRawMessage().toPlain().equalsIgnoreCase("!test")) return;

	Inventory inventory = Inventory.builder()
			.of(InventoryArchetypes.CHEST)
			.property("test", new Identifiable())
			.build(plugin);

	logger.info("getInventoryProperty present? {}", inventory.getInventoryProperty(Identifiable.class).isPresent());
	// OUTPUT: getInventoryProperty present? false
	logger.info("getProperty present? {}", inventory.getProperty(Identifiable.class, "test").isPresent());
	// OUTPUT: getProperty present? false
	logger.info("getProperties size? {}", inventory.getProperties(Identifiable.class).size());
	// OUTPUT: getProperties size? 0
}
```

**Version:**
> spongevanilla-1.12.2-7.0.0-BETA-337

**Comment by VapidLinus** [comment]
@Faithcaio Hey, sorry to ping you, but can you or another Sponge developer confirm that you are able to reproduce this? If not, I'd like to submit more information so this can be fixed asap. None of the inventory properties seem to work right now and this is drastically impacting what we can do with the inventories.

Thanks in advance 🎉 

> 1.12.2-7.0.0-BETA-345

**Comment by Faithcaio** [comment]
Should be all fixed in latest.

Also the InventoryBuilder does no longer need the property name.
`builder.property(new Identifiable())` is the same as `builder.property("identifiable", new Identifiable()))`
works with
`inventory.getInventoryProperty(Identifiable.class)`
