### ISSUE TITLE
Dependency as asset

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1540]
We need some way to store dependencies in plugins.
May be 'lib' directory, like in WAR?

**Comment by JBYoshi** [comment]
The Gradle `shadow` plugin and the Maven `shade` plugin are the recommended ways of doing this, and don’t need any special support.

**Comment by XakepSDK** [comment]
The best way to make a dependency trash from your plugin jar.
upd: Plugins are not isolated from each other, some plugin can provide lib-a:1.0.0 and another plugin can provide lib-a:0.9.8. Need a way to handle this too.

**Comment by stephan-gh** [comment]
@XakepSDK That's why you should **relocate** (e.g. move their classes into a subpackage of your plugin) the dependencies you shade into your plugins. That way they have different class names and won't conflict with each other.

**Comment by Zidane** [comment]
Closing as SpongeAPI isn't going to reinvent the wheel that modern toolchains already do much better than we ever would.

**Comment by Mumfrey** [comment]
I should also point out that if running on Forge the requested functionality is already fully supported via the `ContainedDeps` manifest entry.
