### ISSUE TITLE
1.12.x TNT becomes PrimedTNT, fizzles, and disappears immediately when triggered by specific scenarios of redstone energy

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1546]
**TNT will prime, flash, make a fizzle sound and disappear when powered by SOME configurations of being powered by redstone energy, just POOF out of existence.**
--
All versions of 1.12.2 SpongeForge and SpongeVanilla and likely further back through 1.12s
Default sponge configs, plus or minus Panda redstone, Panda settings=no difference.

---

Specific observations generalized from test scenarios suggest 0/1/2 redstone tick differences, easily reproduced:

- If TNT is placed by the player **into a location that is powered**, no matter how, when placed->**POOF**
- If TNT is pushed by a piston into a powered location, it is normal (flashes and explodes=**BOOM**)
- If piston pushes a block of redstone, or completes a circuit that powers the tnt block adjacent to the final position (ie, push wool over a redtorch or between a powered repeater and tnt) -> **POOF**
- A redtorch placed beside TNT, or offtorch beside tnt that becomes powered -> **BOOM**
- An unpowered repeater/comparator aimed at tnt, when powered -> **BOOM**
- Placing a redwire between a on-torch and tnt-> **POOF**
- Placing a redtorch onto a powered block results in the redtorch flicker before going off, but that is sufficient to prime adjacent tnt->**POOF**

--

To further complicate things, the oldest forge tested seemed to actually have explosions even though invisible for some tests, and some of those destroyed the blocks when making the noise, while some of the others sounded the blast but did not damage any blocks (until logout/login).  (Have not tested older SV)

==
_I realize now this bug was likely present for a while, as I was encountering a lot of oddities related to these scenarios while porting a tnt-regulating plugin prior to cause/context versions; but do not know how earlier, as it was only then discovering that my handlers were not responding to their BlockSnapshot root filters, having been changed to LocatableBlocks causes some time sooner._

**Comment by kashike** [comment]
Can confirm.

**Comment by RedNesto** [comment]
Seems everything is working fine on my side:
- spongeforge-1.12.2-2586-7.1.0-BETA-2865

and
- spongevanilla-1.12.2-7.1.0-BETA-14

But I think it would need the confirmation from someone else.

**Comment by ryantheleach** [comment]
Retested a few of these as a spot test on SpongeVanilla, works.

@theboomer Thanks for the detailed reproduction steps.
@RedNesto Thanks for taking the time to test this issue.
