### ISSUE TITLE
Unable to start under java 9. Version string changed.

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1553]
Unable to start under java 9 because version string was changed.

**Comment by kashike** [comment]
This isn't a huge issue, seeing as Sponge won't run on Java 9 currently.

**Comment by gabizou** [comment]
Java 9 is not supported currently by a larger majority of Sponge's toolchain. When we do get to have Java 9 support in our toolchain, we'll be able to provide support with the java checker.
