### ISSUE TITLE
1.12.2 Context: XP Orbs from mob death/player death drop have no  Spawn_Type context key

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1556]
When players die and their orbs are scattered about, or when they kill a mob and orbs are dropped to pick up, the spawn event for the orbs has no context entry , no spawn_type EventContextKey as all spawn event should.
Does not impact XP from enchantment bottles.

------
SpongeVanilla-1.12.2-beta-343
SpongeForge=1.12.2-bets-2684  Note: On my forge server version, I can not SEE any of the entities at all; I can splash-potion XP bottles and see the effects, sounds, and spawn-events in log, but not orbs.  I can summon mobs and hear them, be hurt by them, but not see them, even disconnectin/reconnecting no.  I do not have this effect on the SV version -- yet.  I will test this later today more indepth to see if I am crazy or not before reporting, but if someone can just second-glance it ...

Environment: Zero mods, zero plugins except one logging SpawnEntityEvents with missing key.

**Comment by ImMorpheus** [comment]
PR merged. This can be closed.

**Comment by phit** [comment]
~actually leaving this open until it's on the stable branch~
