### ISSUE TITLE
LeashHitch#getLeashedEntity() returning null

### ISSUE THREAD

**Issue by Xenmai** [SpongePowered/Sponge#1558]
I'm using the latest Vanilla build: spongevanilla-1.12.2-7.0.0-BETA-345.jar
When using the LeashHitch#getLeashedEntity() method I expect to get an Entity, but I'm getting null instead.

**Comment by Faithcaio** [comment]
The leashed entity holds a reference to the entity holding it not the other way around.
see `LeashData` in API7 
`Keys.LEASH_HOLDER` in API8+

You could attempt to work around this by getting nearby entities and checking the LeashData.
