### ISSUE TITLE
LAST_DAMAGE and PARROT_VARIANT

### ISSUE THREAD

**Issue by seema84** [SpongePowered/Sponge#1561]
Build: 1.12.2-345

[18:38:26 WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.LAST_DAMAGE
[18:38:26 WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.PARROT_VARIANT

please complete this functions

**Comment by XakepSDK** [comment]
Parrot variant
https://github.com/SpongePowered/SpongeCommon/pull/1495

**Comment by parlough** [comment]
I'll finish the parrot PR soon. I can look into LAST_DAMAGE as well.

**Comment by parlough** [comment]
Parrot variant is now implemented in the latest bleeding builds, not sure when I'll leave a chance to do last damage though as it is more involved I believe. I'll look into it though.

**Comment by gabizou** [comment]
Why this wasn’t closed to direct to #8 is not something I’m going to spend time to. These warnings have been pretty standard to attach to said issue. Duplicate of #8
