### ISSUE TITLE
InventoryBuilder listener not functional

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Sponge#1563]
When using the inventory builder to pass inventory event consumer as listener
```
Inventory.builder()
    .of(InventoryArchetypes.DOUBLE_CHEST)
    .listener(ClickInventoryEvent.class, event -> {
        Container targetInventory = event.getTargetInventory();
        ...
```
The provided consumer in the .listener method is never called

- SpongeVanilla version: 1.12.2-7.0.0-BETA-345
- Java version: 1.8_something
- Operating System:

 - [ x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ x] Windows

guess i can just tag this dude @Faithcaio

**Comment by VapidLinus** [comment]
I think this is the same as https://github.com/SpongePowered/SpongeAPI/issues/1646

A temporary workaround is to use `InventoryArchetypes.MENU_GRID` instead, as the `.listener()` callback works for that one.

**Comment by NeumimTo** [comment]
That indeed helped, however i need more space than just 3*9 grid, i guess theres no way to resize the menu grid archetype

**Comment by VapidLinus** [comment]
@NeumimTo I think you can using the `InventoryDimension` property. Try this:
```java
Inventory inventory = Inventory.builder()
		.of(InventoryArchetypes.MENU_GRID)
		.property(InventoryDimension.PROPERTY_NAME, InventoryDimension.of(6, 9))
		.listener(ClickInventoryEvent.class, e -> {
			logger.info("MENU_GRID listener works!");
		})
		.build(plugin);
```

**EDIT:**
In the latest build I think you can simplify the property method to just:
`.property(InventoryDimension.of(6, 9))`

**Comment by XakepSDK** [comment]
//offtop
Latest sponge api allows this:
`.property(InventoryDimension.of(6, 9))`

**Comment by XakepSDK** [comment]
@kashike fixed by https://github.com/SpongePowered/SpongeCommon/commit/b22c02d2e0cde0e94e62b1b125a4d14aed8b0625
