### ISSUE TITLE
Implementation Request: ChangeEntityExperienceEvent and ChangeLevelEvent.TargetPlayer

### ISSUE THREAD

**Issue by Xenmai** [SpongePowered/Sponge#1569]
Hello there. I'm using latest SpongeVanilla 1.12.2 and I've not managed to trigger the ChangeEntityExperienceEvent and ChangeLevelEvent.TargetPlayer events at all. If I'm not mistaken, they should fire when a player collects experience and when a player levels up, respectively.  I assume this is because they are not implemented, so I'm requesting their implementation. Thanks a lot for your time!

**Comment by ryantheleach** [comment]
@JBYoshi You have probably had the most experience with experience of late.

**Comment by JBYoshi** [comment]
See #1467, although I won't mark this as a duplicate since the other one doesn't mention `ChangeLevelEvent.TargetPlayer`.

I will likely end up rewriting the experience events as I implement them.

**Comment by gabizou** [comment]
@JBYoshi did you ever get anything on this done?

**Comment by JBYoshi** [comment]
I had some half-working code in my Git stash for a while. Finally got it completed and tested.
