### ISSUE TITLE
InventoryBuilder#listener never catches InteractInventoryEvents

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/Sponge#1577]
**I am currently running...**
- SpongeVanilla version: spongevanilla-1.12.2-7.0.0-BETA-346
- Java version: 1.8.0 51
- Operating System:
   - [ ] Linux (Ubuntu, Debian, Fedora, etc)
   - [ ] macOS
   - [x] Windows

- Plugins/Mods: 
  - HuskyUI
  - HuskyCrates

**What is the expected result?**
When an InteractInventoryEvent is fired, I should be able to catch it via a listener in an Inventory Builder. This worked some time ago with API 6 and earlier API 7.

**What is the current result?**
The listener is never called.
No errors are thrown.

**Comment by parlough** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/b22c02d2e0cde0e94e62b1b125a4d14aed8b0625 should have fixed this I just don't think SpongeVanilla has had its SC ref bumped.

**Edit:** Yeah it hasn't been bumped in 21 days. @kashike

**Comment by parlough** [comment]
Should be fixed by https://github.com/SpongePowered/SpongeVanilla/commit/d436a118c8d74f9ee492beb2af11c4d12c96cb0e :)

Give it a test once it builds and is uploaded

**Comment by codeHusky** [comment]
Resolved in 1.12.2-7.0.0-BETA-348 SV
