### ISSUE TITLE
Doesn't works with java 9

### ISSUE THREAD

**Issue by RiftomeR** [SpongePowered/Sponge#1578]
I'm using java 9 and server doesn't starts
https://pastebin.com/47C8KcvP

**Comment by parlough** [comment]
Minecraft, Forge, Sponge, and much more that Sponge relies on is not ready to support Java 9 yet and they won't for awhile. Refer to issues such as https://github.com/SpongePowered/SpongeVanilla/issues/355#issuecomment-335770593 and https://github.com/SpongePowered/SpongeCommon/issues/1553 for more information. For now use the latest version of Java 8 :)

**Comment by RiftomeR** [comment]
ok
