### ISSUE TITLE
Implementation request:Player.getOpenInventory()

### ISSUE THREAD

**Issue by RiftomeR** [SpongePowered/Sponge#1580]
This method always returns optional.empty().
Tested on SpongeVanilla version 1.12.2-7.0.0-BETA-349

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1104

https://github.com/SpongePowered/SpongeCommon/pull/1011

**Comment by ryantheleach** [comment]
@phit Can this be closed?
