### ISSUE TITLE
NoClassDefFoundError: net/minecraft/command/EntitySelector

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/Sponge#1586]
https://gist.github.com/ziceptor/f310111e365f86eda8fa93daa6a88ed8

forge-1.12.2-14.23.0.2529-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2726.jar

**Comment by phit** [comment]
update to latest, this was fixed in https://github.com/SpongePowered/SpongeCommon/commit/1491973d983b0dc1553b19256c4672e3e6a32598 & https://github.com/SpongePowered/SpongeForge/commit/cd16d610242a4b012454ab47f6eb95c10a5476aa

**Comment by ziceptor** [comment]
Sorry.
