### ISSUE TITLE
Spawn limit not work [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/Sponge#1589]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2698.jar
- SpongeVanilla version: 
- Java version: 1.8.0_151
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
**Modpack Sky Factory 3 (3.0.15)**
Plugins (180): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Not Enough Items, OpenComputers (Core), SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, Fence Overhaul, Actually Additions, CodeChicken Lib, CodeChicken Core, EnderStorage, Just Enough Items, OpenComputers, ActuallyComputers, Baubles, Extra Utilities 2, AngelRing 2 Bauble, AppleCore, apple_shields, AppleSkin, AutoPackager, Psi, AutoRegLib, Baconators, CraftTweaker JEI Support, MineTweaker 3, B.A.S.E, BD Lib, Bed Bugs, Better Builder's Wands, BiomeTweaker, BlockDispenser, Guide-API, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Mantle, Tinkers' Construct, Ceramics, Chameleon, MCMultiPart, ‽, |, /, Chickens, Chisel, Chisels & Bits, ShadowMC, Clipboard, Clumps, Cyclops Core, Colossal Chests, CommonCapabilities, Cooking for Blockheads, Waila, Dark Utilities, PTRModelLib, Decocraft, Dimensional Cake, Draconic Evolution, Dragon Mounts, Storage Drawers, Drawers & Bits, Elevator Mod, EnderCore, Ender IO, Energy Converters, Engineer's Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Ex Nihilo Adscensio, Ex Compressum, Extra Bit Manipulation, Zero CORE, Extreme Reactors, Farming for Blockheads, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Shadowfacts' Forgelin, Funnels, Garden of Glass, Advanced Generators, Gravestone Mod, Grue, Get Ya' Tanks Here, Hammer Core, Headcrumbs, Hopper Ducts, HydroGel, Immersive Engineering, Integrated Dynamics, Integrated Tunnels, Iron Chest, It's Raining Food, KleeSlabs, LLibrary, Literal Ascension, Long Fall Boots, Loot Bags, LunatriusCore, MineMenu, MiniCoal, Natura, Missing Pieces, Random Things, Roots, MoarSigns, mob_grinding_utils, MTLib, Mod Tweaker, More Chickens, More Shearables, More Shears, Morpheus, Mystical Agriculture, Nice, Not Enough Wands, OreExcavation, Pam's HarvestCraft, ShetiPhian-Core, Platforms, BetterChunkLoader, Buycraft, CatClearLag, GriefPrevention, LuckPerms, Nucleus, SkyClaims, TabManager, TickProfiler, UltimateCore, StatusProtocol, RebornCore, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, Refined Storage, RebornStorage, Redstone Paste, Reliquia, RFTools, RFTools Control, RFTools Dimensions, Wooden Shears, Scanner, Shear Madness, Simple Achievements, Simple Barrels, Simple Corn, Simple Generators, SimpleLabels, Simply Jetpacks 2, Snad, Solar Flux Reborn, Steve's Carts 2, Super Circuit Maker, The Beneath, Tinkers Tool Leveling, Tiny Progressions, TorchMaster, Translocator, Twerk-Sim 2K16, Twitchcrumbs, voidcup, Waddles, WanionLib, I Can See Everything, What Are We Looking At, Wither Crumbs, WorldEdit, Experience Rings, UniDict

**What is the expected result?**
In the configuration of each world, I am establishing a limit of hostile entities, but when checking it within the game, it seems to have no effect.
The same happens with the spawn rate, I have increased it and the generation is the same.
Here are the configuration files for the Nether dimension:
dimension.conf: https://pastebin.com/raw/AhUYh435
world.conf: https://pastebin.com/raw/GBaj1kGQ

**What is the current result?**
The number of hostile entities should be lower.
In the following image I am in a nether dungeon, and I show the amount of entities that are around me, it is always the same amount, between 70 - 75 entities. I want to clarify that there is no other dimension loaded, and only I am connected to the server.
![screenshot_3](https://user-images.githubusercontent.com/13698597/32625750-bbf271d4-c552-11e7-9324-fbc382f9873a.png)

Then I use a clear-lag plugin command, which allows to kill all hostile entities, as shown in the chat.
If I do this, the plugin removes 71 entities, and the statistics on the F3 screen coincide with the elimination of all the entities and only 5 remain, I am sure that those 5 entities were generated immediately after entering the command.
![screenshot_4](https://user-images.githubusercontent.com/13698597/32625803-e11f2222-c552-11e7-913d-1cebe4065426.png)
This should not happen, since the stable configuration file has a maximum of 40 hostile entities, so that limit has no effect.
The same thing happens with tick-rate-monster, increase it to 400, and the speed with which entities are regenerated after eliminating them with Clear-lag, is incredibly fast.

fml-server-latest: https://pastebin.com/raw/2JbiG684

**Comment by phit** [comment]
you set `config-enabled=false` in both files.. also mob spawners are not natural spawns so those won't be affected at all

**Comment by HeberonYT** [comment]
Thanks for the information, now it seems to work.
