### ISSUE TITLE
/help unable to be run in single player without permissions manager.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1594]
Without a permissions service being present, players do not have access to /help by default.

Tested on freshly cloned SpongeForge.

**Comment by phit** [comment]
that is intentional as far as I can tell, https://github.com/SpongePowered/SpongeCommon/pull/1484

**Comment by ryantheleach** [comment]
Not necessarily. before it had no permission, which means you couldn't prevent it even if you wanted to.

Adding a permission doesn't necessarily mean you don't have access to commands by default / in single player. OP levels exist for a reason.
