### ISSUE TITLE
Feature: Alert admins to which plugins potentially reloaded?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1600]
I'm after some input of if the following feature would be worth implementing.

When issuing the /sponge plugins reload command, it would be handy to know if the plugin listed even listened for the reload event.

I propose something like this after running:

1. `/sponge plugins reload`

`Issuing reload command to: PluginA , PluginB, PluginX , PluginZ`

Then admins would be aware of any plugins that failed to listen, as they would not be listed.

2. `/sponge plugins reload PluginA`

either, 

`Issuing reload command to: PluginA`

or 

`PluginA does not support reloading.`

**Comment by parlough** [comment]
I think this would be a great addition along with some of the other changes presented in https://github.com/SpongePowered/SpongeCommon/issues/807. 

I think reporting that the plugin does not support it is better if they simply don't listen to the event, as claiming there is an issue instead suggests the plugin had trouble reloading or failed somewhere(which could be something else we report).

**Comment by ryantheleach** [comment]
@Meronat Maybe the language I used was slightly confusing.

If the plugin is listening for the reload event, then it would show:

`Issuing reload command to: PluginA`

If the plugin asked, does not listen for the reload event

`PluginA does not support reloading.`

**Comment by ryantheleach** [comment]
Closing to consolidate with : https://github.com/SpongePowered/SpongeCommon/issues/807
