### ISSUE TITLE
Entity#getNearbyEntities will sometimes not include the originating entity

### ISSUE THREAD

**Issue by widd** [SpongePowered/Sponge#1607]
**I am currently running...**
- SpongeVanilla version: 1.12.2-7.0.0-BETA-352
- Java version: 8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)

- Plugins/Mods: 
 A simple test plugin

**What is the expected result?**
`getNearbyEntities` should include all entities from a given `Entity`'s location, including the `Entity` whose location is used per the javadoc (as it calls another method in `EntityUniverse` that takes a location).

**What is the current result?**
The `Entity` is missing from the resulting collection.

This can be seen by using `getNearbyEntities` with distances of 25 and 50m respectively.

**Comment by JBYoshi** [comment]
Cannot reproduce.

Code:
```java
package jbyoshi.sponge.test;

import org.spongepowered.api.Sponge;
import org.spongepowered.api.entity.Entity;
import org.spongepowered.api.entity.living.player.Player;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.entity.InteractEntityEvent;
import org.spongepowered.api.event.filter.cause.Last;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.service.pagination.PaginationService;
import org.spongepowered.api.text.Text;

import java.util.stream.Collectors;

@Plugin(id = "common1607")
public class Common1607 {
    @Listener
    public void onInteract(InteractEntityEvent e, @Last Player p) {
        Sponge.getServiceManager().provideUnchecked(PaginationService.class).builder()
                .title(Text.of("Entities near ", toText(e.getTargetEntity())))
                .contents(e.getTargetEntity().getNearbyEntities(25.0).stream().map(Common1607::toText).collect(Collectors.toList()))
                .sendTo(p);
    }

    private static Text toText(Entity entity) {
        return Text.of(Text.of(entity.getTranslation()), "[", entity.getUniqueId(), "]");
    }
}
```

![](https://user-images.githubusercontent.com/12983479/33046877-89085dfa-ce18-11e7-97bc-969a60c767e0.png)

Could you provide some sample code and steps to reproduce?

**Comment by widd** [comment]
This was enough to trigger it in my last test:
```
@Listener
public void onChat(MessageChannelEvent.Chat event, @Root Player player) {
	Collection<Entity> nearby = player.getNearbyEntities(50D);
	System.out.println("all nearby entities");
	nearby.forEach(System.out::println);
}
```

Results in this output:
```
[02:11:11 INFO] [STDOUT]: all nearby entities
[02:11:11 INFO] [STDOUT]: EntityPig['Pig'/160, l='world', x=127.83, y=64.00, z=223.78]
[02:11:11 INFO] [STDOUT]: EntitySquid['Squid'/672, l='world', x=112.50, y=62.00, z=234.50]
[02:11:11 INFO] [STDOUT]: EntitySquid['Squid'/83, l='world', x=111.68, y=57.70, z=232.37]
[02:11:11 INFO] [STDOUT]: EntityItem['item.item.bone'/86, l='world', x=111.92, y=67.00, z=255.53]
[02:11:11 INFO] [STDOUT]: EntityPig['Pig'/102, l='world', x=126.75, y=64.00, z=203.77]
[02:11:11 INFO] [STDOUT]: EntityPig['Pig'/87, l='world', x=111.26, y=64.00, z=251.55]
[02:11:11 INFO] [STDOUT]: EntityItem['item.tile.dirt.default'/107, l='world', x=118.75, y=65.00, z=245.49]
[02:11:11 INFO] [STDOUT]: EntityItem['item.item.seeds'/108, l='world', x=120.60, y=67.00, z=251.88]
```

It seems to be intermittent between reboots, I see no direct cause yet.

**Comment by widd** [comment]
I spotted this too:
```
01:23:46 INFO] [STDOUT]: EntityPlayerMP['widd_'/2705, l='world', x=160.34, y=64.00, z=225.40]
[01:23:46 INFO] [STDOUT]: EntityItem['item.tile.sapling.birch'/3618, l='world', x=171.15, y=69.00, z=225.11]
[01:23:46 INFO] [STDOUT]: EntityPlayerMP['widd_'/505, l='world', x=160.00, y=63.81, z=244.00]
```

It listed me twice in the collection returned directly from `getNearbyEntities`, in two different locations.

**Comment by ryantheleach** [comment]
was there more then 8 entities? If so it's the config file getMaxEntities in AABB getting in the way.

**Comment by widd** [comment]
@ryantheleach That solved the issue, however that now begs the question as to why the naming conventions are as such if they do wildly different things.

In `EntityUniverse` we have:
* `getNearbyEntities`
* `getEntities`

One would assume `getNearbyEntities` would logically just delegate to `getEntities` with a distance check predicate, but the former delegates to `getIntersectingEntities` while the latter is left for implementation - which seems to use `VecHelper` everywhere else.

https://github.com/SpongePowered/SpongeCommon/blob/c96a2d8c2b7a3ab8bb2d1c61cdea47a55ba3a8a9/src/main/java/org/spongepowered/common/world/extent/SoftBufferExtentViewDownsize.java#L473

Without @ryantheleach knowing offhand I never would have been able to fix this - perhaps a refactor or added docs are in order?

**Comment by ryantheleach** [comment]
The real question, is where exactly the bug lies.

No it's not intended to be this opaque.

I only know because it was on the forefront of my mind due to working on it recently.

It probably needs to be documented better, but it makes sense from the implementation point of view, we have an option to limit the amount of entities tested within an aabb, getNearbyEntities uses an AABB to do the testing as it's more performant.

I think where we really let it down, is that the limit kicks in before the filtering of potential entity types, or the fact we even leak it to the API without docs. This is probably causing unknown issues with mods as well, due to how opaque it is. I've recently boosted the default to 24 (which is yet to be PR'd) to match the minimum for Minimum for Mojang's mob cramming rule.
