### ISSUE TITLE
CommandBlock CommandSource

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/Sponge#161]
Currently TileEntityCommandBlock$1 which is the class implementing ICommandSender and is the actual object passed to the command handlers doesn't implement sponge's CommandSource which causes the server to crash whenever a commandblock is activated. However the fix is not quite as simple as it may seem at first glance. There are three requirements for a correct solution in descending importance (only the first is absolutely required):

- **CommandSource**: The object passed to the internal command handler must implement CommandSource in order to stop the crash from occurring.
- **instanceof**: The class passed to the command handler should also implement CommandBlock in order to allow an instanceof check in a plugin's CommandCallable to see if the command is originating from a command block.
- **equals**: The class passed to the command handler should be the actual instance of the command block, to allow an equals check against a specific tile entity in a plugin's CommandCallable.

There are three possible solutions that I currently see.

**Solution A: Inner class implements CommandSource**
This is the simplest solution and does stop the crash from occurring. However this does not solve the instanceof or equals requirements. No other immediate drawbacks that I can see.

**Solution B: Inner class implements CommandBlock**
By implementing commandblock you are implicitly implementing CommandSource thus solving the first issue. You are also solving the instanceof requirement as the source passed to a plugin's CommandCallable will be a class implementing CommandBlock. However, the object passed to the command handler will still be a different object to the actual command block tile entity sourcing the command so it does not cover the equals requirement. Additionally this is a bit of a janky solution as the inner class would have to proxy all extraneous CommandBlock methods back to the parent tile entity.

**Solution C: TileEntityCommandBlock implements ICommandSender and bypasses the inner class**
By having the actual tile entity implement ICommandSender and CommandBlock we can pass the actual object of the tile entity to the command handler thus solving all three requirements. However this is quite an invasive change as any other forge mods expecting the origin of the commands from the commandblock to be the inner class will fail.

An alternative would be if it was possible to send one object to the minecraft/forge command handler (the inner class) and another to the sponge command handler (the tile entity). However I'm not sure of the feasibility of this within the current system.

As you can see there is no perfect solution so any input would be appreciated.

**Comment by Kobata** [comment]
Option D:
CommandBlockLogic is the actual class implementing ICommandSender for command blocks, make this implement a new 'CommandBlockSource' API interface.

This would cover both TECommandBlock and EntityMinecartCommandBlock, and would have a better chance of catching mods adding alternate command blocks (assuming they use the same logic class as a base)

**Comment by Deamon5550** [comment]
Disregard this *whistles and walks away*
