### ISSUE TITLE
ItemDropEvent.Dispense isn't called for dispensers

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Sponge#1623]
**I am currently running...**
- SpongeVanilla version: 4566f6122f7d19c7aa0c7ceb8e3019986d431694 (Commit hash, built from source)
- Java version: 1.8.0_151
- Operating System: Windows 10 64 Bit 16299
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows
- Plugins/Mods: 

**What is the expected result?**
The event gets called

**What is the current result?**
The event doesn't get called

In DispensePhaseState, 

```
            phaseContext.getCapturedItemsSupplier()
                    .acceptAndClearIfNotEmpty(items -> {
```
This segment of code is returning a supplier with captured=null. It appears the EntityItem is being captured by the entity capture rather than the item capture.

**Comment by me4502** [comment]
So just realised there's a larger dispenser-related issue.

Dispensers don't only dispense items. It'd make sense to have an event that's called when dispensers are activated, so that all of their actions can be overridden/cancelled.

**Comment by parlough** [comment]
I believe their other actions should be able to be handled in other ways already, but an extra event that occurs before hand may not hurt to group them all together. 

For example a lot is handled by `SpawnTypes.DISPENSE` and changing the block to water should be handled by having the dispenser in cause/context. This may not all be implemented though, but that is another issue.

**Comment by me4502** [comment]
Fair enough then. I can't think of anything those two cases wouldn't cover.
