### ISSUE TITLE
remove unused config options

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Sponge#1626]
Review of the code revealed the configuration option:

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/config/category/GeneralCategory.java#L33

Is not actually implemented anywhere in the rest of common or within SF.

**Comment by phit** [comment]
Trying to figure out if it was ever used, 2 config refactors earlier it was already there https://github.com/SpongePowered/SpongeCommon/commit/83b2bf765a85829290e07e09397ef6c5bc8a72ad#diff-159a931fa5efcd9155ae5182cb14456bR363

**Comment by Dockter** [comment]
Ideally it could be used to turn off the annoying warning within MinecraftServer.java at line 544, "can't keep up! Did the system time change, or is the server overloaded?"

I'm working on trying to do a mixin to target that.

**Comment by phit** [comment]
so I cloned https://github.com/SpongePowered/SpongeVanilla/commit/2802b4378b2d91f40db8d183cb63ab4b9ab64e44 recursively and ran a search on all files and even back then nothing used this option

**Comment by ryantheleach** [comment]
Nothing in SpongeForge uses it either.
https://github.com/SpongePowered/SpongeCommon/commit/5afad37c96b825b9db7eb06cba52a02b4a856bea

**Comment by phit** [comment]
`infinite-water-source` seems to be dead aswell
