### ISSUE TITLE
Pre-Generation Error's 

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/Sponge#1631]
**I am currently running...**

- SpongeForge version: 1.12.2-2529-7.0.0-BETA-2748
- SpongeVanilla version: 
- Java version:  8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
i just had Nucleus plugin 
**What is the expected result?**
that error was repeatedly showing in console to the point where it got to the log got 11GB
size of the logs i managed to found that error and i don't know what do to
i let 1 one my beta testing player to play and warned him that it's going to lag
i figure it will be fine if 1 player plays
the the first Error shows that the 1) error log
then i didn't let any players on the server
and the error 2) show again as you can see it's not nucleus issue 
cause it showing nothing but as i was reading only thing i can see an issue is 
this
`Source: ASM: com.rwtema.extrautils2.items.DemonicIngotHandler@4b72c1de run(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V`

i am not too sure what is happening i am no experience developer but when this happen the pregeneration just stopped and does not do anything
1) https://pastebin.com/C1t780wb
2) https://pastebin.com/RtCBNav1

**What is the current result?**
when the error starts stop pre-generation

**Comment by gabizou** [comment]
This should be fixed in the latest builds (2751 or 2752), though 2753 (which is currently building) will have another fix for another issue. Please re-test with at least 2751.

**Comment by JoeSGT** [comment]
I am in the process of doing it
I had Deleted My Region folder
and pre-generating the end world again
I am now on SpongeForge 1.12.2-2529-7.0.0-BETA-2753
and i have updated Forge to 1.12.2-14.23.1.2559
i will let you know when the pre-generation is done
or if the error occurs again

**Comment by JoeSGT** [comment]
it seem it's fix Pre-generation is completed without any errors thanks
