### ISSUE TITLE
Utilizing Sponge Scheduler without being a SpongePlugin.

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Sponge#1633]
Hello,

I have a mod that I have made depend on SpongeAPI so that I may utilize the permissions system.  I would also like to utilize the scheduler but I have found that the builder .submit requires a plugin object.

Since this mod isn't a true spongeplugin and is simply just depending on SpongeAPI for some of its feature set is there a way I can utilize the scheduler system without making it a full sponge plugin?

**Comment by Dockter** [comment]
Apparently simply passing in the mod instance works here,  TY Meronat.

**Comment by liach** [comment]
Yeah. Apparently, sponge plugins are just forge mods in SpongeForge.
