### ISSUE TITLE
DataManipulator exceptions

### ISSUE THREAD

**Issue by Valandur** [SpongePowered/Sponge#1637]
As mentioned to @Meronat on Discord there are a few unexpected exceptions that are thrown by DataManipulators. These errors were tested on chickens and sheep, but probably apply more generally to most entities.

## entity.supports
```
java.lang.IllegalStateException: A DataManipulatorBuilder is not registered for the manipulator class: <DataManipulatorClass>
at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
at net.minecraft.entity.Entity.supports(SourceFile:2719)
```
This error is thrown by following classes when calling `entity.supports(<DataManipulatorClass>)`:

- [x] org.spongepowered.api.data.manipulator.mutable.entity.DominantHandData
- [ ] org.spongepowered.api.data.manipulator.mutable.entity.DamagingData
- [x] org.spongepowered.api.data.manipulator.mutable.entity.DamageableData
- [ ] org.spongepowered.api.data.manipulator.mutable.entity.LeashData
- [ ] org.spongepowered.api.data.manipulator.mutable.entity.ShatteringData
- [ ] org.spongepowered.api.data.manipulator.mutable.entity.SleepingData
- [ ] org.spongepowered.api.data.manipulator.mutable.block.FilledData
- [ ] org.spongepowered.api.data.manipulator.mutable.block.FluidLevelData
- [ ] org.spongepowered.api.data.manipulator.mutable.block.LogAxisData
- [x] org.spongepowered.api.data.manipulator.mutable.block.WireAttachmentData
- [ ] org.spongepowered.api.data.manipulator.mutable.item.InventoryItemData
- [ ] org.spongepowered.api.extra.fluid.data.manipulator.mutable.FluidTankData (**only** on SpongeVanilla)

## entity.get
```
java.lang.IllegalArgumentException: This data manipulator doesn't support the following key: Key{Value:Value<Boolean>, Query: Invisible}
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
at org.spongepowered.common.data.manipulator.mutable.common.AbstractData.set(AbstractData.java:186)
at org.spongepowered.common.data.processor.common.AbstractMultiDataSingleTargetProcessor.from(AbstractMultiDataSingleTargetProcessor.java:78)
at org.spongepowered.common.data.util.DataProcessorDelegate.from(DataProcessorDelegate.java:98)
at net.minecraft.entity.Entity.get(SourceFile:2650)
```
This error is thrown when calling `entity.get(<DataManipulatorClass>)` for the following classes:
- [x] org.spongepowered.api.data.manipulator.mutable.entity.InvisibilityData  

but a call to `entity.supports(<DataManipulatorClass>)` returns `true`
This error is also thrown when calling `item.get(<DataManipulatorClass>)` where item is of type `Item`:
- [ ] org.spongepowered.api.data.manipulator.mutable.entity.PickupDelayData
- [ ] org.spongepowered.api.data.manipulator.mutable.entity.DespawnDelayData

## data.copy
```
java.lang.IllegalArgumentException: Applicable constructor not found for class: <DataManipulatorClass>
at org.spongepowered.common.util.ReflectionUtil.findConstructor(ReflectionUtil.java:116)
at org.spongepowered.common.util.ReflectionUtil.createInstance(ReflectionUtil.java:75)
at org.spongepowered.common.data.manipulator.mutable.common.AbstractBoundedComparableData.copy(AbstractBoundedComparableData.java:68)
```
This error is thrown by following classes when calling `data.copy()` where data is of type `<DataManipulatorClass>`:

- [x] org.spongepowered.api.data.manipulator.mutable.entity.FallDistanceData
- [x] org.spongepowered.api.data.manipulator.mutable.entity.InvulnerabilityData

## Expectations
What I was assuming would happen is:
- When calling `entity.supports(...)` is that it returns `false` for any `DataManipulator`s that aren't applicable/don't make sense.
- When calling `entity.get(...)` an exception is understandable (one can use `entity.supports` first), but it might be better to just return an empty optional.
- When calling `entity.copy()` that the data would be copied.

## Confirmed with

- SpongeVanilla, 1.11.2-7.0.0-BETA-275
- SpongeForge, 1.11.2-2282-7.0.0-BETA-2376

**Comment by ryantheleach** [comment]
I believe some of the entity::supports is expected behavior because some of the Data API still remains to be implemented (#8), so I will leave off any that are marked as unimplemented in #8 

However, the following have been marked as implemented, so it is strange that they still throw an error for 

**Entity::supports**

- [ ] org.spongepowered.api.data.manipulator.mutable.block.FilledData
- [ ] org.spongepowered.api.data.manipulator.mutable.block.FluidLevelData
- [ ] org.spongepowered.api.data.manipulator.mutable.block.LogAxisData

Noting that most of these are block data, being used on entities, I suspect they arn't being implemented correctly.

**entity.get**

- [ ] org.spongepowered.api.data.manipulator.mutable.entity.InvisibilityData

**data.copy**

- [x] org.spongepowered.api.data.manipulator.mutable.entity.FallDistanceData
- [x] org.spongepowered.api.data.manipulator.mutable.entity.InvulnerabilityData

**Comment by parlough** [comment]
@Valandur Can you confirm `copy` still doesn't work on `InvulnerabilityData` in the latest builds? My changes to invulnerability, which only landed in 1.12 should have fixed it.

I also fixed copy for `FallDistanceData` in the latest builds.

**Comment by Valandur** [comment]
I can confirm that `InvulnerabilityData` works in the latest 1.12.2 build, and it does **not** work in the 1.11.2 builds, yes.

**Comment by ImMorpheus** [comment]
Updated.

I have no idea what is happening. Some of the data processors have been marked as "implemented" even if they are not.

Code to reproduce:

```
@Listener
public void onClickEntity(InteractEntityEvent.Secondary event, @Root Player player) {
    if (event.getTargetEntity().getType() == EntityTypes.SHEEP) {
        Entity sheep = event.getTargetEntity();


        sheep.supports(org.spongepowered.api.data.manipulator.mutable.entity.DominantHandData.class);
        //sheep.supports(org.spongepowered.api.data.manipulator.mutable.entity.DamagingData.class);
        sheep.supports(org.spongepowered.api.data.manipulator.mutable.entity.DamageableData.class);
        //sheep.supports(org.spongepowered.api.data.manipulator.mutable.entity.LeashData.class);
        //sheep.supports(org.spongepowered.api.data.manipulator.mutable.entity.ShatteringData.class);
        //sheep.supports(org.spongepowered.api.data.manipulator.mutable.entity.SleepingData.class);
        //sheep.supports(org.spongepowered.api.data.manipulator.mutable.block.FilledData.class);
        //sheep.supports(org.spongepowered.api.data.manipulator.mutable.block.FluidLevelData.class);
        //sheep.supports(org.spongepowered.api.data.manipulator.mutable.block.LogAxisData.class);
        sheep.supports(org.spongepowered.api.data.manipulator.mutable.block.WireAttachmentData.class);
        //sheep.supports(org.spongepowered.api.data.manipulator.mutable.item.InventoryItemData.class);
        //sheep.supports(org.spongepowered.api.extra.fluid.data.manipulator.mutable.FluidTankData.class);

        sheep.get(org.spongepowered.api.data.manipulator.mutable.entity.InvisibilityData.class);


        sheep.offer(Keys.FALL_DISTANCE, 0.5F);
        sheep.get(FallDistanceData.class).ifPresent(DataManipulator::copy);

        sheep.offer(Keys.INVULNERABILITY_TICKS, 10);
        sheep.offer(Keys.INVULNERABLE, true);
        sheep.get(InvulnerabilityData.class).ifPresent(DataManipulator::copy);


    }
    player.getWorld().getEntities().stream().filter(e -> e.getType() == EntityTypes.ITEM).findFirst()
            .ifPresent(item -> {
                //item.get(org.spongepowered.api.data.manipulator.mutable.entity.PickupDelayData.class);
                //item.get(org.spongepowered.api.data.manipulator.mutable.entity.DespawnDelayData.class);
            });

}
```
