### ISSUE TITLE
PropertyStrategy is not implemented correctly

### ISSUE THREAD

**Issue by ustc-zzzz** [SpongePowered/Sponge#1642]
Please refer to [PropertyStrategy.java](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/item/inventory/query/strategy/PropertyStrategy.java#L62). In this line (L62), it use `equals` rather than `Property#matches` for testing properties, and it will only compare property values.

For example, `inventory.query(SlotIndex.greaterThanOrEqual(9))` only matches only one slot (the 10th slot) and 11th, 12th, etc. are ignored.

The solution is very simple: change `property.equals(lensProperty)` to `property.matches(lensProperty)`. It will only affect one line so I do not want to open a pull request to fix this. Hope it could be fixed and merged into 1.10.2, 1.11.2, and 1.12.2 branches as quickly as possible.

**Comment by liach** [comment]
@ustc-zzzz You should make a pull if it fixes a bug, especially for important bugs like this one.

**Comment by ustc-zzzz** [comment]
> Please don’t submit pull request for small changes under 20 lines. Instead, join #sponge on IRC (irc.esper.net) or join #spongedev on IRC (irc.esper.net) and we’ll change it together with the other smaller changes.

<https://docs.spongepowered.org/stable/en/contributing/guidelines.html>

**Comment by liach** [comment]
Even https://github.com/SpongePowered/SpongeAPI/pull/1115 is merged, so I thought that may be the case.

**Comment by phit** [comment]
to note this down somewhere for reference, this changes the behavior of `new SlotPos`

>[11:08 PM] LX_Gaming: Don't use 'new SlotPos(x, y)' use 'SlotPos.of(x, y)'.
>[11:08 PM] Simon_Flash: It's the same.
>[11:09 PM] LX_Gaming: Someone else had the same issue yesterday. It's actually not the same, 'new SlotPos(x, y)' uses the DELGATE Operator by default when 'SlotPos.of(x, y)' uses the EQUALS Operator
