### ISSUE TITLE
DamageEntityEvent not working with armor stands

### ISSUE THREAD

**Issue by felixoi** [SpongePowered/Sponge#1644]
SpongeAPI version: stable-6
SpongeCommon version: stable-6
SpongeForge version: stable-6 

**What is the expected result?**

The `DamageEntityEvent` should be called when a `ArmorStand` is hit since it's an entity.

**What is the current result?**

The `DamageEntityEvent` isn't fired for `ArmorStand`s.

My listener code:
```java
@Listener
public void onDeath(DamageEntityEvent event, @Getter("getTargetEntity") Entity entity) {
   Felograms.getInstance().getLogger().info(entity.getType().toString());

   if(entity.getType().equals(EntityTypes.ARMOR_STAND)) {
       logger.info("You hit an armorstand");
   }
}
```

When I hit a `Slime` it's working. Output:
`[14:20:42] [Server thread/INFO] [felograms]: SpongeEntityType{id=minecraft:slime, name=slime, translation=SpongeTranslation{id=entity.Slime.name}, modid=minecraft, class=net.minecraft.entity.monster.EntitySlime}`

but with an `ArmorStand` it isn't.

**Comment by ryantheleach** [comment]
~~Are armor stands damageable in the classic sense? Or would this be a different type of interact entity event?~~

**Edit:** https://forums.spongepowered.org/t/cancel-entity-death-on-kill/21725/4

**Comment by Zidane** [comment]
Fixed awhile ago by JBYoshi.
