### ISSUE TITLE
using fallback lens (logging)

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/Sponge#1647]
**I am currently running...**

- SpongeForge version:  spongeforge-1.12.2-2555-7.0.0-BETA-2766
- SpongeVanilla version: 
- Java version: 8 
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 

**What is the expected result?**
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/tileentity/MixinTileEntityLockable.java#L122
well on that line keep randomly saying that into my console
it's really a minor thing but it's kind of annoying
can you remove it?
i really don't know how to reproduce it sorry it happen random
but this is what is said in console
`[STDOUT]: [net.minecraft.tileentity.TileEntityLockable:generateLens:1622]: using fallback lens`
**What is the current result?**
randomly spamming `using fallback lens`

**Comment by ryantheleach** [comment]
Is this without any mods or plugins? (I get you want it removed, and that it was probably left in by accident, but I'm also curious as to what tile entity was using the fallback)

**Comment by JoeSGT** [comment]
Just found out how do reproduce this bug
get an Iron Chest mod for 1.12.2
and get those new Shulker Box from Iron Chest mod
place it down and open
so each time you open it, it shows that console `using fallback lens`

**Comment by ryantheleach** [comment]
Cheers, that's expected, but the spam isn't as far as I know.

But just a heads up:

1. Thanks for taking the time to find the exact line in the mixin, it makes it a ton easier to triage things.

2. Iron chests arn't in vanilla, you failed to list the mods or provide the log in the ticket, I would have really really appreciated seeing the mods and plugins listed in the ticket.

**Comment by JoeSGT** [comment]
Sorry i usually put the mods/plugins list and or logs is that i was in a hurry and i rush it
when i had time i look into a bit more

**Comment by Faithcaio** [comment]
Removed in latest.
Was just an info for me when I was making fallbacks for TileEntity Inventories we did not mixin into directly.
