### ISSUE TITLE
[1.12.2] advancement trigger minecraft:inventory_changed does not work with sponge

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#1650]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2764
- SpongeVanilla version: 1.12.2-7.0.0-BETA-369
- Java version: 8
- Operating System:linux

**Issue Description**
Server not trigger advancement action when  minecraft:inventory_changed

Does not working on the spongevanilla and spongeforge too.
Work with mojang server, Spigot and SinglePlayer.

**Comment by Faithcaio** [comment]
caused by overwrite in `MixinEntityPlayerMP.sendSlotContents` (used for updating client crafting output with custom recipes)

Now using inject instead of overwrite.
We might not need this code in 1.13 anymore.
