### ISSUE TITLE
Block update issues

### ISSUE THREAD

**Issue by MrIngelborn** [SpongePowered/Sponge#1653]
**I am currently running**

- SpongeVanilla version: 1.12.2-7.0.0-BETA-374
- Java version: openjdk version "1.8.0_131"
- Operating System: Linux

- Plugins/Mods: Minecraft, Mod Coder Pack, SpongeAPI, SpongeVanilla, Discord Bridge, GriefPrevention, LuckPerms, Nucleus

**Issue Description**
Having issues with block updates:
- Removing a block that a torch is attached to does not break the torch
- Breaking a sugar cane does not break the sugarcanes above
- Observers don't react on updates from other observers

**Comment by cirkusapan** [comment]
On the same server as ^

**More Issues**
- Sponges does not remove water properly 
- When doors are broken half of the door remains

**Comment by Kazer-67** [comment]
**More Issues**

- Removing a block that a redstone torch is attached to does not break the redstone torch
- Removing a block that a redstone dust is attached to does not break the dust torch
- Removing a block that a rail is attached to does not break the dust rail

**Comment by Kazer-67** [comment]
More Issues

    Removing a block that a redstone torch is attached to does not break the redstone torch
    Removing a block that a redstone dust is attached to does not break the redstone dust
    Removing a block that a rail is attached to does not break the rail
    Removing a block that a repeater is attached to does not break the repeater

**Comment by Faithcaio** [comment]
@gabizou https://github.com/SpongePowered/SpongeCommon/commit/7698effc04b7fa6a28ef199a2131135bee01f14f also breaks ChangeBlockEvent cancel

**Comment by StoneLegion** [comment]
**Using Sponge Forge Version:**
spongeforge-1.12.2-2555-7.0.0-BETA-2774.jar
forge-1.12.2-14.23.1.2566-universal.jar


Also experiencing the same issue. So far gravel, sand, and other physical full blocks seem somewhat normal. But I'm finding anything that has no player collision? that should drop when say grass, sugarcane even breaking the bottom block of it, etc does not fall/break.

Example picture:
![mtapctb](https://user-images.githubusercontent.com/425853/34083817-50c6e772-e344-11e7-9221-554162dac0dc.png)
