### ISSUE TITLE
JRE 9.0.1

### ISSUE THREAD

**Issue by seema84** [SpongePowered/Sponge#1654]
**I am currently running**

- SpongeVanilla version: Build 1.12.2-7.0.0-BETA-374
- Java version: 9.0.1
- Operating System: Windows 7

message ->

Exception in thread "main" java.lang.RuntimeException: We have detected that you are JRE version 9.0.1, which is out of date!
In order to run Sponge, you **must** be running JRE version 1.8.0_20 (or above).

Previous builds of JRE version 1.8 will not work with Sponge.
This can be downloaded from Oracle: http://www.oracle.com/technetwork/java/javase/downloads/jre8/downloads-2133155.html
        at org.spongepowered.launch.JavaVersionCheckUtils.ensureJava8(JavaVersio
nCheckUtils.java:49)
        at org.spongepowered.server.launch.VersionCheckingMain.main(VersionCheck
ingMain.java:37)

version 9.0.1 is above of 1.8.0_20 but will not work :)

**Comment by mattmess1221** [comment]
>In order to run Sponge, you must be running JRE version 1.8.0_20 (or above).

Java 9 is not supported. It breaks everything.

**Comment by seema84** [comment]
I thought that too but this message its not true.

**Comment by mattmess1221** [comment]
So this message is wrong? I think I see.  Java 9 is greater than Java 1.8, but the notation changed so everything broke. Though it seems to work in our favor for now.

**Comment by seema84** [comment]
ok it was just a hint :-)

**Comment by mattmess1221** [comment]
You should modify the issue title and description to mention this.

**Comment by mattmess1221** [comment]
Also related. #1578

**Comment by seema84** [comment]
changed and yes i dont saw this issue

**Comment by kashike** [comment]
#1553
#1578
https://github.com/SpongePowered/SpongeVanilla/issues/355
