### ISSUE TITLE
Cancelled DamageEntityEvent sends success message

### ISSUE THREAD

**Issue by felixoi** [SpongePowered/Sponge#1655]
SpongeForge: `bleeding`
SpongeCommon: `bleeding`
SpongeAPI: `bleeding`

**What is the expected result?**

The entity shouldn't be killed and no message should be send to player and/or console.

**What is the current result?**

If I cancel the `DamageEntityEvent` and try to kill it with `/kill` the entity will not die but i get the success message, e.g.:

`Killed Slime` --> Player
`[felixoi: Killed Slime]` --> Console

**Comment by ryantheleach** [comment]
@felixoi Looking over the Minecraft source I don't think we should necessarily fix this, and it might fix itself or become possible to fix in 1.13 without overwriting mc commands for nearly no reason.

Was there a good reason why you needed this? Or was it just a (small) thing that didn't seem to make sense?

Plugins can always override /kill with their own command, that returns different messages.

**Comment by felixoi** [comment]
It was a small thing I regonized when cancelling the event. Nothing world-breaking.

**Comment by ryantheleach** [comment]
It's more maintenance then it's worth, could cancel message events, could make a new command with same alias
