### ISSUE TITLE
Queueing SlotTransactions taking items into the offhand

### ISSUE THREAD

**Issue by DosMike** [SpongePowered/Sponge#1657]
**I am currently running**
- SpongeForge version: n/a
- SpongeVanilla version: 1.12.2-7.0.0-BETA-374
- Java version: 1.8.0_151-b12
- Operating System: Windows 7

- Plugins/Mods: Minecraft, Mod Coder Pack, SpongeAPI, SpongeVanilla, LangSwitch, Lockette, Mikes ToolBox (used here for testing), Total Economy, VillagerShops, WarCraft MC, Web-API, Web-API API, WebBooks

**Issue Description**
Basically I noticed that switching items to the offhand does not trigger a ChangeInventoryEvent.
When swapping items between off- and main hand however the SlotTransactions queue up and get pushed with the next ChangeInventoryEvent.

Video in case it's not clear what I did   
https://www.youtube.com/watch?v=w2N6wzm8e6o

The Listener I used    
https://gist.github.com/DosMike/b9cdce0ad46d851c44cad6af00733c02

**Comment by Faithcaio** [comment]
fixed in https://github.com/SpongePowered/SpongeCommon/commit/394983ebcfe296e2cb69373311527738ca289740
