### ISSUE TITLE
GrantAchievementEvent.TargetPlayer not being fired

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/Sponge#1661]
**I am currently running**
- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2782

On latest SpongeForge for API5 (1.10.2), the GrantAchievementEvent.TargetPlayer event is not being fired. You can reproduce it with a simple listener:
```java
    @Listener
    public void onAchievement(GrantAchievementEvent.TargetPlayer event, @Root Player p) {
        System.out.println("fired!");
    }
```

**Comment by phit** [comment]
please refer to https://github.com/SpongePowered/SpongeCommon/issues/41

**Comment by Eufranio** [comment]
Well, it **was** implemented and working some time ago. What changed?

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1293#issuecomment-292800852
https://github.com/SpongePowered/SpongeAPI/pull/1434
