### ISSUE TITLE
NullPointerException: Exception ticking world

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#1662]
**I am currently running**

- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2790
- SpongeVanilla version: N/A
- Java version: 1.8.0_144
- Operating System: Linux

- Plugins/Mods:
SkyFactory 3 v3.0.15
Listed in provided pastebin.

**Issue Description**
Appears the server crashed when a player was exploring the Nether on SkyFactory 3
Crash Report: https://pastebin.com/HcKkYsYE

**Comment by Mallalei** [comment]
i have the same Problem - reading

**Comment by Zidane** [comment]
If this is an issue on 1.12 we will re-open otherwise 1.10 is no longer in support.

**Comment by qaz74107410** [comment]
I have the same problem too. Did anyone get an alternative solution?

**Comment by LXGaming** [comment]
@qaz74107410 I believe the issue is caused by this: https://github.com/SpongePowered/SpongeCommon/commit/dfc7cb62c2d9633d25640610241cfa44e9d58024

I doubt it's going to be fixed by Sponge themselves. Try downgrading to the appropriate version:

SpongeForge:
- [SpongeForge-1.11.2-2476-6.1.0-BETA-2787](https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.11.2-2476-6.1.0-BETA-2787/spongeforge-1.11.2-2476-6.1.0-BETA-2787.jar)
- [SpongeForge-1.10.2-2477-5.2.0-BETA-2788](https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.10.2-2477-5.2.0-BETA-2788/spongeforge-1.10.2-2477-5.2.0-BETA-2788.jar)

SpongeVanilla:
- [SpongeVanilla-1.11.2-6.1.0-BETA-26](https://repo.spongepowered.org/maven/org/spongepowered/spongevanilla/1.11.2-6.1.0-BETA-26/spongevanilla-1.11.2-6.1.0-BETA-26.jar)
- [SpongeVanilla-1.10.2-5.2.0-BETA-402](https://repo.spongepowered.org/maven/org/spongepowered/spongevanilla/1.10.2-5.2.0-BETA-402/spongevanilla-1.10.2-5.2.0-BETA-402.jar)
