### ISSUE TITLE
StackOverflow in GeneralPhase 1.10.2

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#1669]
**I am currently running**

- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2790
- SpongeVanilla version: N/A
- Java version: 1.8.0_144
- Operating System: Linux

- Plugins/Mods:
Project Ozone Lite v1.3.4
Listed in provided pastebin.

**Issue Description**
Crash Report: https://pastebin.com/0bGnuAJ2

**Comment by phit** [comment]
no reproduction and wrong repo, please reopen in SpongeForge when you have a reproduction
