### ISSUE TITLE
Modded Client Crashing On Server Connect

### ISSUE THREAD

**Issue by Kira076** [SpongePowered/Sponge#1675]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.1.0-BETA-2815
- SpongeVanilla version: 
- Java version: 1.8 (151)
- Operating System: Windows 10

### Problem:
When loading in to a server (hosted locally), the client (but not the server) crashes upon load-in. This does not happen when loading in to a single-player world. I've attempted a number of things to remedy this (removing a suspect plugin, upgrading spongeforge versions), and have had this happen 3 times in a row, all of them issues with rendering. (Note: I believe the first time was with an earlier build of spongeforge)

See the crash reports:
[1st Time](https://pastebin.com/Fdyu4CS5)
[2nd Time](https://pastebin.com/kay7nL7T)
[3rd Time](https://pastebin.com/8tuASi2m)

### Update:
Here's a crash log from a fresh minecraft instalation, running Forge 2555 and only spongeforge installed:
[Clean Install](https://pastebin.com/eNxnTUaP)

### Update Two:
I've went through and tested each previous spongeforge version, and the problem ceases at build 2807 of spongeforge (spongeforge-1.12.2-2555-7.0.0-BETA-2807)... 2809 and newer all have the crashing issue. As a side note, I've tried connecting both through 127.0.0.1 and my local IP, and it happens on both.

**Comment by Zidane** [comment]
Cannot reproduce on latest builds after a fix was made for this.

**Comment by ryantheleach** [comment]
There's been talks in various chats that Minecraft removed the keep alive ping unless you are in the Play status.

Mods are going to have to concentrate on not delaying this process longer then they have to.  It ends up being a problem with slow client machines.
