### ISSUE TITLE
Entites filtered in DropItemEvent.Dispense and DropItemEvent.Destruct are still removed from inventories 

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#1678]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2815
- SpongeVanilla version: 1.12.2-7.1.0-BETA-2

**What is the expected result?**
The expected result is that if an entity, such as an `itemstack` is filtered from the event using `filterEntities()`, not only should it not be dropped, but the transaction removing it from the inventory should be cancelled as well.
**What is the current result?**
Currently, the item is not dropped, however it is still removed from the inventory.

**Comment by ImMorpheus** [comment]
Related https://github.com/SpongePowered/SpongeCommon/issues/1280#issuecomment-347008090

**Comment by bloodmc** [comment]
These events are working as intended. First, an ItemStack is NOT an Entity. EntityItem's are created when an ItemStack needs to be spawned into the world which is what these events use. It is also impossible to guarantee restoration to inventory once an entityitem has spawned when you factor in mods and plugins. For all the cases we CAN guarantee it, we fire a 'DropItemEvent.Pre'.

I've been starting to add more support for 'DropItemEvent.Pre' which is what you will need to use going forward if you want to prevent removal from inventory. You can also use the inventory events.
