### ISSUE TITLE
Anvil Inventories missing Input & Output Slots

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#1685]
**I am currently running**
- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2817

**Issue Description**
What is the expected result?
`inventory.query(InputSlot.class)` on an anvil inventory should return the two input slots
`inventory.query(OutputSlot.class)` on an anvil inventory should return the one output slot

What is the current result?
Currently they both return an EmptyInventoryImpl.

**Comment by ryantheleach** [comment]
I suspect this is can't fix @Faithcaio if the rumors I've heard about the anvil container are true?

**Comment by Faithcaio** [comment]
fixed in latest API-7
