### ISSUE TITLE
1.12.2 Crash on EntityXPOrb collide

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/Sponge#1692]
**I am currently running**
- SpongeForge version: 2800
Can't update any further due to it's unstable state

Crashreport:
https://pastebin.com/B9TTtuRp

It's a watchdog crash, so ExpOrb might not be the trigger, but I am confident that this is the trigger in this case.

- Plugins/Mods:
 Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, AdminShop, ArenaPass, BungeeTabListPlus-SpongeBridge, BuyBlocks, Buycraft, ChestCommandsSponge, CommandOutput, GriefPrevention, HexRankSponge, HolographicDisplaysSponge, HuskyCrates, HuskyUI, Lottery, LuckPerms, MCClans, Marriage, NetCoins, Nucleus, PKMUtils, PT, Pixel Announcer, Pixel Auction, Pixel Shout, PixelmonImporter, PixelmonPlaceholders, PlaceholderAPI, PlayerInfoSponge, PortableInventories, ProjectCore for SpongeAPI 7.x, ProjectPortals for SpongeAPI 7.x, RandomTeleports, Rankup, ResetResourcePack, Restarter, SignEditor, SpongeColoredSigns, VirtualTool, gReqSponge, geSuitBans, geSuitChat, geSuitHomes, geSuitSpawns, geSuitTeleports, geSuitWarps 

**Issue Description**
Unexpected server crash on expOrb collide? func_70071_h_ is the update function, so he might try to update it's location, sponge checks if the orb can collide and crashes.

  Update:
This crash was caused by a player that harvested 1000+ ores with a luck pickaxe that granted exp (thousands of)orbs

**Comment by ryantheleach** [comment]
Time: 1/8/18 7:31 PM
Description: Watching Server

-- Head --
Thread: Server Watchdog

This looks like a watchdog stall. Your server timed out.

Short of potentially adding optimizations in places once we have performance graphs there's not much we can do.

**Comment by johnfriedrich** [comment]
I know. Probably GP crashed the server as it checks for every single exp orb if it can collide with all other exp orbs on the exact same place. And if there are thousands of it on the same place, it  might lead to a crash due to thousands of gp collision checks every second.
So not a sponge bug
