### ISSUE TITLE
Cancelling ChangeInventoryEvent.Pickup causes item to be destroyed

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#1693]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2825

**Issue Description**
As the title says, cancelling ChangeInventoryEvent.Pickup prevents the item from being picked up, but also destroys the item in the process

**Comment by ryantheleach** [comment]
Is a different event raised when the items destroyed?

**Comment by Zerthick** [comment]
Not as far as I can tell, the item just goes poof.  What event if any should be thrown?

**Comment by phit** [comment]
see https://github.com/SpongePowered/SpongeAPI/pull/1693

pretty sure you need to cancel `ChangeInventoryEvent.Pickup.Pre` to stop items from being destroyed

**Comment by Faithcaio** [comment]
Correct `ChangeInventoryEvent.Pickup` is fired **after** the items have been picked up and only handle the inventory change.
In the `.Pre` event you can change the items picked up or cancel it leaving the item on the ground.
