### ISSUE TITLE
FusedExplosive Methods not working

### ISSUE THREAD

**Issue by Xenmai** [SpongePowered/Sponge#1701]
Hi there. I'm running SpongeVanilla 1.12.2-7.1.0-BETA-9 and I've encountered some problems with FusedExplosive methods. [API Page](https://jd.spongepowered.org/7.0.0-SNAPSHOT/org/spongepowered/api/entity/explosive/FusedExplosive.html)

FusedExplosive#defuse() and #prime() don't error, but don't seem to do anything at all.

FusedExplosive#isPrimed() doesn't error either, but always returns false. The internal value might not be updated correctly.

I've looked at SpongeCommon FusedExplosive Interface and the code behind those methods seems to be missing.

Could you please confirm this issue, and fix it if needed? Thanks a lot for your time.

**Comment by Aaron1011** [comment]
`FusedExplosive` is implemented by several different entities. Which one are you having problems with?
