### ISSUE TITLE
Server::getAllWorldProperties() caches the world properties rather then fetches them.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1703]
Tested under: 1.12.2-7.1.0-BETA-9 

Read source in SpongeForge.

Server.getAllWorldProperties() fetches them from a cached map.

This causes you to force a restart of the server when importing a new map.

It would be good if the implementation of this method was able to see WorldProperties that had yet been undiscovered by SpongeCommon.

**Comment by dualspiral** [comment]
Lots of world stuff has been done, and really, we shouldn't be continuously checking for world properties when running `getAllWorldProperties()`. They are required to be registered to be usable.

I'm closing this - how it works now is fine.
