### ISSUE TITLE
Legacy Data failing to appear in sponge.data-registrations.failed-data-list

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1714]
**@Big-Deaddy is currently running**

- SpongeForge version: Using SF 2833
- SpongeVanilla version: Untested
- Java version: Unknown
- Operating System: Unknown

**Issue Description**
It's been reported in IRC that removing https://github.com/hsyyid/CommandSigns/tree/master/src/main/java/io/github/hsyyid/commandsigns results in spam.

![image](https://user-images.githubusercontent.com/141554/34929245-929c29c0-fa12-11e7-8706-b515c0a8bfe2.png)

But fails to populate in the failed data configuration: https://gist.github.com/Big-Deaddy/2e20c4ddded6fa8efbdfd42250162eba

It's my suspicion that this is due to the legacy data not being populated in the list, or even having a method listed in the config of the specification to list it.

**Comment by KyleFreedomSeeds** [comment]
bump. Im experiencing the same bug, The spam is so massive it lags out console and freezes the sever for around 30 seconds. Hoping for a fix :D

**Comment by gabizou** [comment]
Once the build finishes, can you try build 2892, it should very well accurately save the config as failed data is discovered.

**Comment by johnfriedrich** [comment]
This is fixed, however entries put in data-to-purge won't get purged from disk. At least is that, what I expect this option should do

**Comment by gabizou** [comment]
It should be purging the data as soon as it is loaded from chunks/entities/etc. Could you provide an example of NBT data for me to double check and test?

**Comment by dualspiral** [comment]
No response, closing.
