### ISSUE TITLE
Implementation : Boss death sound radius 

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#1717]
This issue was originally submitted by @alicheek in [SpongePowered/SpongeForge#1123](https://github.com/SpongePowered/SpongeForge/issues/1123).
___
Just a request, something that spigot is implemented and would be great to see this also implemented in sponge, its nothing major but ive had quite a few people complaining about the sounds due to other players having wither mob grinding systems and such.

dragon-death-sound-radius
Default: 0
Type: Integer
Description: Limit the sound of the dragon's death.

wither-spawn-sound-radius
Default: 0
Type: Integer
Description: Limit the sound of spawning withers.

Thanks again for the great software!

alicheek

**Comment by ryantheleach** [comment]
Moved:
I'd sooner see this implementable as a plugin, however it appears that there isn't any sound / effect events.

https://github.com/SpongePowered/SpongeAPI/issues/1562

Any plugin that attempted to do this without events, would need to use Mixins themselves.

**Comment by parlough** [comment]
Thanks for the suggestions, but for now, I think this will be better implemented as a plugin, which should now be possible with the introduction of this API PR https://github.com/SpongePowered/SpongeAPI/pull/2028 and its corresponding implementation. If anyone feels strongly about including this in Sponge directly, feel free to respond to this issue or make a new one. If you need help implementing the plugin or come across issues, let us know on our Discord or on the forums!
