### ISSUE TITLE
Bed repawning doesn't work correctly

### ISSUE THREAD

**Issue by kherock** [SpongePowered/Sponge#1719]
**I am currently running**

- SpongeForge version: all latest versions
  - 1.12.2-2555-8.0.0-BETA-2841
  - 1.12.2-2555-7.1.0-BETA-2842
  - 1.11.2-2282-7.0.0-BETA-2376
  - 1.11.2-2476-6.1.0-BETA-2792
- SpongeVanilla version:
  - all versions equivalent to the above
- Java version: 8
- Operating System: Windows/Linux

- Plugins/Mods:
None

**Issue Description**

Currently if a player dies and repawns at their stored spawn point (set via sleeping on a bed), it gets reset to the server spawn after respawning at their bed once. I've checked the playerdata files and their spawn point coordinates are simply gone after respawning.

It consistently does it every time when the player dies in another dimension or returns home via End portal. I can't recall if it's ever happened after dying in the overworld. So, easy way to reproduce:
1. Set spawn point via bed
2. Navigate to another dimension (either Nether or The End)
3. Die via `/kill` (or take the End Portal back to the overworld)
4. Die via `/kill` again and the player will incorrectly respawn at the server spawn.

**Comment by phit** [comment]
edit the versions properly latest is useless as it changes all the time..

**Comment by kherock** [comment]
I updated with some version numbers and some important details I forgot to mention!

**Comment by ryantheleach** [comment]
I'm able to reproduce this by following the steps.

**Comment by XakepSDK** [comment]
Old player location isn't copied to new player after dying in another dim.

**Comment by bloodmc** [comment]
Fixed in commits

https://github.com/SpongePowered/SpongeCommon/commit/65d1ec286c41b0b2259ac1e986c06dc679d626df
https://github.com/SpongePowered/SpongeCommon/commit/d7871a0f08dd4ac1790057d2868d20a62844ba93
https://github.com/SpongePowered/SpongeCommon/commit/588fae261e29f1a0a895f4c992862f63ff5c7649
