### ISSUE TITLE
Location Serialization saves BlockType?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1720]
```
    @Override
    public DataContainer toContainer() {
        final DataContainer container = DataContainer.createNew();
        container.set(Queries.CONTENT_VERSION, getContentVersion());
        if (getExtent() instanceof World) {
            container.set(Queries.WORLD_NAME, ((World) getExtent()).getName());
            container.set(Queries.WORLD_ID, getExtent().getUniqueId().toString());
        } else if (getExtent() instanceof Chunk) {
            container.set(Queries.CHUNK_X, ((Chunk) getExtent()).getPosition().getX())
                .set(Queries.CHUNK_Y, ((Chunk) getExtent()).getPosition().getY())
                .set(Queries.CHUNK_Z, ((Chunk) getExtent()).getPosition().getZ())
                .set(Queries.WORLD_NAME, ((Chunk) getExtent()).getWorld().getName())
                .set(Queries.WORLD_ID, ((Chunk) getExtent()).getWorld().getUniqueId().toString());
        }
        container.set(Queries.BLOCK_TYPE, this.getExtent().getBlockType(getBlockPosition()).getId())
            .set(Queries.POSITION_X, this.getX())
            .set(Queries.POSITION_Y, this.getY())
            .set(Queries.POSITION_Z, this.getZ());
        return container;
    }

```

The current Location classes serialization is interesting.

Location<x> seems to have somewhat of a crisis of identity, It more closely represents a BlockLocation rather then a (floating) location inside a world or extent, personally I think it could be due for a rename.

Anyway, the current serialization above, only serializes a reference to an extend if it's a world or chunk, as extent has no id to speak of...

And at the end it falls back to serializing the Position XYZ of the block, as well as the BlockType.

I feel like, at minimum, the BlockType needs to be removed?

It makes sense to me to treat a Location like a Unit Extent except for when it comes to the serialization, In this case it just makes no sense, we already have ways of saving out extents as schematics, or saving worlds, and it doesn't suit the naming.

I see it as an access object / lens to an extent, and serializing it shouldn't serialize the contents of the extent, it should be serializing the lens itself.

If it were possible to get an ID from an extent, and serialize that as well as it's name I'd advocate that as well, but that will involve API changes.

e.g.

A Location<E> Would be serialized as a GridLocation X,Y,Z with a serialized identifier/reference of it's extent, defined by the extent.

World extends Extent would output the world name and world ID for this reference.
Chunk extends Extent would output the reference to it's container (World usually) as well as a Chunk X and Chunk Z.
Arena extends Extent would output the registered name of the arena as it's extent id / reference. e.g. MyArenas:DeathArena2

**Comment by gabizou** [comment]
It’s one of those early implementations that I had to write for serialization. In all honesty, we may not even need to expose the location Object as a class at somepoint. Removing the block if wouldn’t be bad, just bump the content version and have it hard fail if the extent isn’t identifiable as a world or chunk. Personally if people are using location outside an extent perspective for an extent that isn’t persisting, might as well use Vector3i

**Comment by randombyte-developer** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/2109#issuecomment-425076609

Linking that since that issue was closed in favor of this issue.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/commit/b6e56252f976bd47fbc4a9e82a660a36a0e29cb8
