### ISSUE TITLE
Can not cancel dropping item from inventory on pressing `Q` (ClickInventoryEvent.Drop.Single)

### ISSUE THREAD

**Issue by realGWM** [SpongePowered/Sponge#1722]
**I am currently running**
- SpongeForge version: no forge
- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-11.jar
- Java version: 1.8.0_144
- Operating System: Linux

- Plugins/Mods:
inventory_bug

**Issue Description**
`ClickInventoryEvent.Drop.Single` can not be cancelled (`ClickInventoryEvent.NumberPress`, `ClickInventoryEvent.Secondary`, `ClickInventoryEvent.Primary` can be cancelled fine).

https://www.youtube.com/watch?v=2YuBt6pRmGc (Sorry, I forget to disable sounds there)

```Java
@Plugin(id = "inventory_bug", name = "Inventory Bug", version = "1.0")
public class InventoryBug {

    @Listener
    public void onClickInventoryEvent(ClickInventoryEvent event) {
        Container container = event.getTargetInventory();
        if (container.getName().get().equals("inv_bug_test")) {
            event.setCancelled(true);
            System.out.println("Cancelled event \"" + event.getClass().getSimpleName() + "\"!");
        }
    }
}
```

**Comment by ryantheleach** [comment]
From your conversation in discord and the video, it sounds like it is being cancelled, since the item isn't dropping, it's just not retaining the item / sending the update to the client?

**Comment by realGWM** [comment]
Yeah, I think so
