### ISSUE TITLE
Tab completion with fallbacks

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1725]
@simonflash @ewoutvans

**I am currently running**

- SpongeForge version: ?
- SpongeVanilla version: 
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-dfc5c4a7
    SpongeVanilla: 1.12.2-7.1.0-BETA-11

Plugins (7): Minecraft, Mod Coder Pack, SpongeAPI, SpongeVanilla, Auction, EconomyLite, Skygrid

**Issue Description**

@ewoutvans on Discord:
> Okay so I made a command with child commands
![image](https://user-images.githubusercontent.com/141554/35252468-90dcd4d0-0030-11e8-9b5a-259a30bf8834.png)

> but for some reason I need to place 2 spaces before the tabcompletion is triggering
> Here is the code i'm using to register the command

Test Code: https://gist.github.com/Ewoutvans/713fd52b3722539d5eb39338c3e33b1d

> Any idea how to fix?

**Comment by Ewoutvans** [comment]
Version stuff: SpongeVanilla
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-dfc5c4a7
    SpongeVanilla: 1.12.2-7.1.0-BETA-11

And:
Plugins (7): Minecraft, Mod Coder Pack, SpongeAPI, SpongeVanilla, Auction, EconomyLite, Skygrid

**Comment by Ewoutvans** [comment]
Short video of the tab completion problem
https://youtu.be/tYGLQrFmBek

**Comment by Ewoutvans** [comment]
Did some testing and this issue only appears when you don't have a `.executor` on the base command (auctionCmd in my case)
