### ISSUE TITLE
DestructEntityEvent.Death death player is second in cause

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1729]
```
[21:30:13 ERROR] [Sponge]: Could not pass DestructEntityEvent$Death$Impl to Plugin{id=simplescavenger, name=Simple Scavenger, version=1.0, description=Keeps inventory for players with permission, url=https://spongeapi.com, authors=[Xakep_SDK], source=mods/simplescavenger-1.0-SNAPSHOT.jar}
java.lang.ClassCastException: net.minecraft.util.DamageSource cannot be cast to org.spongepowered.api.entity.living.player.Player
```
Is this ok?

**Comment by ImMorpheus** [comment]
full stacktrace ?

**Comment by XakepSDK** [comment]
It's just ClassCastException, because `event.getCause().root()` returned `DamageSource` instance, not a `Player`, because dead player is second in context.
https://gist.github.com/XakepSDK/d34b0eb509b7420abbd55dbe02997784

**Comment by dualspiral** [comment]
If you want the dead player, you want to check the `Living` from `getTargetEntity()` instead. The `DamageSource` is correctly identified as the root _cause_ of the death - you don't want the cause, you want the _target_. The dead player may not even be the cause of the death at all, in which case, you wouldn't expect it.

So yes, this is working as expected. You want the target from `getTargetEntity()`.
