### ISSUE TITLE
Phase exception during MoveEntityEvent.Teleport if closing a player's inventory while holding item in cursor

### ISSUE THREAD

**Issue by VapidLinus** [SpongePowered/Sponge#1744]
If during a `MoveEntityEvent.Teleport` event, a player is holding an item on their cursor and `player.closeInventory()` is called, a phase exception is thrown.

**Sample code to reproduce issue:**
```java
@Listener
public void onTest(MessageChannelEvent.Chat event, @Root Player player) {
	// When player writes "!test" in chat
	if (!event.getRawMessage().toPlain().equalsIgnoreCase("!test")) return;

	Inventory inventory = Inventory.builder()
			.of(InventoryArchetypes.CHEST)
			.build(plugin);

	// Put a diamond in the inventory
	inventory.offer(ItemStack.of(ItemTypes.DIAMOND, 1));

	player.openInventory(inventory);

	// Few seconds later, teleport the player to trigger the teleport event
	Task.builder()
			.delayTicks(20 * 3)
			.execute(() -> player.setLocation(player.getLocation().add(0, 2, 0)))
			.submit(plugin);
}

@Listener
public void onPlayerTeleport(MoveEntityEvent.Teleport event, @Getter("getTargetEntity") Player player) {
        // Close the inventory to trigger the phase exception
	player.closeInventory();
}
```

**Reproduce instructions:**
1. Write !test in chat
2. Quickly click on the diamond to put it on your cursor
3. After 3 seconds you will be teleported into the air and your inventory will close.
4. Diamond will disapear and an exception is thrown

**Exception log:**
https://gist.github.com/VapidLinus/d4a4226444874b1c49a18f6b3e2468d9

> spongevanilla-1.12.2-8.0.0-BETA-393

**Comment by ryantheleach** [comment]
@VapidLinus Just wondering, are you using bleeding/experimental builds for the sake of testing? Whilst we appreciate the bug report, I'm mildly worried about people who are running bleeding/experimental in production, so figured I'd give this obligatory warning that it's a bad idea.

**Comment by RedNesto** [comment]
This is also a thing on `spongevanilla-1.12.2-7.1.0-BETA-14`

**Comment by VapidLinus** [comment]
@ryantheleach Just for testing! My plugin/server has a *long* way to go before it goes public, so I figured I might as well be on bleeding so I am ready to adapt to new API changes as soon as possible until I'm getting closer to release.

**Comment by RedNesto** [comment]
I looked at the issue and now no more exceptions Phase-wise, but no items dropped :3

**Comment by VapidLinus** [comment]
@RedNesto Awesome! 🎉

I wasn't sure if no items being dropped was this issue or a separate one. I noticed but haven't confirmed that `player.closeInventory()` always just makes the cursor item disappear even outside of this case.

**Comment by RedNesto** [comment]
@VapidLinus Were you in creative mode while having the item drop issue, because after talking with Faithcaio we found that the creative mode does not drops the item at cursor, but survival works fine.

**Comment by VapidLinus** [comment]
@RedNesto Nope, I tested everything in survival mode. I will try to create reproduction steps tomorrow!

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/7796f59c6671ba4d34e1273a5438c7049274e1c0

**Comment by VapidLinus** [comment]
@RedNesto After doing some tests I've come to the conclusion that I was wrong about items not dropping _(in other cases; in this issue the item wasn't being dropped but that is now fixed)_. I was just not considering that the item is dropped before the player gets teleported, so the item gets dropped where the player was before the teleport :)
