### ISSUE TITLE
No event is fired when breaking blocks indirectly (in some cases)

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/Sponge#1746]
**I am currently running**

- SpongeForge version: Bleeding branch (https://github.com/SpongePowered/SpongeForge/commit/29fd16f5fcafb25e392896ed70b4de7efb9a1d30 commit)
- SpongeVanilla version: untested
- Java version: 
- Operating System:

- Plugins/Mods: none

**Issue Description**
As of now I've found two way to reproduce this: 

- Place a cactus (at least two blocks)
- Place a piston two blocks away from it.
- Activate the piston with a level
- The piston should touch the cactus and the cactus block (touched by the piston) should break, dropping on the ground.
- No BlockChangeEvent.Break is fired.

____________________
- Place a block
- Put a lever on it
- Move that block with a piston
- The lever is broken.
- No BlockChangeEvent.Break is fired.

```
    @Listener
    public void onSpawn(ChangeBlockEvent.Break event) {
        System.out.println(event.getCause());
    }
```

**Comment by ryantheleach** [comment]
Thanks for the report, Are any other BlockChangeEvents fired, even if you were expecting Breaks?

**Comment by ImMorpheus** [comment]
No. If you listen to the parent event you can see the ChangeBlockEvent.Modify (because you activated the lever) and the ChangeBlockEvent.Place (because you're moving a block with a piston) and then the ChangeBlockEvent.Post which should contain all the block changes (but it doesn't contain the lever), but there's nothing related to the block which is breaking.

**Comment by bloodmc** [comment]
Pistons are a special case that use 'ChangeBlockEvent.Pre' for all locations that will be affected during a move. This is done for performance reasons and to avoid issues with trying to rollback partial moves.

Use the following event contexts to determine direction of move https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/cause/EventContextKeys.java#L78-L80
