### ISSUE TITLE
Static field EMPTY not being initialized in developer environment (SF2868)+

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Sponge#1748]
- SpongeForge version:  2868
- Forge version: 2607

In developer environment:

https://gist.github.com/Dockter/a736883e4a3315f91446fe138d89efed

**Comment by kashike** [comment]
@Cybermaxke

**Comment by Zidane** [comment]
I have pushed a fix for this to bleeding. @Cybermaxke look it over and let me know if there should be more changes.

**Comment by Dockter** [comment]
Update to this issue:  Now stands as: https://gist.github.com/Dockter/061971a8657fa9810ee692333a762e67

**Comment by gabizou** [comment]
While this happens only in development environment, does it happen AT ALL in production?

**Comment by Dockter** [comment]
@gabizou, no, its not happening in production.  @Zidane has been able to replicate in his environment so it is reproducible.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/07d6b38c255a01c6b5a2098ac2369282804c1951

@Cybermaxke this code breaks the client - Bootstrap is **way** before Sponge has been initialised.

**Comment by Zidane** [comment]
@Cybermaxke @gabizou 

No one ever ran the client in the IDE with the changes above? This kind of change should have NEVER been merged without doing that. This needs to be fixed like 5 days ago...........

**Comment by Zidane** [comment]
Update: Inconclusive to this being a mod compat issue with Almura + MalisisCore and Sponge. Still investigating..
