### ISSUE TITLE
Unable to find InventoryPacketState Handler

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#1750]
**Tested on the following:**
- SpongeForge-1.12.2-2555-7.1.0-BETA-2840
- SpongeForge-1.12.2-2586-7.1.0-BETA-2873
- SpongeVanilla-1.12.2-7.1.0-BETA-15

**Issue Description**
Middle clicking outside of any inventory (excluding Creative) causes the following warning in console:
`[Server thread/WARN] [Sponge]: Unable to find InventoryPacketState handler for click window packet: CPacketClickWindow{windowId=1, slotId=-999, usedButton=2, actionNumber=2, clickedItem=1xtile.air@0, mode=CLONE}`

Possibly related to #1434 (Although I have not experienced items disappearing)

**Comment by ryantheleach** [comment]
@LXGaming I know you didn't expect the warning, but was there some game play element that you were expecting to happen when you middle clicked outside the window?

**Comment by LXGaming** [comment]
@ryantheleach Nope.

I don't believe Minecraft performs any action when middle clicking outside of the window.
