### ISSUE TITLE
PhaseStack.pop NoSuchElementException

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/Sponge#1767]
**I am currently running**
- SpongeForge version: 2867

https://pastebin.com/HBLrRuzb

**Issue Description**

Happened randomly. Because Forge fucked up the log rotation, the important junk log got overwritten by the restart. If this should happen again, I will try to get the junk log before restarting.

**Comment by bloodmc** [comment]
This code has been completely changed in latest SF builds. Create a new ticket if something similar occurs.
