### ISSUE TITLE
WorldArchetypeBuilder default value for "keepSpawnLoaded" is null, which throws an error when building without setting it

### ISSUE THREAD

**Issue by Valandur** [SpongePowered/Sponge#1774]
https://github.com/SpongePowered/SpongeCommon/blob/06e5830fb0b26090d530357634cbf2b62e745c05/src/main/java/org/spongepowered/common/world/SpongeWorldArchetypeBuilder.java#L294

This line sets the default value to `null`. If the `keepSpawnLoaded` value is not set through the builder, it stays null when calling "build" and throws a null pointer exception.
Should this be set to either `false` or `true`?

**Comment by ryantheleach** [comment]
@Valandur I'm going to assume this is a 1.12 bug unless corrected for the sake of labelling.

But I'm sure that the developers who are going to need to investigate this will appreciate knowing whether you tested this in SF,SV,Both as well as the versions tested in, as well as your method of creating the builder. It truly does save a lot of time when we have several issues to look at.

**Comment by Valandur** [comment]
My apologies, I was in a rush when I reported this. Yes this affects 1.12.2.

I discovered this on SpongeVanilla 1.12.2-7.1.0-BETA-16, but since the error originates in SpongeCommon it probably also happens in SpongeForge, I may be able to confirm this later during the day.

The code used to generate the error is as follows:
```java
WorldArchetype.Builder builder = WorldArchetype.builder();
WorldArchetype archType = builder.enabled(true).build("archTypeName", "archTypeName");
WorldProperties props = Sponge.getServer().createWorldProperties("New World", archType);
```

**Comment by ryantheleach** [comment]
@Valandur All good! I'm happy for things to get recorded when people are in a rush, rather then being completely forgotten about! I've certainly done both in the past. Thanks for adding the additional information 😄

**Comment by ImMorpheus** [comment]
> WorldArchetype.Builder builder = WorldArchetype.builder();
> WorldArchetype archType = builder.enabled(true).build("archTypeName", "archTypeName");
> WorldProperties props = Sponge.getServer().createWorldProperties("New World", archType);

Code is working fine.
Not able to reproduce on SF with SC updated to https://github.com/SpongePowered/SpongeCommon/commit/8e159170290c6d26bd477c5cf78bd205f2493825
