### ISSUE TITLE
As a user I'd like to see the plugins listed in the crash log.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#1777]
Forge already lists mods, api's and core mods in the minecraft crash log.

Could/Should we add a plugin section to say what plugins were enabled?

**Comment by kashike** [comment]
Plugins are included in the mod list on Forge - this would be an addition into SV.

**Comment by gabizou** [comment]
The better question is whether it should be included in the ever increasingly rare exceptions printed from the phasetracker?

**Comment by stephan-gh** [comment]
SV already includes the plugins in the crash log.

**Comment by ryantheleach** [comment]
The problem with saying "They are already in the mods list" is that they are intertwined with mods. Having them separate would make them easier to read.

**Comment by Zidane** [comment]
~move to sf

**Comment by limbo-app** [comment]
Hey @ryantheleach! I've moved your issue to [SpongePowered/SpongeForge#2811](https://github.com/SpongePowered/SpongeForge/issues/2811).
