### ISSUE TITLE
InteractBlockEvent is not giving exact interaction point when using getInteractionPoint()

### ISSUE THREAD

**Issue by jd1378** [SpongePowered/Sponge#1778]
**I am currently running**

- SpongeVanilla version: 1.12.2-7.1.0-BETA-16
- Java version: 1.8.0_152
- Operating System: Win 10 Home 64-bit

- Plugins/Mods: PacketGate

**Issue Description**

The exact interaction point is available on the InteractItemEvent, but not on InteractBlockEvent, and the protocol says the interaction should be available on Player Block Placement too.

**Comment by ImMorpheus** [comment]
PR merged. This can be closed.
