### ISSUE TITLE
Cannot Run 'gradle setupDecompWorkspace --refresh-dependencies' Build Fails

### ISSUE THREAD

**Issue by GizmoCodes** [SpongePowered/Sponge#178]
I am trying to use sponge to see how it works, and it seems the build fails when I try to decompile it. I have installed gradle and everything correctly, but it still fails. It appears to be at line 255 of the build.gradle file, but opening in Notepad just scrambles the lines to where I can't tell where a line starts and where one ends. This is the command prompt output:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\GizmoCodes\Desktop\Sponge Plugin\build.gradle' line: 255

* What went wrong:
A problem occurred evaluating root project 'Sponge'.
> Could not find property 'javadoc' on task set.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.334 secs

**Comment by gratimax** [comment]
See #171.
