### ISSUE TITLE
CraftItemEvent.Craft returns wrong crafted item for some recipies

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/Sponge#1785]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2586-7.1.0-BETA-2890
- SpongeVanilla version: 
- Java version: 1.8
- Operating System: Win10

- Plugins/Mods: 
```
Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, mercurius_updater
```

**Issue Description**

Open workbench, place in recipe for workbench / bucket.
Have event listening for CraftItemEvent.Craft, print the item type of getCrafted()
Seems to return wooden buttons for workbenchs, and iron nuggets for buckets.
Im guessing its grabing the next 'preview' stack when clearing down the item grid, similar to the preview event being fired twice when an item is crafted.

```
    @Listener
    public void onCrafted(CraftItemEvent.Craft event, @First Player player) {
        System.out.println(event.getCrafted().getType().getName());
    }
```

**Comment by Zidane** [comment]
@Faithcaio You are up.

**Comment by Faithcaio** [comment]
fixed in https://github.com/SpongePowered/SpongeCommon/commit/0f02dfa05542c0662e8cf7d776073e095b8c935e
