### ISSUE TITLE
sapplings not spawning due to leaf decay when harvesting all wood from tree.

### ISSUE THREAD

**Issue by Flashkid669** [SpongePowered/Sponge#1788]
- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-16
- Java version:  1.8.0 
- Operating System: windows 10 and fedora 11
- Plugins/Mods:
Tested with no mods installed

sapplings of all the tree types will not spawn due to leaf decay tracked it back last time it worked was in sponge verson BETA-3 .

**Comment by RedNesto** [comment]
I think I know where it comes from. I'll fix it after another issue.

**Comment by RedNesto** [comment]
The fix has been merged, I think this issue can be closed.

**Comment by colinrgodsey** [comment]
seeing this in 1.12.2-2611-7.1.0-BETA-2927. I forget the last version that worked, but it was probably the stable-7 from about 3-4 weeks ago.
