### ISSUE TITLE
Permission Denied during 'git clone git@github.com:SpongePowered/Sponge.git'

### ISSUE THREAD

**Issue by GizmoCodes** [SpongePowered/Sponge#179]
Trying to do git clone git@github.com:SpongePowered/Sponge.git and got:

Cloning into 'Sponge'...
The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by gratimax** [comment]
Either [generate an ssh key](https://help.github.com/articles/generating-ssh-keys/) or clone from https://github.com/SpongePowered/Sponge. And please learn how to use git/gradle before creating useless issues on this project.
