### ISSUE TITLE
Player's health not being saved/loaded properly

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Sponge#1793]
**I am currently running**

- SpongeVanilla version: 7.1 beta 15
- Java version: 18
- Operating System: ubuntu 17

A player has health above 20 (vanilla max) after server restart player's health will become always 20, health value before restart is always ignored or lost.

**Comment by ryantheleach** [comment]
How far above? 
are you using health scaling? 
How are you manipulating the players maximum health?

We are really going to need a test plugin for this one, there could be multiple factors at play.

**Comment by NeumimTo** [comment]
My bad, i had multiple plugins running where each of them was manipulating max health/scale.. cannot reproduce with a clean env.
