### ISSUE TITLE
Item duplication on canceling ChangeBlockEvent.Break

### ISSUE THREAD

**Issue by jd1378** [SpongePowered/Sponge#1796]
**I am currently running**

- SpongeForge version: -
- SpongeVanilla version: 1.12.2-7.1.0-BETA-18
- Java version: 1.8.0_152
- Operating System: Windows 10 Home 64-bit

- Plugins/Mods: Precogs-1.2, vanish, PacketGate-0.1.1, FastAsyncWorldEdit-sponge112-18.02.09-e09c0c2-1006-19.1.1, my-own-signedit-pl (using packetGate)  , and my own ac which cancels the event   

**Issue Description**
Setup an event listener on ChangeBlockEvent.Break , and setCancelled(true), and you will get the drop when breaking the block while the block is still there .

**Comment by ryantheleach** [comment]
I can't help but think that if this were the case we would have had many people complaining about it, unless this is a very newly introduced change. So many things cancel ChangeBlockEvent.Break it isn't funny.

**Comment by GingerWalnut** [comment]
I've had this happen to me some with a custom protection plugin I am developing. However, it seems to not always happen. Just from what I've seen, this and other related oddities tend to happen more often when there is lag.

**Comment by Dockter** [comment]
Issue linked:  https://github.com/MinecraftPortCentral/GriefPrevention/issues/597

**Comment by Dockter** [comment]
Issue confirmed.

**Comment by RedNesto** [comment]
It seems I could not reproduce the issue (but I do not doubt the fact that it is really an issue).
With what blocks and which conditions can you do this ?

Edit: With the help of @jd1378 I can reproduce it, but it is in "special conditions" and is very serious.

**Comment by johnfriedrich** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1709
Same as this?

**Comment by jd1378** [comment]
when are we going to get a build to test this ?

**Comment by jd1378** [comment]
SpongeAPI: 8.0.0-SNAPSHOT-0c90e0b4
SpongeVanilla: 1.12.2-8.0.0-BETA-0 (bleeding branch)
still happening.
also now ghosting happens after a few tries ...

**Comment by Faithcaio** [comment]
Did you take the latest commits in SpongeCommon too?
The submodule was not updated for SV (it is now)

**Comment by jd1378** [comment]
The issue is fixed.
