### ISSUE TITLE
EndGateway doesn't support Keys.END_GATEWAY_AGE or Keys.END_GATEWAY_TELEPORT_COOLDOWN

### ISSUE THREAD

**Issue by VapidLinus** [SpongePowered/Sponge#1802]
Endgateways should support `Keys.END_GATEWAY_AGE` and `Keys.END_GATEWAY_TELEPORT_COOLDOWN`. But when I try to offer them to the block, nothing happens and I get a `DataTransactionResult.Type.FAILURE` back.

**Sample code to reproduce issue:**
```java
@Listener
public void onTest(MessageChannelEvent.Chat event, @Root Player player) {
	// When player writes "!test" in chat
	if (!event.getRawMessage().toPlain().equalsIgnoreCase("!test")) return;

	Location<World> location = player.getLocation().add(0, 2, 0);
	location.setBlockType(BlockTypes.END_GATEWAY);
	EndGateway gateway = (EndGateway) location.getTileEntity().get();

	logger.info(String.valueOf(gateway.supports(Keys.END_GATEWAY_AGE)));
	logger.info(String.valueOf(gateway.supports(Keys.END_GATEWAY_TELEPORT_COOLDOWN)));
	logger.info(gateway.offer(Keys.END_GATEWAY_AGE, 1L).toString());
	logger.info(gateway.offer(Keys.END_GATEWAY_TELEPORT_COOLDOWN, 1).toString());
}
```
Same issue even if the data offering is put on a 1 tick delay.

**Output:**
> false
> false
> DataTransactionResult{resultType=FAILURE, rejectedData=[], replacedData=[], successfulData=[]}
> DataTransactionResult{resultType=FAILURE, rejectedData=[], replacedData=[], successfulData=[]}

**Reproduction steps:**
1. Write !test in chat
2. End-gateway will be placed above you and the data will be offered
3. Log displays that the data wasn't applied to the new block

**EDIT:**
`Keys.EXIT_POSITION` and `Keys.EXACT_TELEPORT` are also not supported.

> **Version:** spongevanilla-1.12.2-8.0.0-BETA-394

**Comment by parlough** [comment]
The above PR should fix this, thanks for the report. Used your test locally.
