### ISSUE TITLE
Blocks also don't get dropped again when being broken by Psi Guns/Lumbe

### ISSUE THREAD

**Issue by mihionmc** [SpongePowered/Sponge#1804]
**I am currently running** FTB Direwolf20 B  FTBPresentsDirewolf20112-1.12.2-1.8.0-Server.zip

- SpongeForge version:  1.12.2-2611-7.1.0-BETA-2925
- SpongeVanilla version: 
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
- Operating System: linux 

- Plugins/Mods: Psi-r1.1-59.jar, Tinkers’ Construct Mod 1.12.2

**Issue Description**

Blocks  don't get dropped again when being broken by Psi Guns/Lumber Axes on the latest upd on direwolf. 1.12.2-2611-7.1.0-BETA-2911 is the last working version

**Comment by phit** [comment]
~move to sf

**Comment by limbo-app** [comment]
Hey @mihionmc! I've moved your issue to [SpongePowered/SpongeForge#2015](https://github.com/SpongePowered/SpongeForge/issues/2015).
