### ISSUE TITLE
Item drop problem with mods

### ISSUE THREAD

**Issue by Krosta8** [SpongePowered/Sponge#1805]
**I am currently running**

- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2925
- SpongeVanilla version: No
- Java version: 1.8.0_162
- Operating System: Windows

- Plugins/Mods:
Plugins(6): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CmdBuilder, CmdControl
Mods(26): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, BetterQuesting, CraftTweaker2, CreativeCore, IronChest, JourneyMap, JEI, LittleTiles, Malisis Advert, Malisis Doors, Malisis Core, Mantle, ModControl, MrCrayFish Furniture Mod, NetherPortalFix, Pixel Extras, Pixelmon, Tinker's Construct

**Issue Description**
Problem is with item drop. Example: In mod Pixelmon are Berries (example: pixelmon:starf_berry), if you want to collect them, you need to right click on them. Berries just disappear without any drop.
Another example with mod Tinker's Construct and Lumberaxe. When player use lumberaxe (like regular axe, but with ability to cut a whole tree) to cut a tree, tree just disappear without any drop (regular axe works).
I tried to every build from newest to oldest till working one. Last working build for this is 1.12.2-2611-7.1.0-BETA-2916.

Should be not necessary, but here is fml-junk-earlystartup.log: https://gist.github.com/Krosta8/bbf825370bf063f3878b967fa6a7ec1d

**Comment by phit** [comment]
wrong repo and a dupe, please use the spongeforge tracker for mod related issues

https://github.com/SpongePowered/SpongeForge/issues/2015
