### ISSUE TITLE
PortalAgents don't work from nether to overworld

### ISSUE THREAD

**Issue by pmbarrett314** [SpongePowered/Sponge#1807]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2925
- Java version: "1.8.0_151"
- Operating System: Debian 4.9.65-3+deb9u2 (2018-01-04)

- Plugins/Mods: Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Aliases, LuckPerms, MMCReboot, Nucleus, ProjectCore, ProjectInventories, SleepVote, Web-API, Web-API API, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, FTBLib, FTBUtilities, FoamFix, FoamFixCore, Just Enough Items, mercurius_updater

So, on my server, I have the basic set of worlds, `world`, `DIM1`, and `DIM-1`, all interconnected by portals as normal. I'd like to have a second set, we'll call them `new_world`, `new_nether`, and `new_end`, all interconnected in the same way (with the expected way to jump between sets being commands).

I've created the sets of worlds using the multiworld functionality in nucleus. I played around with the portal agent settings in the individual world config files. By setting `minecraft:default_nether` to `new_nether` in the config for `new_world` I can hop into a nether portal in `new_world` and come out in a portal in `new_nether` as expected. However, when I hop back in the same portal, it returns me to `world`, which is not ideal. As far as I can tell, there's no way to set this up as the config stands now.

As I understand it, these config options work for portals going from overworld to nether and overworld to end, but not the other way around. To this end, I think it's necessary to add a config option for a default overworld portal agent to complete this cycle.

I've played around with this a bit, and made at least nether portals work the way I expect. Java is not my first language, and I'm not completely up to speed on the project guidelines, but I'd love some input on whether what I've done is worth rolling into a PR or whether this system is already being worked on, or whether this is completely the wrong place for me to bring this up. What I've done is [here](https://github.com/pmbarrett314/SpongeCommon/commit/232d964fbbca26b3b68746990f42fc8e8924c1db). In essence, I've just added a `minecraft:default_overworld` config key in the `portal-agents` section and the backing logic to deal with that.

**Comment by Zidane** [comment]
@pmbarrett314 nice catch on this, I would entertain a PR (you've mostly got some formatting issues here and there). Let me know. Your code changes do look fine otherwise.
