### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/Sponge#1818]
https://gist.github.com/ziceptor/e305f31a4f9c0ce80ea969475021d62c

Maybe because of that. Around the same time the character is frozen in place. He's kind of in his head. In a reduced form. There he was able to spin. I could not walk.

client https://gist.github.com/ziceptor/bb27fe14d46f8b93665d1e2bcb2b3295

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar

Mods/Plugins

ActionBroadcaster.jar
ActiveTime-s7.1-v1.4.1.jar
CatClearLag-0.8.2.jar
ChangeSkin.jar
chopchop.jar
console-lock-1.1.1.jar
craftbook-sponge-S7.1-4.0-SNAPSHOT-dist.jar
denizen2core-0.4.0.jar
denizen2sponge-0.4.0.jar
DoubleJump-1.3.jar
DoubleJumpMixins-1.0.jar
EasyScoreboards.jar
EconomyLite-7.0.0-2.13.0.jar
elevator.jar
extradrop-0.1.2.jar
FileInventories-0.2.2.jar
flexiblelogin-0.16.8.jar
Gluon-1.0.4.jar
griefprevention-1.12.2-4.3.0.555.jar
InstantRespawn.jar
itemduct.jar
JumpPlates-1.1.jar
LangSwitch.jar
LibCube.jar
LuckPerms-Sponge-4.1.7.jar
MineReset-1.0.8.BETA2.jar
mobspawners-7.1.0-0.1.1.jar
mysteryblock-7.1.0-0.1.0.jar
Nucleus-1.3.1-S7.0-MC1.12.2-plugin.jar
PlaceholderAPI-4.4.jar
projectcore-7.1.0-0.2.2.jar
projectinventories-7.1.0-0.11.2.jar
projectportals-7.1.0-0.14.3.jar
RedNestosBoxOUtils-0.3.jar
TabManager-1.0.4.jar
TimTheEnchanter.jar
TitleMOTD.-.1.0.jar
VillagerShops.jar
walletdrop-7.1.0-0.3.0.jar
worldedit-sponge-6.1.9-SNAPSHOT-dist.jar

**Comment by Zidane** [comment]
```
	at com.gmail.trentech.pji.EventManager.lambda$ClientConnectionEventJoin$2(EventManager.java:167) ~[EventManager.class:?]
```

Contact Trentech and tell him to not set data off thread......
