### ISSUE TITLE
big number deserialize from json incorrect

### ISSUE THREAD

**Issue by james58899** [SpongePowered/Sponge#1821]
https://github.com/SpongePowered/SpongeCommon/blob/aadd13b935d1877d275bb4a5da0cc910f43daa9a/src/main/java/org/spongepowered/common/data/persistence/JsonDataFormat.java#L144-L159

double can't handle big numbers correctly
it will cause UUID can not correct deserialization

**Comment by james58899** [comment]
https://github.com/google/gson/issues/1084

**Comment by stephan-gh** [comment]
Can you provide specific test code (e.g. from a plugin) that is affected by this problem?

**Comment by james58899** [comment]
test plugin : https://gist.github.com/james58899/3a35bf2e5c0fa9aa37b0c7cadeb16837

Reproduce step:
1. use command get item with UUID `/give @p minecraft:stick 1 0 {AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:2,Operation:1,UUIDMost:844454052033679263L,UUIDLeast:-8130380119850524427l}]}`

2. Hold the item in your main hand

3. enter the command `/test`

4. item will serialization and deserialize to off hand

5. see console info or use command to see item NBT
UUID value was changed

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/50e3c5cd3dd9f4f0ae77ce813c032c8659ec3947
