### ISSUE TITLE
unable to write things on sign

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/Sponge#1822]
**I am currently running**

- SpongeForge version:  1.12.2-2611-7.1.0-BETA-2946
- SpongeVanilla version:  -
- Java version:  8
- Operating System: windows

- Plugins/Mods:
no mods or plugins 

**Issue Description**
I setup a clean test server with no mods or plugins i grab a sign out of creative place it down attempt to write something click done and the sign is blank on console it's outputting this 

```
 Player <MC-name> just tried to change non-editable sign
```
it seem this commit broke it 
https://github.com/SpongePowered/SpongeCommon/commit/50441219291e93c6bf274f71140ae622f7878e8a
because i was on a older version that didn't had this commit and it was working fine the version i was at `7.1.0-BETA-2944`

**Comment by gabizou** [comment]
Might need to relate a lot of tile entity code checks till the block processing as block removal was moved till after. Might be triggering it.

**Comment by JoeSGT** [comment]
Fixed on latest spongeforge :D
