### ISSUE TITLE
Forge's TileEntity timing system does not work

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#1823]
This issue was originally submitted by @SquidDev in [SpongePowered/SpongeForge#2029](https://github.com/SpongePowered/SpongeForge/issues/2029).
___
- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2940
- Forge version: 1.12.2-14.23.2.2613
- Java version: 1.8.0_151-b12
- Operating System: Windows

I've mentioned this on the discord, but felt it would probably be better to create an issue too:

Forge adds the `/forge track state te` command, which times how long each tile entity (and entity) takes to tick, reporting the slowest ones. When using SpongeForge, the command runs successfully, but running `/forge track te` (to list the result), does nothing.

The timings hook is added via [Forge's patch to `World.updateEntities`](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/world/World.java.patch#L467). As Sponge overrides this entire method, the timing code is never called.

[discord]: https://discordapp.com/channels/142425412096491520/142425412096491520?jump=416665137504714752

**Comment by gabizou** [comment]
Part of this is we need to have a SpongeImplHooks addition to allow the Forge timings in our overwrite for MixinWorld#updateEntities

**Comment by SquidDev** [comment]
Apologies! I presumed it would require patches to both, and so wasn't sure which one to post it on.

**Comment by bloodmc** [comment]
@SquidDev Why do you need forge's hook? Sponge timings does the same thing but better. Simply type `/sponge timings paste` to get a full timings report.

**Comment by SquidDev** [comment]
@bloodmc I may be wrong, but I believe they do different things? Sponge timings provides an overview of the entire world, including how long each TE class takes to tick. Forge's timings just lists the 10 slowest individual tile entities.

**Comment by gabizou** [comment]
@bloodmc it’s forges timings command that doesn’t work because we aren’t using the timings hook for Forge. It was added a couple of months ago.

**Comment by bloodmc** [comment]
OK we can add it. I don't know when I'll have time to get to it but perhaps someone else can push a fix.

**Comment by Lemmmy** [comment]
Is there any news on this issue?

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/commit/eb2df12bbda33f3d307df79d577187a906388f85

**Comment by SquidDev** [comment]
Thank you!
