### ISSUE TITLE
Scoreboard. Error after player respawn. BungeeCord

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/Sponge#1825]
**I am currently running**
- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2950
- SpongeVanilla version: 1.12.2-7.1.0-BETA-22
- Java version: 1.8.0_151
- Operating System: Ubuntu Server 16.04

- Plugins (26): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CmdCalendar, CommandSyncSponge, CommandUtils, EconomyLite, GriefPrevention, JobsLite, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, RedProtect, SkyClaims, StackBan, TabManager, UltimateChat, UniversalMarket, VirtualChest, WorldEdit

- Mods (31): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Applied Energistics 2, BD Lib, CXLibrary, CoFH Core, CoFH World, CodeChicken Lib, Ex Nihilo Creatio, Extreme Reactors, FoamFix, Giacomo's Foundry, IndustrialCraft 2, Just Enough Items, Mantle, Mod Control, More Furnaces, Parachronology, Redstone Flux, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers' Construct, Tree Chopper, Waterfree Farming, Zero CORE

I use a static Scoreboard with automatic update of values on the timer.

After respawn, when the scoreboard is updated, player is thrown from the server, and the following error appears in the BungeeCord console - https://pastebin.com/zxFYwSiT or WatreFall - https://pastebin.com/kf6UppCz

I update the scoreboard with this code. Sponge.getServer().getOnlinePlayers().forEach(this::setScoreboard);
I perform all operations in the main thread. If the Scoreboard is assigned a random name, it results in a memory leak. I could not find a way to clear or rewrite the scoreboard without calling a memory leak. The only option that helped reduce the memory leak is a multithreaded, but in this case the CPU load is too high.
[My code for the scoreboard.](https://pastebin.com/2KBA6p44)
The same problem is observed in this [plugin](https://forums.spongepowered.org/t/easy-scoreboards-v2-3/12746).

**Comment by ryantheleach** [comment]
I believe it's wrong of Sponge to be leaking memory in this instance, but why are you using a brand new scoreboard each time? Why don't you update the old/existing one instead?

This will strain the Garbage Collector for little reason.

**Comment by SawFowl** [comment]
When I try to use the previous scoreboard, I get a problem with BungeeCord. At the player's respawn, he is thrown from the server. I also tested version 1.11 and found the same bug there. 
This [plugin](https://forums.spongepowered.org/t/easy-scoreboards-v2-3/12746) uses a static scoreboard, but updates its values. The problem is the same as for my code.

**Comment by ryantheleach** [comment]
Anyway, either a heap dump or some screenshots of VisualVM would give a large hint to devs on what to look out for.

**Comment by SawFowl** [comment]
It seems to me to add a method of removing the scoreboard from the player will be enough.

**Comment by ryantheleach** [comment]
A player should always have a scoreboard though, it's just whether it's an existing one, or the server scoreboard.
