### ISSUE TITLE
Undefined behavior changing inventory during InteractInventoryEvents

### ISSUE THREAD

**Issue by SimonFlash** [SpongePowered/Sponge#1826]
When changing the inventory whilst in the middle of an event (particularly `ClickInventoryEvent`), the active inventory of the event is closed before the event has been completed and can be properly canceled.. The result is an undefined state that often results in the cursor item being dropped because the event has not been canceled yet. This is fixed by delaying any calls to open/close the inventory by a tick.

If a change to the open inventory is detected while processing an event, it should delay the action by a tick and print out a warning message as this is undefined (and potentially harmful) behavior. Moving forward to API 8 this should probably be throwing an exception instead.

***

SpongeForge: `2931`

**Comment by Zidane** [comment]
Fixed in stable-7
