### ISSUE TITLE
Item despawns after cancelling pickup event

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Sponge#1837]
**I am currently running**
- SpongeVanilla version:  1.12.2-7.1.0-BETA-26
- Java version:  8
- Operating System: win7

After cancelling the pickup event the item is not picked up as intended, but also despawns from the ground

Code:

	@Listener
	public void onItemPickup(ChangeInventoryEvent.Pickup event, @First(typeFilter = {Player.class}) Player player) {
			event.setCancelled(true);
			return;

**Comment by phit** [comment]
this is intentional see https://github.com/SpongePowered/SpongeCommon/issues/1693#issuecomment-356179190
