### ISSUE TITLE
tileentity-activation module not working on 1.12.2

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#1838]
This issue was originally submitted by @KangYee in [SpongePowered/SpongeForge#2052](https://github.com/SpongePowered/SpongeForge/issues/2052).
___
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2969
- Forge version: forge-1.12.2-14.23.2.2611
- Java version: java8 u163
- Operating System:windows server 2012R2

**Issue Description**
When I set the hopper block-range to 1 in the configuration, the hopper will still work.

**Comment by phit** [comment]
will need some testing user reports setting range on a hopper to 1 will still allow it to work when further away, could be that the chunk was force loaded
