### ISSUE TITLE
[2970 SF] Buckets can be filled through GP deny flags (video)

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/Sponge#1843]
**I am currently running**

- SpongeForge version: 2970
- SpongeVanilla version: N/A
- Java version: 8
- Operating System: CentOS 7

- Plugins/Mods: 
![image](https://user-images.githubusercontent.com/18584380/37870388-0521857e-2fa3-11e8-8797-e93ac70519d1.png)

**Issue Description**
https://cdn.discordapp.com/attachments/243144280405835777/426923181916291072/2018-03-23_18-53-02.mp4

**Comment by bloodmc** [comment]
GP does not stop item interactions by default in order to prevent various issues with items such as foods/mod items etc.. Simply use the interact-item-secondary flag and deny bucket use.
