### ISSUE TITLE
UseItemStackEvent doesn't work on SpongeForge (but maybe on SpongeVanilla)

### ISSUE THREAD

**Issue by nihiluis** [SpongePowered/Sponge#1848]
I am currently running

    SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar
    Forge version: Forge Mod Loader version 14.23.2.2635
    SpongeVanilla version: NO
    Java version: 8_186
    Operating System: DEBIAN

    Plugins/Mods: SpongeForge and DynmapForge, rest are private

**Issue Description**
```kotlin
    @Listener
    fun onEat2(event: UseItemStackEvent.Finish) {
        println("FINISHING USE ITEM STACK")
    }

    @Listener
    fun onEat3(event: UseItemStackEvent) {
        println("GENERAL USE ITEM STACK EVENT")
    }
```

registering this Listener and eating something or drinking a potion does nothing. I'd expect it to print something to the console which it doesnt. no reaction what so ever. I remember my code worked in the past. I was using spongevanilla back then. it might be related.

**Comment by nihiluis** [comment]
I checked SpongeForge and SPongeCommon and found that SpongeForge has this function
`createPlayerUseItemFinishEvent`
https://github.com/SpongePowered/SpongeForge/blob/5087d8342d0ed2f6ae5f7dd8941115f29d9b29a1/src/main/java/org/spongepowered/mod/event/SpongeForgeEventFactory.java#L720

but apparently it's never called? I might err though.

**Comment by phit** [comment]
see https://github.com/SpongePowered/SpongeForge/issues/1928
