### ISSUE TITLE
InteractItemEvent is called twice?

### ISSUE THREAD

**Issue by nihiluis** [SpongePowered/Sponge#1849]
SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar
    Forge version: Forge Mod Loader version 14.23.2.2635
    SpongeVanilla version: NO
    Java version: 8_186
    Operating System: DEBIAN

    Plugins/Mods: SpongeForge and DynmapForge, rest are private

**Issue Description**
```kotlin
    @Listener
    @Include(InteractItemEvent::class, InteractBlockEvent::class)
    fun onInteract2(event: HandInteractEvent, @First player: Player) {
        println("testing somethiung")
    }
```

when I use this and right click an item (and look in the air) this is executed twice. which is unexpected and should not happen imo. If this is WAD please tell me how to make it only execute once.

**Comment by nihiluis** [comment]
Apparently right clicking AIR counts as an interactblockevent.

**Comment by Faithcaio** [comment]
InteractItemEvent fires twice because there are 
MainHand and OffHand SubEvents 
you get both if you do not specify which one you want.
