### ISSUE TITLE
What it means when LegacyCustomDataClassContentUpdater fails

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#1859]
This is not an issue that is needed to be fixed but I want to share what I discovered and maybe save you a bit time if someone else has this problem too.

So the error is this: https://pastebin.com/GQLhPciE
Note that line 2 & 3 contain my own debug messages.

So the legacy data updater wants to update this data(as seen in the log):

```
{ManipulatorData:{ContentVersion:1,ItemCosts:{ContentVersion:1,ItemType:"NONE",UnsafeDamage:0,Count:1}},ManipulatorId:"entity-commands:item-costs-data"}
```

The data is of `ContentVersion: 1` but doesn't contain the manipulator class. It already has the `ManipulatorId`, which should only be present with `ContentVersion: 2`.
This data was probably created at the time the legacy data wasn't quite working in Sponge and the failed data somehow duped itself and got larger and larger.
This inconsistent data was there a long time but it was only discovered with some recent changes.

I have temporarily fixed this by adding a 'pass' to the updater when the new ID is already there:

```
public class LegacyCustomDataClassContentUpdater implements DataContentUpdater {

    @Override
    public int getInputVersion() {
        return DataVersions.Data.CLASS_BASED_CUSTOM_DATA;
    }

    @Override
    public int getOutputVersion() {
        return DataVersions.Data.CUSTOM_DATA_WITH_DATA_IDS;
    }

    @SuppressWarnings("deprecation")
    @Override
    public DataView update(DataView content) {
        // CHANGES Start
        // If the data already has the updated content(id instead of class) this update will be passed and won't throw any errors
        if (content.getString(DataQueries.DATA_ID).isPresent()) {
            // remove any old data if present
            if (content.contains(DataQueries.DATA_CLASS)) {
                content.remove(DataQueries.DATA_CLASS);
            }
            return content;
        }
        // CHANGES End

        final String className = content.getString(DataQueries.DATA_CLASS).get();

        final Optional<DataRegistration<?, ?>> registration = SpongeManipulatorRegistry.getInstance().getRegistrationForLegacyId(className);
        if (!registration.isPresent()) {
            return content;
        }
        content.set(DataQueries.DATA_ID, registration.get().getId());
        content.remove(DataQueries.DATA_CLASS);
        return content;
    }
}
```

I haven't tested this code because I don't have the world files with this corner case data. I will report when it was tested by somehow who has that world.

I don't know if this was the right place to post this. Maybe this issue should be closed immediately and then discussed.

**Comment by phit** [comment]
shrug, maybe it will help someone when they search for this in the future, but closing as there's nothing here for us to handle
