### ISSUE TITLE
Spelling Mistake with Unknown InventoryArchetype name

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#1863]
[InventoryArchetypeRegistryModule.java#L372](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/registry/type/item/InventoryArchetypeRegistryModule.java#L372)

Should be `UNKNOWN` instead of `UKNOWN`

**Comment by phit** [comment]
please put this in https://github.com/SpongePowered/SpongeCommon/issues/23
