### ISSUE TITLE
Automatically infer SPAWNER_NEXT_ENTITY_TO_SPAWN when setting SPAWNER_ENTITIES

### ISSUE THREAD

**Issue by Dykam** [SpongePowered/Sponge#1864]
**I am currently running**
- SpongeVanilla version: 02996af60d947986a1096eee406a967d412d0fd6
- Java version: jdk1.8.0_152
- Operating System: Windows 10

A common use case is to simply set the type of mob to spawn to a single mob. Right now the following is required:

```kotlin
// MobSpawner spawner
val weightedTable = WeightedTable<EntityArchetype>()
val spider = WeightedSerializableObject(EntityArchetype.of(EntityTypes.SPIDER), 1)
weightedTable.add(spider)

mobSpawner.offer(Keys.SPAWNER_ENTITIES, weightedTable)
mobSpawner.offer(Keys.SPAWNER_NEXT_ENTITY_TO_SPAWN, spider)
```

Setting the next entity feels redundant, as discussed in chat.

**Comment by gabizou** [comment]
I'll consider adding this as it would be easy to chuck into the transaction result returned when manipulating the list of spawnable entities.
