### ISSUE TITLE
CommandBlock implementation problems

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Sponge#187]
Right now we have `BlockCommandSource` as mixin for `CommandBlockLogic`, where the commands are internally stored and also executed with. However, additionally right now `CommandBlock` and `MinecartCommandBlock` extend `BlockCommandSource` with no implementation in the mixins for these interfaces.

While we could theoretically just proxy all `CommandSource` methods to the `CommandBlockLogic`, this would most likely cause issues when plugins try to execute commands as a `CommandBlock`. The internal Vanilla commands require `ICommandSender` which just `CommandBlockLogic` implements. Whie we could also proxy `ICommandSender` this may also cause a few other problems at some places where Minecraft would _expect_ the command to be a `CommandBlockLogic` and not the actual tile entity or minecart we've modified to proxy everything to the command block logic.

One way to fix this would be to change the `CommandBlock` and `MinecartCommandBlock` interfaces to have a `BlockCommandSource getSource()` method, but I agree with @Deamon5550 after a discussion about this that this might be an implementation leak in the API because there wouldn't be a big reason for `CommandBlock` not to implement the `BlockCommandSource` directly normally.

**Comment by Zidane** [comment]
@Minecrell 

Is this issue solved or?

**Comment by Zidane** [comment]
@zml2008 

Did you happen to fix this in common?

**Comment by zml2008** [comment]
Not currently, still implemented by CommandBlockLogic. There are some issues presented since this makes only CommandBlocks the only CommandSources that wrap the MC objects rather than implement directly.

**Comment by JBYoshi** [comment]
It looks like this is handled in my commands PR, which is already merged. SpongePowered/SpongeCommon#80

**Comment by zml2008** [comment]
mk, cool
