### ISSUE TITLE
TPS loss on UpdateBlock:flowing_water

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/Sponge#1871]
**I am currently running**

- SpongeForge version: SF 2990 (happens with previous and later builds as well)
- SpongeVanilla version: N/A
- Java version: 8
- Operating System: CentOS 7
- Additional information: Intel I7-6700K DDR4 - 2400 MHz - SSD

- Plugins/Mods: 
![image](https://user-images.githubusercontent.com/18584380/38707974-e3fa80c4-3e81-11e8-807a-ec8e0f0d77ca.png)

**Issue Description**
Water flowing causes performance loss on API 7. Can't remember ever having it on API 5 - confirmed by my own timings as well as other sponge users. Disabling GriefPrevention's `liquid-flow` module does not help, the issue remains. 

I am running the same setup as on API 5, and without Sponge, the server is able to take the water flow without causing an impact on the server's performance. Ran this by @bloodmc and he referred me back to Sponge, where I found others having the same issue. 

To reproduce:
- WE 20 source blocks of water, 5 blocks above the ocean level, using `//set water`. 
> Though this should cause some strain, it should not be noticeable as it is currently.

Timings:
https://timings.aikar.co/?id=5d71989814b84dc893883e141b3ed762
https://timings.aikar.co/?id=a2b92d400d4d427fa1aac60222e36d8d
![image](https://user-images.githubusercontent.com/18584380/38708037-421ce53e-3e82-11e8-803a-b952d104f2ed.png)

**Comment by Zidane** [comment]
@Rasgnarok 

Anyway you can pull off getting a yourkit profiler snapshot?

**Comment by LemADEC** [comment]
![image](https://user-images.githubusercontent.com/4776032/39259567-03a84df4-48b7-11e8-82e5-43dd313f46df.png)
This was reproduced on an FTB revelation server running spongeforge-1.12.2-2611-7.1.0-BETA-3017.jar:
1- go above an ocean
2- stand 20+ blocks above ocean surface
3- world edit a flat platform 64x1x64 blocks of water (//pos1, //pos2, //expand 32 n,s,e,w, //set water)
4- as water flows, "/forge tps" shows TPS going fairly high (200+ ms per tick)
5- once the water falling down reached the ocean surface, TPS goes back to normal
6- world edit out the source blocks (//set 0)
7- as water dissipate, TPS tanks fairly high (550+ ms per tick)
8- consider removing all flowing water before the server times out

**Comment by LemADEC** [comment]
Issue is reproduced in single player using
Twitch launcher -> Vanilla launcher
Forge Mod Loader version 14.23.3.2655 for Minecraft 1.12.2
Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0
5GB RAM allocated to the game
No fancy graphics, no particles
spongeforge-1.12.2-2655-7.1.0-BETA-3059
worldedit-forge-mc1.12-6.1.8-dist
All defaults settings

Steps to reproduce:
1- create new flat world
2- go 20+ high
3- create a 64x1x64 water platform (//pos1, //pos2, //expand 32 n,s,e,w, //set water)
4- as water flows, monitor mean tick time with /forge tps
5- once the water falling down reached the surface, confirm TPS goes back to normal
6- replace water source with air (//set 0)
7- as water dissipate, monitor mean tick time 


Without Sponge, just vanilla and world edit we get this:
![image](https://user-images.githubusercontent.com/4776032/39261839-fd59293a-48bd-11e8-95a4-afecbe25514a.png)
While flowing, mean tick time goes up to 39 ms
While dissipating, mean tick time goes up to 78 ms


With Sponge, we get this:
![image](https://user-images.githubusercontent.com/4776032/39261916-3b4827a0-48be-11e8-9b9a-44c2afc235bf.png)
While flowing, mean tick time goes up to 30 ms
While dissipating, mean tick time goes up to 457 ms
Within 4 seconds after removing the water source blocks, we get the typical warning:
[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2984ms behind, skipping 59 tick(s)
So I guess it took about 1 second to shock the server.

The mean tick time measured are very basic, that's what I had on hand.
Nota: YourKit crash the game within 30 s from attaching to that simple modpack, no idea why.

**Comment by XakepSDK** [comment]
Can you send me test map? I'll profile it with yourkit.

**Comment by LemADEC** [comment]
it's really just a flat world to reproduce it.

**Comment by XakepSDK** [comment]
Log from console: https://gist.github.com/XakepSDK/a98c51ab46197e0699fb07f596eca39c
Snapshot: [forge-1.12.2-14.23.3.2655-universal-2018-04-26.zip](https://github.com/SpongePowered/SpongeCommon/files/1948880/forge-1.12.2-14.23.3.2655-universal-2018-04-26.zip)

@Zidane

**Comment by bloodmc** [comment]
@LemADEC Please test latest SF 3067+

**Comment by LemADEC** [comment]
As tested in single player with spongeforge-1.12.2-2655-7.1.0-BETA-3070, same setup as above:
While flowing, mean tick time goes up to 45 ms.
While dissipating, mean tick time goes up to 279 ms.
Within 6 seconds after removing the water source blocks, we get the typical warning:
```
[19:05:31] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2504ms behind, skipping 50 tick(s)
```
So I guess it took about 3 seconds to shock the server.

Given the crude measurement, flowing didn't change much.
Dissipating is at least twice faster than before, but still 3 times slower with Sponge.

Nice progress, keep it coming :)

**Comment by Rasgnarok** [comment]
Ticket's still marked as waiting for reply, am I missing something?

**Comment by bloodmc** [comment]
@Rasgnarok @LemADEC Please retest with latest SF build.

**Comment by LemADEC** [comment]
As tested in single player with spongeforge-1.12.2-2703-7.1.0-BETA-3119 and Forge 2703, same setup as above:
While flowing, mean tick time goes up to 37 ms.
While dissipating, mean tick time goes up to 255 ms.
Within 12 seconds after removing the water source blocks, we get the typical warning:
```
[08:42:24] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 5092ms behind, skipping 101 tick(s)
```
So I guess it took about 7 seconds to shock the server.

Given the crude measurement, flowing didn't change much.
Dissipating seems to be 10% faster than before, but that doesn't seem really significant.

@bloodmc I've checked the change logs and couldn't see a reference to the fix. Was it pushed in stable yet?

**Comment by LemADEC** [comment]
As tested in single player with spongeforge-1.12.2-2703-8.0.0-BETA-3123 and Forge 2703, same setup as above:
While flowing, mean tick time goes up to 33 ms.
While dissipating, mean tick time goes up to 257 ms.
Within 8 seconds after removing the water source blocks, we get the typical warning:
```
[08:54:20] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2416ms behind, skipping 48 tick(s)
```
So I guess it took about 6 seconds to shock the server.

Given the crude measurement, flowing didn't change much.
Dissipating seems to be the same on stable and bleeding branches. We're still 3 times slower with sponge than without it.

I redid the test with Warmroast, while water is flowing (started a bit before the //set water):
![image](https://user-images.githubusercontent.com/4776032/40601642-42835f06-6256-11e8-80df-0c55e989fd03.png)
It appears there's 4.78% CPU lost in thread locking during lighting computation?

I've also started Warmroast right after the //set 0:
![image](https://user-images.githubusercontent.com/4776032/40602014-876a56c8-6257-11e8-9475-12f20e7bcd56.png)

From a quick check, I see a few cases of CPU usage not adding up in org.spongepowered.mod.event.SpongeModEventManager.extendedPost().
Is there's something to check in there?
![image](https://user-images.githubusercontent.com/4776032/40601958-53c5c8e8-6257-11e8-898a-5a278f0fa4d6.png)
=> 5.33 % vs 0.65 + 0.32 = 0.97 %
![image](https://user-images.githubusercontent.com/4776032/40602046-acad6eb6-6257-11e8-8531-b886347492b4.png)
=> 6.14 % vs 0.81 + 0.32 = 1.13 %
