### ISSUE TITLE
Correct SpongeForge version to use for Forge 2627

### ISSUE THREAD

**Issue by TheCipher01** [SpongePowered/Sponge#1876]
**I am currently running**

- SpongeForge version: x
- SpongeVanilla version:  x
- Java version: 8
- Operating System: ubuntu

- Plugins/Mods:  FTBRevelations Pack

**Issue Description**
SpongeForge causes FTBRevelations server to crash, with this error

> `18.04 02:25:55 [Server] Server thread/FATAL [FML]: 18.04 02:25:55 [Server] INFO States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored 18.04 02:25:55 [Server] INFO | State | ID | Version | Source | Signature | 18.04 02:25:55 [Server] INFO |:----- |:------------------------- |:--------------------------- |:------------------------------------------------- |:---------------------------------------- | 18.04 02:25:55 [Server] INFO | UC | minecraft | 1.12.2 | minecraft.jar | None | 18.04 02:25:55 [Server] INFO | UC | mcp | 9.42 | minecraft.jar | None | 18.04 02:25:55 [Server] INFO | UC | FML | 8.0.99.99 | ftbrevelations1.8.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | 18.04 02:25:55 [Server] INFO | UC | forge | 14.23.2.2627 | ftbrevelations1.8.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | 18.04 02:25:55 [Server] INFO | UC | advancedrocketrycore | 1 | minecraft.jar | None | 18.04 02:25:55 [Server] INFO | UC | spongeapi | 7.1.0-SNAPSHOT-bec74cd | spongeforge-1.12.2-2611-7.1.0-BETA-3019.jar | None | 18.04 02:25:55 [Server] INFO | UC | sponge | 1.12.2-2611-7.1.0-BETA-3019 | spongeforge-1.12.2-2611-7.1.0-BETA-3019.jar | 6729a677746f8cf63ef31881f913ed15d431b7f0 | 18.04 02:25:55 [Server] INFO | UC | foamfixcore | 7.7.4 | minecraft.jar | None | 18.04 02:25:55 [Server] INFO | UC | opencomputers|core | 1.7.2.67 | minecraft.jar | None | 18.04 02:25:55 [Server] INFO | UC | elucore | 1.0 | minecraft.jar | None | 18.04 02:25:55 [Server] INFO | UC | actuallyadditions | 1.12.2-r133 | ActuallyAdditions-1.12.2-r133.jar | None | 18.04 02:25:55 [Server] INFO | UC | baubles | 1.5.2 | Baubles-1.12-1.5.2.jar | None | 18.04 02:25:55 [Server] INFO | UC | actuallybaubles | 1.1 | ActuallyBaubles-1.12-1.1.jar | None | 18.04 02:25:55 [Server] INFO | UC | redstoneflux | 2.0.1 | RedstoneFlux-1.12-2.0.1.2-universal.jar | d4f1503fbacd9b9fb767720420c5395104239ec9 | 18.04 02:25:55 [Server] INFO | UC | cofhcore | 4.3.10 | CoFHCore-1.12.2-4.3.10.5-universal.jar | None | 18.04 02:25:55 [Server] INFO | UC | libvulpes | 0.2.8.-27 | LibVulpes-1.12.2-0.2.8-27-universal.jar | None | 18.04 02:25:55 [Server] INFO | UC | advancedrocketry | 1.4.0.-67 | AdvancedRocketry-1.12.2-1.4.0-67.jar | None | 18.04 02:25:55 [Server] INFO | UC | appliedenergistics2 | rv5-stable-11 | appliedenergistics2-rv5-stable-11.jar | None | 18.04 02:25:55 [Server] INFO | UC | bdlib | 1.14.3.12 | bdlib-1.14.3.12-mc1.12.2.jar | None | 18.04 02:25:55 [Server] INFO | UC | ae2stuff | 0.7.0.4 | ae2stuff-0.7.0.4-mc1.12.2.jar | None | 18.04 02:25:55 [Server] INFO | UC | akashictome | 1.2-10 | AkashicTome-1.2-10.jar | None | 18.04 02:25:55 [Server] INFO | UC | crafttweaker | 4.1.6 | CraftTweaker2-1.12-4.1.6.jar | None | 18.04 02:25:55 [Server] INFO | UC | mtlib | 3.0.4 | MTLib-3.0.4.jar | None | 18.04 02:25:56 [Multicraft] Skipped 344 lines due to rate limit (30/s)`

And when I remove it, server loads fine, the only thing I can figure is there's no sponge forge version for forge 2627, only 2611, 2655 and so on. This version of forge is required for the 1.8 update of FTBRevelations. Any help would be appreciated, and sorry if this was the wrong place to post this.

**Comment by gabizou** [comment]
SpongeForge builds for Forge 2611 are compatible with 2627 last I recall. If not, then I'd recommend to update to the Forge RB which is 2655. Otherwise, we're not going to **revert** an update to target a specific forge version that is already outdated.

Likewise, you didn't follow the format, you just pasted some paste without any actual logs, if you still believe this is a salvageable issue that someone can fix, then by all means provide server logs either using gist.github.com or pastebin or someother pasting site.
