### ISSUE TITLE
The item disappears when cancelling DropItemEvent.Custom

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/Sponge#1879]
**I am currently running**

- SpongeForge version: 
- SpongeVanilla version: 1.12 cloned from github (SpongeCommon updated to [this commit](https://github.com/SpongePowered/SpongeCommon/commit/36a82d2c6bfc2a916d0b9772b750ee7b9d87481c
))

**Issue Description**
See https://github.com/SpongePowered/SpongeCommon/issues/1280. This is the only one I'm able to reproduce. 

> When cancelling DropItemEvent.Custom:
>     The item disappears if I open my inventory, take the item with the cursor and close the inventory.

Note: No, you can't use DropItemEvent.Dispense, it's not fired.

**Code snippet**

```
    @Listener
    public void onDrop(DropItemEvent.Custom event) {
        System.out.println(event.getCause());
        event.setCancelled(true);
    }
```

**Comment by Faithcaio** [comment]
Not sure what to do here. (I assume this was canceling the drop from cursor when closing the inventory)
Where would the item go to? Add it back to the inventory? What to do when it is full then?

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/81ce267dc845e37caf3bed3f3fdc9432a8b14bf6
https://github.com/SpongePowered/SpongeCommon/commit/750088ff008213f4587a7d389ca0259d069ad5b3
