### ISSUE TITLE
Lag in event tracking

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/Sponge#1881]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-3017.jar
- SpongeVanilla version: 
- Java version: 1.8.0_161
- Operating System: CentOS Linux release 7.4.1708

- Plugins/Mods:
FTB Revelation 1.8.0
Notable plugins:
Nucleus-1.3.7-S7.0-MC1.12.2-plugin.jar
griefprevention-1.12.2-4.3.0.573.jar

**Issue Description**
When checking profiler result we can see jumps in consumed CPU in Sponge event tracking call-stack for methods that don't do much processing. This is usually an indication of bad multi-threading (relying too much on synchronization) or very frequent Garbage collection in the code (typically when lots of memory was allocated then freed in sub methods).

Here's an example of such occurrence where 0.46% out of 0.82% is missing:
![image](https://user-images.githubusercontent.com/4776032/39070660-82760b52-44e4-11e8-92d4-51c079ad7ceb.png)

**Comment by Zidane** [comment]
@LemADEC 

```
This is usually an indication of bad multi-threading (relying too much on synchronization) or very frequent Garbage collection in the code (typically when lots of memory was allocated then freed in sub methods).
```

I take it you didn't read the code behind EventContext.get as that literally makes no sense at all.

Here let me help:

https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/cause/EventContext.java#L98

It is just a map lookup from an ImmutableMap and the "lag" is literally a minuscule fraction (as you have pointed out).

**Comment by LemADEC** [comment]
It just means the source of memory allocation is somewhere else in the code, so the hunt continues
