### ISSUE TITLE
TPS drop on World Generation.

### ISSUE THREAD

**Issue by demkom58** [SpongePowered/Sponge#1891]
### TPS:
![tps](https://user-images.githubusercontent.com/5957073/39362228-5ad3883c-4a2e-11e8-8a40-34219865c2c4.png)

### Version:
![version](https://user-images.githubusercontent.com/5957073/39362232-609a7942-4a2e-11e8-9d5a-a7e79b9b9bb5.png)
**_On `spongevanilla-1.12.2-7.1.0-BETA-42`(latest) TPS dorps too._**

### Processor:
![proc](https://user-images.githubusercontent.com/5957073/39362236-65e17dec-4a2e-11e8-908e-1394c1a6b17c.png)

### Boot script:
`chcp 65001
title TestHOLDER
cls
"C:\Program Files\Java\jdk1.8.0_151\bin\java.exe" -Xmx1G -Xms1G -Dfile.encoding=UTF-8 -jar "spongevanilla-1.12.2-7.1.0-BETA-33.jar"
pause`

### OS:
Windows 10

### Timings:
https://timings.aikar.co/?id=cf6304e1308046458be0c31d8983cc49

**Comment by Rasgnarok** [comment]
This is pretty much normal as things go, it's why most people that run servers have to pregenerate. There's no real way around it anymore, sadly.

**Comment by phit** [comment]
pretty much what @Rasgnarok said, we already have multiple patches that improve generation peformance a bit
but you are still limited in performance due to generation being single threaded like most of this game
