### ISSUE TITLE
Hotbar slot resets to first slot after death

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1892]
SpongeVanilla beta 42, check it in demo server.

**Comment by Aaron1011** [comment]
Doesn't this happen in Vanilla?

**Comment by parlough** [comment]
Yeah are we missing some information @XakepSDK? On death, with keepInventory as false and true, the selected slot always gets reset to the first in normal vanilla.

**Comment by XakepSDK** [comment]
Oh, yes, just tested that in pure vanilla server.
This is annoying, can it be "fixed" with a server side flag?

**Comment by Aaron1011** [comment]
To me, this sounds like something for a plugin to address.

**Comment by XakepSDK** [comment]
Well, i hope that this will be easy, without mess with `Map`s.
