### ISSUE TITLE
isConstructing not updated for item entities

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#1899]
**I am currently running**

- SpongeForge version: Not tested
- SpongeVanilla version: 1.12.2-7.1.0-BETA-42
- Java version: Java 1.8.0_171
- Operating System: Windows 10 April Update

- Plugins/Mods:
Plugin I'm developing which exposed this issue.

**Issue Description**
https://github.com/SpongePowered/SpongeCommon/blob/f0e7dfff35fc352a8fcd5b51790d175b8c0de0d7/src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java#L171 The variable `isConstructing` is never updated to be false for **Item entities** that are spawned in the world.

I noticed this as when I dropped an item `isInConstructPhase()` always returned true, The value changes if the server is restarted (Have not tested chunk unloading).

**Comment by bloodmc** [comment]
@Aaron1011 please take a look at this.

**Comment by ryantheleach** [comment]
This would indicate at first glance that the post construct events are failing to fire.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/fd4ff92c3ae5062b1368f01e50541832915bedd5
