### ISSUE TITLE
`Keys.Color` is not empty on leather armor without a color tag

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/Sponge#1902]
**I am currently running**
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3064
- SpongeVanilla version: 1.12.2-7.1.0-BETA-42
- Java version: 1.8.0_161
- Operating System: WIndows 10

**Issue Description**

When running `ItemStack.of(ItemTypes.LEATHER_HELMET, 1).get(Keys.Color)` I'd expect this to return an empty `Optional`, however it returns an Optional with the color `#a06540`.

**Comment by BrainStone** [comment]
Or at least provide a possibility to tell wether a leather armor piece has the color tag set or not.
Because while they might look the same, they certainly aren't the same when hovering over them.

**Comment by BrainStone** [comment]
@Meronat, any updates?

**Comment by gabizou** [comment]
~moveto sc

**Comment by gabizou** [comment]
@move to sc

**Comment by gabizou** [comment]
~move to sc

**Comment by gabizou** [comment]
What about if you dye the helmet normally in vanilla? Does it then have a color tag?

**Comment by BrainStone** [comment]
Yes. If you just craft it, it doesn’t, but once you start combining it with dyes, it has.
