### ISSUE TITLE
Sponge is soft-resetting player advancements on world load

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#1904]
**Tested on the following**

- SpongeForge version:
1.12.2-2611-7.1.0-BETA-3016 (forge-1.12.2-14.23.2.2645)
1.12.2-2655-7.1.0-BETA-3065 (forge-1.12.2-14.23.3.2655)
- SpongeVanilla version:
1.12.2-7.1.0-BETA-32
1.12.2-7.1.0-BETA-42
- Java version: 1.8.0_171
- Operating System:
Linux
Windows

- Plugins/Mods:
Nucleus-1.3.6-S7.0-MC1.12.2-plugin

**Issue Description**
When a world is loaded Sponge appears to do something with Advancements which results in every player currently logged in having there advancements soft-reset, relogging or running `/reload` will bring back the players advancements.

This issue was noticed on the SevTech modpack, The result of this is that players do not get the rewards from completing advancements which means they cannot progress.

**This issue is not present on a Forge only server.**

**Reproduction**
Run the following commands from a Player (Console won't work unless you are targeting an online player):

`/advancement grant @p only minecraft:story/root`
`/advancement test @p minecraft:story/root` - Make sure it says 'Player ... has completed advancement ...'
`/world unload DIM-1` - Requires Nucleus
`/world load DIM-1` - Requires Nucleus
`/advancement test @p minecraft:story/root` - This should now say 'Player ... has **not** completed advancement ...'

Extra:
Relog or run `/reload`
`/advancement test @p minecraft:story/root` - This should now say 'Player ... has completed advancement ...'

**Comment by LXGaming** [comment]
After a bit of digging I believe I've found the root cause of this issue

https://github.com/SpongePowered/SpongeCommon/blob/36a82d2c6bfc2a916d0b9772b750ee7b9d87481c/src/main/java/org/spongepowered/common/mixin/core/advancement/MixinAdvancementProgress.java#L129

The `AdvancementCriterion` object is re-created when a world is loaded and the `progressMap` in `MixinAdvancementProgress` is not updated, the result is that `get(getAdvancement().getCriterion())` returns an empty Optional as there is no equals or hashcode methods implemented in the `AdvancementCriterion` class to match them together

**Comment by bloodmc** [comment]
@Cybermaxke Please take a look at this issue.

**Comment by Cybermaxke** [comment]
@bloodmc Fixed in #1929
