### ISSUE TITLE
Failed to save configuration

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#1906]
This issue was originally submitted by @TomTheHero in [SpongePowered/SpongeForge#1991](https://github.com/SpongePowered/SpongeForge/issues/1991).
___
- SpongeForge version: spongeforge-1.12.2-2586-7.1.0-BETA-2887.jar
- Forge version: 14.23.1.2586
- Java version: build 1.8.0_151-b12
- Operating System: 64bit windows 10 home

Plugins: Currently none
Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Generators, Ambience, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, AutoRegLib, BD Lib, Baubles, Better Builder's Wands, BetterBedrockGen, Block Armor, Botania, ChickenChunks, Chisel, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, ComputerCraft, CraftTweaker JEI Support, CraftTweaker2, Cucumber, Cyberware, DeepResonance, ElecCore, Extended Crafting, External Tweaker, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Gravestone Mod, ICBM-Classic, Industrial Foregoing, IndustrialCraft 2, InstantUnify, Iron Chest, IvToolkit, Loot Bags, LootTweaker, MTLib, Magical Psi, Mantle, Mekanism, MekanismGenerators, MekanismTools, MmmMmmMmmMmm, Moar Tinkers, Mod Tweaker, Modern Warfare, OMLib, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreExcavation, PlusTiC, ProjectE, Psi, Quick Leaf Decay, Random Things, Redstone Arsenal, Redstone Flux, Refined Storage, SanAndreasPs Mod Library, SanAndreasPs Player Model, Secret Rooms 5, Shadowfacts' Forgelin, SimpleInventoryStarter, TATW, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Addons, Tinkers' Construct, UniDict, Voltz Engine, WanionLib, Zero CORE, mob_grinding_utils

Whenever the server launches this error will sometimes appear and this issue does not happend if sponge ain't present https://pastebin.com/S5jkn7pR

This issue occurs at random during startup and i currently have no logs about it available except from the pastebin above.

**Comment by ziceptor** [comment]
> SpongePowered/SpongeCommon@4bbcc65 fixes the problem indicated by the stack trace, it was a duplicated save operation when creating the custom data config file.

The fix didn't work.

[debug.log](https://gist.github.com/ziceptor/29f7f75f4b12fe7d5ce6394f60ed9057)
[latest.log](https://gist.github.com/ziceptor/a22ceaa4feb735f9bf837f8543c24949)

forge-1.12.2-14.23.3.2655-universal.jar
spongeforge-1.12.2-2655-7.1.0-BETA-3070.jar

Windows 7
