### ISSUE TITLE
Teleporting player, who is viewing chest inventory, throws an exception

### ISSUE THREAD

**Issue by MrOnlineCoder** [SpongePowered/Sponge#1913]
**I am currently running**

Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-06016f29
SpongeVanilla: 1.12.2-7.1.0-BETA-33

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode)

- Operating System: Windows 7 64 bit / CentOS (tested on both)

- Plugins/Mods: Nucleus

**Issue Description**

Hello. I found an issue in Sponge 1.12.2:

If a plugin or player teleports another player, which is viewing chest inventory, an exception is thrown and teleportation does not occur.

Steps to reproduce:

* Join a server
* Open any chest and do not close the GUI
* Try to teleport yourself (through console or from another player)
Error message:

```
> net.minecraft.util.ReportedException: Exception while updating neighbours
> at org.spongepowered.common.event.tracking.PhaseTracker.notifyBlockOfStateChange(PhaseTracker.java:528) ~[PhaseTracker.class:1.12.2-7.1.0-BETA-24]
> at net.minecraft.world.WorldServer.func_175685_c(SourceFile:2629) ~[oo.class:?]
> at net.minecraft.tileentity.TileEntityChest.func_174886_c(SourceFile:286) ~[avl.class:?]
> at net.minecraft.inventory.ContainerChest.func_75134_a(SourceFile:68) ~[afv.class:?]
> at net.minecraft.entity.player.EntityPlayerMP.func_71128_l(SourceFile:887) ~[oq.class:?]
> at net.minecraft.entity.player.EntityPlayerMP.func_71053_j(SourceFile:872) ~[oq.class:?]
> at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractInventoryCloseEvent(SpongeCommonEventFactory.java:967) ~[SpongeCommonEventFactory.class:1.12.2-7.1.0-BETA-24]
> at net.minecraft.entity.player.EntityPlayerMP.closeInventory(SourceFile:3982) ~[oq.class:?]
> at net.minecraft.entity.Entity.setLocation(SourceFile:4627) ~[vg.class:?]
> at net.minecraft.entity.Entity.setLocationAndRotation(SourceFile:4558) ~[vg.class:?]
> at io.github.nucleuspowered.nucleus.internal.teleport.NucleusTeleportHandler.teleportPlayer(NucleusTeleportHandler.java:164) ~[NucleusTeleportHandler.class:1.3.2-S7.0]
> at io.github.nucleuspowered.nucleus.internal.teleport.NucleusTeleportHandler.teleportPlayer(NucleusTeleportHandler.java:130) ~[NucleusTeleportHandler.class:1.3.2-S7.0]
> at io.github.nucleuspowered.nucleus.modules.jail.handlers.JailHandler.lambda$jailPlayer$4(JailHandler.java:160) ~[JailHandler.class:1.3.2-S7.0]
> at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-7.1.0-BETA-24]
> at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-7.1.0-BETA-24]
> at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-7.1.0-BETA-24]
> at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-7.1.0-BETA-24]
> at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-7.1.0-BETA-24]
> at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_101]
> at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-7.1.0-BETA-24]
> at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-7.1.0-BETA-24]
> at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-7.1.0-BETA-24]
> at net.minecraft.server.dedicated.DedicatedServer.handler$onTick$zpn000(SourceFile:1263) [nz.class:?]
> at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:351) [nz.class:?]
> at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
> at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
> at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
> Caused by: java.lang.NullPointerException
> at org.spongepowered.common.event.tracking.phase.packet.PacketState.associateNeighborStateNotifier(PacketState.java:99) ~[PacketState.class:1.12.2-7.1.0-BETA-24]
> at org.spongepowered.common.event.tracking.phase.packet.PacketState.associateNeighborStateNotifier(PacketState.java:57) ~[PacketState.class:1.12.2-7.1.0-BETA-24]
> 
```

In my case, it happened when I teleported player using Nucelus /tppos, /tp commands, so I created an issue on their github: [link](https://github.com/NucleusPowered/Nucleus/issues/1148)

but dev said that it is a problem in Sponge itself.

**Comment by Aaron1011** [comment]
@MrOnlineCoder: I can't seem to reproduce this. Can you re-test on the latest SpongeVanilla?

**Comment by MrOnlineCoder** [comment]
@Aaron1011 tested many times. Re-tested on latest recommended SpongeVanilla build:

- Joined the server
- Put a chest
- Opened it
- Put some items in (optional)
- Teleported myself through console
- GOTCHA! Exception. 

Also, I have written a dummy plugin with just 1 command, that would teleport myself 10 blocks away. Teleporation code:

> player.setLocation(player.getLocation().add(0, 10, 0));

Error stack trace:

	Exception while updating neighbours
	 net.minecraft.util.ReportedException: Exception while updating neighbours
	 at org.spongepowered.common.event.tracking.PhaseTracker.notifyBlockOfStateChange(PhaseTracker.java:528) ~[PhaseTracker.class:1.12.2-7.1.0-BETA-33]
	> 	at net.minecraft.world.WorldServer.func_175685_c(SourceFile:2645) ~[oo.class:?]
	> 	at net.minecraft.tileentity.TileEntityChest.func_174886_c(SourceFile:286) ~[avl.class:?]
	> 	at net.minecraft.inventory.ContainerChest.func_75134_a(SourceFile:68) ~[afv.class:?]
	> 	at net.minecraft.entity.player.EntityPlayerMP.func_71128_l(SourceFile:887) ~[oq.class:?]
	> 	at net.minecraft.entity.player.EntityPlayerMP.func_71053_j(SourceFile:872) ~[oq.class:?]
	> 	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractInventoryCloseEvent(SpongeCommonEventFactory.java:967) ~[SpongeCommonEventFactory.class:1.12.2-7.1.0-BETA-33]
	> 	at net.minecraft.entity.player.EntityPlayerMP.closeInventory(SourceFile:3982) ~[oq.class:?]
	> 	at net.minecraft.entity.Entity.setLocation(SourceFile:4627) ~[vg.class:?]
	> 	at com.mronlinecoder.tptest.TPTest.execute(TPTest.java:41) ~[TPTest.class:?]
	> 	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-7.1.0-BETA-33]
	> 	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-7.1.0-BETA-33]
	> 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-7.1.0-BETA-33]
	> 	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
	> 	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(SourceFile:382) [nz.class:?]
	> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:350) [nz.class:?]
	> 	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
	> 	at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
	> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
	> Caused by: java.lang.NullPointerException
	> 	at org.spongepowered.common.event.tracking.phase.packet.PacketState.associateNeighborStateNotifier(PacketState.java:99) ~[PacketState.class:1.12.2-7.1.0-BETA-33]
	> 	at org.spongepowered.common.event.tracking.phase.packet.PacketState.associateNeighborStateNotifier(PacketState.java:57) ~[PacketState.class:1.12.2-7.1.0-BETA-33]
	> 	at org.spongepowered.common.event.tracking.PhaseTracker.notifyBlockOfStateChange(PhaseTracker.java:511) ~[PhaseTracker.class:1.12.2-7.1.0-BETA-33]
	> 	... 18 more
	


And, another interesting fact, that native /tp command works like a charm, no errors. (in Nucleus it's /tpnative)

**Comment by Aaron1011** [comment]
@MrOnlineCoder: Ah, my bad. I meant the latest build (`1.12.2-7.1.0-BETA-45`), not the latest recommended build.

**Comment by MrOnlineCoder** [comment]
Tested on lasted build BETA-47. Nucleus /tppos, /tp commands work good, no errors. But my test plugin (code line listed in previous comment) crashed the server!

Crash report: https://gist.github.com/MrOnlineCoder/3e3b0ce16316110e02ae1e2876994035

**Comment by Aaron1011** [comment]
Can you paste the full source for your test plugin?

**Comment by MrOnlineCoder** [comment]
Yep, here you are: https://gist.github.com/MrOnlineCoder/ccf3a029b4b2c39cf76de8541ca61072

**Comment by MrOnlineCoder** [comment]
Wow, I have noticed that I return null in my command executor! Sorry, now everything works like a charm.
