### ISSUE TITLE
Disable Tab Complete implementation

### ISSUE THREAD

**Issue by seema84** [SpongePowered/Sponge#192]
An option to disable the Tab Complete would be really good. (to prevent stealing from plugins)

**Comment by TheDoctorsLife** [comment]
Instead of completely disabling it, maybe an option on how many letter have to already be typed.
Eg. with the setting on 3 /he TAB would do nothing but /hel TAB would autocomplete to /help.

**Comment by seema84** [comment]
preferably both :-)

**Comment by kenzierocks** [comment]
I'm confused what you mean by stealing from plugins, could you elaborate?

**Comment by seema84** [comment]
Yes, with Tab Complete everyone can see all the commands and thereby acknowledge the plugins.

**Comment by kenzierocks** [comment]
That's not true, vanilla limits by permission and I think we do too.

**Comment by seema84** [comment]
Hm, on Bukkit is it.

**Comment by boformer** [comment]
This PR adds permission checks to the TAB completer: https://github.com/SpongePowered/SpongeAPI/pull/487

When it is merged, the issue should be fixed.
