### ISSUE TITLE
UseItemStackEvent.Finish wrong return type of the method getItemStackInUse

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Sponge#1923]
- SpongeForge version: spongeforge-1.12.2-2690-7.1.0-BETA-3110
- Java version:  1.8
- Operating System: Ubuntu 17

> Get exactly one piece of any consumable item
> Eat it. 
> ItemStackSnapshot itemStack = event.getItemStackInUse(); returns itemstack of air, instead itemstack of type which was recently consumed. 

- The method returns appropriate value if the consumed item was not last in the stack.

```
    	@Listener(order = Order.LATE)
	public void onItemConsumerFinish(UseItemStackEvent.Finish event,
									 @Root(typeFilter = Player.class) Player player) {
		ItemStackSnapshot itemStack = event.getItemStackInUse();
		if (event.getItemStackInUse().getType() == ItemTypes.AIR)
			throw new IllegalStateException("There shouldnt be air");
```

**Comment by gabizou** [comment]
Do you have a stack trace to kinda see where and how this is happening? Preferably the crash should provide some more insight as to the phase contexts in use and being unwound.

**Comment by Faithcaio** [comment]
Its probably the "correct" ItemStack but its quantity was reduced to 0 by Minecraft. 
We just have to create a copy before that is done.

**Comment by NeumimTo** [comment]
@gabizou What do you mean? Its not crashing, i never siad its crashing.

**Comment by Aaron1011** [comment]
This is fixed in the latest SpongeForge and SpongeVanilla.
