### ISSUE TITLE
ItemStack does not deserialize from DataContainer correctly

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#1924]
```java
ItemStack stack = ItemStack.of(ItemTypes.DIAMOND, 1);
DataContainer container = DataContainer.createNew();
container.set(DataQuery.of("Item"), stack);
```
If one were to call
```java
container.getObject(DataQuery.of("Item"), ItemStack.class)
```
, they would end up with an empty `Optional`. But if one instead called
```java
ItemStack.builder().fromContainer(container.getView(DataQuery.of("Item")).get()).build()
```
there would be no issues and it would deserialize correctly.

**Comment by gabizou** [comment]
Try `container.getSerializable(DataQuery.of("Item"), ItemStack.class)`.

It does explain the differences in the [javadocs](https://github.com/SpongePowered/SpongeAPI/blob/d5f1171eb1ede4fe12efe731271eb3ad5a7cf48d/src/main/java/org/spongepowered/api/data/DataView.java#L501-L553)

**Comment by pie-flavor** [comment]
It makes no sense whatsoever that there are separate methods for these things.

**Comment by gabizou** [comment]
It makes sense when you consider the evolution of the class. DataSerializable predates DataTranslators, so getSerializable was one of the first few concrete getters of DataView. 

Could it be improved? Sure. Am I going to clean it up now? No. Maybe when I get around to class generation for custom data.
