### ISSUE TITLE
Cataloged class static final field injection

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1939]
Current injection mechanism into `CatalogedBy` classes depends on access transformers, why not to do this with reflection api?

Profits: less at config lines

**Comment by XakepSDK** [comment]
Also, it was confusing for me, when i made my own registry

**Comment by liach** [comment]
reflection is slow and has a ton of lines.

**Comment by ryantheleach** [comment]
Considering the impedence mis-match from https://github.com/SpongePowered/SpongeForge/issues/2221 not running access-transformers over the extra plugin directories.

We may want to consider allowing a fallback population method, or running access-transformers over the plugins directory.

**Comment by ImMorpheus** [comment]
Plugin provided catalogs are now populated correctly. See https://github.com/SpongePowered/SpongeCommon/pull/2223
