### ISSUE TITLE
Clean up player respawn code

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Sponge#1943]
Currently, there are three different methods where we send an `SPacketRespawn` (four once https://github.com/SpongePowered/SpongeCommon/pull/1926 is merged):

* `EntityUtil#transferPlayerToDimension`
* `EntityUtil#changeWorld`
* `MixinPlayerList#recreatePlayerEntity`

Sending a `SPacketRespawn` requires sending a slew of other packets, from updating the client weather, to setting the client permission level. 

These methods represent an enormous amount of duplicated code. If any one methods falls out of sync with the other, hard-to-reproduce issues like https://github.com/SpongePowered/SpongeCommon/issues/1923 result.

The common code from these methods needs to be factored out, with any deviations from Vanilla's respawn code clearly documented.

**Comment by Zidane** [comment]
This has been sorted out a long time ago. Especially on 1.16.5+
