### ISSUE TITLE
EventContextKeys.USED_ITEMS is no longer included in context for ChangeBlockEvent.Break

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#1945]
**I am currently running**
- SpongeForge version: 3195
- SpongeVanilla version: 64

**Issue Description**
Previously, `EventContextKeys.USED_ITEM` was included in the event context for `ChangeBlockEvent.Break` when the event was triggered directly by a player breaking a block. This is now completely missing as of SpongeForge 3133.

I suspect [this commit](https://github.com/SpongePowered/SpongeCommon/commit/aec4b7ab476c5186c5d0abba865fba77063b0f04) is the culprit for the issue.

**Comment by Aaron1011** [comment]
Fixed in the latest SpongeForge.
