### ISSUE TITLE
PlayerAdvancements loop - performance loss

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/Sponge#1948]
**I am currently running**
_Not running very latest simply because I support recommended builds.... unless advised against._
- SpongeForge version: 3171
- SpongeVanilla version: N/A
- Java version: 8
- Operating System: CentOS 7

- Plugins/Mods: https://timings.aikar.co/?id=6063fe6734464f36969cb0df11948403

**Issue Description**
~About 40 players got logged out, no errors in console left. My sampler triggered a .nps report before as the spike built, and managed to catch:
![image](https://user-images.githubusercontent.com/18584380/41515618-e007363a-727d-11e8-8541-a363cc70f631.png)
![image](https://user-images.githubusercontent.com/18584380/41515623-e743fffa-727d-11e8-9624-18eecfc68e8f.png)

I am not sure I _can_ reproduce this, but here's the report anyways: 
https://cdn.discordapp.com/attachments/253422932070629376/457999810080014336/spike-62252-2330103392.nps

**Comment by bloodmc** [comment]
@Cybermaxke can you take a look at this?

**Comment by XakepSDK** [comment]
I saw stacktrace like this once. Can confirm for at least older builds.

**Comment by Cybermaxke** [comment]
I made a PR https://github.com/SpongePowered/SpongeCommon/pull/1968 with a few fixes related to advancements. However I don't know if one of them would fix this issue.

**Comment by bloodmc** [comment]
This was fixed with PR #1968 which has been merged.

**Comment by Rasgnarok** [comment]
Heads up, I am running 3392 (old, I know), but I just had it happen again. I'd like to have this opened, considering it's hard to reproduce, but definitely does occur even after blood's PR. Indeed the build I run was released according to minecraftforge site as  `7.1.0-BETA-3392 | 2705 | 08/10/18 10:48 PM`, and the PR dates a month before it.

As for testing with a newer version, I'll update my production eventually once I can safely bump Forge versions. For now however, consider this unresolved (attachment includes the sampler that reported it).
[stall-2019-01-05_06.58.35-2.txt](https://github.com/SpongePowered/SpongeCommon/files/2729981/stall-2019-01-05_06.58.35-2.txt)

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/50730232-9ea3d300-1116-11e9-94dd-c25e6d7c250a.png)

**Comment by liach** [comment]
that is how vanilla works when you have a very deep advancement tree. it checks if one of its ancestors is invisible.
