### ISSUE TITLE
SlotIndex decreased by one for transform()ed slots on a custom inventory

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#1950]
With [this](https://gist.github.com/pie-flavor/4dc2e24535ffb16f4e7ed0ae9bc8f3ca) test plugin, you can see that for any custom inventory, all slot indices are correct if you use the untransformed slot, but all slot indices (for the custom inventory half of the screen only) are decremented by one. This results in the second slot being index 0, third slot being index 1, etc., and the first slot simply does not have a SlotIndex property at all.
Custom inventory here means an inventory created using `Inventory.builder()`. It does not matter whether the `InventoryArchetype` is `CHEST` - an existing hopper GUI will have correct transformed slots, a custom hopper GUI will not.

**Comment by Faithcaio** [comment]
try again with latest
