### ISSUE TITLE
Unable to set experience after death

### ISSUE THREAD

**Issue by nihiluis** [SpongePowered/Sponge#1956]
**I am currently running**

I dont use latest version because update is annoying. i have this bug for a long time.
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2996.jar
- SpongeVanilla version: 
- Java version: 8_171
- Operating System: debian yeezy

- Plugins/Mods:
only custom and worldEdit

**Issue Description**
```
        player.offer(Keys.EXPERIENCE_LEVEL, level)
        player.offer(Keys.EXPERIENCE_SINCE_LEVEL,
                (experiencePercentage * player.get(Keys.EXPERIENCE_FROM_START_OF_LEVEL)
                        .orElse(0).toFloat()).toInt())
```

I use this code and it works. Then I go die and suddenly it doesnt do anything anymore... can someone reproduce htis? Normally it sets the Level to a fixed one and exp to fixed. after death no effect anymore. I call this every 20 ticks.

**Comment by ST-DDT** [comment]
Do you keep the reference to the player (entity) the whole time or do you get it new on each call of your code? (Aka is your `player` reference stored in a field?)

Ref: [Docs: Storing References](https://docs.spongepowered.org/stable/en/plugin/practices/bad.html?highlight=player#storing-references)

**Comment by nihiluis** [comment]
Seems to be my error then sorry. I do. Will reopen if it wont fix it.

**Comment by nihiluis** [comment]
Could be very useful to throw an exception though. The player object potentially being useless after death is non intuitive.

**Comment by ST-DDT** [comment]
Yes, on one hand an Exception would be handy, but it would also cost performance if you always have to check whether the instance is still valid. And since you are not supposed to store references to it anyway there is no need for this check IMO. But some hint on the class itself might be useful.

**Comment by ST-DDT** [comment]
Would something like https://github.com/SpongePowered/SpongeAPI/issues/1853 help you?

**Comment by nihiluis** [comment]
Yeah I think that's a good and easy solution.

I dont think performance here is really an argument, when you enforce the use of `Optional` everywhere else. Precisely for the reason that a value might be invalid. Which it is here apparently. This might even occur without saving references like in the doc. Imagine a delayed task which sets the exp to an arbitrary value. This will do nothing if the player dies. How does my plugin know that? Apparently you have to use UUID everywhere which is both unergonomic and has worse performance when you have to call `Sponge.getServer().getPlayer(uuid)` often.
