### ISSUE TITLE
Incompatible with IC2 workbench

### ISSUE THREAD

**Issue by Tollainmear** [SpongePowered/Sponge#1966]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3206
- SpongeVanilla version: 
- Java version: Java 8
- Operating System:windows server 2016

**Issue Description**
The console was filled with  
>[Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task

check it on gist [here](https://gist.github.com/Tollainmear/9c3b02cafa6cc343a762520be568c70b)

(It seems like sponge has problem with IC2 work bench)

and the entirely log is [here](https://gist.github.com/Tollainmear/e4dd80733fb8a5e4a09b80262bc449d3)(It's just all the same error log, repeating)

- Plugins/Mods:
  - Mods (62): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, Advanced Machines, Advanced Solar Panels, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, Avaritia, Avaritia Tweaks, B.A.S.E, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Environmental Tech, Fast Leaf Decay, Forestry, Gravitation Suite, Immersive Engineering, Immersive Petroleum, Immersive Tech, IndustrialCraft 2, Infernal Mobs, InstantUnify, Iron Chest, Just Enough Items, LagGoggles, MCMultiPart, MTLib, Mantle, Mekanism, MekanismGenerators, MineTweakerRecipeMaker, Mod Tweaker, NuclearCraft, OnlinePictureFrame, Redstone Flux, TOP Addons, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, Tri-Addon Controller, Universal Modifiers, Valkyrie Compat, Valkyrie Lib, WorldEdit
  - Plugins (31): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BungeeTabListPlus-SpongeBridge, CarrotShop, CatClearLag, ClearMob, CommandSigns Reloaded, CommandSync, CommandsDispatcher, EasyScoreboards, EconomyLite, GriefPrevention, Holograms, Inventory Sync, KaroglanSignEditor, LuckPerms, MMCReboot, Nucleus, PixelAutoMessages, PlaceholderAPI, ProjectCore, RankUpper, ServerListPlus, Socket4MC, StackBan, Title Broadcaster, UltimateChat, UniversalMarket, VirtualChest

**The picture below **
![image](https://user-images.githubusercontent.com/25898067/42087497-f05eaa82-7bc8-11e8-9e80-16b86d0bdb08.png)

**Comment by Faithcaio** [comment]
Can't really see why this happens.
I added more Debug Info when the error happens.
Please try again with latest build. (should be 3243 when its out)

**Comment by Tollainmear** [comment]
Ok, I'll pay attention to that, thanks for reply.

**Comment by Tollainmear** [comment]
Problem solved, thanks!  🌹
