### ISSUE TITLE
UserStorageService#getFromStoredData creates new user

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Sponge#1970]
Currently, [`UserStorageService#getFromStoredData` unconditionally creates and caches a new `SpongeUser`](https://github.com/SpongePowered/SpongeCommon/blob/6af67f75704096f65c24f84e7132d78316243a50/src/main/java/org/spongepowered/common/service/user/UserDiscoverer.java#L219), even if it ends up returning `null`. As a result, calling `UserStorageService#get` twice on the same `GameProfile` will always return a `User` on the second call, even if it returned `Optional.empty()` the first time.

`getFromStoredData` should cache the non-existance of a stored data file separate, and only create a user if stored data actually exists.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/fbfebe53258ed9323ef29ecb1c7c975240efc20c
