### ISSUE TITLE
End Platform is not created during EntityUtil.handleDisplaceEntityPortalEvent

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Sponge#1975]
- SpongeForge version:   3261 though it effects early versions too.

**Problem:**  End Platform isn't created when player is teleported INTO DIM1

**Cause:**  https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/entity/EntityUtil.java#L412

**Diagnosis:**  entityIn.getLastPortalVec is null but there are other cirsumstances that this can be null but still be allowed to enter the proceeding method.  If this method is skipped then teleporter.placeEntity is never called, thus the createEndPortal method is never called.

**Fix:**  Change line 412 to this:
if (!teleporter.isVanilla() || entityIn.getLastPortalVec() != null || (entityIn.dimension != 1 && toWorld.provider instanceof WorldProviderEnd)) {

**Comment by ryantheleach** [comment]
@Dockter You were concerned about the location of the player / platform in Discord, can you check the location of the platform / player after teleportation?

For reference:
https://minecraft.gamepedia.com/The_End
"They will appear at X=100, Y=49, Z=0, facing west (negative X) on top of a 5×5×1 obsidian platform,"

**Comment by Dockter** [comment]
**Update**, the above fix is inappropriate because it needs to check both the from and to world providers and not rely on the dimension ID's.

**Comment by Dockter** [comment]
**Recommend this:**
*  if (!teleporter.isVanilla() || entityIn.getLastPortalVec() != null || (!(fromWorld.provider instanceof WorldProviderEnd) && toWorld.provider instanceof WorldProviderEnd)) {
