### ISSUE TITLE
AffectItemStackEvent transactions cancel item dupe

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1976]
**I am currently running**
- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-75
Repro code:
```java
@Listener
public void onStackAffect(AffectItemStackEvent event) {
    event.filter(itemStack -> itemStack.getType() != ItemTypes.CRAFTING_TABLE);
}
```
Repo steps:
1. Make plugin with code above
2. Fill crafting grid with right-stay-click
2.1. Take any planks
2.2. Place mouse on crafting grid slot
2.3. Press and hold RMB
2.4. Fill 2x2 square with held RMB
2.5. Release RMB
2.6. Game will put 1 extra plank in your cursor

@Faithcaio

**Comment by Faithcaio** [comment]
Because you did not cancel the cursor-transaction...
You either have to cancel the entire event. Or check for `InteractInventoryEvent` and cancel the cursor transaction there.

**Comment by XakepSDK** [comment]
If i use just rmb without hold, everything works fine.

**Comment by Faithcaio** [comment]
Then that is wrong.
The event should not just automatically cancel the cursor-transaction.

**Comment by Faithcaio** [comment]
Seems like a bug in the ClickInventoryEvent.Drag impl. Its adding items back to the cursor for each canceled slot-transaction. Ignoring the fact that there are possibly additional transactions in crafting inventories.

Btw if you are trying to prevent from crafting a specific item there is 
`CrafItemEvent.Preview` or `CraftItemEvent.Craft` for that.

**Comment by XakepSDK** [comment]
This abstraction level allows me to not duplicate code for other events.

**Comment by XakepSDK** [comment]
Also, if i cancel event, crafting output will contain result, but crafting grid will be empty.

**Comment by Faithcaio** [comment]
Should be fixed in latest.

**Comment by XakepSDK** [comment]
Fixed partially.
Crafting grid cleared, planks returned to cursor, but output slot contains crafted item.
Made with hold-rmb-click:
![image](https://user-images.githubusercontent.com/141554/42545110-e9cef782-84f4-11e8-883a-22c1d26b5a58.png)

I can take result
![image](https://user-images.githubusercontent.com/141554/42545078-bca6d248-84f4-11e8-820f-659d7b6af719.png)

Can take result

**Edit:** (ryantheleach) replaced Puush links with images directly pasted into github, Puush goes down randomly, and has served malware in the past.

**Comment by Faithcaio** [comment]
Not sure what you're doing now.
With the code above the planks are not affected.

**Comment by XakepSDK** [comment]
I'm cancelling `AffectItemStackEvent`, planks are placed using rmb-hold.
1. Drag transaction cancelled
2. Planks gone to cursor
3. Crafting table appeared in output slot

**Comment by Faithcaio** [comment]
Try again with latest

**Comment by XakepSDK** [comment]
It works!
