### ISSUE TITLE
Crash during startup after latest SF Update

### ISSUE THREAD

**Issue by dogboy21** [SpongePowered/Sponge#1981]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3272 + SpongeBootstrap
- Java version: 1.8.0_144
- Operating System: Debian 9

- Plugins/Mods: https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12 (no mods/plugins were loaded during the crash as it happens during Sponge mod initialization)

**Issue Description**

The server crashes during startup after updating to the latest SF version.
Crash Report: https://pastebin.com/nk9u0zP9

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/e19bebe741a5bbbeca2ce485e4b0702d142a3bc6
