### ISSUE TITLE
Unreliability retrieving Player from Inventory Open/Close

### ISSUE THREAD

**Issue by Xemiru** [SpongePowered/Sponge#1985]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.10-BETA-3206
- Java version: 1.8.0_144
- Operating System: Windows 7

**Issue Description**
From the comment block in [this commit](https://github.com/Xemiru/Boxboy/commit/85ac16d40dbc9da8732772a00524fd291d6965e5#diff-138dfa44bb720944b565a83abba747d1R302),

_"Both the Open and Close inventory events have no reliable way of retrieving the target player that was involved with the action. The affected player is not always present in the cause stack. Until reliability is resolved, [these listeners are] replaced with us simply tracking menu opens and closes ourselves in a less efficient manner through tracking which players get Menus opened for them and then constantly asking whether or not they still even have it open."_

Note the solution that was used in this commit, where I chose to depend on a monitor scheduler task instead of events -- a much less intuitive way of accomplishing the goal.

Specifically, there're two cases where the affected Player doesn't appear in the cause stack for the `InventoryInteractEvent.Open` and `InventoryInteractEvent.Close` events.
- .. when `Player#openInventory` is called inside a scheduler task
- .. when the Player isn't the direct cause of an `InventoryInteractEvent.Close`

The current main way to grab the affected player is through the Cause stack, but it being possible to not be present in certain cases makes it unreliable -- especially for inventory events who're sensitive to being immediately responded to with other inventory calls where the best possible workaround is to push it through the scheduler to occur on the next possible tick. Sponge has its own way of detecting this sensitivity and delaying the call on its own, [_which pushes it through the scheduler itself,_](https://github.com/SpongePowered/SpongeCommon/blob/5ee424bd843fe4528f00550259cd4a1dfe0049c4/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L752) but somehow doesn't seem to drop the Player from the stack (and I've no idea how, presumably from messing with the stack frame, though doing this on your own really shouldn't be necessary and not everyone will do it, meaning events from other plugins would still be a potential failure point). This sensitivity check also poses other issues of its own (see #1984).

An argument against this in favor of it being intended behavior was that the player did not intend to open the menu themselves through normal means, so they should not be in the cause stack, in which case..
- .. why does `Player#openInventory` still place the Player in the cause stack outside of a scheduler task?
- .. why is there then no consistent way to grab the affected Player if they aren't always present in the cause stack?

The proposed solution is to **add methods to retrieve the affected player in those two events,** [as other events seem fine with including their targets](https://jd.spongepowered.org/7.0.0/org/spongepowered/api/event/entity/TargetEntityEvent.html#getTargetEntity--).

You can test these interactions using the provided snippets.

[InventoryIssues.java](https://gist.github.com/Xemiru/9afc43bd3f254eea4fba0ce91bc7a3dc) / [JAR File](https://gist.github.com/Xemiru/9afc43bd3f254eea4fba0ce91bc7a3dc/raw/68bda23e90e845e99caaeee3ae4750aecd64749b/inventoryissues.jar)
(JAR file suspiciously big? This file does also have the code for testing #1984 with the `@Plugin` annotation commented out.)

* Test instructions are in the code's comments.

**Comment by XakepSDK** [comment]
If you close your inventory via plugin, source(first object in cause stack) should be plugin, not player.

**Comment by Xemiru** [comment]
Source object isn't relevant to this issue -- especially when you can simply ignore the source and retrieve it through `Cause.first(type)`. It's focus is the unreliability of grabbing the affected Player instance through what's currently the only way to do so: the Cause stack. The goal of this issue is to correct this unreliability.

The proposed solution asks for either the Player to always be present in some form, or have a different consistent way of grabbing the Player, since having the Player in the Cause stack without them being an actual reason goes against the intentions of the Cause class. This could be done through EventContext or just adding a `getAffectedPlayer()` method in the event class.

There's a workaround for the open event, where you can iterate through the online Players and compare the result of `getOpenInventory()` to the event's `getTargetContainer()`, but this isn't possible for close event. [The workaround I used for the close event is much bigger than a simple comparison and neither that or the open event iteration should be necessary.](https://github.com/Xemiru/Boxboy/commit/1efb68a57e647ec23ab7d6923791f02369888f84#diff-138dfa44bb720944b565a83abba747d1R347)

**Comment by XakepSDK** [comment]
@Faithcaio tl;dr for you:
Sometimes viewer isn't present in cause / context.
Also, inventory open event isn't fired for players own inventory, is it ok?
Pure tests output:
```
<Xakep_SDK> test1
Event: class org.spongepowered.api.event.InteractInventoryEvent$Open$Impl
Cause[Context=Context[], Stack={Plugin{OmmitedForReadability}, EntityPlayerMP['Xakep_SDK'/392, l='world', x=252.88, y=76.00, z=197.66]}]
Event: class org.spongepowered.api.event.InteractInventoryEvent$Close$Impl
Cause[Context=Context[], Stack={EntityPlayerMP['Xakep_SDK'/392, l='world', x=252.88, y=76.00, z=197.66]}]

<Xakep_SDK> test2
Event: class org.spongepowered.api.event.InteractInventoryEvent$Open$Impl
Cause[Context=Context[], Stack={Plugin{OmmitedForReadability}}]
Event: class org.spongepowered.api.event.InteractInventoryEvent$Close$Impl
Cause[Context=Context[], Stack={EntityPlayerMP['Xakep_SDK'/392, l='world', x=252.88, y=76.00, z=197.66]}]

<Xakep_SDK> test3 [player inv on E key]
test3
Event: class org.spongepowered.api.event.InteractInventoryEvent$Close$Impl
Cause[Context=Context[], Stack={Plugin{OmmitedForReadability}, DedicatedServer}]

<Xakep_SDK> test4 [player inv on E key]
test4
Event: class org.spongepowered.api.event.InteractInventoryEvent$Close$Impl
Cause[Context=Context[], Stack={Plugin{OmmitedForReadability}}]
```
Test code:
https://gist.github.com/XakepSDK/e8aea26a14c718b99f12cd4b07c5b88b

**Comment by Faithcaio** [comment]
> Also, inventory open event isn't fired for players own inventory, is it ok?

Not ok. But the Client won't tell us so we do not know.

**Comment by Faithcaio** [comment]
fyi in API8 `Container` will have `Optional<Player> getViewer();`

**Comment by Xemiru** [comment]
Good to know. I tried to check if containers were unique to players while messing with this issue, but `getViewers()` was unimplemented. Though from the fact that it's returning an optional, it seems like the container won't keep the player if it's closed (in which case it doesn't help resolve the issue for the close event)?

**Comment by gabizou** [comment]
I'd definitely give @bloodmc's testing jars a try lately as he's been hammering away at forge events syncing, which I'm almost sure he's had to resolve some packet issues to potentially resolve this issue (maybe? I don't know for sure). Not sure which jar is needed or which one is for which, but I'll let him make that statement.

**Comment by Faithcaio** [comment]
After checking again: The player is not actually ever removed from the Container.
So I'll change it to return Player instead of Optional.
Also `isOpen():boolean` to check if the container is still open.
