### ISSUE TITLE
Inventory contents are not dropped when broken on TE update

### ISSUE THREAD

**Issue by SquidDev** [SpongePowered/Sponge#1986]
- SpongeForge version: Development environment with SpongePowered/SpongeForge@fb9f996117891efbc38246f1a87b8b7b763296e0. Also tested on 1.12.2-2705-7.1.0-BETA-3270.
- Java version: 1.8.0_151
- Operating System: Windows 10
- Plugins/Mods: None

When breaking a block, inside a TileEntity's `update` method, any items dropped using `InventoryHelper.dropInventoryItems` are discarded (such as from `BlockChest`). From what I can tell, they are added to `PhaseContext.getBlockItemDropSupplier` inside `ContainerUtil.performBlockInventoryDrops`, but then never consumed.

It's possible there are other cases where this also occurs. I've tried to investigate but I'm afraid I haven't been able to figure much out.

### Reproduction code/steps
Firstly, add this method to `MixinTileEntityFurnace`. You can also do it in a dedicated TE, but this was easier to test with.

```java
@Inject(method = "update", at = @At("HEAD"))
private void onUpdate(CallbackInfo info) {
    if (world.isRemote || world.playerEntities.isEmpty()) return;

    BlockPos pos = getPos().offset(EnumFacing.NORTH);
    IBlockState state = world.getBlockState(pos);
    if (state.getMaterial() == Material.AIR) return;

    EntityPlayer player = world.playerEntities.get(0);
    TileEntity tile = world.getTileEntity(pos);

    state.getBlock().onBlockHarvested(world, pos, state, player);
    if (world.setBlockState(pos, Blocks.AIR.getDefaultState(), world.isRemote ? 11 : 3)) {
        state.getBlock().onBlockDestroyedByPlayer(world, pos, state);
    }
    state.getBlock().harvestBlock(world, player, pos, state, tile, ItemStack.EMPTY);
}
```

 1. Place a chest in the world and fill it with items
 2. Ctrl+Click the chest to pick it up with NBT.
 3. Place this chest and break it: confirm that items are dropped
 4. Place a furnace.
 5. Place the chest north of this furnace. Confirm is is broken, with only a chest item dropping (but not its contents)

**Comment by bloodmc** [comment]
@SquidDev test with latest SF which can be found here
http://files.minecraftforge.net/spongepowered

**Comment by SquidDev** [comment]
@bloodmc I've tested on the latest commit in a development environment with test plugins/mods disabled. I'm happy to set up with an official build as well, but I don't believe it'll make any difference.

**Comment by bloodmc** [comment]
OK expect a fix soon.

**Comment by Aaron1011** [comment]
Fixed in the latest SpongeForge.

**Comment by SquidDev** [comment]
Thank you!
