### ISSUE TITLE
Runaway Phase Errors on Switching Phase

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/Sponge#1988]
**I am currently running**

- SpongeForge version: 3291
- SpongeVanilla version: N/A
- Java version: 8
- Operating System: CentOS 7

- Plugins/Mods: https://timings.aikar.co/?id=10b048d7ff6a4667acc46b1b432f7377

**Issue Description**
Getting massive spam on: https://gist.github.com/Rasgnarok/b97fff5182ff108d79aa4c3989aa887b . Shutting down the server gives this: https://gist.github.com/Rasgnarok/b97fff5182ff108d79aa4c3989aa887b , uncertain if related.

**Comment by gabizou** [comment]
Need the full log. There's some leftover phase states on the stack that somehow didn't get cleaned up, which usually print out an error when that happens. Also, it looks like the tasks are from buy craft. Could you try uninstalling that and trying again?

**Comment by Rasgnarok** [comment]
I do not think it is related to Buycraft per se, as I seem to get it with other scheduling mods and plugins - Pixelmon seems to suffer similarly. Here's the log from one of these crashes.
[2018-07-12-1.log](https://github.com/SpongePowered/SpongeCommon/files/2191499/2018-07-12-1.log)

**Comment by Zidane** [comment]
There have been massive changes to the tracker since this time. Closing as this would need a complete re-test.
