### ISSUE TITLE
Can't get EquipmentSlotType from EquipmentSlot

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#1993]
**I am currently running**

```
SpongeVanilla
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-9cb5cb8c
    SpongeVanilla: 1.12.2-7.1.0-BETA-59
```

**Issue Description**

```
if (slot instanceof EquipmentSlot) {
  Optional<InventoryProperty> optProperty = slot.getInventoryProperty(EquipmentSlotType.class);
}
```

`optProperty` is always empty. I don't think that's right.

My current workaround is calling `boolean slot.isValidItem(EquipmentType)` against every type I am interested in to find out what is supported by the slot.

**Comment by Faithcaio** [comment]
try again with latest

**Comment by randombyte-developer** [comment]
Half fixed: When swapping items to the offhand via `F` it works. But when directly manipulating the offhand or the armor slots within the inventory GUI it is still an `Optional.empty()`.

**Comment by JBYoshi** [comment]
I was looking at this earlier, and it seems that the parent `Inventory` is mismatched. `slot.parent()` returns the `Container` object. It should be returning the `EquipmentInventory`.

**Comment by Faithcaio** [comment]
@JBYoshi No slots you get from an event with Container always have the Container as parent.
E.g. to be able to compare `SlotIndex` (which is defined by the parent).

**Comment by JBYoshi** [comment]
The `EquipmentTypeProperty` is only defined for the slot within the `EquipmentInventory`. So without the `EquipmentInventory` you can’t get the `EquipmentType`. For properties like that I think it would be better for them to simply be bound to the slot instead of to both the slot and parent inventory.

**Comment by Faithcaio** [comment]
> The EquipmentTypeProperty is only defined for the slot

That is wrong. 
InventoryProperties are defined only on the parent never on the slot. (there are exceptions for "root" inventories e.g. to get the display name of a chest)
As such you can get the `EquipmentTypeProperty` on other inventories than `EquipmentInventory` as long as there is a lens that provides it.

**Comment by Faithcaio** [comment]
In this case calling. `slot.transform()` returns the slot with the player-inventory as parent which will then have the property on it.

**Comment by Faithcaio** [comment]
try again with latest

**Comment by randombyte-developer** [comment]
Works, thanks!
