### ISSUE TITLE
EntityTickPhase PhaseState errors on brandnew first-start server api8.0.0

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1997]
**I am currently running**

- SpongeForge version: 
- SpongeVanilla version: spongevanilla-1.12.2-8.0.0-BETA-432 (latest build as of writing report)
- Java version: jre1.8.0_171
- Operating System: Win7

- Plugins/Mods:
None - pure raw brand-new first start default generated server 

**Issue Description**
During startup generating map, phase-state error occured, EntityTickPhase on a HORSE 
Similar phase error after 1 min exploration on the rebooted server

Pastebin of log entries here:  https://pastebin.com/mKGJt9Ua

I am not running a spForge server to replicate phase-state errors, but assume that Common is the location for the reports.   If additional phase-state errors found on my vanilla server need to be posted in only vanilla, or must require me to run a spforge server and also reproduce before posting, please instruct as to preference for posting requirements in the future.

**Comment by XakepSDK** [comment]
Don't use api 8

**Comment by gabizou** [comment]
Don't bother using API 8 builds at this point in time. With 1.13 about to release, the API is going to break in massive ways where a majority of our implementation (read mixins, not actual system rewrites, like the PhaseTracker) is going the way of the dodo. Not to sound rude, but this sort of phase issue is kinda meaningless until we do have to rewrite this particular mixin for 1.13. This isn't an issue on stable, so I'd suggest using that.
