### ISSUE TITLE
Cannot create scoreboard prefix consisting entirely of color codes

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#2001]
```java
Player player = Sponge.getServer().getPlayer("pie_flavor").get();
Team team = Team.builder().name("test").prefix(TextSerializers.FORMATTING_CODE.deserialize("&d").build();
Scoreboard board = Scoreboard.builder().teams(Arrays.asList(team)).build();
player.setScoreboard(board);
team.addMember(player.getTeamRepresentation());
```
This *should* make it so my name is colored pink in all chat messages.
![](https://i.imgur.com/qfU5Wa0.png)
But if I change that `"&d"` to `"&d "`:
![](https://i.imgur.com/gXzJUTu.png)
I can only conclude that empty text is being optimized out here.

**Comment by XakepSDK** [comment]
Well known issue with deserializer.
https://github.com/SpongePowered/SpongeCommon/issues/1504
