### ISSUE TITLE
Redstone does not work the same as normal minercraft

### ISSUE THREAD

**Issue by TherayTharow** [SpongePowered/Sponge#2003]
**I am currently use almura 1.12.2 client, **
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3320
- SpongeAPI version: 7.1.0-SNAPSHOT-8976964
- Java version: 8
- Operating System: win 10

- Plugins/Mods: Dockter's Almura from technics so I have no idea.
it does this on the server and a single player world
**Issue Description**
RedStone Does not work the same as in normal M.C comparators are one thing that is that has this
problem 1 dispenser  with water bucket comparator out the back  should get redstone level of 2 but always get power level of 1 when press button on top of it, it dispenses water and the redstone level should go down to 1 but the power level does not change.

**Comment by ryantheleach** [comment]
For Reference, Vanilla 1.12: https://youtu.be/1Knze5oCjPw

**Comment by ryantheleach** [comment]
Unable to replicate: https://youtu.be/qNP5eP8BMww

Tested on forge-1.12.2-14.23.4.2739-universal.jar with spongeforge-1.12.2-2705-7.1.0-BETA-3206.jar

No plugins or mods, default configuration.

**Comment by phit** [comment]
@ryantheleach that sf version is super old, test on latest

**Comment by phit** [comment]
I retested on 1.12.2-2705-7.1.0-BETA-3322 and it still works.. still, testing on such an old build especially when the issue was made for a way newer build doesn't really help

**Comment by ryantheleach** [comment]
@PowellA12 @phit Apologies, must have hit recommended instead of latest on the download site by accident.
