### ISSUE TITLE
Block capture error on just fresh server

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#2011]
**I am currently running**

- SpongeForge version:
spongeforge-1.12.2-2705-7.1.0-BETA-3326
- Mod list:
https://gist.github.com/XakepSDK/605d4a63a6740766b02411ef26740620
- Plugin list:
No plugins

I just installed forge, started it one time, copied mods from my client and started it again.
Latest.log: https://gist.github.com/XakepSDK/e5c6d0d71c7dcacdc0af702ad9bfa219
Debug.log: https://gist.github.com/XakepSDK/521807afc706baa9c444b0ffe149bc13

**Comment by bloodmc** [comment]
@XakepSDK Is this occuring on latest SF?

**Comment by XakepSDK** [comment]
I'll test this today or tomorrow.

**Comment by XakepSDK** [comment]
Yes.
https://gist.github.com/XakepSDK/01d2dcf397f0ccbfda3b876f5d6bcfcf
Log includes versions and mod/plugin list.

**Comment by XakepSDK** [comment]
More exceptions: now with full startup failure.
Same version, but bit more mods.
https://gist.github.com/XakepSDK/72dd931c35bde04463ff269eb1a7a36f
