### ISSUE TITLE
offline inventory enderchest 

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#2018]
This issue was originally submitted by @02Miki in [SpongePowered/SpongeForge#2281](https://github.com/SpongePowered/SpongeForge/issues/2281).
___
Idk if this is the right section, couldn’t create a new ticket in pull requests; can you add offline inventories for enderchest, like the same thing you did with player inventories

**Comment by Faithcaio** [comment]
I moved the method from `Player` to `User` in API8

Maybe API7 too? @gabizou @Zidane

**Comment by ryantheleach** [comment]
So being on User means the User would already be loaded right? There's no need to make like, an async request or something because they want offline access?

**Comment by Faithcaio** [comment]
For `Player` nothing changes.
For `User` the inventory is loaded lazily when you request it. 
Making changes to it marks it as dirty.
Dirty users are saved eventually but before the player joins.

**Comment by ryantheleach** [comment]
request the user, or request the inventory? If the latter, would it be worth making it async?

**Comment by Faithcaio** [comment]
User nbt is loaded into memory before.

**Comment by gabizou** [comment]
Moving the method from Player to User is still going to be valid, just add a proper override annotation in `Player`.
