### ISSUE TITLE
inventory.offer broken

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#2020]
**I am currently running**

- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-93

I'm iterating over custom inventory, created by my plugin:
```java
Inventory.Builder builder = Inventory.builder()
        .of(InventoryArchetypes.CHEST)
        .property(InventoryTitle.of(title))
        .property(InventoryDimension.of(9, rows))
        .listener(InteractInventoryEvent.class, new CancelListener())
        .listener(ClickInventoryEvent.class, new ClickListener());
if(player != null) builder.withCarrier(player);
this.inventory = builder.build(plugin);
```

I'm trying to set items in empty slots:
```java
for (Inventory inv : inventory.slots()) {
    InventoryTransactionResult offer = inv.offer(emptyItem.getIcon());
    System.out.println("Type=" + offer.getType() +", Replaced=" + offer.getReplacedItems() + ", Rejected=" + offer.getRejectedItems());
}
```
Only first slot item will be replaced.
InventoryTransactionResult is:
https://gist.github.com/XakepSDK/0844bd97a2c7af5fe6a0e410bfcd4397

**Comment by Yeregorix** [comment]
Does `getIcon()` recreates a new `ItemStack` for each call ? Otherwise it's normal because `offer(ItemStack)` consumes the stack.

**Comment by XakepSDK** [comment]
Forgot to close. Already found this yesterday.
