### ISSUE TITLE
Error trying to cancel ClickInventoryEvent

### ISSUE THREAD

**Issue by m1zark** [SpongePowered/Sponge#2022]
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3233
- Java version: Java 8

```java
public void onItemCraft(ClickInventoryEvent event, @First Player player, @Getter("getTargetInventory") Inventory inventory) {
    if (inventory.getArchetype() == InventoryArchetypes.WORKBENCH || inventory.getArchetype() == InventoryArchetypes.ANVIL) {
        event.getTransactions().forEach(slotTransaction -> {
            if(slotTransaction.getOriginal().get(Keys.ITEM_LORE).isPresent()) {
                event.setCancelled(true);
            }
        });
    }
}
```

So I was using this code to block placing items in a workbench or anvil if it had lore, just to stop people from renaming or editing special items. Well the workbench part works just fine, but whenever I try the same item in an anvil the item just disappears and I get the following error.

[https://pastebin.com/LHXpmCJf](https://pastebin.com/LHXpmCJf)

This only happens when I cancel the event, as I can do anything else to the item just fine. I have also tried using newer versions of spongeforge, with the same results.

**Comment by Faithcaio** [comment]
Probably already fixed as I've done work on inventories since. Try with latest. If you are able to reproduce it we will re-open the issue.

**Comment by m1zark** [comment]
[https://pastebin.com/CsruWJrz](https://pastebin.com/CsruWJrz)

Here is the error on the latest version, 3361. It's exactly the same as before. While in the anvil UI, I click on the item in my bar and the item disappears and I get that error in console.
