### ISSUE TITLE
ArmorEquipable getters throw IllegalStateException

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#2024]
**I am currently running**

- SpongeForge version: 1.12.2-2705-8.0.0-BETA-3348:dev
- Java version: 1.8.0_162
- Operating System: Windows 10 x64

**Issue Description**
ArmorEquipable `.getBoots()` `.getLeggings()` `.getChestplate()` and `.getHelmet()` throw IllegalStateException when called on a `Player` with no armor. (I've not tested with other entity types or other getters.)

Stacktrace: https://pastebin.com/Ay0ZbDEd

**How to reproduce**
```java
Player p = chooseRandomPlayerWithNoArmor();
p.getBoots();
p.getLeggings();
p.getChestplate();
p.getHelmet();
```

**Comment by Faithcaio** [comment]
MixinArmorEquipable#getEquipped returns optional for empty items :/ it should not

**Comment by Yeregorix** [comment]
Is it possible to also fix the issue in `bleeding` ? ^^

**Comment by Faithcaio** [comment]
should be..

**Comment by Yeregorix** [comment]
Sorry I didn't watch the good commit. ^^'
