### ISSUE TITLE
Minecart CommandBlock missing manipulators

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/Sponge#2027]
**I am currently running**

- SpongeForge version: bleeding branch (SpogeCommon https://github.com/SpongePowered/SpongeCommon/commit/ad1a7de9a3d3f9d04d591c1c8b2bb98e03b2878b)
- SpongeVanilla version: 

**Issue Description**
Minecart CommandBlock is missing manipulators. 
Ex. place a minecart command block, burn it and try to retrieve IgniteableData or Keys.FIRE_TICKS.

```
@Listener
public void onInteractEntity(InteractEntityEvent event) {
    System.out.println(event.getTargetEntity().toContainer());
    System.out.println("IS PRESENT: " + event.getTargetEntity().get(Keys.FIRE_TICKS).isPresent()); 
}
```

I've found this while working https://github.com/SpongePowered/SpongeCommon/pull/2023, so if I come up with something it will be added to that PR.

**Comment by gabizou** [comment]
As i know the systems in great length, can you test on stable branches instead of bleeding? It’s getting repetitive to keep asking this.

**Comment by ImMorpheus** [comment]
I thought bleeding was synced with stable recently. 

Anyway the problem is also there since `MixinEntityMinecartCommandBlock#supplyVanillaManipulators` is not calling `super#supplyVanillaManipulators`.

https://github.com/SpongePowered/SpongeCommon/blob/dcbf53c72268c79e65280f920d67c19bb71b4e90/src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntityMinecartCommandBlock.java#L51-L53

Apparently this also affects arrows:
https://github.com/SpongePowered/SpongeCommon/blob/dcbf53c72268c79e65280f920d67c19bb71b4e90/src/main/java/org/spongepowered/common/mixin/core/entity/projectile/MixinEntityArrow.java#L83-L85.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/pull/2023. PR pending.
