### ISSUE TITLE
ChangeBlockEvent.Break not fired when block break by water

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2028]
**I am currently running**

- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-93
- Java version: OpenJDK Version "1.8.0_171"
- Operating System: Linux Mint 18.3 Sylvia (Kernel: x86_64 Linux 4.13.0-45-generic)
- Plugins/Mods: Empty (Only one my experimental plugin)

**Issue Description**

The ChangeBlockEvent.Break not fired when block break by water. It's not logical...

**Comment by Zidane** [comment]
@Lignium I believe that @bloodmc elected to only have those fire ChangeBlockEvent.Pre due to performance concerns.

Granted this was years ago. Performance has came a long way. @bloodmc we may be able to have this again.

**Comment by bloodmc** [comment]
Definitely not going to make water fire break as it is very spammy and the event itself would require block snapshots which would hurt performance. Use `ChangeBlockEvent.Pre` for water and check the locations affected.
