### ISSUE TITLE
sponge -g/-w reload not working

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/Sponge#2036]
**I am currently running**

- SpongeForge version: bleeding branch (SpongeCommon commit https://github.com/SpongePowered/SpongeCommon/commit/d1b8572f639d71267955becc8e2e263fa4f34770)
- SpongeVanilla version: 

**Issue Description**

(I'm testing on SpongeForge so "deny-chunk-requests" is off by default).

- Start the server
- A default global.conf with `deny-chunk-requests=false` has been generated
- Inside WorldServer `this.activeConfig.getConfig().getWorld().denyChunkRequests` is false (this is good)
- Edit global.conf and change `deny-chunk-requests` to true
- Run sponge -g reload
- `this.activeConfig.getConfig().getWorld().denyChunkRequests` is still false
- Try sponge -w world reload
- `this.activeConfig.getConfig().getWorld().denyChunkRequests` is still false

I've also tried adding `deny-chunk-requests=true` to world.conf with no luck.

(PS. I didn't test this on stable-7, the system has been reworked with https://github.com/SpongePowered/SpongeCommon/pull/1957)
EDIT: nevermind, that PR was cherry-picked on stable-7.

**Comment by phit** [comment]
don't bother testing on bleeding, you are wasting your time seriously.. there's so many commits missing

if it isn't an issue on stable its basically a nonissue

**Comment by ryantheleach** [comment]
For context, in case you arn't currently aware: https://forums.spongepowered.org/t/community-vote/24729

Most of development has been focused on stable for months, and the 2 branches have drifted. It's planned for bleeding to be relevant again soon for plugin authors, but not until that vote is resolved and we sort out which direction we are going in.

Even then, I'd only be testing against bleeding, if you are explicitly trying to test new API or new Implementation that hasn't yet reached stable.

**Comment by ImMorpheus** [comment]
I'm well aware. The thing is, #1957 is targeting bleeding. Why bother testing stable-7 ? Little did I know the commit was cherry-picked soon after.

Just tested on the other branch.
I'm able to reproduce this on stable-7 (updated to commit https://github.com/SpongePowered/SpongeCommon/commit/751b801e1becc7a72dbeda43c9c5bf9725024160).
Sadly this is an issue.

**Comment by ImMorpheus** [comment]
@phit Can you remove the bleeding label ? This was reproduced on stable-7
