### ISSUE TITLE
No configurability of fireworks

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#2040]
**I am currently running**
`1.12.2-7.1.0-BETA-98`

The shape does not change to creeper with the following code. Also color changes don't apply. I don't know what 'flickers' and 'trails' look like, but when changing that I also don't see any changes.

```
FireworkEffect effect = FireworkEffect.builder()
    .shape(FireworkShapes.CREEPER)
    .build()
ParticleEffect particleEffect = ParticleEffect.builder()
    .type(ParticleTypes.FIREWORKS)
    .option(ParticleOptions.FIREWORK_EFFECTS, Arrays.asList(effect))
    .build()
world.spawnParticles(particleEffect, pos)
```

**Comment by phit** [comment]
@randombyte-developer was this fixed now that the PR is merged?

**Comment by randombyte-developer** [comment]
No sadly not.

**Comment by clienthax** [comment]
Turns out the data wasn't actually being used when making the packet.
https://github.com/SpongePowered/SpongeCommon/pull/2096

**Comment by XakepSDK** [comment]
Already known issue: https://github.com/SpongePowered/SpongeCommon/issues/1853
