### ISSUE TITLE
Cancelling DropItemEvent.Pre still removes items from the player's inventory

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#2044]
**I am currently running**
- SpongeVanilla version:  1.12.2-7.1.0-BETA-59

**Issue Description**
As the title says, cancelling `DropItemEvent.Pre` prevents an item from being dropped, however the item is still removed from the player's inventory. This should not be the behavior per https://github.com/SpongePowered/SpongeCommon/issues/1678

**Comment by Faithcaio** [comment]
It is possible to use `ClickInventoryEvent.Drop`.

**Comment by Faithcaio** [comment]
Clarified in API.
