### ISSUE TITLE
MoveEntityEvent#setToTransform does nothing

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#2052]
**I am currently running**
- SpongeForge version: 1.12.2-2705-8.0.0-BETA-3362:dev
- Java version: 1.8.0_162
- Operating System: Windows 10 x64

**How to reproduce**
```java
	@Listener
	public void onPlayerMove(MoveEntityEvent e, @Getter("getTargetEntity") Player p) {
		if (e.getToTransform().getPosition().getY() < 0) {
			p.sendMessage(Text.of("You have been moved to the spawn point."));
			e.setToTransform(new Transform<>(e.getToTransform().getExtent().getSpawnLocation()));
		}
	}
```

**Result**
The player receive the message when he is moving under y=0 but he is not moved.

**Comment by JBYoshi** [comment]
Can reproduce on stable as well.

**Comment by JBYoshi** [comment]
```java
if (!toTransform.equals(toTransform)) {
```

![](http://discordemoji.com/assets/emoji/thonk.png)
