### ISSUE TITLE
liquids and buckets dupe

### ISSUE THREAD

**Issue by ResponsibleBear** [SpongePowered/Sponge#2053]
https://github.com/MinecraftPortCentral/GriefPrevention/issues/746

Hello. 
[GP] Running GriefPrevention 1.12.2-4.3.0.646
[GP] Running SpongeForge 1.12.2-2705-7.1.0-BETA-3374
[GP] Running luckperms 4.2.51

**Comment by phit** [comment]
we have an issue template, please use it
