### ISSUE TITLE
Wrongly fired AffectSlotEvent

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#2059]
**I am currently running**

```
> sponge version 
[16:14:26 INFO]: SpongeVanilla
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-6cd2dc3d
    SpongeVanilla: 1.12.2-7.1.0-BETA-105
```

I have a plugin which listens for `AffectSlotEvent`s on `EquipmentSlot`s to prevent any modifications there. There are some checks to allow the plugin itself to put items with some special data in those `EquipmentSlot`s though.

I encountered something odd:

1. Call `Player#equip(EquipmentType, ItemStack)`
2. Let the player open the inventory
3. An `AffectSlotEvent` is fired, but the original and the final `ItemStackSnapshot` in the event are the same, checked with `ItemStack#equalTo(ItemStack)`.

Since both are exactly equal, I don't see any reason why this event should be fired. I can workaround this by checking if both are equal and then just ignore that event.

*Edit 1*:

This only happens if those things are met:
- The inventory wasn't opened after the `equip` call yet
- The inventory is opened in creative mode

Examples:

- **A**: Be in survival mode, call equip, open inv => no event is fired, so good
- **B**: Survival, equip, switch to creative, open inv => event is fired, bad
- **C**: Survival, equip, open inv, switch to creative, open inv => no event

So it seems that survival mode swallows that event somehow, which is good.

*Edit 2*:

It is actually the `org.spongepowered.api.event.ClickInventoryEvent$Creative$Impl` event which is fired, although nothing is clicked.

**Comment by Faithcaio** [comment]
Creative Mode is weird like that. IIRC there is no real way to check what type of interaction the client made. So we just always fire events when the clients sends us stuff for creative mode.

**Comment by randombyte-developer** [comment]
Ok thanks for the response. Then I'll close this as it seems to be unfixable.
