### ISSUE TITLE
Items dropping in ChangeBlockEvent.Decay when they're not supposed to

### ISSUE THREAD

**Issue by maodus** [SpongePowered/Sponge#2066]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3206
- Java version: 8, 181 64 bit
- Operating System: Windows 7

- Plugins/Mods:
griefprevention-1.12.2-4.3.0.628, Pixelmon-1.12.2-6.3.4-universal

**Issue Description**
Both cancelling the event and setting the transaction to be invalid in the ChangeBlockEvent.Decay event stop the block from disappearing but they do not stop the dropping of items. Here is the code that I'am currently using: 

```java
    @Listener
    public void onBlockDecay(ChangeBlockEvent.Decay event){
        event.getTransactions().forEach(trans -> {
            Location<World> blockPos = trans.getOriginal().getLocation().get();
            GPClaim claim = GriefPreventionPlugin.instance.dataStore.getClaimAt(blockPos);

            if(claim != null && (claim.isAdminClaim() || claim.hasAdminParent())){
                trans.setValid(false);
            }

        });

    }
```

**Comment by dualspiral** [comment]
This was a long time ago now, so I'm going to close this because I know there have been a fair few fixes in this area. If this is still a problem, please open a new issue with updated information. Thanks!
