### ISSUE TITLE
unable to use custom boolean data

### ISSUE THREAD

**Issue by mmis1000** [SpongePowered/Sponge#2069]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3410
- Java version: Java 8
- Operating System: Linux

- Plugins/Mods: 
- Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, A Plugin that make sponge human lie down, Galaxy, NPCs, SpongePrometheusExporter, VillageMarkerSponge, packetgate/ 
- Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AppleSkin, JMFixer, JourneyMap, RandomPatches

**Issue Description**

Offer custom data data on Human in SpawnEntityEvent always failed and even the constructor of data manipulator is not called at all

Code that does not work(kotlin)
https://gist.github.com/mmis1000/5f446e4244bb64a2dc5acaec1864f6d7

**Comment by dualspiral** [comment]
This might be due to a quirk in the custom data system. The first time you offer custom data, you must offer the Data Manipulator first, not the key. You can use the key after you have done that.

**Comment by ImMorpheus** [comment]
>  The first time you offer custom data, you must offer the Data Manipulator first, not the key. You can use the key after you have done that.
