### ISSUE TITLE
SpongeBlockStateMatcherBuilder#build() throws a NegativeArraySizeException when no traits are specified

### ISSUE THREAD

**Issue by 14mRh4X0r** [SpongePowered/Sponge#2070]
This can be fixed by removing the - 1 part in new BlockTrait<?>[this.traits.size() - 1].

(Creating an issue instead of a PR because it is a trivial change)

Copied over from SpongePowered/SpongeAPI#1835 since implementation was moved here.

**Comment by ryantheleach** [comment]
@Gabizou ~fixed this in bleeding 14 days ago~ when it was moved to implementation in bleeding.

However this is still a bug in the API on stable.

**Comment by 14mRh4X0r** [comment]
The logic is still flawed; it will allocate an array one element too small for the traits. This is probably better fixed by using `new BlockTrait<?>[0]`, in most cases [that's more efficient anyway](https://shipilev.net/blog/2016/arrays-wisdom-ancients/).

**Comment by ImMorpheus** [comment]
PR merged and cherry-picked to stable
