### ISSUE TITLE
auto-populate broken since config rework

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#2076]
This issue was originally submitted by @PorPit in [SpongePowered/SpongeForge#2393](https://github.com/SpongePowered/SpongeForge/issues/2393).
___
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3409
- Forge version: forge-1.12.2-14.23.4.2705
- Java version: 1.8
- Operating System: windows server 2012

- Plugins/Mods:
Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActionBroadcaster, CMD Item, CarrotShop, CrazyFeetSponge, EconomyLite, EpicBanItem, GriefPrevention, LinkMe, LuckPerms, MCRMB, McrmbCommand, Nucleus, PixelVip, PlaceholderAPI, PlotSquared, ProjectCore, SpongyCord, StackBan, StopUnloadWorld, Twenty Ticks, VirtualChest, VirtualTool, World Polisher
Mods (44): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Solar Panels, Applied Energistics 2, Baubles, Better Records, Botania, CraftTweaker JEI Support, CraftTweaker2, CraftTweakerSync, CreativeCore, CreativeCoreDummy, CustomNPCs, Extra Planets, FTB Utilities, FTBLib, FoamFix, FoamFixCore, Galacticraft Core, Galacticraft Planets, Immersive Engineering, Immersive Tech, IndustrialCraft 2, Iron Chest, Just Enough Items, MJRLegendsLib, MTLib, Mekanism, MekanismGenerators, Micdoodle8 Core, MineCamera, MineCameraDummy, Mod Tweaker, OnlinePictureFrame, Pam's HarvestCraft, Shadowfacts' Forgelin, Thaumcraft, Wireless Crafting Terminal 2, WorldEdit, p455w0rd's Library

**Issue Description**
when i use the new sponge version（3361 or 3409） 
set the  global config  "tileentity-activation=true" and "auto-populate=true" and restart server
config does not add any tileentities to default settings
but when i use sponge 7.1.0-BETA-3206
the default settings can be generated normally

**Comment by phit** [comment]
after discussion and some testing, the issue is the config system rework which got rid of config-enabled

`getActiveConfig` will now always return the world specific config, due to how the fallback works in the new system
sadly it is currently impossible to see which config has actually set auto-populate set explicitly, as a temporary fix we should for now always force auto-populate to go to the global config

> q: maybe we just move the activation stuff to another config file?
> a: then we lose the ability to overwrite things on a per world/dimension basis
