### ISSUE TITLE
Sponge does not properly shutdown async lighting thread when world got killed

### ISSUE THREAD

**Issue by mmis1000** [SpongePowered/Sponge#2078]
**I am currently running**

- SpongeForge version: 3422
- Java version: OpenJDK 8
- Operating System: linux

- Plugins/Mods: Galaxy, LuckPerms, SpongePrometheusExporter, VillageMarkerSponge, AppleSkin, Duplicate Entity UUID Fix (DEUF), JMFixer, JourneyMap, Just Enough Items, RandomPatches

**Issue Description**

Sponge async lighting seems does not shutdown properly when world is killed.  

Our server has a lot of world loaded and unloaded due to the way we use worlds, and we found that a lot of threads stall there and not cleared.  
(May not be a big issue for other server as they won't load and unload worlds so often, but we can't load all worlds because we have over 1000 worlds on the server)  

Currently, we monkey patch the `WorldServer::flush()` method to force these threads shutdown .  

https://github.com/OKTW-Network/Galaxy/blob/master/src/main/java/one/oktw/galaxy/mixin/MixinWorldServer.java

But, I though this should be handled by the sponge itself.

**Comment by Aaron1011** [comment]
Fixed in the latest SpongeForge.

**Comment by mmis1000** [comment]
@Aaron1011
Is it supposed to kill the lighting thread before check the world unloading should be cancelled or not?  
I saw there is a check to cancel world unloading right after disabling lighting thread
