### ISSUE TITLE
QueryOperationTypes.ITEM_STACK_IGNORE_QUANTITY incorrect behavior

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#2081]
**I am currently running**
- SpongeForge version: 1.12.2-2705-8.0.0-BETA-3423:dev
- Java version: 1.8.0_162
- Operating System: Windows 10 x64

**How to reproduce**
```java
((PlayerInventory) p.getInventory()).getPrimary().query(QueryOperationTypes.ITEM_STACK_IGNORE_QUANTITY.of(ItemStack.of(ItemTypes.STONE, 1))).poll(1);
```

**Issue Description**
This code remove stone from your inventory if you have stone but if it's not the case it will remove others items, such as grass, dirt, etc ..

**Comment by ryantheleach** [comment]
Leave the bleeding bugs well alone until 1.13 sponge is nearing release.
