### ISSUE TITLE
BlockRay with onlyAirFilter returns before reaching a non-air target

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/Sponge#2086]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3417 & https://github.com/SpongePowered/SpongeForge/commit/6e1e92f6f0465db52420d14fb98633b9ab868693
- SpongeVanilla version: - 
- Java version: 1.8.0u171
- Operating System: CentOS & Windows10

- Plugins/Mods:
n/a

**Issue Description**
BlockRay returns a reached position while still inside air blocks while onlyAirFilter is set.
For example, when raytracing from y=256 to y=0, we're expected to reach the y=128 in the nether.

In practice, if direction is (0 -255 0), then result is Empty:
![image](https://user-images.githubusercontent.com/4776032/44876712-19a93880-aca2-11e8-8a91-d171a821d5cf.png)

If direction is (10 -255 10), then result is y=153:
![image](https://user-images.githubusercontent.com/4776032/44876741-27f75480-aca2-11e8-9790-ae39d6af6246.png)

I'm using the following code:
```
...
final Location<World> lBottom = new Location<>(chunk.getWorld(),
                                               chunk.getPosition().getX() * 16 + 8,
                                               chunk.getPosition().getY(),
                                               chunk.getPosition().getZ() * 16 + 8 );
final Location<World> lTop = new Location<>(lBottom.getExtent(),
                                            lBottom.getX() - 0,
                                            lBottom.getExtent().getBlockMax().getY(),
                                            lBottom.getZ() - 0 );
Optional<BlockRayHit<World>> result = BlockRay.from(lTop)
                                         .stopFilter(BlockRay.onlyAirFilter())
                                         .to(lBottom.getPosition())
                                         .end();
commandSource.sendMessage(Text.of(String.format("From (%.1f %.1f %.1f) to (%.1f %.1f %.1f) returned %s",
                                                lTop.getX(), lTop.getY(), lTop.getZ(),
                                                lBottom.getX(), lBottom.getY(), lBottom.getZ(),
                                                result )));
```

**Comment by ryantheleach** [comment]
It's my suspicion that this may be due to the block ray being exactly along the vertical.

**Comment by ghost** [comment]
Whatever creates the issue affects VoxelSniper as well. FWIW, the Vector3d GenericArgument has a working BlockRay in it.

**Comment by ImMorpheus** [comment]
I'm not able to reproduce this on SF (stable-7) SC (commit https://github.com/SpongePowered/SpongeCommon/commit/92c5aad6fbfad1fc20da6fb4516efd321d8257e4)


`[Server thread/INFO]: From (15.3 256.0 5.7) to (15.3 0.0 5.7) returned Optional[BlockRayHit{(15.336572534665102, 129.0, 5.699999988079071) in WorldServer{Name=DIM-1, DimensionId=-1, DimensionType=minecraft:nether, DimensionTypeId=-1}}]`

`[Server thread/INFO]: From (15.3 255.0 5.7) to (15.3 1.0 5.7) returned Optional[BlockRayHit{(15.336572534665102, 129.0, 5.699999988079071) in WorldServer{Name=DIM-1, DimensionId=-1, DimensionType=minecraft:nether, DimensionTypeId=-1}}]`

`[Server thread/INFO]: From (15.3 255.0 5.7) to (15.3 0.0 5.7) returned Optional[BlockRayHit{(15.336572534665102, 129.0, 5.699999988079071) in WorldServer{Name=DIM-1, DimensionId=-1, DimensionType=minecraft:nether, DimensionTypeId=-1}}]`
