### ISSUE TITLE
Doc says fully customized skins are not possible while in fact they are

### ISSUE THREAD

**Issue by nihiluis** [SpongePowered/Sponge#2089]
**I am currently running**

- SpongeForge version: 2705
- SpongeVanilla version: ????
Spogne APi version 7
- Java version:  8
- Operating System: arch linux

- Plugins/Mods: irrelevant ...

**Issue Description**
i think I found wrong information in the docs. you can change the skin of any player and Human to anything you want ... you can just upload png to mineskin.org service and then he gives you signature and texture value base64 you want and need (same way you create skulls). see: https://wiki.citizensnpcs.co/Skins
```
    /**
     * Represents the {@link Key} for the skin of a {@link Humanoid}.
     *
     * <p>Skins can only be manipulated by supplying the UUID of a player
     * having that skin. The binary skin data is signed by Mojang so fully
     * customized skins are not possible.</p>
     *
     * @see SkinData#skinUniqueId()
     */
    public static final Key<Value<UUID>> SKIN_UNIQUE_ID = DummyObjectProvider.createExtendedFor(Key.class,"SKIN_UNIQUE_ID");
```

**Comment by Cybermaxke** [comment]
This is already fixed in bleeding, so for API8+, it won't be for API 7 because it caused breaking changes.
Got fixed by this PR: https://github.com/SpongePowered/SpongeAPI/pull/1836

**Comment by nihiluis** [comment]
looks pretty good, hope its merged

**Comment by Cybermaxke** [comment]
Yeah, it's merged: https://github.com/SpongePowered/SpongeAPI/commit/a3431307f06996321489b69664b16202e8806042
