### ISSUE TITLE
ClickInventoryEvent getting Item with all data

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#2093]
This issue was originally submitted by @NanitSoft in [SpongePowered/SpongeAPI#1907](https://github.com/SpongePowered/SpongeAPI/issues/1907).
___
Hi! I created custom inventory with ItemStack's with custom data. But ItemStackSnapshot don't have any data, which i put in ItemStack. How i can get original item with all puted data?
`
ItemStackSnapshot item = e.getCursorTransaction().getOriginal();
System.out.println(item.getKeys()); //Printed empty array
`

**Comment by ghost** [comment]
Okay, new information. Now i'm not prevented event and i get next result. When i click on item, it not have any data. When i try put item to inventory, the click event activated and if i debug this i see all item data `¯\_(ツ)_/¯`

**Comment by ghost** [comment]
In API v7.1.0 work perfectly. Issue closed.
