### ISSUE TITLE
CraftItemEvent#Preview does not edit items

### ISSUE THREAD

**Issue by RussianJeb** [SpongePowered/Sponge#2098]
**I am currently running**

- SpongeVanilla version: 1.12.2-7.1.0-BETA-115 
- Java version: 1.8
- Operating System: Windows 10

When I’m crafting 1 item it becomes a stick. But when I’m put a few items 1st item becomes a stick and others become the standard result of crafting.

Code: 
```java
@Listener
    public void onWorkbench(CraftItemEvent.Preview event){
        ItemStack itemStack = ItemStack.builder()
                .itemType(ItemTypes.STICK)
                .build();
        event.getPreview().setCustom(itemStack);
    }
```

**Comment by Faithcaio** [comment]
fixed in latest
