### ISSUE TITLE
MoveEntityEvent.teleport does not apply to spectator mode teleporting 

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#2099]
This issue was originally submitted by @TheCrunchy in [SpongePowered/SpongeAPI#1908](https://github.com/SpongePowered/SpongeAPI/issues/1908).
___
While in spectator mode you can middle click and use the icons to teleport to other people, the MoveEntityEvent.teleport event doesnt listen for this.

**Comment by ryantheleach** [comment]
@TheCrunchy Can you provide details, e.g. test plugin, what implementations you tested on etc.

**Comment by TheCrunchy** [comment]
@ryantheleach 
API - spongeapi-7.1.0-20180820.174752-54-shaded
Running on - spongeforge-1.12.2-2705-7.1.0-BETA-3438

Using this code - https://pastebin.com/bhR0BP9C
