### ISSUE TITLE
Invalid character constant

### ISSUE THREAD

**Issue by Jeanolos** [SpongePowered/Sponge#210]
When I build Sponge, I get an error that says "Invalid character constant". I fixed it by replacing 'Â§' with just '§'. But then I get "Unmappable character for encoding UTF-8.

**Comment by simon816** [comment]
You're not using UTF-8, make sure your IDE is set up correctly.

**Comment by Minecrell** [comment]
@simon816 is right, your IDE is not setup correctly if you have this problem.
