### ISSUE TITLE
Incorrect(?) behavior of InteractItemEvent[.Secondary.MainHand]

### ISSUE THREAD

**Issue by realGWM** [SpongePowered/Sponge#2102]
**I am currently running**
- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-59.jar
- Java version: 1.8.0_181
- Operating System: Arch Linux 4.14.69-1-lts

- Plugins/Mods:
SpongeBug.jar

**Issue Description**

Code: https://gist.github.com/GreWeMa/b6267ab4417bfc555ea408ba1cd6da58
This code cancels **InteractItemEvent.Secondary.MainHand** if player holds stick in hand (item does't matter, and even is not needed at all) and opens inventory with name "Bug".
If player uses stick on air or almost any other block - everything is going as expected, my custom inventory with name "Bug" is opened.
If player uses stick on block which can be opened (like chest, workbench, furnace and etc.) this block's inventory opens (but event is cancelled, so it should not happen).
Video: https://www.youtube.com/watch?v=ebCQ4b0itpg

**Comment by gabizou** [comment]
Retest on 116, we went and fixed a few bugs with interactions but have yet to make a new recommended build pending some more bug fixes.

**Comment by realGWM** [comment]
Retested on 116.
Now it works almost as expected, except that **InteractItemEvent.Secondary.MainHand** is now not fired at all if I click on air (works as expected if I click on blocks).
On 59 it **is** fired on click on air.
But this sounds like a different problem, should I close this issue and open a new one?

**Comment by ImMorpheus** [comment]
Related: https://github.com/SpongePowered/SpongeCommon/issues/2013

**Comment by ImMorpheus** [comment]
> Now it works almost as expected, except that InteractItemEvent.Secondary.MainHand is now not fired at all if I click on air (works as expected if I click on blocks).

Ok, no, this is an issue with SpongeVanilla. See https://github.com/SpongePowered/SpongeVanilla/issues/389
