### ISSUE TITLE
Entity Duplication with Nether Portals

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#2103]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3445
- SpongeVanilla version: 1.12.2-7.1.0-BETA-116
- Java version: 1.8
- Operating System: Linux / Windows

- Plugins/Mods:
GriefPrevention v1.12.2-4.3.0.654 (**Only on SpongeVanilla**)
LuckPerms v4.2.99
Nucleus v1.5.5-S7.0-MC1.12.2

**Issue Description**
Items dropped into a Nether Portal are getting duplicated when the target world is unloaded and loaded.
Video: https://www.youtube.com/watch?v=JNy0cWaRh-0

This issue is **NOT** present on SpongeVanilla unless GriefPrevention is also present

**Steps to reproduce**
1. Create a Nether Portal in the Overworld, Go through said portal in order to generate the chunks in the Nether then go back to the Overworld.
2. Drop any stackable item into the Nether Portal and wait for it to disappear.
3. Run `/world unload DIM-1` then `/world load DIM-1` (This requires Nucleus)
4. Go through the Nether Portal.
5. Profit???

**Comment by JBYoshi** [comment]
Can reproduce. The item appears to be loaded twice (the same UUID each time). I'm using SpongeForge, with both GP and Nucleus installed (I am not using LP).

**Comment by JBYoshi** [comment]
Latest findings: In `EntityUtil.transferEntityToDimension()`, the call to `toWorld.spawnEntity(entity)` adds the item to the spawn list in the tracker (not sure if that's intended). Then, when it calls `toWorld.updateEntityWithOptionalForce(entity, false)`, the item is added directly to the chunk. Somehow this gets corrected when entering the dimension, so when the world is unloaded and then reloaded, two items exist.
