### ISSUE TITLE
Cause stack corruption exceptions thrown at high rate

### ISSUE THREAD

**Issue by RedNesto** [SpongePowered/Sponge#2104]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3452
- SpongeVanilla version: local version with latest SpongeCommon commits (92dbbdcc283d7f7b4f9b5c35ee690e8187f46111)
- Java version: 1.8.0_181
- Operating System: Windows 7

- Plugins/Mods: _None_

**Issue Description**
The console is filled with Cause stack related stacktraces ([like this](https://gist.github.com/RedNesto/3c8cf11f6650f12e903edcdc019fcffd)) when the player moves (and probably many other interactions).
SpongeForge 3451 does not have this issue.

**Comment by mmis1000** [comment]
```java
            Sponge.getCauseStackManager().pushCause(player); // item +1
            Sponge.getCauseStackManager().pushCause(player); // ignored, item +0

            // doimg something...           

            Sponge.getCauseStackManager().popCause(); // pop, item -1
            Sponge.getCauseStackManager().popCause(); // still pop, item -1, boom!!!
```

I though this pattern is broken after the commit sponge common 92dbbdc
The `SpongeCauseStackManager` now reject to add new cause to the list if it already has.
But it will still pop the cause no matter previous push success or not.
Result in the cause list altered in a completely unexpected way.

Maybe a list of counter can solve this issue by ensuring you won't pop the cause that you did not ever push
```java
// maybe
private final Deque<int> counters = Queues.newArrayDeque();

void pushCause(Object obj) {
  if (this.cause.peak() === obj) {
    counters.add(counters.pop() + 1);
  } else {
    counters.add(0);
    cause.add(obj);
  }
}


void popCause() {
  if (this.counters.peak() > 0) {
    counters.add(this.counters.pop() - 1);
  } else {
    counters.pop();
    cause.pop();
  }
}
```
