### ISSUE TITLE
Implement permissions handling for non-Player CommandSources

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/Sponge#211]
paging @SpongePowered/developers 

# Handling CommandSource permissions

## Server console
Do we give server console real permissions? Maybe just make it be the default subject where UNDEFINED becomes TRUE??? I can see that we want to like stop the console from doing certain commands like accidentally, but if someone could access the console the sender could also access the permissions configuration to change permissions.

Console permissions subjects could also be lumped in with like 'remote' subjects -- like rcon, console, etc are part of the same collection?

## Rcon

Should be handled similar defaults to server console. More of a point to give this actual permissions, since there is a point to restricting capabilities (rcon access != FS access)

## Command Blocks
Command blocks are harder. There are really multiple ways of going about this:

1. All command blocks have the same permissions -- this is simple, lump the single 'commandblock' subject in with the rest of the system subjects
2. Each command block's permissions are determined by the name given to it -- so default command block has permissions for '@', others by name. Enabling this means we might as well expect permissions plugins to support arbitrary subject types -- not just users/groups. This gives command blocks separate permissions from users/groups **i prefer this one**

3. The command blocks share permissions with the same-named player. This may cause issues though if a command block is not required to have the same name as a player. Gotta test???

Any other senders I missed? Let me know what you think about these proposals.

**Comment by modwizcode** [comment]
@zml2008 I like a lot of this, but for the command blocks I think the proposals are flawed. Command block names are also used by some maps (mostly older) to indicate who is saying the /say command from the command block.

Moving forward /tellraw will solve that problem, but we still have many maps with /say and named command blocks would be confusing with permissions. 

As long as you address that smallish issue I'm perfectly fine with using the name of the command block.

**Comment by zml2008** [comment]
well Sponge is set up so that default permissions match what commands are allowed to vanilla users by default, meaning that any named command block could execute /say. Is that the issue you were worried about?

**Comment by modwizcode** [comment]
I think so.

**Comment by ST-DDT** [comment]
Well players are identified by their uuid?
And we could use a prefix for command blocks.
`@CMDB_<Name>`
This guarantees that there will never be collisions between players and commandblocks.
As an alternative we could add a getType method to CommandSource and leave it to the permission service to deal with it properly. This method would also help for commands whether it can be executed from that source. Ex Arena join is only available to Players regardless of permissions.

**Comment by zml2008** [comment]
@ST-DDT I suggest looking at how the permissions api actually works before commenting on issues relating to it.

And for your last example, that's what `source instanceof Player` is for.

**Comment by zml2008** [comment]
This is implemented with PR #215
