### ISSUE TITLE
Cannot setup world Gamemodes [World Gamemode doesnt save - World Manager Problem?]

### ISSUE THREAD

**Issue by HaniXP** [SpongePowered/Sponge#2111]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3477
- SpongeVanilla version: 
- Java version: Version 8 - 181
- Operating System: Windows 7 Ultimate (64 - bit)

- Plugins/Mods:
Plugins : 
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, EconomyLite, FlexibleLogin, GriefPrevention, LuckPerms, MMCRestrict, MagiBridge, NPCs, Nations, Nucleus, PlaceholderAPI, UltimateCore

Mods : 
Minecraft, Minecraft Coder Pack,
 Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astikoor, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, Baubles, Better Records, BiblioCraft, BuildCraft, BuildCraft Compat, BuildCraft Lib, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Davinci's Vessels, Doggy Talents, Dynmap, EnderStorage, Exotic Birds, Extra Bit Manipulation, Extreme Reactors, FastWorkbench, FoamFix, FoamFixCore, Forestry, Forge Endertech, Forge Microblocks, Forge Multipart CBE, IndustrialCraft 2, Inventory Tweaks, Just Enough Items, MCMultiPart, MalisisCore, MalisisDoors, Mega Loot, Mekanism, MekanismGenerators, Minecraft Multipart Plugin, Modern Warfare, MorePlayerModels, Moving World, MovingWorld CORE, MrCrayfish's Device Mod, MrCrayfish's Furniture Mod, MrTJPCore, Not Enough Items, OMLib, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, ProjectRed Core, Random Things, RandomPatches, Redstone Flux, Redstone Paste, SecurityCraft, Shadowfacts' Forgelin, SignPicture, TESLA, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Treecapitator, Waila, WorldEdit, Zero CORE, bspkrsCore

**Issue Description**

When i try to set gamemodes for a world, it doesnt work at all, the world stays the same.. 
I mean like.. i've created a world and the world is called "creative" , ive created it by using nucleus world commands such as /world create etc.. after the world creation, i tried to set the game mode for that world into "Creative Mode" by doing "/world setgamemode creative creative" but nothing happens, the world's game mode is stuck on "survival" mode and its never changing, even after many restarts, Here's a screenshot 

![sdt](https://user-images.githubusercontent.com/23115604/46517924-7045fb80-c87a-11e8-8023-1b14abea6335.JPG)

I've talked with nucleus staff and they told me that normally it should show it creative post-restart
If it doesn't, then it's a bug.. & they told me that they are  pretty sure this was a world manager error

[ relatable issue : #1506 ]

ServerLogs : https://gist.github.com/AgentHani/8908445e34f22cba909bb01ae605c23c

**Comment by IBGnova** [comment]
I'm currently having an issue where when I disable worlds, they come re-enable after reboots. They stay disabled for the duration of the server up-time, but right when the server comes back from a restart they seem to be back and players can enter with portals. I was told this issue might be related to the one listed above, and to comment this here. :p
