### ISSUE TITLE
Invalid return value of World#getBlockMax()

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2120]
**I am currently running**

- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-121
- Java version: 1.8.0_181
- Operating System: Kubuntu 18.04 Bionic
- Plugins/Mods: None

**Issue Description**

The `World#getBlockMax()` method returns incorrect value. Instead of (29999999, 255, 29999999), it returns (30000000, 256, 30000000), that is, at one larger. Along with that breaks the `World#getBlockSize()` method, which returns (60000001, 257, 60000001) instead of (60000000, 256, 60000000).

**Comment by NamStalker** [comment]
From what I can tell, the World#getBlockMax() should return (30000000, 256, 30000000), but the World#getBlockSize() is actually wrong and is returning with the added 1 to all values. I can submit a PR to fix this, but it seems like the first method is returning as intended.

Let me know if I may misunderstand what it should be returning.

**Comment by Lignium** [comment]
The default world length is 60M. 30M blocks for negative values (from -30M to -1 inclusive), and remaining 30M blocks for positive values with zero (from 0 to 29,999,999 inclusive). The fact is that we confuse coordinates of blocks and coordinates of points in the world. Coordinates of a block are given by the coordinate of it center + Vector3d(-0.5, -0.5, -0.5). This means that at a block with coordinates (29999999, 255, 29999999) the opposite vertex will be just at the coordinates (30M, 256, 30M). I hope clearly written. :)

**Comment by NamStalker** [comment]
Ok, I see what happened there. I'll look into this once I get home. If anyone else wants to look into this or has more info, it is related to the change in #1958
