### ISSUE TITLE
Shutting down piston by redstone path explosion isn't detected 

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#2132]
**I am currently running**
- SpongeVanilla version: spongevanilla-1.12.2-7.1.4
- Java version: 1.8.0_192
- Operating System: Arch Linux
- Plugins/Mods: TestPiston

**Issue Description**
Depowering piston by redstone explosion doesn't detect explosion owner.

Test code:
```java
@Listener
public void onPistonMove(ChangeBlockEvent.Pre event) {
    Optional<World> pistonExtend = event.getContext().get(EventContextKeys.PISTON_EXTEND);
    Optional<World> pistonRetract = event.getContext().get(EventContextKeys.PISTON_RETRACT);
    if (!pistonExtend.isPresent() && !pistonRetract.isPresent()) {
        return;
    }

    for (Map.Entry<EventContextKey<?>, Object> entry : event.getContext().asMap().entrySet()) {
        System.out.println(entry.getKey().getName() + ": " + entry.getValue());
    }
}
```

Result:
[19:50:31 INFO] [STDOUT]: Piston Retract: WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}

Testing area:
![2018-11-06_19 50 15](https://user-images.githubusercontent.com/4938483/48068767-ea60fb80-e1fd-11e8-93ad-3d92a997c1ef.png)
![2018-11-06_19 54 48](https://user-images.githubusercontent.com/4938483/48068768-ea60fb80-e1fd-11e8-9025-04211ed8550d.png)

**Comment by JBYoshi** [comment]
I can't reproduce this on the latest versions of SpongeForge or SpongeVanilla.

**Comment by ImMorpheus** [comment]
Not able to reproduce on SF (updated to https://github.com/SpongePowered/SpongeForge/commit/56076fef9034ab20d4a3f0704d6fbf26629a1e11)
SC updated to https://github.com/SpongePowered/SpongeCommon/commit/65c5ff81aa162b8d48098f9a90b50c4a5aa31451

Result:
```
Block Event Queue: SpongeLocatableBlock{blockState=minecraft:piston[extended=true,facing=east], position=(-255, 70, -75), worldReference=New World-}
Piston Retract: WorldServer{Name=New World-, DimensionId=0, DimensionType=minecraft:overworld}
Owner: EntityPlayerMP['Player918'/278, l='New World-', x=-254.98, y=75.38, z=-87.42]
Notifier: EntityPlayerMP['Player918'/278, l='New World-', x=-254.98, y=75.38, z=-87.42]


```
