### ISSUE TITLE
Incomplete serialized data of quartz column

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2137]
- SpongeVanilla version: spongevanilla-1.12.2-7.1.4
- Java version: openjdk_1.8.0_181
- Operating System: Kubuntu 18.04
- Plugins/Mods: A simple test plugin

**Issue Description**
At the stage of converting BlockState of a quartz column BlockState (and maybe others) into a DataContainer, rotation information is lost.

`BlockState#toString() -> minecraft:quartz_block[variant=lines_z]`
`BlockState#toContainer().toString() -> ... BlockType=minecraft:quartz_block[variant=lines] ...`

The original thread from Sponge forum: https://forums.spongepowered.org/t/deserialize-block/26161

**Comment by JBYoshi** [comment]
Can reproduce. It appears that `BlockState.getId()` is missing information.

I don't think there is a way to handle updating old IDs at the moment, so fixing this would probably break existing save data.

**Comment by SimonBHB** [comment]
Le bug existe toujours, pas de solution ?

[translate.google.fr]:
The bug still exists, no solution?

**Comment by gabizou** [comment]
Finally figured it out: The enums and basically any `IStringSerializable` would provide a translation key for their `toString()` values instead of the serialization name value, so Quartz's Lines would provide `lines` as their `toString()` and only by calling `IStringSerializable.getName()` would it provide `lines_z`... Now it's providing the correct name in the ID generation.

**Comment by SimonBHB** [comment]
Bonjour, 
c'est normal que le texte est pas sauvegardé sur un BlockState de panneau ?
minecraft:wall_sign[facing=east]
![image](https://user-images.githubusercontent.com/8994762/62701235-11926680-b9e4-11e9-8317-895db1382680.png)

translate.google.fr:
Hello,
is it normal that the text is not saved on a wall_sign BlockState?
minecraft:wall_sign[facing=east]

**Comment by Lignium** [comment]
@SimonBHB This data is stored in tile entity, separate from block state.

**Comment by SimonBHB** [comment]
et comment on la sauvegarde avec le BlockState ?

translate.google.fr:
and how to save it with the BlockState ?

**Comment by JBYoshi** [comment]
You may want to take a look at [`BlockSnapshot`](https://jd.spongepowered.org/7.1.0/org/spongepowered/api/block/BlockSnapshot.html). It stores data from both the block state and the tile entity.

**Comment by SimonBHB** [comment]
Comme cela ?

Location<World> location = event.getTargetBlock().getLocation().get();
BlockSnapshot blockSnapshot = BlockSnapshot.builder().from(location).build();

il y a rien:

translate.google.fr: 
there is nothing:

[17:56:46] [Server thread/INFO] [plugin]: SpongeBlockSnapshot{worldUniqueId=607c288d-7f71-48a0-a29c-abad9caea46f, position=(1017, 66, 1055), blockState=minecraft:wall_sign[facing=north], extendedState=minecraft:wall_sign[facing=north]}

**Comment by Lignium** [comment]
`event.getTargetBlock().createTileEntityArchetype().get().getTileData().toString()`

The method `TargetBlockEvent#getTargetBlock()` already returns a `BlockSnapshot`.

**Comment by SimonBHB** [comment]
J'avais pas fait attention^^
Merci, c'est dommage, car il y a plein de données qui ne me servent à rien comme la position et le monde

translate.google.fr:
Thank you, it's a shame, because there are plenty of data that do not serve me anything like the position and the world
