### ISSUE TITLE
Keys.LAST_DATE_PLAYED is empty, while JoinData is present

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/Sponge#2151]
**I am currently running**
- SpongeVanilla version: 1.12.2-7.1.0-BETA-121
- Java version: 1.8.0_121 
- Operating System: Windows 10

When getting the last played instant from a user by using `user.get(Keys.LAST_DATE_PLAYED)`, the returned optional is empty, but when getting via the JoinData, via `user.get(JoinData.class).get().lastPlayed().get()` both are present.

```java
                    User user = UserStorageService#get(uuid).orElse(null);
                    if (user != null) {
                        JoinData data = user.get(JoinData.class).orElse(null);
                        if (data != null) {
                            ...
                        }
                    }
```

**Comment by ryantheleach** [comment]
I would have expected Last_Date_Played to be the previous date played. not now. but maybe my memory is rusty.
