### ISSUE TITLE
CooldownEvent.Set API is not functional

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#2154]
**I am currently running**
- SpongeVanilla version: 7.1.5-RC139
- Java version: 1.8.0_192
- Operating System: Windows 10

- Plugins/Mods: Irrelevant.

**Issue Description**
You cannot cancel `CooldownEvent.Set` nor can you set a custom cooldown. :)

**Comment by phit** [comment]
what happens when you use the test plugin?
https://github.com/SpongePowered/SpongeCommon/blob/a9423c7ec9f2b423b52c273f7e7a23818a8f3e41/testplugins/src/main/java/org/spongepowered/test/CooldownTrackerTest.java

**Comment by ghost** [comment]
I haven't used that plugin; this is what I've tried:

```java
@Listener
public void onCooldownSet(final CooldownEvent.Set event) {
    if (event.getItemType().equals(ItemTypes.ENDER_PEARL)) {
        event.setNewCooldown(1);
    }
}
```
```java
@Listener
public void onCooldownSet(final CooldownEvent.Set event) {
    if (event.getItemType().equals(ItemTypes.ENDER_PEARL)) {
        event.setCancelled(true);
    }
}
```
Second one throws an error. First one doesn't work.

**Comment by parlough** [comment]
I believe this should be fixed in most cases. If anything else comes up let me know. Thanks for the report!
