### ISSUE TITLE
Canceled water placement can still destroy rails and causes an error when the rail is replaced.

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/Sponge#2158]
This issue was originally submitted by @brjcarbone in [SpongePowered/SpongeVanilla#395](https://github.com/SpongePowered/SpongeVanilla/issues/395).
___
SpongeVanilla 7.1.5 (RC139 with MySQL PR merged).

```java
@Listener
public void onChangeBlockPlace(final ChangeBlockEvent.Place event, @First Player player) {
    event.setCancelled(true);
}
```

Use a water bucket on a rail and it will get destroyed which can be used to bypass regional protections. Replacing the rail returns this: https://paste.md-5.net/pupetobelu.tex

It will also destroy buttons and other blocks where water may be placed at the same coordinate.

Edit: https://cdn.discordapp.com/attachments/142425412096491520/520031262358896640/2018-12-05_19-18-03.mp4

In this clip, all block placement is canceled, but rails bypass with a large error (as seen in the link above). Water destroys the rails despite being canceled as well.
___
**Edit: Significant testing has occurred in the original issue.** --ryantheleach

**Comment by ryantheleach** [comment]
Post by @DrZoddiak: 

> Tested with 1.12.2-2768-7.1.5-RC3507 Rails appear to still get blocked placing with no errors, so the rail issue appears to be SV specific. Water blocks appear to actually still place entirely with no issue.
> 
> I however tested using Griefprevention to block placement of blocks.
> https://griefprevention.github.io/debug/?ITy2xjXXJg
> 
> With this report you can see that in the beginning I did have permissions to place blocks (Trust) 
> https://gyazo.com/14d008165d9613647743c094c74d4d1c
> and after executing `cfd` I was treated normally and blocks were denied placement.
> https://gyazo.com/8335ffff8730bc3dbd883ac0fc5dd89f
> Here you can see that my placement for placing blocks was denied
> https://gyazo.com/b25d21ada6d41903e6a7eff18a244ddd
> 
> but as shown here it places them anyway (I place blocks, turn on debug, attempt to place a few more and am denied, and then am allowed to place rails)
> https://gyazo.com/ffff85d45d7352112b67469ac365489a
> 
> And here you may notice that Block-Place does not actually appear to be checked on Water at all (this may be GP specific which is likely the discrepancy in the water being allowed placement compared to OP) 
> https://gyazo.com/d17ce1669669a0c065df8a982cc7a053
> 
> So to summarize. Rails allowing to be placed despite block-placement appears to be an SV specific issue. The matter of water breaking blocks it is placed on is still up in the air, as GP doesn't appear to effect water blocks as OP's test did. My IDE isn't in functioning order, or I'd test the same way.
> 
> Edit: Latest.log from SV test
> https://gist.github.com/DrZoddiak/111657ad23bdd64f3674d18bad5d37a3

___
Post by @DrZoddiak: 

> Alright upon being given a plugin from @brjcarbone 
> Using similar code he posted I get this error on SV and SF.
> 
> https://gist.github.com/DrZoddiak/e43e18e447bef447ed70019b45b488c9
> 
> This issue should probably be moved to SC because of this.
>

**Comment by ImMorpheus** [comment]
> Use a water bucket on a rail and it will get destroyed which can be used to bypass regional protections.

I'm not able to reproduce this with the Interactevents PR.

Try testing with https://github.com/SpongePowered/SpongeCommon/pull/2125 if you're able to setup a local dev environment

**Comment by ImMorpheus** [comment]
Tested with SV (https://github.com/SpongePowered/SpongeVanilla/commit/d26e6a06309f601510f871236e176a48ab0a8be8) and SF (https://github.com/SpongePowered/SpongeForge/commit/1c1d1328c13a02960ccca626fa4713f6ce43c8e0)

(SC updated to https://github.com/SpongePowered/SpongeCommon/commit/4063674e2d3f0c2c71cbf37ac7db505ba4eeeb17)

Using the test code above:  
```java
@Listener
public void onChangeBlockPlace(final ChangeBlockEvent.Place event, @First Player player) {
    event.setCancelled(true);
}
```  
> Use a water bucket on a rail and it will get destroyed which can be used to bypass regional protections. Replacing the rail returns this: https://paste.md-5.net/pupetobelu.tex  

Not able to reproduce

> In this clip, all block placement is canceled, but rails bypass with a large error (as seen in the link above). 

Not able to reproduce

> Water destroys the rails despite being canceled as well.  

Not able to reproduce. However, the rail is dropped (NOT broken). (it's a dupe bug)
I'm opening a new issue for this.
