### ISSUE TITLE
Listening for GameRegistryEvent.Register<CraftingRecipe> fails to run listeners.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#2159]
**I am currently running**

SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-6eb292fd
    Sponge: 1.12.2-7.1.5-SNAPSHOT
    SpongeForge: 1.12.2-2768-7.1.5-RC0
    Minecraft Forge: 14.23.5.2768

**Plugins/Mods:**
- Modified RecipeTest : https://gist.github.com/ryantheleach/40ce23eee453afd69f396070f8b5afc5

**Issue Description**
Listening for the Game Registry event, as opposed to preinit fails to register recipes.
Breakpoints are missed, listener never run.

**Comment by ryantheleach** [comment]
On second thoughts, maybe we should split this into SC / SV for the unable to be overwritten aspect.

**Comment by Cybermaxke** [comment]
This will be fixed for bleeding in https://github.com/SpongePowered/SpongeCommon/pull/2174 and I will backport the fix to stable after it gets merged.

**Comment by Cybermaxke** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/bfdea2de6d5f34b102eb77ca0ad61534d8470aac
