### ISSUE TITLE
Missing contexts in UseItemStackEvent

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2166]
**I am currently running**

- SpongeVanilla version: spongevanilla-1.12.2-7.1.5-RC143
- Java version: OpenJDK 1.8.0_191
- Operating System: Kubuntu 18.04
- Plugins/Mods: Only one experimental plugin

**Issue Description**

I analyzed the work of UseItemStackEvent and discovered that not all events have player information in context. This is certainly not such a big problem, since the player is in the event stack. But still...

When switching a slot while using an item (using a bubble with water or using a bow):

1. UseItemStackEvent.Start - Present
2. UseItemStackEvent.Tick - **Missing**
3. UseItemStackEvent.Reset - **Missing**

Completed action:

1. UseItemStackEvent.Start - Present
2. UseItemStackEvent.Tick - **Missing**
3. UseItemStackEvent.Finish - **Missing**
4. UseItemStackEvent.Replace - **Missing**
5. UseItemStackEvent.Reset - **Missing**

The undone action, that is, the right mouse button has been released (eating food and as well as a bow shot):

1. UseItemStackEvent.Start - Present
2. UseItemStackEvent.Tick - **Missing**
3. UseItemStackEvent.Stop - Present
4. UseItemStackEvent.Reset - Present

\+ Bonus: Small typo in class documentation: [UseItemStackEvent.Reset](https://jd.spongepowered.org/7.1.0/org/spongepowered/api/event/item/inventory/UseItemStackEvent.Reset.html)

**Comment by Aaron1011** [comment]
Can you pastebin the plugin code you're using?

**Comment by Lignium** [comment]
The most common unremarkable code... [Spongeriment.java](https://pastebin.com/iKDhn7kB)

**Comment by Lignium** [comment]
Ha-ha, I did not have time to write, in the context you need to add used item. Thanks!
