### ISSUE TITLE
"Shift T" feature from Quark raises IllegalStateException exception

### ISSUE THREAD

**Issue by bluelightning32** [SpongePowered/Sponge#2168]
**I am currently running**
- SpongeForge version:  1.12.2-2768-7.1.5-RC3512
- Java version: OpenJDK 64-Bit Server VM, version 1.8.0_191, running on Linux:amd64:4.19.8-300.fc29.x86_64
- Operating System: Fedora 29

- Plugins/Mods:
Lots of mods present. The one mod relevant to the bug is Quark. I also have the ultimatechat plugin install. I'm not sure if that's a factor.

**Issue Description**
Quark has a feature where you can hover over an item in your inventory, then press shift-T to print that item in chat. The feature works fine with just forge, but with spongeforge, the player gets disconnected.

I'm hitting this with the Enigmatica Expert 2 modpack. However, I found that someone else already filed a bug report with Quark about it from a different mod pack. The Quark author closed the bug and said it's a Sponge problem, not a Quark problem.

https://github.com/Vazkii/Quark/issues/917

**Comment by JBYoshi** [comment]
It looks like Quark is sending chat messages on the wrong thread. I'm pretty sure it's *supposed* to use the main thread, but I can't figure out *why*, except for Sponge compatibility. The involved `ItemStack` is a copy, so the only ways it could affect the outside world are `PlayerList.sendMessage()` (sends a chat message to all players; Sponge tries to fire an event here) and `NetHandlerPlayServer.chatSpamThresholdCount`.

Here's the involved method in Quark: https://github.com/Vazkii/Quark/blob/45f15323d5553a67206a91cd893d8f66dad1ba83/src/main/java/vazkii/quark/management/feature/LinkItems.java#L51-L73
(The `ItemStack` provided to the method is not shared with the player's inventory in any way - it's read straight from a packet and discarded after being handled.)

**Comment by phit** [comment]
~move to sf

**Comment by limbo-app** [comment]
Hey @bluelightning32! I've moved your issue to [SpongePowered/SpongeForge#2542](https://github.com/SpongePowered/SpongeForge/issues/2542).
