### ISSUE TITLE
Listeners GameRegistryEvent.Register<DataTranslator<?>> never calling

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2169]
**I am currently running**

- SpongeVanilla version: spongevanilla-1.12.2-7.1.4
- Java version: OpenJDK 1.8.0_181
- Operating System: Kubuntu 18.04
- Plugins/Mods: Only one experimental plugin

**Issue Description**

Listeners `GameRegistryEvent.Register<DataTranslator<?>>` never calling and impossible to register correctly `DataTranslator`s.

**Comment by Cybermaxke** [comment]
Right now it's not allowed to register custom `DataTranslator`s.
https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/registry/type/data/DataTranslatorRegistryModule.java#L99

**Comment by Lignium** [comment]
I need to serialize to `DataContainer` instances of a regular class that is not associated with Data API. `DataTranslator` is best suited for this. It is very important that this happens automatically when calling the appropriate methods in `DataView` class. Why then need `DataManager#registerTranslator()` method? The fact that the event is not triggered is more like a bug.

**Comment by Cybermaxke** [comment]
For now use the `DataManager#registerTranslator()` method, I will fix it when I have the time.

**Comment by Lignium** [comment]
There is another problem... Work of methods `DataManager#registryTranslator()` and `GameRegistryEvent.Register#register()` somewhat different. When registering a `DataTranslator` with `GameRegistryEvent.Register#register()` then methods `DataView#getObject()` and `DataView#getObjectList()` can't get data translator.

In practice, it is not yet possible to test, due to the bug described above.

I made a small image illustrating this:
![Registering of DataTranslator](https://user-images.githubusercontent.com/41531939/50746513-187fad80-1238-11e9-82e7-ca4c1a9ea5a5.png)

**Comment by Cybermaxke** [comment]
Yes, I already noticed that the two methods are currently doing different things.

**Comment by Cybermaxke** [comment]
@Lignium The event should work now as expected.
