### ISSUE TITLE
Extents with a Y above 0 can't run getHighestYAt

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#2172]
I have an Extent that is one block high, and the one block is at 1 instead of 0. If I call `extent.getHighestYAt(x, z)` it gives me `org.spongepowered.api.util.PositionOutOfBoundsException: Position is out of bounds: expected in range (-32, 1, 176) to (-17, 1, 191) but got (-32, 0, 176)`

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/f408ee509fb434404e29e7cbba3be16a71abb0ab
