### ISSUE TITLE
Investigate MixinPlayerChunkMapEntry#resendUpdatedBiomes

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Sponge#2178]
While working on 'natural chunk regen' with @bloodmc, I noticed that sending a player a `new SPacketChunkData(chunk, 65535)` for an *existing* chunk can have strange effects. Specifically, it causes entities to become invisible client-side (even though they still exist in the client world) until they move out of the chunk.

We use this same approach in `MixinPlayerChunkMapEntry#resendUpdatedBiomes`. We should investigate if setting the biome for a chunk with entities in it causes this issue.

**Comment by ImMorpheus** [comment]
> We should investigate if setting the biome for a chunk with entities in it causes this issue.

We can assume it does, given the issues opened in the past few weeks. I'm closing this since the issue was fixed by https://github.com/SpongePowered/SpongeCommon/pull/2390
