### ISSUE TITLE
Calling transferToWorld on boat player is riding on only teleport the boat to other world

### ISSUE THREAD

**Issue by mmis1000** [SpongePowered/Sponge#2179]
**I am currently running**

- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-70763aa8
- Sponge: 1.12.2-7.1.3-SNAPSHOT
- SpongeForge: 1.12.2-2768-7.1.3-RC3495
 -Minecraft Forge: 14.23.4.2765

- Plugins/Mods: AppleSkin, FoamFix, FoamFixCore, JMFixer, JourneyMap, RandomPatches, VanillaFix, OKTW Galaxy, PacketGate, SpongePrometheusExporter, VillageMarkerSponge

**Issue Description**

When a player is on a boat, you call transferToWorld  on the boat.  
Only the boat will be teleported to other world.  
Although it does change the location of player, player still stays in the same world

Might be a vanilla issue though

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/b448e80292ba62b9be9198a9a8bdb3739672070d
