### ISSUE TITLE
BlockSnapshotBuilder world uuid check

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#2180]
Add check for world uuid here:
https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/block/SpongeBlockSnapshotBuilder.java#L222

SpongeBlockSnapshot checks world uuid, but builder doesn't.

**Comment by ImMorpheus** [comment]
> SpongeBlockSnapshot checks world uuid, but builder doesn't.

SpongeBlockSnapshotBuilder doesn't check the world when building the block snapshot. 
https://github.com/SpongePowered/SpongeCommon/blob/2bcf872366579dca175e327adf88a5ea6772e91e/src/main/java/org/spongepowered/common/block/SpongeBlockSnapshotBuilder.java#L91

The correct way should be to add a message to the exception like we did for blockstate.

https://github.com/SpongePowered/SpongeCommon/blob/2bcf872366579dca175e327adf88a5ea6772e91e/src/main/java/org/spongepowered/common/block/SpongeBlockSnapshot.java#L111-L113

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/f0e8373b84bc392841d3f865ad9f2b579b47b019
