### ISSUE TITLE
InteractItemEvent not fired

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/Sponge#2184]
@ImMorpheus 

SF spongeforge-1.12.2-2768-7.1.5-RC3515.jar:
Works as expected, InteractItemEvent is fired whenever I'm doing a right click.

SF spongeforge-1.12.2-2768-7.1.6-RC3561.jar/spongeforge-1.12.2-2768-7.1.5.jar:
InteractItemEvent is fired when I'm doing a right click at air, it is also fired when I'm doing a right click at a block with a "non-placeable" item in hand (stick, arrow, feather etc.), but when I'm doing a right click at a block with a "placeable" item in hand (dirt, stone, skull etc.) - event is not fired.

Is it a bug, or is it just how the new API works? If its second, then it's not quite comfortable and now I need to use both "InteractItemEvent" and "InteractBlockEvent" in order to do things that I was able to do using only "InteractItemEvent"...

_Originally posted by @GreWeMa in https://github.com/SpongePowered/SpongeCommon/issues/2013#issuecomment-462060852_

**Comment by Dockter** [comment]
This could be related and is already fixed.  Can you try latest build?  https://github.com/SpongePowered/SpongeCommon/issues/2193

**Comment by realGWM** [comment]
Hello!
I tried spongeforge-1.12.2-2768-7.1.6-RC3596 and still, InteractItemEvent is not fired when placing a block (by "placing a block" I mean doing a right click on a block with a "placeable" item in hand).

**Comment by ginyai** [comment]
#2125 That pull request's SpongeForge and SpongeVanilla parts remove the call of `InteractItemEvent.Secondary` on handling right click block at MixinPlayerInteractionManager 

Listener code:
``` java
    @Listener
    @Exclude(ChangeStatisticEvent.class)
    public void onInvChange(Event event, @First Player player){
        logger.info(event.getClass().getSimpleName());
    }
```
Output when place a block
In spongevanilla-1.12.2-7.1.5-RC148
and spongeforge-1.12.2-2768-7.1.5-RC3526 
```
InteractItemEvent$Secondary$MainHand$Impl
InteractBlockEvent$Secondary$MainHand$Impl
ChangeBlockEvent$Place$Impl
ChangeBlockEvent$Post$Impl
NotifyNeighborBlockEvent$Impl
AnimateHandEvent$Impl
```
In spongevanilla-1.12.2-7.1.5-RC151 & RC156
and spongeforge-1.12.2-2768-7.1.5-RC3539 & 7.1.6-RC3555
```
InteractBlockEvent$Secondary$MainHand$Impl
ChangeBlockEvent$Place$Impl
ChangeBlockEvent$Post$Impl
NotifyNeighborBlockEvent$Impl
AnimateHandEvent$Impl
```
https://github.com/SpongePowered/SpongeCommon/pull/2125#issuecomment-453771117
RC on a block with an itemstack did not call InteractItemEvent twice

**Comment by realGWM** [comment]
So, what's about the issue?
I'm getting complains that my plugin isn't working as expected with newer Sponge versions, while it works fine (excluding other bugs of course..) with, for example, RC3515.

**Comment by ImMorpheus** [comment]
@ginyai Short answer: no
Those mixins were moved to SpongeCommon, they are still applied to SF and SV. 

---
@GreWeMa 

Also from the PR:

> (...) 
> this PR aims to fire events based on the packets received by the server.
> CPacketPlayerTryUseItem -> InteractItemEvent
> CPacketPlayerTryUseItemOnBlock -> InteractBlockEvent
> (...)

There's no `CPacketPlayerTryUseItem` when `doing a right click at a block with a "placeable" item in hand`. You're placing a block. You should be listening to `ChangeBlockEvent.Place`.

**Comment by realGWM** [comment]
Ok
