### ISSUE TITLE
CapturedTransactions tracking issue

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#2187]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.6-RC3563
- SpongeVanilla version: 1.12.2-7.1.6-RC154
- Java version: 1.8
- Operating System: Linux, Windows

- Plugins/Mods:
  - LuckPerms-Sponge-4.3.94
  - Nucleus-1.8.3-S7.1-MC1.12.2-plugin
  - Custom Plugin listening to `ChangeInventoryEvent.Pickup`

**Issue Description**
CapturedTransactions are not getting tracked/cleared correctly resulting in incorrect transactions being passed to events. Original issue: https://github.com/prism/Prism/issues/118 I tracked it back to Sponge when investigating it.

**Reproduce**
- Put a bucket of lava in your inventory
- Make sure your gamemode is Survival
- Run `/` in chat
  - Any command even unknown ones should work
- Place the lava and pick it back up using the bucket
  - It doesn't matter how quickly you do this
  - Perform this step as much as you like, the more the merrier
- Drop the bucket of lava and then pick it up
  - You can drop and pickup any item
- Observe the output of the Pickup Event

**Code**
```
@Listener
public void onPickup(ChangeInventoryEvent.Pickup event) {
    LoggerFactory.getLogger("PICK_UP").info(""); // Split up event messages
    event.getTransactions().forEach(transaction -> {
        LoggerFactory.getLogger("PICK_UP").info("Original: {}", transaction.getOriginal().toString());
        LoggerFactory.getLogger("PICK_UP").info("Final: {}", transaction.getFinal().toString());
    });
}
```

**Expected Output**
```
[PICK_UP]: Original: SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}
[PICK_UP]: Final: SpongeItemStackSnapshot{itemType=minecraft:lava_bucket, quantity=1}
```

**Actual Output**
```
[PICK_UP]: Original: SpongeItemStackSnapshot{itemType=minecraft:lava_bucket, quantity=1}
[PICK_UP]: Final: SpongeItemStackSnapshot{itemType=minecraft:bucket, quantity=1}
[PICK_UP]: Original: SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}
[PICK_UP]: Final: SpongeItemStackSnapshot{itemType=minecraft:lava_bucket, quantity=1}
[PICK_UP]: Original: SpongeItemStackSnapshot{itemType=minecraft:lava_bucket, quantity=1}
[PICK_UP]: Final: SpongeItemStackSnapshot{itemType=minecraft:bucket, quantity=1}
[PICK_UP]: Original: SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}
[PICK_UP]: Final: SpongeItemStackSnapshot{itemType=minecraft:lava_bucket, quantity=1}
[PICK_UP]: Original: SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}
[PICK_UP]: Final: SpongeItemStackSnapshot{itemType=minecraft:lava_bucket, quantity=1}
```

**Comment by Zidane** [comment]
@Faithcaio Did you break this again?

**Comment by Faithcaio** [comment]
No?

**Comment by Aaron1011** [comment]
@LXGaming Can you re-test on the latest SpongeForge?

**Comment by LXGaming** [comment]
Still an issue on 3577

**Comment by Aaron1011** [comment]
@LXGaming: I can't seem to reproduce this. Can you confirm that this happens with no plugins (other than a plugin with just the custom listener you included)?

**Comment by LXGaming** [comment]
Confirmed on a completely fresh server.

Here is a YouTube video which demonstrates the issue: https://www.youtube.com/watch?v=134ziWPkSzk

Updated Event Code (To provided some reference to the chat messages)
```
@Listener
public void onPickup(ChangeInventoryEvent.Pickup event, @Root Player player) {
    player.sendMessage(Text.of(""));
    event.getTransactions().forEach(transaction -> {
        player.sendMessage(Text.of(TextColors.WHITE, "Original: ",
                TextColors.GREEN, transaction.getOriginal().getType().getId(), " x", transaction.getOriginal().getQuantity()));
            
        player.sendMessage(Text.of(TextColors.WHITE, "Final: ",
                TextColors.GREEN, transaction.getFinal().getType().getId(), " x", transaction.getFinal().getQuantity()));
    });
}
```

**Comment by LXGaming** [comment]
This issue isn't limited to a lava bucket it works with certain items such as consuming Food/Potions, Throwing Splash Potions/Ender Pearls/Eggs, Firing a bow and even equipping armor by shift right clicking while it's in your hand.

I've tracked the build that introduced this back to `spongeforge-1.12.2-2705-7.1.0-BETA-3293` & `spongevanilla-1.12.2-7.1.0-BETA-80` (Which are 7 months old)

Commits to SpongeCommon which were added to those builds:
https://github.com/SpongePowered/SpongeCommon/commits?since=2018-07-09T03:33:29Z&until=2018-07-13T18:30:32Z

Testing via an IDE it may have been caused by the Phase changes which occurred **after** https://github.com/SpongePowered/SpongeCommon/commit/2be420d3bd516bbb38f2ff2145f6b1bea4b34818
Currently unable to pin point the exact commit as most of them won't compile

**Comment by gabizou** [comment]
I'm not seeing the unexpected output in latest. Can you re-test?

**Comment by LXGaming** [comment]
I can still reproduce this on SpongeForge 3643 and in a Dev environment.

I believe this might be the cause:
https://github.com/SpongePowered/SpongeCommon/blob/7c673c7ea102562a5ba098f82f0114779eea901b/src/main/java/org/spongepowered/common/command/SpongeCommandManager.java#L332

`setCapture` is suppose to get set back to `false` here:
https://github.com/SpongePowered/SpongeCommon/blob/7c673c7ea102562a5ba098f82f0114779eea901b/src/main/java/org/spongepowered/common/event/tracking/phase/general/CommandState.java#L125

By throwing debug messages into the code I can see that `unwind` isn't getting called until AFTER its captured a transaction.

**Comment by LXGaming** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/7c673c7ea102562a5ba098f82f0114779eea901b/src/main/java/org/spongepowered/common/event/tracking/PhaseTracker.java#L319-L321

Because the `CommandPhaseContext` didn't capture anything unwind doesn't get called meaning `captureTransactions` doesn't get set back to `false`
