### ISSUE TITLE
Update to 1.10/15w14a

### ISSUE THREAD

**Issue by sam4215** [SpongePowered/Sponge#219]
Mojang's latest update has changed a few mechanics of Minecraft. I'd like some feedback to Sponge updating ASAP. First, a PR should be opened soon to support the love system. A PlayerDamageEvent is no longer needed, and the Entity Component System will need to update. Quite a few new Block Types will be needed.
Happy April Fools everyone :D

**Comment by Zidane** [comment]
Nice try but you forgot isFlowerPot.
