### ISSUE TITLE
World configuration arrays are being reset to 'null'

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/Sponge#2190]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-1.12.2-14.23.5.2768-7.1.6-RC3582.jar
- SpongeVanilla version: 
- Java version: 1.8.0_191-b12
- Operating System: CentOS 7.6

- Plugins/Mods:
none

**Issue Description**
By default, the world.conf has `block-blacklist=[]` and `world-generation-modifiers=[]`.
After restarting the server, they are `block-blacklist=null` and `world-generation-modifiers=null`.
After restarting the server, they remains set to null.
If I change to `world-generation-modifiers="sponge:void"`, then restart the server, it's changed again to `world-generation-modifiers=null`.
If I change to `world-generation-modifiers=["sponge:void"]`, then restart the server, it's changed again to `world-generation-modifiers=null`.
If I change to `world-generation-modifiers=["sponge:void"]`, then kill the server, delete the world folder, then restart the server, it's changed again to `world-generation-modifiers=null`.

Also to note, the world modifier doesn't seem to be taken into account, when present in the file.

**Comment by phit** [comment]
can't reproduce with spongeforge-1.12.2-2768-7.1.6-RC3586.jar

deleted world, went to `config/sponge/worlds/minecraft/overworld/world.conf`

and set
```
    world-generation-modifiers=[
        "sponge:void"
    ]
```

after starting the server the overworld is void, stopping and starting server left the config untouched

**Comment by LemADEC** [comment]
spongeforge-1.12.2-2768-7.1.6-RC3584.jar works with your syntax. I guess the line break is mandatory in that configuration file or something was fixed for in 3583 / 3584 ?

**Comment by phit** [comment]
didnt see any commits to anything touching it, so yeah i assume you need the line breaks
