### ISSUE TITLE
Player Inventory isViewingInventory() always true

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/Sponge#2194]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.6-RC3592
- SpongeVanilla version: 1.12.2-7.1.6-RC155
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
- Operating System: Windows 10 and Debian 9.6

- Plugins: MyTest
- Mods: None

**Issue Description**
Since the developers of mods often make the same mistake in work with the containers that open when using the item, I decided to fix this in my plugin. But then I ran into a problem. I can not find out whether the player is really open inventory.
I also checked this method `player.getOpenInventory().isPresent()`. The result is similar.

**Comment by Cybermaxke** [comment]
This is a limitation of the client. The client doesn't send a packet when the player inventory gets opened, so the server assumes it's always open.

**Comment by SawFowl** [comment]
So, I need to check the name of the open inventory?

**Comment by Cybermaxke** [comment]
Do you just want to know if a non player inventory is open?

**Comment by SawFowl** [comment]
I check if the player’s inventory is open, as well as the discarded object and whether there is an object with the same id in his main hand or if there is air there. 
If these conditions are met, then I close the player's inventory.

**Comment by SawFowl** [comment]
It seems I have found a way to get around this restriction.

```
if(!player.getOpenInventory().get().toString().contains("ContainerChest") && !player.getOpenInventory().get().toString().contains("ContainerPlayer")) {
		player.closeInventory();
}
```

**Comment by Zidane** [comment]
Checking the title is indeed one approach. Unfortunately this is a nasty attribute of how Inventories work in Minecraft.
