### ISSUE TITLE
Inventory Stack trace - phase tracker issue?

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Sponge#2196]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3594
- Forge:  1.12.2 - build 2814

Not sure what is causing this, randomly seeing this on server console:  https://gist.github.com/Dockter/ef048e321aa3ebc9416754d49a9049ee

Post this regardless of that fact by the request of @Zidane

**Comment by Dockter** [comment]
Tagging @Faithcaio

**Comment by Faithcaio** [comment]
Looks like `Container#slotClick` `this.inventorySlots.get(slotId)`.
No Mods?
Looks like the slotId is just wrong and there are no range checks before.

**Comment by Dockter** [comment]
I have quite a few (26) mods but the stack trace didn't point to anything.  Need additional information?

**Comment by Dockter** [comment]
Seems the bug may be triggered from the backpacks mod.  They haven't updated in a while and our inventory stuff changed so I have a feeling that its our changes causing this issue.

**Comment by Faithcaio** [comment]
Still happening @Dockter? Can you link the mod.
