### ISSUE TITLE
updateHealthPriorToArmor causing performance issues on large servers

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/Sponge#2198]
I've received numerous spark results from servers showing `updateHealthPriorToArmor` using 4-5% usage as its called every tick for each player.

Here are a few samples

https://sparkprofiler.github.io/?l09ftzunWm
https://sparkprofiler.github.io/?bNEgGLGEya

net.minecraft.entity.player.EntityPlayerMP.handler$updateHealthPriorToArmor$zhb000()4.05%
net.minecraft.entity.player.EntityPlayerMP.handler$updateHealthPriorToArmor$zhb000()2.46%

**Comment by ImMorpheus** [comment]
PR merged
