### ISSUE TITLE
Delayed scheduled task not executing after the specified delay

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/Sponge#220]
When scheduling a task with `SynchronousScheduler#runTaskAfter(Object plugin, Runnable task, long delay)`, the task is executed immediately, rather than after the specified delay.

I found this while developing a warps plugin, and so when I printed out the amount of ticks since the server started using `Server#getRunningTimeTicks()`, both when the command was sent and when the Runnable was run, the same value was outputted, indicating that there was indeed no delay.

**Comment by Minecrell** [comment]
@sibomots

**Comment by Zidane** [comment]
Last I tested this, it worked...I'll give it a whirl again.
