### ISSUE TITLE
Unable to change speed or direction of falling block

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Sponge#2200]
- SpongeForge version: spongeforge-1.12.2-2768-7.1.5-RC3542
- Java version: Java 8
- Operating System: Win 10

Im trying to make FallingBlock entity to fly slowly upwards. it appears no matter what velocity i set it never goes up. in fact this code creates a entity which is destroyed in the next tick. 

     iterator = BlockRay.from(entity.getLocation().getExtent(), position)
                .narrowPhase(false)
                .distanceLimit(range)
                .direction(direction)
                .iterator();

    //scheduled
        if (iterator.hasNext()) {
            BlockRayHit<World> next = iterator.next();
            Location<World> location = next.getLocation();
            World world = location.getExtent();

            Entity block = world.createEntity(EntityTypes.FALLING_BLOCK, next.getBlockPosition());
            block.offer(Keys.VELOCITY, new Vector3d(0,1,0));
            block.offer(Keys.FALLING_BLOCK_STATE, world.getBlock(next.getBlockPosition().add(0,-1,0)));
            world.spawnEntity(block);
        }

**Comment by randombyte-developer** [comment]
I once did a thing where a falling block floated in the air. I did this by adding the falling block to a marker armor stand as a passenger: https://github.com/randombyte-developer/free-blocks/blob/master/src/main/kotlin/de/randombyte/freeblocks/FreeBlock.kt#L83
Then disabling the gravity of the armorstand and giving it a velocity might work.

**Comment by ImMorpheus** [comment]
You're looking for https://github.com/SpongePowered/SpongeCommon/pull/2303

**Comment by ImMorpheus** [comment]
PR merged
