### ISSUE TITLE
Water tracking freezes server

### ISSUE THREAD

**Issue by phit** [SpongePowered/Sponge#2201]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3588
- SpongeVanilla version: n/a

- Plugins/Mods: none

**Issue Description**

crash with lots of water taking too long to process
https://gist.github.com/Krominicon/72b5c48728142d043eea892a1105b622

previous related issue https://github.com/SpongePowered/SpongeCommon/issues/1871

I'll add a test chunk for this once I have some time, right now this is more of a reminder for myself

**Comment by liach** [comment]
@phit Any warmroast report, etc.? That might help identifying the cause.

I have a similar fluid report from users about modded fluid at https://sparkprofiler.github.io/?XVBT2D74Sb , don't know if they are related.

**Comment by phit** [comment]
ill profile once i have the chunk to repro it, didn't have time yet to grab it from my server
the above stall report isn't from me even, just someone with the same issue was in discord

**Comment by phit** [comment]
test world https://phit.link/s/dawdadwadawd.zip
just go to -146, 62, -147

**Comment by gabizou** [comment]
Added extra handling and speed for performance with this. Also, can disable block captures (config for dynamic liquids I think is just disable block events for "Minecraft:flowing_water") + listen for ChangeBlockEvent.Pre to cancel liquids entirely.
