### ISSUE TITLE
Inventory close event not receive

### ISSUE THREAD

**Issue by james58899** [SpongePowered/Sponge#2205]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.6-RC3604
- SpongeVanilla version: N/A
- Java version: OpenJDK 1.8.0_202-b26
- Operating System: Arch Linux

- Plugins/Mods:
```
Plugins (10): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, LuckPerms, OKTW Galaxy, PacketGate, SpongePrometheusExporter, VillageMarkerSponge, i18n

Mods (15): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AppleSkin, FoamFix, FoamFixCore, JMFixer, JourneyMap, Just Enough Items, RandomPatches, SpongeForge, VanillaFix
```

**Issue Description**
Use `Inventory.builder()` register event listener cannot receive close event

Can receive event use `@Listener` on plugin main class

Can receive event on SF 1.12.2-2768-7.1.6-RC3575, but RC3576 broken

**Comment by XakepSDK** [comment]
Show your code and listener

**Comment by james58899** [comment]
builder https://github.com/OKTW-Network/Galaxy/blob/ac8800b9555fd379bedfe864ed568154c395f094/src/main/kotlin/one/oktw/galaxy/gui/Confirm.kt#L46

listener https://github.com/OKTW-Network/Galaxy/blob/ac8800b9555fd379bedfe864ed568154c395f094/src/main/kotlin/one/oktw/galaxy/gui/GUI.kt#L53

it can receive other event but close not received

**Comment by james58899** [comment]
oops click wrong button

**Comment by XakepSDK** [comment]
@Aaron1011 looks like event fired after inventory closed, so your change removes listener before event fired, but i'm not sure.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/9f886382ffc1aa5739d5946f6ea46bedefc51519
