### ISSUE TITLE
Server.copyWorld() gives same dimensionIDs if world copied multiple times

### ISSUE THREAD

**Issue by GlassSpirit** [SpongePowered/Sponge#2206]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5
- Java version: 1.8
- Operating System: Windows 7

**Issue Description**
`Sponge.getServer().copyWorld()` gives same dimensionIDs for copied worlds if that world is copied multiple times.
For example if I copy default world with `dimensionId = 0`, first copied world would have `dimensionId = 2` because of nether and end. But if I copy default world more times, all copied worlds would have `dimensionId = 2`.
I think copyWorld doesn't properly update latest dimensionId value.

As I see from SpongeCommon code, dimensionId's are stored in `org.spongepowered.common.world.WorldManager.class` in `worldFolderByDimensionId` map and `dimensionBits` BitSet.
When worlds are loaded by game, `dimensionBits `and `dimensionTypeByDimensionId` are somehow populated, but when new worlds are created by `WorldManager.createWorldProperties()` or `WorldManager.copyWorld()`, dimensionId is get by `getNextFreeDimensionId()`, which gets first free id from dimensionBits, but doesn't change it anyhow (!).
So all next worlds created by that methods would have same dimensionId, which can break a lot of things...

**Comment by Zidane** [comment]
Closed in PR that was merged.
