### ISSUE TITLE
Inventory close event never fired

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#2208]
SpongeForge version: `spongeforge-1.12.2-2768-7.1.6-RC3616`

Probably introduced in https://github.com/SpongePowered/SpongeCommon/commit/c5234c33e88a67b3b4d183e93a7cfd898b942bc4

Maybe a duplicate of #2205. I've got a minimal working example: https://github.com/randombyte-developer/sponge-inv-listener-bug
Plugin class (for saving just a few clicks): https://github.com/randombyte-developer/sponge-inv-listener-bug/blob/master/src/main/java/de/randombyte/test/SpongeInvListenerBug.java

After calling the `/test` command, then inventory opens. When closing the inventory, the message `Inventory closed!` is *not* shown.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/9f886382ffc1aa5739d5946f6ea46bedefc51519

**Comment by KhaozFrost** [comment]
ProDrifter7Today at 7:47 PM
-new Furnaces are broken. When you go to smelt your items it takes you out the furnace with your items and then locks it self and you can't re open it, also when you mine the furnace and replace it, it still locked.

**Comment by Aaron1011** [comment]
@KhaozFrost See https://github.com/SpongePowered/SpongeForge/issues/2639
