### ISSUE TITLE
Cannot teleport players across worlds

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/Sponge#221]
The API docs say that the `Entity#setLocation(Location location)` method is "equivalent to a teleport", but it seems to only work when the target location to teleport the player to is in the same World as the Player's current World. For example, if I execute the following (assuming the Player is currently in the Overworld, and `myWorld` is the Nether):

``` java
Location newLoc = new Location(myWorld, new Vector3d(x, y, z));
boolean success = player.setLocation(newLoc);
System.out.println("Teleport success: " + success);
```

The player would not be teleported, but the success boolean would still be true.

However, if the player is already in the Nether and the code is executed, they would be teleported, and `success` would be true, like it should be.

**Comment by Zidane** [comment]
This is being addressed in this branch:
https://github.com/SpongePowered/Sponge/tree/feature/world-creation

**Comment by bloodmc** [comment]
@RobertHerhold This has been fixed in my world-creatoin branch PR #218 which should be pulled soon.

**Comment by RobertHerhold** [comment]
@bloodmc Sounds good! Thanks for the quick resolution.

**Comment by bloodmc** [comment]
@RobertHerhold fixed in https://github.com/SpongePowered/Sponge/commit/55175a11f7327a42c20f6f1f9e20307c4ca3058e
