### ISSUE TITLE
NPE inside TextComponentString

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#2216]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.6-RC3624
- Forge version: 1.12.2-14.23.5.2815

Exception: https://gist.github.com/XakepSDK/7aa9dd628e7621ff0f50377148fbb0bc
Line with problem: https://github.com/NipoCN/TabModifier/blob/master/src/me/nipo/tabmodifier/commands/CommandRefresh.java#L95

Mods and plugins list: https://gist.github.com/XakepSDK/5a00a56f6c944f02fa0bbce024800de8

**Comment by ImMorpheus** [comment]
Nothing to do with Sponge.

Report to TabModifier.

**Comment by XakepSDK** [comment]
Isn't sponge work to catch all nulls before they go deeply in implementation?
It fails in `ITextComponent#createCopy`, somehow `Text` got `null` inside.
