### ISSUE TITLE
Array out of bounds on DataView manipulation

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#2222]
On SV 1.12.2-7.1.6-RC156, `DataView#set(DataQuery.of(), "test")` triggers an `ArrayIndexOutOfBoundsException`.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/7af4bde2a110f7dcdcb5917a7a3275ede7baad3b
