### ISSUE TITLE
Project Red & CC: Tweaked issues with updating

### ISSUE THREAD

**Issue by TheSpicePhantom** [SpongePowered/Sponge#2227]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3629.jar
- SpongeVanilla version: -
- Java version: 1.8.0_201-b09
- Operating System: Linux - Ubuntu 16.04/16.02 (not sure) LTS

- Plugins/Mods:

 Advanced Machines
 Advanced Solar Panels
 AE2 Stuff
 AppleSkin
 Applied Energistics 2
 Aroma1997's Dimensional World
 Aroma1997Core
 asielib
 AutoRegLib
 Baubles
 BD Lib
 BiblioCraft
 Binnie's Botany
 Binnie's Design
 Binnie's Extra Bees
 Binnie's Extra Trees
 Binnie's Genetics
 Binnie Core
 Blockcraftery
 BuildCraft
 BuildCraft Builders
 BuildCraft Compat
 BuildCraft Energy
 BuildCraft Factory
 BuildCraft Lib
 BuildCraft Robotics
 BuildCraft Silicon
 BuildCraft Transport
 CC: Tweaked
 Charset
 Chisel
 Chisels & Bits
 CodeChicken Lib
 CoFH Core
 CoFH World
 Compact Solar Arrays
 Computronics
 Crafting Tweaks
 CraftTweaker2
 CraftTweaker JEI Support
 Diet Hopper
 EnderStorage
 Energy Converters
 Fancy Fluid Storage
 FastWorkbench
 Flat Colored Blocks
 FoamFix
 FoamFixCore
 Forestry
 Forge Microblocks
 Forge Mod Loader
 Forge Multipart CBE
 FTB Library
 FTB Utilities
 FTB Utilities: Backups
 Gravitation Suite
 GravityGun
 Guide-API
 Harvest
 iChunUtil
 Immersive Cables
 Immersive Engineering
 IndustrialCraft 2
 Industrial Foregoing
 Integration Foregoing
 Inventory Tweaks
 Iron Chest
 JEI Bees
 Just Enough Energistics
 Just Enough Items
 Long Fall Boots
 MachineMuse's Modular Powersuits
 MagicBees
 MCMultiPart
Minecraft
 Minecraft Coder Pack
 Minecraft Forge
 Minecraft Multipart Plugin
 MineTogether
 MineTogetherServer
 Mod Tweaker
 Modular ForceField System
 Modular Routers
 Morpheus
 Morph-o-Tool
 MrTJPCore
 MTLib
 Mystical Lib
 Netherending Ores
 Numina
 Placebo
 Player Plates
 PortalGun
 projectred-compat
 ProjectRed Core
 ProjectRed Expansion
 ProjectRed Exploration
 ProjectRed Fabrication
 ProjectRed Illumination
 ProjectRed integration
 ProjectRed Relocation
 ProjectRed Transmission
 ProjectRed Transportation
 ProjectX 2
 Railcraft
 RandomPatches
 Reborn Core
 Redstone Flux
 Reliquary
 Retro Exchange
 Shadowfacts' Forgelin
 Silverfish
 Simple Corn
 Smooth Font Core
 Soul Shards Respawn
 Sponge
 SpongeAPI
 SpongeForge
 Steve's Carts 2
 Tech Reborn
 Tech Reborn Mod Compatibility
 Tesla Core Lib
 Tesla Core Lib Registries
 Thaumcrafft Inventory Scanning
 Thaumcraft
 Thaumic Energistics
 Thaumic Tinkerer
 The One Probe
 Thermal Dynamics
 Thermal Expansion
 Thermal Foundation
 The Twilight Forest
 TOP Addons
 TorchMaster
 Traverse
 UniDict
 WanionLib
 WirelessRedstone-CBE
 World Control
 YABBA

**Issue Description**
Workaround that fixes at least this issue atm: spongeforge-1.12.2-2768-7.1.6-RC3616.jar

Mods that didn't work correctly: 
 - CC: Tweaked
 - Project Red
 - Maybe some more, didn't test all.

What didn't work:

- CC: Tweaked
  - Turtles and Computers would reset after 2 seconds of running their programs

- Project Red
  - Timer:
    - It works, but doesn't output signal to any adjacent cables or redstone dust
![2019-03-29_21-06-18](https://user-images.githubusercontent.com/12653237/55261986-b9489c80-526c-11e9-8309-1ecfdc0ca85f.gif)

**With Workaround**
![2019-03-29_21-25-17](https://user-images.githubusercontent.com/12653237/55262047-e9903b00-526c-11e9-9987-2eff477eb7e4.gif)

**Comment by selkiess** [comment]
I can confirm this is an issue with the latest spongeforge build as well.

Besides the timer from ProjectRed not outputting I have also witnessed redstone output breaking for many of its redstone gates and redstone wire not updating.

An easily repeatable way to reproduce the weird behavior is to hook up:

Timer -> minecraft repeater -> NOT gate -> anything switching by redstone

The initial cycle works fine but the NOT gate will cease to output after the initial redstone signal disables it. Breaking redstone that is connected to the output or input of the not gate and replacing it causes the redstone to revert to correct behavior.
![not gate](https://user-images.githubusercontent.com/18093341/55678625-c7c93080-58ca-11e9-847c-02e904912873.png)
