### ISSUE TITLE
Register event listeners with protected/default/private access modifiers

### ISSUE THREAD

**Issue by boformer** [SpongePowered/Sponge#223]
Right now it is only possible to register events in public classes with public event listener methods.

1. It is possible to register protected/default/private event listener **classes**, but when Sponge tries to call the methods, a ``java.lang.IllegalAccessError`` is thrown.
2. Sponge ignores non-public event listener **methods**, except for the ``onPreInitialization`` method (why???):
```java
@Plugin(id = "spongetest", name = "SpongeTest", version = "0.1.0")
public class SpongeTestPlugin {

    @Inject
    private Logger logger;

    @Subscribe
    private void onPreInitialization(PreInitializationEvent event) {
        // not ignored WTF?
        logger.info("Sponge Test plugin loaded.");
    }
    @Subscribe
    private void onCommand(CommandEvent event) {
        // ignored
    }
    @Subscribe
    void onPlayerJoin(PlayerJoinEvent event) {
        // ignored
    }
    @Subscribe
    protected void onPlayerChat(PlayerChatEvent event) {
        // ignored
    }
    @Subscribe
    public void onPlayerQuit(PlayerQuitEvent event) {
        // not ignored
    }
}
```

I would like to have both options: Register non-public event classes, and non-public event methods. Is it possible?

**Comment by Mumfrey** [comment]
Use case?

**Comment by boformer** [comment]
@Mumfrey I don't want all of my classes and methods are visible for other plugin developers.

Let's say you have an interface ``WelcomeService`` (welcomes new players with a message that can be set by other plugins).

The implementation ``SimpleWelcomeService`` needs a public method ``onPlayerJoin(...)`` to listen to the ``PlayerJoinEvent``. The class also has to be public.

Other plugins should only use the interface ``WelcomeService`` to interact with the class. The implementing class should not be public. 

I could also create the service without the interface, and let other plugins interact directly with the class. In that case, I don't want that the event handler method is public.

**Comment by ZephireNZ** [comment]
There's definitely a point of using an interface for something like this, but I agree that making it a requirement that events be public can be annoying for plugins that are used by other plugins.

**Comment by progwml6** [comment]
event handler methods should always be public this is how EVERY event handling system with annotations works. we shouldn't be slowing them down by forcing the access to be changed to public at runtime

**Comment by simon816** [comment]
So to be consistent, the access change [here](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/plugin/SpongePluginContainer.java#L139) should be removed?
That would explain why `PreInitializationEvent` is not ignored.

**Comment by Minecrell** [comment]
IMO even the state event handlers should go through our event bus instead of being called separately. This would make this consistent for these and for the other events.

**Comment by progwml6** [comment]
@minecrell I disagree state events are not normal events and can't be fired by plugins

@simon816 it probably should

Also...
Keep events public in plugins we shouldn't be slowing down the event handlers for access changes

@bloodmc I reccomend closing this once preinit is fixed

**Comment by Minecrell** [comment]
@progwml6 That doesn't mean we can't use our existing environment for calling event handler methods, which is also more performant than the current reflection way. Also, in what way does this prevent firing state events by plugins?

**Comment by gabizou** [comment]
The most obvious issue is that if your event listener is so delicate that you don't want people to be calling the actual method, dev are just going to call their own created event and you'd still have the same problem.

Having code design like this is just bad. I encourage you to redesign your plugin to handle it's own restrictions.
