### ISSUE TITLE
Changes in `UserStorageService` not tracked

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#2232]
In order to resolve SpongePowered/SpongeAPI#1989 satisfactorily, the classes which hold onto `UserStorageService` instance variables will need to update them on service provider change.

**Comment by Defman** [comment]
```
MixinEntity
MixinEntity_Tracker
MixinChunk_Tracker
```
Are all the classes which contains a field reference to `UserStorageService`.

**Comment by phit** [comment]
Feel free to open this if this gets added to API, right now this issue isn't really relevant unless I'm missing something?

**Comment by pie-flavor** [comment]
I mean it is still, it's a bug for it not to know who is storaging users, whether not it's actually possible to create one yet.
