### ISSUE TITLE
Created worlds ignoring set parameters

### ISSUE THREAD

**Issue by trentech** [SpongePowered/Sponge#2240]
**I am currently running**
- SpongeForge version: 
- SpongeVanilla version: spongevanilla-1.12.2-7.1.6-RC156
- Java version: 1.8.0_211
- Operating System: Windows 1

When creating a world certain parameters appear to be ignored however properties do display as set. For example setting a specified seed to a world, when running /seed, the correct seed is displayed however the world is generated completely different from the expected results. Tested this a couple of known seeds from the web. Also flying around appears no structures are being generated nor have I found a bonus chest at spawn. Code snippet below.

```
        WorldArchetype.Builder builder = WorldArchetype.builder();
 
        builder.generateBonusChest(true);
        builder.usesMapFeatures(true);
       
        try {
            Long s = Long.parseLong(value);
            builder.seed(s);
        } catch (Exception e) {
            builder.seed(value.hashCode());
        }
       
        WorldArchetype settings = builder.enabled(true).keepsSpawnLoaded(true).loadsOnStartup(true).build(args.get(0), args.get(0));
 
        WorldProperties properties;
        try {
            properties = Sponge.getServer().createWorldProperties(args.get(0), settings);
        } catch (IOException e) {
            e.printStackTrace();
            throw new CommandException(Text.of(TextColors.RED, "Something went wrong. Check server log for details"), false);
        }
 
        Sponge.getServer().saveWorldProperties(properties);

```

**Comment by dualspiral** [comment]
> For example setting a specified seed to a world, when running /seed, the correct seed is displayed however the world is generated completely different from the expected results

That specific thing should have been fixed by https://github.com/SpongePowered/SpongeCommon/pull/2234.

Can you update to SV 160 and recheck? 156 is over a month an a half old.

**Comment by trentech** [comment]
ah, Last I check 157 was the latest but contained a game breaking bug. Will update and re-run tests. Thanks

**Comment by trentech** [comment]
Confirmed, this is a non issue on SV 160. Thanks
