### ISSUE TITLE
Issue with async light thread and regeneration

### ISSUE THREAD

**Issue by NeusFear** [SpongePowered/Sponge#2245]
**I am currently running**
- SpongeVanilla version:  1.12.2-7.1.6-RC163
- Java version: 1.8
- Operating System: Windows 10 and Ubuntu 16.04
- Plugins/Mods: Sponge, Worldedit, Voxelsniper, and my server's plugin

**Issue Description**
For my use case, I have created a world populator that before I have set a location to allow generation, it never generates any blocks. Now, this worked fine in RC156, however, since updating to RC163 this does not work.
https://gist.github.com/NeusFear/86bef9ef2123cbf9f8354a536291014a
And I would regenerate the chunks later using:
https://gist.github.com/NeusFear/3677821ad5f85cc5c0169c53721ff8f1
in a command.

Additional errors that happen when using this are errors with the Async Light Thread: https://gist.github.com/NeusFear/9e20d9286e7bfd301ef71b5874716c70
If I turn off the thread, the thread doesn't error, of course, however previous issues persist.

If you need more information or more code snippets let me know.

**Comment by Cybermaxke** [comment]
The async lighting error should be fixed with: https://github.com/SpongePowered/SpongeCommon/commit/a5d41cb149c2e0a7f7dac2f626eb12719ac79957
