### ISSUE TITLE
Entity AI has no dimension sanity checks (MC-149563)

### ISSUE THREAD

**Issue by aromaa** [SpongePowered/Sponge#2248]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.6-RC3671
- SpongeVanilla version: 1.12.2-7.1.6-RC165
- Java version: Java 8
- Operating System: Windows 10
- Plugins/Mods: None

**Issue Description**
Entity AI has no dimension sanity checks, this can lead to players being attacked by mobs in other world, more detailed report on: https://bugs.mojang.com/browse/MC-149563

This is more plausable on server software that supports multiple worlds

**Comment by JBYoshi** [comment]
Can reproduce on 3881 using [this code](https://gist.github.com/JBYoshi/9c212e5550ea40b2e29bdcf4eb1d7a65) (not a valid plugin by itself; patch as needed). The smoke shows the location of the zombie in another dimension. Once the zombie dies from sunlight, both dimensions will be deleted. (Note that the entity activation range plugin must be turned off or [patched in this method](https://github.com/SpongePowered/SpongeCommon/blob/da4a779dbb07ee2950143ae049edc957d3dc1dc0/src/main/java/org/spongepowered/common/mixin/plugin/entityactivation/EntityActivationRange.java#L390).)
