### ISSUE TITLE
Furnaces eject items, sometimes destroying the ore in the process.

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/Sponge#2254]
**I am currently running**

- SpongeForge version: 1.12.2 7.1.6 RC3682 
- SpongeVanilla version: 1.12.2-7.1.6-RC166 
- Operating System: Windows 10

- Plugins/Mods: Nucleus, LuckPerms

**Issue Description**
Furnaces just puke their items out for no apparent reason. They seem to be acting like they're breaking. The cooking process freezes in them as well. On occasion it seems like the process destroys the raw materials being cooked

**Comment by johnfriedrich** [comment]
99% same issue could be closed probably
https://github.com/SpongePowered/SpongeForge/issues/2725

**Comment by gabizou** [comment]
Yeah, can be closed.
