### ISSUE TITLE
UseItemStackEvent.Replace errors

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#2255]
```java
@Listener
public void onUse(UseItemStackEvent.Replace e) {
    ItemStack stack = e.getItemStackResult().getOriginal().createStack();
}
```
This throws a CCE because n.m.i.ItemStack can't be cast to o.s.a.i.i.ItemStackSnapshot.

**Comment by Lignium** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/7c50d60ef9f897267c7503e580f35a0a112cc60a/src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntityLivingBase.java#L1241
