### ISSUE TITLE
Can't use SetToTransform on MoveEntityEvent anymore

### ISSUE THREAD

**Issue by runescapejon** [SpongePowered/Sponge#2257]
**I am currently running**

- SpongeForge version: RC3689
- SpongeVanilla version: n/a
- Java version: 8
- Operating System: windows 10

- Plugins/Mods:
n/a

**Issue Description**
it seem that there a bug not being able to use form of teleportation on MoveEntityEvent 
here an example i use 
```
@Listener
public void OnMove(MoveEntityEvent event, @Getter("getTargetEntity") Player player) {
		event.setToTransform(event.getFromTransform().setLocation(player.getWorld().getSpawnLocation()));
}
```
this method doesn't work but when i roll back to SF-RC3512 this method work fine.

**Comment by Zidane** [comment]
Try the latest SF, I believe this is resolved.

**Comment by runescapejon** [comment]
Test it on version SF `RC3731` and it's not fix.

**Comment by Zidane** [comment]
I'll look into this-this evening and let you know.

**Comment by Zidane** [comment]
Closed in latest SpongeForge that got bumped with latest SpongeCommon. SpongeVanilla will get bumped shortly.
