### ISSUE TITLE
Support TameEntityEvent for Mountable Entities

### ISSUE THREAD

**Issue by SarahGreyWolf** [SpongePowered/Sponge#2260]
**I am currently running**
- SpongeVanilla version: 1.12.2-7.1.6-RC169

**Issue Description**
Requesting support for TameEntityEvent for Mountable Entities such as Horses and related entities.

**Comment by ImMorpheus** [comment]
Horses were the last one for which the event was not fired.

Fixed by https://github.com/SpongePowered/SpongeCommon/commit/7a19f298f6b998fbe9106860181df01b5eefedcb
