### ISSUE TITLE
BiomeType ids are inconsistent with field names

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Sponge#2264]
Sponge [renames several Minecraft biome types](https://github.com/SpongePowered/SpongeCommon/blob/953811eaa27f3bcdd75d71960b7b4f93fb160087/src/main/java/org/spongepowered/common/registry/type/world/gen/BiomeTypeRegistryModule.java#L99-L133), in order to properly map them to fields in `BiomeTypes`. However, the ids returned by `BiomeType#getId` are the old, un-renamed ids. This can be confusing for plugin developers: For example, calling `Sponge.getRegistry().getType(BiomeType.class, "mesa_plateau_mountains"` will return `Optional.empty()`, despite `BiomeTypes.MESA_PLATEAU_MOUNTAINS` existing.

**Comment by kashike** [comment]
This is no longer an issue after the registry refactor.
