### ISSUE TITLE
UserDiscoverer not catching UTFDataFormatException

### ISSUE THREAD

**Issue by phit** [SpongePowered/Sponge#2266]
**Issue Description**

looks like this isn't catching malformed nbt just io exceptions, should probably handle that too and not crash

https://gist.github.com/phit/a14a45487c743b83ab1bcf0236d616b3

https://github.com/SpongePowered/SpongeCommon/blob/ff1377197715e1266080e6a7a607647fb5af0416/src/main/java/org/spongepowered/common/service/user/UserDiscoverer.java#L303-L307

**Comment by simon816** [comment]
`UTFDataFormatException` is a subclass of `IOException` so i'm not sure what's going on there

**Comment by JBYoshi** [comment]
Could you post a sample player data file?

**Comment by simon816** [comment]
This explains it:
`NBTTagCompound.readNBT` catches the `IOException` and re-throws it as a `ReportedException`.

```java
        try
        {
            nbtbase.read(input, depth, sizeTracker);
            return nbtbase;
        }
        catch (IOException ioexception)
        {
            CrashReport crashreport = CrashReport.makeCrashReport(ioexception, "Loading NBT data");
            CrashReportCategory crashreportcategory = crashreport.makeCategory("NBT Tag");
            crashreportcategory.addCrashSection("Tag name", key);
            crashreportcategory.addCrashSection("Tag type", Byte.valueOf(id));
            throw new ReportedException(crashreport);
        }
```
