### ISSUE TITLE
Bug with schematics. Containers is empty.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/Sponge#2268]
**I am currently running**
- SpongeForge version: 1.12.2-2825-7.1.6-RC3713
- SpongeVanilla version: 1.12.2-7.1.6-RC178
- Java version: OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
- Operating System: Debian 9

- Plugins: FastAsyncWorldEdit, GriefPrevention, Nucleus, SkyClaims, WorldEdit

**Issue Description**
When you insert a schematic, its existing containers become empty. There are no errors in the console while inserting the schematics.
The FastAsyncWorldEdit plugin cannot save schemas normally, there is an error in the console.
`
[12:23:09 ERROR] [STDERR]: мая 20, 2019 12:23:09 PM com.sk89q.worldedit.command.SchematicCommands save
[12:23:09 ERROR] [STDERR]: INFO: [WorldEdit] Mr_Krab saved /home/skytech/config/sponge/plugins/worldedit/schematics/fb0210a3-b65c-3dc6-927b-a8bd2ddb4e3b/test.schematic
`

**Comment by Aiidoneus** [comment]
Possibly related to https://github.com/SpongePowered/SpongeForge/issues/2761 ?

**Comment by SawFowl** [comment]
It looks like it. But as I noticed, the problem is observed with all containers. Even with vanilla.

**Comment by phit** [comment]
please retest on RC3723

**Comment by SawFowl** [comment]
I have already done the preliminary test. When inserting a previously created schematic, the containers are still empty, but if you make a new one, then the items in the containers seem to be saved and inserted as expected. In the near future I will conduct more tests, since I have not checked everything yet.

**Comment by phit** [comment]
previously created, as in when this bug was active? that's expected, as long as schematics made months ago and new ones work fine this bug is fixed

**Comment by SawFowl** [comment]
Schemes were created more than six months ago. And when they are inserted, the containers are empty.
This is the schematic for the SkyClaims plugin. It is inserted without errors on version 1.12.2-2768-7.1.6-RC3682. On newer versions the chest is empty.
[classic.zip](https://github.com/SpongePowered/SpongeCommon/files/3232375/classic.zip)
