### ISSUE TITLE
Dispenser Phase Tracker Issue

### ISSUE THREAD

**Issue by kencinder** [SpongePowered/Sponge#2269]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6-RC3713
- Java version: OpenJDK 1.8.0_211
- Operating System: Debian 9

- Plugins/Mods: None

**Issue Description**

Place a Dispenser in front a double flower such as a rosebush, put bone meal inside and activate the dispenser with redstone in any manner.
The expected behaviour is for a flower to be dropped, none is dropped and the linked gist is what occurs in the server log upon doing the aforementioned.

https://gist.github.com/kencinder/1d778a9a5e7ed71016c016c120fdc0d3

This also occurs back on SF 7.1.6 RC3616 which we are running on production, I tested on latest to be sure it wasn't fixed already.

**Comment by JBYoshi** [comment]
I can't seem to reproduce this on the latest development versions of either SpongeForge or SpongeVanilla. Is this the correct setup?
![2019-05-24_10 33 36](https://user-images.githubusercontent.com/12983479/58339595-8c99a700-7e0f-11e9-8310-ee14a6c67af4.png)

**Comment by kencinder** [comment]
Correct setup, I just tested it again on spongeforge-1.12.2-2825-7.1.6-RC3716 and is not working. You get the particle effects, and nothing drops and the same thing shows up in the server log.

**Comment by JBYoshi** [comment]
This should be fixed in the next build.

**Comment by kencinder** [comment]
Is fixed, thank you.
