### ISSUE TITLE
Nether portal sounds after each cross world teleport

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/Sponge#2273]
**I am currently running**

- SpongeForge version: 3740
- SpongeVanilla version: ----
- Java version: 202

Mods: Pixelmon and own plugins that do teleports(homes/teleport/spawn etc.
But even nucleus does this. So probably not bad code.

Players started reporting nether portal sounds after each crossworld teleport.
Maybe? Due to this commit?
https://github.com/SpongePowered/SpongeCommon/commit/409dd6ac866e7a1c636b65066b78e173bf64e98f

**Comment by Zidane** [comment]
rofl this is the funniest bug I've heard in a while.

**Comment by Zidane** [comment]
Fixed in latest SF.
