### ISSUE TITLE
The message when kicking a player is not coloured correctly

### ISSUE THREAD

**Issue by DoNotSpamPls** [SpongePowered/Sponge#2279]
**I am currently running**
- SpongeVanilla version: 1.12.2-7.1.5
- Java version: 1.8.0_211
- Operating System: Windows 10 Version 1903

- Plugins/Mods: None!

**Issue Description**
When kicking a player with a coloured message (for example, `/kick DoNotSpamPls §cThis is a test!`), only the first word, in this case - "This", is coloured. The rest of the message is white.

**Comment by phit** [comment]
did you test that this isn't the case in vanilla?

**Comment by DoNotSpamPls** [comment]
Thanks for the heads-up, apparently it's an upstream bug, since it also happens on Vanilla. In that case, where should my bug report go?

**Comment by Zidane** [comment]
I would put it on the Vanilla issue tracker for Mojang but it will never get fixed in 1.12.2.

Now if you do so, we can consider (and I stress consider) patching this on Sponge's end and note the ticket it was patching in the comments.

**Comment by Zidane** [comment]
I am going to close this as it is not a Sponge bug.

**Comment by DoNotSpamPls** [comment]
From what I see, the issue has been fixed in 1.14.2, so reporting on the Vanilla tracker wouldn't be helpful. I'm going to wait for the eventual SpongeAPI 8 release, although it'd be nice if a patch can be considered for API 7 😛
