### ISSUE TITLE
Define behaviour of the Y coordinate for chunks

### ISSUE THREAD

**Issue by DDoS** [SpongePowered/Sponge#228]
Right now the API has getChunk(Vector3i) and other similar methods where the Y coordinate is used for chunks. A quick look at the implementation shows that this coordinate is ignored, as Minecraft only has a single layer of chunks.

I propose to instead define all chunks at Y = 0 and return no chunks for any other Y values.

This is to improve cross implementation compatibility.

**Comment by ST-DDT** [comment]
This sounds reasonable to me. But we should then add s9me kind of helper method to world to allow us checking the valid y bounds of chunk koordinates. For default worlds this will be always one or zero if we use indexes. Vector3i getPotentialMinChunk = (-3*10^7/16; 0; -3*10^7/16?) and getPotentialMaxChunk = (3*10^7/16; 0; 3*10^7/16?)

**Comment by modwizcode** [comment]
Maybe having a XZ-plane specific version of our position class could be used. I think that would be very helpful, since for maps I only have two coordinates to set, but the getY on Vector2i implies that Y is the value, which is incorrect.

**Comment by simon816** [comment]
I believe similar discussion was held on https://github.com/SpongePowered/SpongeAPI/issues/70, it was decided that 2-component vectors should always be `(X, Y)` and not `(X, Z)`

**Comment by DDoS** [comment]
Yeah, we're not replacing vector2. Also we want to keep the Y coordinate to support implementations that could have 3D chunks.

**Comment by OscarOrSomething** [comment]
What if y=-1 returned the whole chunk and any other returned the appropriate chunk? If I remember correctly, Minecraft world saves split chunks vertically as well.

**Comment by Zidane** [comment]
@OscarOrSomething 

You are thinking of what is called a "ChunkSection". In Minecraft, a Chunk is 16x256x16.

**Comment by DDoS** [comment]
There's no reason why chunks couldn't also be infinite in negative y. Returning a whole column is also impossible in implementations that has infinite vertical chunks.

**Comment by OscarOrSomething** [comment]
@Zidane Oh yeah, Sorry.

*fades into background*

**Comment by DDoS** [comment]
I'm thinking about adding a ChunkSpaceInfo singleton class to the API to provide a description of the chunk layout. This include chunk dimensions, coordinate ranges for each axes, methods to check if coordinates are valid and methods to convert between chunk and block.

@Zidane Do you know where I could put a reference an instance of this class?

**Comment by Zidane** [comment]
@DDoS 

util.world perhaps? Shorthand it to ChunkInfo?

**Comment by DDoS** [comment]
ChunkInfo suggests that it relates to chunks. This is more about the layout of the space that contains the chunks.

Also, I was talking about where to put the reference to the singleton. For example `world.getChunkSpaceInfo()`. This could also be a constant (although a method would make implementation easier).

**Comment by DDoS** [comment]
It's going to go in Server, as `getChunkLayout()`. The class will be named `ChunkLayout`. Server was chosen because it can be easily obtained and the layout would be expected to be server wide, not world specific.

**Comment by DDoS** [comment]
PR'd!

https://github.com/SpongePowered/SpongeAPI/pull/581

**Comment by Mumfrey** [comment]
> You are thinking of what is called a "ChunkSection". In Minecraft, a Chunk is 16x256x16.

Actually for clarity, in minecraft a `Chunk` is actually 16x16x16. The construct of vertical chunks which historically was a `Chunk` is now a `ChunkColumn`.

**Comment by Zidane** [comment]
@DDoS has defined this appropriately.
