### ISSUE TITLE
DragonEgg is affected by gravity too

### ISSUE THREAD

**Issue by RedRelay** [SpongePowered/Sponge#2280]
Hi,

DragonEggs are affected by gravity but are not assignable from FallingBlock class.
That's weird but maybe it property GravityAffected must be added, isn't it ?

https://github.com/SpongePowered/SpongeCommon/blob/6ffd99fdb7ac0c0f47586230e3bc7183dbd9eb63/src/main/java/org/spongepowered/common/data/property/store/block/GravityAffectedPropertyStore.java#L48

**Comment by Zidane** [comment]
Closed in latest SpongeCommon. The next time we do a SpongeForge or SpongeVanilla build this will be included. Thanks!
