### ISSUE TITLE
ConnectedDirectionData seems to be broken on vine blocks

### ISSUE THREAD

**Issue by RedRelay** [SpongePowered/Sponge#2288]
- SpongeForge version: 7.1.0
- Java version: OpenJDK Hotspot 1.8
- Operating System: W10

As described here :

https://forums.spongepowered.org/t/blockvine-connecteddirectiondata-seems-to-be-broken/29212

ConnectedDirectionData seems to be broken on vine blocks.
Maybe it is a minecraft native behavior.

**Comment by JBYoshi** [comment]
> Direction.UP is never set when using connectedDirections()

This is the intended behavior. `ConnectedDirectionData` is only used for horizontal connections.

```java
public interface ConnectedDirectionData extends DataManipulator<ConnectedDirectionData, ImmutableConnectedDirectionData> {
    SetValue<Direction> connectedDirections();
    Value<Boolean> connectedNorth();
    Value<Boolean> connectedSouth();
    Value<Boolean> connectedEast();
    Value<Boolean> connectedWest();
}
```

> I think BlockVine should have a DirectionalData for facing AND a ConnectedDirectionData for attachment in side block or upside vine.

I don't think that would work. `DirectionalData` only lets each block be connected in one direction, but vines can be connected in multiple directions.

```java
public interface DirectionalData extends DataManipulator<DirectionalData, ImmutableDirectionalData> {
    Value<Direction> direction();
}
```

**Comment by JBYoshi** [comment]
As far as the `up=false` part in `toString()`, it’s only set to true on the client, when it displays the block. That string representation is generated by the original Minecraft code, not by ConnectedDirectionData.

**Comment by gabizou** [comment]
UP is part of extended block state properties. Much like https://github.com/SpongePowered/SpongeCommon/issues/2284, you can get the up value, but it can't be set on the server since it is evaluated only on client rendering. 1.14 eliminates these extended states.
