### ISSUE TITLE
WorldArchetype SerializationBehaviors.NONE not obeyed

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/Sponge#2291]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.7-RC3768
- Java version: 1.8.0_202/64-bit (Oracle Corporation)
- Operating System: Linux (4.15.0-43-generic/amd64)

- Plugins/Mods: Tekxit 3, Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CatClearLag, EpicBanItem, GriefPrevention, LuckPerms, MMCReboot, MMCRules, Nucleus, ServerListPlus, Total Economy, spark, worldedit-sponge

Attempting to implement regeneration for worldedit sponge,
It seems that setting the SerializationBehavior to NONE still results in files being written to the worlds folder for the new world when it is loaded.

Code in question: https://github.com/EngineHub/WorldEdit/pull/486/files
(This is currently worked around by unloading and deleting the world after)

**Comment by gabizou** [comment]
I think I found the issue:
In [MixinMinecraftServer](https://github.com/SpongePowered/SpongeCommon/blob/acf1cfccdc7a821c803c2a309ec144e6f5fbe2e9/src/main/java/org/spongepowered/common/mixin/core/server/MixinMinecraftServer.java#L663-L689), the `World` is not checked for serialization behaviors none.

@Zidane is this the right point where we'd need to check for saving?

**Comment by Zidane** [comment]
Correct but I doubt this is the only spot.

**Comment by Zidane** [comment]
@clienthax I am making a fix for you but some folders and files will still be wrote and only because Vanilla's SaveHandler very much assumes they'll be there and mods do too.

At the least, we'll only write what we have to. Chunks for sure won't be wrote.

**Comment by gabizou** [comment]
@Zidane thought this should be fixed now or still no?

**Comment by JBYoshi** [comment]
What's the status on this? If this has been abandoned, feel free to assign it to me and I'll get to it sometime in the next week.

**Comment by dualspiral** [comment]
@JBYoshi - are you still willing to take a look at this?

**Comment by JBYoshi** [comment]
Yep. I'll look into it tomorrow.
