### ISSUE TITLE
World Creation Blocks Issue

### ISSUE THREAD

**Issue by Rage-GitHub** [SpongePowered/Sponge#2294]
**I am currently running**
- SpongeVanilla version: 1.12.2-7.1.7-RC214
- Java version: 1.8.0_212/64-bit
- Operating System: Linux (3.10.0-957.12.2.el7.x86_64/amd64)

- Plugins:
![image](https://user-images.githubusercontent.com/17907584/59231218-e7702400-8bad-11e9-97b0-00b41574b538.png)

**Issue Description**
When creating a world with either Nucleus or ProjectWorlds, an odd issue happens where when you try to place blocks it replaces them and surrounding blocks with some rock/stone type block.

https://drive.google.com/file/d/1q2GSzDBFAl-9HlXe5J4Xngk0ObyHRV-Z/view?usp=sharing

[latest.log](https://github.com/SpongePowered/SpongeVanilla/files/3273998/latest.log)

**Comment by Zidane** [comment]
Fixed in latest SV.
