### ISSUE TITLE
Realtime Mixin failing to apply

### ISSUE THREAD

**Issue by Cosido** [SpongePowered/Sponge#2298]
- SpongeForge version:  RC3782
- Forge version:   2838
- Java version: 8
- Operating System: Linux

Updating my build server to newest forge/spongeforge to test it out. I did the same with my Hub and it seems to work fine with no problems.

Updating from 2809/3616

I use a Proxy, the server boots fine, but when I try to connect, The server crashes, only happening on this server, another server with same forge/SF works fine, unsure if thats helpful info though
Below is the log, can provide more info if asked, thanks!
https://pastebin.com/nuYgxyAp

**Comment by Cosido** [comment]
That did allow me to connect, unsure if you knew that was going to happen, just letting you know ^-^ Thank you very much, When/If this is fixed in a future update, should I re-enable that or is it safe to keep turned off and won't be needed?

**Comment by phit** [comment]
its not enabled by default, you turned it on at some point, see the docs for what it does https://docs.spongepowered.org/stable/en/server/management/performance-tweaks.html#realtime

**Comment by Zidane** [comment]
I pushed a branch up that fixes this issue. It'll merged likely later on today or tomorrow.

**Comment by Zidane** [comment]
Fixed in latest stable-7.
