### ISSUE TITLE
Enchanted item deserialization issue

### ISSUE THREAD

**Issue by Shmeeb** [SpongePowered/Sponge#2301]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3150
- Forge version: 14.23.4.2703
- Java version: 8
- Operating System: Ubuntu

Serialize an ItemStackSnapshot (that has enchantments) with:
`String json = DataFormats.JSON.write(snapshot.toContainer());`

Then load it with:
`DataContainer container = DataFormats.JSON.read(json);`
`ItemStackSnapshot snapshot = Sponge.getDataManager().deserialize(ItemStackSnapshot.class, container).get();`

The original and the deserialized version are not the same, as it seems a short turns into an int:
https://cdn.discordapp.com/attachments/452901983515443200/454297812243447809/unknown.png

You can use this code to test if the ItemStackSnapshot is identical according to Inventory#contains: https://pastebin.com/wKFbWzD8

**Comment by Shmeeb** [comment]
Made a vid showing the issue: https://youtu.be/F8KggktxTQU

@gabizou

**Comment by Faithcaio** [comment]
Only fixes the issue with enchantments.
For modded we cannot possibly know what is supposed to be a short or int.

**Comment by Shmeeb** [comment]
Same issue still happens @Faithcaio 

```
    SpongeAPI: 7.2-fe189dcf
    Sponge: 1.12.2-7.2.0
    SpongeForge: 1.12.2-2838-7.2.0
    Minecraft Forge: 14.23.5.2838
```
