### ISSUE TITLE
ClickInventoryEvent.Drop.Outside not firing in creative mode

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2306]
**I am currently running**

- SpongeVanilla version: spongevanilla-1.12.2-7.1.6
- Java version: OpenJDK 1.8.0_212
- Operating System: Kubuntu 18.04
- Plugins/Mods: Just a simple test plugin

**Issue Description**

`ClickInventoryEvent.Drop.Outside` not firing in creative mode, only in survival mode. I tried different ways to drop out an item - from the hotbar, from the survival inventory, directly from the creative catalog. Other `ClickInventoryEvent.Drop` events are also not fired.

In survival mode:
```
DropItemEvent$Pre$Impl
ConstructEntityEvent$Pre$Impl
ConstructEntityEvent$Post$Impl
ClickInventoryEvent$Drop$Outside$Primary$Impl
```

In creative mode:
```
DropItemEvent$Pre$Impl
ConstructEntityEvent$Pre$Impl
ConstructEntityEvent$Post$Impl
DropItemEvent$Dispense$Impl
```

**Comment by Faithcaio** [comment]
`CreativeInventoryPacketState` fires the event.

With no item in hand the Client wont inform us, so there is no event for that.
