### ISSUE TITLE
SaveWorld problem.

### ISSUE THREAD

**Issue by Zaxar163** [SpongePowered/Sponge#2309]
**I am currently running**
- Java version: 1.8u211
- Operating System:
ArchLinux

- Plugins/Mods:
NOP

**Issue Description**
SaveWorld can stop saving adter exception in saving world (bad mods such as AE2)
Fix it in MinecraftServer#saveAllWorlds:
```java
    @Overwrite
    public void saveAllWorlds(boolean isSilent)
    {
        for (WorldServer worldserver : this.worlds)
        {
            if (worldserver != null)
            {
                if (!isSilent)
                {
                    LOGGER.info("Saving chunks for level '{}'/{}", worldserver.getWorldInfo().getWorldName(), worldserver.provider.getDimensionType().getName());
                }

                try
                {
                    worldserver.saveAllChunks(true, PhosphorData.PROGRESS_SAVE_WORLDS);
                }
                catch (MinecraftException minecraftexception)
                {
                	CrashReport crashreport = CrashReport.makeCrashReport(minecraftexception, "Exception saving worlds");
                    worldserver.addWorldInfoToCrashReport(crashreport);
                    throw new ReportedException(crashreport);
                }
            }
        }
    }```

**Comment by gabizou** [comment]
I'm confused, what's the reason for bringing this up? If a mod is throwing an exception during saving, that's on the mod's developer to fix. Are you asking for an option to prevent crashing the server/game if an exception is thrown during saving?

**Comment by Zaxar163** [comment]
Mods such as AE2 may create recursive crash NBT tag which will stop saving world... It is better to crash, not to log, because most problems with save caused by invalid chunk/nbt and will be on next save. Also some mods may create crash player-data for you, it`ll have another effect as crash NBT. It`is better to crash server and better log it.

**Comment by gabizou** [comment]
>Mods such as AE2 may create recursive crash NBT tag which will stop saving world..

Do you have a log for it? becuase I'm almost sure I can make a patch that'll detect the recursion and "self activate" said patch to avoid the recursive nature. But I'd probably make it a config option on SpongeForge if anything. Thoughts @Zidane @phit ?

**Comment by Zaxar163** [comment]
I get it on previsious versions on more mods and know that it can be with all servers Forestry+AE2 (BackPack into AE2 Strorage Cluster into Backpack... At some value you`ll get crash-chunk).

**Comment by gabizou** [comment]
Going to close this as it's not something I'm willing to alter as a change. Mods causing issues on save are mods fault, and if it's causing world corruption, I don't believe it's in Sponge's place to be forcing the server to crash where the game normally will simply log the exception. If a real crash is wanted, I'd suggest making the request on Forge to force a game crash in that instance.
