### ISSUE TITLE
Discussion: Procedures for managing Overwrite methods in mixins

### ISSUE THREAD

**Issue by Mumfrey** [SpongePowered/Sponge#231]
Calling @SpongePowered/developers for comments.

It is my belief that we need to put a procedure (or at least some reasonably strict guidelines) in place for managing `@Overwrite` methods in mixins. This thought is largely triggered by [these two behemoths](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/server/MixinServerConfigurationManager.java#L126-L362) which just present a maintenance nightmare as they stand.

We currently have no standard for marking `@Overwrite` methods, meaning that determining the purpose of an `@Overwrite` and the specific code which has changed is an excercise left up to the observer. I think this needs to change before we create too much unmaintainable code.

Suggestions for things we should encode in an `@Overwrite` procedure:

* **All** `@Overwrite` methods should be decorated with a (javadoc?) comment which at minimum contains who added the `@Overwrite` method and why, for example:
 
 ```java
/**
 * @auhor Mumfrey
 * Adds custom logic for summoning Cthulu
 */
@Overwrite
public void doSomething() {
    // etc
 ```
 
 This will make it possible to quickly determine whether an `@Overwrite` is needed any more, whether it can be replaced with an injection when someone has more time, etc. etc. and in extreme cases, who to go and ask when the inevitable "what the hell does this code even do" comes up :)

* Where an `@Overwrite` method is being employed to only change certain blocks of code within a method (eg. it began as a copy/paste of the target method and was subsequently modified). The changed blocks should be marked with some standard comment *a la* `// CraftBukkit start` and `// CraftBukkit end` of old. Where new code **replaces** old code, the old code should be left behind and commented out:
 
 ```java
// Sponge start
// this.baz = false; // old code
this.baz = this.getFoo().isBar();
// Sponge end
```
 
 The old code thing is a suggestion, but I think we should do something along those lines mainly so that when we port changes forward it's possible to locate similar code in the new class?

* Where an `@Overwrite` method entirely differs from its target counterpart (eg. when replacing a hard-coded accessor with some custom logic) the `// Sponge start` and `//Sponge end` could be omitted and the method description can cover it.

* Things we might also want to insist upon/recommend in the method comment might be:

 * Usage of the `@since` tag to designate the forge/mc version at time of adding/last modification?
 * Usage of the `@category` tag with some pre-defined categories indicating purposes of the `@Overwrite`
 * Usage of something like `TODO: inject` if the person adding the `@Overwrite` isn't sure if (for example) an injector is actually a more suitable way of achieving the same goal but isn't experienced enough with injectors to actually write one.

Inviting discussion on what the procedure should be, I think the fact that we ought to put something in place is pretty obvious (for future sanity purposes), but how strict we want to be and what the guidelines themselves should actually be is something we need to decide. Whatever we decide it should go into the contribution guidelines and a review of current `@Overwrite`s undertaken to make them compliant.

As an example, we could make a javadoc comment a "must have" and everything else be optional, or we could go full strict-mode and send people to the firing squad if they don't comment their additions :)

Okay, `</ramble>`.

**Comment by Zidane** [comment]
I agree with all your points. @bloodmc has wrote most of the overwrites so far and would be the best person to add some documentation.

**Comment by Minecrell** [comment]
+1 for this. Right now it's quite hard to figure out what was changed within the huge overwritten methods

**Comment by bloodmc** [comment]
I agree with everything except "since" and "category" additions. In addition we should probably add javadocs for all the interfaces we add as well.

**Comment by Zidane** [comment]
@Mumfrey 

Move this issue up to common.

**Comment by Zidane** [comment]
Graduated up into common: 

https://github.com/SpongePowered/SpongeCommon/issues/52
