### ISSUE TITLE
Problems with setting blocks in distant parts of a world

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2316]
**I am currently running**

- SpongeVanilla version: spongevanilla-1.12.2-7.1.6
- Java version: OpenJDK 1.8.0_212
- Operating System: Kubuntu 18.04
- Plugins/Mods: None

**Issue Description**

In the distant parts of a world (for example, 8000 blocks from spawn at zero), not setting blocks. My code forcibly loads unloaded chunks, but as it turned out, this is not enough. It turns out the blocks will not be set until I call any method that returns the current block state in a given position, for example, `World#getBlockType()`. I copy and restore blocks using `BlockSnapshot`, call `World#restoreSnapshot()` method. However, if a player is located near the specified copying destination, the operation will succeed, even without calling `World#getBlockType()`.

Such beauty turns out... For lower blocks (grass block layer and lower), `World#getBlockType()` is not called, but for upper blocks it is always called.

The most interesting thing is that these cut-out areas take several chunks, not one, and also not equal to the chunk size.

![Screenshot](https://user-images.githubusercontent.com/41531939/60808218-6ac26c80-a190-11e9-9d0e-2a4c34b29a4d.png)

**Comment by Lignium** [comment]
Issue is solved. Your API misled me. I called `Chunk#loadChunk(true)` instead of `World#loadChunk (true)`. I thought these were exactly the same calls, until I discovered that the `World#getChunk()` method does not return `Chunk` for unloaded and/or non-generated chunks. What is the `Chunk#loadChunk(true)` method for?

**Comment by Zidane** [comment]
World
```java
    @Override
    public Optional<Chunk> loadChunk(int x, int y, int z, boolean shouldGenerate) {
        if (!SpongeChunkLayout.instance.isValidChunk(x, y, z)) {
            return Optional.empty();
        }
        final WorldServer worldserver = (WorldServer) (Object) this;
        // If we aren't generating, return the chunk
        if (!shouldGenerate) {
            return Optional.ofNullable((Chunk) worldserver.getChunkProvider().loadChunk(x, z));
        }
        return Optional.ofNullable((Chunk) worldserver.getChunkProvider().provideChunk(x, z));
    }
```

Chunk
```java
    @Override
    public boolean loadChunk(boolean generate) {
        WorldServer worldserver = (WorldServer) this.world;
        net.minecraft.world.chunk.Chunk chunk = null;
        if (worldserver.getChunkProvider().chunkExists(this.x, this.z) || generate) {
            chunk = worldserver.getChunkProvider().loadChunk(this.x, this.z);
        }

        return chunk != null;
    }
```

@gabizou loadChunk in Chunk is a little odd.

**Comment by gabizou** [comment]
Pretty sure it's from a legacy standpoint at this point, we've optimized/mutated `WorldMixin#loadChunk` for various optimizations/changes it no longer matches the `loadChunk` implemented in `ChunkMixin_API`.

**Comment by JBYoshi** [comment]
Quick question... how do you get access to a `Chunk` object if it isn't loaded and generated?

**Comment by gabizou** [comment]
> how do you get access to a `Chunk` object if it isn't loaded and generated?

You request it from the `ChunkProvider`.

**Comment by JBYoshi** [comment]
I mean, from the SpongeAPI perspective. I don't understand how it would be possible to call `Chunk.loadChunk()` without the chunk already being loaded.

**Comment by gabizou** [comment]
> `Chunk.loadChunk()` without the chunk already being loaded.

Empty chunks can be still chunks, but marked as unloaded.
