### ISSUE TITLE
Forgotten debug message

### ISSUE THREAD

**Issue by electron93** [SpongePowered/Sponge#2321]
**I am currently running**
- SpongeForge version: **1.12.2-2838-7.1.7-RC3841**
- Java version: **1.8.0_201/64-bit (Oracle Corporation)**
- Operating System: **Linux (4.15.0-54-generic/amd64)**

When someone connects to the server.

![2019-07-11_01-24-25](https://user-images.githubusercontent.com/1076914/61009798-a15cda80-a37c-11e9-890c-14eeb80ec625.png)

https://github.com/SpongePowered/SpongeCommon/blob/00f5e56506b1bf9f52489a453443c215473a0534/src/main/java/org/spongepowered/common/util/NetworkUtil.java#L154

Appeared in https://github.com/SpongePowered/SpongeCommon/commit/d21b2f4bad13f0775f022c26e3a284334e7e8997#diff-b4d2fdccffb016e7921d2caf90621cfe

**Comment by ImMorpheus** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/23#issuecomment-510647542
