### ISSUE TITLE
StackOverflow in SpongeObjective::updateDisplayName

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/Sponge#2324]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.7-RC3848
- SpongeVanilla version: No builds containing the commit exist
- Java version: 1.8.0_212
- Operating System: Windows 10

- Plugins/Mods:
Nothing

**Issue Description**
In this commit https://github.com/SpongePowered/SpongeCommon/commit/6f6c62f3b6ae4cebae28d1f48157a91fc1752a99 changes were made here https://github.com/SpongePowered/SpongeCommon/commit/6f6c62f3b6ae4cebae28d1f48157a91fc1752a99#diff-d3fb2f10396961c3997f147bbfdb737bR85 which result in a StackOverflow.

Potentially problematic changes
- https://github.com/SpongePowered/SpongeCommon/commit/6f6c62f3b6ae4cebae28d1f48157a91fc1752a99#diff-d3fb2f10396961c3997f147bbfdb737bR109

Stacktrace: https://gist.github.com/LXGaming/acdb70fd47911e6e4cc6b9126606f0cc

This was originally reported in Discord by `Sussy <3` but no issue has been created.

**Steps to reproduce**
1. Run `scoreboard objectives add fix_me_senpai dummy Fix me senpai`
2. **Optional** Restart your server and watch it crash on startup

**Comment by ImMorpheus** [comment]
PR merged https://github.com/SpongePowered/SpongeCommon/pull/2327
