### ISSUE TITLE
Relax watchdog monitoring during server init phases

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Sponge#233]
This is mostly a reminder for @bloodmc .

The server's watchdog will, likely, halt the server during generation at init if you have a few custom worlds with heavy generators (like 4 overworlds) that are populating for the first time. We should relax the watchdog or use Cauldron's.

**Comment by Zidane** [comment]
http://pastebin.com/JfkT8fbS

A sample log of what is going on.

**Comment by Zidane** [comment]
The crash dump, FML didn't halt that one :p.

http://pastebin.com/yYXv28UH

**Comment by simon816** [comment]
IMO I think the watchdog is starting too early, it should start when the server has finished setting up

**Comment by Zidane** [comment]
@simon816 

Unfortunately, that would mean it wouldn't catch hangs during startup. Must be a happy compromise.

**Comment by ST-DDT** [comment]
Would it be possible to notify the watchdog between each world generation, that we are still there?
`watchdog.notifyAlive()`
That way we have the watchdog listening all the time and if the server hangs up at a certain point the dog can bark. But he won't be alarmed if we are just too slow during start up.

**Comment by Zidane** [comment]
@ST-DDT 

With plugins/mods we can never know if their generation is just hard on the server (as in complex) or the server is truly hung. Its better to just disable it during generation phase of server start.

**Comment by Xemiru** [comment]
bump-still a thing as of f19ca18, overworld generation alone caused watchdog to tell the server to die.

**Comment by Zidane** [comment]
This is a non-issue because Mojang allows this to be configurable via "max-tick-time" in the server.properties.
