### ISSUE TITLE
Error in registerTeam

### ISSUE THREAD

**Issue by Addalyn** [SpongePowered/Sponge#2334]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3875
- SpongeVanilla version: 
- Java version: 1.8.0_202
- Operating System: Windows 10 (but irrelevant)

- Plugins/Mods: Plugins (9): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, GlowTrails, LuckPerms, Nucleus, ShadowCore, serversync

**Issue Description**

When we upgrade to spongeforge 7.1.7 (RC3875 at the time of testing yesterday)
Our custom plugin that uses teams to have people glow in all sort of colors broke,
`java.lang.ClassCastException: net.minecraft.scoreboard.ScorePlayerTeam cannot be cast to org.spongepowered.common.bridge.scoreboard.ScorePlayerTeamBridge`

I try'd to debug it seeing if code was somehow messed up, but it follows Sponge api 7.1.0 correctly
It also works perfectly fine on 7.1.6 Stable
After some investigation i noticed that allot of changes happend in the teams in 7.1.7.

has the way sponge handles teams changed in some way? or is this just a bug
cause i try'd to use another plugin that uses teams in almost similar way of our code
and that one fails exactly same error to (https://ore.spongepowered.org/HDR/Player-Glow) also on `registerTeam`

(https://gist.github.com/PurpleIsEverything/7b193109c07c33c0994f1de73efcc9f1)

```
    private final Scoreboard scoreboard = Scoreboard.builder().build();
    ...
    public PlayerGlow(GlowTrails plugin) {
        PlayerGlow.plugin = plugin;
        for (GlowColour color : GlowColour.values()) {
            TextColor textColor = color.getTextColor();
            Team team = Team.builder().name(color.getTeam()).prefix(Text.of(new Object[]{textColor})).color(textColor).build();
            team.setAllowFriendlyFire(true);
            team.setCanSeeFriendlyInvisibles(false);
            scoreboard.registerTeam(team);
            teams.put(color, team);
        }
    }
   ...
```

**Comment by Zidane** [comment]
@Alexandrea Fixed in latest SF. Thanks for the heads up.
