### ISSUE TITLE
Chunk regeneration problem, World.regenerateChunk( ... )

### ISSUE THREAD

**Issue by electron93** [SpongePowered/Sponge#2343]
**I am currently running**
 - SpongeForge version: **RC3885**
 - Java version: **openjdk 1.8.0_222/64-bit**
 - Operating System: **Linux (4.15.0-54-generic/amd64)**
 - Plugins (10): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, BungeeTabListPlus-SpongeBridge, LuckPerms, OEye, OServer, OAPI, OChat
 - Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, SpongeForge

**Issue Description**
I'm trying to regenerate chunk using the `World.regenerateChunk( ... )` method, full code below:

```java
    @Override
    public CommandResult execute(CommandSource src, CommandContext args) throws CommandException {
        if (!(src instanceof Player)) {
            return CommandResult.empty();
        }

        Player player = (Player) src;

        BlockRay<World> ray = BlockRay.from(player)
                .stopFilter(BlockRay.continueAfterFilter(BlockRay.onlyAirFilter(), 1))
                .build();

        Optional<BlockRayHit<World>> end = ray.end();

        end.ifPresent(hit -> {
            Location<World> location = hit.getLocation();

            player.sendMessage(Text.of("End pos: ", hit.getPosition()));
            player.sendMessage(Text.of(" end type ", location.getBlockType().getName()));
            player.sendMessage(Text.of(" chunk at ", location.getChunkPosition()));

            player.getWorld()
                    .regenerateChunk(location.getChunkPosition())
                    .ifPresent(chunk -> {
                        Vector3i pos = chunk.getPosition();

                        player.sendMessage(Text.of(
                                TextColors.YELLOW, "Chunk ", TextColors.GOLD, "[",
                                TextColors.RED, pos.getX(), TextColors.YELLOW, ",",
                                TextColors.RED, pos.getZ(), TextColors.GOLD, "]",
                                TextColors.YELLOW, " regenerated"
                        ));
                    });
        });

        return CommandResult.success();
    }
```

Maybe I'm doing something wrong?

With or without other mods, it doesn't matter. There is nothing interesting in the log files. Nothing about (un-)loading and/or (re-)generating chunks.

**Screenshots**

![2019-08-09_22 34 21](https://user-images.githubusercontent.com/1076914/62804606-76d67c80-baf6-11e9-8a07-e8ac313869dd.png)

![2019-08-09_22 34 51](https://user-images.githubusercontent.com/1076914/62804649-95d50e80-baf6-11e9-8aaa-02895dc5013a.png)

**Comment by electron93** [comment]
Tried with **SpongeVanilla RC265**, works as expected (much less difference after chunk regeneration).

**Comment by Zidane** [comment]
@JBYoshi

**Comment by JBYoshi** [comment]
Can reproduce on the latest SpongeForge. So far I've narrowed it down to `ChunkGeneratorOverworld.generateHeightMap()` not providing the same values for `this.heightMap` each time.
