### ISSUE TITLE
Inventory reverting up on player log out and reconnect

### ISSUE THREAD

**Issue by Addalyn** [SpongePowered/Sponge#2346]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3878.jar
- SpongeVanilla version: 
- Java version: 1.8.0_202
- Operating System: Linux

- Plugins/Mods:
```
Plugins (34): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Announcer, BetterChunkLoader, Buycraft, DimensionReset, EconomyLite, GlowTrails, GriefPrevention, Hammer for Sponge, Holograms, HuskyCrates, HuskyUI, Kai's Commons, LuckPerms, Market, Nucleus, Prism, ProjectBorders for SpongeAPI 7.x, ProjectCore, ProjectPortals, PwnFilter, Relocator, ServerStatistics, ShadowCore, ShadowRestrict, ShadowTrades, Simplicity, Sledgehammer, UsefulCommands, VoteHandler-Sponge, serversync
```
```
Mods (305): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AE2 Wireless Terminals (AE2WTLib), AI Improvements, ATM Tweaks, Actually Additions, Actually Baubles, ActuallyComputers, Advanced Generators, Advanced Rocketry, Advanced Rocketry Core, AgriCraft, Akashic Tome, AppleCore, AppleSkin, Applied Energistics 2, Armory Expansion, Armory Expansion - Construct's Armory, Armory Expansion - Custom Materials, Armory Expansion - Ice and Fire, Armory Expansion - MatterOverdrive, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, Attribute Fix, AutoRegLib, B.A.S.E, BD Lib, Backpack, Baubles, Baubley Heart Canisters, Better Builder's Wands, Better Than Mending, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Bird's Foods, Blockcraftery, Blood Debug, Blood Magic: Alchemical Wizardry, BloodyLib, Bonsai Trees, Bookshelf, Botania, Brandon's Core, CC: Tweaked, CC: Tweaked, Capability Adapter, Chameleon, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Computronics, Construct's Armory, Cooking for Blockheads, Corail Tombstone, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Draconic Evolution, ET Lunar, ElecCore, ElecCoreLoader, Electroblob's Wizardry, Embers Rekindled, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, Ender IO endergy, EnderCore, EnderStorage, Environmental Creepers, Environmental Tech, Exchangers, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTB Library, FastFurnace, FastWorkbench, Fence Jumper, Flat Colored Blocks, Floralchemy, Forestry, Forge Microblocks, Forge Multipart CBE, Funky Locomotion, GenDustry, Good Ol' Currency Mod, Guide-API, Guidebook, Hooked, IE Cloche Compat, Immersive Engineering, Immersive Petroleum, Immersive Tech, InControl, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InfinityLib, InitialInventory, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Generators, Iron Chest, JAOPCA, JAOPCAAgriculture, JEI Bees, Just A Ore Processing Compatibility Attempt: Additions, Just Enough Dimensions, Just Enough Energistics, Just Enough Items, Just Enough Reactors, KJ Lib, KleeSlabs, LibEx, LibrarianLib, LibrarianLib Stage 2, Lost Souls, LunatriusCore, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, Mekanism: Generators, Mekanism: Tools, Minecraft Multipart Plugin, Mob Totems, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, ModPatcher, Morph-o-Tool, Morpheus, MrTJPCore, Mystical Agradditions, Mystical Agriculture, Mystical Agriculture Tiered Crystals, Mystical Lib, Mystical World, Nature's Compass, NetherEx, No Mob Spawning on Trees, Not Enough Wands, NotEnoughIDs, NuclearCraft, Nutrition, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreDictInit, OreExcavation, OreExcavation Integration, Overloaded, PackCrashInfo, PackMode, Patchouli, Pink Flamingo, Placebo, Plants, PlusTiC, PneumaticCraft: Repressurized, PortalGun, Portality, Pressure Pipes, Project Intelligence, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Integration, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, Psi, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, RFTools Power / OC Integration, RFToolsPower, Random Things, RandomTweaks, Ranged Pumps, Reborn Core, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Reliquary, Roguelike Dungeons, Roots, Rustic, Sampling Performance Profiler, Schematica, ShadowMC, Shadowfacts' Forgelin, Shield Parrying, Simply Jetpacks 2, Soul Shards Respawn, SpongeForge, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, Superior Shields, SwingThroughGrass, TATW, TOP Addons, Tech Reborn, Tech Reborn Mod Compatibility, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Computers, Thaumic Periphery, The Betweenlands, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Thermal Logistics, TickProfiler, Tinker's JEI, Tinkers Construct OpenComputers Driver, Tinkers Tool Leveling, Tinkers' Construct, Tiquality, Transport, Traverse, UniDict, Universal Modifiers, Unloader, Valkyrie Lib, Vulpes library, WAIM, WanionLib, Water Strainer, Waystones, Wetstone, Wireless Crafting Terminal 2, WirelessCharger, Wizardry, Woot, World Primer, World Utils, Worley's Caves, WrapUp, XL Food Mod, XNet, Xtones, YNot, Zero CORE, asielib, careerbees, iChunUtil, p455w0rd's Library, projectred-compat
``` 
ATM3R ModPack

**Issue Description**

So we have an issue on 7.1.7 RC3878 (persist till RC3890) 

That something a player inventory is reverted as when the server started up,

i did some test to player who had this issue (there quite a couple of them, but not on myself... :/)
I passed him some items and i looked at his playerdata and he had all items in it

https://cdn.discordapp.com/attachments/610345605788729357/610363267310682145/unknown.png

when he logged out he still had all items in his playerdata

https://cdn.discordapp.com/attachments/610345605788729357/610363363989651456/unknown.png

when he logged back into the server, his player data got reset to when server started up..

https://cdn.discordapp.com/attachments/610345605788729357/610363446617178142/unknown.png

I tryd just reseting there player data, and that seem to have worked, untill day later the issue came back (or when the server got restarted)

I'm at a loss on why this is hapening, there is no errors in log file, there is no errors in debug.log
its just a normal login of a player but his inventory being reset, 
its like the server has cached and using that instead of there player data

if the server restart while they are online its all fine (prosuminly due fact cache will be gone)

we use same forge as any other server we have and they don't cause an issue forge-1.12.2-14.23.5.2838-universal so its not forge

only difference between server is that this server uses 7.1.7 and all others are on 7.1.6 , and yes we need 7.1.7 on this server due fact of some plugins are rewrote to be compatible with 7.1.7 and way you guys are changing bridge names etc

this is the playerdata of player in question, encase you can see anything wrong with it
[b40ff547-5a78-49c4-a9e9-ed13dec347cd.zip](https://github.com/SpongePowered/SpongeCommon/files/3491400/b40ff547-5a78-49c4-a9e9-ed13dec347cd.zip)

**Comment by Addalyn** [comment]
After much more testing we found out that its some "caching" issue cause we tryd same thing but then restarted the server, instead of him coming back online first, and when the server restarted he logged on and his inventory was same as he logged off,

We then tryd again let him take all items out of his inventory and reloged
![image](https://user-images.githubusercontent.com/622983/62880029-c43c2f00-bd2c-11e9-8ad4-405e0ffe9a57.png)
Left is from when he was online and passed me all put one skull, middle is when he was offline, and right is when he came back to the server

We have not been able to isolate the version of 7.1.7 that started it as we had to start with version RC3878 due fact that teams where broken before that

**Comment by Faithcaio** [comment]
One way this could happen if for some reason there is an old 
`SpongeUser` instance around which for some reason stayed dirty 
and as such is saved before joining:
https://github.com/SpongePowered/SpongeCommon/blob/da40458a2c60c8114fd567dc0dd35e5bb3799147/src/main/java/org/spongepowered/common/util/NetworkUtil.java#L158

**Comment by Faithcaio** [comment]
Actually the inventories just stayed "cached" when invalidating an offline User.
So when anything marks the user as dirty (even unrelated to inventories) it saves the still cached inventory at login.

But that is fixed now :)

**Comment by Addalyn** [comment]
Yes issue has been fixed thank you :)
