### ISSUE TITLE
The configurate translator failed on non-root nodes

### ISSUE THREAD

**Issue by ustc-zzzz** [SpongePowered/Sponge#2352]
**I am currently running**
- SpongeVanilla version: `1.12.2-7.1.7-RC268`
- Java version: `openjdk version "1.8.0_212"`
- Operating System: `#1 SMP Debian 4.19.37-6 (2019-07-18)`

The example plugin and part of the output:  
<https://gist.github.com/ustc-zzzz/dc6518488b62dbc19d6fdfa5df8a36f4>

The configurate translator successfully handled `node1` while failed to handle `node2` and threw an error.

**Comment by dualspiral** [comment]
I have backed out the change that caused this while #2353 is being worked on. I think the fix for this was already in the PR, but it isn't quite ready yet.

https://github.com/SpongePowered/SpongeCommon/commit/41519ee5e2ab2771dee1db91ad6febb6e1215565
