### ISSUE TITLE
Unable to deserialize Location

### ISSUE THREAD

**Issue by TheoKah** [SpongePowered/Sponge#2354]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.7-RC3901
- Java version: 1.8.0_151
- Operating System: Windows

- Plugins/Mods: None apart from the test plugin

**Issue Description**

Since 3900, it is not possible to de-serialize Locations anymore

I put this in the `GameStartedServerEvent` :
https://gist.github.com/TheoKah/d8481beac6a9fc630ab0c51784e930af

And got this exception:
https://gist.github.com/TheoKah/29a4cfa6b9ea06f2b2c1dc7bdff9a8bf

Same code is working on 3899

**Comment by dualspiral** [comment]
I have backed out the change that caused this while we work on a better fix.

https://github.com/SpongePowered/SpongeCommon/commit/41519ee5e2ab2771dee1db91ad6febb6e1215565

**Comment by ImMorpheus** [comment]
(Also duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2352)
