### ISSUE TITLE
Respawning after dieing crashes the server

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/Sponge#236]
The issue is [here](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/entity/CombatHelper.java#L35) which makes reference to MixinEntityLiving which does not exist at runtime.

[Stack trace for reference](https://gist.github.com/Deamon5550/d292e34de38db2cebe8a)

**Comment by kenzierocks** [comment]
Potential fix: https://github.com/kenzierocks/Sponge/commit/6fd8b4999fb131f7ee65e29785a9b968d68fc921

**Comment by kenzierocks** [comment]
Fixed in ca17814
