### ISSUE TITLE
Sponge Forge isn't loading in any way, no config folders/commands

### ISSUE THREAD

**Issue by Jacob345k** [SpongePowered/Sponge#2362]
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3903
- SpongeVanilla version: 
- Java version: 1.8.0_212
- Operating System: Windows 10 Server

- Plugins/Mods: 
(images of my mods folder as my issue is sponge doesn't work or load)
https://cdn.discordapp.com/attachments/484569952137904128/615382809527451721/unknown.png
https://cdn.discordapp.com/attachments/484569952137904128/615382867308183572/unknown.png
https://cdn.discordapp.com/attachments/484569952137904128/615382924728074241/unknown.png

**Issue Description**
Sponge Forge isn't loading in any way, no config folders/commands load, in the plugins folder i have these plugins: 
![image](https://user-images.githubusercontent.com/25356889/63662860-b30c0d00-c785-11e9-9d35-1ec691a2b228.png) however they do not load as sponge doesn't load. Here is my latest.log
[latest.log](https://github.com/SpongePowered/SpongeCommon/files/3539285/latest.log)
If you need or want anything else i will respond quickly. thanks for your time in reading this and responding.

**Comment by KorewaLidesu** [comment]
Try put them to mods folder.
Also config folder generated in *server config folder*, not in *plugins* folder since this is Forge.

**Comment by dualspiral** [comment]
https://forums.spongepowered.org/t/common-crash-issues-please-read-first/29689 - read the old mixin part. You have a mod with an older version of Mixin shaded that is loading first, that will make Sponge load it’s version first.

Discord and the Sponge Forums are better places for support. GitHub is for issues and bugs with the software itself. Thanks!
