### ISSUE TITLE
AbstractMethodError when call World#digBlock(Vector3i, GameProfile)

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2364]
**I am currently running**

- SpongeVanilla version: 7.1.6 and also 7.1.7-RC272
- Java version: OpenJDK 1.8.0_222
- Operating System: Kubuntu 18.04
- Plugins/Mods: None

**Issue Description**

Method: `World#digBlock(Vector3i, GameProfile)`

```
java.lang.AbstractMethodError: Method net/minecraft/world/WorldServer.digBlock(IIILorg/spongepowered/api/profile/GameProfile;)Z is abstract
	at net.minecraft.world.WorldServer.digBlock(SourceFile) ~[oo.class:?]
```

Related unresolved issue: https://github.com/SpongePowered/SpongeCommon/issues/1841

**Comment by ImMorpheus** [comment]
> Related unresolved issue: 1841

That's the same issue. Method name is different, but both are all about implementing simulated methods for players.
