### ISSUE TITLE
Incorrect error when a command fails

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/Sponge#2365]
**I am currently running**

- SpongeForge version: https://github.com/SpongePowered/SpongeForge/commit/3fbc8850d9a5a31fecc5bd33693a42c1e1396e34
- SpongeVanilla version: 

- Plugins/Mods: None

**Issue Description**

Some commands are returning an ambiguous/incorrect error.

`/sponge mods foo` (or /sponge plugins foo)
```
Input command mods was not a valid subcommand!
mods foo
^
Usage: /sponge which|mods|audit|plugins|timings|metrics|heap|version|<>|[--global|-g] [--world|-w <world>] [--dimension|-d <dimension>] chunks|tps|<>|[--global|-g] [--world|-w <world>] [--tracker|-t] [--dimension|-d <dimension>] reload|save|config
```

This is wrong since `mods` is a valid subcommand. The error should warn me the argument is wrong and print the usage of `/sponge mods` (not `/sponge`)

nested dispatcher:

```
SimpleDispatcher root = new SimpleDispatcher();
SimpleDispatcher foo = new SimpleDispatcher();
CommandSpec spec = CommandSpec.builder()
        .arguments(GenericArguments.onlyOne(GenericArguments.user(Text.of("user"))))
        .executor((src, ctx) -> {
            ctx.requireOne(Text.of("user"));
            return CommandResult.success();
        })
        .build();

foo.register(spec, "bar");
root.register(foo, "foo");

Sponge.getCommandManager().register(this, root, "root");
```
`/root foo bar invaliduser`
```
No values matching pattern 'invaliduser' present for user!
invaliduser
^
Usage: /root foo
```
Good error, but the usage is wrong. It should show the usage of `/root foo bar` (it should be `Usage: /root foo bar <User>
`

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/1718

Read that and associated issues for some of the context. It’s a similar issue, though “mods” being an invalid subcommand is not great.

It really all boils down to how command elements are dealt with on children and I’m really not up for making large changes on the API layer now, which is where commands are held - the system is actually somewhat delicate. It is part of why I was getting this for 8 in the first place (even before Brig came along)

**Comment by ImMorpheus** [comment]
That's exactly the issue I have with usage.

It seems to be fixed here, by appending the children to the usage.
https://github.com/SpongePowered/SpongeAPI/blob/20b5f1b027ceceb9a120df25a2a9fb8a6a1e792b/src/main/java/org/spongepowered/api/command/args/ChildCommandElementExecutor.java#L216-L223

However there's nothing like that in `SimpleDispatcher` (in fact, `childArgumentParseExceptionFallback(false)` didn't work). Does that mean they are not meant to be nested ? 

I can see why you don't want to make large changes to the current api. What about making public the constructor of `ArgumentParseException.WithUsage` to make it easier for people using the low-level command api to work around this ?

**Comment by dualspiral** [comment]
I see no issue with it really. I see it as an implementation detail but, at this stage, 7 is about patchwork and if it helps paper over the cracks, then let’s just roll with it.

As for nesting... well, they can be. It’s just not how the system works on the high level so I never really thought about it.

If the simplest solution is to make the exception public, go for it.
