### ISSUE TITLE
Completing incorrect phase/Unexpectedly Completing An Empty Stack   

### ISSUE THREAD

**Issue by MineTears** [SpongePowered/Sponge#2371]
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3909
- Forge version: 1.12.2 (7.1.6 / Forge 14.23.5.2825)
- Java version: 8
- Operating System: Windows 10

- Plugins : Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CmdBuilder, CmdControl, DailyRewards, EconomyLite, GTS, GTS Reforged Bridge, ImpactorAPI, LuckPerms, Nations, Nucleus, PixelmonBroadcasts, PixelmonEconomyBridge, PlaceholderAPI, VirtualChest, WorldEdit

- Mods : Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, CustomNPCs, JourneyMap, LegendaryPlus, OfflineSkins, Pixel Extras, Pixelmon, SpongeForge, Wondertrade

Juste taking Minecraft basic Bone Meal, right clicking it on the ground to create grass and flowers

https://gist.github.com/MineTears/7db7da11f06f300705c6af43e52b2c80

Thanks for any help! If it has already been solved, I'm very sorry!

**Comment by ImMorpheus** [comment]
Able to reproduce on SF (latest) with no mod.

See https://github.com/SpongePowered/SpongeCommon/commit/1700f27c9c207bf614fd480f41130ddefe671f36#diff-a7c7c324f1b07aa0f22f9e1566a33ac4L54

**Comment by MineTears** [comment]
Is there any fix yet? :c

**Comment by gabizou** [comment]
This was fixed a few days ago, got missed in closing the issues, fixed in https://github.com/SpongePowered/SpongeCommon/commit/7350b749c253c38e56adce2c743da953db7ded9f
