### ISSUE TITLE
ClickInventoryEvent.Drop.Primary is not correctly fired

### ISSUE THREAD

**Issue by aromaa** [SpongePowered/Sponge#2391]
**I am currently running**

- SpongeForge version: 
- SpongeVanilla version: 1.12.2-7.1.7-RC277.jar
- Java version:  1.8.0_211/64bit
- Operating System: Windows 10
- Plugins/Mods: None

**Issue Description**
When dropping item outside of the inventory by using left click, event ClickInventoryEvent.Middle is fired instead of ClickInventoryEvent.Drop.Primary. However ClickInventoryEvent.Drop.Secondary is fired without issues.

This can be easily inspected by using the following:
```
@Listener
public void clickInventory(ClickInventoryEvent event, @Last Player player)
{
    player.sendMessage(Text.of(event.getClass()));
}
```

**Comment by gabizou** [comment]
I'll be getting to do a full test with this soon, just to potentially log the various bit-packed datas for the client to test with. Pardon for the delay in getting this reviewed and resolved.
