### ISSUE TITLE
InteractItemEvent.Secondary.MainHand fired twice when right clicking entity with item in hand

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/Sponge#2402]
**I am currently running**
- SpongeForge version: `spongeforge-1.12.2-2838-7.1.7-RC3928`
- SpongeVanilla version: `spongevanilla-1.12.2-7.1.7-RC297`

As I've noted in the following gist:
https://gist.github.com/ItsDoot/a7bbae7419de6096b2506bc5612ae90d

`InteractItemEvent.Secondary.MainHand` is fired twice when you right click an entity with an item in hand. I believe the first firing is for when there is no item in hand, but is fired anyways, and the second firing is for when there is actually an item in hand.

Another partially related observation: There is no place where `Primary.OffHand` of any of the interact events is fired; is there a reason the subinterface exists, besides for uniformity?

Plugin used to test events: https://github.com/ItsDoot/event-tester

**Comment by ImMorpheus** [comment]
Working on it.

It seems the two events are fired because of different packets, namely `CPacketUseEntity` and `CPacketPlayerTryUseItem`.

**Comment by JBYoshi** [comment]
> There is no place where Primary.OffHand of any of the interact events is fired; is there a reason the subinterface exists, besides for uniformity?

Regarding that, it's technically impossible to use an off-hand item while left-clicking. From the [minecraft wiki](https://minecraft.gamepedia.com/Dual_wield#Usage):

> Players also cannot break blocks or attack with the off-hand, even if nothing is held in the main hand.
