### ISSUE TITLE
SpawnEntityEvent is not fired after ClientConnectionEvent.Login

### ISSUE THREAD

**Issue by aromaa** [SpongePowered/Sponge#2412]
**I am currently running**

- SpongeForge version: 
- SpongeVanilla version: 1.12.2-7.1.7-RC308
- Java version: 1.8.0_211/64bit
- Operating System: Windows 10

**Issue Description**
The current documentation for ClientConnectionEvent says the following events should happen on login process:

#Auth -> #Login -> SpawnEntityEvent -> #Join

However the SpawnEntityEvent is never actually fired

**Comment by ImMorpheus** [comment]
Able to reproduce on SF (SC https://github.com/SpongePowered/SpongeCommon/commit/11a0398d9f3fe12ed7cf40ff758d6f7d36dbf154)
