### ISSUE TITLE
Horse dismount bug

### ISSUE THREAD

**Issue by RussianJeb** [SpongePowered/Sponge#2418]
**I am currently running**

- SpongeVanilla version:  1.12.2-7.1.6
- Java version: 1.8.0_181
- Operating System: Windows 10 Pro x64

- Plugins/Mods: None

I have some bug with horse. Sometimes if dismount from horse, it disappears (i hear horse sounds) or teleports to start location. Also if I'm riding a horse, I can start teleport to start and back about 10 times. I think this is vanilla bug. I found a similar problem here: https://bugs.mojang.com/browse/MC-101247 and it fixed in 1.15 snapshot

**Comment by ImMorpheus** [comment]
> SpongeVanilla version: 1.12.2-7.1.6

That build is 5 months old. Please try to reproduce with the latest version (there have been a few issues about disappearing entities not long ago).
