### ISSUE TITLE
FlammableProperty 

### ISSUE THREAD

**Issue by SimonBHB** [SpongePowered/Sponge#2419]
**I am currently running**

- SpongeForge version: 7.2.0-SNAPSHOT/
- Forge version: 1.12.2-14.23.5.2825
- Java version:1.8.0_181
- Operating System: W10

**Issue Description**

Bonjour

FlammableProperty renvoie false quand je test sur un bloc de bois c'est normal ?

[Google translate]:
FlammableProperty returns false when I test on a block of wood is normal ?
https://github.com/SpongePowered/SpongeAPI/blob/a1418ae3fccbfa1fbc56e05d2f3375dcd1344e1c/src/main/java/org/spongepowered/api/data/property/block/FlammableProperty.java

**Comment by JBYoshi** [comment]
You need to call `getProperty()` on the `Location`, not the `BlockType`.

**Comment by SimonBHB** [comment]
Et comment on sait si le bloc est en train de brûler ?

[Google translate]:
And how do we know if the block is burning?

**Comment by JBYoshi** [comment]
Look for a block next to the first block with a type of `BlockTypes.FIRE`.
