### ISSUE TITLE
Clicking anvil slots error if UpdateAnvilEvent is being listened to

### ISSUE THREAD

**Issue by DrZoddiak** [SpongePowered/Sponge#2426]
**I am currently running**

- SpongeVanilla version: Built from [#8bfae45](https://github.com/SpongePowered/SpongeVanilla/commit/8bfae45eeff5d9896dc019eb1e7f9abda92ec2b5)
- Java version: 1.8.0_181
- Operating System: Windows 10

- Plugins/Mods: Luckperms, TestPlugin (Made for this issue, code linked below)

**Issue Description**
If a plugin is listening to `UpdateAnvilEvent`, and a player uses the anvil and clicks either left, right, or result slot, then [this error is sent](https://gist.github.com/DrZoddiak/b4726a36c8a2038f137c6a06de4e15d3)
If a valid input is set into the anvil in example if you put an enchanted book in the right slot you receive the same error, but once you put a sword (or any item) into the left slot, the error stops getting sent.
From then on you can act freely with the anvil until you re-open the menu, and then the errors persist (until a valid input is made)

This doesn't happen if nothing is listening to the `UpdateAnvilEvent`

Code necessary to replicate (It's tiny)
https://gist.github.com/DrZoddiak/426e0abbeed9e68bef42b13d4125617d

Latest.log
https://gist.github.com/DrZoddiak/8dcfcf5aab297459b3bafa776f025228

The error sent (same as above, just copying here)
https://gist.github.com/DrZoddiak/b4726a36c8a2038f137c6a06de4e15d3

**Comment by Faithcaio** [comment]
was fixed in https://github.com/SpongePowered/Sponge/commit/aa86ca4ec0d768a17c5daebdb9aebce748663be0
