### ISSUE TITLE
Switching world does not show experience value

### ISSUE THREAD

**Issue by taomrp** [SpongePowered/Sponge#2435]
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7
- Java version: java8-221
- Operating System:centos-7.6

Player experience (level not shown) cannot be used Enchanting table when a player transfers from one world to another
as:world tp DIM1/world tp world

**Comment by clienthax** [comment]
This seems to only be when using TP commands, using the nether portal doesn't have the same effect
