### ISSUE TITLE
MoveEntityEvent.Teleport not firing for Nucleus commands

### ISSUE THREAD

**Issue by blairwilson** [SpongePowered/Sponge#2440]
**I am currently running**

- SpongeForge version: spongevanilla-1.12.2-7.1.8-RC317
- SpongeVanilla version: spongeforge-1.12.2-2838-7.1.8-RC3963
- Java version: 1.8.0_201
- Operating System: Windows 10

- Plugins/Mods:
Nucleus
LuckPerms
BUtils (my plugin facing the issue)

**Issue Description**
I'm using MoveEntityEvent.Teleport to detect when a player enters a "Second Overworld" in my server, adds a boss bar displaying they are in the second world and removes it once they leave.

Using /world teleport and /warp from Nuclues doesn't seem to fire this event but /rtp while in the world does.

I am extremely new to developing plugins so my code could definitely be the issue here although it does seem strange. [Code snippet](https://gist.github.com/HHServers/8b66e7bc05c6ad7c8af175774426af49)

**Comment by dualspiral** [comment]
Change `@Root` -> `@Getter("getTargetEntity")`. The cause is not the same as the target.

**Comment by blairwilson** [comment]
I have tried the suggested changes and it still seems to happen unfortunately :(

**Comment by ImMorpheus** [comment]
I'm not able to reproduce this with SF (https://github.com/SpongePowered/SpongeForge/commit/5b52f64dc6f6a49554303856f649744a0cdd2377) and Nucleus 1.14.2-S7.1.

Both `/warp` and `/world teleport` fire a `MoveEntityEvent.Teleport` when teleporting a player from a world to another (I've created another overworld using Nucleus).
