### ISSUE TITLE
AttackEntityEvent not getting triggered by shooting

### ISSUE THREAD

**Issue by fingoltin** [SpongePowered/Sponge#2442]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.7
- SpongeVanilla version: N/A
- Java version: 1.8.0_212/64-bit (Oracle Corporation)
- Operating System: Linux

- Plugins/Mods: Just my own

With this snippet the event isn't getting triggered when getting shot by something. (Player shooting other player, skeleton shooting player). This kind of situation is in the javadocs for the event so I assume it should get triggered in these situations.

```java
@Listener(order = Order.FIRST)
public void onAttack(AttackEntityEvent event) {
        getLogger().info(event.getCause().toString());
}
```

**Comment by gabizou** [comment]
Getting shot is different than a player hitting another entity. Getting shot is a `DamageEntityEvent`, whereas a Zombie attacking a player with a sword is both `AttackEntityEvent` (from the Zombie as a Source) and `DamageEntityEvent` for the Player receiving damage.

**Comment by fingoltin** [comment]
> 
> 
> Getting shot is different than a player hitting another entity. Getting shot is a `DamageEntityEvent`, whereas a Zombie attacking a player with a sword is both `AttackEntityEvent` (from the Zombie as a Source) and `DamageEntityEvent` for the Player receiving damage.

```java
 Due to this ambiguous variety of information that is possible to provide, the AttackEntityEvent can be summarized as so:

An Arrow, that was shot by a Skeleton, with an enchanted ItemTypes.BOW ItemStack, when the World Difficulty was set to Difficulties.HARD, will deal possibly "5" damage to any Entity it hits. 
```

Shouldn't this be updated then?
