### ISSUE TITLE
With SpongeForge installed, zomibie pigman anger doesn't work properly

### ISSUE THREAD

**Issue by Akiranya** [SpongePowered/Sponge#2452]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.7
- Forge version: 14.23.5.2838
- Java version: 1.8.0_232/64-bit (Private Build)
- Operating System: Linux (4.15.0-45-generic/amd64)

- Plugins/Mods:

Plugins : Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge

Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Astral Sorcery, Baubles, Better Records, Blood Magic: Alchemical Wizardry, Chameleon, Corail Tombstone, Grimoire of Gaia 3, Guide-API, Iron Chest, JourneyMap, Just Enough Calculation, Just Enough Items, LagGoggles, Mantle, MrCrayfish's Furniture Mod, QuickStore, Realistic Terrain Generation, Shadowfacts' Forgelin, SlashBlade, SpongeForge, Tinker SlashBlade, Tinkers' Construct, Waila, What Are We Looking At

**Issue Description**
Attacking one of the pigmen within many of them should make all nearby pigmen aggressive. But in fact, it looks like with SpongeForge installed, the anger spreads much slower than it does in vanilla behavior. Also, each time attacking a pigman, it only makes part of nearby pigmen aggresive, not all of nearby pigmen. Some nearby pigmen even remain neutral for a long time after the attack.

This issue makes the [zombie pigman farming](https://minecraft.gamepedia.com/Tutorials/Zombie_pigman_farming) not working properly, which relies on anger of pigmen heavily.

As to how I confirmed this issue... With Sponge installed, I just spawned dozens of zombie pigmen with spawn eggs, then I switched to survival gamemode. I attacked one of the pigmen, then it happened like what I said above. Then I tried it **without** Sponge installed, and I did exactly what I had done before, the anger spread instantly. All nearby pigmen became aggresive moving to me.

The config of sponge is all default during test.

No crash-report and relevant server log generated.

**Comment by JBYoshi** [comment]
Can reproduce on 7.1.8, and I think I found the cause.

https://github.com/SpongePowered/SpongeCommon/blob/da40458a2c60c8114fd567dc0dd35e5bb3799147/src/main/java/org/spongepowered/common/mixin/entitycollisions/ChunkMixin_Collisions.java#L84

This is limiting the number of pigmen that are alerted (to 8 by default). I'm probably going to change this by skipping the limit for large searches, but in the meantime you can work around this by changing `max-entities-within-aabb` in `global.conf` to 0 (which removes the limit).
