### ISSUE TITLE
Dup bug shulker 2 players

### ISSUE THREAD

**Issue by Heriptik** [SpongePowered/Sponge#2470]
- SpongeForge, Java, Operating System version : https://image.noelshack.com/fichiers/2020/02/1/1578271500-sponge-version.png

My mods : https://image.noelshack.com/fichiers/2020/02/1/1578271673-mods-sponge.png
My plugins : https://image.noelshack.com/fichiers/2020/02/1/1578271700-plugins-1.jpg https://image.noelshack.com/fichiers/2020/02/1/1578271702-plugins-2.jpg https://image.noelshack.com/fichiers/2020/02/1/1578271703-plugins-3.jpg

**Issue Description**

Hello you must first be two players, a shulker and wait until the server times go down (18-17 tps), with more than 100 constant players it goes down very quickly. you have to break the shulker and take the item at the same time using the change keys with the mouse on the object.

Video : https://uptostream.com/lkyrffkf95s2

I tried the recommended spongeforge version 7.1.7 and this does not solve the problem

**Comment by JBYoshi** [comment]
Does this still happen with SpongeForge 7.1.9?

**Comment by dualspiral** [comment]
No response in over three months. Closing.
