### ISSUE TITLE
DropItemEvent.Destruct is called when inventory is kept

### ISSUE THREAD

**Issue by SettingDust** [SpongePowered/Sponge#2478]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.9-RC3980

**Issue Description**
[Gist](https://gist.github.com/SettingDust/e20032a1c4d972ee3d88022f014f2be9)
The `DropItemEvent.Destruct` is still called when `keepInventory` is true. And the `event.getEntities()` size is 0.

**Comment by Lignium** [comment]
It seems like this is a feature. It's okay that the event is called idle, much worse when there is not enough data or the data is incorrect.
https://github.com/SpongePowered/SpongeCommon/blob/e03eff307a7a51f57d1e386faeb06cca2925d338/src/main/java/org/spongepowered/common/event/tracking/phase/entity/EntityDeathState.java#L112-L113

**Comment by SettingDust** [comment]
> https://github.com/SpongePowered/SpongeCommon/blob/e03eff307a7a51f57d1e386faeb06cca2925d338/src/main/java/org/spongepowered/common/event/tracking/phase/entity/EntityDeathState.java#L112-L113

But it still shouldn't be called. It is not a mod event

**Comment by dualspiral** [comment]
It's tied to the mod event though. With the way Sponge works, in a modded environment, it strives to call events that have a Forge equivalent. In Forge, [the `LivingDropsEvent` is equivalent](https://github.com/SpongePowered/SpongeForge/blob/18f4ee7198a16373b265952ae44667d2f4c8b043/src/main/java/org/spongepowered/mod/event/SpongeToForgeEventFactory.java#L180-L182). And, if we have that behaviour in SF, then we really should make it consistent and do it in SV too. Besides, the explanation why is given right in that comment. 

Working as intended - gives flexibilty in case mods add to the drop list _and_ it gives plugins a sane time to drop items itself - no items might be dropped but a plugin might want to drop some sort of skull, this is the time to do it. So it should be fired.

For your case, an "empty" event is easy to detect and ignore - that's what you're going to have to do.
