### ISSUE TITLE
UR Ghast Despawning

### ISSUE THREAD

**Issue by tankcr** [SpongePowered/Sponge#2479]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.8-RC3967
- SpongeVanilla version: 
- Java version: 
- Operating System:
Ubuntu Server 19.10

- Plugins/Mods:
Mods (181): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, AE2 Stuff, AE2 Wireless Terminals (AE2WTLib), Advanced Generators, AgriCraft, Animus, AppleSkin, Applied Energistics 2, ArchitectureCraft, Astral Sorcery, AutoPackager, AutoRegLib, BD Lib, Basic Nether Ores, Baubles, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blood Magic: Alchemical Wizardry, Botania, Botanic Additions, Brandon's Core, Building Gadgets, CXLibrary, Carpenter's Blocks, Chisel, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, CookieCore, CoroUtil Library, CreativeCore, CreativeCoreDummy, Cucumber Library, Deep Mob Learning, Deep Mob Learning - Blood Magic Addon, Draconic Evolution, Dynamic Trees, Dynamic Trees BOP, Dynamic Trees TC, Dynmap, ET Lunar, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Ex Compressum, Ex Nihilo Creatio, Exchangers, Exotic Birds, Extended Mod Config, Extended Renderer, Extra Cells 2, Extra Golems, Extra Utilities 2, Extreme Reactors, FTB Library, Facade Painter, Flux Networks, FoamFix, FoamFixCore, Forestry, GenDustry, Gendustry JEI Addon, Growable Cells, Guide-API, Hammer Core, Immersive Cables, Immersive Engineering, Industrial Foregoing, InfinityLib, InstantUnify, Integration Foregoing, Inventory Tweaks, Iron Chest, JAOPCA, JEI Bees, Jade, JourneyMap, Just Enough Items, Just Enough Reactors, JustEnoughIDs, LLibrary, LagGoggles, Loot Bags, LunatriusCore, MachineMuse's Modular Powersuits, MagicBees, Malisis Blocks, Malisis Switches, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, Mekanism: Generators, More Furnaces, MrCrayfish's Furniture Mod, MrTJPCore, Mystical Adaptations, Mystical Agradditions, Mystical Agriculture, Natura, NoMoreRecipeConflict, Not Enough Wands, Numina, OnlinePictureFrame, OpenBlocks, OpenModsLib, OpenModsLib Core, OreDictInit, Pam's Get all the Seeds!, Pam's HarvestCraft, Patchouli, Placebo, PlusTiC, ProjectE, RFTools, RFTools Dimensions, Random Things, RandomPatches, Redstone Flux, Refined Storage, Refined Storage Addons, Shadowfacts' Forgelin, Simply Jetpacks 2, SpongeForge, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, Thaumic Energistics, Thaumic Grid, Thaumic Periphery, Thaumic Tinkerer, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkering With Blood Magic, Tinkers' Construct, TreeCapitator, Tropicraft, UniDict, Universal Modifiers, Valkyrie Lib, Waila, WanionLib, Wireless Interface Terminal, Wireless Pattern Terminal, Woot, WrapUp, YABBA, Zero CORE, bspkrsCore, p455w0rd's Library

**Issue Description**
16:12:00
Entity being removed for bounding box restrictions
BB Size: 4,275 > 1,000 avg edge: 15.368
Motion: (0.1, 0, -0.003)
Calculated bounding box: box[-2886.5, 56.0, 4512.497436739854 -> -2872.4000328542866, 74.0, 4526.5]
Entity bounding box: null
Entity: EntityTFUrGhast['Ur-Ghast'/156797, l='DIM7', x=-2879.50, y=56.00, z=4519.50]
Entity NBT: {HurtByTimestamp:6,ForgeData:{SpongeData:{}},RelativeAABB:[-7.0d,0.0d,-7.0d,7.0d,18.0d,7.0d],Attributes:[{Base:250.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.699999988079071d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:128.0d,Modifiers:[{UUIDMost:92687438303282695L,UUIDLeast:-7584850518651910104L,Amount:0.015649215364184576d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,DeathTime:0s,ForgeCaps:{"llibrary:extendedentitydatacapability":{},"twilightforest:cap_shield":{permshields:0,tempshields:0}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Motion:[0.0999671457134543d,0.0d,-0.002563260146498828d],Leashed:0b,UUIDLeast:-7992132862664578106L,Health:244.0f,LeftHanded:0b,Air:300s,OnGround:0b,Dimension:7,ExplosionPower:1,Rotation:[-19.408249f,-8.241865f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:995305885432434272L,Pos:[-2879.5d,56.0d,4519.5d],Fire:0s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,inTantrum:0b,HurtTime:7s}
Entity being removed for bounding box restrictions
BB Size: 4,275 > 1,000 avg edge: 15.367
Motion: (-0.002, 0, -0.1)
Calculated bounding box: box[-2886.502438299337, 56.0, 4512.4000297271905 -> -2872.5, 74.0, 4526.5]
Entity bounding box: null
Entity: EntityTFUrGhast['Ur-Ghast'/156798, l='DIM7', x=-2879.50, y=56.00, z=4519.50]

**Comment by clienthax** [comment]
Edit the limits in the config

**Comment by tankcr** [comment]
um, that is a super vague answer. Are we talking about a sponge config?
