### ISSUE TITLE
Dupe some blocks

### ISSUE THREAD

**Issue by bigenergy** [SpongePowered/Sponge#2487]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.9-RC3986
- Forge version: forge-1.12.2-14.23.5.2847
- Java version: 1.8.0_211
- Operating System: Ubuntu 19.04

- Plugins/Mods: no mods

**Issue Description**
1. Put a zombie skull (Any skull)
2. Break her down
3. Drops 2 instead of 1
Works with any skull

The same problem exists with the destruction of double blocks (an example of a telescope from astral sorcery) https://github.com/HellFirePvP/AstralSorcery/issues/1170

**Comment by dualspiral** [comment]
Can you check 3983 for me - and if you can't reproduce on that, then 3984? Thanks in advance.

**Comment by dualspiral** [comment]
For now, we have decided to revert all changes that led up to this issue and put the work in progress onto a branch. This will not be an issue in the next build.

Thank you for your help with this.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/65136e797b760d37c5846ad923649f44dba87f81

Typed in the wrong issue number on the commit... it's this one

**Comment by bigenergy** [comment]
@dualspiral It is still sometimes reproduced on SF-1.12.2-2838-7.1.9

**Comment by dualspiral** [comment]
Not due to this bug, it isn't - the commit fixed the serious dupe bug you reported which was consistent. 

File a new one with _exact_ reproduction steps - not just linking to this issue and saying "this happens sometimes".
