### ISSUE TITLE
NbtTranslator isn't passing the tests.

### ISSUE THREAD

**Issue by TheDoctorsLife** [SpongePowered/Sponge#249]
Easiest way to explain it. http://ci.blastcraft.org:8080/job/Sponge/154/testReport/org.spongepowered.mod.service.persistence.data/NBTTranslationTest/testContainerToNBT/

**Comment by Minecrell** [comment]
Try to clean the workspace, there are tons of old stuff in there

**Comment by Minecrell** [comment]
Fixed I guess? :P

**Comment by TheDoctorsLife** [comment]
seems to, I'll repoen if the issue remains tomarrow (I have to go today)

**Comment by TheDoctorsLife** [comment]
Yep, that fixed it, I know now to have it clear the workspace first.

**Comment by Minecrell** [comment]
Not always, but you should clean the workspace from time to time, especially if there were major changes. Sometimes Git/Gradle don't handle everything perfectly, submodules changes can cause some problems sometimes

**Comment by TheDoctorsLife** [comment]
No, on the CI, I set it so it clears before starting, I was testing something earlier and forgot to change it back.
