### ISSUE TITLE
uuid in offline mode 

### ISSUE THREAD

**Issue by ShymaSAD** [SpongePowered/Sponge#2490]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.8
- Java version: 8
- Operating System: Windows 10 

- Plugins/Mods: Only the plugin i'm developing. 

**Issue Description**
Such a problem, I need to log in to the server with a UUID check that matches in the database and in the launcher, but in fact, the server generates a new UUID when logging in to the server.
Client give me: d70ab85734aa4ec0a6c1763bfefada60
Server give me: 336c091b-6f17-339f-9e74-fdf22ccadc51
I want from server: d70ab85734aa4ec0a6c1763bfefada60

**Comment by XakepSDK** [comment]
Cracked servers are not supported

**Comment by ShymaSAD** [comment]
What should i do then?

**Comment by gabizou** [comment]
Use online mode, or if you need to use a proxy (BungeeCord, Waterfall, Velocity, etc.) make sure those are in online mode.
