### ISSUE TITLE
Two bugs related to player inventory

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2494]
**I am currently running**

- SpongeVanilla version: spongevanilla-1.12.2-7.1.9
- Java version: OpenJDK 1.8.0_232
- Operating System: Kubuntu 18.04 LTS
- Plugins/Mods: None

**Issue Description**

1) `GridInventory#set(SlotPos, ItemStack)` method absolutely does not work, the result of which seems to always be failed. The given coordinates do not affect the result.
2) The `EquipmentInventory` iterator should return all 4 slots as `EquipmentSlot`, however one of them is just a `Slot`.

Test code:

```java
@Listener(order = Order.POST)
public void onPlayerInteract(InteractBlockEvent.Secondary.MainHand event, @Root Player player) {
    Objects.requireNonNull(event, "event");
    Objects.requireNonNull(player, "player");
    
    Logger logger = getLogger();
    
    PlayerInventory playerInventory = (PlayerInventory) player.getInventory();
    GridInventory gridInventory = playerInventory.getMainGrid();
    
    ItemStack itemStack = ItemStack.builder().quantity(10).itemType(ItemTypes.APPLE).build();
    InventoryTransactionResult result = gridInventory.set(new SlotPos(0, 0), itemStack);
    
    logger.info(result.getType().toString() + ": " +
                result.getRejectedItems()
                      .stream()
                      .map(ItemStackSnapshot::getType)
                      .map(ItemType::getId)
                      .collect(ImmutableList.toImmutableList())
                      .toString());
    
    EquipmentInventory equipmentInventory = playerInventory.getEquipment();
    
    logger.info("Equipment slots:");
    
    for (Inventory inventorySlot: equipmentInventory) {
        logger.info(inventorySlot.getClass().getName());
    }
}
```

Output:

```
FAILURE: [minecraft:apple]
Equipment slots:
org.spongepowered.common.item.inventory.adapter.impl.slots.SlotAdapter
org.spongepowered.common.item.inventory.adapter.impl.slots.EquipmentSlotAdapter
org.spongepowered.common.item.inventory.adapter.impl.slots.EquipmentSlotAdapter
org.spongepowered.common.item.inventory.adapter.impl.slots.EquipmentSlotAdapter
```

**Comment by Faithcaio** [comment]
`SlotPos.of(0,0)` gives you the SlotPos with the EQUAL operator use that here.
`new SlotPos(0,0)` defaults to DELEGATE which is used for creating inventories only.

**Comment by Lignium** [comment]
> `SlotPos.of(0,0)` gives you the SlotPos with the EQUAL operator use that here.
> `new SlotPos(0,0)` defaults to DELEGATE which is used for creating inventories only.

Oh, I'm completely confused with the Inventory API. Thank you for the explanation and the speed in fixing the second bug!
