### ISSUE TITLE
"getWeather" return strange values.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/Sponge#250]
"world.getWeather" return strange values.
If clear weather:
org.spongepowered.common.weather.SpongeWeather@53793239.

If rain weather:
org.spongepowered.common.weather.SpongeWeather@2cdd2d2.

If thunder weather:
org.spongepowered.common.weather.SpongeWeather@3a0f050f.

"world.getWeather.getName" always returns "weather".

![2015-04-26_21 46 32](https://cloud.githubusercontent.com/assets/10154956/7338191/f4b958fa-ec5d-11e4-9eb2-62737fbdbc99.png)

**Comment by RobertHerhold** [comment]
All of your links give 404's btw

**Comment by gyroninja** [comment]
It doesn't look like this is implemented yet. https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/weather/SpongeWeather.java It's hard coded right now to return "weather"

**Comment by Azatik** [comment]
@RobertHerhold, this is what returns "world.getWeather".

**Comment by Azatik** [comment]
@gyroninja thank you. Waiting for implementation.

**Comment by gyroninja** [comment]
@Azatik Would probably be best if you could open an issue on SpongeCommon just s a reminder that it still needs to be implemented.
