### ISSUE TITLE
`multi-world-patches` in global config works incorrectly.

### ISSUE THREAD

**Issue by ginyai** [SpongePowered/Sponge#2502]
https://github.com/SpongePowered/SpongeCommon/blob/851bff2a36f910feaa3f501b257bdc42317f6486/src/main/java/org/spongepowered/common/mixin/plugin/MultiWorldCommandPlugin.java#L56
The code here does not change after the Mixin classes renaming.
https://github.com/SpongePowered/SpongeCommon/commit/dd753ad39d53c3b267d12726c41429d4352ccd37

For example 
src/main/java/org/spongepowered/common/mixin/command/multiworld/MixinCommandDefaultGameMode.java → src/main/java/org/spongepowered/common/mixin/command/multiworld/CommandDefaultGameModeMixin_MultiWorldCommand.java

with class `MixinCommandDefaultGameMode` in the name will be “defaultgamemode”
and now it is “”

I was reading global.conf and cannot understand the meaning of 
```
        # Patches the specified commands to respect the world of the sender instead of applying the 
        # changes on the all worlds.
        multi-world-patches {
            ""=true
        }
```
I try to understand by reading the source and find out that this config is only used at `MultiWorldCommandPlugin`. I think this is an issue.

**Comment by dualspiral** [comment]
Follow the template like everyone else has to do and explain exactly what is going on and why it's a problem. This is a lazy attempt at an issue and, as someone who has been trying to prioritise issues, I honestly have no idea why this is an issue.

Just posting a code snippet and saying "this does not work" or "this no longer does what it should" is not helpful to those of us who haven't touched this part of the system and therefore might not necesarily know why this is a problem.

**Comment by ginyai** [comment]
@dualspiral I'm sorry. edited.

**Comment by ginyai** [comment]
And I find an old global.conf file with 
```
        multi-world-patches {
            defaultgamemode=true
            difficulty=true
            gamerule=true
            seed=true
            setdefaultspawnpoint=true
            time=true
            toggledownfall=true
            weather=true
            worldborder=true
        }
```
