### ISSUE TITLE
Issue with the `CraftItemEvent.Preview` 

### ISSUE THREAD

**Issue by ginyai** [SpongePowered/Sponge#2505]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.10-RC3994
- SpongeVanilla version: 
- Java version: 1.8.0_231
- Operating System: windows 10

- Plugins/Mods: only a test plugin with a listener
```java
    @Listener
    public void onCraft(CraftItemEvent.Preview event) {
        event.getTransactions().forEach(slotTransaction -> slotTransaction.setCustom(slotTransaction.getFinal()));
    }
```

**Issue Description**
When drag in crafting slots then release the left button, the output slot will show the craft as if there is only the first crafting slot is set.
images:
![N4M`9Y%XGNZZ49AW{683PST](https://user-images.githubusercontent.com/7886775/74551335-f786a180-4f8d-11ea-877b-4eb72fb2b2a9.png)
![S})A$Q10UA6`IHL9_WOPTUJ](https://user-images.githubusercontent.com/7886775/74551345-fa819200-4f8d-11ea-821b-79698345d349.png)
![QTMSWXWFUBSS9KB8VL{~S)J](https://user-images.githubusercontent.com/7886775/74551352-fd7c8280-4f8d-11ea-964d-0071cbac38de.png)

The event is fired form DragInventoryStopState
https://github.com/SpongePowered/SpongeCommon/blob/72a1d111b0aeceacf74f7595c26454f7e16a2737/src/main/java/org/spongepowered/common/event/tracking/phase/packet/drag/DragInventoryStopState.java#L61-L76

I add a breakpoint and find that the captured `previewTransactions` is more one.
In the first image, it is like:
1. air -> iron_nugget*9
2. iron_nugget*9 -> air
3. air -> air
4. air -> air

But we choose the first transaction as craft result.

**Comment by Lignium** [comment]
Related: https://github.com/SpongePowered/SpongeCommon/issues/2363#issuecomment-575887109

**Comment by ginyai** [comment]
Related: https://github.com/SpongePowered/SpongeCommon/commit/270d36cd4111eafd76ff184e293466b4c62cb65f
