### ISSUE TITLE
Server Crashing on adding Sponge Coremod

### ISSUE THREAD

**Issue by tomgie** [SpongePowered/Sponge#251]
When I add the Sponge Coremod to the server, it crashes and the server stops.

Forge Version: 1.8-11.14.1.1334-universal
Minecraft Version: 1.8
Sponge Version: 1.8-1371-1.1DEV-424 Main Version
Operating System: Debian Linux 7

Crash Report for fml-server-latest: http://pastebin.com/d2QYEUKx
Crash report for fml-junk-earlystartup: http://pastebin.com/3UPbeNLY

**Comment by Zidane** [comment]
http://files.minecraftforge.net/

Your Forge version is quite out of date. You need to be using 1.8-11.14.1.1371 or higher.
