### ISSUE TITLE
EntitySnapshot restore a removed Entity instance on DestructEntityEvent .

### ISSUE THREAD

**Issue by Xy718** [SpongePowered/Sponge#2512]
**I am currently running**

- SpongeForge version:  stable-7
- Java version: 1.8.0_181
- Operating System: Windows 7

**Issue Description**

### Event:
`DestructEntityEvent`
### Possible problematic code:
```
@Listener(order = Order.EARLY,beforeModifications = true)
public void onItemPickup(
	DestructEntityEvent event
	) {
	Entity targetItem=event.getTargetEntity();
	EntitySnapshot eSnapShot=targetItem.createSnapshot();
	Entity saveItem=eSnapShot.restore().get();
	Task.builder()
		.delayTicks(1)
		.execute(()->{
			saveItem.getWorld().spawnEntity(saveItem);
		})
		.submit(MyPlugin.get());
}
```

I need copy this targetItem to respawn after the event.
But the returns `targetItem#isRemoved()` and `saveItem#isRemoved()` are the same,both are `true`.
This caused the Item to be deleted immediately after it was generated.

I have solved it by other methods, but this maybe a Sponge problem,right?

**Comment by gabizou** [comment]
So there's a little bit of a disconnect: Do you want to restore the entity as it was or do you want to re-create a similarly like entity with the same type and metadata, but not the same unique id? If you're wanting to duplicate an item as it expires, you can make an archetype and spawn one from that archetype.

**Comment by Xy718** [comment]
Aww,i got it.Sorry for delaying your time!
