### ISSUE TITLE
UserStorageService#get queries data from Mojang

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/Sponge#2518]
**I am currently running**
- SpongeVanilla version: stable-7
- Java version: 1.8.0_121
- Operating System: Windows 10

When calling `UserStorageService#get(UUID)`, if the user has not joined the server yet, the SpongeUserStorageService will [try to create a new User](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/service/user/SpongeUserStorageService.java#L51) by querying it's GameProfile data from Mojang. Since `User` is a representation of the player data of an player who ever joined the server, I'd expect `service.get(UUID)` to return an `Optional.empty()` for users who haven't played in the server yet. I may be misundertanding the terms here, if so, some clarification would be appreciated.

I'm having problems with this because I'm loading data from many UUIDs, and wanted to get the name of the users for the ones who ever played in the server, but this is triggering many queries to Mojang, and I'm getting a lot of `AuthenticationException`s.

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 7) of SpongeAPI. Support for API 7 ended in January 2022.

API-7 is now end-of-life. We will not be issuing any more API updates for version 7 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API7/1.12.2[^2]
___

We now have UserManager, allowing people to choose between `load` and `loadAndCreate`

[^1]: https://forums.spongepowered.org/t/status-update-8th-january-2022-spongeapi-8-released/39861#minecraft-1122-spongeapi-7-10
[^2]: https://forums.spongepowered.org/t/sponge-status-update-28th-may-2022/40135#api-71122-community-support-8
