### ISSUE TITLE
InteractItemEvent.Primary delayed while jumping

### ISSUE THREAD

**Issue by SocraticPhoenix** [SpongePowered/Sponge#2526]
**Tested on:**
- Windows 10, Java 1.8.0_241

- Sponge Vanilla 1.12.2-7,1,10 (recommended/stable build as of today)
- Sponge Vanilla 1.12.2-7.1.11-RC346

**Issue:**
`InteractItemEvent.Primary` seems to fire late, sometimes, if the player is jumping.

Test plugin: https://gist.github.com/SocraticPhoenix/f1942d4e39b6a1e101669a1c6f56b997
Video showing behavior: https://youtu.be/1aSCkg8HWEI
(delay most visible at 0:10)

**Comment by Yeregorix** [comment]
I've found a similar issue few days ago with `InteractBlockEvent.Primary`. The event can be delayed indefinitely if the player is in adventure mode and if he doesn't move. It seems to be related to this method in the implementation: https://github.com/SpongePowered/SpongeCommon/blob/4a9742b465d095769fa4e6ca5fbf22865e3de87b/src/main/java/org/spongepowered/common/mixin/core/server/MinecraftServerMixin.java#L321

If we read this method we can also quickly understand another big issue: if multiple players click in the same tick, there will be a event only for the last player.

**Comment by JBYoshi** [comment]
Looks like the PR was closed a while ago, so I'll close this. Reopen if it still happens.
