### ISSUE TITLE
Tab-Autocomplete throws an Exception

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#253]
**Sponge:** sponge-1.8-1371-2.1DEV-428
**Forge:** 8.0.76.1397
**Client:** Vanilla 1.8.4
**Plugins/Mods:** none
**Java Version:**
> `C:\Windows\system32>java -version`
> `java version "1.8.0_40"`
> `Java(TM) SE Runtime Environment (build 1.8.0_40-b25)`
> `Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)`

**OS:** Windows 7 - 64 bit

If you type `/tell ` *(with space at the end)* and press tab, you get an ArrayIndexOutOfBoundsException. Here is the [Console-Output](http://pastebin.com/XNRKM8z9), and here the [latest fml-server.log](http://pastebin.com/tcEEi6rM).

**Comment by nikosgram13** [comment]
Have you update the submodules?

**Comment by boformer** [comment]
@nikosgram13 I guess he downloaded the compiled jar from the repo.

**Comment by TBlueF** [comment]
@boformer thats right. :)
