### ISSUE TITLE
Projectiles hit players in spectator

### ISSUE THREAD

**Issue by jacksonhardaway** [SpongePowered/Sponge#2533]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.9
- Java version: OpenJDK JRE 1.8.0_242
- Operating System: Linux (unknown distro, using a host)

- Plugins/Mods: None

**Issue Description**
Projectiles such as snowballs, splash potions, lingering potions, etc. hit spectators as if they were in another gamemode. For example if I throw a splash potion as someone who is in spectator, the splash potion will splash as if the player was in survival or creative.

**Comment by LXGaming** [comment]
This bug was introduced in SpongeForge-1.12.2-2838-7.1.7-RC3905 which included this commit https://github.com/SpongePowered/SpongeForge/commit/17981cbfa4a5d8d89ca2a3275b234a9d9cebc46c

**Comment by JBYoshi** [comment]
Should be fixed in the next Sponge builds.
