### ISSUE TITLE
Problem with Sponge on my server

### ISSUE THREAD

**Issue by lncogmito** [SpongePowered/Sponge#254]
Forge version: 1.8-11.14.1.1397
Sponge: 1.8-1371-2.1DEV433

I have a problem when i put sponge on my server (into the mods folder)
When i have a mod in it: it's ok but when it s sponge, i suddenly cannot make anything with the RCon or something else. The error message when i try to make any commands in the rCon:

"Error executing: help (net.minecraft.network.rcon.RConConsoleSource cannot be cast to org.spongepowered.api.util.command.CommandSource)"

I don t uderstand what i need to do. Can you help me please

**Comment by Zidane** [comment]
Rcon support hasn't been implemented from the API.

**Comment by lncogmito** [comment]
Excuse me but i'm belgian, so i don't understand very well what you mean in your sentence.
(and I'm sorry for every mistake I can do)

**Comment by Zidane** [comment]
@lncogmito 

Its a bug with Sponge and we'll get it fixed up as soon as we can.

**Comment by lncogmito** [comment]
Ok, i just understood your first answer. Can we know how we will know when this bug will be fixed up?

**Comment by Zidane** [comment]
@lncogmito 

Depends on people's availability. You shouldn't be trying to run Sponge as your live server, it should only be used for testing.

**Comment by lncogmito** [comment]
Ok thank you

I hope this report will help you in the sponge's conception

**Comment by lncogmito** [comment]
I don't understand what are the reference you are giving zml :/

**Comment by ST-DDT** [comment]
I guess he referenced this Pr in the commits that (partially or fully) fixes this issue.

**Comment by zml2008** [comment]
That is the commit that fixed this issue. Guess @Zidane accidentally stripped that out when merging the PR.
