### ISSUE TITLE
Implement `ItemStack`/`ItemStackSnapshot` isEmpty().

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Sponge#2544]

**Comment by JBYoshi** [comment]
I think this has been implemented. https://github.com/SpongePowered/SpongeCommon/blob/175e583203cba692d42ad0b0265949d74bebbea3/src/mixins/java/org/spongepowered/common/mixin/api/mcp/item/ItemStackMixin_API.java#L209-L212
