### ISSUE TITLE
Spongeforge on an RLCraft server: WorldServer cannot be cast to WorldBridge

### ISSUE THREAD

**Issue by syntience** [SpongePowered/Sponge#2556]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.2.0
- Java version: 1.8.0_242
- Operating System: Linux (amd64)

- Plugins/Mods: https://www.curseforge.com/minecraft/modpacks/rlcraft/files/2836138 (no plugins yet)

**Issue Description**
trying to run an rlcraft server using spongeforge. this crash happens sometime during startup. what do? i've already looked at https://www.curseforge.com/minecraft/modpacks/rlcraft/files/2836138.

crash log: https://gist.github.com/syntience/a39c6ebb6220c574977d75a0f7def1bb

**Comment by Zidane** [comment]
We cannot fix issues if you do not provide us a log. Please adhere to the issue template and we'll re-open when you do.

**Comment by syntience** [comment]
> 
> 
> We cannot fix issues if you do not provide us a log. Please adhere to the issue template and we'll re-open when you do.

shoot sorry. i even had the git gist ready, just forgot to include it. updated the post @Zidane

**Comment by syntience** [comment]
fixed. i just had to revert to an older version of  spongeforge (7.1.8)

**Comment by gabizou** [comment]
> fixed. i just had to revert to an older version of spongeforge (7.1.8)

That's not a fix... You should provide the log and we can try to figure out what changes took place, because 7.2.0 is pretty important for a bug fix that was made. Sticking with older versions of SpongeForge is never recommended.

**Comment by Aiidoneus** [comment]
You need to update Tickprofiler. It is a server side mod so updating it shouldn't hurt users trying to connect to your server

**Comment by syntience** [comment]
> 
> 
> > fixed. i just had to revert to an older version of spongeforge (7.1.8)
> 
> That's not a fix... You should provide the log and we can try to figure out what changes took place, because 7.2.0 is pretty important for a bug fix that was made. Sticking with older versions of SpongeForge is never recommended.

fair i guess. 



> 
> 
> You need to update Tickprofiler. It is a server side mod so updating it shouldn't hurt users trying to connect to your server

will try, thanks
