### ISSUE TITLE
Incorrect implementation of User.getLocation

### ISSUE THREAD

**Issue by TheGlitch76** [SpongePowered/Sponge#2559]
**stable-7**
User.setLocation should only work on already loaded worlds, and not attempt to load one if it is now found. (see [here](https://github.com/SpongePowered/SpongeCommon/pull/2558/commits/1a4242a42677580ea024a7eda4514202fd7a47bb#r405228485))
[This method](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/api/mcp/entity/player/EntityPlayerMPMixin_API.java#L653) should be corrected to attempt to get the world directly through the list of loaded worlds (unsure of the api7 specifics on that) and orElseThrow if it is not found.

**Comment by ImMorpheus** [comment]
api7 is going to stay like this.
api8 was fixed by https://github.com/SpongePowered/SpongeCommon/pull/2558
