### ISSUE TITLE
Console spam SpogeForge error

### ISSUE THREAD

**Issue by Youwenqwq** [SpongePowered/Sponge#2563]
### I am currently running

- SpongeForge version: 1.12.2-2838-7.2.0
- SpongeVanilla version: 1.12.2-7.2.0
- Forge version: 14.23.5.2847
I am using 2847 because there are some mods don't support 2838
- SpongeAPI: 7.2-fe189dcf
- Java version: 1.8.0.241
- Operating System: Windows Server 2016 LTS

- Plugins/Mods:

`Plugins (14): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, DupeFixer, FlexibleLogin, LuckPerms, MMCRestrict, Nucleus, Prism, SkinChanger, TitleMOTD, TogetherMusic, WorldEdit`

`Mods (35): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advent Of Ascension, Another Common Bug Fix, AppleCore, AppleSkin, Applied Energistics 2, Backpack, Chameleon, Cucumber Library, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Just Enough Items, JustEnoughIDs, LunatriusCore, Mystical Agriculture, Patchouli, SpongeForge, Storage Drawers, Touhou Little Maid, Up-Sizer`

### Issue Description
[ErrorLog-Github-Gist](https://gist.github.com/youwen233/26513549e78dfbfdc123d3cd0470979d)
[ErrorLog-2](https://gist.github.com/youwen233/8c56324fffd15e7984dfe9466ee2ee41)

**Comment by clienthax** [comment]
Full log is required

**Comment by dualspiral** [comment]
No response for three weeks. Closing.
