### ISSUE TITLE
when i have sponge and one other mod when i go in my world and exit out it freezes

### ISSUE THREAD

**Issue by LOLDERP** [SpongePowered/Sponge#258]
when i have sponge and one other mod when i go in my world and exit out it freezes

**Comment by Zidane** [comment]
@LOLDERP 

I need the log that your server generated. Please use a service like gist and put a link here.

**Comment by mcsnetworks** [comment]
Define freeze.  Are you getting a spike on the CPU or does the server stop "ticking" ?

**Comment by Zidane** [comment]
Closing due to lack of feedback.
