### ISSUE TITLE
MariaDB 2.0.3 connector doesn't support MySQL 8.X versions

### ISSUE THREAD

**Issue by victorbetoni** [SpongePowered/Sponge#2589]
**I am currently running**
- SpongeVanilla version: 7.1.0
- Java version: 8
- Operating System: Windows 10

I tried to connect to my mysql server through Sponge using SqlService but I got the following error:
 
`[com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: (conn:8) Unknown system variable 'tx_isolation'`

I took a look in a topic about this error and it said that this error is due to the outdated connector.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/2008#issuecomment-622525155

We're actually looking at this and I expect to have this sorted soon - closing this in favour of that.
