### ISSUE TITLE
Request: add configuration option to disable WorldUnload if server is NOT shutting down

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/Sponge#2590]
Hello, 
I am asking for a configuration option be added here:
https://github.com/SpongePowered/SpongeCommon/blob/save-off/src/main/java/org/spongepowered/common/world/WorldManager.java#L536

In the event that the server is NOT shutting down, a configuration value here would prevent a world from being unloaded even if it was asked to because the loaded chunk list was empty.  

Note: I assume there is a better way of doing this.
Reason: We utilize TerrainControl with thousands of configuration biomes and custom objects.  I am allowing spawn chunks to unload to save on ticks, but in the event the world unloads during normal operation, when the world is reloaded all of the configuration values for TC have to reload, which takes around 10-20 seconds.

I added a :return false: to the line above for usage with Almura.

**Comment by Zidane** [comment]
Closing this as it is likely to not happen for 1.12. This has been added for 1.16.5+ and you have a workaround you added for your own needs.
