### ISSUE TITLE
Potential SpongeFabric?

### ISSUE THREAD

**Issue by enderger** [SpongePowered/Sponge#2601]
**I am currently running**

- SpongeForge version: N/A
- SpongeVanilla version: N/A
- Java version: N/A
- Operating System: N/A

- Plugins/Mods: N/A

**Issue Description** - My server has been wanting to implement the fabric mod called Carpet but we use plugins and we think that a Fabric implementation of Sponge could help us with that. I think that many of us would appreciate one and I hope that this makes it into this project. I was not able to find an issue pertaining to this, so here I am making one.

**Comment by Zidane** [comment]
@enderger 

I appreciate your enthusiasm for the project but I must, unfortunately, decline at this time.

As it stands, the official SpongeAPI implementation is targeting either plain "Vanilla" Minecraft or provided as a Mod for interoperability with Minecraft Forge.

Sponge respects the work of the Fabric team and have worked with individuals from their camp on numerous occasions. A few of them have helped us tremendously, thus far, on the Minecraft 1.14.4 port.

That said, creating a new implementation is not a decision that is to be made lightly. It adds a tremendous amount of work (supporting Minecraft Forge as a mod has been an incredible undertaking) and is something I, as a leader of this ecosystem, cannot authorize at this time.

Now if an individual or group decides to implement SpongeAPI onto the Fabric ecosystem, we would be more than happy to assist them with any necessary API changes that both camps can agree upon.
