### ISSUE TITLE
PlayerChatEvent's getMessage is not correct

### ISSUE THREAD

**Issue by pqqqqq** [SpongePowered/Sponge#261]
In the forge implementation of Sponge, when using the PlayerChatEvent#getMessage event, the method returns a Text that includes the player's name in angle brackets (<>). For example, if I type "hi" into the server getMessage would return \<pqqqqq\> hi.

Workspace info if you need it:
Forge version: 1.8-11.14.1.1371
Sponge build: 1.8-1371-2.1DEV-437

**Comment by simon816** [comment]
This may actually be a useful feature if a plugin want's to manipulate the player name for example.
I'm assuming it's unintentional though.

**Comment by ryantheleach** [comment]
Yeah this should be intended, otherwise how else are formatting plugins supposed to format the whole message?

The message comes out as a Text so it should be possible to break it back into parts to get the playername right?

**Comment by ZephireNZ** [comment]
The problem with the current implementation is that plugins wanting to format the message would have no idea where the message starts and the prefix ends. Perhaps spit this into `getPrefix()` and `getMessage()` which would allows plugins to modify the prefix much more easily.

**Comment by ryantheleach** [comment]
I'm not sure that's true. What format is the Text? if it's possible to break it into it's translatable parts then it provides more flexibility then getPrefix would.

**Comment by zml2008** [comment]
I want to do something like getMessage, which returns the original message, and getFormattedMessage, which returns the message with formatting & stuff applied.

**Comment by boformer** [comment]
It would be nice to have a ``setFormat(Text format)`` method like Bukkit had, with placeholders that will be replaced. That is better than a ``getPrefix`` and easier to manipulate than ``getFormattedMessage``: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/AsyncPlayerChatEvent.html#setFormat%28java.lang.String%29

**Comment by zml2008** [comment]
However formats are a pain to do with the Text system (A good API class to handle template usage would be very nice though, imo the optimal solution if somebody has the time to write it *hint* *hint*).
Currently the only Text class that supports placeholders is the Translatable, which is considered a single unit for styling and links.
