### ISSUE TITLE
Vanish state can't pickup any items

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#2615]
**I am currently running**
 SpongeAPI: 7.2.0-f12f8e774
 Sponge: 1.12.2-7.2.2-SNAPSHOT
 SpongeForge: 1.12.2-2838-7.2.2-RC4027
 Minecraft Forge: 14.23.5.2847

When the player enters the vanish state, they cannot pickup any items
https://gyazo.com/f5c5414245ec663b898ad826d2958a94

**Comment by clienthax** [comment]
Well yeah, that's intended

**Comment by ghost** [comment]
Is it possible to enter vanish state to pick up items?
Or are there any options to set them?

**Comment by clienthax** [comment]
The entire point of vanish is to not interact with any visible impact, any other implementations would have to toggle this in the way they enable vanish

**Comment by dualspiral** [comment]
Just to clarify:

> Is it possible to enter vanish state to pick up items?
> Or are there any options to set them?

It's not down to implementation itself, but the plugins that enable/disable vanish. There are two options available to vanish, one of those would re-enable collisions - needed for picking up items. If you're using Nucleus, I turn that off and always have done, it's just that Sponge has caught up with what it meant.

Ask on the **plugin** issue tracker that puts you into vanish if you want to have this supported.

**Comment by ghost** [comment]
Yes, I use Nucleus
and how do I enable vanish collisions?

**Comment by dualspiral** [comment]
Please read the entire comment.
> Ask on the **plugin** issue tracker that puts you into vanish if you want to have this supported.
