### ISSUE TITLE
Errors with unqualified access to instance variables.

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/Sponge#262]
These places don't use `this.` for access to instance variables:

- [MixinEventPlayerChat:74](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/event/player/MixinEventPlayerChat.java#L74)
-  [SpongeModGameRegistry:103-104](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/registry/SpongeModGameRegistry.java#L103-L104)

**Comment by Deamon5550** [comment]
Covered by #263
