### ISSUE TITLE
NPE in o.s.c.world.WorldManager#loadWorld

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#2639]
[This function](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/world/WorldManager.java#L619) declares that its `properties` parameter is `Nullable`, yet calls a method without null-checking in line 635. Since `loadWorld(String)` passes null for that parameter, this results in a guaranteed exception when the method is called for a world that doesn't exist, instead of returning `Optional.empty()` like it's supposed to.

**Comment by dualspiral** [comment]
Spotted it, thanks.

In the future, _please_ use the template provided. There is no version information here in particular, and your link doesn't link to a specific commit so if we'd left this some time, we may have ended up somewhat confused.
