### ISSUE TITLE
LaunchProjectileEvent does not fire without empty AffectEntityEvent listener

### ISSUE THREAD

**Issue by codestripper** [SpongePowered/Sponge#2648]
I know this sounds dumb, and maybe I'm just doing this incorrectly. I'm trying to get LaunchProjectileEvent to fire when I throw a bottle of enchanting. Sounds easy enough. Here's my code:
`@Listener
    public void onLaunchProjectile(LaunchProjectileEvent event) {
        Logger logger = plugin.getInstance().getLogger();
        logger.info("Made it to listener");
    }`

No matter what I do, this event will not fire unless I also include the AffectEntityEvent listener in the plugin, or even in a different plugin:
`@Listener
    public void onInteractEntity(AffectEntityEvent event) {
    }
`

**Comment by codestripper** [comment]
@dualspiral I can confirm that adding `-Dsponge.shouldFireAll=true` to the argument line "fixes" the issue. I am able to remove the AffectEntityEvent listener and the LaunchProjectileEvent fires as it should.

**Comment by RedNesto** [comment]
Maybe it happens because LaunchProjectileEvents are [fired from SpawnEntityEvent](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java#L301) (except plugin-launched ones)
