### ISSUE TITLE
No obfuscation mapping for @Overwrite method

### ISSUE THREAD

**Issue by wizardsambolton** [SpongePowered/Sponge#268]
I am getting this error: No obfuscation mapping for @Overwrite method after running the mixin stuff

**Comment by Minecrell** [comment]
Can you post the **full log** or is this the only message you're getting?

**Comment by wizardsambolton** [comment]
@Minecrell Sure Description	Resource	Path	Location	Type
No obfuscation mapping for @Inject target moveDerailedMinecart	MixinEntityMinecart.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/entity/vehicle	line 69	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Inject target updateEntities	MixinWorld.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/entityactivation	line 57	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinEntityMinecart.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/entity/vehicle	line 59	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinMinecraftServer.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/server	line 101	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinMinecraftServer.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/server	line 189	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinSaveHandler.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/world	line 58	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinSaveHandler.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/world	line 78	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinSaveHandler.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/world	line 127	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinSaveHandler.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/world	line 192	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinServerConfigurationManager.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/server	line 129	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinServerConfigurationManager.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/server	line 236	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinServerConfigurationManager.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/server	line 367	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinServerConfigurationManager.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/server	line 376	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinWorld.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/entityactivation	line 66	Annotation Problem (Java 6 processor)
No obfuscation mapping for @Overwrite method	MixinWorldProvider.java	/Sponge/src/main/java/org/spongepowered/mod/mixin/core/world	line 63	Annotation Problem (Java 6 processor)

**Comment by ST-DDT** [comment]
Is this error from your IDE? And which one do you use?

**Comment by wizardsambolton** [comment]
@ST-DDT yes this is in my IDE and i am using eclipse

**Comment by Mumfrey** [comment]
It means you missed the step of specifying `reobfSrgFile` or specified the wrong file when you did so.

**Comment by wizardsambolton** [comment]
@Mumfrey ok thanks but remind me briefly where i do that?

**Comment by Mumfrey** [comment]
If you know how to do that at all, I can only assume you got it from my tutorial video. In which case the instructions are [right there](https://youtu.be/6d42wDHbAfE?t=463).

**Comment by wizardsambolton** [comment]
@Mumfrey Edit: checked and it seems that i have specified it

**Comment by Mumfrey** [comment]
The capitalisation is important.

**Comment by wizardsambolton** [comment]
i have it capitalised like this: reobfSrgFile

**Comment by Mumfrey** [comment]
That's correct, check that the correct file is specified and that there are no quotes or spaces in the value. If you're certain it's right then force a full rebuild of all projects by selecting `Project` -> `Clean` -> `Clean All Projects`

**Comment by wizardsambolton** [comment]
@Mumfrey still not working

**Comment by wizardsambolton** [comment]
wait fixed thanks! turned out i had to remove file:///
