### ISSUE TITLE
Update PathAsFileProvider from core:invalid

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Sponge#2680]
Located in: [core:invalid](https://github.com/SpongePowered/SpongeCommon/blob/6dc6982ad7d3ed44eb5ab542f1fcff51e2e1af38/invalid/main/java/org/spongepowered/common/inject/provider/PathAsFileProvider.java)

Part of: provider

This is part of the upgrade process for Sponge and is likely involving some work and investigation.

Advice and tips include:
- Sometimes things are just a simple method name change
- Might be a new class or field
- Understanding what the original intention of the target code had
- Analyzing whether the functionality achieved by the target class/mixin still exists
- Understanding the new functionality in the new Minecraft version that requires rewriting for the functionality
- The SpongeAPI usage could very well have gone ~~missing~~ out the window if functionality was deemed unnecessary for release

**Comment by ImMorpheus** [comment]
Updated in https://github.com/SpongePowered/Sponge/commit/93a3b045a8a9b69e0f49ed21263809864d50fb02

Dropped in https://github.com/SpongePowered/Sponge/commit/97ef12fad044e4f95373ea578e1f4f8630dc7d32
