### ISSUE TITLE
Sponge server GUI stays open in the backround

### ISSUE THREAD

**Issue by TheDoctorsLife** [SpongePowered/Sponge#269]
on the latest sponge build (441), when you double click the sponge jar, pulling up the gui, it continues to stay open in the background. after letting it run for an hour I finally forced closed it if you need any info I will provide it, I'll post some screenshots later on.

EDIT: This only occurs when clicking the "Ok" button, closes the window via. the "x" mark for windows kills the java proccess as well.

**Comment by simon816** [comment]
All that needs to be done is add `dialog.dispose();` after [this line](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/launch/Main.java#L100)
