### ISSUE TITLE
Cannot run sponge.jar install,run,or go

### ISSUE THREAD

**Issue by TheDoctorsLife** [SpongePowered/Sponge#270]
It immediately pulls up the gui instead of installing sponge. (or running it (kindof))

EDIT: I'm running build 441

**Comment by Mumfrey** [comment]
What operating system?

**Comment by TheDoctorsLife** [comment]
Windows, I'm running through cmd

**Comment by Mumfrey** [comment]
It's impossible to troubleshoot this kind of thing in a Q/A fashion, please provide as much information as possible. What operating system are you running? What (if anything) is shown in the console when you run the jar? What command are you running? What java version are you running?

**Comment by liach** [comment]
It is a mod jar not a installer I think.

**Comment by TheDoctorsLife** [comment]
I am running Windows 7, nothing shows up in console, ```C:\Users\benjamin.hoffmeyer\Desktop\Minecraft\runtime\jre-x64\1.8.0_25\bin\javaw.exe -jar sponge-1.8-1371-2.1DEV-441.jar install,run, or go``` 1.8 update 25.

**Comment by Mumfrey** [comment]
You're running `javaw.exe` that's why, that's the intended behaviour. For console use you should use `java.exe`

**Comment by TheDoctorsLife** [comment]
*facepalm* thanks, for some reason I was thinking sponge is minecraft.

**Comment by Mumfrey** [comment]
As mentioned in the article I linked, `javaw.exe` doesn't present a console to the application, and so the console capabilities required for `install`/`run`/`go` are not available.
