### ISSUE TITLE
Player moved too fast! issues on setting location and bizzare coordinate reported

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#271]
Folks aren't sure if this is an implimentation or API issue:
Setting a player location sometimes causes the server to block it as a moved-too-quickly event, which is unavoidable - we're moving them instantaneously across the map :)

But in addition, the logs have mysterious output when it cancels.  The coordinates randomly get negated, even the Y coordinate in back to back trials:

BooMod moved too quickly! -605.0,-20.09800000190735,170.0 (605.0, 20.09800000190735, 170.0)
[16:50:40] [Server thread/WARN]: BooMod moved too quickly! -43.0,13.0,-259.0 (43.0, 13.0, 259.0)
[16:50:46] [Server thread/WARN]: BooMod moved too quickly! 43.0,-13.0,259.0 (43.0, 13.0, 259.0)
[16:51:43] [Server thread/WARN]: BooMod moved too quickly! 86.5,71.0,-194.5 (86.5, 71.0, 194.5)

Forge Mod Loader version 8.0.76.1397.

**Comment by Aaron1011** [comment]
This is an implementation issue. Currently, there's no method in the api to disable the check.

**Comment by theboomer** [comment]
would the odd coordinate sign-swapping in the output be a totally different issue then within the moved-too-fast handling code?  Its not like the system is always negating the z in reporting the output, for example.

**Comment by ryantheleach** [comment]
Would it be worth adding a method to teleport players as opposed to setting their locations?

**Comment by ST-DDT** [comment]
I consider setLocation the same as teleport.
So i don't see a reason to add another method for that.

**Comment by WhippyCleric** [comment]
I've found this too, I'm in the process of writing a command system plugin which includes home, spawn etc an on random occasions this does occur. Given the usage of spawn command on so many servers I would view this is a high priority bug in the implementation

**Comment by Zidane** [comment]
@bloodmc 

You know 100x more about this than me due to your time with Cauldron. Could you rectify this in SpongeCommon?

**Comment by bloodmc** [comment]
Sure, I'll take a look tomorrow.

**Comment by bloodmc** [comment]
@theboomer Please provide me with a copy of a test world and exact code you are using to trigger the issue. I have a fix but need to confirm it works before pushing. Thanks!

**Comment by theboomer** [comment]
Its been n number of builds since the tests were done, and I dont know if I have a working state plugin for what did that, but im sure i can try to put something together to test, and will figure out a way to make the files available.  If not in 30min, then will have to wait til tomorrow, but will-do

**Comment by theboomer** [comment]
I managed to recover the functional test part of the code out of comments but while trying to recompile to test it, its not cooperating.  My CommandExecutor implementing classes /command builder things dont seem to be happy as they are.    I haven't written a command handler code in a long time, so in case something strange has changed that I am unaware of in recent builds...  I'm currently using the 1446 forge and 1446-dev482 sponge versions on my test server.

I'm getting Caused by: java.lang.NoSuchMethodError: org.spongepowered.api.util.command.spec.CommandSpec$Builder.setDescription(Lorg/spongepowered/api/text/Text;)Lorg/spongepowered/api/util/command/spec/CommandSpec$Builder;

Yet there are no errors apparent in Eclipse, the error suggests that the setDescription() part of the commandspec builder is not in the current code, yet, its still in the intelletext if I create a new command, and if i comment it out, then the error is on the next command-spec property..  I haven't tried any coding in several weeks, and have switched forge versions a few times recently, so i dont know to what extent this 

I will keep pushing to try to get this to compile, I have even written a clean new plugin just copy/pasting the module code over to it, with same results...

**Comment by theboomer** [comment]
https://forums.spongepowered.org/t/mystery-eclipse-issue-with-magical-nonimporting-imports/7989  Is what is holding me back from retesting this and giving you anything.  I dont know if its something weird in a configuration, or if my Eclipse has decided to rise up against me, but I'm stuck in a rut unable to compile a working plugin and until I can resolve it, your request will be stuck.

**Comment by theboomer** [comment]
Resolved the mystery issue (answer was D'oh) for part of it, and wrong api dependancy version, but now I need to rewrite the scheduler part to compile..

**Comment by theboomer** [comment]
I said screw-the-scheduler and went straight to moving the player to coordinates, which is what I was using before implimenting a delay that didn't help anyways...
========
I have not been able to get the same moved-too-quickly errors at any time from over 100 tp jumps at different times and frequency of jumping with sponge 1446-dev500  and forge 1446
=========
I am including all the module code that should have been the code used to get the spotty motion results, map coordinates are hardcoded to move the player within the same world.  
The map I've uploaded to here:
http://www.ethicraft.net/world.zip

I wish I could generate the failure results still, I'm sure its possible by matching the right versions of api and dependancies, which i have no idea how to do at this time.
