### ISSUE TITLE
PlayerEnterBedEvent Seems to do nothing

### ISSUE THREAD

**Issue by WhippyCleric** [SpongePowered/Sponge#272]
PlayerEnterBedEvent seems not to fire, or the subscription is not working. I have the code shown at below. I would expect this to log "entered bed" but it seems to do nothing.

import org.slf4j.Logger;
import org.spongepowered.api.event.Subscribe;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.event.entity.player.PlayerEnterBedEvent;
import com.google.inject.Inject;

@Plugin(id = "WhipCommands", name = "WhipCommands")
public class WhipCommands {
        @Inject
	Logger logger;

	@Subscribe
	public void onPlayerEnterBed(PlayerEnterBedEvent event) {
		logger.info("entered bed");
	}
}

Sponge Build: sponge-1.8-1371-2.1DEV-445
Forge Build: forge-1.8-11.14.1.1371-universal
Client Type/Version (Forge/Vanilla and version) : Forge forge-1.8-11.14.1.1371-universal
Installed Plugins and/or Mods: Only sponge and my test  plugin
Java Version: 1.7.0_79
Operating System: Windows 7 64 bit

**Comment by kenzierocks** [comment]
There's no implementation probably.

**Comment by WhippyCleric** [comment]
That would seem to be the case, is this the place to request an implementation to be written? If someone has a guide to contribution I'm happy to have a go myself

**Comment by Deamon5550** [comment]
It hasn't been implemented yet, but I've tagged this issue with help wanted so at some point someone will implement it and this issue will be closed.

Opening issues like these does help us prioritize which events we're implementing.

**Comment by ryantheleach** [comment]
Is this still an issue? Looking at the implementation this is a forge event, So it probably still needs to be implemented on Vanilla, but is it being thrown on Sponge?

**Comment by Zidane** [comment]
Closing this as the new events system makes how this did work not relevant anymore. We just need to fire this.
