### ISSUE TITLE
PlayerEvent / UserEvent constantly triggered with open-container event

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#273]
Trying to map-out what events trigger and dont trigger yet.  PlayerEvent and UserEvent spam alternatingly as soon as player logs in, without any movement/action taken.  
Logging the getClass().getName() of the event, this is it:

 PlayerEvent net.minecraftforge.event.entity.player.PlayerOpenContainerEvent
 UserEvent  net.minecraftforge.event.entity.player.PlayerOpenContainerEvent
 PlayerEvent net.minecraftforge.event.entity.player.PlayerOpenContainerEvent
 UserEvent  net.minecraftforge.event.entity.player.PlayerOpenContainerEvent
 PlayerEvent net.minecraftforge.event.entity.player.PlayerOpenContainerEvent
 UserEvent  net.minecraftforge.event.entity.player.PlayerOpenContainerEvent
 PlayerEvent net.minecraftforge.event.entity.player.PlayerOpenContainerEvent
 UserEvent  net.minecraftforge.event.entity.player.PlayerOpenContainerEvent

Not able to clear that in any way - no containers are opened, no interface open on the client.  
I do see that it doesn't appear to be an event from sponge but forge maybe?  
Is the generic "userevent" and "playerevent" meant for capturing non-sponge api events?

And is that opencontainer event being thrown for a good reason that I dont understand, or is this a bug in forge or in sponge that is triggering something that shouldn't be?

**Comment by simon816** [comment]
Looks like an issue with forge, https://github.com/MinecraftForge/MinecraftForge/issues/1871

**Comment by Zidane** [comment]
Well the open container event isn't a bug except for its, possibly, bad naming.

Namely PlayerOpenContainerEvent is moreso PlayerOpenContainerTickEvent...it isn't meant for when the container is first opened.

**Comment by mossyblog** [comment]
Zidane: So really the name of the event is just onUpdateTickEvent in reality. Given it will always fire as long as player has an inventory (which i'm assuming is 100% of the time). Ideally the concept that PlayerOpenContainer event should fire is within ChestContainer/Container class via Open/Close inventory methods?
