### ISSUE TITLE
Update MapStorageMixin from core:invalid

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Sponge#2757]
Located in: [core:invalid](https://github.com/SpongePowered/SpongeCommon/blob/6dc6982ad7d3ed44eb5ab542f1fcff51e2e1af38/invalid/main/java/org/spongepowered/common/mixin/invalid/core/world/storage/MapStorageMixin.java)

Part of: storage

This is part of the upgrade process for Sponge and is likely involving some work and investigation.

Advice and tips include:
- Sometimes things are just a simple method name change
- Might be a new class or field
- Understanding what the original intention of the target code had
- Analyzing whether the functionality achieved by the target class/mixin still exists
- Understanding the new functionality in the new Minecraft version that requires rewriting for the functionality
- The SpongeAPI usage could very well have gone ~~missing~~ out the window if functionality was deemed unnecessary for release

**Comment by tyhdefu** [comment]
MapStorage no longer exists in 1.16. Instead its purpose is served via DimensionDataStorage, and getting map data is done from here.
Code snippets of changes 
```
@Nullable
public MapItemSavedData getMapData(String var1) {
    return (MapItemSavedData)this.getServer().overworld().getDataStorage().get(() -> {
        return new MapItemSavedData(var1);
    }, var1);
}
public void setMapData(MapItemSavedData var1) {
    this.getServer().overworld().getDataStorage().set(var1);
}
```
The MapStorage I added in the Map Api was purely a sponge concept, that sorted everything maps into one place.
This purely seems to be checking for async thread access, so if anything these injects should be put onto DimensionDataStorage to check for async access there.
