### ISSUE TITLE
Text on Signs not showing

### ISSUE THREAD

**Issue by Ekranos** [SpongePowered/Sponge#278]
When i want to plant a sign with some text on it, i get the following exception and the text doesn't show up.

http://pastebin.com/babkJZdp

Im running:
Forge: forge-1.8-11.14.1.1410-universal
Sponge: sponge-1.8-1371-2.1DEV-455

It's a fresh forge installation with ONLY sponge. Also this problem doesn't happen when i remove sponge.

**Comment by simon816** [comment]
This crash has been posted a few times now.
https://github.com/SpongePowered/Sponge/issues/266#issuecomment-103403545 and https://github.com/SpongePowered/SpongeCommon/pull/42#issuecomment-104173699, it needs further investigation.

I notice you have a different forge build (`1410`) to the one sponge is using (`1371`). As a general rule, make sure you have the same number, and only submit issues if they are.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/Sponge/commit/6836a463bd42923935e9383682528c40ffa76174
