### ISSUE TITLE
Watchdog bites while debugging

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#280]
Hello!

Is there a way to relax the watchdog while I'm debugging(line by line)? Of course, the watchdog thinks that nothing is happening(while I let execute the code line by line), so it gets angry. :dog: 

``[21:45:12] [Server Watchdog/FATAL]: A single server tick took 124,08 seconds (should be max 0,05)
[21:45:12] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
``

**Comment by simon816** [comment]
In `server.properties` there is a key `max-tick-time`, set it to a big number.

**Comment by randombyte-developer** [comment]
Thank you!

**Comment by Aaron1011** [comment]
@randombyte-developer: You can also set it to 0, which disables the watchdog thread entirely.

**Comment by randombyte-developer** [comment]
Good to know. Thanks! 
This should be written down somewhere in the docs.
