### ISSUE TITLE
Potion effects not updating when switching worlds

### ISSUE THREAD

**Issue by verbeto** [SpongePowered/Sponge#285]
When teleporting a player to another world using `transferToWorld`, potion effects are not properly updated on the client. To fix this, line 120 in [MixinEntity](https://github.com/SpongePowered/Sponge/blob/d612b083534b45a48b79022551f1eab326d67e75/src/main/java/org/spongepowered/mod/mixin/core/entity/MixinEntity.java#L120) needs to be changed to:
````java
entityplayermp1.setHealth(entityplayermp1.getHealth());
            
for(Object effect : entityplayermp1.getActivePotionEffects()) {
    entityplayermp1.playerNetServerHandler.sendPacket(new S1DPacketEntityEffect(entityplayermp1.getEntityId(), (PotionEffect) effect));
}

net.minecraftforge.fml.common.FMLCommonHandler.instance().firePlayerChangedDimensionEvent(entityplayermp1, currentDim, targetDim);
````

I have tested this and it fixes the issue. Note that this is not an issue with vanilla as the bug does not occur when using a nether or end portal.

**Comment by Zidane** [comment]
@verbeto 

Could you issue a PR for this?

**Comment by verbeto** [comment]
@Zidane Yup.

**Comment by ST-DDT** [comment]
Just for the reference:
https://github.com/SpongePowered/Sponge/pull/302
