### ISSUE TITLE
Implementation of the PlayerInteractEntityEvent

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#286]
According to [this](https://github.com/SpongePowered/Sponge/issues/274) Event Progress Tracker and my Plugin, the **PlayerInteractEntityEvent** is not jet implemented.
_Deamon5550 said [here](https://github.com/SpongePowered/Sponge/issues/272): "Opening issues like these does help us prioritize which events we're implementing." So i thougt i'll open this issue, since this is the last missing event i need to finish my plugin and start my server :)_

For the sake of completeness:
_Sponge Build: 1.8-1371-2.1DEV-467
Forge Build: forge-1.8-11.14.1.1397
Client Type/Version (Forge/Vanilla and version) : Vanilla 1.8.6
Installed Plugins and/or Mods: Sponge, My Plugin, (and DynmapForge)
Java Version: 1.8.0_40
Operating System: Windows 7 64 bit_

**Comment by nikosgram13** [comment]
Can you re-open this issue in SpongeCommon as it's most relevant there. :smile: 

https://github.com/SpongePowered/SpongeCommon

**Comment by TBlueF** [comment]
I can.
