### ISSUE TITLE
Event filtering?

### ISSUE THREAD

**Issue by Xemiru** [SpongePowered/Sponge#288]
![log](http://i.imgur.com/hieWu3u.png)

So I was messing around with logging long time ago, and I remembered I couldn't really filter the events to get the generic type I really want (which is all events relating to game mechanics). I told the main class to listen to `GameEvent`, but it doesn't look like its returning game events; as depicted in the given photo it throws `CanUpdate`, `Unload`, `Save`, and somewhere before, `Load` (it spammed it but I let it go on to the point where it wasn't in history anymore).

Question now is, is this the intended behavior? If so, what's the better way to filter out these types of events? If not, well--there you go.

```java
// event code
    @Subscribe
    public void init(GameEvent event) {
        System.out.println(event.getClass().getSimpleName());
    }
```

**Comment by simon816** [comment]
Those are Forge events (entity related). Use `getClass().getName()` to see the entire FQN.
You could filter them by ignoring classes whose package is `net.minecraftforge`

**Comment by ryantheleach** [comment]
Wouldn't that result in filtering just about everything in sponge due to mixins?

**Comment by ST-DDT** [comment]
What kind of filtering do you want to achieve?
Events starting with `A`, events related to entities?
Note: The base event class is `Event` not `GameEvent`.
`GameEvent` is an event interface in the middle of nowhere. Almost everything extents it. And your listener will recieve all events that extend `GameEvent`.
Your `init()` method looks like it tries to listen to some game [`StateEvent`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/state/StateEvent.java) example [`InitializationEvent`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/state/InitializationEvent.java). There are other events (subclasses) for entities, blocks ... as well. So you might use that as well.
If you want to limit the shown events to those send by Sponge you have to check the stacktrace or check the package name. With the drawback that Sponge itself might call Forge's events.
@ryantheleach The `SpongeEventFactory` uses a different package.

**Comment by Xemiru** [comment]
@ST-DDT `init()` method name was because i just changed a method in test code to be an event handler; i didn't bother changing the name of the method

filtering for events that pertain purely to game mechanic-related events, e.g. whenever an entity actually moves and doesn't wait to be updated, when a block gets broken or placed, when a firework is set off or something, etc. essentially, all events that relate to something that can happen in the game and not the ones that relate to something happening internally, invisible to the player of the game (the player player, not the client player).

**Comment by Mumfrey** [comment]
@Xemiru [read this](http://meta.stackexchange.com/questions/66377/what-is-the-xy-problem) and then explain what your `X` problem is.

**Comment by Xemiru** [comment]
`X` -- I can't seem to find a real method to filter out events without getting all hacky by scanning package names (which can be implementation-specific) or something.

**Comment by Mumfrey** [comment]
But you still haven't *why you want do do this "filtering" in the first place*! That still seems like a `Y` problem, you haven't actually provided your `X`. *What are you trying to actually achieve?*

**Comment by Xemiru** [comment]
Final result I'm aiming for is an easy way to catch all events without being spammed by all the internals like the load and save events, or the update check events for the purpose of debugging. Using an event subtype doesn't work that well either, as when I tried to listen for `PlayerEvent`s, it still throws me those internal forge events.

**Comment by Mumfrey** [comment]
Are you being deliberately obtuse. **Why do you want to listen to all events?**

**Comment by Xemiru** [comment]
apologies if i'm slow to get at what you're poking at.

its all for the purpose of debugging and/or research.

**Comment by Mumfrey** [comment]
You're going to need to outline what you actually think is missing here, because that doesn't seem like a use-case that is in any way actually useful to have in the API/Implementation. It seems like you just want to log events "for the lulz" and are expecting there to be some simple mechanism in place to do the heavy lifting for you.

If you're writing some kind of research tool why would you not use the type of interface provided by something like Ethereal for instance, where the default is to display everything and you add your own "filters" interactively?

The kind of thing you're talking about just isn't useful outside the specific case you seem to be angling for, and even then it seems like you're going about things back-to-front.

**Comment by Xemiru** [comment]
yeah, it started to look that way the longer this went on.
i'll close the issue, then; seems like i just made this off of laziness.
