### ISSUE TITLE
Can't get player's inventory

### ISSUE THREAD

**Issue by Try4W** [SpongePowered/Sponge#291]
Hello.

I run sponge server from this repo and try to test my little plugin, there is command executor code:
    
    @Override
    public CommandResult execute(CommandSource src, CommandContext args) throws CommandException {
        if(src instanceof Player) {
            Player playerSrc = (Player) src;
            ItemStack blazeRodStack = itemStackBuilder.itemType(ItemTypes.BLAZE_ROD).quantity(1).build();
            playerSrc.getInventory().query(blazeRodStack);

            playerSrc.sendMessage(Texts.of("Have a nice day, " + src.getName() + " :)"));
            return CommandResult.success();
        }
        src.sendMessage(Texts.of("You haven't inventory :C"));
        return CommandResult.empty();
    }

but when i execute the command(i run server from workspace in intellij idea) i got some errors:

http://pastebin.com/LpsJDTsP

It's a bug or i just do something wrong?

**Comment by simon816** [comment]
The inventory API is not implemented yet.
Note that if you see `AbstractMethodError` it usually means that method is not implemented in sponge.

**Comment by Try4W** [comment]
Sad. Thank you, take note.

**Comment by twizmwazin** [comment]
Is there a status on this implementation? I heard that it was @Mumfrey who would implement it, after writing the inventory API. I haven't heard anything since, and that was a couple months ago. This is one of the larger features preventing me from developing with the platform.

**Comment by Zidane** [comment]
Closing this as we have an issue in SpongeCommon for the Inventory impl.
