### ISSUE TITLE
Plugins are completely blocked from shading Apache libraries

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#296]
[This line](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/SpongeCoremod.java#L71) of `SpongeCoremod` prevents plugins from using any Apache library whatsoever. I'm not entirely sure what the reasoning behind this is, but surely it should be limited to one or more specific libraries rather than the enitre namespace.

**Comment by Mumfrey** [comment]
It can't be removed because that exclusion is added by fml on the client but not the server. If it's removed then things will break.

If you need to shade an apache library then rename the package.

**Comment by caseif** [comment]
[Escalated to Minecraft Forge.](https://github.com/MinecraftForge/MinecraftForge/issues/1957) I'd like to keep this issue open while the one on MF is pending.

**Comment by progwml6** [comment]
libraries should be renamed when shaded

**Comment by caseif** [comment]
That's missing the point. It's a bit ridiculous to block the *entire* namespace when in reality only select libraries would cause issues. Regardless, it's not in Sponge's hands currently.
