### ISSUE TITLE
Plugin doesn't receive any events when third party library is bundled into jar

### ISSUE THREAD

**Issue by gr4y** [SpongePowered/Sponge#297]
Hi there,

I can't find it in the docs and I haven't found an issue in here, so I am filing one here. I am rebuilding an sponge plugin with an external library. So I build a jarFile with the gradle plugin named shadowJar, which worked great with bukkit, but sponge doesn't like that as it seems. 

I subscribed to the PreInitializationEvent, but the StatusPlugin class doesn't receive anything. Whenever I remove the dependency and disable the shadowJar plugin the plugin will be loaded and all events are received.

As you can see in the log file the plugin is loaded, and the events are sent, but as you can see in the log file too, there is no trace of my custom log statements. You can look at the plugins code here: [http://github.com/bukkiteers/status](bukkiteers/status).

I am happy to receive anything that would lead me into the right direction. :smile:

**Comment by Mumfrey** [comment]
> As you can see in the log file

Can you please include the relevant log.

**Comment by gr4y** [comment]
Sorry, I forgot to paste the link to the gist. I couldn't paste it in here 
cause it was to large. Here it is: 
https://gist.github.com/gr4y/5860496116a17e5fc168

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by simon816** [comment]
You've imported the wrong `@Subscribe` annotation. See [StatusPlugin:7](https://github.com/bukkiteers/status/blob/86f9053e7da47462135f42488b2167dea0daf245/src/main/java/de/gr4yweb/sponge/StatusPlugin.java#L7)
> import com.google.common.eventbus.Subscribe;

It should be [`org.spongepowered.api.event.Subscribe`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/Subscribe.java)

**Comment by gr4y** [comment]
I just have a glowing desire to run head first into a brick wall. Thank you @modwizcode!

**Comment by modwizcode** [comment]
I just closed the issue, @simon816 is the one who found the problem, thank him.

**Comment by gr4y** [comment]
Thanks @simon816, a thousand times. I just added an checkstyle rule to prevent that error in the future. https://github.com/bukkiteers/status/commit/8129746926540b7fdc932fd6ee60b4f298684109
