### ISSUE TITLE
gradlew error

### ISSUE THREAD

**Issue by castlerush** [SpongePowered/Sponge#298]
Ok so when i open cmd in the folder, and type "gradlew" i get this error

C:\Users\7804364\Desktop\Sponge-master\Sponge-master>gradlew

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\7804364\Desktop\Sponge-master\Sponge-master\build.gradle' l
ine: 35

* What went wrong:
A problem occurred evaluating root project 'Sponge'.
> Could not read script 'C:\Users\7804364\Desktop\Sponge-master\Sponge-master\Sp
ongeCommon\gradle\implementation.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 31.088 secs

C:\Users\7804364\Desktop\Sponge-master\Sponge-master>

**Comment by twizmwazin** [comment]
You need to follow the build instructions int the README. 

`git clone --recursive https://github.com/SpongePowered/Sponge.git`  
`cd Sponge`  
`gradle setupDecompWorkspace --refresh-dependencies`  
`gradle build`
