### ISSUE TITLE
Leaf Decay crash

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/Sponge#299]
http://pastebin.ubuntu.com/11780195/

**Comment by modwizcode** [comment]
This is probably caused by leaf decay mixins being incorrect. I will verify.

**Comment by modwizcode** [comment]
@Zidane seems like it's world related which you have some experience with.

**Comment by Zidane** [comment]
@modwizcode "some" is an interesting statement (/me looks at unified world changes)

Stack trace is pretty clear on this, just need to implement getBlockSnapshot.

**Comment by simon816** [comment]
I'm on it
