### ISSUE TITLE
Can't respawn after dead

### ISSUE THREAD

**Issue by lanord** [SpongePowered/Sponge#301]
Here is the stacktrace : https://gist.github.com/lanord/40e12082c0514f350e03

I've tested by drowning, suffocation, mob attack and the /kill command. All the same results, no possible respawn. Need to delete player data file to get back.

This happen on single and multiplayer (dedicated server).

**Comment by Minecrell** [comment]
Most likely broken as of https://github.com/SpongePowered/SpongeCommon/commit/c9087dad5ce0cd3210087c100803ab877f6eb314#diff-570a8a6ae26d5d39025137a9141da47bL131 @simon816

**Comment by Zidane** [comment]
@simon816 

I warned you about this. Add those AT changes back or pull them down into Sponge-only. You really need to watch what you are removing next time.
