### ISSUE TITLE
Location in command argument's don't work

### ISSUE THREAD

**Issue by gamerforEA** [SpongePowered/Sponge#304]
Forge: 11.14.3.1486
Sponge: 1446-2.1DEV-508
Command: /set 1 1 1
Source code: http://pastebin.com/89cYKyys
Log: http://pastebin.com/xT2Sjnmg
java.lang.ClassCastException: net.minecraft.world.WorldServer cannot be cast to org.spongepowered.api.world.storage.WorldProperties

**Comment by simon816** [comment]
This is actually an issue in the API. The crash is happening at [GenericArguments:1103](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/command/args/GenericArguments.java#L1103)
It looks like the `LocationCommandElement` assumes the world object is a `WorldProperties` instance.
I'm pretty sure it's [this line](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/command/args/GenericArguments.java#L1084) that's causing the problem, it should be `getWorld().getProperties();` @zml2008 confirm?
