### ISSUE TITLE
negative potion amplifiers not allowed

### ISSUE THREAD

**Issue by jaymsDooku** [SpongePowered/Sponge#3046]
There are some potion effects that accept a negative amplifier such as the Jump Boost Potion Effect, but I'm unable to build a Potion Effect with a negative amplifier because the builder does not accept negative amplifier values.

**Comment by ImMorpheus** [comment]
Moved to common, this is an issue with the implementation
 https://github.com/SpongePowered/SpongeCommon/blob/f9d49c6572d194dfba32c32b912b906080771fca/src/main/java/org/spongepowered/common/effect/potion/SpongePotionBuilder.java#L107
