### ISSUE TITLE
FoodData error.

### ISSUE THREAD

**Issue by mcmacker4** [SpongePowered/Sponge#306]
So I was creating a couple of commands that go kind of together. One is for healing people and the other one is for feeding people.
These two commands have the exact same code except one uses HealthData and the other one uses FoodData instead.
The healing command works fine. The feeding one does feed and does it correctly but it gives an error.

Code:
Healing command: http://pastebin.com/dnSu11q7
Feeding command: http://pastebin.com/TPND3GLb
Stacktrace returned by /feed: http://pastebin.com/9JmKEUGU

**Comment by simon816** [comment]
I see what's happening, the method `setFoodSaturationLevel` is client side only,
```java
    @SideOnly(Side.CLIENT)
    public void setFoodSaturationLevel(float foodSaturationLevelIn)
```
