### ISSUE TITLE
forgeBin 1446 403 access denied error

### ISSUE THREAD

**Issue by FamleeX** [SpongePowered/Sponge#307]
Every time I go to compile Sponge, I always end up getting this error. Is there anyway to fix this?

**Comment by Zidane** [comment]
Can we get a log please?

**Comment by kenzierocks** [comment]
Sounds like you forgot `setupDevWorkspace` or `setupDecompWorkspace`.

**Comment by FamleeX** [comment]
That fixed it, thanks!
