### ISSUE TITLE
Entity Activation Broken

### ISSUE THREAD

**Issue by kristi71111** [SpongePowered/Sponge#3081]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.2.4-RC4058
- Forge version: 14.23.5.2854
- SpongeVanilla version: N/A
- Java version: 1.8.0_241-b07
- Operating System: Windows 10

- Plugins/Mods:
**Mods (7):** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, SpongeForge
**Plugins (4):** Minecraft, MinecraftCoder Pack, SpongeAPI, Sponge

**Issue Description**
Upon updating from SpongeForge 1.12.2-2838-7.2.2-RC4024 to latest or any version in between entity activation ranges are not being respected. As seen in the video below. Upon further investigation and self compilation with commit <https://github.com/SpongePowered/SpongeCommon/commit/23642ed024879f3a65fab3a4d26b1b3b86e32ec8> being reverted the issue is resolved.
**Video:** <https://youtu.be/PiorCfrhkts>
**Sponge config:** <https://pastebin.com/j8dNJcBh>

**Comment by dualspiral** [comment]
@ImMorpheus can you look at the issue here please, see why your optimisation failed for them.
@kristi71111 I notice you've also wanted to revert the latest commit, can you open an issue explaining why?
