### ISSUE TITLE
AbstractMethodError on NotifyNeighborEvent

### ISSUE THREAD

**Issue by tyhdefu** [SpongePowered/Sponge#3097]
**I am currently running**
- SpongeForge version: Not tested
- SpongeVanilla version: spongevanilla-1.12.2-7.2.3
- Java version: 8
- Operating System: Windows 10

- Plugins/Mods:
My custom test plugin for this bug.
**Issue Description**
NotifyNeighbor.filterDirections doesn't seem to be implemented.
The following code:
```java
@Listener
public void notifyNeighbor(NotifyNeighborBlockEvent e) {
    e.filterDirections(dir -> true);
}
```
causes an AbstractMethodError. Also, the javadocs say that .getNeighbors is immutable, but i am able to work around
.filterDirections not being implemented by removing the undesired updates from the map.

**Comment by thibaulthenry** [comment]
Still occurs in API-8
However, this event needs a complete rewrite according to gabizou

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/Sponge/pull/3314
