### ISSUE TITLE
Issue CollideEntityEvent

### ISSUE THREAD

**Issue by Looter-source** [SpongePowered/Sponge#3112]
**I am currently running**

- SpongeForge version:  SpongeForge 1.12.2-2838-7.2.3 

- Plugins/Mods: griefdefender-sponge-1.5.0-DEV6 (5).jar
https://gyazo.com/3ed3d54e2b04ff05ec5268951c5124da
https://gyazo.com/b5a7094d04e3aa9c9d8993a66d3896c9

**Issue Description from Bloodshot Side**
CollideEntityEvent is no longer passing the item frame as the cause. All it passes in latest is player.
 it passes  cause = Cause[Context=Context[], Stack={EntityPlayerMP['KratosKnox2'/332, l='world', x=-167.91, y=70.19, z=250.30]}]
 which is completely wrong because the bike is not colliding with the player, it is colliding with the item frame

**What I am working on**
So I want to solve this problem, where people can ride a bicycle to against the item frame and destroy someone's painting. 

So I made a test server, where i only put the latest griefdefender / latest luckperms / latest recommended sponge in it.

But I still have this problem, because it's a issue by spongeforge, and I really hope it can be resolved.

**Here's a video of how you perform the issue**
https://gyazo.com/8f5d7cfd67065873194dcb7db17333b5

**Comment by dualspiral** [comment]
Okay, blood tested it, it's 4024.

@JBYoshi, the rewrite of the collisions module broke the cause - can you take a look please? The direct cause should be the item being collided with.

From a chat I had with @bloodmc:

> Someone broke CollideEntityEvent in a past update...
> ItemFrame protection is now broken
> When a pixelmon bike collides with frame I used to receive the cause
> `Cause[Context=Context[], Stack={EntityItemFrame['entity.ItemFrame.name'/414, l='world', x=-58.03, y=71.50, z=219.50]}]`
> Now I get
> `Cause[Context=Context[], Stack={EntityPlayerMP['KratosKnox2'/332, l='world', x=-167.91, y=70.19, z=250.30]}]`
> The bike collides with the itemframe not the player

Ideally, in this case, the cause should contain the following (from root down):

* ItemFrame
* Pixelmon bike (this is what collided with the frame)
* Player

I would settle for previous behaviour right now though.

It wasn't clear from the diff for the rewrite where this might have changed, unfortunately, hopefully it won't be too difficult to find.

**Comment by JBYoshi** [comment]
I've traced this down to the root call - it seems I did miss a case when the collision events should be active (`World.getCollisionBoxes()`). Will fix as soon as I figure out how best to handle the mixin code.
