### ISSUE TITLE
Not able to connect to sponge server behind BungeeCord proxy

### ISSUE THREAD

**Issue by ghacproductions** [SpongePowered/Sponge#315]
It's not able to connect to a sponge server which is behind a BungeeCord proxy. The sponge server does not give out any information of a try of connection to the server.

**Comment by JBYoshi** [comment]
The devs would probably need more information to figure this out.
- Any error messages, including the disconnect message
- The Forge, Sponge, and BungeeCord versions

**Comment by progwml6** [comment]
please move this to common

**Comment by ghacproductions** [comment]
There are no error-messages, the player simply does not connect to the server. The bungeecord-proxy says, that the player connected but also shows that he disconnected in the next message. There are no logs at the sponge server.

Sponge-Version: sponge-1.8-1487-2.1DEV-523
BungeeCord-Version: Build 1​07​6

**Comment by progwml6** [comment]
this issue occurs in both implementations please re-open it in the common repo
