### ISSUE TITLE
Cannot apply entity archetypes (from schematic)

### ISSUE THREAD

**Issue by SimonCROS** [SpongePowered/Sponge#3158]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.3.1-RC4077
- Java version: 1.8.0_241
- Operating System: Windows 10

- Plugins/Mods: EconomyLite, LuckPerms, Nucleus

**Issue Description**
Hello, when I try to generate an entity from a schema, I get exactly the same error as #1959

```
[Server thread/ERROR] [Sponge]: Error occurred while executing command 'myplugin' for source EntityPlayerMP['SeaMoon69'/16, l='world', x=-301,12, y=114,00, z=302,13]: Could not retrieve value for key 'sponge:spawn_type'
java.util.NoSuchElementException: Could not retrieve value for key 'sponge:spawn_type'
        at org.spongepowered.api.event.cause.EventContext.require(EventContext.java:116) ~[EventContext.class:1.12.2-2838-7.3.1-RC4077]
        at org.spongepowered.common.entity.SpongeEntityArchetype.apply(SpongeEntityArchetype.java:151) ~[SpongeEntityArchetype.class:1.12.2-2838-7.3.1-RC4077]
```
with this code

```java
for (Entry<Vector3i, TileEntityArchetype> tileEntByPos : schematic.getTileEntityArchetypes().entrySet()) {
	Vector3i position = tileEntByPos.getKey();
	TileEntityArchetype tileEntity = tileEntByPos.getValue();

	tileEntity.apply(player.getLocation().add(rotateY(position, rotation)));
}
for (Entry<Vector3d, EntityArchetype> entByPos : schematic.getEntitiesByPosition().entries()) {
	Vector3d position = entByPos.getKey();
	EntityArchetype entityArc = entByPos.getValue();

here -> entityArc.apply(player.getLocation().add(rotateY(position, rotation)));
}
```
but in my case using snapshot then using the restore method also throws an error
```
[Sponge]: Error occurred while executing command 'myplugin' for source EntityPlayerMP['SeaMoon69'/16, l='world', x=-301,45, y=114,00, z=302,33]: null
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[minecraft_server.1.12.2.jar:?]
        at org.spongepowered.common.entity.SpongeEntitySnapshotBuilder.build(SpongeEntitySnapshotBuilder.java:256) ~[SpongeEntitySnapshotBuilder.class:1.12.2-2838-7.3.1-RC4077]
        at org.spongepowered.common.entity.SpongeEntityArchetype.toSnapshot(SpongeEntityArchetype.java:183) ~[SpongeEntityArchetype.class:1.12.2-2838-7.3.1-RC4077]
        at org.spongepowered.common.entity.SpongeEntityArchetype.toSnapshot(SpongeEntityArchetype.java:65) ~[SpongeEntityArchetype.class:1.12.2-2838-7.3.1-RC4077]
```

**Comment by gabizou** [comment]
You shouldn't have to apply all the archetypes yourself, just apply the schematic to the location, as the [copy pasta plugin demonstrates](https://github.com/SpongePowered/SpongeCommon/blob/d8f9d7dcc1a2048d095b82ae31c5669eca52f042/testplugins/src/main/java/org/spongepowered/test/CopyPasta.java#L129-L136). But otherwise, your code you're pasting is not the same as the stack trace, there's nowhere in [SpongeEntityArchetype that calls toSnapshot](https://github.com/SpongePowered/SpongeCommon/blob/d8f9d7dcc1a2048d095b82ae31c5669eca52f042/src/main/java/org/spongepowered/common/entity/SpongeEntityArchetype.java#L110-L170), which your stack trace suggests is being called.

**Comment by SimonCROS** [comment]
The second error was obtained using the second line of code provided on issue #1959, where the author says using toSnapshot works.
```java
Optional<Entity> entity2 = entity1.createArchetype().toSnapshot(entity1.getLocation()).restore();
```

Also, following a conversation about the sponge discord, you answered me after ask how to rotate schematics
@SeaMoon15 rotating isn’t supported yet. We don’t have a way in the api to rotate blockstates.
So I cannot use schematic.apply as you advise me on your answer to the problem.

If you have another way to rotate schematic than do it manually, can you tell me how ?

**Comment by gabizou** [comment]
>[Server thread/ERROR] [Sponge]: Error occurred while executing command 'myplugin' for source EntityPlayerMP['SeaMoon69'/16, l='world', x=-301,12, y=114,00, z=302,13]: Could not retrieve value for key 'sponge:spawn_type'
java.util.NoSuchElementException: Could not retrieve value for key 'sponge:spawn_type'
     

This specifically says that you need to provide the EventContext (in a stack frame) for the SpawnType for the associated entity spawned).

Wrap with a try with resources like so:
```
try (StackFrame frame = Sponge.getCauseStackManager().pushStackFrame()) {
  frame.addContext(EventContextKeys.SPAWN_TYPE, SpawnTypes.PLUGIN);
  // do things with your archetypes being applied
}
```

**Comment by SimonCROS** [comment]
Thanks, it works !
