### ISSUE TITLE
player .setRotation(vector3drotation) not working

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#316]
Its hard to imagine Im using it incorrectly. Trying to set the rotation of a player with this method to a Vector3d object of (0,0,0) or (90,0,0) or (180,0,0) or (270,0,0).  all doubles.

player.setRotation(newRotation);  in my code does nothing

Is the rotation function not implimented yet (rendering various teleporting systems incomplete)
or
must a set-rotation be activated somehow afterwards, or in a delayed task, or similar?

Forge 1487/Dev 523

**Comment by kenzierocks** [comment]
It should be implemented (https://github.com/SpongePowered/SpongeCommon/blob/5e7dbbe55a5a02b9acf6997c27c0555d8e1fa35d/src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java#L360), this might be Sponge specific. Does it also happen on SpongeVanilla?

**Comment by ST-DDT** [comment]
Have you tried getting the rotation imideatly after setting it?
That way we can check whethwr the rotation is set all or if just the client isnt updated.
Are angles measured in degree in sponge?

**Comment by theboomer** [comment]
I added a getRotation and dumped the value immediately after setting it, and ... it is actually set to the rotation that I set it at.
The rotation yaw are angles gotten by sponge are from -359.999.. to +359.999 and pitch angles are -90 to 90 degrees (straight down to straight up, as they should be)
Trying to reproduce what angle it will be is a bit tricky, but it seems that if you are standing in one place and turn left a full circle the angles will be the negatives, and if right a full circle then some, they will be positives, and what they are at all other times is a flip of the coin ..  But it still becomes (gottenangle + 360) mod 360  to get a 0 to 359.999 usable...

**Comment by theboomer** [comment]
Nope, sorry guys... perhaps instructions are oversimplified for folks familiar with git and gradle and such, but I am unable to follow the instructions correctly in order to clone the vanilla and build the server jar.
I am not able to indicate what the behavior is in vanilla thusly.

**Comment by theboomer** [comment]
Also, i dont understand how mixins work, what the code nomenclatures mean and all that, but..
1) Why is the setrotation method the only one with "shadow$" in it?  What makes that unique?  Nothing else has it.  The equivalent setlocation has a much more involved code 
other setthings simply set this.thing=value
Why shadow$ for setRotation and no where else, and this is the part that doesn't seem to be working right...

**Comment by kenzierocks** [comment]
Because there's a different `setRotation` we provide that doesn't match the built-in one, so we reference the built-in as `shadow$setRotation` so it doesn't conflict. It's very unlikely to be the problem.

**Comment by DDoS** [comment]
Looking at the implementation, this doesn't force an update on the client side. If you disconnect and reconnect though the rotation should be changed. Implementation needs to be fixed.

**Comment by modwizcode** [comment]
Yeah I actually have the correct code to do this in my Stargate plugin, I just need to find a clean way to integrate it.

**Comment by DDoS** [comment]
I [added code](https://github.com/SpongePowered/SpongeCommon/commit/eb757d650e697d2fa3d01ff2605bbc3572181bd0) to update player rotation in `Entity.setRotation()`. This works for players.

When it comes to other entities, the latest entity information is sent to the players periodically. If the AI decides to rotate and entity between the setRotation call and the update, the setRotation appears to be lost. This isn't incorrect, but I'm not sure if it is desired.

**Comment by JBYoshi** [comment]
@DDoS Close?

**Comment by DDoS** [comment]
Not sure if this is solved.

**Comment by DDoS** [comment]
I'll close this as I consider it solved.
