### ISSUE TITLE
Shulker Mob Crash

### ISSUE THREAD

**Issue by KJImmy** [SpongePowered/Sponge#3179]
Any time I make contact with a shulker mob the game crashes. I've narrowed it down to the SpongeForge mod and tried making contact with every other mob but it only happens with shulkers. It also doesn't happen with shulker boxes, only the mob. It does seem like I can still hit the mob if I maintain distance, but the crash happens anytime I walk into it. When this happens I get the following error message:

The game crashed whilst ticking entity
Error: java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=Client thread, priority=5, group=java.lang.ThreadGroup[name=main,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
Exit Code: -1

**Comment by dualspiral** [comment]
I know you put it on the SpongeAPI repo (which was the wrong place, don't worry, I transferred it) so you missed the issue template: but we'll need the following information.

- SpongeForge version: 
- Java version: 
- Operating System:
- Plugins/Mods:

**Comment by KJImmy** [comment]
Oops, sorry thank you for correcting that.

SpongeForge version - I initially tried it with 1.12.2-2838-7.3.0, I did try 1.12.2-2838-7.3.0-RC4079 as well and the problem still happened.
Java version - 1.12.2
OS - Windows 10
Mods - I initially found the issue while setting up Pixelmon Reforged 1.12.2, but I was able to narrow it down to SpongeForge by adding in my mods one at a time, and the issue still occurred when I did it with only SpongeForge and Forge 1.12.2

**Comment by ImMorpheus** [comment]
Please follow the issue template, it's actually rather important if you want to get dev attention to fix your issue.

Edit this issue with the required details / template, and I'll reopen and hide this comment.

Specifically: the log is mising.
