### ISSUE TITLE
Human Events vs Player Events

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/Sponge#318]
At the moment, any Forge event involving an `EntityPlayer` gets passed to plugins as a `Player___Event`. However, `EntityPlayer` maps to `Human`, not `Player`. It would be nice if the events that involve a `Human` but not a `Player` would map to `Human___Event`, while events that involve an actual `Player` would map to `Player___Event`.

**Comment by simon816** [comment]
`EntityPlayer` is no longer a `Human`. `Human` is now implemented as an `EntityCreature`.

I realized the issue of forge player events some time ago, where the player object in the forge event may not be a player in sponge. For example `FakePlayer` should not fire `PlayerEvent`s, but instead it should fire the more generic events.

In my [`feature/fake-player`](https://github.com/SpongePowered/Sponge/compare/feature/fake-player) branch I tackle the problem with `IMixinEvent.getSpongeEquivalent()`
@SpongePowered/developers thoughts on my idea on that branch?

**Comment by JBYoshi** [comment]
> `EntityPlayer` is no longer a `Human`. `Human` is now implemented as an `EntityCreature`.

I meant the stuff for `FakePlayer`. Maybe it could have a configurable `Player` as a source. For example, if player X clicks a sign, and a plugin handles that event to make the player break a block, `event.getEntity()` could return player X.

**Comment by simon816** [comment]
@gabizou is working on event causes in SpongePowered/SpongeAPI#712, maybe something like that could be possible with the new cause system.

**Comment by Zidane** [comment]
This issue has changed a bit since new events system

**Comment by JBYoshi** [comment]
Sounds good.
