### ISSUE TITLE
Index out of range error for commands with default parameter and child command (API8)

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/Sponge#3186]
Dear @dualspiral, I broke your commands using a command with a defaulted parameter and a child command.

### Command usage ###
`/testoptionaldefaultwithsubcommand`
#### Expected: ####
Executor gets run using the "default" value
#### Actual: ####
StringIndexOutOfBoundsException :(

### Code and Full Error: ###
https://gist.github.com/Faithcaio/025f0c6397c3abb7d742e96b0a9dc5d7
Note that if the parameter is instead optional (and NOT defaulted) it works as expected.

**Comment by Faithcaio** [comment]
`SpongeCommandDispatcher#shouldContinueTraversing()` returns true because defaulted parameter `doesNotRead` causing the reader to skip past the end of the string.
Because a literal (the sub-command) is present it tries to match literals causing it to read the String past its end.

I think the solution would be to ignore literals when the reader cannot read anymore and just return SpongeArgumentCommandNode with `doesNotRead` parsers.

Replace
https://github.com/SpongePowered/SpongeCommon/blob/0f59cbbaa8a5deb625d714ff7ba53989e07e5ad9/src/main/java/org/spongepowered/common/command/brigadier/dispatcher/SpongeCommandDispatcher.java#L236
with
```
            if (originalReader.canRead()) {
                nodes = node.getRelevantNodes(originalReader);
            } else { // Reader cannot read anymore so ONLY nodes with parsers that do not read can be processed
                nodes = node.getChildren().stream().filter(n -> n instanceof SpongeArgumentCommandNode && ((SpongeArgumentCommandNode) n).getParser().doesNotRead()).collect(Collectors.toList());
            }
```

**Comment by dualspiral** [comment]
Thanks for looking into this. I just went through it with your notes and I think you're right - that's the solution. I'll add it now, thank you.
