### ISSUE TITLE
Incorrect AttributeOperations supplier IDs

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/Sponge#3202]
The static fields in `AttributeOperations` are unusable because they do not line up with the actually registered `ResourceKey`s.

Actually registered, versus field supplier id:
- `addition` > `add_number`
- `multiply_base` > `add_percentage`
- `multiply_total` > `multiply_percentage`

Looks like we should manually specify the supplier ID mappings, because IMO the mojang names aren't as good.

**Comment by ItsDoot** [comment]
There appears to be a similar issue with being able to use `AttributeTypes`, which also throws an UnknownTypeException when trying to use the static fields.

**Comment by kashike** [comment]
This was resolved.
