### ISSUE TITLE
Storing a single CatalogType with Custom Data fails

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/Sponge#3207]
There seems to be an issue with storing a `CatalogType` with custom data (that is, `Key<Value<MyCatalogType>>`).

Here is a test plugin as well as a full log of the error that occurs: https://gist.github.com/ItsDoot/a69919b90b4dce43138e1bd20aa1e72d

I have a hunch that `NbtTranslator`'s `getBaseFromObject` just needs to be adjusted to take them into account, like how `DataView`'s `set` does.

https://github.com/SpongePowered/SpongeCommon/blob/52e6f899e9b6fdbdc0b005d2b59d36bdeafef7f5/src/main/java/org/spongepowered/common/data/persistence/NbtTranslator.java#L102

https://github.com/SpongePowered/SpongeCommon/blob/52e6f899e9b6fdbdc0b005d2b59d36bdeafef7f5/src/main/java/org/spongepowered/common/data/MemoryDataView.java#L268

EDIT: For QoL it would also help to verify a type is serializable further up the call chain, and throw a more descriptive exception.

**Comment by Faithcaio** [comment]
It actually goes through exactly that `MemoryDataView` Code. But `CatalogType#getKey` is not a String.
