### ISSUE TITLE
Sponge Coremod incompatible with Optifine.

### ISSUE THREAD

**Issue by jadunker** [SpongePowered/Sponge#321]
When forge is launched with both optifine and sponge in the mods folder. Minecraft is slow to start-up. Minecraft will fail to start the game and take the user back to the main menu. Attempting to do so again causes the game to cease responding. Forge launched with each mod individually works fine.
Optifine's URL: http://optifine.net/home

**Comment by gabizou** [comment]
Until Optifine starts being compatible with Minecraft, we can't provide any support for it.

**Comment by jadunker** [comment]
Optifine is compatible with minecraft. The crash from the two mods being active at once.

**Comment by JBYoshi** [comment]
> Optifine is compatible with minecraft. The crash from the two mods being active at once.

Could you post the crash report?

**Comment by Zidane** [comment]
@jadunker 

What @gabizou meant (but poorly articulated) was that Optifine tends to be incompatible with anything and everything. Optifine won't support any other mod, its up to other mod devs to be compatible with it which is really sad. No dev responsibility at all.

Anyhow, we need your crash reports and logs so that we can see if we can fix the incompatibility.

**Comment by mcsnetworks** [comment]
Optifine's codebase is a compiled obfuscated mess in my opinion.  Its developer may be good at optimizing the renderer within Minecraft but he's the worst community offender for providing support and compatibility to other mods.  The fact that after years in development it is still closed source makes making other mods compatible even more difficult.

**Comment by jadunker** [comment]
It does not crash per say. It fails to start the game then freezes if you
try again.

**Comment by progwml6** [comment]
Unless there is an error in your logs there is nothing we can do

**Comment by heni123321** [comment]
I have tried to run Sponge and optifine and i'm getting a strange log https://dl.dropboxusercontent.com/u/98665796/log.txt

**Comment by JBYoshi** [comment]
From @heni123321's log, the error near the top of the log suggests that Optifine is initializing `net.minecraftforge.common.DimensionManager` *before Forge starts loading mods.* `org.spongepowered.mod.mixin.core.forge.world.MixinDimensionManager` tries to get the `Sponge` object, but since Sponge isn't initialized yet, it fails.

To me, this seems like an almost-crash - it's an exception that makes the game unusable; it just doesn't halt the game.

**Comment by simon816** [comment]
I can see what optifine is doing here, after opening it in jd-gui.
Basically there is a class, `Reflector` that stores many references to classes and fields when the class is first initialized. One of those is `DimensionManager`. It's wrong that optifine is force-loading about 20 classes so early in the game (literally a few method calls away from `main(String[])`).
Sponge can defend against this however, by creating the SpongeGame instance as soon as the sponge coremod is constructed. @SpongePowered/developers should we allow SpongeGame to be constructed this early or shall we moan at optifine? :P

**Comment by progwml6** [comment]
@simon816 as far as i am concerned any optifine bugs are optifines problem to fix.

**Comment by gabizou** [comment]
> @SpongePowered/developers should we allow SpongeGame to be constructed this early or shall we moan at optifine? :P

It's Optifine's fault for doing the classloading so early before things are properly started. They change the startup chain of Minecraft. We aren't going to come in and fix it for them.

**Comment by JBYoshi** [comment]
> should we moan at optifine? :P

> [Optifine's] developer... he's the worst community offender for providing support and compatibility to other mods.

So what should we do?

**Comment by Tzky** [comment]
I tried running Forge+Optifine+Sponge on the clientside and failed too. Forge+Optifine works, Forge+Sponge obviously too. Just not all three together. I can confirm that DimensionManager error mentioned above, happend for me too.

As already said: It's probably Optifines fault as it tends to break everything (and as been for a long time now). :/
