### ISSUE TITLE
IllegalStateException: Optional.get() cannot be called on an absent value [Client]

### ISSUE THREAD

**Issue by Cactose** [SpongePowered/Sponge#322]
Description: Exception in server tick loop

````
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:47)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:310)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:56)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:126)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)
````

Occurs with newest Forge and Sponge versions, as well as on older Forge versions.
No plugins are loaded. Seems to only occur with worlds generated using the 1.9 snapshots.

Forge version: forge-1.8-11.14.3.1502 & forge-1.8-11.14.3.1499
Sponge version: sponge-1.8-1499-2.1DEV-544

**Comment by simon816** [comment]
That's an old Sponge build you've referenced there
try again with `1.8-1499-2.1DEV-544` and with forge build 1499

**Comment by Cactose** [comment]
Oh, whoops! That was the Sponge build I was using. I copied and pasted that from my last bug report and forgot to change it. I need to pay more attention, haha.

It still does it with 1.8-1499-2.1DEV-544 and forge build 1499.

**Comment by simon816** [comment]
Does this happen on newly generated worlds or only on existing worlds?

The only thing I can think of is that that the world folder was renamed, so the `level.dat` file still stores the original name

**Comment by Cactose** [comment]
It doesn't happen on newly generated worlds. Even after the new world is saved and reloaded on a new instance of Minecraft, it continues to work.

**Comment by simon816** [comment]
OK I think what I stated above is true. Sponge registers the `WorldInfo` (the data in `level.dat`) with `SpongeGameRegistry`. There is an entry in the data, LevelName, that represents the name of the world, this is what Sponge registers.
When a single player world is loaded, it looks up the name from the world folder name, not the LevelName, so if the folder has been renamed, it doesn't match. @bloodmc / @Zidane does that seem like a plausible reason for the absence of the overworld `WorldProperties`?

**Comment by Cactose** [comment]
After further testing, this seems to only occur with worlds generated using 1.9 snapshots.

**Comment by gabizou** [comment]
> 1.9 snapshots.

There's your problem. The snapshots are generating worlds with data that is incompatible with 1.8 entirely. Mojang already states this in the release notes of the snapshots.

**Comment by bloodmc** [comment]
@Cactose reopen ticket if this occurs on 1.8.
