### ISSUE TITLE
String choices parameter with spaces inside

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3223]
```
SpongeVanilla version: 1.15.2-8.0.0
Java version: 8
Operating System: Windows 10
Plugins: Just a plugin to test commands in API-8
```

Hello, 

I wanted test the choices Parameter in api-8 to check if we can have string choices with spaces inside.

So I did this thing: 

`Parameter.choices("Text with spaces", "Multiple choices").setKey("test").build()` 

But it is not possible to parse this because then we have parsing error in Minecraft: 

![test1](https://user-images.githubusercontent.com/25883318/101262585-37e32600-3740-11eb-8f55-894937be8793.png)

So I tried: 

`Parameter.choices("\"Text with spaces\"", "\"Multiple choices\"").setKey("test").build()` 

To escape the quotes, then we have in Minecraft: 

![test2](https://user-images.githubusercontent.com/25883318/101262588-3e719d80-3740-11eb-9331-0733bbd1e308.png)

In fact, it seems like the parser considers `"Text with spaces"` (with the quotes) as the key to retrieve, which is logic. But the command is filling `Text with spaces` (without the quotes) because this is the value of the "Text with spaces" argument.

I know it's a minor issue compared to the current workload, so I don't expect to have priority regards on this, but I already know that it will be a problem when I'll migrate my plugin to API-8.

Thanks for reading this issue.

**Comment by dualspiral** [comment]
Bleh. I'll fix this when I have a moment. Just so I don't have to think too much later, if you have 

```
Parameter.choices("Text with spaces", "Multiple choices").setKey("test").build()
```

and you provide the parameter `"Multiple choices"` (ignore the red, run it anyway), does it succeed and return `Multiple choices`?

**Comment by thibaulthenry** [comment]
Well, I think I misled you with my screenshots.

With: 
`Parameter.choices("Text with spaces", "Multiple choices").setKey("test").build()`
and the command:
`/cm Multiple choices`
I have the error:
![test3](https://user-images.githubusercontent.com/25883318/101266208-150b3e80-374d-11eb-91ec-d0a64ea53c77.png)

With: 
`Parameter.choices("\"Text with spaces\"", "\"Multiple choices\"").setKey("test").build()`
and the command:
`/cm "Multiple choices"`
I have the error:
![test2](https://user-images.githubusercontent.com/25883318/101266238-43891980-374d-11eb-9759-8009d7a5e869.png)


What I think you wanted me to try: (I don't have any red highlighting)
`Parameter.choices("Text with spaces", "Multiple choices").setKey("test").build()`
and the command:
`/cm "Multiple choices"`

It works, but this is not the filled value when pressing tab. Actually we just need to wrap the choice with quotes if this one contains spaces.


Same thing with: (when I tried to get around the parameter)
`Parameter.choices("\"Text with spaces\"", "\"Multiple choices\"").setKey("test").build()`
and the command:
`/cm "\"Multiple choices\""`

It works, so we also have to escape quotes in choices if we add an additional quotes wrapping like I proposed upon above

**Comment by dualspiral** [comment]
> What I think you wanted me to try: (I don't have any red highlighting)
> `Parameter.choices("Text with spaces", "Multiple choices").setKey("test").build()`
> and the command:
> `/cm "Multiple choices"`
> 
> It works, but this is not the filled value when pressing tab.

That's all I wanted to know, I knew what was going on.
