### ISSUE TITLE
Anvil UIs do not work correctly if another plugin listens to UpdateAnvilEvent and edits the Results

### ISSUE THREAD

**Issue by 02Miki** [SpongePowered/Sponge#3227]
**I am currently running**

- SpongeForge version: 2838-7.2.2 (not latest due to other plugins not being updated yet)
- Java version: I'm not sure honestly
- Operating System: Linux

- Plugins: Nucleus, Luckperms, CustomRecipes (the plugin that is actually editing the anvil "recipes")
- Mods: Pixelmon

My plugin is currently listening to the UpdateAnvilEvent and allowing me to introduce things like silk touch 2 and 3. If I use a normal anvil block it works alright, no issues at all, but if I use nucleus' /anvil (and I assume any other anvil UI) it breaks. Players trying to enchant items with "vanilla" enchants won't be able to, and whenever they try, it removes the levels on the client side, but as soon as they relog/get more xp, they get the levels back

I know the code is far from ideal, but it was a quick test; here's the code I use to edit the anvil logic https://gist.github.com/02Miki/a795e5c07f96491e2d386822202c609e

**Comment by 02Miki** [comment]
https://cdn.discordapp.com/attachments/754384155575582740/785191065438650368/unknown.png here's a screenshot of the error it fires

**Comment by hutchy50** [comment]
Not sure if it's a proper fix, but making it so the event doesn't fire unless there is and item in the first anvil slot seems to fix it

**Comment by hutchy50** [comment]
As an additional update to this issue, the bug in the event actually causes a dupe glitch when placing items in and out of the second slot of a normal anvil. 
Happens whenever the event errors https://pastebin.com/Gndpi7Sz causing the item do dupe or disappear
