### ISSUE TITLE
Command parsing fails with parametrized parent command

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3234]
```
SpongeVanilla version: 1.15.2-8.0.0
Java version: 8
Operating System: Windows 10
Plugins: WIP plugin for api-8
```

Hey,

In API-7, we had the possibility to add parameters to a parent command, and attach sub commands to this parent.
The commands was structured like that: 

`/parentCommand <parameter> childCommand <parameters of child command>`

In API-8, we still have this possibility but it fails to parse the command.

Testing case: 

Root command > Border command with optional world properties parameter > Center command 
`/cm border [<world-properties>] center <x> <z>`

Without optional argument from **border** command, working:
![command2](https://user-images.githubusercontent.com/25883318/102024061-dcdcaf00-3d8f-11eb-8604-df296f10097c.png)

With optional argument from **border** command, not working, I can't go further after the world properties parameter:
![command](https://user-images.githubusercontent.com/25883318/102024068-f3830600-3d8f-11eb-9d0a-89e693dc758d.png)

Thanks for reading this issue

**Comment by dualspiral** [comment]
> The commands was structured like that:

Show code explaining what you mean?

**Comment by thibaulthenry** [comment]
API 7:

```java
CommandSpec childCommandSpec = CommandSpec.builder()
                .arguments(GenericArguments.string(Text.of("childParameter")))
                .executor(new ChildCommand())
                .build();

CommandSpec parentCommandSpec = CommandSpec.builder()
                .arguments(GenericArguments.string(Text.of("parentParameter")))
                .child(childCommandSpec, "childCommand")
                .executor(new ParentCommand())
                .build();
```


API 8:

```java
Command.Parametrized childCommand = Command.builder()
                .parameter(Parameter.string().setKey("childParameter").build())
                .setExecutor(new ChildCommand())
                .build();

Command.Parametrized parentCommand = Command.builder()
                .parameter(Parameter.string().setKey("parentParameter").build())
                .child(childCommand, "childCommand")
                .setExecutor(new ParentCommand())
                .build();
```

**Comment by dualspiral** [comment]
In API 7 that doesn't do what you claim. `child` in both adds the command as a _top level_ subcommand, so what you suggest _doesn't_ do this:

```
/parentCommand <parameter> childCommand <parameters of child command>
```

but this:

```
/parentCommand <parameter>
/parentCommand childCommand <parameters of child command>
```

It's the same in API 8 - something I made sure I specified in the API 8 JDs:

https://github.com/SpongePowered/SpongeAPI/blob/66b8db9507c963dbec21df64128ef83112960c38/src/main/java/org/spongepowered/api/command/Command.java#L321-L329

Those JDs also tell you how to create a "in the middle" subcommand. The one thing that it doesn't say is that you'll probably want to use `Parameter.firstOf(...)` in that scenario, especially if you plan to have other subcommands, or even a no-subcommand path.

**Comment by thibaulthenry** [comment]
I wrote it badly yesterday. Must remove the executor in the api-7

```java
CommandSpec childCommandSpec = CommandSpec.builder()
                .arguments(GenericArguments.string(Text.of("childParameter")))
                .executor(new ChildCommand())
                .build();

CommandSpec parentCommandSpec = CommandSpec.builder()
                .arguments(GenericArguments.string(Text.of("parentParameter")))
                .child(childCommandSpec, "childCommand")
                .build();
```

I now remember I tricked to have an executor on parametrized parents AND have the childs.


But now we have setTerminal in API-8 so I directly added the executor on the parent. Didn't realize it would break my way to have parameter on parent.

**Comment by thibaulthenry** [comment]
Hey @dualspiral

So I tried to implement the way you adviced me with sub commands.

```
Command.Parameterized center = Command.builder()
        .parameter(CosmosParameters.POSITION_XZ)
        .setExecutor(new Center())
        .build();

Command.Parameterized border = Command.builder()
        .parameter(Parameter.worldProperties(false).setKey("world").optional().build())
        .child(center, "center")
        .setExecutor(new text())
        .setTerminal(true)
        .build();

Parameter.Subcommand borderParam = Parameter.subcommand(border, "border");

Command.Parameterized backup = Command.builder()
        .setExecutor(new text())
        .setTerminal(true)
        .build();

Command.Parameterized root = Command.builder()
        .setExecutor(new text())
        .child(backup, "backup")
        .parameter(borderParam)
        .setTerminal(true)
        .build();

event.register(Cosmos.pluginContainer, root, "cm");
```

What I should expect from this is 

`/cm border [<world>] center <x> <z>`
`/cm backup ...not implemented..`

However I got the same error than before

After filling the world parameter I can't go further with `center <x> <z>`

**Comment by dualspiral** [comment]
Becuase you're doing it wrong. Why are you making `border` a `Parameter.Subcommand` and not `center` - it's the other way around you want it, surely?

Read the child JDs again. It tells you that you should only use that for a _direct_ subcommand of a command.

**Comment by thibaulthenry** [comment]
What you suggest me worked perfectly for one sub command, but adding another one does not work.

```
Command.Parameterized center = Command.builder()
    .parameter(CosmosParameters.POSITION_XZ)
    .setExecutor(new Center())
    .build();

Command.Parameterized size = Command.builder()
    .parameter(Parameter.integerNumber().setKey("diameter").build())
    .setExecutor(new text())
    .build();

Command.Parameterized border = Command.builder()
    .parameter(Parameter.worldProperties(false).setKey("world").optional().build())
    .parameter(Parameter.subcommand(center, "center"))
    .parameter(Parameter.subcommand(size, "size"))
    .setExecutor(new text())
    .setTerminal(true)
    .build();

Command.Parameterized backup = Command.builder()
    .setExecutor(new text())
    .setTerminal(true)
    .build();

Command.Parameterized root = Command.builder()
    .setExecutor(new text())
    .child(backup, "backup")
    .child(border, "border")
    .setTerminal(true)
    .build();

event.register(Cosmos.pluginContainer, root, "cm");
```

Seems logical because parameters are designed to be in series ?
Actually I do not see how to resolve my problem because, as you said, a child can't be filled after a parameter, it is a direct subcommand of a command.
The fact is that I'm looking for some kind of parallel behavior that child represent, but after the world parameter.


My commands in API-7 for the border module: 


`/cm border [<world>] center <x> <z>`
`/cm border [<world>] size <x> <z>`
`/cm border [<world>] info`
`/cm border [<world>] warningdistance <distance>`
`/cm border [<world>] damageamount <value>`
..etc..


`[<world>]` was the argument on the border command
`center`, `size`, `info`,... were the childs of the border command

**Comment by dualspiral** [comment]
Yes, and I told you how to do it back in the comment that closed this issue:

> The one thing that it doesn't say is that you'll probably want to use Parameter.firstOf(...) in that scenario, especially if you plan to have other subcommands, or even a no-subcommand path.

**Comment by thibaulthenry** [comment]
I'm dumb.. 😖

**Comment by thibaulthenry** [comment]
Me, again.. This time not for stupid talk, I hope

Since I put a subcommand parameter on the border command, the **terminal** behavior does not work anymore.
As far as I understand,  Parameter.Subcommand should be treated as parameter.

So If I do not fill anything and enter  `/cm border`, it should work, as the JD tells: 

![terminal](https://user-images.githubusercontent.com/25883318/102388627-51069500-3fd2-11eb-9552-b2a1cbde67b0.png)

I got a parsing error instead

![border](https://user-images.githubusercontent.com/25883318/102389483-79db5a00-3fd3-11eb-8f4c-8fe68d81682f.png)

Is this a bug or intended ?
