### ISSUE TITLE
Parameter.Value.Builder#orDefault does not mark parameter as optional. Also another request

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3248]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 81f8ff9aab292daec57472cad8bb08b194d65997)
Java version: 8
Operating System: Windows 10
Plugins: WIP plugin for api-8
```

I don't think I need to explain more but when building a parameter with orDefault, it will not be marked as optional even when we force it using optional() method.

I have another request about the orDefault method. 
It is said in the javadoc that orDefault fills the parameter when missing AND when parsing failed.

It could be cool to have the opportunity to separate these two cases, for example with orDefaultOnFail(), and orDefaultOnMissing()..  (with better names maybe)

Thanks for reading this issue

**Comment by dualspiral** [comment]
`orDefault` is going away. It will be up to the developer to check to see whether something has been parsed or not if a parameter is optional.
