### ISSUE TITLE
NullPointerError on Forge1499+ Build 564, nothing else

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#325]
Latest build throwing NPE during server load, server crashes in preInit.  Forge1499 plus build 564 only, no plugins or mods.  Build 563 starts fine.
..concurrentHashMap // SpongeDataRegistry// SpongeGameRegistry....

http://s.mpserv.net/63043f99d3c07e7883e0d32f10ad0113.png  Image of error

**Comment by Aaron1011** [comment]
@theboomer: This will be fixed as soon as I bump the `SpongeCommon` ref to this commit: https://github.com/SpongePowered/SpongeCommon/commit/7c3927d89124173bcd4a619a23b7414ddae741e9.

I'm hold off to avoid bumping it again when I fix another issue.
