### ISSUE TITLE
No exposed way to retrieve Parameter.SubCommand registered via Command.Builder.parameter(Parameter) and wrapped into SpongeMultiParameter

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3250]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 81f8ff9aab292daec57472cad8bb08b194d65997)
Java version: 8
Operating System: Windows 10
Plugins: WIP plugin for api-8
```

I'm building terminal command that displays all possible sub commands, like this:

![available](https://user-images.githubusercontent.com/25883318/103457721-05f2be80-4d02-11eb-9b3c-970f39ce9e66.png)

But when I have a prefixed parameter like that:

`/cm border [<world>] <subcommand>`

I have to use the  Command.Builder.parameter(Parameter) and wrap all my subcommands in a FirstOf parameter.

When I don't have prefixed parameter, I can use the Command.Parameterized#subcommands to display the subcommands.
Otherwise, I have no way to retrieve the subcommands parameter wrapped in the SpongeMultiParameter (FirstOf here)

If I use Command.Parameterized#parameters, I have no way to retrieve the subcommands parameters because no method neither interface are exposed for SpongeMultiParameter in the api

![notexposed](https://user-images.githubusercontent.com/25883318/103457796-9df0a800-4d02-11eb-8786-19c5775453ea.png)

My ideal wish would be a way to access to  `public List<Parameter> getParameterCandidates()` from  `SpongeMultiParameter`

Thanks for reading this issue

**Comment by Faithcaio** [comment]
already part of https://github.com/SpongePowered/SpongeAPI/pull/2286
