### ISSUE TITLE
WorldManager#worldKeys file system exploration is bugged

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3255]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 13b8c404e47f91f1c99913396910c2f2b33ce60f)
Java version: 8
Operating System: Windows 10
Plugins: WIP plugin for api-8
```

Hey, I generated new worlds with the API-8, but WorldManager#worldKeys contains malformated keys

![keys](https://user-images.githubusercontent.com/25883318/104372913-7084d500-5520-11eb-85ed-e9df281812f9.JPG)

Thanks for reading this issue

**Comment by Zidane** [comment]
Haha, that is fucked up.

Okay thanks, will fix this evening.

**Comment by Zidane** [comment]
I believe I pushed up the fix to this.
