### ISSUE TITLE
Command completion after a flag is broken

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3264]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 3753b5e3630bb22f25402d1f8452f7eb8afb7ce2
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hello, today I'm gonna write a serie of issues that are in my mind or just as todos in my plugin for api-8.
Sorry for the spam.

So, for this first issue, I encoutered a problem using flags in command.
Move command : `/cosmos move [--safe-only] [<targets>] [<world>] [<x> <y> <z>] [<pitch> <yaw> <roll>]`

So when I complete my move command like that:

`/cosmos move --safe-only` 

I got the following ui completion: 

![flag3](https://user-images.githubusercontent.com/25883318/106389966-66028080-63e6-11eb-9273-8a43b2fa2f8c.png)

And it's infinite :

![flag2](https://user-images.githubusercontent.com/25883318/106389844-e1176700-63e5-11eb-8235-81805f1e70bb.png)

Thanks for reading this issue

**Comment by dualspiral** [comment]
And that's correct. Flags are intended for use multiple times - that's how they worked in 7, that's how they work in 8. If you don't want that behaviour, just create a literal and put it in your command itself.
