### ISSUE TITLE
Locate world folders in API-8

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3265]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 3753b5e3630bb22f25402d1f8452f7eb8afb7ce2
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey, I wrote this issue because at the moment we have no exposed way to locate the path of minecraft worlds in API-8.

Indeed, the nether and the end are located in the default world folder, but no way to know where is the default world folder located.
The folder location depends on the `level-name` property in the `server.properties` file.

Also, it's possible to build a custom way to locate plugin worlds but this should be in the api.

So for these two problems, it would be nice to have a method for that in the world manager.

Like `Path getWorldPath(ResourceKey worldKey)`

Thanks for reading this issue

**Comment by dualspiral** [comment]
> we have no exposed way to locate the path of minecraft worlds in API-8

Why do you need this?

**Comment by thibaulthenry** [comment]
Backup worlds

**Comment by Zidane** [comment]
Added: https://github.com/SpongePowered/SpongeAPI/commit/1a462fdd1f1c20f1b6d42c6c0cbfc8adf4426541
