### ISSUE TITLE
List every world templates keys existing in api-8

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3268]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 3753b5e3630bb22f25402d1f8452f7eb8afb7ce2
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey!

Currently in the world manager of the api-8 we have no way to list every existing templates keys like we do for the world keys.
Would be nice to have a command like the following one : 

`List<ResourceKey> templateKeys();`

For example: 

![templateKeys](https://user-images.githubusercontent.com/25883318/106390117-24260a00-63e7-11eb-9045-8e7b68d73ac9.png)

Here my template key would be `cosmos:need`

This would be useful to load templates generated by another plugin for example.

Currently, if I'm not using the template directly after I generated it, I can't retrieve its key anymore with the api.

Thanks for reading this issue

**Comment by Zidane** [comment]
Added: https://github.com/SpongePowered/Sponge/commit/a57b24dd57792c5dc649f2a28d4427fda1a11ac4
