### ISSUE TITLE
ClientCompletionTypes list of default parameters is always empty

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3270]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 3753b5e3630bb22f25402d1f8452f7eb8afb7ce2
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey,

As the title says, when we use try to list the `ClientCompletionTypes` of a default parameter, like `Parameter.entity()`,
the list is always empty :

![empty](https://user-images.githubusercontent.com/25883318/106390286-eaa1ce80-63e7-11eb-96a7-62543fe98cf2.png)

The strange thing is that the `Parameter.Value<Entity>` will accept types like selectors, but without any `ClientCompletionTypes` listed.

I do think that when Sponge tries to convert Minecraft parameters (in `SpongeRegistryLoaders`), it forgets to register the `ClientCompletionTypes`.

Thanks for reading this issue.

**Comment by dualspiral** [comment]
And that is expected, as per https://github.com/SpongePowered/SpongeAPI/blob/api-8/src/main/java/org/spongepowered/api/command/parameter/managed/ValueParser.java#L95-L100

What you're really asking for is for more CCTs to be exposed

**Comment by dualspiral** [comment]
Closing this issue. The behaviour isn't a bug and from later issues and discussions, the root problem that led to this was solved in a different way.
