### ISSUE TITLE
The relevance of CommandContext#getAll in API-8

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3275]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 3753b5e3630bb22f25402d1f8452f7eb8afb7ce2
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey,

In API-7, `CommandContext#getAll` was useful because an argument typed as, for example, `Entity`, could contain either a single Entity or a list of Entity.
To have a list of entities, we used to do this : `args.<Entity>getAll(Text.of("targets"))`

But now parameters are strictly typed so you can't retrieve a list of entities from a `Parameter.Value<Entity>`

Also if you have a parameter typed as `Parameter.Value<List<Entity>>` you can't use `CommandContext#getAll`, otherwise it will give you a `List<List<Entity>>`.

In all case I had to use `CommandContext#getOne`, even when I need to get a list of things.

What is the relevance of `CommandContext#getAll` now ? Is there any use case ?

Thanks for reading this issue.

**Comment by dualspiral** [comment]
Yes, if you use the parameter with the same key multiple times you need to use `getAll` with it - such as via `consumeAllRemaining`. It is by design.
