### ISSUE TITLE
Redstone Event Structure Idea

### ISSUE THREAD

**Issue by LinkTheProgrammer** [SpongePowered/Sponge#328]
I actually got this idea from just happening to be in the teamspeak while some sponge devs were talking about how they were going to design the redstone event structure.

This is my idea:

New Objects:
RedstonePath

Overview of RedstonePath:
Contains redstone objects (in an ArrayList<> most likely so it can be expanded).
A second List of redstone objects that will actually have their state updated from an event.

Logic:

Whenever redstone dust is placed down, you check the neighboring blocks and create a new RedstonePath or merge onto a neighboring RedstonePath if it exists (probably through a path "filesystem" so to speak, ordered by chunk). You must check for redstone blocks, redstone dust, and redstone peripherals only.

Whenever redstone dust is destroyed: if it was a segment in a RedstonePath, you split the path into separate segments (6 total possible). Else, set the reference to the RedstonePath that held the redstone to null and let GC do it's work (unless of course you put the path into an ObjectPool to circumvent GC).

Whenever a redstone event is triggered the first time, it should propagate the full redstone circuit within a RedstonePath, and any non-redstone blocks should be added to the second List for blocks to be updated. The redstone dust need only be graphically updated as you can calculate the power of the next peripheral or block at any time, in any redstone state. 

Whenever a redstone event superseding the first is triggered, the second List in the path will be updated rather than the first.

This is very much an implementation of a state machine. Quite efficient since it skips updating the state of unnecessary blocks such as redstone dust and peripherals. There is still the problem of pistons and how it will affect the implementation of RedstonePaths, but this should suffice for now. Really, you could turn minecraft into a FSM and you wouldn't need to make redstone an FSM, plus it would solve the piston problem on it's own.

**Comment by spaceemotion** [comment]
While not a bad idea, how would you go about storing that data? Afaik, Minecraft currently does know which redstone things are connected like you describe it - these custom lists / maps would have to be stored somewhere (inside additional files?).

And what if somebody decides to create a world, build contraptions in it, adds the sponge mod and uses a plugin that needs the redstone feature? The first time it might create that cached list, but what if he removes sponge again (for whatever reason), continues building and later decides to re-add it? The cache would have to be updated and checked for changes, not just across restarts and (re-)installs, but also across world modifications from other tools (such as MCEdit) and/or plugins.

Otherwise adding some sort of redstone context to see which blocks were involved could be very helpful, so good luck with that!

**Comment by LinkTheProgrammer** [comment]
Well, here's what I would do in the case of a world that never had sponge
before:
probe the generated chunks for redstone and redstone blocks, not
peripherals, since peripherals rely on a source of redstone to work, and
the next time you place redstone or a torch it would turn into a
RedstonePath anyways. I would then make a registry for those chunks (see
details next paragraph)

If the world was started with sponge I would:
Create a cascading registry file with chunk references to chunks that
contain redstone dust or blocks, and the chunks would have chunk
coordinates of the 1)initial source(s) of the redstone signal (or null) 2)
the chunk coordinates of strings of redstone dust relative to chunk vector
(0, 0, 0)(throw RedstoneChunkParseException if no redstone dust is
found) and 3) chunk locations of non-redstone blocks affected directly by
any redstone current and in turn affect the circuit directly.

I would also be careful to check for chunk corruption and throw a
CorruptChunkException if I found one, catch it, and attempt to regenerate
the chunk and restore it as best as possible to the modified state.

**Comment by JBYoshi** [comment]
Thirteen labels...? That's the most I've ever seen on any GitHub project! :smile:

**Comment by LinkTheProgrammer** [comment]
Ikr 😂

**Comment by ST-DDT** [comment]
How would we handle integrated circits added by plugins (special signs). Or blue redstone etc?

**Comment by LinkTheProgrammer** [comment]
As long as that plugin's objects extend redstone then it would be
compatible. Unless you run the server on a Turing machine of course then
any redstone derivatives would be compatible!

**Comment by Zidane** [comment]
This ticket has ran its course.

**Comment by LinkTheProgrammer** [comment]
Was it implemented?

**Comment by DDoS** [comment]
No, it was rejected. We have more important things to work on and this feature would be too complicated to implement and maintain.

**Comment by LinkTheProgrammer** [comment]
Well perhaps when I have time I can implement it for you and when you guys
have the time you can do the rest and integrate it into sponge (I'll just
make a PR when it's done)

**Comment by DDoS** [comment]
Good luck, but keep in mind that this is likely to break and cause compatibility issues in the future. We won't pull it if we can't properly manage these problems.

**Comment by LinkTheProgrammer** [comment]
Compatibility issues? Why, I've never heard of compatibility issues in an
OOP environment. Especially since you can create a compatible wrapper class
for an object. What were you saying?

**Comment by LinkTheProgrammer** [comment]
How do you think my entire backwards compatible API will work?

**Comment by wizjany** [comment]
We have yet to see it work.

**Comment by LinkTheProgrammer** [comment]
Yes I know "all words no action" been there done that. Everyone'll have to
wait because I don't have a team to work on it while I'm at school, and I
haven't moved it from my old hard drive yet.

**Comment by Andre601** [comment]
dear god.... How many labels do you want to add?

**Comment by kashike** [comment]
Yes.
