### ISSUE TITLE
Redstone Bugs

### ISSUE THREAD

**Issue by Pulverizer** [SpongePowered/Sponge#3291]
**I am currently running**

- SpongeVanilla version: latest stable-7 in a dev environment
- Java version: 8 build 251
- Operating System: Windows 10

- Plugins:

**Issue Description**
I've realised that the issue was not with the patches but with sponge. Details are in this post:
https://github.com/SpongePowered/Sponge/issues/3291#issuecomment-808331883

Original Issue:
> Minecraft has a known redstone bug: https://bugs.mojang.com/browse/MC-11193
> 
> I activated the Eigen patch, however, 10 out of 12 dispensers fired and 16 TNT was dispensed.
> So the patch does not function correctly.

**Comment by Earthcomputer** [comment]
Which of those contraptions did you activate?

**Comment by Pulverizer** [comment]
> Which of those contraptions did you activate?

A TNT cannon of mine. I'll try to provide a few more details regarding the design tomorrow.

**Comment by Pulverizer** [comment]
Sorry, I forgot about this, Uni got busy.

Here's the TNT cannon video: https://1drv.ms/v/s!An7pkNSr0-ZVg598ZsfGpPl0L9_jZA?e=lSTv2G

**Minor Corrections:**

1. There are 12 TNT propellent dispensers, not 14. Oops!

2. When looking at the console I reviewed the first firing and not the second. I also read the information incorrectly.

First explosion is from when all the dispensers triggered.
There are 18 TNT, all of which are propellent.

In the second explosion from when the two bottom middle dispensers did not trigger there are 16 TNT, all of which are propellent.

REMINDER: There are only 12 propellent dispensers!

**Comment by Earthcomputer** [comment]
Works as intended:
![Screenshot from 2021-02-13 13-20-03](https://user-images.githubusercontent.com/13084089/107850948-34ce7b00-6dfe-11eb-8cba-91bc660db60e.png)

**Comment by Pulverizer** [comment]
Okay, but that still doesn't explain how I got more TNT dispensed than there were Dispensers.
I'd like to also note that this design would function correctly on Spigot.

**Comment by Earthcomputer** [comment]
> I'd like to also note that this design would function correctly on Spigot.

It's locational

**Comment by Pulverizer** [comment]
Seems I am mistaken, it does not function on Spigot either.
But I know it does function on a server that I used to play on.
I'll reach out to them and see if they know anything.

**Comment by Pulverizer** [comment]
Found it! :)

Okay so, 1.12 Paper and Spigot use egien-redstone.
Spigot 1.10 uses panda-redstone and this design does work.

Switched to panda-redstone and the dispensers work.
Still spawning too much TNT though.

**Comment by gabizou** [comment]
> Still spawning too much TNT though

Under what context?

**Comment by Pulverizer** [comment]
> > Still spawning too much TNT though
> 
> Under what context?

With either Panda's or Eigen's patch, my design has 12 propellent dispensers but spawns 18 or 16 respectively.
I know that spigot 1.10.2 uses a patch (think it might be Panda's?) that does not have this issue.

Could you point me to where these patches are applied?

**Comment by Earthcomputer** [comment]
The issues you're experiencing have nothing to do with redstone dust and everything to do with quasi-connectivity. You need to either get a patch that fixes quasi-connectivity not updating droppers/dispensers, or redesign your contraption so it works with quasi-connectivity in mind.

**Comment by Pulverizer** [comment]
> The issues you're experiencing have nothing to do with redstone dust and everything to do with quasi-connectivity. You need to either get a patch that fixes quasi-connectivity not updating droppers/dispensers, or redesign your contraption so it works with quasi-connectivity in mind.

Dispensers activating twice from a single signal is somehow QC? Could you explain how QC would cause that?

**Comment by Pulverizer** [comment]
~~have written a test plugin and even with the patches disabled the dispensers are still spawning more TNT entities than they should.~~

![image](https://user-images.githubusercontent.com/9803259/112659870-bc22fb80-8e4c-11eb-99e5-73c1960c027a.png)
 ~~the design is the same i used before, it only have 15 propellent and 2 projectile dispensers.~~
 ~~Somehow, even with the dispensers all firing correctly the first time it manages fire 2 TNT from some of them even though only 1 TNT is consumed.~~

**Comment by Pulverizer** [comment]
nvm i forgot about some dispensers when counting. just going to close this for now
