### ISSUE TITLE
A command with children is always terminal even when specifying not to be

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3299]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 2143a6d4ef9c60846a062554f83d500fde096ebd)
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey,

When bulding the following command structure, the parent command is terminal whereas I specify not to be.
Same behavior if I don't use the setter `setTerminal`.

```java
final Command.Builder commandBuilder = Command.builder();

final Map<List<String>, Command.Parameterized> childCommandMap = new HashMap<>();
childCommandMap.put(Arrays.asList("sub1", "subone"), new Sub1().getParametrized());
childCommandMap.put(Arrays.asList("sub2", "subtwo"), new Sub2().getParametrized());

commandBuilder.children(childCommandMap);

Command.Parameterized parameterized = commandBuilder
        .setExecutor(new Parent())
        .setTerminal(false)
        .build();

event.register(Cosmos.pluginContainer, parameterized, "parent");
```

Thanks for reading this issue

**Comment by dualspiral** [comment]
Why wouldn't your example be terminal? 

```java
final Command.Builder commandBuilder = Command.builder();

final Map<List<String>, Command.Parameterized> childCommandMap = new HashMap<>();
childCommandMap.put(Arrays.asList("sub1", "subone"), new Sub1().getParametrized());
childCommandMap.put(Arrays.asList("sub2", "subtwo"), new Sub2().getParametrized());

commandBuilder.children(childCommandMap);

Command.Parameterized parameterized = commandBuilder
        .setExecutor(new Parent())
        .setTerminal(false)
        .build();

event.register(Cosmos.pluginContainer, parameterized, "parent");
```

In your example, reproduced above, you have a parameterless, childless command with an executor. If it wasn't terminal, what's the point of it? 

I suspect you meant to add children to it. But even if you added the children to it, kind of the same point, because you **can** have a command with children and no executor. If that's what you want, don't set the executor.

**Comment by thibaulthenry** [comment]
I first expected the terminal field to lock the fact that the command can be terminal. 
What confused me is the fact that I clearly defined my command as non-terminal with the `false` boolean but the presence of the executor made the command effectively terminal.

In case of non-terminal command, you're right, add the executor is pointless.
Actually I have a global management of this type of command registration, so I extracted an example to show the case I was facing.

I'll just not add the executor if the command is not expected to be terminal.

Thanks for help :)
