### ISSUE TITLE
Vector parameters have an extra 0.5 value to X and Z coordinates

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3310]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 5a0778bc25a66ea96b6799e6c347b65aa4473592)
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hello,

I just discovered that the brigadier parameter used by Sponge with `Parameter.vector3d()` is adding an extra +0.5 to X & Z coordinates, maybe to center entities on blocks.

However this is something we don't expect in Sponge, or at least we should have a way to choose if this +0.5 is effectively added.

![0 5](https://user-images.githubusercontent.com/25883318/110224820-6c04e900-7edf-11eb-845c-508aa67c3a73.png)

It also concerns the Vector2d: 

```java
Parameter.builder(Vector2d.class)
        .setKey(CosmosKeys.X_Z)
        .parser(ResourceKeyedValueParameters.VECTOR2D)
        .optional()
        .build()
```

Thanks for reading this issue

**Comment by thibaulthenry** [comment]
This +0.5 value is only added when the input is an integer apparently.

0 0 0 -> 0.5 0 0.5
0.5 0 0.5 -> 0.5 0 0.5
-1 0 -1 -> -0.5 0 -0.5

**Comment by dualspiral** [comment]
It's what Vanilla does, we just translate the output from their parser like so: https://github.com/SpongePowered/Sponge/blob/api-8/src/main/java/org/spongepowered/common/registry/SpongeRegistryLoaders.java#L352-L358

I'm kind of the side of it might be considered "expected", but only because it's what Mojang does. In any case, I'd want to keep this behaviour in some form because I know some people _will_ want it.

**Comment by thibaulthenry** [comment]
I do know that Sponge is using vanilla parameters.
But do we want this bevahior in Sponge ?

I mean a vector3d is not always a position, in my case its a velocity so the 0.5 is not expected

**Comment by dualspiral** [comment]
> But do we want this bevahior in Sponge ?

> In any case, I'd want to keep this behaviour in some form because I know some people will want it.

**Comment by thibaulthenry** [comment]
So this needs to be documeted otherwise I'll not be the only one to encounter this.

In my case the problem is that I cant know from the value if this 0.5 has been automatically added or intentionnaly put by the user

So im not able to remove the extra 0.5 by myself

**Comment by dualspiral** [comment]
Note that I did not say that I wanted to keep this only. I said in some form - it could be that we just create another parameter that does not exhibit this behaviour.

**Comment by thibaulthenry** [comment]
Oh right I misinterpreted.
This could be a solution for me indeed.

Thanks

**Comment by dualspiral** [comment]
Coming back to this, I'm going to default to the behaviour you suggest - you're right, as a default this is more sensible.

If someone wants the behaviour where entering an integer adds 0.5 to the axis, please add a new issue and we'll add it.
