### ISSUE TITLE
EntityVolume#getNearbyEntities throws IncompatibleClassChangeError

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/Sponge#3319]
Calling `EntityVolume#getNearbyEntities` throws an `IncompatibleClassChangeError`.

**Sponge version:** latest commit, `e2529303d40113b3b944ab1f3ebd5d301a35ff05`
**Java version:** `11`
**Stacktrace:** https://gist.github.com/ItsDoot/b62d3a68eb0458b8b3d8fc15ccffa89e

**Comment by zml2008** [comment]
Known issue, see SpongePowered/Mixin#451

**Comment by gabizou** [comment]
Fixed in the commit above. Workaround is to just move the methods where they'll be not conflicting with an interface mixin.
