### ISSUE TITLE
Kicked for flying after using cruxite artifact from Minestuck

### ISSUE THREAD

**Issue by mraof** [SpongePowered/Sponge#332]
After using the cruxite artifact for the first time, the player is kicked for flying and the surrounding area is not copied to the new dimension

**Comment by bloodmc** [comment]
@mraof Please post the stack trace.

**Comment by JBYoshi** [comment]
@bloodmc It's a *kick*, not a crash.

**Comment by EzraEn1** [comment]
\@JBYoshi We don't want a _crash report_, we want a _stack trace_. So post
the _log_.

On Sat, Aug 29, 2015 at 3:40 AM, JBYoshi <notifications@github.com> wrote:

> @bloodmc <https://github.com/bloodmc> It's a *kick*, not a crash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpongePowered/Sponge/issues/332#issuecomment-135869435>
> .
>



-- 
Check out my site and send me ideas!

**Comment by JBYoshi** [comment]
As I said before, there is no stack trace for a kick.

**Comment by Zidane** [comment]
Closing this until we get more feedback.
