### ISSUE TITLE
Crash atstart-up org.spongepowered.common.configuration.SpongeConfig

### ISSUE THREAD

**Issue by vlee489** [SpongePowered/Sponge#333]
When I Launch Sponge with mods I Get a Crash.

Error Log at https://gist.github.com/vlee489/8b75431b734fbc616fb8

Sponge build: 1.8-1499-2.1DEV-590
Forge Version: 11.14.3.1499
Client type: Forge (11.14.3.1499)
Installed plugins/mods
  - [1.8]bspkrsCore-universal-7.01
  - [1.8]Treecapitator-universal-2.0.5
  - AdminShop-0.3 (Plugin)
  - AttachableGrinder-5.0.0
  - CodeChickenCore-1.8-1.0.5.36-universal
  - IceCreamSandwichCreeperModv1.1.0a 1.8
  - iChunUtil-5.4.0
  - ironchest-1.8-6.0.99.749-universal
  - MobAmputation-5.0.0
  - MrCrayfishFurnitureModv3.4.8-build1(1.8)
  - NotEnoughItems-1.8-1.0.5.104-universal
  - Torched-5.0.0
  - TotalEconomy (Plugin)
  - TrailMix-5.0.0
  - worldedit-forge-mc1.8-6.1
  - Yampst-YGcraft Modded-Beta1.3 (https://en.yampst.net)
  - CodeChickenLib-1.8-1.1.2.133-universal (Automatic Generated by chicken code core at startup in the 1.8 folder) 

Java Version: 1.8.0_25
Operating System: Windows 10 64x

###### A download of the all the stuff used in the server is at http://files.superninja.xyz/Spongefailed.zip

**Comment by simon816** [comment]
This is due to an incompatibility with CodeChickenCore
I have a PR to forge which I hope will fix it, https://github.com/MinecraftForge/MinecraftForge/pull/2022
(I need to update the PR in fact)

**Comment by simon816** [comment]
The issue has been fixed with Forge, [update Forge](http://files.minecraftforge.net/) to `11.14.3.1521` and grab the [latest Sponge build](https://repo.spongepowered.org/maven/org/spongepowered/sponge/)
