### ISSUE TITLE
why does https://github.com/SpongePowered keep telling lies

### ISSUE THREAD

**Issue by LOLDERP** [SpongePowered/Sponge#334]
like i check https://github.com/SpongePowered and it said sponge was updated 2 hours ago when 
i pressed it it said authored 9 days ago

**Comment by rfox90** [comment]
This isn't an issue, Its a misunderstanding of how GitHub and by proxy Git works.

Sponge's Master branch was updated 9 days ago. Other branches have newer commits.

Please only open issues here if they are issues?
