### ISSUE TITLE
[API 8] Sync scheduler is running behind on what looks like a per tick basis

### ISSUE THREAD

**Issue by NickImpact** [SpongePowered/Sponge#3341]
**I am currently running**

- SpongeVanilla version: API 8 - RC 486
- Java version: 1.8.0_221
- Operating System: Windows 10

- Plugins/Mods: Impactor, ImpactDev Interface (Scoreboard)

**Issue Description**
The Sync Scheduler appears to be taking too long to process during some tick intervals. It appears that there are situations where the scheduler will skip a singular tick, assuming the process to setup the executor took too long in that tick. While you'll get some on the correct rate, it appears that a good portion of executions end up a tick later than they should, causing some ambiguity into the actual rate of the task.

Below is a tracked state of executions given a set of ticks for its interval, using the following code:
```Java
private Instant prior;

    public TPSWatcher(boolean supportsDuration) {
        this.durationSupported = supportsDuration;
        Sponge.server().scheduler().submit(Task.builder().execute(() -> {
            Instant now = Instant.now();
            if(prior == null) {
                prior = now;
            }
            SpongeImpactorPlugin.getInstance().getPluginLogger().info("Timestamp: " + now + " - " + Duration.between(prior, now).toMillis() + "ms since last iteration");
            prior = now;

            this.onTick(this.tick++);
            if(this.tick == Integer.MAX_VALUE - 8) {
                this.tick = 0;
            }
        }).interval(Ticks.of(<tick rate>)).plugin(SpongeImpactorPlugin.getInstance().getPluginContainer()).build());
    }
```

## Tick Rates

1 = https://gist.github.com/NickImpact/c9dd7c031f7b44c6c9b64d4eb0f7809b
2 = https://gist.github.com/NickImpact/2d33078abef21d7d5cab719254533da5
20 = https://gist.github.com/NickImpact/5b62557ba634de8805e8baeaa408b4da

**Comment by dualspiral** [comment]
Heh, this one is a little wild but I think I have it. It's easiest seen here:

https://github.com/SpongePowered/Sponge/blob/ebb449d79641e9f57601fde916dc87c33b158dc7/src/main/java/org/spongepowered/common/scheduler/SpongeTaskBuilder.java#L148-L149

Specifically, look at the last parameter - the task is only marked as tick based if BOTH a delay and interval are set as tick based. Later on, we have this:

https://github.com/SpongePowered/Sponge/blob/ebb449d79641e9f57601fde916dc87c33b158dc7/src/main/java/org/spongepowered/common/scheduler/SyncScheduler.java#L48

...which for your test case is `false`. So what happens then is that if the scheduler starts at, say, 5ms into a tick, then 3ms into a tick, the delta is 48ms, meaning that the task is skipped for a tick, hence what you see.

Committing a fix now.
