### ISSUE TITLE
Unexplanable command completion conflict with aliases in API-8

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3349]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit f213985571fcc41fb69f0a5fcfcabafc2ad44b6a)
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey, 

I have this command in my plugin :

Move:
`/cm move [<entities-moved>] [<world>] [<x> <y> <z>] [<rx> <ry> <rz>]`

Move has two aliases : `mv` and `tp`

For a reason I can't explain, I do not have the same completion when using `/cm move` or `/cm tp` :

![move](https://user-images.githubusercontent.com/25883318/112386285-03947500-8cf1-11eb-9af1-571e827dd2ef.png)

![tp](https://user-images.githubusercontent.com/25883318/112386307-0a22ec80-8cf1-11eb-8bde-cad7ded9302d.png)

This is the same command so the completion should be the same.
Morever, when I start to complete the tp command I have parsing error :

![tpwrong](https://user-images.githubusercontent.com/25883318/112386534-6128c180-8cf1-11eb-8153-a584a607ee41.png)

Whereas when I press enter, the command runs normally.

Weirdest thing is that this bug happens only for the `tp` alias, `mv` works perfectly fine

Thanks for reading this issue

**Comment by dualspiral** [comment]
Provide code to reproduce this. I think I know what's going on but having a minimal test case that I can just copy/paste will help.

**Comment by thibaulthenry** [comment]
Unfortunately I do not manage to extract a standard example from my command registration system so I'm not able to identify the real issue of this problem.

But this is a bug that is persistent. Each time I run the server the completion fails for this specific alias.

I'll try to find a clear reproduction of this bug with standard Sponge parameters

**Comment by dualspiral** [comment]
Try the latest commit - [I think this is the problem.](https://github.com/SpongePowered/Sponge/commit/3874fc4a092cc451cdacb262e507f0a22e406cf7#diff-4ae5ea2bdfc5b89195819fae0e31629744b86b3d3b087247437e4946e9a5b3ebR102-R118)

**Comment by thibaulthenry** [comment]
Indeed, it's now working correctly!
