### ISSUE TITLE
Completion positionned at the start of the command with ValueParameterModifiers after completing once

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3360]
```
SpongeVanilla version: 1.16.5-8.0.0 (commit 2f5a93109a79207ebf754b3105697d7446b7c7f3)
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey, I'm currently trying to manipulate `ValueParameterModifiers` to solve a problem I'm facing with the `MANY_ENTITIES` built-in parameter of brigadier.

I discovered a bug that put my additionnal completion strings at the start of the command.

My modifier:

```java
private static final class EntitiesModifier implements ValueParameterModifier<List<Entity>> {

    @Override
    public Optional<? extends List<Entity>> modifyResult(Parameter.Key<? super List<Entity>> parameterKey, ArgumentReader.Immutable reader, CommandContext.Builder context, @Nullable List<Entity> value) throws ArgumentParseException {
        if (value == null || value.isEmpty()) {
            throw reader.createException(Component.text("No entities found"));
        }

        return Optional.of(value);
    }

    @Override
    public List<String> modifyCompletion(final CommandContext context, final String currentInput, final List<String> completions) {
        completions.add("Kazz96");
        completions.add("NewCompletion");

        return completions;
    }
}
```

A standard command example: 

```java
Command.Parameterized command = Command.builder()
        .addParameter(
            Parameter.builder(new TypeToken<List<Entity>>() {})
                .addParser(ResourceKeyedValueParameters.MANY_ENTITIES)
                .modifier(new EntitiesModifier())
                .key(Parameter.key("targets", new TypeToken<List<Entity>>() {}))
                .build()
        )
        .addParameter(Parameter.bool().key("state").build())
        .executor([...executor...])
        .build();
```

Before I start completing : 

![before](https://user-images.githubusercontent.com/25883318/113631990-9e367180-966a-11eb-95e3-273d213dcef4.png)

After:

![completionmodifier](https://user-images.githubusercontent.com/25883318/113632002-a2628f00-966a-11eb-9298-74fc8c91328a.png)

As you can see, only the extra completion choices are displayed at the start.

Then if I press tab, the completed string is put at the start of the command

Thanks for reading this issue

**Comment by dualspiral** [comment]
There is a valid bug here.

However, based on this issue I need to point out that while I added modifiers for you, you seem to misunderstand their limitations. Adding a completion is not going to make the parameter accept it, they are intended as a filter and operate on the result of a parameter. So, adding a new completion is not going to work in this case anyway.

**In general, you should NOT be using a modifier unless you are altering the existing potential results - either by removal or modification of what they return.** If you want to add something new, use `firstOf` and a separate element.

**Comment by thibaulthenry** [comment]
The parameter after the `add` node is this one (again):

```java
Parameter.firstOf(
                Parameter.builder(new TypeToken<List<Entity>>() {})
                        .addParser(ResourceKeyedValueParameters.MANY_ENTITIES)
                        .key("entities")
                        .modifier(new EntitiesModifier())
                        .build(),
                Parameter.formattingCodeText().key("text-ampersand").build(),
                Parameter.jsonText().key("text-json").build()
        )
```

If I do not add the modifier to modify the result, the `MANY_ENTITIES` will catch any input value and return an empty collection without throwing an error.

This is why I did this:

```java
if (value == null || value.isEmpty()) {
    throw reader.createException(Component.text("No entities found"));
}
```


Modifying the completion possibilities wasn't here to ask the parameter to accept them.
It was for testing purpose and I discovered this bug

In my case, my `NewCompletion` completion would fall into the `formattingCodeText`, because not accepted by the `MANY_ENTITIES` as you said.

**Comment by dualspiral** [comment]
In truth, then, this is actually very much a non-bug. This will only occur if you're adding completions that don't exist on the root parameter - if you were trying to do that it was never going to work in the first place. 

Nevertheless, I've fixed it.
