### ISSUE TITLE
Parameter#jsonText has accepts an extra character

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3361]
```
SpongeVanilla version: 1.16.5-8.0.0 (commit 6960240abb8dd4d811a4898b148238cdb152e93a)
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey, recently I figured out that the `Parameter.jsonText()` parameter accepts a extra character :

```java
Command.Parameterized command = Command.builder()
        .addParameter(Parameter.jsonText().key("json").build())
        .addParameter(Parameter.bool().key("state").build())
        .executor(new Test())
        .build();
```

You can see I cant put whatever I want after the last bracket: 

![json](https://user-images.githubusercontent.com/25883318/114074753-05d80100-98a5-11eb-9b05-154efc6ec0f3.png)

This extra character is not optional, you have to add 2 minimum space if you want to continue the command completion :

![json2](https://user-images.githubusercontent.com/25883318/114075185-8f87ce80-98a5-11eb-9d7f-cde4aecfcbda.png)

But if I press enter here, I got an error message (maybe because there are 2 whitespaces between 2 parameters ?)

![json3](https://user-images.githubusercontent.com/25883318/114075445-d83f8780-98a5-11eb-938a-bd90417b0a05.png)

If I put the  `Parameter.jsonText()` in a `FirstOf` parameter I have the same behavior : 

![json2firstof](https://user-images.githubusercontent.com/25883318/114075572-f7d6b000-98a5-11eb-9750-54a9aaa1e186.png)

You can test with:

```java
Command.Parameterized command2 = Command.builder()
        .addParameter(
                Parameter.firstOf(
                        Parameter.jsonText().key("json").build(),
                        Parameter.bool().key("state").build()
                )
        )
        .addParameter(Parameter.bool().key("state").build())
        .executor(new Test())
        .build();
```

Well, at this point this is not really annoying because the parsed json will have no clue that you added an extra character (when you check in your executor)

However, I have command that uses `Parameter.jsonText()` into a `FirstOf`, and if I combine this bug with the bug https://github.com/SpongePowered/Sponge/issues/3360, I can't use my command :

![json3combined](https://user-images.githubusercontent.com/25883318/114075534-ec838480-98a5-11eb-9370-e04a4dafcd19.png)

The fact that the command cannot be parsed above only occurs with modifiers. If I don't add any modifier to my parameter, it works.

Also, if I don't use json but have a modifier it works :

![json3combined2](https://user-images.githubusercontent.com/25883318/114076341-d88c5280-98a6-11eb-90ee-37e2983a1bf2.png)

So, I concluded that this is the combinaison of the 2 bugs that broke my command.

Thanks for reading this issue

**Comment by dualspiral** [comment]
[Given that all we do with `jsonText` is delegate to the Mojang parameter](https://github.com/SpongePowered/Sponge/blob/api-8/src/main/java/org/spongepowered/common/registry/SpongeRegistryLoaders.java#L348), this is more likely to be a client bug rather than a Sponge problem.

**Comment by dualspiral** [comment]
Also:

> The fact that the command cannot be parsed above only occurs with modifiers. If I don't add any modifier to my parameter, it works.

...but you don't explain how or where the modifier is applied. Show code.

**Comment by thibaulthenry** [comment]
Yeah actually it's the exact same code than in https://github.com/SpongePowered/Sponge/issues/3360

```java
Parameter.firstOf(
                Parameter.builder(new TypeToken<List<Entity>>() {})
                        .addParser(ResourceKeyedValueParameters.MANY_ENTITIES)
                        .key("entities")
                        .modifier(new EntitiesModifier())
                        .build(),
                Parameter.formattingCodeText().key("text-ampersand").build(),
                Parameter.jsonText().key("text-json").build()
        )
```

with the modifier I described in https://github.com/SpongePowered/Sponge/issues/3360

**Comment by dualspiral** [comment]
Ignoring your modifiers problem for a moment (that should really be its own issue), I simplified your test case:

```java
        final Parameter.Value<String> testString = Parameter.string().key("string").build();
        final Parameter.Value<Component> jsonTextParameter = Parameter.jsonText().key("text").build();
        event.register(
                this.plugin,
                Command.builder()
                    .addParameter(jsonTextParameter)
                    .addParameter(testString)
                    .executor(ctx -> {
                        ctx.sendMessage(Identity.nil(), ctx.requireOne(jsonTextParameter));
                        ctx.sendMessage(Identity.nil(), Component.text(ctx.requireOne(testString)));
                        return CommandResult.success();
                    })
                    .build(),
                "testcomponentjson"
        );
```

I thought this might be a problem with how I translate the nodes for transferring to the client, but that's not the case. Putting a breakpoint in `n.m.commands.Commands`, final line of `sendCommands` and inspecting `var3`, it indeed shows me that the node structure is correct - we do nothing beyond this point:

![nodes](https://user-images.githubusercontent.com/1904167/114087117-61a58880-98ab-11eb-97f2-6e2f1d96cdb2.png)

So this is indeed a client bug. The only thing we could do is modify the parser to try to account for trailing rubbish to match the client experience.

**Comment by dualspiral** [comment]
Actually, looking at it more, my test case doesn't work at all on parsing, and your issue isn't clear as to what it does when you try to run it - have you _run_ the command, and if so, what works, and what doesn't?

**Comment by thibaulthenry** [comment]
`/test {"text":"json"}x true` will work only if x is not a whitespace

Otherwise I have the error I screened in the original post

**Comment by thibaulthenry** [comment]
![content](https://user-images.githubusercontent.com/25883318/114088654-87d02600-98b5-11eb-8a2f-f870dd74033d.png)

With the right content inside

**Comment by thibaulthenry** [comment]
Also, I figured out that Mojang always put the json parameter : `ComponentArgument.textComponent()` as the last parameter of scoreboard commands so they never encountered this issue of additional whitespace

**Comment by dualspiral** [comment]
It was indeed a Mojang problem, problem on the server too. Worked around it.

While I cannot work around the client bug for Vanilla clients, if they separate the parameters by two spaces, it'll still work. So a minor inconvenience, but at least it'll work now.

**Comment by thibaulthenry** [comment]
https://bugs.mojang.com/browse/MC-222880

**Comment by thibaulthenry** [comment]
Apparently the bug is already known since June 2018 but not fixed yet :
https://bugs.mojang.com/browse/MC-131636

It also effects component argument with double quotes. Single quotes works fine from what I see
