### ISSUE TITLE
IllegalAccessError when registering RegisterCommandEvent listener using `@Listener`

### ISSUE THREAD

**Issue by jpenilla** [SpongePowered/Sponge#3367]
**I am currently running**

 SpongeVanilla
    Minecraft: 1.16.5
    SpongeAPI: 8.0.0
    Sponge: 1.16.5-8.0.0
    SpongeVanilla: 1.16.5-8.0.0
    JVM: 11.0.10/64-bit (AdoptOpenJDK)
    OS: Linux/5.11.11-arch1-1 (amd64)

- Plugins/Mods: testing plugin

**Issue Description**

Registering an `EventListener` implementation works fine, however attempting to register the same listener using the `@Listener` annotation results in an `IllegalAccessError` when the generated listener is called. https://paste.gg/p/anonymous/b37300414b4f4a05aae31cf3e1092932

Listener:
```java
@Listener
public void handleRegistrationEvent(final RegisterCommandEvent<Command.Raw> event) {
  // ...
}
```
Registering like so works fine:
```java
Sponge.eventManager().registerListener(
        pluginContainer,
        new TypeToken<RegisterCommandEvent<Command.Raw>>() {},
        this::handleRegistrationEvent
);
```
Registering like so causes the `IllegalAccessException`:
```java
Sponge.eventManager().registerListeners(pluginContainer, this);
```

**Comment by Zidane** [comment]
@dualspiral 

Can you look into this one?

**Comment by RedNesto** [comment]
Seems like `cloud.commandframework.sponge.SpongeRegistrationHandler` is not public.

**Comment by dualspiral** [comment]
Ah, thanks @RedNesto, [that is indeed the problem](https://github.com/Incendo/cloud/blob/feature/sponge/cloud-minecraft/cloud-sponge/src/main/java/cloud/commandframework/sponge/SpongeRegistrationHandler.java#L41)

@jpenilla We use ASM to generate listener handlers, thus all listeners must be in public classes with public methods when using that route to register them.

Not a Sponge error.

**Comment by zml2008** [comment]
These restrictions could potentially be relaxed in API 9 with [hidden classes](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/invoke/MethodHandles.Lookup.html#defineHiddenClass(byte%5B%5D,boolean,java.lang.invoke.MethodHandles.Lookup.ClassOption...)) -- See #3456
