### ISSUE TITLE
Localization info is lost when calling `getString` on `CommandSyntaxException`

### ISSUE THREAD

**Issue by jpenilla** [SpongePowered/Sponge#3379]
**I am currently running**
SpongeVanilla 1.16.5

**Issue Description**

Localization info is lost when calling `getString` on `CommandSyntaxException`. This effects `ClientNativeArgumentParser`s: https://github.com/SpongePowered/Sponge/blob/028c07d48747f5ebb35b24b0bbf33a1471cda30f/src/main/java/org/spongepowered/common/command/brigadier/argument/StandardArgumentParser.java#L143 but also anywhere else `getString` might be called on a `CommandSyntaxException`. This is due to Mojang using `TranslatableComponent`s for error messages, which when converted to a String will use the default locale (in the case of the dedicated server, english).

**Proposed Solution**

Mixing into Brigadier's `CommandSyntaxException` so that it implements `ComponentMessageThrowable` would allow for preserving the `TranslatableComponent` by using `ComponentMessageThrowable.getOrConvertMessage`.

**Comment by dualspiral** [comment]
> Mixing into Brigadier's CommandSyntaxException so that it implements ComponentMessageThrowable

We cannot do that. We're working on the assumption that Brigadier is excluded from transformations.

**Comment by kashike** [comment]
Should be fixed with https://github.com/SpongePowered/Sponge/commit/1e192a151e3f21894a7b5c83735a1e0a8a42690a.
