### ISSUE TITLE
ServerLocation no longer DataSerializable

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/Sponge#3392]
In API-7, `Location` was `DataSerializable` (through `DataHolder`).
Now in API-8, `Location` (and therefore `ServerLocation`) is no longer `DataSerializable`.

This makes it non-trivial to serialize/deserialize custom data that contains locations.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/Sponge/commit/8bf35817def81dabb85f0c6c078795d54d820221
