### ISSUE TITLE
Whitewashed Banners in SV 1.17

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/Sponge#3424]
When the block supporting any banner is broken, a clean white banner is dropped. The pattern is erased.
For comparison, breaking the banner directly returns the patterned banner as expected.

This throws no errors in the console. 

SpongeVanilla: 1.17-9.0.0-RC651
JVM: 16.0.1/64-bit (Private Build)
OS: Linux/5.4.0-66-generic (amd64)

All we have are some CubeEngine plugins.

**Comment by Faithcaio** [comment]
@gabizou 

https://github.com/SpongePowered/Sponge/blob/a5629f7ee7c1b85b3c3ad173d80f5adb56e3c8fd/src/main/java/org/spongepowered/common/event/tracking/context/transaction/pipeline/WorldPipeline.java#L97
returns null when called after `this.chunkPipeline.processChange`

causing the dropped banner to not include the BlockEntity nbt
