### ISSUE TITLE
Maps evaporate in SpongeVanilla 1.17

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/Sponge#3425]
When opening a fresh, unused blank map (in the overworld), it makes an unfurling noise and promptly vanishes. No filled map object is produced. This throws no errors in the console.

SpongeVanilla: 1.17-9.0.0-RC651
JVM: 16.0.1/64-bit (Private Build)
OS: Linux/5.4.0-66-generic (amd64) yadda yadda

All we have are some CubeEngine plugins.

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/Sponge/blob/21aa50ff0019e3c5c33db070fa63027a0d74f0a7/src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java#L1047
