### ISSUE TITLE
IBlockReader isn't part of Sponge

### ISSUE THREAD

**Issue by mosemister** [SpongePowered/Sponge#3440]
**I am currently running**

- SpongeVanilla version: API: 8.0.0 (Built on 24th June 2021)
- Java version: 16
- Operating System: Windows 10

- Plugins/Mods: Custom unnamed plugin

**Issue Description**

I get the error of ``java.lang.UnsupportedOperationException: Unfortunately, you've found an extended class of IBlockReader that isn't part of Sponge API`` when using the following code

```java
Chunk chunk;
chunk.blockMin();
```

```java
        return this.chunk.entities(AABB.of(this.chunk.blockMin(), this.chunk.blockMax()));
```

**Comment by Zidane** [comment]
@mosemister Can you print a `toString()` of `this.chunk`?

**Comment by mosemister** [comment]
@Zidane 
Sure

``LevelChunk{World=ServerLevel[key=ResourceKey[minecraft:dimension / minecraft:overworld],worldType=minecraft:overworld], Position=-3}``

**Comment by Zidane** [comment]
Ah a `LevelChunk`
