### ISSUE TITLE
TabList sends duplicate packet information [API-8] + [API-7]

### ISSUE THREAD

**Issue by tyhdefu** [SpongePowered/Sponge#3443]
**I am currently running**

- SpongeForge version: N / A
- SpongeVanilla version: N / A
- Java version: N / A
- Operating System: N / A

This is an issue identified purely by code inspection.

There is duplicate information being sent in packets. ADD_PLAYER contains all the information.
There is no reason to again send update packets.
https://github.com/SpongePowered/Sponge/blob/stable-7/src/main/java/org/spongepowered/common/entity/player/tab/SpongeTabList.java#L166

Also the same in API-8
https://github.com/SpongePowered/Sponge/blob/api-8/src/main/java/org/spongepowered/common/entity/player/tab/SpongeTabList.java#L166

Code for if this gets fixed and these links become invalid:
```java
if (!this.entries.containsKey(uniqueId)) {
        this.entries.put(uniqueId, entry);

        this.sendUpdate(entry, ClientboundPlayerInfoPacket.Action.ADD_PLAYER); // KEEP
        entry.displayName().ifPresent(text -> this.sendUpdate(entry, ClientboundPlayerInfoPacket.Action.UPDATE_DISPLAY_NAME)); // REMOVE - UNECESSARY
        this.sendUpdate(entry, ClientboundPlayerInfoPacket.Action.UPDATE_LATENCY); // REMOVE - UNECESSARY
        this.sendUpdate(entry, ClientboundPlayerInfoPacket.Action.UPDATE_GAME_MODE); // REMOVE - UNECESSARY
}
```

It is quite clear from looking at `ClientboundPlayerInfoPacket` that the ADD_PLAYER case is a combination of all other cases.
Fixing this should improve performance.

**Comment by dualspiral** [comment]
I'm guessing you tested this? If so, throw us a PR will you? :)

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/Sponge/commit/d874ef212576250bb6c02a6f97579b14b277f6dc
