### ISSUE TITLE
Failed to load mixin configs from a plugin

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/Sponge#3445]
**I am currently running**
- SpongeVanilla version: https://github.com/SpongePowered/Sponge/commit/d50c4b42685a6885134e1fcb62390d96cea3498b (latest as of this posting)
- Java version: Both of `16.0.1` and `11.0.10.9`
- Operating System: `Windows 10`

- Plugins/Mods:
https://github.com/ExpanseMC/SoakedLight

**Issue Description**
Can't properly load mixin configs from a plugin.
https://gist.github.com/ItsDoot/ec20ec262ce0a3e0650f0edd5cef452c

**Comment by zml2008** [comment]
Should be fixed as of https://github.com/SpongePowered/plugin-spi/commit/050def24413318442bf468ba3a07ffc149a5104d -- latest SV build with this fix is off https://github.com/SpongePowered/Sponge/commit/304effb7ea2a0548138103369df0e10fc77c1f5a
