### ISSUE TITLE
.peek() reports inventory contents incorrectly and can produce stacked unstackable items. [API-7]

### ISSUE THREAD

**Issue by tyhdefu** [SpongePowered/Sponge#3446]
**I am currently running**

- SpongeForge version: 
- SpongeVanilla version: 7.3.0
- Java version: 8
- Operating System: Windows 10

- Plugins/Mods:
The plugin that contains this code.

**Issue Description**

Inventory.peek() is returning incorrect information. It reports multiple items with the same damage value instead of one of each, and consequently, peeking then removing just dupes the items, whereas it should cleanly remove them one at a time. I have only tested this with diamond swords of different damage values.

```java
ItemStack itemStack = inventory.query(QueryOperationTypes.ITEM_STACK_CUSTOM.of(predicate)).peek(maxSize)
    .orElse(null);
CraftBookPlugin.spongeInst().getLogger().info("Found item: " + itemStack);
```

```
[21:29:02 INFO] [craftbook]: Found item: 4xitem.swordDiamond@1
[21:29:02 INFO] [craftbook]: Found item: 3xitem.swordDiamond@0
[21:29:02 INFO] [craftbook]: Found item: 2xitem.swordDiamond@3
[21:29:02 INFO] [craftbook]: Found item: 1xitem.swordDiamond@2
```

The chests actual contents were, in order: a diamond sword with damage 1, diamond sword with damage 0, diamond sword with damage 3, diamond sword with damage 2.
I also thought that sponge prevented you from creating item stacks with quantity above their max stack size, but as shown above that doesn't seem to be the case.
This is pretty bad as my plugin relies on sponge reporting the inventory contents correctly.
I am not sure if this happens in Api-8 or not.

**Comment by Faithcaio** [comment]
Sponge does not prevent you from creating oversized stacks.
Its the vanilla inventories that wont accept them. 
As such when offering a stack of 5 diamond swords to a normal vanilla inventory it will fill up 5 slots.
Modded inventories could choose to accept such stacks.

The logic for `peek(limit)` and `poll(limit)` only check if the items peeked/polled are the same `ItemType` in API7.
I agree that this felt wrong but changing it now in API7 is too late as plugins may rely on that behavior and there are ways around the issue.

The variant `peek(limit)` got removed in API8 as it was redundant.
You are supposed to query for what you want and then call `totalItems()` (API7) `totalQuantity()` (API8).
The variant `poll(limit)` in API8 now checks if the items are equal except for quantity.

Not quite sure what you are trying to do but if you 
use `peek(maxSize)` and then `poll(maxSize)` it will remove the stacks.
Alternatively using `peek()` without limit only returns a single slot regardless of stacksize.
Finally you could query again for the exact stack.
