### ISSUE TITLE
Error when serializing a class with annotation @ConfigSerializable.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/Sponge#3450]
**I am currently running**
- SpongeVanilla version:  1.16.5-8.0.0-RC724
- Java version:  OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
- Operating System: ArchLinux

**Issue Description**
Sponge tries to serialize all objects, and not just those that are marked with an annotation @Setting.

**Comment by dualspiral** [comment]
That is correct, and intended behaviour for Configurate 4.

You can either:

* Mark all fields you do not want serailised with the `transient` keyword ([see the example here](https://github.com/SpongePowered/Configurate/wiki/Object-Mapper#bringing-it-all-together))
* Use a custom `ObjectMapper.Factory` with [`NodeResolver.onlyWithSetting()`](https://configurate.aoeu.xyz/4.1.0/apidocs/org/spongepowered/configurate/objectmapping/meta/NodeResolver.html#onlyWithSetting()), so something like

```java
// create your factory
final ObjectMapper.Factory factory = ObjectMapper.factoryBuilder().addNodeResolver(NodeResolver.onlyWithSetting()).build();

// get your preferred defaults from here, this assumes Configurate defaults - you may want Sponge defaults
final TypeSerializerCollection child = TypeSerializerCollection.defaults().childBuilder().registerAnnotatedObjects(factory).build();

// register it in a new ConfigurationOptions based on the defaults - again, you might want different option defaults
final ConfigurationOptions options = ConfigurationOptions.defaults().serializers(child).build();

// create your loader with these options
final HoconConfigurationLoader loader = HoconConfigurationLoader.builder().defaultOptions(options)...build();
```

(There are other ways to do it, this is just the one that came to me first)
