### ISSUE TITLE
Another API 8 Chunk issue

### ISSUE THREAD

**Issue by mosemister** [SpongePowered/Sponge#3478]
**I am currently running**

- SpongeVanilla version: 8.0.0 SNAPSHOT - Latest as of 18/July - 10:16 British Time
- Java version: 16.0.1 2021-04-20
- Operating System: Win 10 Build 19043.1110

- Plugins/Mods:
1 custom plugin

**Issue Description**
Crash when calling specific function:

```
java.lang.AbstractMethodError: Receiver class net.minecraft.world.level.chunk.LevelChunk does not define or inherit an implementation of the resolved method 'abstract java.util.Collection entities(org.spongepowered.api.util.AABB, java.util.function.Predicate)' of interface org.spongepowered.api.world.volume.entity.EntityVolume.
        at org.spongepowered.api.world.volume.entity.EntityVolume.entities(EntityVolume.java:86)
```

```java
Chunk chunk;
AABB bounds = AABB.of(chunk.blockMin(), chunk.blockMax());
return chunk.entities(bounds);
```

**Comment by dualspiral** [comment]
I think `LevelChunk` has a fair few of these methods that aren't implemented, so I'll be just checking all of them.
