### ISSUE TITLE
Setting custom stack on pickup event breaks dropping items.

### ISSUE THREAD

**Issue by DrZoddiak** [SpongePowered/Sponge#3479]
**I am currently running**

- SpongeForge version: 
- SpongeVanilla version: cd9daca5b9
- Java version: JVM: 16.0.1/64-bit (AdoptOpenJDK)
- Operating System: OS: Windows 10/10.0 (amd64)

- Plugins/Mods: Spotlin, Soulbound

**Issue Description**
When using `ChangeInventoryEvent.Pickup.Pre` it has a function of `setCustom()`
Using this causes dropping items to always instant pickup.

This is a quick test 
https://gist.github.com/b250ac23954c6fbd049b4fca08cf7927

To replicate:
1) Throw non-cake-item out of inventory
2) Receive cake instantly.

While this seems ideal; receiving cake, It can get a bit messy.

To note, Gabi pointed me toward a branch working on inventory stuffs, it may be fixed there, but I was unable to test on the branch.
https://github.com/SpongePowered/Sponge/tree/api8/inventory-transactions

**Comment by Faithcaio** [comment]
Fixed in my branch. vanilla had moved the check for pickupdelay after our injection for the pickup pre-event
