### ISSUE TITLE
MySQL Connection. Driver not found. Java 16.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/Sponge#3487]
**I am currently running**
- SpongeVanilla version: 1.16.5-8.0.0-RC787
- Java version:  OpenJDK 16
- Operating System: Arch

**Issue Description**
I propose to add a library to create connections with MySQL. I know you tell me about the presence of HicariCP and creating a connection through the Sponge API, but I already checked it and I can say that it does not work. I get a message about the lack of driver to create a connection. I added the library(Connector/J 8.0.26) myself and everything started to work.
There are 2 variants. I think you choose which better.
https://downloads.mariadb.com/Connectors/java/  <- I have not tested this library.
https://dev.mysql.com/downloads/connector/j/  <- Works fine.

[My libraries.json](https://github.com/SpongePowered/Sponge/files/6886615/libraries.json.txt). See line 46. It works. Connector/J 8.0.26

**Comment by Zidane** [comment]
Sponge does not ship the SQL drivers. We do ship the connection pool (Hikari) but you will need to include the relevant drivers in your plugin.

This is our stance _today_. We are looking into other ways to solve this issue. Namely the fact that our drivers tend to go out of date and people want to use newer ones which by doing so breaks other plugins that relied on behaviors of older ones.

**Comment by Zidane** [comment]
To be clear, the driver that is there I believe is coming from another lib unless someone missed one when removing them from the buildscripts.

**Comment by SawFowl** [comment]
Do you propose to add a library for each plugin that you need to connect to MySQL? Without a driver, the connection is not possible, but there is no driver for the current time. If you add a driver to each plugin, you will get a bunch of same type libraries, and it is bad.

**Comment by Zidane** [comment]
@SawFowl 

We are aware of this. We are attempting to determine the best course of action here, as I stated above this is what is going on today. Not what will be the official stance in the future.

**Comment by SawFowl** [comment]
I hope that you will solve this problem before the release. Since without this, many plugins will not work. For example, [TotalEconomy](https://github.com/ericgrandt/TotalEconomy).
