### ISSUE TITLE
Fatal server lag when using TNT and Physics mod (SF 1.16.5)

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/Sponge#3517]
**I am currently running**
    spongeforge-1.16.5-36.2.1-8.0.0-RC878-universal
    forge-1.16.5-36.2.2
    java version 1.8.0_301 by Oracle
    Operating System: Windows 10.0.19042

- Plugins/Mods:
    physics-mod-1.3.4_forge

**Issue Description**
The server goes boom when TNT explodes. I set some off in the nether and got a nice crash log for my efforts.

https://www.dropbox.com/s/afkht5mfwgi84yl/latestSFcrash.log

**Comment by Zidane** [comment]
@Inscrutable 

We need a new log posted (that isn't dropbox). Use gist.github.com

**Comment by Inscrutable** [comment]
[latestSFcrash.log](https://github.com/SpongePowered/Sponge/files/7834284/latestSFcrash.log)

**Comment by gabizou** [comment]
> [02Sep2021 20:14:50.481] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/H:/MINECRAFT/SpongeTest/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER


Looks like mixing is out dated, give a newer forge version an install and make sure to delete mixing versions pre 0.8.4 and report back?

**Comment by Inscrutable** [comment]
OK, I tested this again using forge-1.16.5-36.2.23 and spongeforge-1.16.5-36.2.5-8.0.0-RC1031-universal. 
No specific errors crop up that refer to Sponge this time, but there is a big caveat:
If you use TNT in the nether, SpongeForge will cause server-killing lag. The watchdog shuts it down - and this only happens when SpongeForge is present. There's some lag, but not total client-freezing server paralysis. 
[Physics_vs_Sponge2.log](https://github.com/SpongePowered/Sponge/files/7834835/Physics_vs_Sponge2.log)

**Comment by Inscrutable** [comment]
More testing, Bad News. I can't even get a new world to load now. 
`Description: Exception initializing world 'minecraft:overworld'
java.lang.IllegalStateException: Should be within a PhaseState to record a transaction!`
Using forge 36.2.26, physics-mod-2.6.7-mc-1.16.5-forge, and spongeforge-1.16.5-36.2.5-8.1.0-RC0-universal (built from PR #3844 ).
Client Log: https://gist.github.com/Inscrutable/da3630489921a6bdf9dacec7ad86daee

EDIT: It seems SpongeForge crashes the client on it's very own at the moment, so I have to try this on a server...

**Comment by Inscrutable** [comment]
Update 2: On a server, it now works. Case closed. SpongeForge, on the other hand, should not crash the client...
