### ISSUE TITLE
Transaction Log Warning + Exception on Executing /clear

### ISSUE THREAD

**Issue by WillBAnders** [SpongePowered/Sponge#3519]
**I am currently running**
- SpongeForge version: `N/A`
- SpongeVanilla version: `1.16.5-8.0.0-RC876`
- Java version:  `16`
- Operating System: `Windows 10`

**Issue Description**

Executing `/clear` diplays `WARN: Logged transaction without event transaction!` followed by the exception `java.lang.Exception: null at ... TransactionalCaptureSupplier.logTransaction`. The command itself still works.

 - [Stacktrace](https://gist.github.com/WillBAnders/2fdf636d086f9f5c38e7a141eef2bcdd)

**Comment by Faithcaio** [comment]
Note that if this kind of warning with exception shows up it is only an issue with Sponge not being able to create the appropriate event. (In this case an optional crafting preview event as `/clear` can also remove items from the 2x2 crafting grid)
The original inventory change is never affected by this.
