### ISSUE TITLE
Tinkers Construct slot transaction spam with SpongeForge (SF 1.16.5)

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/Sponge#3527]
**I am currently running**
    spongeforge-1.16.5-36.2.1-8.0.0-RC893-universal
    forge-1.16.5-36.2.4
    java version 1.8.0_301 by Oracle
    Operating System: Windows 10.0.19042

- Plugins/Mods:
    Mantle-1.16.5-1.6.123
    TConstruct-1.16.5-3.1.2.265
    (these are the latest builds for 1.16.5)

**Issue Description** (Updated)
    <s>Two problems come up, one of them fatal.</s>
    (1) The warning `Logged slot transactions without event!` appears on login and frequently thereafter.
   <s>(2) When I tried to interact with the connected inventories of TiC (Storage chests, TiC Anvil, Tool Forge etc), the server dies after a cascade of phase tracker spam. The meat seems to be `Unknown inventory slimeknights.tconstruct.tables.tileentity.table.crafting.LazyResultInventory report this to Sponge`</s>

[Sponge_TIC.log](https://github.com/SpongePowered/Sponge/files/7134533/Sponge_TIC.log)

**Comment by Faithcaio** [comment]
2: https://github.com/SpongePowered/Sponge/commit/c8f4238aff612890ceb9201f3adeb2c7307c0f6e might fix it

**Comment by Inscrutable** [comment]
I tried `spongeforge-1.16.5-36.2.1-8.0.0-RC895-universal` and it no longer crashes, issue (2) above is fixed. Things can now be crafted in the TiC inventories, and you can swap between them. The smelter isn't functional though (it says too cold?).
Still getting a lot of `Logged transaction without event transaction!` stuff.

**Comment by Gregorsharpe** [comment]
I've observed a similar issue with spongeforge-1.16.5-36.2.5-8.0.0-RC1100-universal and the Create mod, attempting to place a filter object into any of the filter slots log-spams lines related to `Logged transaction without event transaction!` and blocks the player from applying any of the filters. Attaching the log [here](https://ghostbin.com/uvCkm).

**Comment by ShunL12324** [comment]
Same issue when opening the GUI of [AE2](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)'s drive
[log](https://gist.github.com/Eric-liucn/44730cc3794ebcd3bdc2c13dd15df099)
Using SpongeForge RC1100
Only AE2, luckperms installed

**Comment by Faithcaio** [comment]
see https://github.com/SpongePowered/Sponge/issues/3680
