### ISSUE TITLE
Wyrmroost + SpongeForge calls client class on server (SF 1.16.5)

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/Sponge#3532]
**I am currently running**
spongeforge-1.16.5-36.2.1-8.0.0-RC896-universal
forge-1.16.5-36.2.4
java version 1.8.0_301 by Oracle
Operating System: Windows 10.0.19042

- Plugins/Mods:
StorageDrawers-1.16.3-8.2.2
Wyrmroost-1.16.3-1.2.11

**Issue Description**
When I log in and try to spawn any kind of dragon from Wyrmroost, I get kicked and can't login again.
The server throws a dire looking error (and this problem only happens when SpongeForge is present):
(1) `An error occurred building event handler - java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER`

Note: I disabled the entity bounding box limit in the sponge config for these tests.

[WyrmroostSponge2.log](https://github.com/SpongePowered/Sponge/files/7147647/WyrmroostSponge2.log)

**Comment by gabizou** [comment]
Care to try this [special build](https://github.com/SpongePowered/Sponge/suites/5163966667/artifacts/156362790) built from [this PR](https://github.com/SpongePowered/Sponge/pull/3619)? I believe it'll solve this problem (and the 4 other tickets related to this one).

**Comment by Inscrutable** [comment]
Sorry, no such luck, It goes kaboom in a spectacular fashion, and won't start at all. 
`java.lang.StringIndexOutOfBoundsException: String index out of range: 0` seems to be at the core of it.
I'm running Eclipse Temurin JRE 8 v 312, and Forge 1.16.5 36.2.26 this time, but that shouldn't affect things.

[SpongeFallDownGoBoom.log](https://github.com/SpongePowered/Sponge/files/8009529/SpongeFallDownGoBoom.log)

**Comment by gabizou** [comment]
Try with [this build](https://github.com/SpongePowered/Sponge/suites/5195843733/artifacts/158428511) built from the same PR.

**Comment by Inscrutable** [comment]
100% functional. Well done, it works!

**Comment by gabizou** [comment]
Fixed with https://github.com/SpongePowered/Sponge/pull/3619
