### ISSUE TITLE
Blocks not syncing between Server and Client

### ISSUE THREAD

**Issue by Cleardragonf** [SpongePowered/Sponge#3533]
**I am currently running**

- SpongeForge version: 1.16.5-36.2.1-8.0.0-RC895
- Java version: 11
- Operating System: Windows 10

- Plugins/Mods: Tinkers Construct, Carryon, Mantle, ProjectE

**When a player is trying to break a block it 'appears' on the client side to be broken, but nothing drops...and the block is technically still there and won't allow the player through...**

https://gist.github.com/Cleardragonf/a506f8efeafb306d560990c9576dde31

**Comment by gabizou** [comment]
Already fixed in RC896+
