### ISSUE TITLE
Exception Exiting Phase crash from AlexsMobs (SF 1.16.5)

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/Sponge#3535]
**I am currently running**
-    spongeforge-1.16.5-36.2.1-8.0.0-RC898-universal
-    forge-1.16.5-36.2.4
-    java version 1.8.0_301 by Oracle
-    Operating System: Windows 10.0.19042

**Plugins/Mods**:
-    alexsmobs-1.10.1
-    citadel-1.7.1-1.16.5 (dependency of above)
-    smallships-1.16.5-1.8.5

**Issue Description**
After I logged in, the server seemed to be working OK. I broke some grass and fed some crows some seeds, and then it fell over.

[Alexlatest.log](https://github.com/SpongePowered/Sponge/files/7171039/Alexlatest.log)

**Comment by Switch-Back18** [comment]
How did you get spongeforge 1.16 ?

**Comment by Inscrutable** [comment]
@MathisSkate this is really not the place to ask, as your question is unrelated to the issue. Please refrain in future.
HOWEVER, for unstable builds of SpongeForge for 1.16, look at the repository at https://repo.spongepowered.org/#browse/search=attributes.maven2.artifactId%3Dspongeforge

**Comment by Inscrutable** [comment]
I can no longer reproduce this error with latest Forge, SpongeForge, and Mods. 
I re-tested this using Forgeforge-1.16.5-36.2.39, Spongeforge-1.16.5-36.2.5-8.1.0-RC1313-universal, and the latest versions of Alex's Mobs and Citadel (alexsmobs-1.12.1 and citadel-1.8.1-1.16.5).  I traveled to every dimension and spawned every mob the mod had to offer, died many times, and had no crashes or serious errors. Just a few ignored slot transactions, which aren't game breaking. This can probably be closed now.
