### ISSUE TITLE
[SOLVED] Server crashes and other nuisances

### ISSUE THREAD

**Issue by Billabonga** [SpongePowered/Sponge#354]
Hi,

I had server crashes when using the fishing rod. Furthermore, exp points disappear, gamemode can't be set to creative, and a plugin - toomanyitems - gets disabled.

http://pastebin.com/embed_js.php?i=Kjrf8BNW

http://pastebin.com/embed_js.php?i=3WH8ES9x

**Comment by Zidane** [comment]
I've never encountered any of these issues. You need to zip up your world and upload it. You can try testing without WorldEdit for Forge. I also don't see your plugin toomanyitems at all in that log.

**Comment by JBYoshi** [comment]
@Zidane I believe TooManyItems is client-side only. It uses commands for stuff that needs the server.

**Comment by ST-DDT** [comment]
> java.lang.OutOfMemoryError: Java heap space

Maybe your server/client is running with too less memory. 

> [19:29:50] [Client thread/INFO]: Created: 512x512 textures-atlas

Your texture pack? 512x512 will probably take a lot space

**Comment by JBYoshi** [comment]
@ST-DDT The textures-atlas is a combination of all the block/item textures, not an individual texture.

**Comment by Billabonga** [comment]
I don't use a texture pack - allocated mem 1 gb - , and I had absolutely no issues using 1499/577 and earlier - only later versions cause grief. :(  It also makes no difference when I remove toomanyitems.

**Comment by Billabonga** [comment]
I started a new world and the server crashed again twice using a fishing rod and setting a door. 

http://pastebin.com/embed_js.php?i=jATB9XKV"></script>
http://pastebin.com/embed_js.php?i=t1xYm0fv"></script>

Forge 1515 and Sponge 1515/671

I am a bit lost here .......

**Comment by Zidane** [comment]
@Billabonga 

Should have a fix for you shortly

**Comment by Zidane** [comment]
@Billabonga 

Can you zip up your save and put it on dropbox and let me grab it?

**Comment by Zidane** [comment]
@Billabonga 

Wait about 30 or so mins and give the latest Sponge a try. Issue will be resolved.

**Comment by Billabonga** [comment]
@Zidane Thanks a lot for your quick response and your effort. I very much appreciate it and everything is hunkydory.

BTW For future reference: what's or where do I find that dropbox you were referring to above

**Comment by Zidane** [comment]
https://www.dropbox.com/

Basically lets you upload files and share them to others. Handy for passing off a save to a dev ;).
