### ISSUE TITLE
Explosion Builder bug API8

### ISSUE THREAD

**Issue by DrZoddiak** [SpongePowered/Sponge#3541]
**I am currently running**

    Minecraft: 1.16.5
    SpongeAPI: 8.0.0-SNAPSHOT
    Sponge: 1.16.5-8.0.0-SNAPSHOT
    SpongeVanilla: 1.16.5-8.0.0-RC0
    JVM: 16.0.1/64-bit (AdoptOpenJDK)
    OS: Windows 10/10.0 (amd64)

- Plugins/Mods:

**Issue Description**
https://github.com/SpongePowered/Sponge/blob/65d744fe1befe3a1a8b6a5e863a5321642ec9d86/src/main/java/org/spongepowered/common/world/SpongeExplosionBuilder.java#L153

The line should read something like
`this.canCauseFire, this.shouldBreakBlocks ? net.minecraft.world.level.Explosion.BlockInteraction.DESTROY : net.minecraft.world.level.Explosion.BlockInteraction.NONE);`

This checks if the Explosion is supposed to smoke, and then decides to destroy blocks based off of that.

This is in theory a 1 line change, but the only reason I didn't make a PR is that I don't know what to do with the smoke option. So I'm leaving it up to you.

https://gist.github.com/DrZoddiak/09285690b6b6dddf95d826ebb292b7ae

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/Sponge/commit/79d85eba5a6f367f4cb3aa70b5b824361d3e9d31
