### ISSUE TITLE
Exception in server loop

### ISSUE THREAD

**Issue by ConfusedMapper** [SpongePowered/Sponge#355]
Hey sorry if this isn't the right place but I need help. Trying to set up just a basic server for myself so I can get some plugins going, but the server crashes every time. Crash log here: http://pastebin.com/rULg7MLM

Any help at all would be appreciated, thanks!

**Comment by JBYoshi** [comment]
The crash report mentions being unable to find interface that was renamed quite some time ago. Make sure you have the latest version (build 666 at the moment).

**Comment by Deamon5550** [comment]
The exception is because he is using VoxelSniper which is not updated for the event changes yet.
