### ISSUE TITLE
Inventory changes during Join-Event produce warning and no events

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#3552]
**I am currently running**
- **Minecraft:** 1.16.5
- **SpongeAPI:** 8.0.0-SNAPSHOT
- **Sponge:** 1.16.5-8.0.0-SNAPSHOT
- **SpongeVanilla:** 1.16.5-8.0.0-RC932
- **JVM:** 16.0.1/64-bit (Oracle Corporation)
- **OS:** Windows 10/10.0 (amd64)
- **Plugins/Mods:** This testplugin: https://github.com/TBlueF/SpongeTests/tree/test/inventory-events

**Issue Description**
Changing the players Inventory using `inventory().offer(...)` during the event `ServerSideConnectionEvent.Join` raises the following warning in the console:
```
[Server thread/WARN] [sponge]: Ignoring slot transaction on InventoryMenu during EntityTickContext. SlotTransaction{slot=SlotAdapter[ordinal=37], original=SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}, default=SpongeItemStackSnapshot{itemType=minecraft:iron_pickaxe, quantity=1}, custom=Optional.empty, valid=true}
```

Additionally, changing the players Inventory during both `ServerSideConnectionEvent.Login` and `ServerSideConnectionEvent.Join`, does not trigger any `InventoryChangeEvent`.

Using the same method to change the players Inventory during a Command-Execution does none of the above issues.

The code to reproduce this issue can be found here:
https://github.com/TBlueF/SpongeTests/blob/test/inventory-events/src/main/java/de/bluecolored/spongetest/testplugin/Plugin.java

**Comment by Faithcaio** [comment]
With a few exceptions we currently only fire events for inventories that are synced to the client.
As such the offline User inventory wont fire events currently.

While we still cannot associate the change directly to the plugin causing it, the change during the Join event now causes an inventory event. (which gets rid of the warning for this case)
