### ISSUE TITLE
Spawning an entity on chunk load causes deadlock

### ISSUE THREAD

**Issue by masagameplay** [SpongePowered/Sponge#3555]
**I am currently running**
    Minecraft: 1.16.5
    SpongeAPI: 8.0.0-SNAPSHOT
    Sponge: 1.16.5-8.0.0-SNAPSHOT
    SpongeVanilla: 1.16.5-8.0.0-RC935
    JVM: 16.0.1/64-bit (Oracle Corporation)
    OS: Windows 10/10.0 (amd64)

- Plugins/Mods:
- Custom plugin that spawns a villager on chunk load

**Issue Description**

```
@Listener
public void onChunkLoad(final ChunkEvent.Load event) {
    ServerLocation location = ServerLocation.of(event.worldKey(), 0, 100, 0);
    Villager villager = location.createEntity(EntityTypes.VILLAGER.get());
    location.spawnEntity(villager);
}
```
Teleport to 0 100 0 -> crash

Crash log https://gist.github.com/masagameplay/d97f7260904fe6c67a4d0b9ba8ddd1a1

**Comment by gabizou** [comment]
I mean, Chunks are loaded asynchronously, so you're trying to perform world modifications on a chunk asynchronously here. The API docs should mention that ChunkEvent.Load is asynchronous so world modifications should be scheduled via a Task.
