### ISSUE TITLE
Crash on start up due to mixins

### ISSUE THREAD

**Issue by BronzeS8** [SpongePowered/Sponge#3569]
**I am currently running**[message.txt](https://github.com/SpongePowered/Sponge/files/7727435/message.txt)
- SpongeForge version: spongeforge-1.16.5-36.2.5-8.0.0-RC962-universal.jar
- SpongeVanilla version: 
- Java version: 8
- Operating System: MacOS

- Plugins/Mods:
Spongeforge
AI improvements
AIOT Botania
Alex's Mobs
Apotheosis
Aquaculture 2
Ars Nouveau
Astral Sorcery 
AttributeFix
Baubles - Reborn?
Better third person
Better End
Biomes O'plenty
Blood Magic
Blue Skies
Bookshelf
Botania 
Botany Pots
Botany Trees
CaveBiomeAPI
Chipped
Chunky Pregenerator
Citadel
Create
Create Crafts & Additions
Curios API
Darker Depths
Decorative Blocks
Decorative Blocks modded compat
Druidcraft
Dungeon Crawl
Dungeons Enhanced 
Dungeon Gear
Dungeon Mobs
Dungeon Plus
Dynamic Surroundings 
Eidolon 
Eidolon's Hexblades 
Enhanced Celestials
Escencia
Fairy Lights
Farmers Delight
Farmers Delight Compats
Farmers Delight Intergration
Floocraft
Flywheel
Gateways to Eternity
GeckoLib
Goblin Traders
Hals Exploration Mod
Hexerei 
Ice and Fire: Dragons
Journey Map
JEI
Kobolds
LibX
Ma Essentials
MarbleGate's Exotic Enchantment: Flowing Agony
Mushroom Quest
Mythic Botany
Natures Aura
Nether's Exoticism
NoCube's Sea Dwellers
Obfuscate 
ObserverLib
Oh The Biomes You'll Go
Patchouli 
Placebo
Sea And Prehistory 
Skin Layers 3D (Forge)
Skin Swapper
Sky Village
Sophisticated backpacks
Structure GEI API
The Twilight Forest
Tome of Blood
Waystones
Whisperwoods
Xenoclus 2
Yungs API (Forge)
Yungs Better Caves
Yungs Better Mineshafts

**Issue Description**
When loading server with modpack and sponge forge, it crashes on start up. I believe this because the mixins don't seem to work when running with sponge forge. I tried this with dungeon gear, and when removed dungeon gear I got the error with Botania

[message.txt](https://github.com/SpongePowered/Sponge/files/7727435/message.txt)

**Comment by Zidane** [comment]
Closing as no long has been provided. Re-open when you have a log to post and we'll look into it.

**Comment by BronzeS8** [comment]
Sorry I might be a bit slow but what is a log exactly? I thought the thingy I posted in the top right was a log, here: https://github.com/SpongePowered/Sponge/files/7727435/message.txt
