### ISSUE TITLE
PositionOutOfBoundsException

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#357]
I had this Crash now twice: http://pastebin.com/2ErVndLE
I know its not the latest Sponge Version, but as i am not exactly sure what it caused i cant reproduce it really.
I updated my Sponge Version now and i'll tell you if the crash persists.
Maybe you can figure something with that Stacktrace :)
As far as i can tell none of my Plugins are involved.

**Comment by Zidane** [comment]
The error is pretty clear...something is feeding -1 to the y. Test without plugins and add them back slowly.

**Comment by JBYoshi** [comment]
@TBlueF 

```
at net.minecraft.world.gen.feature.WorldGenBigTree.func_180709_b(WorldGenBigTree.java:307)
at net.minecraft.block.BlockSapling.func_176476_e(BlockSapling.java:168)
```

It appears to be caused by a thick (2-block-wide trunk) tree growing.

**Comment by TBlueF** [comment]
Ok, i tried a little and i managed to reproduce it with the latest Sponge and the correct Forge Version, no other mods/plugins on a fresh server.

I loaded the new server, joined and went to the end. Then i placed a Watersource so, that it flew down into the void. As soon as it reached y0 this Crash occured: http://pastebin.com/45AXznRr

I am happy to say: Not my fault :)

**Comment by JBYoshi** [comment]
I think the root problem is an inconsistency between Minecraft and Sponge behavior. When asked to get the state of an out-of-bounds block position, Minecraft just sends back air, but Sponge throws an exception. When asked to set the state of an out-of-bounds block position, Minecraft does nothing, but Sponge throws an exception.

**Comment by TBlueF** [comment]
Maybe [this](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/event/block/MixinEventNotifyNeighborBlock.java#L97) is the problem?
Because its always a BlockNotifyEvent on a neighbor Block that is outside of Bounds thats causing the Crash.

*e.g. 
[00:37:39] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'setblock 0* **255** *0 log' for source EntityPlayerMP['TBlueF'/256, l='world', x=0,82, y=254,00, z=2,18]: Position is out of bounds: expected in range (-30000000, 0, -30000000) to (29999999, 255, 29999999) but got (0,* **256***, 0)*

*at net.minecraftforge.event.world.BlockEvent$NeighborNotifyEvent .createSpongeEventData(BlockEvent.java:97)*
