### ISSUE TITLE
SpongeForge (16.5-36.2.5-8.0.0-RC975) has fatal errors with Twilight Forest mod (1.16.5-4.0.870)

### ISSUE THREAD

**Issue by andersonaddo** [SpongePowered/Sponge#3574]
**I am currently running**

- SpongeForge version: 16.5-36.2.5-8.0.0-RC975
- Java version: 1.8.0_311
- Operating System: Oracle Cloud VM (Oracle-Linux-7.9-aarch64-2021.12.08.0)
 
I'm not using the latest version for SpongeForge for 1.16.5 (RC1000 )because it has login errors, and the one before that doesn't allow players to pick up items for some reason,

- Plugins/Mods:
- BiomesOPlenty-1.16.5-13.1.0.477-universal.jar  
- journeymap-1.16.5-5.7.3.jar  
- spongeforge-1.16.5-36.2.5-8.0.0-RC975-universal.jar
- jei-1.16.5-7.7.1.138.jar  
- twilightforest-1.16.5-4.0.870-universal.jar

**Issue Description**
I'm trying to make a world by running my forge jar. 
It runs normally, but the initial logs have a lot of fatal errors: https://pastebin.com/mTAe8vUS
The issue seems to be stemming from a problem with TwilightForest. Strangely, TwilightForest still _seems_ fuctional, like I can create the portal and enter the forest.

I'm making this issue here since these errors don't exist without SpongeForge installed.

**Comment by gabizou** [comment]
Care to try this [special build](https://github.com/SpongePowered/Sponge/suites/5163966667/artifacts/156362790) built from [this PR](https://github.com/SpongePowered/Sponge/pull/3619)? I believe it'll solve this problem (and the 4 other tickets related to this one).

**Comment by gabizou** [comment]
Fixed by https://github.com/SpongePowered/Sponge/pull/3619
