### ISSUE TITLE
Server Crash when placing down LittleTiles

### ISSUE THREAD

**Issue by Vulant** [SpongePowered/Sponge#3580]
**I am currently running**

- SpongeForge version: SpongeForge 1.12.2-2838-7.4.7
- Forge 2860

- Plugins/Mods: https://pastebin.com/icZNwwYC

**Issue Description**
Server is crashing when placing down LittleTiles, specifically items that are in recipe format. I suspect it has something to do with UniverseGuard2's region protection, but I'm not too entirely sure. The crash log mentions something only from sponge and about tileentities which LittleTiles is. Sorry for being so vague, I truly do not understand the nature of this crash or what the crash log is trying to tell me.

Here is the crashlog: https://pastebin.com/vpWBdHCQ

Following instructions from https://docs.spongepowered.org/stable/en/server/spongineer/incompatible.html#old-mixins,
I renamed SpongeForge with the aaa_ prefix, changed settings in FoamFix and made sure my JEID was up to date. Still having the same errors, and it turns out this issue is not limited to LittleTiles. It seems to be some sort of conflict with my protection plugin UniverseGuard2 where I have a region in which players are not allowed to place things down. The behavior now is that players can bypass this protection rule and place things down while the plugin tells them they don't have permission, and there's a bunch of errors in the console talking about incorrect phase.

Here is the error: https://pastebin.com/Ky3ZaDa0

**Comment by gabizou** [comment]
re-run the server with `-Dmixin.debug.export=true` and upload a zip of the `<gamedir>/.mixin.out` folder.

**Comment by Vulant** [comment]
[mixin.out.zip](https://github.com/SpongePowered/Sponge/files/7834610/mixin.out.zip)

Here is the .mixin.out folder, thank you!!

**Comment by gabizou** [comment]
That doesn't seem to have run exporting, mind rerunning and upload the logs as well?

**Comment by Vulant** [comment]
Apologies, I had to contact my server host to add the parameters it seems lol. Hopefully this time it worked?
[mixin.out2.zip](https://github.com/SpongePowered/Sponge/files/7843411/mixin.out2.zip)
