### ISSUE TITLE
World UUID's don't persist over a server restart

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#3581]
**I am currently running**
- **SpongeForge** version: **1.16.5-36.2.5-8.0.0-RC1030**
- Java version: **11.0.12/64-bit (Oracle Corporation)**
- Operating System: **Windows 10/10.0 (amd64)**
- Plugins/Mods:
  - [This](https://github.com/TBlueF/SpongeTests/tree/test/world-uuid) test-plugin

**Scenario**
Starting and stopping the server twice using a test-plugin that outputs the UUID of the main-world.

E.g.:
```java
logger.info(evt.engine().worldManager().defaultWorld().uniqueId());
```

**Expected result**
The UUID of the world is the same each time the server get's started

**Actual result**
The UUID changes each time the server restarts

**Additional thoughts**
I think that this is only happening in the Forge-implementation for Sponge, not in the Vanilla implementation.
Upon comparing the `level.dat` of a world from SpongeVanilla and SpongeForge, the UUID seems to be completely missing on forge worlds:

SpongeForge:
![image](https://user-images.githubusercontent.com/10765470/148706745-f4f2edb9-0aed-458f-8692-44b8fb181166.png)
vs SpongeVanilla
![image](https://user-images.githubusercontent.com/10765470/148706788-f4b9aee5-f91e-4c44-b857-3dab3e8c35e0.png)

**Comment by gabizou** [comment]
Might be related with #3624

**Comment by kencinder** [comment]
> Might be related with #3624

Nope, just tested with `spongeforge-1.16.5-36.2.5-8.0.0-RC1077` and at no point is any SpongeData present in level.dat. Clean test server, multiple restarts, SpongeData remains empty.
