### ISSUE TITLE
Spongeforge 1.16.5 and botania

### ISSUE THREAD

**Issue by avescarelo** [SpongePowered/Sponge#3587]
**I am currently running**

- SpongeForge version: 1.16.5-36.2.5-8.0.0-RC962 EXPERIMENTAL
- Forge version: 1.16.5 - 36.2.22
- Java version: build 1.8.0_312-8u312-b07-0ubuntu1~18.04-b07
- Operating System: Linux

**Issue Description**
If try to add Botania to the server, it crashes when loading. Without this mod - server working.

        log: https://gist.github.com/avescarelo/b2cc5bc5837524dbc44bcfc78f441e12

**Comment by gabizou** [comment]
This has been fixed on both sides (Botania has a fix, and SpongeForge RC1036+)
