### ISSUE TITLE
can some help me

### ISSUE THREAD

**Issue by LOLDERP** [SpongePowered/Sponge#359]
i keep get this error when i run sponge 
Information:Using javac 1.8.0_60 to compile java sources
Information:java: Errors occurred while compiling module 'Sponge'
Information:Modules "SpongeCommon", "Sponge", "SpongeAPI" were fully rebuilt due to project configuration/dependencies changes
Information:2015-10-04, 8:55 PM - Compilation completed with 14 errors and 5 warnings in 54s 84ms
/Users/derp/Sponge/SpongeCommon/SpongeAPI/src/main/java/org/spongepowered/api/data/value/immutable/ImmutableCollectionValue.java
Information:java: Some input files use unchecked or unsafe operations.
Information:java: Recompile with -Xlint:unchecked for details.
/Users/derp/Sponge/SpongeCommon/src/main/java/org/spongepowered/common/scoreboard/SpongeScoreboard.java
Warning:(189, 58) java: legacy() in org.spongepowered.api.text.Texts has been deprecated
Warning:(197, 65) java: legacy() in org.spongepowered.api.text.Texts has been deprecated
Warning:(198, 71) java: legacy() in org.spongepowered.api.text.Texts has been deprecated
/Users/derp/Sponge/SpongeCommon/src/main/java/org/spongepowered/common/mixin/core/scoreboard/MixinScoreboard.java
Warning:(178, 43) java: legacy() in org.spongepowered.api.text.Texts has been deprecated
Warning:(192, 50) java: legacy() in org.spongepowered.api.text.Texts has been deprecated
/Users/derp/Sponge/SpongeCommon/src/main/java/org/spongepowered/common/mixin/core/world/extent/MixinExtentViewTransform.java
Information:java: Some input files use unchecked or unsafe operations.
Information:java: Recompile with -Xlint:unchecked for details.
/Users/derp/Sponge/src/main/java/org/spongepowered/mod/mixin/core/world/MixinChunk.java
Error:(74, 20) java: cannot find symbol
  symbol:   variable captureBlockSnapshots
  location: variable worldIn of type net.minecraft.world.World
/Users/derp/Sponge/src/main/java/org/spongepowered/mod/mixin/entityactivation/MixinWorld.java
Error:(70, 76) java: cannot find symbol
  symbol:   method getPersistentChunks()
  location: class net.minecraft.world.World
/Users/derp/Sponge/src/main/java/org/spongepowered/mod/mixin/core/event/world/MixinEventWorldExplosion.java
Error:(71, 85) java: cannot find symbol
  symbol:   method getPosition()
  location: variable explosion of type net.minecraft.world.Explosion
/Users/derp/Sponge/src/main/java/org/spongepowered/mod/mixin/core/event/player/MixinEventPlayerHarvestBlock.java
Error:(78, 37) java: method canSilkHarvest in class net.minecraft.block.Block cannot be applied to given types;
  required: no arguments
  found: net.minecraft.world.World,net.minecraft.util.BlockPos,net.minecraft.block.state.IBlockState,net.minecraft.entity.player.EntityPlayer
  reason: actual and formal argument lists differ in length
Error:(83, 47) java: cannot find symbol
  symbol:   method getExpDrop(net.minecraft.world.World,net.minecraft.util.BlockPos,int)
  location: class net.minecraft.block.Block
Error:(197, 28) java: cannot find symbol
  symbol:   method getHarvestTool(net.minecraft.block.state.IBlockState)
  location: variable block of type net.minecraft.block.Block
Error:(202, 40) java: cannot find symbol
  symbol:   method getHarvestLevel(net.minecraft.item.ItemStack,java.lang.String)
  location: class net.minecraft.item.Item
Error:(207, 34) java: cannot find symbol
  symbol:   method getHarvestLevel(net.minecraft.block.state.IBlockState)
  location: variable block of type net.minecraft.block.Block
/Users/derp/Sponge/src/main/java/org/spongepowered/mod/mixin/core/entity/player/MixinEntityPlayerMP.java
Error:(54, 63) java: cannot find symbol
  symbol:   method channel()
  location: class net.minecraft.network.NetworkManager
/Users/derp/Sponge/src/main/java/org/spongepowered/mod/mixin/plugin/entityactivation/ActivationRange.java
Error:(85, 26) java: cannot find symbol
  symbol:   method isCreatureType(net.minecraft.entity.EnumCreatureType,boolean)
  location: variable entity of type net.minecraft.entity.Entity
Error:(87, 87) java: cannot find symbol
  symbol:   method isCreatureType(net.minecraft.entity.EnumCreatureType,boolean)
  location: variable entity of type net.minecraft.entity.Entity
Error:(88, 17) java: cannot find symbol
  symbol:   method isCreatureType(net.minecraft.entity.EnumCreatureType,boolean)
  location: variable entity of type net.minecraft.entity.Entity
Error:(90, 86) java: cannot find symbol
  symbol:   method isCreatureType(net.minecraft.entity.EnumCreatureType,boolean)
  location: variable entity of type net.minecraft.entity.Entity
Error:(92, 93) java: cannot find symbol
  symbol:   method isCreatureType(net.minecraft.entity.EnumCreatureType,boolean)
  location: variable entity of type net.minecraft.entity.Entity

**Comment by ZephireNZ** [comment]
I assume this was built through the IDE? There's currently a problem where the IDE puts the dependencies in the wrong order, see #353 too fix it.

Basically you need to move "SpongeCommon" to the very bottom of the dependency list in the module configuration for IntelliJ.
