### ISSUE TITLE
SpongeForge crashing with botania on startup

### ISSUE THREAD

**Issue by Chrisgoac** [SpongePowered/Sponge#3596]
**I am currently running**

- SpongeForge version: Latest version
- Forge version: 1.16.5-36.2.22
- Java version: openjdk version "11.0.13" 2021-10-19
- Operating System: Both, Windows and Linux

- Plugins/Mods:

**Issue Description**
When installing Botania on theserver with SpongeForge, it crashes.
Log: https://pastebin.com/EFb4K55z

**Comment by gabizou** [comment]
Closing as no response from OP.
