### ISSUE TITLE
Type 'interface org.spongepowered.api.effect.VanishState$Factory' has no factory registered!

### ISSUE THREAD

**Issue by masagameplay** [SpongePowered/Sponge#3599]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.0.0-RC1039

### Operating System

Windows 10

### Java Version

16.0.1

### Plugins/Mods

```shell
- A test plugin that does not do anything yet
```

### Describe the bug

After starting the server the console filled with the following `org.spongepowered.api.registry.TypeNotFoundException: Type 'interface org.spongepowered.api.effect.VanishState$Factory' has no factory registered!`

### Link to logs

https://paste.gg/p/anonymous/3e6a3f0036e64658953a0381fff39717

**Comment by dualspiral** [comment]
[That doesn't make much sense because it is registered](https://github.com/SpongePowered/Sponge/blob/api-8/src/main/java/org/spongepowered/common/registry/SpongeFactoryProvider.java#L282)...

**Comment by dualspiral** [comment]
Just to add to this, I spun up a server and walked around spawning entities, and got nothing like this at all. Why you'd get this confuses me, because the line of code I linked above was added at the same time as vanishstate became a thing. _Especially_ because you're running SV...

**Comment by gabizou** [comment]
One key factor here is that this isn't production, this is in-dev via SpongeGradle. Testing this in production hasn't had issues as such.

Having just reproduced a similar environment, I can't get the same error showing up. Please provide the --debug log from `runServer`

**Comment by gabizou** [comment]
Closing as no response given and haven't been able to reproduce this issue personally.
