### ISSUE TITLE
Bug World. Problems with generators worlds.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/Sponge#360]
Why all used generator OverWorld (Nether-type and THe-End-type)? Use Sponge build 686.
I tested. I removed the sponge. It was good.
Details in the video:
https://youtu.be/-0lDVSUWBPg

**Comment by simon816** [comment]
I couldn't reproduce this. Remove any plugins and see if it still doesn't work.
If not, generate a new world and try again

**Comment by Azatik** [comment]
@simon816 I left only a sponge. Problem still exists.
Screen (This Nether):
![2015-10-05_20 37 33](https://cloud.githubusercontent.com/assets/10154956/10285183/1dd8b970-6ba1-11e5-9dcd-3f1040eb7f91.png)

**Comment by Azatik** [comment]
This fault sponge. 100%. I now removed the sponge. It was good. Worlds generated good.
Screen (This Nether, Without sponge.):
![2015-10-05_20 54 13](https://cloud.githubusercontent.com/assets/10154956/10285662/4fa3c1fa-6ba3-11e5-9f9a-1320e5708051.png)

**Comment by TBlueF** [comment]
What forge Version? Your `allow-nether` setting is on `true` right?

**Comment by Azatik** [comment]
@TBlueF forge 1515, allow-nether=true.
Read my previous comment. The problem occurs after you install a sponge.

**Comment by simon816** [comment]
Make sure you are using Forge build 1515.

Create an empty directory and set up a Sponge server in there, see if the problem still persists.

**Comment by Zidane** [comment]
This issue is confirmed and we are looking into it.
