### ISSUE TITLE
DataProviderRegistrator does not deal with inheritance

### ISSUE THREAD

**Issue by aromaa** [SpongePowered/Sponge#3610]
### Affected Product(s)

SpongeVanilla

### Version

16.5-8.0.0-RC1055

### Operating System

-

### Java Version

-

### Plugins/Mods

```shell
-
```

### Describe the bug

When multiple targets register the same data key it results to inconsistent behavior where the implementation is randomly used between the registered targets. This can be observed with the armor stands `HEAD_ROTATION` key that is also implemented in the living entity which armor stand inherent from. When the key randomly decides to use the living entity implementation it leads to wrong behavior.

**Comment by gabizou** [comment]
I'd imagine something akin to Minecraft's ClassInheritanceMultimap to where the most specific providers are supplied as a higher priority than the least specific providers are given second. I don't know how easy this is to do off the top of my head, so I'm leaving it open for anyone wishing to contribute a solution.

**Comment by Faithcaio** [comment]
When there are multiple matching `DataProvider`s a `DelegateDataProvider` is created.
To fix this we would have to sort the providers list in it.
