### ISSUE TITLE
ClassCastException when beeing hit

### ISSUE THREAD

**Issue by Elikill58** [SpongePowered/Sponge#3617]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-RC1060

### Operating System

Windows

### Java Version

16

### Plugins/Mods

```shell
[]
```

### Describe the bug

With latest version (and it seems to appear with some old one), when I'm hit by entities (tested with Phantom and zombie) There is a ClassCastException

### Link to logs

https://gist.github.com/Elikill58/229df3101d881a583e3545ca56998b06

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/Sponge/commit/0e770d331553f06d345c0025ba436cf830676a1e
