### ISSUE TITLE
ClassCastException when trying to load the chunk 

### ISSUE THREAD

**Issue by realkarmakun** [SpongePowered/Sponge#3623]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.0.0-RC1062

### Operating System

Windows

### Java Version

16.0.1/64-bit (AdoptOpenJDK)

### Plugins/Mods

```shell
Just my plugin
```

### Describe the bug

I'm trying to iterate over all chunks in world. I've built list of pointers to the chunks but when trying to get them with following code, I get ClassCastException
```java
serverWorld.loadChunk(chunkPointer, true).ifPresent(worldChunk -> {
                logger.consoleInfo( "Chunks min, max: " + worldChunk.min() + worldChunk.max());
            });
```
Exception:
```
java.lang.ClassCastException: class net.minecraft.world.level.chunk.ProtoChunk cannot be cast to class org.spongepowered.api.world.chunk.WorldChunk (net.minecraft.world.level.chunk.ProtoChunk and org.spongepowered.api.world.chunk.WorldChunk are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @985696)
```

### Link to logs

https://paste.gg/p/anonymous/89e7b84f74f54ec381b8fb54c1a03fb2

**Comment by gabizou** [comment]
Not forgotten, just a rather complicated issue since I'm not most familiar with the chunk pipeline's semantics of when a chunk Is deemed ready and ensure the request is completed. I'm not sure why with the status flag being set that an impostor chunk is being returned....

**Comment by realkarmakun** [comment]
Is there any info I can help collect?
