### ISSUE TITLE
Performant Mod Incompatibility

### ISSUE THREAD

**Issue by DocterDum** [SpongePowered/Sponge#3630]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.0.0-RC1073-universal.jar

### Operating System

Windows

### Java Version

Adopt OpenJDK Hotspot 1.8.0_322

### Plugins/Mods

```shell
SpongeForge
Performant (performant-1.16.2-5-3.85m.jar)
Optionally: Not Enough Crashes (notenoughcrashes-4.1.4+1.16.5-forge.jar)
```

### Describe the bug

Originally discovered with not enough crashes -> Loads to menu but all characters are white squares
![unknown](https://user-images.githubusercontent.com/7615222/154009086-7a27f3c9-621d-48ba-88ad-2c8f5fb6d55a.png)
![unknown](https://user-images.githubusercontent.com/7615222/154009094-25db60b4-3e9b-465d-a55e-64484aa51b1e.png)

Testing without Not Enough Crashes caused the game to crash (Shocking isn't it), I have attached the logs from the crash below

### Link to logs

https://paste.ee/p/K5J7U

**Comment by gabizou** [comment]
Try this [build](https://github.com/SpongePowered/Sponge/suites/5341959552/artifacts/166929217) based off [the PR](https://github.com/SpongePowered/Sponge/actions/runs/1857636401)

**Comment by DocterDum** [comment]
That's fixed it, thanks for the awesome work!

**Comment by gabizou** [comment]
For reference, build `1.16.5-36.2.5-8.0.0-RC1079` has the fix, no need to use the specific build from the PR ;)
