### ISSUE TITLE
Mekanism Crash On Launch

### ISSUE THREAD

**Issue by DocterDum** [SpongePowered/Sponge#3631]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.0.0-RC1073-universal.jar

### Operating System

Windows

### Java Version

Adopt OpenJDK Hotspot 1.8.0_322

### Plugins/Mods

```shell
SpongeForge
Mekanism-1.16.5-10.1.1.456.jar (Latest)
```

### Describe the bug

When both Mekanism and SpongeForge are installed, Minecraft crashes on launch

[latest.log](https://github.com/mekanism/Mekanism/files/8066821/latest.log)
[debug.log](https://github.com/mekanism/Mekanism/files/8066822/debug.log)
[crash-2022-02-15_18.35.43-fml.txt](https://github.com/mekanism/Mekanism/files/8066824/crash-2022-02-15_18.35.43-fml.txt)

**Comment by DocterDum** [comment]
https://github.com/mekanism/Mekanism/issues/7411

**Comment by gabizou** [comment]
Mind giving this [test build](https://github.com/SpongePowered/Sponge/suites/5341842437/artifacts/166922365) a shot? It's built directly from the [commit](https://github.com/SpongePowered/Sponge/commit/5f7b4c58adf9103e17ae9b70a1774adeee9988b0) that should work around the above issue. If there are more exceptions, wouldn't mind taking a look at fixing those in the same PR.

**Comment by DocterDum** [comment]
Tested with that build and it's worked fine!

Thanks for the quick help :)
