### ISSUE TITLE
Thunderstorm command does not start thunderstorm

### ISSUE THREAD

**Issue by whimxiqal** [SpongePowered/Sponge#3640]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.0.0-RC1077-universal

### Operating System

Windows

### Java Version

17.0.1

### Plugins/Mods

```shell
none
```

### Describe the bug

On a normal singleplayer world, the commands `/weather rain` and `/weather thunder` cause rainstorms, but the thunder version also makes it a thunderstorm. The sky visibly becomes darker and lightning strikes occasionally. 

In a SpongeVanilla server, `/weather thunder` produces the same visual result as `/weather rain` and never produces thunder. I waited for roughly 20 minutes and still no thunder/lightning occurred. It's unclear whether thunderstorms happen naturally without the command, but `/weather thunder` does not seem to produce the correct vanilla behavior.

**Comment by Faithcaio** [comment]
It was never actually changing into thunderstorm mode. Enjoy the weather
