### ISSUE TITLE
Compatibility Issue with Bountiful and Kotlin

### ISSUE THREAD

**Issue by uwuscutely** [SpongePowered/Sponge#3642]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.0.0-RC1081

### Operating System

Linux

### Java Version

Java 11

### Plugins/Mods

```shell
https://bin.bloom.host/raw/kuvadolehu
```

### Describe the bug

Server crashes on startup and mod fails to load correct with Sponge loaded.

### Link to logs

https://bin.bloom.host/dexeremiwa.rb

**Comment by gabizou** [comment]
Unable to be fixed. KotlinForForge explicitly casts an interface to a concrete expected type [here](https://github.com/thedarkcolour/KotlinForForge/blob/ff611f3d51f17d3d8749e6259e53e64ebfbd5346/src/main/kotlin/thedarkcolour/kotlinforforge/forge/Forge.kt#L37) and SpongeForge utilizes it's own implementation of an `IEventBus` (that doesn't extend `EventBus`). 

There is a possible workaround but it's not clean or something I'd like to support/maintain moving forward. The whole point of Forge exposing the interface is to... expose the interface. A mod depending on the implementation of an interface to be the same isn't a smart thing to do (and this is why this issue arises).

The harder part is that the mod already made the necessary changes in 1.17+ versions of the mod, so it's not likely to get any fixes for 1.16 :/

**Comment by uwuscutely** [comment]
Issue opened on Kotlin repo. Fix for 1.16 might be coming, not 100% sure

**Comment by thedarkcolour** [comment]
If I manage to get it working the fix will also work all the way back until 1.14.
