### ISSUE TITLE
Bountiful Baubles blows up SF 1.16.5 (Critical injection failure)

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/Sponge#3646]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.0.0-RC1085-universal

### Operating System

Windows 10

### Java Version

1.8.0_51 by Oracle

### Plugins/Mods

```shell
The complete Cuboid Outpost modpack (client version), version 1.1.0 (https://www.curseforge.com/minecraft/modpacks/cuboid-outpost). I also substituted in Gabizou's patched version of abnormals_core-1.16.5-3.3.1, which actually works with SpongeForge. (It crashes on the abnormals-core conflict without the patch).
```

### Describe the bug

It crashes during start-up, throwing a long chain of errors starting with
`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException`
and ending with this:
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method onApplyDamageAmount(FLnet/minecraft/util/DamageSource;)F in bountifulbaubles.mixins.json:MixinPlayerEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap bountifulbaubles-common-refmap.json`

I humbly submit that perhaps `bountifulbaubles-1.16.5-0.1.0-forge` has some incompatibility with SpongeForge.

Here is the log-file for your perusal:
[latest.log](https://github.com/SpongePowered/Sponge/files/8206446/latest.log)

**Comment by Inscrutable** [comment]
Update: I tried with SpongeForge-1.16.5-36.2.5-8.1.0-RC1313-universal, and got the same result as above.

**Comment by DrZoddiak** [comment]
I worked on getting this mod working with SpongeForge. I am unsure as to the "proper" resolution.
The above error that @Inscrutable received got resolved, and I got a new (but similar) error with the below method.
I'm no Mixin Magician, but something tells me it has something to do with LocalCaptures?
https://github.com/DrZoddiak/BountifulBaubles/blob/ea420ec42776539c1fa38512e950a4539105e621/common/src/main/java/cursedflames/bountifulbaubles/mixin/MixinPlayerEntity.java#L94-L117

All that said, I have produced a Jar that loads with SpongeForge 1.16.5
I'm not wholly familiar with the Mod, I did test a couple items but I'm not certain *everything* is as it should be.
https://github.com/DrZoddiak/BountifulBaubles/releases/tag/Patched-MissingFeature

As I said above I'm not familiar with Mixin, so trying to "really" fix this is a bit out of my league.
but I did fix all of the build-script errors, so at worst I saved someone the 4 hours it took me!

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
