### ISSUE TITLE
SpongeForge 1.16.5 InvalidMixinException ATM6

### ISSUE THREAD

**Issue by Aiidoneus** [SpongePowered/Sponge#3647]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.0.0-RC1085-universal.jar

### Operating System

Linux

### Java Version

1.8.0_212

### Plugins/Mods

```shell
No Plugins

Mods
You can view it here https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/relations/dependencies
```

### Describe the bug

The server was running fine as a regular forge server. Once I added SpongeForge, it seems to hard crash with several mixin errors. Not sure what more I can provide but I linked the logs. Please let me know what more I can do to help solve the issue. 

### Link to logs

https://gist.github.com/Aiidoneus/e344da617173ee2dcc6e1f66a9e09485

**Comment by gabizou** [comment]
Re-run with `-Dmixin.dumpTargetOnFailure=true` as a JVM arg and zip the `.mixin.out` folder that's created after the crash (it will be in your game directory). This is needed to help resolve why there's some extra methods that shouldn't be there.

**Comment by Aiidoneus** [comment]
[mixin.out.zip](https://github.com/SpongePowered/Sponge/files/8239081/mixin.out.zip)
I believe this is what you need?

**Comment by gabizou** [comment]
That's an empty folder, it should have nested folders within it after the crash happens.

**Comment by Aiidoneus** [comment]
That was all that was in there. There was only 1 class file after you go through the folders

**Comment by gabizou** [comment]
When this PR is finished [building](https://github.com/SpongePowered/Sponge/actions/runs/2009652871), you could try using the SpongeForge production jar from the Action's result (scroll to the bottom of the summary).

Edit: Update, here's the [download link](https://github.com/SpongePowered/Sponge/suites/5723925294/artifacts/189250382) for the production jar

**Comment by gabizou** [comment]
When this PR is finished [building](https://github.com/SpongePowered/Sponge/actions/runs/2009652871), you could try using the SpongeForge production jar from the Action's result (scroll to the bottom of the summary).

**Comment by Aiidoneus** [comment]
Hello,
Here is a new error in the logs I am getting. I am also attaching the mixin class file I am getting as well if that helps. 
https://gist.github.com/Aiidoneus/e9c86080984d9ef758db41c7c59f7199
[mixin.zip](https://github.com/SpongePowered/Sponge/files/8310060/mixin.zip)

**Comment by gabizou** [comment]
> Here is a new error in the logs I am getting

Seems like the gist link is 404'ing for me, did you upload and then mean to replace them?

**Comment by Aiidoneus** [comment]
Sorry. Fixed it cut off some of the URL somehow.

**Comment by gabizou** [comment]
Ok, going to try a different (maybe hackier workaround), pending the [build from this run](https://github.com/SpongePowered/Sponge/actions/runs/2009797295)

Edit: Try this [build](https://github.com/SpongePowered/Sponge/suites/5724183572/artifacts/189268934)

**Comment by gabizou** [comment]
@Aiidoneus updated my previous comment with the build download that should work now.

**Comment by Aiidoneus** [comment]
https://gist.github.com/Aiidoneus/5bfbab841caf7298624a770d85249964

**Comment by gabizou** [comment]
Ok cool, so the underlying issue is fixed, the abnormals core issue is fixed in Abnormals Core with the [PR that was merged](https://github.com/team-abnormals/blueprint/pull/146) last week. I don't know exactly how to get an updated abnormals core version, but building it based on their 1.16.x branch should bring it back with compatibility.
