### ISSUE TITLE
One more crash with computers

### ISSUE THREAD

**Issue by maestrous** [SpongePowered/Sponge#365]
Actually, one more crash. with last build.
No crash report, just log.
http://pastebin.com/raw.php?i=LYByBzk9

**Comment by simon816** [comment]
Seems to be a compatibility issue when OpenComuters (`OpenComputers-MC1.8-1.5.18.39-universal.jar`) is present

**Comment by maestrous** [comment]
Yesterday was another crash, and more log/process loading, its was fixed. today this. if is error of mod OC - sadly.

**Comment by Zidane** [comment]
@bloodmc has been using this to test for a while. Should be working.

**Comment by Aaron1011** [comment]
@maestrous: Could you give us the log after running the server with the the following argument

`-Dmixin.debug.verbose=true -Dmixin.debug.verify=true`

**Comment by maestrous** [comment]
So, if i right - this.
http://pastebin.com/raw.php?i=0wuKqrD6

**Comment by Aaron1011** [comment]
@maestrous - You've added the argument correctly, but I need the entire log - not just that header.

**Comment by maestrous** [comment]
i cant give you, because it is not written to the log. log with your args same as in my first message. Only console output different. same 122 lines and 12 822 bytes. O.o

But if still want - http://pastebin.com/ryr4paCE

**Comment by maestrous** [comment]
i cant give you, because it is not written to the log. log with your args same as in my first message. Only console output different. same 122 lines and 12 822 bytes. O.o

But if still want - http://pastebin.com/ryr4paCE

**Comment by Zidane** [comment]
@Aaron1011 

This really seems like something loaded a new or old version of Guava, no?

**Comment by Aaron1011** [comment]
@Zidane: I agree.

**Comment by simon816** [comment]
This might be something to do with Guava classes loaded using the LCL, something https://github.com/MinecraftForge/MinecraftForge/pull/2022 would hopefully solve

**Comment by Polymetric** [comment]
I'm also getting this crash when running latest Sponge and OC. Let me know if there's anything I can do to help test a fix.

**Comment by simon816** [comment]
The guava class loading issue has been fixed in forge 1521, but there still is an issue with OpenComputers, #362 continues to occur using latest sponge and forge, follow https://github.com/MightyPirates/OpenComputers/issues/1485 for updates.
