### ISSUE TITLE
Entity teleport event.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/Sponge#3651]
### Is this request specific to one implementation of Sponge?

No

### Sponge Version

SpongeVanilla: 1.16.5-8.0.0-RC1088

### What are you requesting?

In API7 there was an entity teleportation event. API8 doesn't have it. Now I have to use this code to define teleportation when developing a plugin.

```java
	@Listener
	public void onMove(MoveEntityEvent event) {
		boolean teleport = !(event.source() instanceof Entity) ? true : !entityId(event.entity()).equals(entityId((Entity) event.source()));
	}

	String entityId(Entity entity) {
		return Sponge.game().registry(RegistryTypes.ENTITY_TYPE).valueKey(entity.type()).asString();
	}
```
In doing so, another problem arises. If the teleportation is done with a command, I cannot get the specific sender of the command to later check the permission to teleport. I need to check if the teleportation is performed by another player or console and prevent it if necessary.
There is also a bug with the ender-pearl. Teleportation is not cancelled. Even if you cancel the event, it still happens.

**Comment by dualspiral** [comment]
> In API7 there was an entity teleportation event. API8 doesn't have it. Now I have to use this code to define teleportation when developing a plugin.

Use the cause, not just the source. In this scenario, it sounds like you're interested in more than just the direct cause, but a lot of the contextual information.

What would a teleport event add that you can't get from this event as it stands?

> If the teleportation is done with a command, I cannot get the specific sender of the command to later check the permission to teleport.

It's in the cause, you might just need to traverse it. I imagine you're probably finding a plugin as the cause, but the player (if a player executed the command) will be just below it. You may be interested in looking at the first player in the cause, or even just traversing it for the first `Player` or `SystemSubject`.

> There is also a bug with the ender-pearl. Teleportation is not cancelled. Even if you cancel the event, it still happens.

File a bug ticket for that please, separate problem.

**Comment by Faithcaio** [comment]
Also there is `EventContextKeys.MOVEMENT_TYPE`
https://github.com/SpongePowered/Sponge/blob/84ea2013c1319a8d12c70e479e719effc59cd05c/testplugins/src/main/java/org/spongepowered/test/movement/MovementTest.java#L161


> File a bug ticket for that please, separate problem.

Fixed it already.

**Comment by Faithcaio** [comment]
And this is what the cause looks like
![image](https://user-images.githubusercontent.com/1575592/159130383-5f9c1843-4421-4483-bd83-cc733cc5e733.png)
when setting position in a command
https://github.com/SpongePowered/Sponge/blob/84ea2013c1319a8d12c70e479e719effc59cd05c/testplugins/src/main/java/org/spongepowered/test/movement/MovementTest.java#L99
so I think everything you need should be available
