### ISSUE TITLE
Error while starting Sponge in Development Environment

### ISSUE THREAD

**Issue by Rain336** [SpongePowered/Sponge#366]
## Info:
Everytime when I start the Client or Server I get an InvocationTargetException from LaunchWrapper saying it can't find the Methode "main" in net.minecraft.client.Minecraft .
It's strange that this even happens when I start the Server

## ErrorLog:
https://gist.github.com/Rain336/26dcf8d0609ae6063053

**Comment by Aaron1011** [comment]
@Rain336: I've had exactly the same issue in Intellij (which I assume you're using, based on the error).

To fix this, right click on your `Sponge` module and click on `Module Settings`. In the `Dependencies` section, move `SpongeCommon` to the *very bottom* of the list.
