### ISSUE TITLE
Using the empty map item causes an exception

### ISSUE THREAD

**Issue by avaruus1** [SpongePowered/Sponge#3672]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.0.0-RC1112

### Operating System

Linux/5.15.32-xanmod1-tt-1 (amd64)

### Java Version

18.0.1

### Plugins/Mods

```shell
None
```

### Describe the bug

Right clicking an empty map causes an exception.

### Link to logs

https://gist.github.com/avaruus1/ccfc9990f5e26ed2d8780914e276192a

**Comment by Faithcaio** [comment]
see https://github.com/SpongePowered/Sponge/issues/3680
