### ISSUE TITLE
Placing a dry sponge in water dupes sponge (ironic)

### ISSUE THREAD

**Issue by whimxiqal** [SpongePowered/Sponge#3673]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.0.0-RC1105

### Operating System

Tested both Windows and Linux

### Java Version

1.8.0_202

### Plugins/Mods

```shell
Just spongeforge-1.16.5-36.2.5-8.0.0-RC1105-universal
```

### Describe the bug

When you place a dry sponge in water, it uses the sponge in your hand, places the sponge in the water, and sponge absorbs the water as it should. But, the dry sponge is still in the inventory but hidden, thus duping it. You can `/give` a new sponge and the old one will pop up too, making a stack of 2. You can also just relog and see that the dry sponge reappears.

### Link to logs

N/A

**Comment by Faithcaio** [comment]
@gabizou It seems that the `CheckBlockPostPlacementIsSameEffect` returning null causes the interaction to fail and as such the server is not consuming the stack in hand.
https://github.com/SpongePowered/Sponge/blob/add8ccd0a6db6b617a66cdfea5631b35b18172a5/src/main/java/org/spongepowered/common/event/tracking/context/transaction/effect/CheckBlockPostPlacementIsSameEffect.java#L52

Using `return new EffectResult(newState, true);` seems to work. Makes sense to you?
