### ISSUE TITLE
Plugin load issues due to resolution tries of non-runtime annotations

### ISSUE THREAD

**Issue by derklaro** [SpongePowered/Sponge#3674]
### Affected Product(s)

SpongeVanilla

### Version

1.18.1-9.0.0-RC1117

### Operating System

Linux 

### Java Version

openjdk version "17.0.2" 2022-01-18

### Plugins/Mods

```shell
(Aside from my plugin:) ViaVersion, Spark
```

### Describe the bug

The listener factory of Sponge tries to load annotation classes which are only retained on class level and therefore not available in the runtime. The test code (shown below) uses lombok's NonNull annotation as an example, but any other annotation which is not retained for runtime use will cause the same issue. The only workaround seems to be to use annotations which are retainable at runtime or remove them completely.

```java
  @IsCancelled(Tristate.FALSE)
  @Listener(order = Order.LAST)
  public void handle(@NonNull ServerSideConnectionEvent.Login event, @NonNull @Root User user) {}
```

### Link to logs

https://gist.github.com/derklaro/236632c47c50494630723b5b74c39408

**Comment by gabizou** [comment]
Something to note: It's redundant to annotate for null checking parameters passed through a `@Listener` annotated method, the parameters are intrinsically never null.

While I did the fix for the underlying issue, this doesn't mean Sponge will support Lombok as a tool.
