### ISSUE TITLE
Sponge  16.5-36.2.5-8.0.0-RC1118 Crash with mod mine mine no mi

### ISSUE THREAD

**Issue by PeterLaArdilla** [SpongePowered/Sponge#3676]
### Major SpongeAPI version

8

### Is this likely to be a breaking change?

I don't know

### What are you requesting?

My server crash with just sponge and mine mine no mi mod, when i join the server
[Nuevo documento de texto (5).txt](https://github.com/SpongePowered/SpongeAPI/files/8643911/Nuevo.documento.de.texto.5.txt)

**Comment by gabizou** [comment]
Closing for the following reasons:
- Mod source urls aren’t available
- Mod’s CurseForge doesn’t appear to have a 1.16.5 version available to download
- The mixin conflict in the report isn’t possible to replace in Sponge, the mod should be able to use Forge supported events to modify reach checks (best guess as to what it may be attempting to do)
