### ISSUE TITLE
`PluginPackResources#getResources` not working

### ISSUE THREAD

**Issue by SettingDust** [SpongePowered/Sponge#3677]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.0.0-RC1118

### Operating System

Windows

### Java Version

11.0.14.1 by Microsoft

### Plugins/Mods

```shell
Developing
```

### Describe the bug

- [x] Resolve namespace twice https://github.com/SpongePowered/Sponge/blob/api-8/vanilla/src/main/java/org/spongepowered/vanilla/server/packs/PluginPackResources.java#L92=
	The path will look like `data\plugin-foo\plugin-foo`. But it should be `data\plugin-foo`
- [x] Output always the input path instead of the files https://github.com/SpongePowered/Sponge/blob/api-8/vanilla/src/main/java/org/spongepowered/vanilla/server/packs/PluginPackResources.java#L96=

**Comment by SettingDust** [comment]
I'm working on it

**Comment by dualspiral** [comment]
Good catches, and thanks for the PR!
