### ISSUE TITLE
Sleeping Does Not Reset Night

### ISSUE THREAD

**Issue by NHDriver4** [SpongePowered/Sponge#368]
Forge: forge-1.8-11.14.3.1520
Sponge: sponge-1.8-1519-2.1DEV-702
Other Mods: None

I am running a server with Forge and Sponge, with no additional mods or config tweaks. When night comes, I can sleep in a bed, but time does not advance to morning.

**Comment by Zidane** [comment]
@Aaron1011 

Add this to your list.

**Comment by Aaron1011** [comment]
Resolved in https://github.com/SpongePowered/SpongeCommon/commit/3a3b4c2c8c3cf832c6f4092881e4563ee25125ec
