### ISSUE TITLE
`SpongeBlockSnapshot#restore()` get world wrongly

### ISSUE THREAD

**Issue by SettingDust** [SpongePowered/Sponge#3682]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.0.0-RC1128

### Operating System

Windows

### Java Version

11.0.14.1 by Microsoft

### Plugins/Mods

```shell
custom
```

### Describe the bug

https://github.com/SpongePowered/Sponge/blob/api-8/src/main/java/org/spongepowered/common/block/SpongeBlockSnapshot.java#L169=
Should get world with `getServerWorld` for init the world.

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/Sponge/commit/01f740be1a75b5b68afea1cc4990406117614dfa
