### ISSUE TITLE
1.16.5 spongeforge - ModList was loaded too early

### ISSUE THREAD

**Issue by RawrMaoster** [SpongePowered/Sponge#3685]
**Affected Products:**
Sponge Forge

**Version:**
spongeforge-1.16.5-36.2.5-8.0.0-RC1130-universal.jar

**Operating System:**
Unknown - OMGServ Panel

**Java Version:**
Java 8

**Mods / Plugins:**
Mods contained in the technic modpack ''Tekxit Journey''

**Describe The Bug:**
When i add in spongeforge to mods folder i get told it loads too fast. No crash log.

**Link to log file:**
https://pastebin.com/S3taJpWd

**Comment by SettingDust** [comment]
Don't attach log as file in issue next time. Use [gist](https://gist.github.com)/paste service plz.
You need provide the way to reproduce the issue when you submitting. There is a [template](https://github.com/SpongePowered/Sponge/blob/api-8/.github/ISSUE_TEMPLATE/bug_report.yml) when you submit issue in **correct** repo. Plz edit this issue to add the info in form. `SpongeDocs` is the repo of `docs.spongepowered.org`.

**Comment by RawrMaoster** [comment]
Apologies, I usually use paste bin but recently learned i could drag and drop!

To reproduce you could simply go to technic and install Tekxit Journey, Use mods in a server environment and make sure it boots as is and then drag and drop spongeforge into mods folder.

Should provide errors in the current available update.

If not ill update this when i release my next update for that modpack.

**Updated the original post to reflect how i think it should have looked.**

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
