### ISSUE TITLE
`ItemStack.Builder#fromBlockSnapshot` can't fetch from `tall_seagrass`

### ISSUE THREAD

**Issue by SettingDust** [SpongePowered/Sponge#3687]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.0.0-RC1131

### Operating System

Windows

### Java Version

java version 17.0.3 by JetBrains s.r.o.

### Plugins/Mods

```shell
custom
```

### Describe the bug

`ItemType not found for block type: minecraft:tall_seagrass`
But click the wheel can get
![图片](https://user-images.githubusercontent.com/19922286/168795662-a4da616e-e9e7-43f3-848f-836da808f84b.png)

**Comment by Faithcaio** [comment]
This is because there is no item equivalent for the tall variant of seagrass.
Vanilla gets the itemstack via `Block#getCloneItemStack`

**Comment by Faithcaio** [comment]
Nvm. that method is client side only
I don't see another way to get the correct item.

**Comment by SettingDust** [comment]
Have to preserve a map for getting correct item
