### ISSUE TITLE
Unable to Place Water and Lava Bucket

### ISSUE THREAD

**Issue by NHDriver4** [SpongePowered/Sponge#370]
Forge: forge-1.8-11.14.3.1520-universal.jar
Sponge: sponge-1.8-1519-2.1DEV-706.jar
Other Mods: None
Config Changes: Default

I am unable to place a water or lava bucket. I am out of the spawn radius. I tried this as a regular player, as well as an oped admin. If I remove Sponge from the mix, I can place just fine.

**Comment by Zidane** [comment]
@NHDriver4 

Its a known issue, we'll get it fixed as soon as we can.

**Comment by NHDriver4** [comment]
Thank you. Didn't see an issue filed, figured I'd do so.
