### ISSUE TITLE
Illegal State Exception with Progressive Bosses mod

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#3714]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.1.0-RC1153

### Operating System

Linux

### Java Version

openjdk 1.8.0_312

### Plugins/Mods

```shell
- InsaneLib-1.4.2
- ProgressiveBosses-3.4.3
```

### Describe the bug

Basically, it seems that Sponge doesn't like the idea of Progressive Bosses changing some of the dragon's properties. As a result, it crashes when trying to start the server. That's the most I could work out from the issue.

Also, the forge version is: forge-1.16.5-36.2.35

**How to reproduce:**

- Put Sponge, InsaneLib and Progressive Bosses inside the mod's folder.

- Run the server

### Link to logs

https://paste.gg/p/anonymous/dbf5aacfcbc74c24b7bdcdb1e0c63ffc

**Comment by vectrixdevelops** [comment]
This should be safe to close since the fix got merged.
