### ISSUE TITLE
Spiders 2.0, Progressive Bosses and FastWorkbench Minus Replacement crashing server on startup

### ISSUE THREAD

**Issue by Carhenia** [SpongePowered/Sponge#3715]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1153

### Operating System

debian 11

### Java Version

openjdk v11.0.12

### Plugins/Mods

```shell
Spiders 2.0 (spiders-2.0-1.16.4-1.0.4)
Progressive Bosses (ProgressiveBosses-3.4.3-mc1.16.5)
Insane Lib (InsaneLib-1.4.2-mc1.16.5)
FastWorkbenchMinusReplacement (fastbenchminusreplacement-1.4)
MixinBootstrap (_MixinBootstrap-1.1.0)
```

### Describe the bug

The following mods are crashing the server on startup. I tested this by only installing the mod (and relevant core mod) causing the error, alongside sponge. 

Spiders 2.0: [Latest](https://mclo.gs/9Sj5L3I)
Progressive Bosses: [Latest](https://mclo.gs/sO5KZ6o)
FastWorkbenchMinusReplacement: [Latest](https://mclo.gs/8tEXC5Z)

**Comment by Zidane** [comment]
Spiders 2.0, mod conflict

Progessive Bosses, known, issue on it already (it adds more Dragon phases, need to make us not die from it..)

FastWorkbenchMinusReplacement, mod conflict

I'd prefer separate tickets for 1 and 3 if possible. For the first and last mods, no promises...it depends on what we're doing and what the mods are doing. We're not above changing our code to be compatible but we don't promise 100% compatibility either. We'll try as time allows.

**Comment by Carhenia** [comment]
I'll make the separate tickets now, thanks.
