### ISSUE TITLE
Spiders 2.0 crashing server on startup

### ISSUE THREAD

**Issue by Carhenia** [SpongePowered/Sponge#3716]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1153

### Operating System

debian 11

### Java Version

openjdk v11.0.12

### Plugins/Mods

```shell
Spiders 2.0 (spiders-2.0-1.16.4-1.0.4)
```

### Describe the bug

Spiders 2.0 mod is crashing the server on startup. I tested this by installing it alone alongside sponge.

### Link to logs

https://mclo.gs/9Sj5L3I

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
