### ISSUE TITLE
Server crashes after loading overworld.

### ISSUE THREAD

**Issue by Giorgio1234** [SpongePowered/Sponge#3726]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1164

### Operating System

Ubuntu Server

### Java Version

openjdk version "1.8.0_312"

### Plugins/Mods

```shell
tconstruct
biomesoplenty
appliedenergestics2
jei
bloodmagic
mantle
patchouli
curios
twilight forest
botania
spacebosstools
```

### Describe the bug

Server loads up, I join in, run around for a minute, server returns crash.

I am migrating my current server from magma to sponge.

I have noticed a few people having issues with sponge and applied energestics. Possible incompatibility?

### Link to logs

https://pastebin.com/JwSLuwVM

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
