### ISSUE TITLE
Suspected Mixin Incompatibility with Vault Hunters Mod

### ISSUE THREAD

**Issue by jakematt123** [SpongePowered/Sponge#3728]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1164

### Operating System

Linux (Unknown Distro)

### Java Version

Java 8

### Plugins/Mods

```shell
Mods:
Vault Hunters Modpack (VERSION 1.13.3) (https://vault-hunters.fandom.com/wiki/Mods)

Plugins: None
```

### Describe the bug

Startup crash when using SpongeForge for the first time. The crash is at the bottom of the paste provided. It seems to be an issue with Sponge and The_Vault mod. 

### Link to logs

https://pastebin.com/u1fbr3TB

**Comment by Inscrutable** [comment]
It seems this is still breaking Sponge's mixins using recent versions of the modpack (Vault Hunters 1.13.8, containing Vault mod version 1.8.3p1.13.8L) and SpongeForge RC1182. 
Here's the problematic mod: https://www.curseforge.com/minecraft/mc-mods/vault-hunters-official-mod

**Comment by dvtkrlbs** [comment]
Is this needs to be fixed by vault developers or is there anything sponge can do in this case. Just came across this issue.

**Comment by Faithcaio** [comment]
This is the conflict:

```
@Redirect conflict. Skipping 
assets/the_vault/the_vault.mixins.json:MixinServerPlayerEntity->
   @Redirect::yes(Lnet/minecraft/world/GameRules;Lnet/minecraft/world/GameRules$RuleKey;)Z with priority 1000, 
already redirected by 
mixins.sponge.core.json:server.level.ServerPlayerMixin->
   @Redirect::tracker$useKeepFromBridge(Lnet/minecraft/world/GameRules;Lnet/minecraft/world/GameRules$RuleKey;Lnet/minecraft/entity/player/ServerPlayerEntity;Z)Z with priority 1101
```


Sponge redirects the `GameRules.RULE_KEEPINVENTORY` evaluation to enable overriding the rule on players individually.
https://github.com/SpongePowered/Sponge/blob/ae86a5c88c543c1ddbe6f26c7665499148e3ebc2/src/mixins/java/org/spongepowered/common/mixin/core/server/level/ServerPlayerMixin.java#L700

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
