### ISSUE TITLE
MowziesMobs and SpongeForge: Ticking Player, Tick must be greater than 0

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#3733]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.10

### Operating System

Linux

### Java Version

openjdk 1.8.0_312

### Plugins/Mods

```shell
Mowzie's Mobs (Mod)
GeckoLib (Mod)
```

### Describe the bug

In a nutshell, Mowzie's Mobs uses a lot of animations (I suppose it gets from GeckoLib).
These animations are able to render correctly but for some reason the player isn't able to deal any damage as intended when using them.
Besides, every animation that is not related to the player, like shockwaves that animate the surrounding blocks or an animation that spawns boulders in front of the player don't seem to work.

The biggest issue and clue about this bug is that when trying a specific animation of the mod, the player client gets disconnected because of an Internal Server Error reported by Sponge.
As it isn't an actual crash, I've attached part of the debug log containing the exception report.

This seems to be happening only regarding the player, as the actual mobs are able to use them as intended.

No workarounds found.

### Link to logs

https://gist.github.com/WhiteFox-git/fbe2981e62c1893d06b5e68865ece29b

**Comment by ghost** [comment]
Link to MowziesMobs open issue:
https://github.com/BobMowzie/MowziesMobs/issues/646

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
