### ISSUE TITLE
Chunk-Pregenerator commands not working with SpongeForge

### ISSUE THREAD

**Issue by nickkeane** [SpongePowered/Sponge#3734]
### Affected Product(s)

SpongeForge

### Version

v1.16.5-36.2.5-8.1.0-RC1164

### Operating System

Windows

### Java Version

JDK 8u342

### Plugins/Mods

```shell
MC Forge v36.2.39
Chunk-Pregenerator v3.4.0
Dynmap v3.4-beta-5-806
```

### Describe the bug

Chunk-Pregenerator (/pregen) commands don't work when SpongeForge is active.

They return an error:

Unknown Command. Type /help for a list of commands.

Also, the following errors are printed when I log into the server:

[15:21:00] [Server thread/ERROR]: Root command /pregen does not have an associated plugin! Using "unknown" in place of plugin ID for the permission.
[15:21:00] [Server thread/ERROR]: Root command /unknown:dynmap does not have an associated plugin! Using "unknown" in place of plugin ID for the permission.
[15:21:00] [Server thread/ERROR]: Root command /unknown:dmap does not have an associated plugin! Using "unknown" in place of plugin ID for the permission.
[15:21:00] [Server thread/ERROR]: Root command /unknown:dmarker does not have an associated plugin! Using "unknown" in place of plugin ID for the permission.
[15:21:00] [Server thread/ERROR]: Root command /unknown:dynmapexp does not have an associated plugin! Using "unknown" in place of plugin ID for the permission.

The DynmapForge commands (/dynmap, /dmap, etc.) are working fine by comparison w/ SpongeForge installed.

I don't have a permissions plugin installed (I disabled LuckPerms) and I have OP status.

Chunk-Pregenerator Issue: https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator/issues/178

**Comment by Speiger** [comment]
Chunk Pregenerator doesn't support SpongeForge. Its a dedicated server framework and I would have to write a specialized version just for it.

And no i don't blame Spongeforge for not supporting it.
It is just designed to run on a vanilla + forge server.

If you want to use Chunk Pregenerator, make a temporary vanilla + forge server.
Pregen your world, then switch back to spongeforge.

For the Sponge/Spongeforge devs, I would suggest you just default to this kind of answer. Or make a pinned issue.
I don't plan on making a "specialized server" version anytime soon.

Edit: Chunk Pregen dev writing here

**Comment by zml2008** [comment]
Why shouldn't it run with SpongeForge? SpongeForge is, at its core, "just" another forge mod. If you use standard Forge API to register commands, then any failure for your commands to work is a SpongeForge issue.

**Comment by Speiger** [comment]
@zml2008
The general why i say its incompatible:
IIRC sponge server, or custom servers in genral, do a bunch of changes how mc works in the background.
I don't mean Foundation changes, but stuff like permission hooks, configuration hooks stuff that if a mod does excessive things would basically start a conflict with the infrastructure.
And the way chunk pregen works can be easily looked at excessively. (Loading region files at once)
Ofc my information can be wrong and/or outdated, but in this case its safer.

This command specific issue could be to command merging/conflict issue being present.
Or that mc also supports command replacing in its system that i make use of in later versions, but removed to ensure better support.

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1

**Comment by Speiger** [comment]
@ImMorpheus i fixed it on my side so it can be closed here.
