### ISSUE TITLE
ATM6 Crash on World Load

### ISSUE THREAD

**Issue by Aiidoneus** [SpongePowered/Sponge#3735]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.1.0-RC1164-universal.jar

### Operating System

Linux

### Java Version

1.8.0_212

### Plugins/Mods

```shell
No Plugins

Mods:
https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/relations/dependencies

Disabled mods from the list: lazydfu & Observable
```

### Describe the bug

The server goes through most of the startup process but stalls on what looks like on world load. I have removed SpongeForge and the world does load properly. Re-adding it after the fact causes some errors regarding missing world properties. 

Let me know if you need any other details!

### Link to logs

https://gist.github.com/Aiidoneus/0e1e4bc76088e0b6afc520fd00f10630

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
