### ISSUE TITLE
Ray trace crashes when no results are found

### ISSUE THREAD

**Issue by mosemister** [SpongePowered/Sponge#3750]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.1.0-RC1175

### Operating System

Linux

### Java Version

17.0.4

### Plugins/Mods

```shell
Custom only
```

### Describe the bug

When running the following code and when no valid blocks are hit, I get the error reported

```java
                ServerPlayer player;
		Optional<RayTraceResult<LocatableBlock>> opRayTraceResult = RayTrace
				.block()
				.continueWhileBlock(RayTrace.onlyAir())
				.limit(7)
				.sourceEyePosition(player)
				.execute();
```

### Link to logs

https://paste.gg/p/anonymous/018c7b55374c40b3bfb9e66fbbb296fd

**Comment by vectrixdevelops** [comment]
You must set the `direction` or `end` values in the RayTrace builder too. Taking `SpongeTargetBlockValueParameter` as an example it sets both the `sourceEyePosition` and `direction` like `.sourceEyePosition(player).direction(player.headDirection())`.

**Comment by mosemister** [comment]
I would love it if the error said ``The end or direction needs to be specified`` As I was assuming that setting the sourceEyePosition as the player would also set the direction from the player too
