### ISSUE TITLE
SpongeForge 1.16.5 crashing at start

### ISSUE THREAD

**Issue by agentflemme** [SpongePowered/Sponge#3752]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.1.0-RC1180-universal and latest

### Operating System

Linux, Containerized debian 10

### Java Version

11

### Plugins/Mods

```shell
Plugins :
Tested with and without, so wouldn't be the cause

CatClearLag
EconomyLite
FusionPixelmon
GTS
Holograms
HuskyCrates
HuskyUI
Impactor
LocaleAPI
LuckPerms
Nucleus
PistonMOTD
PixelGenocide
PixelmonPlaceHolders
PlaceHolderAPI
RegionGuard
UltimateChat

Mods :
Tested with and without, so wouldn't be the cause

AppleSkin
Byg
CFM
Create
Flywheel
IronChest
JEI
Morpheus
Pixelmon
Spongeforge (duh)
StorageDrawers
Valhelsia - Core and Structures
XlPackets
```

### Describe the bug

Server crashes on early load, before loading mods, plugins or anything. 
Quoting a staff member from Discord, because early loading isnt my cup of tea : "Something is loading before sponge and making it impossible for sponge to add what it needs."
"No i was refering to the fact Sponge cannot find the minecraft file of world (as well as many others)"

Tested : 
Java 8 and 11, respectively on Debian 9 and 10
Forge 36.2.5 and Forge 36.2.39

### Link to logs

https://pastebin.com/1zE32hu7 (latest forge) , https://pastebin.com/du86Dx8M (older forge)

**Comment by SawFowl** [comment]
You have a conflict of mixins. Place the sponge on the first place in the load. To do this, rename its file by adding 1 to the beginning.
It may not help. In this case, uninstall the conflicting mod.

**Comment by agentflemme** [comment]
> You have a conflict of mixins. Place the sponge on the first place in the load. To do this, rename its file by adding 1 to the beginning. It may not help. In this case, uninstall the conflicting mod.

Tried, same issue.
The thing is that i also tried without all the mods and without all the plugins

**Comment by SawFowl** [comment]
> > You have a conflict of mixins. Place the sponge on the first place in the load. To do this, rename its file by adding 1 to the beginning. It may not help. In this case, uninstall the conflicting mod.
> 
> Tried, same issue. The thing is that i also tried without all the mods and without all the plugins

Try Forge 6.2.34. My server starts normally with this version. I haven't tried the others.

**Comment by agentflemme** [comment]
> > > You have a conflict of mixins. Place the sponge on the first place in the load. To do this, rename its file by adding 1 to the beginning. It may not help. In this case, uninstall the conflicting mod.
> > 
> > 
> > Tried, same issue. The thing is that i also tried without all the mods and without all the plugins
> 
> Try Forge 6.2.34. My server starts normally with this version. I haven't tried the others.

You mean 36.2.34 ?
ill try rn

**Comment by SawFowl** [comment]
Yes. I meant this version.

**Comment by agentflemme** [comment]
> Yes. I meant this version.

seems like theres less errors, but still crashes
https://pastebin.com/Ye3SUdu7
