### ISSUE TITLE
SlotClickHandler is not called when the player is in spectator mode

### ISSUE THREAD

**Issue by avaruus1** [SpongePowered/Sponge#3781]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.1.0-RC1213

### Operating System

Linux

### Java Version

18.0.2.1/64-bit (Eclipse Adoptium)

### Plugins/Mods

```shell
-
```

### Describe the bug

InventoryMenu's SlotClickHandler never seems to be called when the player is in spectator mode. Inventory GUIs seem to work in spectator mode on our Spigot servers, so the required information for it to be called is sent by the client.

**Comment by Faithcaio** [comment]
ok so we handle the callbacks inside `AbstractContainerMenu` but vanilla never calls this because in 
`ServerGamePacketListenerImpl#handleContainerClick` when the player is spectator it just sends back the slots.
So we'll need to inject there directly

**Comment by Faithcaio** [comment]
Fixed in
API8 https://github.com/SpongePowered/Sponge/commit/cc0d7e86063581b85a2010c32dbba5de13592d96
API9 https://github.com/SpongePowered/Sponge/commit/caccaedeebd882921a4132719f57180cd94f2ecc
API10 https://github.com/SpongePowered/Sponge/commit/c594689daf1e5e0aaa23b11fbf7170418d0c54cb

**Comment by avaruus1** [comment]
> Fixed in API8 [cc0d7e8](https://github.com/SpongePowered/Sponge/commit/cc0d7e86063581b85a2010c32dbba5de13592d96) API9 [caccaed](https://github.com/SpongePowered/Sponge/commit/caccaedeebd882921a4132719f57180cd94f2ecc) API10 [c594689](https://github.com/SpongePowered/Sponge/commit/c594689daf1e5e0aaa23b11fbf7170418d0c54cb)

Now the click handler is triggered twice, when the player is not in spectator mode :D
