### ISSUE TITLE
Support pprof

### ISSUE THREAD

**Issue by sfxworks** [SpongePowered/Sponge#3785]
### Is this request specific to one implementation of Sponge?

No

### Sponge Version

1.16.5 and newer

### What are you requesting?

Hi there. I would like the ability to use Grafana Phlare to gain a flame graph of servers. In order to do this, server cores need to provide a profiling data endpoint. In Paper's case, this would be jpprof https://grafana.com/docs/phlare/latest/operators-guide/configure-agent/language-support/jvm/

I have considered hiring a developer to make a plugin, though I feel that this would best be served at the core of paper as an enable/disable config option.

I'm no java developer, but according to their documentation:

>If you’re using gradle, add the following dependency to your build.gradle:
```
dependencies {
// ....
    implementation 'com.grafana:jpprof:0.1.0'
//...
}
```

**Comment by zml2008** [comment]
This is not Paper -- perhaps you are looking for a different repository?

Based on actually reading the page, it looks like this is some sort of wrapper for async-profiler, one of the backends that [Spark](https://spark.lucko.me/) supports. Any sort of http endpoint for accessing those profiles has more of a chance of making sense there, where the plugin already focuses on profiling.
