### ISSUE TITLE
Auth Issue SpongeForge 1.16.5 MODERN Proxy Velocity

### ISSUE THREAD

**Issue by Nathan-Moignard** [SpongePowered/Sponge#3787]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1235

### Operating System

Linux

### Java Version

DK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mix

### Plugins/Mods

```shell
There is no mod installed in the SpongeForge mods/ folder exept SpongeForge JAR file itself.
```

### Describe the bug

What is the bug:
I installed a Velocity Proxy Server **Velocity 3.1.2-SNAPSHOT** using the MODERN protocol. I then configured the secret key in the velocity.toml and in the config/sponge/sponge.conf
To resume: SpongeForge is configured in MODERN protocol + the Velocity Key.

When trying to join Velocity, I am well redirected to the SpongeForge server. However, authentication errors are triggered in the SpongeForge server console (Logs attached).

Velocity Error Logs:
```
[00:35:04] [Netty epoll Worker #13/INFO]: [connected player] Je_Susi_Cache (/192.168.0.254:49910) has connected
[00:35:04] [Netty epoll Worker #13/INFO]: [server connection] Je_Susi_Cache -> spongeforge has connected
[00:35:04] [Netty epoll Worker #13/INFO]: [server connection] Je_Susi_Cache -> spongeforge has disconnected
[00:35:04] [Netty epoll Worker #13/ERROR]: [connected player] Je_Susi_Cache (/192.168.0.254:49910): unable to connect to server spongeforge
com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
[00:35:04] [Netty epoll Worker #13/INFO]: [connected player] Je_Susi_Cache (/192.168.0.254:49910) has disconnected: Unable to connect you to spongeforge. Please try
```

How to reproduce it:
- Setup [**Velocity 3.1.2-SNAPSHOT**](https://api.papermc.io/v2/projects/waterfall/versions/1.19/builds/506/downloads/waterfall-1.19-506.jar)
- Setup SpongeForge Server with **forge-1.16.5-36.2.34** and **spongeforge-1.16.5-36.2.5-8.1.0-RC1235-universal**
- No Mod or Plugin is required to be installed except SpongeForge itself.
- Start a Vanilla or Forged Client and try to join the Velocity Proxy

### Link to logs

https://gist.github.com/Nathan-Moignard/eed4f0b240fc5e3866768f9d66778a79

**Comment by zml2008** [comment]
Forge uses a new modded handshake system since 1.13 -- Velocity and Forge have not yet implemented the changes necessary to support Forge on proxies, so Forge cannot be proxied yet. If you want to use a Velocity network, you'll need to run SpongeVanilla.
