### ISSUE TITLE
[Future] Java 17 missing

### ISSUE THREAD

**Issue by ErythroCraft** [SpongePowered/Sponge#3790]
### Is this request specific to one implementation of Sponge?

No

### Sponge Version

all versions

### What are you requesting?

Can you update to Java 17 please?

**Comment by zml2008** [comment]
what exactly do you want "updated"?

**Comment by ErythroCraft** [comment]
I want use sponge or mixin with Java 17

**Comment by zml2008** [comment]
with the minimal information you have given, this seems more like a support request. Come to our discord, or ask on our forums (both linked from the README) for further assistance.
