### ISSUE TITLE
Ignoring slot transaction on InventoryMenu during EntityTickContext

### ISSUE THREAD

**Issue by V1nga** [SpongePowered/Sponge#3791]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1235-universal

### Operating System

Windows

### Java Version

1.8.0 211

### Plugins/Mods

```shell
crafting-dead-core-1.16.5-1.7.5-alpha
```

### Describe the bug

Code source: [github-repository](https://github.com/nexusnode/crafting-dead/tree/1.16.x)

1. When reloading a weapon, it is canceled without any errors in log file
2. In the modification, when the weapon is not loaded and you press the left mouse button, the weapon starts reloading automatically and then the sponge gives an error in log file

### Link to logs

https://paste.gg/p/anonymous/a961a00eed3e47409661518f32a0a845/files/c25b442274ab4b118f7f5ddf2b8b07ec/raw

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
