### ISSUE TITLE
Fiber/Async chat event handling

### ISSUE THREAD

**Issue by sunmisc** [SpongePowered/Sponge#3792]
### Is this request specific to one implementation of Sponge?

Yes, only SpongeVanilla

### Sponge Version

1.19.2-10.0.0-RC1239

### What are you requesting?

There has already been a similar request, but there are significant nuances and changes that I will talk about.

The Project Loom (jdk 19 preview) adds a preview of the fiber concept (green threads, virtual threads), inside these threads, locking may not cost anything, and the threads themselves can be created not in thousands (like OS threads) but in millions; It opens up new possibilities

In order not to break the current API, I suggest adding a new Async****ChatEvent event, which will trigger all events in some thread (there is no guarantee that these will be fibers)

It should look like this:
- publication of synchronous events
- / some pool / - publication of asynchronous events (within the same pool, you can perform further actions, as far as I know, the chat allows work in another thread)

However, it is not necessary to make Async****ChatEvent a thread-safe class, since all actions happen sequentially.

This will solve a lot of performance issues
- get rid of blocking the main thread
- in the future, lightweight threads will allow you to conveniently work with this kind of thing, without using CompletableFuture / Callback / - we can simply block without idle CPU

Yes, fibers have not been released yet, but even a pool from the 1st system thread will be much better than blocking in the main thread

This pool, you can create with thoughts / let it stand for now, nothing bad will happen, and then you can change one word and BINGO! /

**Comment by zml2008** [comment]
Chat signing and the message links that are part of the system (requiring order to be maintained) would make this all relatively impractical. There's no point doing some massive new thing without profiling showing the performance issue

**Comment by sunmisc** [comment]
> Chat signing and the message links that are part of the system (requiring order to be maintained) would make this all relatively impractical. There's no point doing some massive new thing without profiling showing the performance issue 

I don’t see any problems with the implementation of the order, this can be implemented with a queue from Callback (there are queues in java.util.concurrent ) you just need to inside the current task (after all event calls, run the next task
  ```
  tryFire() {
      handle(q.pollFirst());
  }
  handle(Task start) {
       execute(() -> {
          // todo: work
          handle(q.pollFirst());
       }
 )
```
more or less like this
