### ISSUE TITLE
IP Forwarding not working

### ISSUE THREAD

**Issue by MainBreezy** [SpongePowered/Sponge#3793]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1235-universal

### Operating System

Windows 10

### Java Version

1.8.0_351

### Plugins/Mods

```shell
Spongeforge-1.16.5-36.2.5-8.1.0-RC1235-universal.jar
```

### Describe the bug

I am trying to connect my forge server to my paper server, but when I try to connect to my modded server via "/server modded", it says "If you wish to use IP forwarding, please enable it in your Bungeecord config as well!" I followed the Bungeecord/Waterfall guide and enabled IP forward in the Bungeecord config. Online mode in server.properties for both servers are set to false and enabled Bungeecord in global.conf. I'm not sure what I am doing wrong.

### Link to logs

Forge Server's server.properties: https://pastebin.com/MrxEvWZ4 Paper Server's server.properties: https://pastebin.com/6L5P5xDi Paper Server's spigot.yml: https://pastebin.com/vFbSmtuZ SpongeForge sponge.conf: https://pastebin.com/1Hk75c2c Waterfall config.yml: https://pastebin.com/KBPv5fh8

**Comment by Yeregorix** [comment]
AFAIK Forge 1.13+ is not compatible with proxies
See
https://github.com/PaperMC/Velocity/pull/690
https://github.com/PaperMC/Velocity/issues/248
https://github.com/PaperMC/Waterfall/issues/450

**Comment by MainBreezy** [comment]
Then I guess I'll just have to do without it
