### ISSUE TITLE
[spongeforge-1.16.5] incompatible mods

### ISSUE THREAD

**Issue by MochidsukiC** [SpongePowered/Sponge#3795]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.1.0-RC1235-universal

### Operating System

Windows

### Java Version

17.0.3.1

### Plugins/Mods

```shell
abnormals_core-1.16.5-3.3.1.jar
farmersrespite-1.16.5-1.1.jar
immersivecooking-1.2.0.jar
nethers_delight-2.1.jar
```

### Describe the bug

The above mods are not compatible with SpongeForge

**Comment by mosemister** [comment]
Abnormal core is known and has a fix: take a look at the official docs. 

https://docs.spongepowered.org/stable/en/server/spongineer/incompatible.html

More information about the other three would be useful

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
