### ISSUE TITLE
The server can't launch with Animal Bikes

### ISSUE THREAD

**Issue by Minecraftine** [SpongePowered/Sponge#3802]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.1.0-RC1256

### Operating System

Windows

### Java Version

JAVA 8 351

### Plugins/Mods

```shell
Animal Bikes
```

### Describe the bug

Animal Bikes is incompatible with Sponge Forge. The server can't run.

### Link to logs

https://gist.github.com/Minecraftine/29de6eb92064dfa678e8bb984d6c1103

**Comment by aromaa** [comment]
The mod adds a game rule which id has a blank space at the end. The mod developer should fix this.
