### ISSUE TITLE
The server can't launch with Valkyrien Skies (1.16.5)

### ISSUE THREAD

**Issue by Minecraftine** [SpongePowered/Sponge#3809]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.1.0-RC1256-universal

### Operating System

MacOS

### Java Version

Java 8

### Plugins/Mods

```shell
architectury-1.32.66
cloth-config-4.16.91-forge
eureka-1.0.0-alpha7
kotlinforforge-1.17.0-obf
spongeforge-1.16.5-36.2.5-8.1.0-RC1256-universal
valkyrienskies-116-2.0.0-alpha6
```

### Describe the bug

The server can't launch with Valkyrien Skies and its dependencies.

### Link to logs

https://gist.github.com/Minecraftine/2d5188b556352e6e4ea512c98cac38eb

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
