### ISSUE TITLE
[BUG] - Immersive Engineering - Duplicate Key

### ISSUE THREAD

**Issue by AnCasper** [SpongePowered/Sponge#3819]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1264 FORGE: 36.2.5

### Operating System

Linux Ubuntu 22.04 - Base

### Java Version

Tested - Java 8 & 11

### Plugins/Mods

```shell
Mods > All The Mods 6 Skyblock 1.0.7 Forge 46.2.33

Tried without plugins, same issue.
Plugins > LuckPerms-Sponge-5.4.58 and Nucleus-3.0.0-BETA7-MC1.16.5-SpongeAPI8.1-plugin
```

### Describe the bug

Not much to add, it worked once and has decided to not work again. Also tried moving a Single Player world to the server just in the off chance it would work. Nothing is in the "**DataPacks**" folder for the save/any save

If you need any more info feel free to ask away!

### Link to logs

https://paste.gg/p/anonymous/e0bab44d5d884d47b6d499f02fc0f905

**Comment by AnCasper** [comment]
Problem still persists in version: 1.16.5-36.2.5-8.1.0-RC1269 FORGE: 36.2.5

**Comment by AnCasper** [comment]
Problem still persists in version: 1.16.5-36.2.5-8.1.0-RC1276 FORGE: 36.2.5

**Comment by AnCasper** [comment]
Problem still persists in version: 1.16.5-36.2.5-8.1.0-RC1278 forge: 36.2.5

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
