### ISSUE TITLE
Joining the server crashes it

### ISSUE THREAD

**Issue by avaruus1** [SpongePowered/Sponge#3823]
### Affected Product(s)

SpongeVanilla

### Version

1.19.3-10.0.0-RC1274

### Operating System

Linux

### Java Version

18

### Plugins/Mods

```shell
None
```

### Describe the bug

It seems like the recent commits to API-10 broke something. The server crashes with no plugins installed when a player joins.

### Link to logs

https://gist.github.com/avaruus1/517b0d20d0d58af55317786f16d316c5

**Comment by ImMorpheus** [comment]
Should be fixed by https://github.com/SpongePowered/Sponge/pull/3824

Thanks for the report!
