### ISSUE TITLE
Latest Spongeforge Does Not Allow You To Talk To Pixelmon TCG NPCs - Kicks You

### ISSUE THREAD

**Issue by DecaNFT** [SpongePowered/Sponge#3828]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1278

### Operating System

Windows

### Java Version

Java 8 - jre1.8.0_361

### Plugins/Mods

```shell
Pixelmon, SpongeForge
```

### Describe the bug

I just found out that latest spongeforge version messes with the TCG NPC in pixelmon reforged 1.16.5. Using an older spongeforge I was able to get it to stop but it was kicking me from my server any time I tried to talk to the TCG NPC. Now it works fine since I started using the first 8.1.0 version of spongeforge rather than latest.

### Link to logs

https://paste.gg/p/anonymous/999bf6c69fa346c190bbe4c9c13ee676

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
