### ISSUE TITLE
Problems with Create mod

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/Sponge#3835]
### Affected Product(s)

SpongeForge

### Version

SpongeForge 1.16.5-RC1296

### Operating System

Win10

### Java Version

Oracle 1.8.0_361-b09

### Plugins/Mods

```shell
create-mc1.16.5_v0.3.2g.jar
flywheel-1.16-0.2.5
```

### Describe the bug

Rotational power is not correctly transferred in many cases. The connection between shafts and gearboxes fails vertically when they are placed. Bashing most things with a wrench seems to liven them up, but it's not intended behavior (i.e. it doesn't happen without SpongeForge present). 
Gearshifts (reversing rotational; direction) are completely insensitive to switches, and this really breaks things. I can't get the steam turbine to work either. Basically, something's broken with the way it updates the transmitted power in Create blocks. 
There was also an issue when placing cogs; Create shows a preview for placing them when you aim at another cog. This feature is broken, and the cogs end up misplaced. 
No relevant console errors were seen. Just a few ignored slot transactions when I got sawed in half.
On the bright side, water wheels and windmills definitely work now. Even the stress gauge yields data.

Server log file: [latest.log](https://github.com/SpongePowered/Sponge/files/11131327/latest.log)

**Comment by Inscrutable** [comment]
OK, the guts of this issue have been fixed in PR #3838. The only thing left is the weird cog positioning that results from using Create's "Placement Assist". 
Addendum: During testing I also noted that interaction with Create's wireless redstone links is broken. Normal behavior allows them to be visibly tagged with 2 items (to make a unique channel). They can't be tagged at all at the moment, so only the default wireless channel works.

**Comment by Yeregorix** [comment]
Fixed in #3844 and #3838
