### ISSUE TITLE
Incompatible with Frosted Heart (mod made for The Winter Rescue modpack)

### ISSUE THREAD

**Issue by drag0n1zed** [SpongePowered/Sponge#3846]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1312

### Operating System

OpenJDK Java 11 Docker Image

### Java Version

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8) OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

### Plugins/Mods

```shell
The entire "The Winter Rescue" Modpack
https://www.curseforge.com/minecraft/modpacks/the-winter-rescue
Mods:
https://legacy.curseforge.com/minecraft/modpacks/the-winter-rescue/relations/dependencies
Though I'm pretty sure it's this mod causing problems: https://legacy.curseforge.com/minecraft/mc-mods/frosted-heart
```

### Describe the bug

The server crashes when loading with the mod Frosted Heart.
The Github issue on their repository: https://github.com/TeamMoegMC/FrostedHeart/issues/33

### Link to logs

https://gist.github.com/SyuKoshiishi/65e4a4fcb5ba51c1e9be00aab4ed6e37

**Comment by drag0n1zed** [comment]
Link the forums page: https://forums.spongepowered.org/t/1-16-5-36-2-5-8-1-0-rc1312-java-lang-runtimeexception-java-lang-reflect-invocationtargetexception/41552

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
