### ISSUE TITLE
QuestAdditions Mixin Crash (InvalidInjectionException) 1.16.5

### ISSUE THREAD

**Issue by DrZoddiak** [SpongePowered/Sponge#3867]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1344

### Operating System

Windows 11

### Java Version

OpenJDK Runtime Environment Temurin-17+35 (build 17+35)

### Plugins/Mods

```shell
kruntime
ZoddJoin
spongeforge
architectury
ftb-library
ftb-teams
items-filters
ftb-quests
questadditions
```

### Describe the bug

When adding SpongeForge to the environment and creating a world the environment crashing with the logs linked below.

QuestAdditions is a side-mod for ftb-quests which depends on the other mods listed.
The only things unnecessary to reproduce are kruntime and Zoddjoin which are plugins.

[Crash-fml.txt](https://gist.github.com/DrZoddiak/203df7ed644ee3717d99d9a2b048c073)

[latest.log](https://gist.github.com/DrZoddiak/1362156c1c98f83613297b861c32678c)

debug.log linked below.

### Link to logs

https://gist.github.com/DrZoddiak/781760b84aa145a2e71bc2c0a77b2965

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
