### ISSUE TITLE
Players are being disconnected when they click on NPCs from pixelmon

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/Sponge#3871]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1352-universal

### Operating System

Linux

### Java Version

1.8.0_212/64-bit

### Plugins/Mods

```shell
Mods: pixelmon, BiomesOPlenty, BooshelfForge, chiselandhabits, WAWLA, costumes, ironchests, placebo, selene. clumps, fastfurnace, fastworkbench, ferritecore, notenoughcrashes, spark, starlight, storagedrawers, treechop, worldedit

Plugins: ChatManager, CommandPack, GTS, Impactor, LocaleAPI, LuckPerms, RegionGuard, TablistBoard
```

### Describe the bug

The video of the issue:
https://www.youtube.com/watch?v=Xkf1djfgDMU&t=1s&ab_channel=KonanMayer

When players click on TCG trader from pixelmon mod, they are being disconnected from the server. I have the same modpack on mohist server and there's no an issue like that. I made a request to fix that to pixelmon but they said it's sponge issue

### Link to logs

https://paste.anfanik.me/oyipapoqej.sql

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
