### ISSUE TITLE
Console flooding

### ISSUE THREAD

**Issue by PingvinchikPororo8814** [SpongePowered/Sponge#3877]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1352

### Operating System

Linux

### Java Version

Java 8

### Plugins/Mods

```shell
Plugins: LogFilter, TileEntityDropper, HopperLimiter, Impactor, LocaleAPI, RegionGuard, ChatManager, CommandPack, TablistBoard, ChestCommands, LuckPerms.

Mods: Smoothchunk mod, HT's TreeChop, Biomes 0' Plenty, Chunky, spark, Clumps, Fast Workbench, Placebo, Storage Drawers, DoesPotatoTick, SpongeAPI, Sponge, Bookshelf, WorldEdit, FastFurnace, Starlight, Ferrite Core, Costumes, Waila, WAWLA, Memory Leak Fix, Forge, SpongeForge, Auto Restart, Selene, Iron Chests, Pixelmon Mod, Pixelmon TCG, Client Reset Packet, ServerRedirect.
```

### Describe the bug

Console flooding, like this: https://paste.anfanik.me/ivuxageqik.md

### Link to logs

https://paste.anfanik.me/ivuxageqik.md

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
