### ISSUE TITLE
Sponge forge None existing forge version Server Crash

### ISSUE THREAD

**Issue by HowdyItsCurtis69** [SpongePowered/Sponge#3878]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.1.0-RC1352

### Operating System

Windows 10

### Java Version

8

### Plugins/Mods

```shell
This is the modpack and mod list for the pack that I want to add the sponge to so I can add x-ray prevention and shops. https://pastebin.com/E1R8whqw https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons-2
```

### Describe the bug

The forge version I am using is forge-1.16.5-36.2.39. When I go to the sponge page it says MINIMUM FORGE REQUIRED: 36.2.5 that version of forge does not exist Or I would update the modpack and server to this version of forge myself So I added sponge anyways and it is giving me this crash report for my server when it is launched. https://pastebin.com/7tQV2Sfy

### Link to logs

https://pastebin.com/7tQV2Sfy

**Comment by SettingDust** [comment]
https://github.com/SpongePowered/Sponge/issues/3795

**Comment by gabizou** [comment]
This is an already resolved issue, abnormals_core is the culprit and the fix is linked above.
