### ISSUE TITLE
JEI and SpongeForge cause Vanilla recipes and recipes for other mods using the vanilla crafting table to disappear.

### ISSUE THREAD

**Issue by Noel012020** [SpongePowered/Sponge#3894]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.2.0

### Operating System

Windows

### Java Version

openj9 1.8.0.345

### Plugins/Mods

```shell
jei-1.16.5-7.8.0.1009.jar (mod)
spongeforge-1.16.5-36.2.5-8.2.0-universal.jar (mod)
serverlistplus-3.5.1 (plugin)
```

### Describe the bug

When loading JEI and spongeforge in the minecraft version of 1.16.5, there is an error when checking the datapack list. Because of this error, when a client logons on to the server, they cannot see any crafting recipes in the crafting table or JEI gui. This is from the server point of view pack.mcmeta, unable to get pack info for it. Crafting is still possible; however, the recipe is invisible

### Link to logs

https://paste.gg/p/anonymous/27db6a4d9a244780a82ae7d80d27f974

**Comment by Noel012020** [comment]
Also, an additional note is that in the mods folder, the spongeforge mod is written as: aaa_spongeforge-1.16.5-36.2.5-8.2.0-universal.jar as stated to do on spongeforge website for known mod incompatibilties.

**Comment by Noel012020** [comment]
Also, an additional note, I run a significantly larger modpack then the one posted here; however, I was having the disappearing recipes in the crafting table, I decided to test and took out all the others mods while testing datapacks and came to this conclusion.

**Comment by AlexandreArcil** [comment]
Hello,
I tested on my side but the recipes are visibles as shown in the screenshots.

I didn't find serverlistplus version 3.5.1, only 3.5.0.
I tested with the original spongeforge plugin name and with the added `aaa_`.
Also, it's not errors but warnings.

Did I do something wrong ?

![image](https://github.com/SpongePowered/Sponge/assets/12583966/4021e1db-0fc7-4421-94b3-4076fce65882)
![image](https://github.com/SpongePowered/Sponge/assets/12583966/8c727647-16e1-4300-91c0-06336eb19510)
![image](https://github.com/SpongePowered/Sponge/assets/12583966/1c7bbaf6-6f8b-41fb-acd9-a28fbc1f77c8)

**Comment by Noel012020** [comment]
Hello, so right off the bat, I noticed there quite a few difference, one being that you have sponge api and sponge installed as plugin and the fact you have a different version of serverlistplus which I just found on ore the sponge platform. Another thing is are you using the jvm arguments I am using to start the server and are you forcing it to use a certain version of java like I am so it  does not just pick a general version. I will try adding sponge api and sponge to see if that helps the problem.

**Comment by Noel012020** [comment]
These are the arguments used: java -Xms11G -Xmx11G  -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=4 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:MaxGCPauseMillis=50 -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -XX:NewRatio=3 -jar forge-1.16.5-36.2.34.jar nogui
PAUSE

**Comment by Noel012020** [comment]
After more testing I found out that jei starting to work again with just spongeforge and jei, now i will start implenting all the other mods again to see if it is still problematic.

**Comment by Noel012020** [comment]
Alright, after a little more testing I found out that the mod that was breaking minecraft recipes with jei and spongeforge is the mod: tomes2.0.1 for minecraft version 1.16.5. It seems as the tomes mod is incompatible, can anyone test this to make sure this is true?

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
