### ISSUE TITLE
SpongePowered Mixin Crash Error - Unexpected Error in Modded Minecraft

### ISSUE THREAD

**Issue by SirTwsted** [SpongePowered/Sponge#3900]
### Affected Product(s)

SpongeForge

### Version

I don't know

### Operating System

Windows

### Java Version

version 20

### Plugins/Mods

```shell
Crash Log
https://pastebin.com/d6vEfE6J


Mods List Used
https://pastebin.com/p4qRpyUw
```

### Describe the bug

Log into the minecraft modded world and the game crashes.
I don't know what else to say or do.  🤷‍♀️

**Comment by zml2008** [comment]
Not sponge, looks like an issue with a coremod in the mod blue_skies

**Comment by SirTwsted** [comment]
Thats strange because when I disable the Blue Skies mod,  the error still happens.  🤷‍♀️
I am using CurseForge and installed Forge from CurseForge.  Sop I don't even know how Sponge even got installed.
As I have not directly installed it, unless Sponge is embedded within forge.  🤷‍♀️🤔

**Comment by zml2008** [comment]
You are not using sponge, forge provides Mixin (a library Sponge produces), which other mods then use to help transform the game's code. What is probably happening is another mod conflicts, which happens after the point where blue skies was causing a crash.

**Comment by SirTwsted** [comment]
I just disabled Optifine  and the game works fine.  
When I reactivate Optifine, I get the same error I just posted.  
Optifine version ( OptiFine_1.20.1_HD_U_I5.jar )

**Comment by zml2008** [comment]
Sounds like a mod conflict then.

**Comment by SirTwsted** [comment]
Ya, between Optifine and Sponge / Forge / Mixin.
I have going everywhere trying to fix this problem.  Its frustrating.

**Comment by zml2008** [comment]
well you'd get there faster if you stopped asking people who have no connection to the issue
