### ISSUE TITLE
IP-forwarding completely broken (both legacy & modern) on 1.20.2

### ISSUE THREAD

**Issue by avaruus1** [SpongePowered/Sponge#3905]
### Affected Product(s)

SpongeVanilla

### Version

1.20.2-11.0.0-RC1386

### Operating System

Linux

### Java Version

17.0.8.1/64-bit

### Plugins/Mods

```shell
-
```

### Describe the bug

IP-forwarding appears to be completely unusable on API-11. This is presumably due to the introduction of the configuration phase. The following exceptions are thrown when a player attempts to join to server when using it.

Legacy forwarding: https://gist.github.com/avaruus1/a23767136a1df965f9fcd18bd5b3f279

Modern: https://gist.github.com/avaruus1/f914cebbfdbc6dbe25fecce0042db2a7

**Comment by 4drian3d** [comment]
I get the same error when upgrading my SpongeVanilla 1.20.1 server to 1.20.2 using modern forwarding, the error occurs both when starting the server and when a player tries to log in

SpongeVanilla1.20.2-11.0.0-RC1423
