### ISSUE TITLE
ServerSideConnectionEvent.Auth called twice per login

### ISSUE THREAD

**Issue by avaruus1** [SpongePowered/Sponge#3907]
### Affected Product(s)

SpongeVanilla

### Version

1.20.2-11.0.0-RC1386

### Operating System

Linux

### Java Version

18.0.1/64-bit

### Plugins/Mods

```shell
-
```

### Describe the bug

`ServerSideConnectionEvent.Auth` is called twice per login.

**Comment by ImMorpheus** [comment]
PR merged
