### ISSUE TITLE
Container#type() is null

### ISSUE THREAD

**Issue by MrHell228** [SpongePowered/Sponge#3925]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.2.0

### Operating System

Windows

### Java Version

openjdk 11.0.2

### Plugins/Mods

```shell
-
```

### Describe the bug

When player click an item in his inventory (opens with 'E') _type_ in code below is null
```
@Listener
public void click(ClickContainerEvent e) {
	ContainerType type = e.inventory().type();
}
```

**Comment by pandier** [comment]
Yeah, there isn't a container type for player inventories. It would probably be better if the API returned an Optional.

**Comment by Faithcaio** [comment]
fixed in API12
