### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by PingvinchikPororo8814** [SpongePowered/Sponge#3927]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.2.1-RC1369

### Operating System

Linux

### Java Version

1.8.0_372

### Plugins/Mods

```shell
HT's TreeChop v0.14.6
Limited chunk loading mod v1.8
LogFilter v3.0.5
Clumps v6.0.0.28
ModernFix v5.4.2+mc1.16.5
Placebo v4.6.1
SpongeAPI v8.0.0
RedstoneAntilag v1.0.0-S8.0.0-RELEASE
Bookshelf v10.4.32
Starlight v1.0.0-RC2
Costumes v2.0.3
Impactor v4.0.0
Waila v1.10.11-B78_1.16.2
WAWLA v8.0.9
LocaleAPI v2.6.0-S8.0.0-RELEASE
CommandPack v1.4.0-8.1.0-RELEASE
ChestCommands v1.0.0-S8.0.0-RELEASE
Memory Leak Fix v1.0.0
LuckPerms v5.4.89
Forge v36.2.39
Auto Restart v2.0.0
Selene v1.16.5-1.0
Iron Chests v1.16.5-11.2.21
ServerRedirect v1.4.4a
Pixelmon TCG v9.1.9
Client Reset Packet v0.0.6
Pixelmon Mod v9.1.9
Serene Seasons v1.16.5-4.0.1.130
Minecraft v1.16.5
TileEntityDropper v1.0.0-S8.0.0-RELEASE
Smoothchunk mod v2.0
Sponge v8.0.0
HopperLimiter v1.0.0-S8.0.0-RELEASE
Biomes O' Plenty v1.16.5-13.1.0.488
Holographic Text v1.0-SNAPSHOT
Chunky v1.2.123
AntiClicker v1.0.2-S8.0.0-RELEASE
Fairy Lights v4.0.5
SpongeForge v1.16.5-36.2.5-8.1.0-RC1352
spark v1.9.1
Fast Workbench v4.6.2
AutoRegLib v1.6-49
Quark vr2.4-322
Storage Drawers v8.5.2
DoesPotatoTick v1.16.5-3.6.1
WorldEdit v7.2.5+57d5ac9
RegionGuard v1.8.2
ChatManager v1.0.2-S8.0.0-RELEASE
TablistBoard v1.2.0-S8.0.0-RELEASE
FastFurnace v4.5.0
Ferrite Core v2.1.1
AI-Improvements v0.4.0
chunksending mod v1.16.5-2.5
```

### Describe the bug

The server crashes a couple times a day. Reasons are not known. I attach logs and crash-log

[latest (9).log](https://github.com/SpongePowered/Sponge/files/13440665/latest.9.log)
[crash-2023-11-21_06.10.17-server.txt](https://github.com/SpongePowered/Sponge/files/13440667/crash-2023-11-21_06.10.17-server.txt)

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
