### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by Krxwn** [SpongePowered/Sponge#3944]
### Affected Product(s)

SpongeVanilla

### Version

1.20.2-11.0.0-RC1471 & 1.20.1-11.0.0-RC1365

### Operating System

Linux (Debian 11)

### Java Version

17

### Plugins/Mods

```shell
nothing
```

### Describe the bug

Hello, I've been trying for a while to upgrade a vanilla minecraft server to spongevanilla, the server starts without any problem, the problem comes when any player tries to join it in 1.20.1, it says the following error; "invalid player data", and in 1.20.2 the server only displays "Disconnected". The world already existing.

### Link to logs

https://paste.gg/p/anonymous/8e6b3a26497c42e8b0302f78b895ae78

**Comment by gabizou** [comment]
This was fixed a while back, must've not gotten associated with the commit in particular.
