### ISSUE TITLE
Can't import vanilla server to spongevanilla

### ISSUE THREAD

**Issue by Krxwn** [SpongePowered/Sponge#3945]
### Is this request specific to one implementation of Sponge?

Yes, only SpongeVanilla

### Sponge Version

1.20.2-11.0.0-RC1471 & 1.20.1-11.0.0-RC1365

### What are you requesting?

Hello, I've been trying for a while to upgrade a vanilla minecraft server to spongevanilla, the server starts without any problem, the problem comes when any player tries to join it in 1.20.1, it says the following error; "invalid player data", and in 1.20.2 the server only displays "Disconnected". The world already exist, attached is the "latest.log" where two players tried to connect to the server.
[latest.log](https://github.com/SpongePowered/Sponge/files/14290642/latest.log)

**Comment by Krxwn** [comment]
I've only just noticed this, but when looking for the UUID files of both players, in the latest I've published on paste.gg, both players log in with the same UUID, so I'm going to publish the player data in question... (I probably read the logs wrong, sorry 😅)

Edit: it work without the resourcepack
[e5188603-6028-4f0f-a3db-5a2c599fc52d.zip](https://github.com/SpongePowered/Sponge/files/14296190/e5188603-6028-4f0f-a3db-5a2c599fc52d.zip)

**Comment by aromaa** [comment]
Closing as fixed by 4eb91dd
