### ISSUE TITLE
Crash when saving game on 1.20.6

### ISSUE THREAD

**Issue by SamB440** [SpongePowered/Sponge#4015]
### Affected Product(s)

SpongeVanilla

### Version

1.20.6-11.0.0-RC1607

### Operating System

Windows

### Java Version

21

### Plugins/Mods

```shell
SpongeTestPlugin v1.0.0
```

### Describe the bug

The server will crash when saving the game when an objective is registered.

Use the following code in a plugin:
```java
final Scoreboard scoreboard = Sponge.server().serverScoreboard().orElseThrow();
Objective objective = Objective.builder().name("sponge-test").criterion(Criteria.DUMMY).displayName(Component.text("Tickets Left", NamedTextColor.YELLOW, TextDecoration.BOLD)).build();
scoreboard.addObjective(objective);
scoreboard.updateDisplaySlot(objective, DisplaySlots.SIDEBAR);
```

Then run `/save-all`.

### Link to logs

https://pastes.dev/duEalnnKe4

**Comment by aromaa** [comment]
Fixes in 63200e2.
