### ISSUE TITLE
ItemStack serialization/deserialization is broken

### ISSUE THREAD

**Issue by SamB440** [SpongePowered/Sponge#4016]
### Affected Product(s)

SpongeVanilla

### Version

1.20.6-11.0.0-RC1614

### Operating System

Windows

### Java Version

21

### Plugins/Mods

```shell
SpongeTestPlugin
```

### Describe the bug

As discussed on Discord (https://discord.com/channels/142425412096491520/539537645152239626/1242538551543857302 + https://discord.com/channels/142425412096491520/142425521391665153/1242523722959818894), itemstack deserialization/serialization is broken since 1.20.6.

Using the following code, the problem can be tested: https://pastes.dev/BXy6dkluam

This will yield: https://pastes.dev/wIaBeyiRzE

On 1.20.4 this succeeds without error.

The items should deserialize as:
![image](https://github.com/SpongePowered/Sponge/assets/11319274/180ae402-03d0-4d81-8dfb-5a5ea0350757)

**Comment by Faithcaio** [comment]
fixed in https://github.com/SpongePowered/Sponge/commit/2061a453986b89f58966748297a59fb54fc46577
