### ISSUE TITLE
SpongeForge for Minecraft 1.20.1

### ISSUE THREAD

**Issue by ConstasJ** [SpongePowered/Sponge#4028]
### Is this request specific to one implementation of Sponge?

Yes, only SpongeForge

### Sponge Version

1.20.1

### What are you requesting?

As 1.20.1 has became another major Minecraft version for MinecraftForge mods, if SpongeForge can support 1.20.1, it will be very nice for mod server host like me.
Is it possible for SpongeForge to add support for Minecraft 1.20.1?

**Comment by McSnurtle** [comment]
Please!!!
