### ISSUE TITLE
ResolutionException on neo forge.

### ISSUE THREAD

**Issue by Imitater967** [SpongePowered/Sponge#4153]
### Affected Product(s)

SpongeForge

### Version

spongeneo-1.21.3-21.3.0-beta-13.0.0-RC1926-universal 

### Operating System

windows

### Java Version

22

### Plugins/Mods

```shell
only sponge
```

### Describe the bug

![image](https://github.com/user-attachments/assets/78652dc3-5cbc-4cd3-b0d6-3c5d68988f8f)

**Comment by gabizou** [comment]
Investigating this further, one of our dependencies is getting bundled in Neo: `com.fasterxml.jackson.core:jackson-core` and because it's being bundled, and we simultaneously shadow it in the jar, Java Module System is correctly asserting the problem.

**Comment by gabizou** [comment]
Fixed with `1.21.3-21.3.35-beta-13.0.0-RC1957`, available on the [Downloads Page](https://spongepowered.org/downloads/spongeneo?minecraft=1.21.3&offset=0). Note that this has been tested on the latest NeoForge at the time of writing: 21.3.58
