### ISSUE TITLE
KeepInv + Sponge 1.10.2 - 5.0.0-BETA-1808

### ISSUE THREAD

**Issue by Solidflip** [SpongePowered/Sponge#982]
Players who die keep their inventory even when Gamerule KeepInv is set to false. This happens in all worlds and with no mods/plugins or with them as well.

Saw a guy on the forums with the same problem that wasnt resolved: https://forums.spongepowered.org/t/items-kept-on-death/14436

I ran into this issue with a modpack installed and a few plugins, as well as when i removed all of that and just ran vanilla with sponge. 

Per gabizou on the IRC im attaching my world file and sponge/forge config.

Sponge Version: 1.10.2 - 5.0.0 - BETA - 1808
Forge Version: 2098
World: https://www.dropbox.com/s/fpx4ifftrvnsmvv/world.zip?dl=0
Configs: https://www.dropbox.com/s/mluj6k0k6kkfvc5/Configs.zip?dl=0

(i added only the forge/sponge configs as thats where the issue is, the problem occured with just vanilla)

**Comment by AlphaWolf21** [comment]
Having the exact same issue, a release to fix this would be great!

**Comment by Aaron1011** [comment]
@AlphaWolf21: Are you able to reproduce this on a fresh world, with fresh Sponge configs? I haven't been able to do so locally.

**Comment by AlphaWolf21** [comment]
I have, i am running on a dedicated server using OVH, and the problem only occurs when sponge is installed, i have tried to create a server on my local pc and try and the same problem persists. I am using spongeforge, this probably goes under spongeforge but i found this issue open and continued it instead of making a new one.

**Comment by Zidane** [comment]
I believe this was fixed in: https://github.com/SpongePowered/SpongeForge/commit/6016383ff0570c74d81e3b32b5e3434fac9c2ab9
