### ISSUE TITLE
Shields and banners

### ISSUE THREAD

**Issue by TheRedCoderGit** [SpongePowered/Sponge#984]
Shields should have the same data (color, patterns, etc).
Trying to create a black banner is rather simple:
ItemStack banner = builder.itemType(ItemTypes.BANNER).build();
banner.offer(Keys.BANNER_BASE_COLOR, DyeColors.BLACK);
it works, however, if i change the item type to shild, it doesn't work

**Comment by gabizou** [comment]
The problem is the Data implementation hasn't been updated to support shields yet (they were most all written during the 1.8 period, so updating for new features isn't terribly difficult). Thanks for pointing it out!

**Comment by Feeliiix** [comment]
Working on it.

**Comment by parlough** [comment]
@gabizou Wasn't this completed in https://github.com/SpongePowered/SpongeCommon/commit/ca47c86 and https://github.com/SpongePowered/SpongeCommon/commit/78365a7?

**Comment by JBYoshi** [comment]
Looks like it was.
