### ISSUE TITLE
Adding custom data to ItemStacks does not work as expected

### ISSUE THREAD

**Issue by ZephireNZ** [SpongePowered/Sponge#985]
Someone on IRC had an issue with a custom value being applied to an ItemStack returing FAILURE but without mentioning the values that failed in the `DataTransactionResult`.

@simon816 pointed out the issues lies here: https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/item/MixinItemStack.java#L399

ItemStack does not fully implement the spec, returning `DataTransactionResult.failNoData()` instead of `failResult()`

**Comment by ZephireNZ** [comment]
@gabizou

**Comment by Zidane** [comment]
@ZephireNZ 

Could you submit us a PR as a fix?

**Comment by ImMorpheus** [comment]
I'm able to reproduce this on stable-7 (updated to https://github.com/SpongePowered/SpongeCommon/commit/f082f78f9548d16f1c184302290202df92c1dce0)

Code:

```
ItemStack.of(ItemTypes.SPONGE, 1).createSnapshot().createStack()
        .offer(MyHomes.FRIENDS, Arrays.asList(UUID.randomUUID(), UUID.randomUUID()));
```

You can put that in a custom testplugin (MyHomes.FRIENDS is part of the myhomes testplugin)
