### ISSUE TITLE
SpongeParticleHelper error

### ISSUE THREAD

**Issue by trentech** [SpongePowered/Sponge#987]
http://pastebin.com/DTHtWwt2

I think this error is related to this

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/effect/particle/SpongeParticleHelper.java#L123

**Comment by Cybermaxke** [comment]
This is a duplicate issue of SpongePowered/SpongeVanilla#275 and will be fixed with #986
