### ISSUE TITLE
Entity removal of Player doesn't kick

### ISSUE THREAD

**Issue by FerusGrim** [SpongePowered/Sponge#989]
Currently when a Player is removed (`Entity#remove()`), they just exist in some kind of weird state where they can't interact with anything, and updates are no longer sent to them (outside of the time).

My suggestion is that `Player` override `remove()` and re-direct it to whatever handles kicking a player.

/shrug

https://forums.spongepowered.org/t/entity-removal-help/15336

**Comment by ryantheleach** [comment]
It shouldn't kick. 
What it does isn't surprising, because it removes the player from the worlds trackers. 
I can't really see a usecase for it even being exposed to plugins however, since remove would be internally handled on log out, or on world change...

There is probably some esoteric use for it though.

**Comment by axle2005** [comment]
Its really not hard to exclude once you realize its a thing. Upon figured out this was my issue, I just prevented "minecraft:player" from being affected by any of my code anyway.

**Comment by octylFractal** [comment]
Entity removal shouldn't kick because that's not what happens in vanilla. In vanilla, when you die (your entity is removed) you are simply respawned. If anything is changed, that might be the best option.

**Comment by simon816** [comment]
I think it should throw an `IllegalStateException` if you try to remove a player.

Edit: `UnsupportedOperationException` makes more sense here

**Comment by JayPeaSize** [comment]
Why would it throw an exception? You can do it in vanilla, no need to prevent it. Nor should it be a kick. In any platform, bukkit, forge etc. Its always just allowed you to do it. Its nothing new. Just skip it when itterating through if you need to.

**Comment by Zidane** [comment]
@Rhonim 

The remove function in Vanilla is an internal method. It actually needs to put you through the death process if remove is allowed to affect a Player. In Sponge, your EntityPlayerMP entity is never re-created.

**Comment by ryantheleach** [comment]
Adding on to this issue, I just attempted to remove an entity from a world in a Single Player Dev environment.

What ended up happening is the entity froze and stopped responding, presumably because it was removed on the server side and updates were never sent to the clients.

**Comment by gabizou** [comment]
Looking back at this issue, I feel like we should override and throw an `UnsupportedOperationException` for players with regards to removal, since it specifically applies to players, it's something that I'd not want to have to deal with re-synchronizing the player entity and dealing with issues otherwise.

**Comment by ryantheleach** [comment]
There appears to be some contention on the way to resolve this.

What is the best way to resolve people disagreeing on the best method to solve this?

I'm looking for more input on a definitive way that this should be handled, so that a volunteer can potentially fix this.

**Comment by Zidane** [comment]
What @gabizou said fits here.

Someone PR a throw of an exception here and move on.
