### ISSUE TITLE
Support for firing Sponge events that quack like Forge events

### ISSUE THREAD

**Issue by sk89q** [SpongePowered/Sponge#99]
Currently we have no way to fire Sponge events in a way that also activates handlers listening to the equivalent Forge event. For example, the "PlayerBreakBlockEvent" has an equivalent in Forge and so it should trigger both Forge and Sponge event handlers.

Requirements:

* The event handlers must called in the right order, interweaving Sponge and Forge event handlers.
* Raising the Forge event must also raise the Sponge-equivalent event.
* Raising the Sponge event must also raise the Forge-equivalent event.
* It should be possible for developers to extend Sponge events and raise them, while also raising equivalent Forge events if relevant.

The following solutions have been on the table for the past few months, but none are satisfactory:

* Generate monolithic classes at runtime that implement both the Sponge and Forge event interfaces (as Forge intends to switch to interfaces for events). This has the downside of runtime conflict involving method signatures.
* Modify the event bus code to handle firing "paired" events. Firing the Sponge event would, for example, also trigger the equivalent Forge event handlers who would receive a Forge event version of the Sponge event.

**Comment by Zidane** [comment]
@sk89q @bloodmc 

From what I can tell, this has been solved? Can we close this issue?
