### ISSUE TITLE
CustomInventory capacities are broken

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#990]
A custom inventory created with archetype `CHEST` will not accept items inserted into slots greater than ordinal `26` (the max slot in a single-chest), regardless of actual capacity (set via the `InventoryDimension` property). Futhermore, attempting to create an inventory of this archetype with fewer than 27 slots will result in an `IndexOutOfBoundsException` upon calling `build`. [Stack trace](https://gist.github.com/caseif/d63995ecf3498cf81ea0918c5a389752).

I have replicated this behavior on both SpongeVanilla and SpongeForge, with no observed differences between the platforms.

**Comment by Dockter** [comment]
I sense some hard coded values somewhere...

**Comment by caseif** [comment]
I'd say it's probably getting tripped up on some validation code within MInecraft or something.

**Comment by kashike** [comment]
@Faithcaio
