### ISSUE TITLE
Chunk Generator in Sponge does not seem to read from the current regions?

### ISSUE THREAD

**Issue by StoneLegion** [SpongePowered/Sponge#992]
I'm quite new to this stuff but I used to plugins so far nucleus and one I like better with more settings projectborders.

The issue here is if you stop or sadly crash with any of these it does not seem to read from the world/regions so it has to generate from scratch. Of course it does not chunk generate but it has to open 1000's of chunks all over again before it gets to new chunks/regions to continue to generate. 

Because of memory leaks, bugs, crashes, etc this means for someone creating a massive world it might actually be impossible to generate an entire world with this current method.

**Comment by gabizou** [comment]
@KaneHart The problem would only arise in any case if the region is not _saved_ before the crash. If the server hasn't had a chance to save to disk the already generated chunks, then none of it will persist between a crash and restart.

**Comment by inklit** [comment]
I tested this on 1.8.9 and can say that it is definitely going through every chunk from the beginning and reading them before actually generating anything.

When you stop the server and start the generator again, it will start from the beginning even though it should start where the last region leaves off instead of the beginning.

**Comment by StoneLegion** [comment]
1.10.2 Here and I know for a fact it's going through from the start again as well. I'm actually watching it happen live. I have region files up into the 50's and I'm in the 20's right now slowly going through them. My file size of course also has not changed for over 20%.

If I stop it will do it all over again and again sadly.

**Comment by StoneLegion** [comment]
Just crashed here is a prime example:

I have 130 regions and starting again with any of these mods I sadly start all the way from the start as you can see from this (last modified)

https://i.imgur.com/kb2tZIj.png

**Comment by bloodmc** [comment]
@DDoS Please look into this issue.

**Comment by DDoS** [comment]
Just as an update, I'm really busy right now finishing my university semester, but I should have time to work on this later this month. I'm considering one of two solutions:

- Find a way to check which chunks are generated by doing a few as possible file system operations
- Add functionality to let the plugin know which chunks have been generated, and tell the pre-generator which chunks should be skipped. Tracking and skipping of already generated chunks would then be the responsibility of the plugin

I'm leaning towards the first, although it might be quite complicated to implement.

**Comment by Deamon5550** [comment]
You should only have to open up each region file and read the first 8KB from the start of them which contains the information on what chunks are present in the the region file.
