### ISSUE TITLE
Canceling collect to cursor causes items to disappear

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/Sponge#993]
http://i.imgur.com/uTH8wIc.png
-> DoubleClick on the 63 Stack
-> Let First Event (picking up the stack) go trough
-> Items get collected on cursor (removes 1 item from the other inventory)
-> Cancel Event 
-> Resets ItemStack on cursor but not the Top Inventory
http://i.imgur.com/o1AUOgl.png

@bloodmc you did fix #974, this might be related

**Comment by Faithcaio** [comment]
This is still happing.
Test-Listener:
http://pastie.org/private/isuzttynmcyungn4w8xp2q

**Comment by bloodmc** [comment]
@Faithcaio OK thanks, i'll take a look soon.
