### ISSUE TITLE
Inventory Issue

### ISSUE THREAD

**Issue by Proxying** [SpongePowered/Sponge#997]
Within Spigot, a popular form of GUI's were the form that could be navigated by a player (as they clicked on one item, it opened another GUI, etc etc.) now that Sponge has a base Inventory API setup, something similar should be possible soon, which would bring Sponge into a better state for developers to use. However, I've came across this issue, upon opening another inventory via the ClickInventoryEvent, an issue occurs in which whatever item you clicked is added/replaces the item within the new inventory. Example of the code and a gif of the issue are below.

Item is still replaced http://i.imgur.com/PUkoOIK.gifv
Running this code; http://i.imgur.com/3YuEzEM.png

So the first item should be a golden apple, as it's being offered to the custom inventory upon creation, but the item that was clicked previously (beef) has replaced it.

This has been tested on the latest version of SpongeForge at this time (1832). Since the inventory transactions are handled via code in SpongeCommon, this seemed the more suitable place to report it.

**Comment by ryantheleach** [comment]
Please don't screenshot code unless you are trying to show highlighting errors and need support. It makes it a lot harder to reproduce the error as opposed to just pasting in a section of the code as text, or using a gist.
