### ISSUE TITLE
Calling setBlock does not fire any ChangeBlockEvents

### ISSUE THREAD

**Issue by simon816** [SpongePowered/Sponge#998]
Simple listener

``` java
     @Listener
     public void onBlockChange(ChangeBlockEvent e) {
         System.out.println(e);
     }

```

Calling `World#setBlock` from command handler or interact event (and probably anywhere) does not fire a `ChangeBlockEvent`
Using spongeforge bleeding https://github.com/SpongePowered/SpongeForge/commit/ec945eedf4752f052f104c6c0d006f63865be1f3
This essential feature worked fine on 1.8.9

Also, it looks like `ChangeBlockEvent.Post` is fired when a player places/breaks a block which contradicts the specification

> ```
> * <p>The idea is that  a block, entity, or tile entity "ticks" in which
>  * during that "tick", they make different types of block changes. If the
>  * block change is purely one type then the corresponding event is thrown
>  * instead. For example, If the block change is purely "placing" of
>  * blocks, the {@link Place} event would be thrown instead.</p>
> ```

**Comment by Zidane** [comment]
@simon816 

Need your code for calling setBlock. Paste your listener.

**Comment by simon816** [comment]
@Zidane OK here's a minimal example. It will break the block beneth you when running `/testcmd`

``` java
    @Listener
    public void onBlockChange(ChangeBlockEvent e) {
        System.out.println(e);
    }

    @Listener
    public void onPreInit(GamePreInitializationEvent event) {
        Sponge.getCommandManager().register(this, CommandSpec.builder().executor((src, args) -> {
            if (src instanceof Player) {
                ((Player) src).getLocation().sub(0, 1, 0).setBlock(BlockTypes.AIR.getDefaultState(),
                        Cause.source(Sponge.getPluginManager().fromInstance(this).get()).build());
            }
            return CommandResult.success();
        }).build(), "testcmd");
    }
```

**Comment by gabizou** [comment]
Pretty sure that this is now fixed since Causes refactor.
