### ISSUE TITLE
DestructEntityEvent does not fire for non-living entities

### ISSUE THREAD

**Issue by simon816** [SpongePowered/Sponge#999]
Listener:

``` java
    @Listener
    public void onEntityDestruct(DestructEntityEvent event) {
        System.out.println(event);
    }
```

Example: drop sand from a height. The fallingsand entity dies but never fires the event.
This worked fine in 1.8.9

**Comment by gabizou** [comment]
Is this still an issue? I distinctly remember there being a commit attempting to fix this.

**Comment by simon816** [comment]
Just tested this on latest bleeding (SpongePowered/SpongeForge@55d753c8d21dcd6ee4c4f6754de0e4e7e93a225c), still no event fired when the falling sand entity turns into sand block

**Comment by Eufranio** [comment]
Using latest SpongeForge (API6, 1.11.2) and still no event.

**Comment by parlough** [comment]
Will be solved by https://github.com/SpongePowered/SpongeCommon/pull/1157

**Comment by ImMorpheus** [comment]
PR  merged
